### ISSUE TITLE
Settings display incorrectly on first open

### ISSUE THREAD

**Issue by corobin** [uBlockOrigin/uBlock-issues#1669] opened 2021-07-27 04:46 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

On Android Firefox, when opening the uB0 settings page for the 1st time after not recently opening it, on first load it shows the default settings instead of the user-configured settings. It displays the correct settings upon refreshing the page.

### A specific URL where the issue occurs

not a web page issue

### Steps to Reproduce

1. launch Firefox
2. Kebab menu -> "Add-ons"
3. press uB0 item (if uB0 is not already installed, install it)
4. "Settings"
5. you should now be on the uB0 settings page on the "Settings" tab
6. change the settings, for this example: uncheck every checkbox
7. exit Firefox
8. restart phone (I do not think that this is required, but I found this is the most reliable way to reproduce the issue quickly)
9. repeat steps 1-4

### Expected behavior

it should display the settings page showing the user's configuration

e.g. no boxes checked

### Actual behavior

it shows the default settings configuration

e.g. the default boxes checked

And then, if you now refresh the page, it will now show the user's configuration

### uBlock Origin version

reproduced on 1.37 (and also 1.36.x versions that i can remember)

### Browser name and version

Firefox 90.1.2

### Operating System and version

tested on both Android 11 and Android 9

**Comment by gorhill** [comment] 2021-07-30 12:01
I can also reproduce this in desktop Firefox and Chromium. The issue is that the browser loads the extension page before uBO's background process is loaded, so that the extension page is unable to connect to it to get the information needed to make the extension page reflect the actual settings.

In Chromium, at the extension page console, I get:

    Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

**Comment by uBlock-user** [comment] 2021-07-30 12:34
> Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

This was reported on reddit several times in the past year whenever a user reported uBO to be broken and not blocking any ads on Chromium.

**Comment by gorhill** [comment] 2021-07-30 12:35
This affects only the dashboard or other such auxiliary pages, not the uBO's process itself. Having the browser open extension pages at launch before the extension process is ready has always been an issue.

**Comment by gorhill** [comment] 2023-07-14 11:51
This was fixed in [1.48.0](https://github.com/gorhill/uBlock/releases/tag/1.48.0) with <https://github.com/gorhill/uBlock/commit/5c92d95143b07aaee6f04a41db6e0a3e9a55db06>.

**Closed by gorhill** 2023-07-14 11:51 UTC
Labels: bug
