### ISSUE TITLE
Broken page saving (ctrl-s)

### ISSUE THREAD

**Issue by anedroid** [uBlockOrigin/uBlock-issues#3176] opened 2024-03-19 17:58 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

While page saving downloads all the required resourced, URLs doesn't get changed to point to local file, as browser does by default.

### A specific URL where the issue occurs.

```yaml
https://mermaid.js.org/syntax/flowchart.html
```

### Steps to Reproduce

1. Open a page
2. Press ctrl-s
3. Choose "complete webpage"
4. Open the downloaded file

### Expected behavior

You should see how the page was looking like at the moment of saving.

### Actual behavior

Opened page lack styles, fonts, some images, etc.

### uBO version

1.56.0

### Browser name and version

Firefox 123.0.1

### Operating System and version

Fedora Linux 39 (Cinnamon) x86_64

**Comment by gorhill** [comment] 2024-03-19 19:45
Unable to reproduce using default settings/lists.

**Comment by gwarser** [comment] 2024-03-19 20:45
```
+0
/script.tagged-events.outbound-links.js
--
mermaid.js.org
0,3
get
script
https://p.mermaid.live/js/script.tagged-events.outbound-links.js
```

Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/986 ?

**Comment by gwarser** [comment] 2024-03-19 20:50
Ah! Page is broken when you retry, because then only main html is saved (that's why it succeeds).

**Comment by gorhill** [comment] 2024-03-19 22:06
> when you retry

I can reproduce after clicking the retry button.

I can also reproduce similar issue of improper saving without uBO, after setting Firefox Enhanced Tracking Protection to _Strict_ for this webpage: `https://resobscura.substack.com/p/he-spoke-of-computers-with-some-awe`. Seems to work at first, but an error is reported and clicking the retry button causes an improperly saved webpage.

Closing as a browser issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1445211>.

**Closed by gorhill** 2024-03-19 22:06 UTC
Labels: unable to reproduce
