### ISSUE TITLE
dobreprogramy.pl: breakage

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#2448] opened 2023-01-06 12:47 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other [similarly-purposed blockers](https://twitter.com/gorhill/status/1033706103782170625).
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.dobreprogramy.pl/skuteczny-sposob-na-telemarketerow-juz-wiecej-nie-zadzwonia,6852610894154688a`

### Category

breakage

### Description

`www.dobreprogramy.pl##script:-abp-contains(slotNumber):upward(2)` filter from "POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda" is hiding the body.

What is puzzling - I cannot find any `script` with `slotNumber` two branches down the `body`.

Actually, this seems to be the `html` what is hidden!? uBO glitch?

Can someone reproduce?

@krystian3w ?

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_20230106_131041](https://user-images.githubusercontent.com/886325/211011053-1276a8fa-5163-4090-af69-efe67a509c5c.png)
![Screenshot_20230106_131129](https://user-images.githubusercontent.com/886325/211011062-b998ee3c-c145-48ba-b35c-fd03cf3a99d8.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.46.1b6
Firefox: 110
filterset (summary): 
  network: 85242
  cosmetic: 46252
  scriptlet: 16978
  html: 875
listset (total-discarded, last-updated): 
  added: 
    POL-0: 7881-25, 1m
    POL-2: 1279-12, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32382-91, 1m
    ublock-badware: 4250-0, 1m
    ublock-privacy: 305-0, 1m
    ublock-abuse: 77-0, 1m
    ublock-unbreak: 1928-3, now
    ublock-quick-fixes: 458-0, now
    easylist: 61678-643, now
    easyprivacy: 30884-1738, now
    urlhaus-1: 7241-0, now
    plowe-0: 3669-2, now
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 838 ms
  maxAssetCacheWait: 298 ms
```
</details>

**Comment by gorhill** [comment] 2023-01-06 15:08
Note that the filter in POL list still needs to be fixed, as it will now be dropped. ABP syntax for pseudoclass operators requires the use of `#?#`, and uBO enforces this by considering the filter invalid when using an `-apb-` operator without `#?#`. Since the filter uses uBO-specific `upward()`, the filter should just use `has-text()`, there is no point using `-abp-` syntax with uBO-specific operators.

**Comment by gorhill** [comment] 2023-01-06 15:09
CLosing as duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2442>.

**Closed by gorhill** 2023-01-06 15:09 UTC
Labels: duplicate
