### ISSUE TITLE
Remember temporarily whitelisted sites after updates

### ISSUE THREAD

**Issue by cae3uax** [uBlockOrigin/uBlock-issues#717] opened 2019-09-03 04:49 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

If dynamic filtering is used and uBlock Origin is updated while various sites are temporarily whitelisted, these sites are no longer temporarily whitelisted after the update. For long running browser sessions with many tabs open and multiple projects going on, this is quite annoying.

A fix is of course to disallow automatic updates under the uBlock Origin extension settings, but I will then probably forget about checking for updates manually and I like the updating to take care of itself.

I don't know if it can be done at all, but a nice enhancement is if uBlock Origin would not forget about the temporarily allowed stuff after an update.

Just to be clear, I **temporarily** allow some sites, because I don't want to permanently whitelist them.  After the update, the sites should still just be **temporarily** whitelisted.

### A specific URL where the issue occurs

https://www.google.com/

### Steps to Reproduce

1. Enable dynamic filtering and temporarily whitelist a site.
2. Wait for  uBlock Origin to update to a newer version.

### Expected behavior:

uBlock Origin will still remember the temporarily whitelisted site after the update.

### Actual behavior:

uBlock Origin does no longer remember the temporarily whitelisted site after the update.

### Your environment

* uBlock Origin version: 1.22
* Browser Name and version: Mozilla Firefox 68.0.2

**Comment by gwarser** [comment] 2019-09-03 07:48
Probably implemented in Fx by this: https://bugzilla.mozilla.org/show_bug.cgi?id=1279012

**Comment by uBlock-user** [comment] 2019-09-03 13:19
When any extension updates the browser reloads the extension entirely that's the same as closing and browser and opening again, so unsaved settings are lost. This is not an issue fyi.

**Comment by gorhill** [comment] 2019-09-03 13:21
As pointed out by @gwarser, uBO can prevent the reload by registering a `onUpdateAvailable()` listener.

**Comment by uBlock-user** [comment] 2019-09-03 13:24
Is that available for Chromium too ?

**Comment by gwarser** [comment] 2019-09-03 18:22
This was available in Chrome 25:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/reload#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onUpdateAvailable#Browser_compatibility

No idea why I was watching this bug. And it is 3 years old ??? Fx 51? It seemed to me it was more recent.

**Closed** 2019-09-06 12:54 UTC
Labels: enhancement

**Comment by gwarser** [comment] 2019-09-06 16:25
I think this prevents downgrading. I need to disable uBO to downgrade.

Does not prevent update when checking manually (good?).

Will go back to b1 and wait for auto update.

Side note: can we have rule to not set fixed label if not tested? Or maybe you tested this already @uBlock-user?

**Comment by gorhill** [comment] 2019-09-06 16:35
> I need to disable uBO to downgrade.

That's an unavoidable side effect, acceptable given that restarting uBO mid-session can cause loss of settings for majority of users. Those testing uBO will have to accept to deal with the manual reload step.

**Comment by gorhill** [comment] 2019-09-06 16:47
I could force a reload if the version number is lower than the current version -- the assumption would be that cases of downgrading are always done manually and hence it's safe to reload the extension.

**Comment by uBlock-user** [comment] 2019-09-06 17:20
@gwarser I couldn't test it because the commit is only added, there was no release. I couldn't even if I wanted to. Now coming to the point of adding the fixed label or not, you closed it, so I added the label believing you tested it. I didn't close it even though the commit was added 2 days ago because there was no updated release in the release section.

**Comment by uBlock-user** [comment] 2019-09-06 17:26
I usually never test because I believe gorhill would only add a commit after testing and I don't like to second guess him. But we can have a rule if you believe so ? 

@gwarser

**Comment by gorhill** [comment] 2019-09-06 17:32
> I don't like to second guess him

Errr.. what? I do actually hope other are helping testing changes, asking me to cover all cases is unrealistic. My understanding of the "fixed" label was that the fix was confirmed to be working as intended.

**Comment by gwarser** [comment] 2019-09-06 17:32
Ah, ok. So I will not close if not really complete or without chance to test. (I just wanted to remove it from "the queue" as "taken care of already").

No second guessing, just accidental breakage, typos, errors in transmission etc.  ;)

**Comment by uBlock-user** [comment] 2019-09-06 17:34
> Errr.. what?

I meant what I said. I'm not testing each and every bug you fix, otherwise that would mean I'm second guessing you. I do test and report back if I see something unusual from time to time.

**Comment by gwarser** [comment] 2019-09-06 17:35
>My understanding of the "fixed" label was that the fix was confirmed by someone else than me to be working as intended.

I do this.

**Comment by uBlock-user** [comment] 2019-09-06 17:38
Well my understanding was based on the bugs listed under "Closed as fixed" in release section must have been fixed, so I add the label to reflect that.

**Comment by gorhill** [comment] 2019-09-06 17:40
> bugs listed under _"Closed as fixed"_ in release section

Those items are just so that I keep track of what will be in the release notes in the next stable release, but they are not to be read literally for the dev builds.

**Comment by uBlock-user** [comment] 2019-09-06 17:42
Good to have been clarified now, we never talked about this before anytime.

**Comment by gwarser** [comment] 2019-09-06 17:43
I was thinking about another label - "confirmed"(?) - but this will add too much noise.

Also sharing thoughts about change is not bad. It doesn't have to be a bug, just different point of view. Sometimes people may see things differently.

**Comment by uBlock-user** [comment] 2019-09-06 17:46
gorhill doesn't put "fix" in commit messages anymore, so test it manually whoever can and then close it ?

**Comment by gwarser** [comment] 2019-09-08 12:25
Downgrading works fine (by drag&drop). I was wrong about manual check for update - I cannot make it to update this way. Updating by browser restart works.

**Comment by uBlock-user** [comment] 2019-09-11 08:21
> Those testing uBO will have to accept to deal with the manual reload step.

Can you put the new change behind an advance setting ? Because if that has to be done for every new update which seems so because uBO no longer updates as it used to, then it's going turn into an annoyance specifically for users like me and others who use dev builds of uBO. I prefer the old behaviour back.

**Comment by gwarser** [comment] 2019-09-25 11:50
I think this approach may be flawed - `suspendTabsUntilReady` stop to be effective and ads start leaking on startup when extension updates. At least cosmetic filters are not applied.

I experienced this yesterday evening no my phone when uBO updated to b16, and reproduced today on b17. Need to check if it's similar on desktop browser.

**Comment by gwarser** [comment] 2019-09-25 14:37
Hmmm, it's fine on Nighlty. Can be something with mobile firefox.

**Comment by gwarser** [comment] 2019-11-23 19:46
See also: https://github.com/gorhill/uBlock/issues/3185

**Comment by neroux** [comment] 2020-05-21 13:24
I would second @uBlock-user's comment

> Can you put the new change behind an advance setting ? Because if that has to be done for every new update which seems so because uBO no longer updates as it used to, then it's going turn into an annoyance specifically for users like me and others who use dev builds of uBO. I prefer the old behaviour back.

While I understand the rational behind the request itself - and **am not arguing** the feature should be removed altogther again - it should **not** be the standard behaviour.

The default behaviour should be like with any other extension, that an update actually updates the extension. For those who do wish to keep the extension running until a browser restart, there could be a flag which enables the current behaviour.

@gorhill, is there any chance we could get the behaviour to be switched? The current approach which requires a browser restart is "midly" annoying.

-----

Also, the description at https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#extensionupdateforcereload is not accurate

> otherwise the extension will reload only when being explicitly disabled then enabled

Disabling and enabling does not force the update. A full browser restart is required

**Comment by gorhill** [comment] 2020-05-21 13:35
> is there any chance we could get the behaviour to be switched?

No. Unconditional data loss is worst than having to opt-in to possible data loss. Firefox is working on a new user interface so that user can force a reload of the extension if they want: <https://bugzilla.mozilla.org/show_bug.cgi?id=1627495>.

**Comment by neroux** [comment] 2020-05-21 13:55
> Unconditional data loss is worst than having to opt-in to possible data loss.

I would not call it unconditional data loss, as that data is not supposed to be persisted and will get "lost" anyhow with a restart. This feature only postpones that at the cost that the extension does not exhibit standard behaviour and everyone who does not bother won't be able to properly update the extension.

Again, I am not arguing the feature should be removed, simply the behaviour should be switched. There doesn't seem to be data to back up either statement, but I'd argue that change was rather for a minority.

> Firefox is working on a new user interface so that users can force a reload of the extension if they want

Still, that should be reworded as the current description is not accurate.

**Comment by gorhill** [comment] 2020-05-21 14:11
> that data is not supposed to be persisted

How do you know? Only the user get to know whether they intend to persist the changes once they are happy with it. It's not just the rule, one could be in the process of crafting filters in the dashboard just to see their work disappear out of nowhere. I don't understand how this can be argued against.

**Comment by neroux** [comment] 2020-05-21 14:19
> How do you know?

The very description of this issue "Enable dynamic filtering and temporarily whitelist a site."

> one could be in the process of crafting filters in the dashboard just to see their work disappear out of nowhere.

This is a general issue with the way Firefox updates extensions and not specific to uBlock. The adopted approach essentially tries to "fix" that on its own and breaks the update system. This is particularly bad as the outlined way to force the update does not even work. Right now, one has to restart the browser (lose all tabs in that process, talking about data loss) when there is an update, given the person even noticed there was an update.

This feature essentially rendered automatic (and manual) updates useless and threw us back to the days when all extension updates required a restart.

**Comment by gorhill** [comment] 2020-05-21 14:34
> threw us back to the days when all extension updates required a restart

As said, this is being addressed by Firefox devs. As said above, I will not change the current behavior.
