### ISSUE TITLE
Safari 14 extension

### ISSUE THREAD

**Issue by specter78** [uBlockOrigin/uBlock-issues#1127] opened 2020-06-24 06:08 UTC
Now that safari is making extensions easier to develop, can we expect an official safari extension?

https://hacks.mozilla.org/2020/06/welcoming-safari-to-the-webextensions-community/

**Comment by uBlock-user** [comment] 2020-06-24 06:44
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1123

**Closed by uBlock-user** 2020-06-24 06:44 UTC
