### ISSUE TITLE
Support for importing GDrive-hosted filter lists

### ISSUE THREAD

**Issue by mica** [uBlockOrigin/uBlock-issues#703] opened 2019-08-14 02:53 UTC
I just switched from storing my filters in a txt file on Dropbox, where they provide a URL to the raw data, to Google Drive, where the best you can get is [a direct download url](https://sites.google.com/site/gdocs2direct/). 

It would be great if you could get uBlock to import GDrive-hosted files.

**Comment by uBlock-user** [comment] 2019-08-14 05:33
Duplicate of https://github.com/gorhill/uBlock/issues/3025

**Comment by mica** [comment] 2019-08-14 06:01
This is not a duplicate of the issue you listed. It's a completely different request. Please reopen this.

**Comment by mica** [comment] 2019-08-14 06:13
> Duplicate of [gorhill/uBlock#3025](https://github.com/gorhill/uBlock/issues/3025)

No, this is not a duplicate. This is a completely separate matter. Please reopen this.

**Comment by gwarser** [comment] 2019-08-14 08:41
And what exactly is wrong?

**Comment by uBlock-user** [comment] 2019-08-14 08:45
Nothing's wrong, google drive simply doesn't offer raw URLs because it's for storing things only not downloading and uploading filterlists. OP should use GitHub instead.

**Closed** 2019-08-14 11:10 UTC
Labels: declined, something to address
