### ISSUE TITLE
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

### ISSUE THREAD

**Issue by daspri** [uBlockOrigin/uBlock-issues#141] opened 2018-07-22 23:01 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Fails to update filters

### A specific URL where the issue occurs

moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/dashboard.html

### Steps to Reproduce

Open Firefox's "Browser Console" to see the error

1. Go to Filter Lists
2. Click 'Update Now'

### Expected behavior:

Filters should update.

### Actual behavior:

Filters do not update.

```
XHRGET https://raw.githubusercontent.com/gorhill/uBlock/master/assets/assets.json?_=212819
XHRGET https://publicsuffix.org/list/public_suffix_list.dat?_=212819
XHRGET https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt?_=212819
XHRGET https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt?_=212819
XHRGET https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt?_=212819
XHRGET https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt?_=212819
XHRGET https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt?_=212819
XHRGET https://easylist.to/easylist/easylist.txt?_=212819
15:53:46.412 [uBlock0CacheStorage] <unavailable>
vapi-cachestorage.js:94:9
genericErrorHandler
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/vapi-cachestorage.js:94:9
XHRGET https://easylist.to/easylist/easyprivacy.txt?_=212819
[HTTP/2.0 200 OK 16ms]
15:53:46.993  InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. vapi-cachestorage.js:230
putToDb/<
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/vapi-cachestorage.js:230:17
getDb
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/vapi-cachestorage.js:115:20
putToDb
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/vapi-cachestorage.js:219:9
set
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/vapi-cachestorage.js:77:9
onReady
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/assets.js:533:9
getAssetCacheRegistry
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/assets.js:426:9
assetCacheWrite
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/assets.js:536:5
onRemoteContentLoaded
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/assets.js:791:9
onLocalLoadSuccess
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/assets.js:217:9
onLoadEvent
moz-extension://d879bf29-1bac-4212-8cbb-be53485d7ab0/js/assets.js:128:9
```

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

uBlock Origin v1.16.14
Firefox 61.0.1
Windows 7 x64

**Comment by gwarser** [comment] 2018-07-23 00:41
https://github.com/gorhill/uBlock/issues/2985

How much free disk space you have?

**Comment by daspri** [comment] 2018-07-23 02:02
118,292,480 bytes free on that drive

**Comment by daspri** [comment] 2018-07-23 03:03
No, that setting is still set "true".

If I disable EasyList and restart firefox and Update Now, the update completes.

If I then Purge Cache and Update Now, it fails with the same error but after a different list (unbreak).

**Comment by uBlock-user** [comment] 2018-07-23 05:30
Can't reproduce. Filters updating as expected.

**Comment by gwarser** [comment] 2018-07-23 08:38
>118,292,480 bytes free 

120 megabytes? I have problems with update on my Android when free space is below 350MB

**Comment by gorhill** [comment] 2018-07-23 10:41
According to [Browser storage limits and eviction criteria](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits), the global limit is 50% of free disk space, so ~60 MB in the current case.

From this, there is a group limit, which if I understand correctly is that at most 20% of the global limit can by assigned to uBO, so 12 MB in the current case. So yes, it does seem like an issue with low disk space.

**Comment by gwarser** [comment] 2018-07-23 11:34
@gorhill it is possible to detect this case and show some dialog?

**Comment by gorhill** [comment] 2018-07-23 11:44
It's kind of a catastrophic error, the documentation said:

> The group limit is also called the "hard limit": it doesn't trigger origin eviction

When this occurs, there is no fallback possible. This occurs deep in the code, when using Firefox API, and there might be no uBO UI available, aside the icon in the toolbar (assuming it has not been hidden by the user).

At this point, if I am going to through lot of code at this, I rather work on the feasibility of compressing the data so as to reduce the storage footprint -- well it would be nice if Firefox's implementation of indexedDB did this for everybody.

**Comment by gwarser** [comment] 2018-07-23 12:03
When this happens filter lists are shown as outdated and when I click on "Update now" animation is spinning indefinitely - a way to fix only this case?

**Comment by gorhill** [comment] 2018-07-23 12:10
> when I click on "Update now" animation is spinning indefinitely - a way to fix only this case?

From what I see in the call stack above, this fails at the database level, not at the transaction level. There are error handlers at the transaction level. But it's a bit more complicated at the database level because the handlers at that level do not know about which callers need to be notified. It just means it's possible but not trivial to fix this. If I instead work on compressing (assuming feasability), this would possibly prevent uBO from failing (except in even more extreme cases of low disk space).

**Comment by gwarser** [comment] 2018-07-23 12:35
I can reproduce after filling my disk by `dd if=/dev/zero of=zero bs=1M` and then updating filters:

<details><summary>Browser console log
</summary>

```
14:14:22.938 [uBlock0CacheStorage] 
abort
​
bubbles: true
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
isTrusted: true
​
originalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
srcElement: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
target: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
timeStamp: 1038957
​
type: "abort"
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
vapi-cachestorage.js:94:9
genericErrorHandler
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:94:9
(Async: EventHandlerNonNull) getDb/req.onsuccess
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:152:13
(Async: EventHandlerNonNull) getDb
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:149:9
vAPI.cacheStorage<
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:55:5
<anonymous>
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:41:22
14:14:23.104 [uBlock0CacheStorage] 
abort
​
bubbles: true
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
isTrusted: true
​
originalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
srcElement: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
target: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
timeStamp: 1039123
​
type: "abort"
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
vapi-cachestorage.js:94:9
genericErrorHandler
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:94:9
(Async: EventHandlerNonNull) getDb/req.onsuccess
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:152:13
(Async: EventHandlerNonNull) getDb
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:149:9
vAPI.cacheStorage<
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:55:5
<anonymous>
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:41:22
14:14:34.596 [uBlock0CacheStorage] 
abort
​
bubbles: true
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
isTrusted: true
​
originalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
srcElement: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
target: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
timeStamp: 1050616
​
type: "abort"
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
vapi-cachestorage.js:94:9
genericErrorHandler
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:94:9
(Async: EventHandlerNonNull) getDb/req.onsuccess
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:152:13
(Async: EventHandlerNonNull) getDb
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:149:9
vAPI.cacheStorage<
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:55:5
<anonymous>
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:41:22
14:14:34.628 [uBlock0CacheStorage] 
abort
​
bubbles: true
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
isTrusted: true
​
originalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
srcElement: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
target: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
timeStamp: 1050646
​
type: "abort"
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
vapi-cachestorage.js:94:9
genericErrorHandler
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:94:9
(Async: EventHandlerNonNull) getDb/req.onsuccess
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:152:13
(Async: EventHandlerNonNull) getDb
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:149:9
vAPI.cacheStorage<
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:55:5
<anonymous>
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:41:22
14:14:34.910 [uBlock0CacheStorage] 
abort
​
bubbles: true
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
isTrusted: true
​
originalTarget: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
srcElement: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
target: IDBTransaction { mode: "readwrite", db: IDBDatabase, error: DOMException, … }
​
timeStamp: 1050928
​
type: "abort"
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
vapi-cachestorage.js:94:9
genericErrorHandler
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:94:9
(Async: EventHandlerNonNull) getDb/req.onsuccess
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:152:13
(Async: EventHandlerNonNull) getDb
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:149:9
vAPI.cacheStorage<
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:55:5
<anonymous>
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:41:22
14:14:35.038 [Show/hide message details.] InvalidStateError: A mutation operation was attempted on a database that did not allow mutations. vapi-cachestorage.js:230
putToDb/<
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:230:17
getDb
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:115:20
putToDb
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:219:9
set
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/vapi-cachestorage.js:77:9
onReady
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/assets.js:533:9
getAssetCacheRegistry
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/assets.js:426:9
assetCacheWrite
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/assets.js:536:5
onRemoteContentLoaded
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/assets.js:791:9
onLocalLoadSuccess
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/assets.js:217:9
onLoadEvent
moz-extension://a41ed17e-8cfa-48fa-8853-8be569753609/js/assets.js:128:9
```

</details>

**Comment by gorhill** [comment] 2018-07-23 13:18
>  I can reproduce after filling my disk

Isn't a scary thing to try? I fear the desktop/OS is going to start to fail badly before I can even get to try to repro.

**Comment by gorhill** [comment] 2018-07-23 13:38
Well the point is maybe uBO should at least stop spinning endlessly in its UI, though the core issue though would still be there: an essentially defect uBO because of low disk space.

**Comment by gwarser** [comment] 2018-07-23 13:46
>Isn't a scary thing to try?

:) 
@gorhill I have all Firefox test browsers as portable in home (partition) subfolder.
And even for `/` there should be still space reserved for root user.

@uBlock-user this happens to me frequently on Android when my free disk space fall bellow ~350MB This is 2014 phone with only 4GB of disk space total and bellow 1GB for user. Updating apps may cause this and you will not even know when this happens until ads starts appearing.

**Comment by gorhill** [comment] 2018-07-23 14:04
Ok I will come up with something. Since there is not always a UI available, I am thinking of showing a red warning on the _Settings_ page (where the "Storage used" area) for when the _"mutation operation was attempted"_ error occurs -- which could be caused by other reasons than just low-disk spaceI suppose. That warning would be cleared whenever a write operation succeed.

**Comment by daspri** [comment] 2018-07-23 15:30
My Firefox profile is on a virtual encrypted disk (vera/true) & portable, therefore not as large as the full drive. (cache is not on the same drive)

**Comment by gorhill** [comment] 2018-07-23 15:42
> when I click on "Update now" animation is spinning indefinitely - a way to fix only this case?

Looking at the code, I am not seeing why this would be. When uBO writes to the storage, it does so without minding the result. Are you sure about "indefinitely"? Can I see a screenshot of the console, I want to see if there is an unhandled exception, so far what I see is all handled by uBO.

**Comment by gorhill** [comment] 2018-07-23 16:21
I can reproduce now. Found an old 1GB stick, created a profile on it, and filled it with a 800MB file, there is around ~60 MB left. I get the errors now in the console, so now I have something to work with.

**Comment by gwarser** [comment] 2018-07-23 16:33
One solution may be to go back to extension storage - Mozilla will move backend to IndexedDB soon https://bugzilla.mozilla.org/show_bug.cgi?id=1474562
User will see low disk space before uBO starts to have problems.

>Are you sure about "indefinitely"?

Yes, I even once leave phone for the night with it spinning.

**Comment by gwarser** [comment] 2018-07-23 16:44
![screenshot_20180723_183926](https://user-images.githubusercontent.com/886325/43090691-65dbfdea-8ea8-11e8-97eb-3ef61c61dc09.png)
![screenshot_20180723_183932](https://user-images.githubusercontent.com/886325/43090696-68150bce-8ea8-11e8-8eb0-a690a5c92696.png)
![screenshot_20180723_183941](https://user-images.githubusercontent.com/886325/43090702-6aec3200-8ea8-11e8-96e9-e9cee3ed7a8d.png)

**Comment by gorhill** [comment] 2018-07-23 17:08
> One solution may be to go back to extension storage

Using `storage.local` instead of `indexedDB` is irrelevant. If I want more disk space given to uBO, I need to add the [`unlimitedStorage`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Unlimited_storage) permission.

So far I have resisted adding this permission because of how this was received by _some_ users when [Privacy Badger](https://github.com/EFForg/privacybadger/issues/1745) added it to their manifest .

In any case, now that I can reproduce I found out that there is an exception thrown, and this is trivially handled. uBO should still work fine without being able to use its cache (up to a point), this will just cause it to launch less efficiently since it might have to re-compile all filter lists every time.

The errors will still be written at the console, but there should no longer be unhandled exceptions.

**Comment by uBlock-user** [comment] 2018-07-23 17:21
> So far I have resisted adding this permission because of how this was received by some users when Privacy Badger added it to their manifest .

But you already added it in Chromium, and I don't see any backlash, so why would it now receive backlash for the same permission being added to Firefox?

**Comment by gorhill** [comment] 2018-07-23 18:12
I think the unhandled exception that was fixed here could have been the cause of reports of uBO having 0/0 filters at launch. I selected EasyList DEU (not in the package) and I tested without the fix (installed from AMO), and the number of filters loaded was less than it should have been if all went fine. I then tested same with the fix here and all filters were loaded (probably took longer time though because they needed download/compilation).

**Comment by gwarser** [comment] 2018-07-23 18:13
asset-viewer.html shows content from cache? Because EasyList shows Last modified: 12 Jun 2018 12:47 UTC

**Comment by gorhill** [comment] 2018-07-23 18:20
> asset-viewer.html shows content from cache?

By order: from cache, -- if not present, then from package, -- if not present then from remote location (if applicable).

**Comment by grenzor** [comment] 2018-07-25 12:57
>8 MB of storage space for plus ~40 ms of load time? 
Did you mean 80MB? If so, it seems worth it to me.

Also did you look at https://github.com/lz4/lz4? Looking at their benchmarks it could be faster and provide better compression/decompression. Found some JS libraries for it on Github but not sure if they include the "LZ4 HC" version or comparable speed/efficiency of SnappyJS. Maybe you're already happy with SnappyJS but just thought I'd ask.

**Comment by gorhill** [comment] 2018-07-25 16:59
Assuming default filter lists + selfie, without compressing, there need to be ~150 MB of free disk space, while with compressing there need to be ~70 MB of free disk space. The cache itself is ~15 MB uncompressed, ~7 MB compressed. I used `min disk space = cache size x 5 x 2`, as per indexedDB doc.

**Comment by gwarser** [comment] 2018-07-25 19:56
You have SSD disk? Will be interesting to see load + decompress time. May be worth it for devices <100MB/s

**Comment by gorhill** [comment] 2018-08-05 22:35
Here are the results when using [lz4-wasm](https://github.com/gorhill/lz4-wasm):

                                          d-size     c-size   ratio   c-time ms   d-time ms
                 [cache/assets.json]       20675        5517    27%           1    
            [cache/ublock-resources]       68524       29556    43%           1    
              [cache/ublock-filters]      500365      153737    31%           4
              [cache/ublock-badware]        5350        3085    58%           1    
              [cache/ublock-privacy]        7793        4440    57%           0
                [cache/ublock-abuse]       13929        5707    41%           0    
              [cache/ublock-unbreak]       63370       24706    39%           1    
                    [cache/easylist]     2700655     1053468    39%          19    
                 [cache/easyprivacy]      426307      203452    48%           3    
                   [cache/malware-0]       22754       14641    64%           1    
                   [cache/malware-1]      577440      364169    63%           7    
                     [cache/plowe-0]       69315       26129    38%           2    
     [cache/compiled/ublock-filters]      659064      179359    27%           4           2
     [cache/compiled/ublock-privacy]       11886        3065    26%           0           0
       [cache/compiled/ublock-abuse]       10611        5162    49%           0           0
     [cache/compiled/ublock-unbreak]       45121       20979    46%           0           0
           [cache/compiled/easylist]     3636161     1338516    37%          26          11
        [cache/compiled/easyprivacy]      599641      277396    46%           5           3
          [cache/compiled/malware-0]       32748       14779    45%           1           1
          [cache/compiled/malware-1]      811205      376090    46%           8           4
            [cache/compiled/plowe-0]       66074       25436    38%           1           0
                          Total (MB)         9.9         3.9    40%        

There were issues though with using WebAssembly:

- Chromium: not allowed without using a `'unsafe-eval'` in the manifest, which of course I won't do.
    - Note that I do force `same-origin` on the fetch, so it's unclear whether this is a Chromium issue or by design.
- Firefox: I needed to add `application/wasm    wasm` to my `/etc/mime-types`. I don't know if this would be an issue with Windows.

So this means despite the promising results above, such wasm-based solution is not yet ready for a stable release. I may add experimental support through a hidden setting though, will see.

**Comment by gwarser** [comment] 2018-08-05 22:55
>Firefox: I needed to add `application/wasm wasm` to my `/etc/mime-types`

Why? Is https://gorhill.github.io/lz4-wasm/test/index.html different?

**Comment by gorhill** [comment] 2018-08-05 23:01
I read the data through a XMLHttpRequest in the demo/benchmark page, and feed an ArrayBuffer to the WebAssembly engine. In the extension code I use `WebAssembly.instantiateStreaming`.

I actually did not try XMLHttpRequest in the extension code, I figure this would not be allowed because one could XMLHttpRequest to anywhere and use the bytes from the response to execute code from any origin -- so I stuck with the spirit of executing-code-only-from-the-package, anything else which would happen to work would quite certainly be an issue to fix in Firefox.

**Comment by grenzor** [comment] 2018-08-05 23:12
Really interesting results! 

Just out of curiosity, did node-lz4 have slower compression/decompression speeds than lz4-wasm?

**Comment by gwarser** [comment] 2018-08-06 12:16
My findings:

Looks like Firefox stores lots of nulls in database:

Size of *.sqlite file (only) on my standard Nightly profile with latest uBO rc was ~40MB.
After switch to lz4 branch (reset to default + restore backup) size decreased to 150kB - turned out most data is stored inside *.files subfolder - only ~11MB! (with selfie)

I thought something is broken, but filter lists are recent and all seems to work fine.

I switched back to rc - *.sqlite 41MB, *.files 7MB.

Side note: storage.local is stored in second folder, with `^userContextId=*` appended - ~70kB.

And I just confirmed this in fresh profile - lz4 branch uses ~11MB of disk space, latest rc 41MB of *.sqlite and 7MB in *.files without selfie, 12MB with selfie.


<details><summary>selectedFilterLists
</summary>

```
  "selectedFilterLists": [
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt",
    "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt",
    "https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt",
    "https://gist.githubusercontent.com/gorhill/ef1b62d606473c68d524/raw/f8181faac18cb5172c7c9bca8e5a3b22f0c925d0/gistfile1.txt",
    "POL-0",
    "plowe-0",
    "fanboy-social",
    "fanboy-thirdparty_social",
    "fanboy-annoyance",
    "adguard-annoyance",
    "malware-1",
    "malware-0",
    "fanboy-enhanced",
    "easyprivacy",
    "adguard-spyware",
    "easylist",
    "adguard-generic",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-experimental",
    "ublock-badware",
    "ublock-annoyances",
    "ublock-filters",
    "user-filters"
  ]
```

</details>

**Comment by jspenguin2017** [comment] 2018-08-06 19:39
WOW, you actually coded the compression library in assembly?!

**Comment by uBlock-user** [comment] 2018-08-11 15:54
Updated to the latest dev build, set `cacheStorageCompression` purged all cache and redownloaded all my lists, storage size on Chromium was 27 megs(assuming this as the point of reference for comparison because FF doesn't support `getBytesInUse` API yet and now with the workaround in place) and now on Firefox it's 9.9 megs!! Impressive!

**Comment by yourduskquibbles** [comment] 2018-08-11 16:36
I am showing a 3X size reduction as well, storage size was 15megs and is now 5megs with `cacheStorageCompression` set to `true`. Great work!

**Comment by gwarser** [comment] 2018-08-11 19:04
Correction to my comment about database size - my Nightly finally decided to put something inside *.sqlite file. Now it's *.sqlite: 16MB, *.files: 12MB
uBO reports: Storage used: 16,277,060 bytes

No idea why this happened - I cannot reproduce in fresh profile...

**Comment by gorhill** [comment] 2018-08-11 21:46
Sounds like the load selfie to me. Note that when you enable `cacheStorageCompression`, uBO will compress opportunistically from there on, it will not go through the storage to compress existing entries, just when something is written to it. If you want to find out the difference after toggling the setting, purge all caches and force an update. Also, eventually the selfie will be also written to the storage after all filter lists are updated,

**Comment by runboy93** [comment] 2018-08-12 13:54
Changed setting "cacheStorageCompression" to true, then went and purge and finally added my lists, before 11 megs and now 4 megs, using Firefox 62 Beta on Android.

**Comment by gwarser** [comment] 2018-08-12 18:35
>there were three clear regions of CPU usage

Not sure if you know this, these blue "hills" in the graph are not cpu usage. This is stack size. Even low "height" may use lot of cpu.

**Comment by uBlock-user** [comment] 2018-08-14 20:44
There's a performance-wise gain too when force updating filterlists, previously it would take a second or two for it to complete, now it downloads and updates the lists instantaneously and snappier even on Chromium.

**Comment by gorhill** [comment] 2018-08-14 23:15
The original issue has been addressed, the compression won't ever guarantee that running low on disk space will never affect uBO, so at this point I consider the issue fixed.

**Closed by gorhill** 2018-08-14 23:15 UTC
Labels: Firefox, bug

**Comment by shellye5** [comment] 2018-08-15 09:09
@gorhill sometimes filters take long to download with compression on any ideas on how to debug it?
Are you enabling it soon?
will this come to legacy too?

**Comment by Vangelis66** [comment] 2018-08-29 01:29
... Apologies if this isn't the proper place to post about my predicament, but I was directed to this issue via the Release Notes of the [latest dev build](https://github.com/gorhill/uBlock/releases/tag/1.16.21b0)... 

OS: **Windows Vista SP2 32-bit**
Browser: **Mozilla Firefox ESR 52.9.0 32-bit**
uBlockOrigin version: dev channel, v**1.16.21b0** (WE)

I was updated to the latest dev build from a previous dev build (from memory, must've been **1.16.17.7**) which is now removed from the GitHub repo. 

I opened the dashboard and tried to manually update 3rd-party filters; the "clocks" at the far right of each list all started spinning but after a few (3-4) seconds all turned simultaneously into an orange triangle (with a white exclamation mark inside), then, after another 2-3 seconds, all went back into the "clock" state... 

This behaviour I had never witnessed previously, after some checks it looked as though my lists hadn't updated 😭 E.g., the "**I don't care about cookies**" list remained at v2.8.8, while I checked and v2.8.9 is already on line at its [site](https://www.i-dont-care-about-cookies.eu/)... 

From looking closer at the release notes of **1.16.21b0**, I saw 

> A new advanced setting: **cacheStorageCompression**, default to **true**. 
> When true, uBO will lz4-compress data before storing it in its cache storage in supported platforms. 
> Currently, the only supported platform is **Firefox**/Firefox for Android.

By launching Firefox Browser Console (CTRL+SHIFT+J), clearing everything inside it and starting a manual 3rd-party filter list update, the console is populated with many `Error: LZ4BlockWASM: not initialized` instances: 

![brconsole](https://user-images.githubusercontent.com/9669492/44759176-1d717980-ab41-11e8-8a80-5b195423fde5.jpg)

I do hope they're meaningful to someone of you wonderful people...

For now, my options to successfully update 3rd-party filter lists on my setup are tested to be: 
1. Access "advanced user" settings, toggle the new pref `cacheStorageCompression` to `false`, apply changes and then the update of lists will work... 
2. Downgrade to the latest version (1.16.20=1.16.18) of the stable channel, where `cacheStorageCompression` is either absent/not enabled by default.
3. Downgrade to the latest legacy (XUL) version, 1.16.4.4, installable on 52.9.0 - sadly, it isn't backwards compatible with the WE versions, hence I'd have to reconfigure it from scratch... 

I understand that I don't have things on my side, as Vista has been EOL'd by MS and Fx 52.9.0 will be EOL'd by Mozilla in over a week's time... However, any insight as to what's the cause of this new issue will be highly appreciated... 

Many thanks in advance....

**Comment by gwarser** [comment] 2018-08-29 10:12
>Downgrade to the latest legacy (XUL) version, 1.16.4.4, installable on 52.9.0 - sadly, it isn't backwards compatible with the WE versions, hence I'd have to reconfigure it from scratch...

You can export your settings to file and import in new installation.

**Comment by Vangelis66** [comment] 2018-08-29 17:02
@gwarser 
> You can export your settings to file and import in new installation. 

Thanks for this tip, I'm sure I knew it already, but (originally) posting late at night and under some frustration doesn't help much in my growing age... 

Just to confirm, do the filter-list storage files the WE version saves inside `./profile/storage/default/*` get somehow translated to the format of files the XUL version stores inside `./profile/extension-data/*` when one downgrades from WE -> XUL and imports settings, as per your suggestion?

**Comment by gwarser** [comment] 2018-08-29 19:32
Settings exported by clicking in uBO Settings tab on "Back up to file" button will be saved in special portable text format ([json](https://en.wikipedia.org/wiki/JSON)) and will contain all uBO settings and addresses of filter lists you are subscribed to. One thing missing will be your statistics (request blocked since install).

**Comment by resistor4u** [comment] 2018-09-04 06:42
I'm on 1.16.20 on Firefox 61.0.2 on Mac OS 10.11.6, and I'm unable to set `cacheStorageCompression true` in the Advanced settings - when I add and apply the settings, `cacheStorageCompression` disappears. Anyone else getting this?

**Comment by gwarser** [comment] 2018-09-04 10:40
This feature is in beta tested now. You can install uBO development builds for Firefox from here https://github.com/gorhill/ublock/releases

**Comment by resistor4u** [comment] 2018-09-06 17:50
@gwarser if so, then perhaps the wiki documentation (https://github.com/gorhill/uBlock/wiki/Advanced-settings) should be changed? There, it says the feature is for "uBO 1.16.17b and above."
