### ISSUE TITLE
Control panel interface bug in Google Chrome for Mac 10.9.5

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#1557] opened 2021-04-16 08:57 UTC
uBlock Origin 1.34.1rc0 default
Google Chrome 66.0.3359.117 (for Mac)
Mac OS 10.9.5 Mavericks, MacBook Pro 13 Retina

There are only 7 lines in "My filters": https://i.imgur.com/hIDat4O.jpg

This problem appeared along with the new interface design, but I kept forgetting to report it.

**Comment by gorhill** [comment] 2021-04-16 10:49
Duplicate of #1287.

**Closed by gorhill** 2021-04-16 10:49 UTC
Labels: duplicate
