### ISSUE TITLE
Request: ublock chromium browser for Android

### ISSUE THREAD

**Issue by colbycdev** [uBlockOrigin/uBlock-issues#420] opened 2019-02-13 22:06 UTC
What I'm thinking of is a chromium based browser for Android that fully incorporate uBlock functionality, like cosmetic filters and host block. 
I'm getting quite tired of no Android extension support (Yandex support some chrome webstore extensions on Android, ublock isn't supported, I always get a message from the webstore saying just that).  Firefox support extensions on Android, but it is significantly slower at web page rendering on mobile (much slower than chromium based Android browser and Firefox desktop).
Android alternatives (browsers like brave, kiwi, etc) are inferior to uBlock
Another alternative, though I don't know if it would be very hard/impossible to implement (not sure on Samsung policy) is an extension for Samsung internet, which is chromium based

That being said, your extension is a modern miracle, and I can't imagine an internet without it. Thanks for all your amazing work

I also apologize if this has already been requested

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fmilligan** [comment] 2019-02-13 22:11
I would also love this. I use brave browser on mobile, and it does not compare

**Comment by uBlock-user** [comment] 2019-02-14 13:39
Duplicate of https://github.com/gorhill/uBlock/issues/1092

**Closed by uBlock-user** 2019-02-14 13:39 UTC

**Comment by colbycdev** [comment] 2019-02-14 14:30
So what you are saying is screw Android? I pretty much only use the platform, and FF is slow AF at web page rendering. At least put out a call for help for devs who could do it. At the moment,there is no competent chromium based browser with adblock on mobile. Sure, you have brave, but it doesn't do cosmetic filtering (so a lot of frowny faces) and allows some 'acceptable' ads
Always the case. Mobile market is bigger than PC nowadays, but a lot of devs refuse to specially adapt because"well, we have a PC. Why don't you? Go out and spend a few hundred dollars you don't have because we won't adapt to our user base"
I saw a meme with the caption " well, it works on my machine" on r/programmer_humor and it sums this up perfect 
I'm sorry if I'm ranting; just a frustrated dev with no PC

_Sent from my TETRA using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pedro7** [comment] 2019-02-14 16:07
I believe he meant:
"No time and no plans from the main dev.
Attempts at doing so would possibly diminish quality of uBlock Origin Firefox/Chrome extension due to spreading too thin".

**Comment by colbycdev** [comment] 2019-02-14 16:15
So, as I said. Screw Android, get a PC peasants
________________________________

**Comment by uBlock-user** [comment] 2019-02-14 16:19
Original issue has been declined, so no it's not happening.

**Comment by gorhill** [comment] 2019-02-14 16:48
> So what you are saying is screw Android?

No, [my answer](https://github.com/gorhill/uBlock/issues/1092#issuecomment-166159997) was:

> No, it's a hobby, I wouldn't have time for this.

People are entitled to exactly _zero_ of anything I or other volunteers do here, so to complain that I or other volunteers decline to do even more is quite rude.

I use uBO with Firefox for Android, and this works just fine for me.
