### ISSUE TITLE
The logger doesn't show ? in rules with #?#

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2475] opened 2023-02-01 14:29 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

To counter `sekai-kabuka.com#?#td[align="center"][class] > table > tbody > tr > td > div[style]:has(> ins.adsbygoogle)` in AG Annoyances, `sekai-kabuka.com#@#td[align="center"][class] > table > tbody > tr > td > div[style]:has(> ins.adsbygoogle)` or even the logger's disabling button (FilterAuthor mode) does not work. The only way to counter seems to be `sekai-kabuka.com#@?#td[align="center"][class] > table > tbody > tr > td > div[style]:has(> ins.adsbygoogle)` (look `?`).

### A specific URL where the issue occurs.

https://sekai-kabuka.com/

### Steps to Reproduce

1. Visit the site with AG Annoyances enabled, but the site may be different if accessed from foreign or by VPN.
2. If the filter is applied, try to counter.

### Expected behavior

`sekai-kabuka.com#@#td[align="center"][class] > table > tbody > tr > td > div[style]:has(> ins.adsbygoogle)` and disalbing via the logger should work.

### Actual behavior

Doesn't work.

### uBO version

1.46.0

### Browser name and version

Chrome 109.0.5414.120

### Operating System and version

Windows 10

**Comment by gorhill** [comment] 2023-02-01 14:34
Did you try with `#@?#`?

**Comment by Yuki2718** [comment] 2023-02-01 14:37
Okay, but the logger doesn't show `?`. At least the disable via the logger needs fix.

**Comment by gorhill** [comment] 2023-02-01 14:40
By the way, why is AdGuard using `?`? The unfortunate side-effect in uBO is that the filter is being compiled as procedural while it would otherwise be a perfectly valid declarative filter, being applied natively by the browser.

**Comment by Yuki2718** [comment] 2023-02-01 14:48
I don't know TBH but faintly remember there was some compatibility issue and they temporally changed to `#?#abp-has()`. Maybe @krystian3w knows better.

**Comment by krystian3w** [comment] 2023-02-01 14:57
https://github.com/AdguardTeam/ExtendedCss/issues/161 - here started IMO.

https://github.com/AdguardTeam/FiltersRegistry/pull/665 
https://github.com/AdguardTeam/FiltersRegistry/pull/664 - both don't touching ublock files on adtidy.org:

> ```adb
> wuyong.fun,26g.me,myqqjd.com,poapan.xyz,javboys.com,chpadblock.com,idevicecentral.com,fcportables.com,codehelppro.com##+js(abort-on-property-read, reqServers)
> rbs.ta36.com#?#.container > div[id][class]:has(h4.adblock_title)
> !
> ```

https://github.com/AdguardTeam/ExtendedCss/issues/154 - opened about troubles with check invalid inside has/convert to procedural.

**Comment by krystian3w** [comment] 2023-02-01 15:00
PS. ABP engine parse only:

`#@#td[align="center"][class] > table > tbody > tr > td > div[style]:has(> ins.adsbygoogle)`

as exception, so his engine disable use JS and CSS4 implementation at same time.

**Comment by Yuki2718** [comment] 2023-02-01 15:15
I will suggest to change these `#?#*:has` rules to `##*:has()` when Firefox and Safari CB officially support native :has(), if no others do.

**Comment by gorhill** [comment] 2023-02-01 15:27
On the other hand this would be a problem for people using older versions of a browsers not supporting native `:has()` and `?` would be the only workaround to force procedural -- think of Firefox vs Firefox ESR.

**Comment by gorhill** [comment] 2023-02-01 15:29
Simpler repro case I can work with:

    example.org#?#div:has(> h1)
    example.org#@#div:has(> h1)

**Comment by Yuki2718** [comment] 2023-02-21 12:14
IIRC `:contains()` was translated into `:has-text()` in the logger in the older versions, but now displayed as is separately with the same `:has-text()` rule as if they're different operator?

**Comment by krystian3w** [comment] 2023-02-22 07:25
Even the exception must be with an identical operator:
```adb
github.com##p:contains(contains)
! no longer disable AdGuard / pre-CSS syntax:
github.com#@#p:has-text(contains)
github.com#@?#p:-abp-contains(contains)
```

**Comment by Yuki2718** [comment] 2023-07-15 01:35
Now opposite is the case - to counter `sankei.com#?#.main-items > .col-container > .col-item:has(.story-card-feed > .col-container > article.storycard span.sponsored)` in Japanese filters (no more exist as I adjusted), `sankei.com#@?#.main-items > .col-container > .col-item:has(.story-card-feed > .col-container > article.storycard span.sponsored)` doesn't work and I have to use `sankei.com#@#.main-items > .col-container > .col-item:has(> .story-card-feed > .col-container > article.storycard span.sponsored)`. Is this expected behavior?

**Comment by gorhill** [comment] 2023-07-15 13:12
This works for me:

    example.org#?#body:has(p):style(color: red)
    example.org#@?#body:has(p):style(color: red)

Also:

    example.org#?#body:has(p):style(color: red)
    example.org#@#body:has(p):style(color: red)

**Comment by Yuki2718** [comment] 2023-07-15 13:47
Oh, sorry! I missed I added `>` in https://github.com/AdguardTeam/AdguardFilters/commit/ca53d4a3c8103caf545b47e39f3ec100aa045740

**Comment by gorhill** [comment] 2024-04-15 00:02
I can't reproduce an issue in latest uBO. Closing.

**Closed by gorhill** 2024-04-15 00:02 UTC
Labels: bug
