### ISSUE TITLE
::before / ::after no longer hidden as generic filter?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#464] opened 2019-03-16 04:43 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`##div[class="widget polarisSpid"]:before` no longer cut / hide pseudoelements as generic cosmetic filter.

### A specific URL where the issue occurs

```
https://www.folkebladet.no/nyheter/2019/03/15/Kystverket-avsl%C3%A5r-Ytre-%C3%98yfjord-etablering-18661811.ece

https://www.hitra-froya.no/pluss/nyheter/2019/03/15/For-Evaldas-var-nedleggelse-i-nord-starten-p%C3%A5-et-nytt-og-godt-liv-her-i-%C3%B8yregionen-18665600.ece

https://www.rbnett.no/sport/2019/03/14/Etterlyser-bedre-informasjon-fra-klubbene-18660293.ece

https://www.smp.no/nyheter/2019/03/15/Hareid-held-seg-til-%C3%85lesund-18664411.ece
```

https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-473264989

### Steps to Reproduce

1. paste to my filters panel: `##div[class="widget polarisSpid"]:before`

     - save changes

2. open demo site

3.  blurred on text is still visible:

    ![obraz](https://user-images.githubusercontent.com/35370833/54470771-0bd68300-47ae-11e9-982b-0f3d05a81030.png) |
    --- |

### Expected behavior:

recover works filter as generic

### Actual behavior:

filter need TLD or domain name to works

### Your environment

* uBlock Origin version: uBO 1.18.6
* Browser Name and version: Firefox 66 RC3
* Operating System and version: Windows 7 Pro x64

---

###### no affected versions:

uBO <= 1.17.4

**Comment by uBlock-user** [comment] 2019-03-16 06:50
@gwarser Did this work before ?

**Comment by uBlock-user** [comment] 2019-03-16 07:02
My Filters shows 0 by 0 after adding it, so it's not getting counted it and it's not gonna getting applied either if it's not getting counted as a filter.

**Comment by DandelionSprout** [comment] 2019-03-16 08:11
I can confirm first-hand that this has been supported since at least July last year, potentially earlier as well. In fact, https://github.com/DandelionSprout/adfilt/issues/7 was in its modest beginnings about an issue that was resolved by using a `:before` entry.

**Comment by DandelionSprout** [comment] 2019-03-16 08:14
https://github.com/DandelionSprout/adfilt/blob/master/NorwegianList.txt#L963 through L981 contains several examples of this being applied in regular use, and `##.Article-header-body:before` was known (or merely believed) to work as a generic entry at some point in time.

**Comment by THEtomaso** [comment] 2019-03-16 08:21
> I can confirm first-hand that this has been supported since at least July last year, potentially earlier as well.

March 2017?
https://github.com/gorhill/uBlock/commit/cf123b926497414cdaab83e265ae85891f372ab6#diff-3b15596213ed9ba37fb5b8bb1402a6c2

BTW; `##div[class="widget polarisSpid"]:before` works just fine in uBO Legacy.

**Comment by gorhill** [comment] 2019-03-16 12:10
The filter requires at least one hostname, it can't be used without a hostname. This has been like this since at least Dec 2017, I didn't check earlier.

**Comment by THEtomaso** [comment] 2019-03-16 12:26
> Edit: This has been like this since gorhill/uBlock#2448 was fixed

If this was the case, then shouldn't uBO Legacy fail to load those rules too?

**Comment by gorhill** [comment] 2019-03-16 13:31
> shouldn't uBO Legacy fail to load such generic rules too?

I would expect so. I will have to investigate further then.

**Comment by gorhill** [comment] 2019-03-16 13:42
Ok I was wrong: it seems this is a regression from <https://github.com/gorhill/uBlock/commit/261ef8c510fd91ead57948d1f7793a7a5e2a25fd>.

**Closed** 2019-04-21 12:40 UTC
Labels: bug

**Comment by krystian3w** [comment] 2020-03-08 22:52
@gwarser test imo again no works as generic:

`https://www.medonet.pl/zdrowie,gastroenterolog---opis-specjalizacji--przebieg-badania--leczenie,artykul,1729478.html`

https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/c9414a44248d2da938c16467f28705686f6d32d4

**Comment by gwarser** [comment] 2020-03-09 00:22
Cannot test on your example - I don't see it.

Works here:

- disable JS
- add `##.gt3_preloader::after`
- load `http://jarmarktumski.plock.eu/`
- you will see blank page instead of this gif:


![image](https://user-images.githubusercontent.com/886325/76173951-44802100-61a4-11ea-8769-9946f22f2263.png)

**Comment by krystian3w** [comment] 2020-03-09 06:51
Try found article from Google, also clear cookies for medonet.

**Comment by gorhill** [comment] 2020-03-09 11:24
These are tests for CSS pseudo elements, they succeed: <https://gorhill.github.io/uBlock/tests/css-selector-based-cosmetic-filters.html>.

**Comment by krystian3w** [comment] 2020-03-09 11:26
OK - I suppose similar glitch AS generic:

`##.cookie` on body/html tag

When for my filter does not work but @gwarser have some blank page (breakage).

**Comment by gorhill** [comment] 2020-03-09 11:40
>     medonet.pl##.NTZpopup
>     medonet.pl##.withNTZpopup::before

Those filters are specific, they are injected unconditionally so they can't suffer from issues affecting generic filters.

**Comment by krystian3w** [comment] 2020-03-09 14:32
Yes.

**Comment by krystian3w** [comment] 2023-02-09 10:58
About dropped pseudo-class syntax:

#2483 #2442
