### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by haze242** [uBlockOrigin/uBlock-issues#808] opened 2019-12-05 10:25 UTC
Periodically, after the launch browser, I see missed ads, open settings, turn to filters, the first second watching a blank space instead of a list of filters, missing even those that default, then they reappear, but 50% - "0 used out of 0".

https://i.imgur.com/QwScZZ6.png

"Purge all cashes" + "Update now" fix the problem, but after restarting browser, it comes back.

Windows 7, Firefox 70, Nano Adblocker v1.0.0.131 (Based on uBlock Origin Version/1.23.0 Commit/a5601b8), suspendTabsUntilReady true

Sorry for my English

**Comment by uBlock-user** [comment] 2019-12-05 10:30
>  Nano Adblocker v1.0.0.131 

You're not using uBO, so why post here then ?

**Comment by haze242** [comment] 2019-12-05 10:56
> 
> You're not using uBO, so why post here then ?

Because I think it's uBO bug, not a Nano ( but duplicated there too )

**Comment by uBlock-user** [comment] 2019-12-05 11:10
> it's uBO bug

You can't claim without experiencing it on uBO first and you don't even have uBO installed. Fork bugs are fork maintainer's responsibility.

**Comment by haze242** [comment] 2019-12-05 11:50
> 
> You can't claim without experiencing it on uBO first and you don't even have uBO installed. Fork bugs are fork maintainer's responsibility.

And then on a clean profile and clean config and ESR etc...

Nano is a stable uBO + Nano Resources + Nano Filters + redesign + a few little things.
It's logical to assume it's a uBO bug.

I reported it because this is serious bug.
I don't have time to work as a tester and I don't know enough about the uBO and its interactions with browsers, other extensions, config values.
If you don't know what could have caused such a bug, then I will just use Vivaldi (there is no such problem).

**Comment by gwarser** [comment] 2019-12-05 12:36
Update your Firefox or switch `dom.storage.next_gen` to `false`
Are you cleaning cookies/storage on startup?
Are you using first party isolation?

**Comment by gorhill** [comment] 2019-12-05 13:26
> the first second watching a blank space instead of a list of filters

It's because when the dashboard opens before uBO's main process is ready (which is what happens when you restore tabs at launch with uBO's dashboard already opened), it's not able to communicate with the main process and thus will be unable to display the content. Just force a refresh of the dashboard.

Maybe I could add code to force a refresh of the dashboard tab once uBO's main process is all ready, I will need to investigate.

**Comment by haze242** [comment] 2019-12-05 13:38
1. I'm switched dom.storage.next_gen to false as soon read the news about this bug.
2. Yes, i'm cleaning cookies/storage on close + cache memory only ( disk/offline disabled )
3. Yes FPI + RFP
4. Yes

**Comment by haze242** [comment] 2019-12-05 13:43
> 
> It's because when the dashboard opens before uBO's main process is ready

suspendTabsUntilReady not solve this problem?

**Comment by gorhill** [comment] 2019-12-05 13:47
First-party isolation is not officially supported and is afflicted by issue in Firefox 70. You need to see if you suffer the same issue in a fresh new profile with no `about:config` modifications -- the warning when you access `about:config` is there for a reason.

**Comment by gorhill** [comment] 2019-12-05 13:49
> `suspendTabsUntilReady` not solve this problem?

This is an issue unrelated to `suspendTabsUntilReady` -- which you also didn't need to touch by the way.

The symptom of what I am talking about is:

![a](https://user-images.githubusercontent.com/585534/70240865-fd653880-173b-11ea-8298-c2b8fd8b8cf4.png)

If this is not your specific issue, then forget what I said -- I can't reproduce your issue and never suffered the partial loading of filters as I see in your screenshot.

**Comment by uBlock-user** [comment] 2019-12-05 13:52
> cleaning cookies/storage on close

sounds like  https://bugzilla.mozilla.org/show_bug.cgi?id=1313401#c0

**Comment by haze242** [comment] 2019-12-05 14:07
> 
> 
> First-party isolation is not officially supported and is afflicted by issues in Firefox 70. 


If it's FPI bug, then this is the first FPI bug I noticed, despite using for quite a long time ( and a similar mechanism in Chromium ).


> 
> 
>  the warning when you access `about:config` is there for a reason.

about:config - the only reason why I still use Firefox :)

> 
> 
> sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1313401#c0
thanks, try to disable cleaning storage

**Comment by gorhill** [comment] 2019-12-05 14:10
Another point:

> Nano Adblocker v1.0.0.131 (Based on uBlock Origin Version/1.23.0 Commit/a5601b8),

You should be using 1.24.2, 1.23.0 had more issue with FPI, and the latest version contains fixes to better work around some of FPI kinks which have not been fixed in Firefox 70.

**Comment by haze242** [comment] 2019-12-05 14:44
I use the Nano for two reasons, I'm lazy to connect all Nano lists separately, and secondly, I use uBO-Scriptlets in addition to the Resources Nano.

 >
 >
 > You should be using 1.24.2
I'll wait a while, temporarily disable cleaning storage and restoring session ( if that's not enough, I'll temporarily disable the FPI and use Temporary Containers ).

Another question on ESR compatibility with FPI is better or worse?

**Comment by gorhill** [comment] 2019-12-05 14:59
> Another question on ESR compatibility with FPI is better or worse?

According to <https://bugzilla.mozilla.org/show_bug.cgi?id=1554805>, it's not fixed in 68 ESR.

**Comment by haze242** [comment] 2019-12-05 15:14
> 
> 
> According to https://bugzilla.mozilla.org/show_bug.cgi?id=1554805, it's not fixed in 68 ESR.
Well, then I stay on the 70. Thanks all for answers. )

**Comment by gorhill** [comment] 2019-12-05 16:31
Closing since most likely issue was with `about:config` changes.

**Closed** 2019-12-05 16:30 UTC
Labels: external
