### ISSUE TITLE
Follow-up to #3631

### ISSUE THREAD

**Issue by tamlin-mike** [uBlockOrigin/uBlock-issues#174] opened 2018-08-19 18:43 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
This is my follow-up to #3631. I have repro sites, but due to the change in who could add comments (only code contributors) I was prevented from adding that (probably vital) info to the bug report.

### A specific URL where the issue occurs
https://www.svd.se/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
Visit site. Noteworthy might be I do have a bunch of UO hiding rules already in effect. I also have NoScript active.
2. [Second Step]
Select UP Element Zapper icon inside the UO pop-down "menu".
3. [and so on...]
Use mouse to move around. Note that it highlights page elements as you move the cursor over them. Hit the Del(ete) key, and note how nothing happens. Workaround I found seems to be you need to right-click, to bring up the context menu, then hit ESC to dismiss it. Now the Del key works as expected.

### Expected behavior:
Del(ete) key works immediately on entering zapping mode.

[What you expected to happen]

### Actual behavior:
Already explained.

[What actually happened]
Already explained.

### Your environment

* uBlock Origin version: 1.16.16
* Browser Name and version: Firefox.Q 61.0.2 64-bit
* Operating System and version: Win10-64

**Comment by gwarser** [comment] 2018-08-19 19:12
Different repository https://github.com/gorhill/uBlock/issues/3631

Duplicate of https://github.com/gorhill/uBlock/issues/953

https://github.com/gorhill/uBlock/issues/953#issuecomment-305854150:
>Maybe something else is "eating" the Esc key, preventing the event from reaching uBO. Something to try when this occurs: right-click on the page to bring up the contextual menu, then right click again somewhere on the page to dismiss the contextual menu, then try again the Esc key. Does it works now? 

Can you check Nightly? https://github.com/gorhill/uBlock/issues/3631#issuecomment-413183717

**Closed by gwarser** 2018-08-19 19:12 UTC
