### ISSUE TITLE
uBlock Origin extension blocks all web browser connectors in UnGoogled-Chromium

### ISSUE THREAD

**Issue by Jd7Kz8o** [uBlockOrigin/uBlock-issues#1927] opened 2022-01-13 12:35 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

After updating UnGoogled-Chromium Web-Browser to the latest version:
Version 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

The browser extension uBlock Origin blocks any connection of the UnGoogled-Chromium Web-Browser and Is also not responsive to any action.
As soon as I disable uBlock Origin, the browser works.

I then uninstalled uBlock Origin 1.33.2 and installed the latest version 1.40.8, no change, the extension blocks all connections of the web browser.

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5, KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.11.5-custom
OS Type: 64-bit
Processors: 8 × AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx, Memory: 13.7 GiB of RAM

### A specific URL where the issue occurs

anny

### Steps to Reproduce

have no steps

### Expected behavior

have no

### Actual behavior

extension disabled

### uBlock Origin version

1.40.8

### Browser name and version

Version 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

### Operating System and version

Kubuntu 20.04

**Comment by mapx-** [comment] 2022-01-13 12:46
if you already updated all filter lists, try

`$ping,third-party,badfilter`

**Comment by uBlock-user** [comment] 2022-01-13 12:46
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1790

**Closed by uBlock-user** 2022-01-13 12:46 UTC
