### ISSUE TITLE
Missing dark mode contrast in protocol manager 

### ISSUE THREAD

**Issue by crazyyzarc** [uBlockOrigin/uBlock-issues#1338] opened 2020-11-11 06:38 UTC
Do you can implement a better contrast for protocol manager. I have activated the Dark Mode under W10 Release build 2004. My current uBlock Origin version is 1.30.9b14. Under Settings -> Personalization -> Colors -> Select color. You see it here:
![2020-11-11 07_32_57-Window](https://user-images.githubusercontent.com/4954535/98777262-b1f9e680-23f0-11eb-9238-b2542e18294a.png)

![2020-11-11 07_42_25-uBlock₀ — Protokoll der Netzwerkanfragen](https://user-images.githubusercontent.com/4954535/98777696-81ff1300-23f1-11eb-9fae-86cfb45ab828.png)

**Comment by uBlock-user** [comment] 2020-11-11 07:12
It's not complete yet.

**Comment by gwarser** [comment] 2020-11-11 11:41
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/401

**Closed by gwarser** 2020-11-11 11:41 UTC
