### ISSUE TITLE
settings are difficult to access with a longer list

### ISSUE THREAD

**Issue by usernamehyphen** [uBlockOrigin/uBlock-issues#3058] opened 2024-01-04 08:22 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When opening settings to get filters cache invalidated and refreshed, my filters tab opens, text area gets focus, scrolls down to its end (possibly because it remebers last focused line?) and hides settings and (the other) filters tabs, **scrolling up  on page is not possible** and so settings and posibility to update external filter lists.

### A specific URL where the issue occurs.

localhost

### Steps to Reproduce

1. Set up a long user filter list so its longer than screen (shows scrollbar)
2. Open unlock origin from any page in fennec(Firefox from f-droid repo)
3. Open dashboard
4. Try to navigate to other tabs...

### Expected behavior

Being able to get to settings tab

### Actual behavior

not being able to get to settings... not really, there is a workaround)

### uBO version

1.54

### Browser name and version

fennec 121.0.0 (Build #1210020), 1955f8455f+ GV: 121.0-20231221193920 AS: 121.0

### Operating System and version

lineageos

**Comment by usernamehyphen** [comment] 2024-01-04 08:30
Scrollbar doesn't even show.
![Screenshot_20240104-085903_Fennec edited](https://github.com/uBlockOrigin/uBlock-issues/assets/120217643/19e70829-93cb-4991-9895-d54fe2cedda8)

**Comment by garry-ut99** [comment] 2024-01-04 10:49
I can reproduce: Firefox 121 & uBO 1.54, it wasn't happening in some previous versions of Firefox, so it's something which happens in new Firefox versions.

> usernamehyphe : not being able to get to settings... not really, there is a workaround

The workaround is to access uBO settings by :
 `...` > `Addons` > `Manage Addons` > `uBlock Origin` > `Settings` instead of
 `...` > `Addons` > `uBlock Origin` > `Settings Pane`

**Comment by u-RraaLL** [comment] 2024-01-04 12:18
Happens only with `Scroll to hide toolbar` enabled.

(Settings > Customize > Gestures > Scroll to hide toolbar)

**Comment by usernamehyphen** [comment] 2024-01-04 12:29
> Happens only with `Scroll to hide toolbar` enabled.
> 
> (Settings > Customize > Gestures > Scroll to hide toolbar)

Yes, that is true... however, You could have shorten it to *happens only in default settings*

**Comment by usernamehyphen** [comment] 2024-01-04 12:34
> Happens only with `Scroll to hide toolbar` enabled.
Yes, that is true... however, You could have shorten it to *happens only in default settings*

**Comment by gwarser** [comment] 2024-01-04 12:34
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2326 ?

**Comment by J3ekir** [comment] 2024-01-04 19:53
I think you should use something like this in 1p-filters.css.
`body { height: 100svh; }`

**Comment by krystian3w** [comment] 2024-01-09 13:14
https://github.com/uBlockOrigin/uBlock-issues/issues/3058#issuecomment-1877677071 - but for Firefox 102, so 79–101 need other idea (One rabbi says that the error does not occur in edition 120 and the second rabbi's opinion rather indicates that any edition with a retractable strap may be susceptible).

**Comment by gwarser** [comment] 2024-02-12 14:50
Not yet in stable build, and it's difficult to test in dev uBO on mobile.

**Comment by krystian3w** [comment] 2024-02-12 23:40
Maybe have rooted device and switched xpi files in profile (as long Firefox itself reject these modification).

**Comment by gorhill** [comment] 2024-02-29 13:48
No feedback, assuming it is fixed, closing.

**Comment by gwarser** [comment] 2024-02-29 15:47
Still broken. Not sure the workaround from https://github.com/uBlockOrigin/uBlock-issues/issues/3058#issuecomment-1876889216 worked for me before, but it does not work now. My workaround to put cursor in the first line still works.

**Comment by gorhill** [comment] 2024-03-01 02:40
Toggling on desktop mode is also a good workaround.

**Comment by gwarser** [comment] 2024-03-05 17:44
Does not work for me.

Redmi Note 10 Pro, b14.

As soon the text cursor is restored to the bottom of the list, menu disappears.

**Comment by gorhill** [comment] 2024-03-05 18:51
> Does not work for me.

Then I don't know what to do. I could reproduce before the change, I can no longer reproduce after the change, and I understand that the issue was because `100vh` was used, but `100vh` included the browser chrome, while `svh` exclude the browser chrome -- hence my understanding of why this fixed it on my side.

**Comment by krystian3w** [comment] 2024-03-06 09:00
Maybe similar test need list viewer and resource viewer:

- for first I lost search bar and error counter
- for viewer I lost input with URL

**Comment by garry-ut99** [comment] 2024-03-06 09:59
The bug in "My filters" pane is fixed for me on 2 different phones.

But like the above comment says - for me the same bug still occurs also in resource viewer
(in "Filter lists" pane after clicking an eye icon to view content of a filter list.)

**Comment by gwarser** [comment] 2024-03-06 10:18
I have no idea - I tried it this morning, and it magically fixed itself :confused: 

I was testing it for over an hour now, and all was fine in mobile mode (desktop view still broken for over 100 lines, I have ~200). I even tried reinstalling uBO again (installing from file without disabling uBO from add-on manager does not work - yesterday I installed it after turning it off from add-on manager "just in case").

All was fine!

And just out of the blue I toggled to desktop mode and back and now it's broken again!!!
I even recorded video of reproducing it!

And you know what? It just fixed itself again :D

Must be something very rare or with unique STR, so hopefully users will not have issue with it too often.

**Comment by garry-ut99** [comment] 2024-03-06 11:01
> gwarser : I don't have issue with list/resource viewer.

Are you sure, because the bug in resource viewer sometimes occurs immediately after opening resource viewer, but sometimes not, but even if it doesn't occur immediately, then still can be reproduced by additional steps, for example in "AdGuard - Mobile Ads":
- typing a single letter in the search field (for example "v") 
and waiting until it automatically jumps to the found line
- or clicking down arrow on Errors: 1 found

**Comment by gorhill** [comment] 2024-03-06 12:10
Out of caution since it's the first time I use `svh` units, I added the `100svh` only for mobile mode in the dashboard. Resource viewer is not embedded in the dashboard, so it needs its own `100svh`. I should look up everywhere `100vh` is used.

**Comment by garry-ut99** [comment] 2024-03-12 11:09
Fixed for me now in 1.56.1b15. 

By the way, I see that "Scroll to hide tollbar" works not only in websites, but also in browser extensions, for example I see it working in AdGuard for Browser, it's useful when browsing/scrolling in extension settings panes, for the same reason it would be useful to have it enabled/supported in uBO.

**Comment by gorhill** [comment] 2024-03-12 11:23
> Scroll to hide tollbar

What's that?

**Comment by garry-ut99** [comment] 2024-03-12 11:47
A typo, I meant "toolbar", not "tollbar", this is the setting which was causing the issue here, like mentioned in https://github.com/uBlockOrigin/uBlock-issues/issues/3058#issuecomment-1877005118.

**Comment by krystian3w** [comment] 2024-03-12 12:15
Probably `uBlock-user` reported in the past bug with horizontal scroll (picker appeared slightly below it).

Anybody could check if forcing svh raised the picker on the PC with Firefox 101+ (not in Firefox 78.x/91.x ESR) and Chromium 108+.

**Closed** 2024-04-14 23:51 UTC
Labels: bug, Firefox-Android
