### ISSUE TITLE
Crash uBlock v1.17.3b4 | Linux x64 Chrome/72.0.3595.2

### ISSUE THREAD

**Issue by tron86** [uBlockOrigin/uBlock-issues#299] opened 2018-11-03 12:55 UTC
### Prerequisites
all sites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Optional permission 'file:///*' is redundant with the required permissions;this permission will be omitted.
                     
                    {
   "author": "All uBlock Origin contributors",
   "background": {
      "page": "background.html"
   },
   "browser_action": {
      "default_icon": {
         "16": "img/icon_16.png",
         "32": "img/icon_32.png"
      },
      "default_popup": "popup.html",
      "default_title": "uBlock Origin dev build"
   },
   "commands": {
      "launch-element-picker": {
         "description": "__MSG_popupTipPicker__"
      },
      "launch-element-zapper": {
         "description": "__MSG_popupTipZapper__"
      },
      "launch-logger": {
         "description": "__MSG_popupTipLog__"
      }
   },
   "content_scripts": [ {
      "all_frames": true,
      "js": [ "/js/vapi.js", "/js/vapi-client.js", "/js/contentscript.js" ],
      "matches": [ "http://*/*", "https://*/*" ],
      "run_at": "document_start"
   }, {
      "all_frames": false,
      "js": [ "/js/scriptlets/subscriber.js" ],
      "matches": [ "http://*/*", "https://*/*" ],
      "run_at": "document_idle"
   } ],
   "default_locale": "en",
   "description": "__MSG_extShortDesc__",
   "icons": {
      "128": "img/icon_128.png",
      "16": "img/icon_16.png",
      "32": "img/icon_32.png",
      "64": "img/icon_64.png"
   },
   "incognito": "split",
   "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1apZ9Qi2M6vC55vLxUQ/wUJnMr0g6kfKpk2Ge9QLkyGkwJRSGr1X5Wzv8euXbnlukG3f6eecFmVuNvaS6aZbTWG9bLbSWe/OC1hDBiooVBUjZO0TuogHIqBtTi2RRmdaySXeDmCTLbu1vs7jn70flCMwrd8wKKvGf25UqH/70FJTwfPOiGLmyrifafanrBNzR4ZdtBvkoaJhgxJ19C+n0eWUTg8dOpnozKbTWoeualPefoJis8xqPKZq3Hoa2JhNuTLyKe8YHIWInT6OIeFJBZwtbT0BNx22TQz5l522B4tGbL9K9w6JwIldXo8rXchfXppCjXTwz4HdAr+g6FBFeQIDAQAB",
   "manifest_version": 2,
   "minimum_chrome_version": "51.0",
   "name": "uBlock Origin development build",
   "optional_permissions": [ "file:///*" ],
   "options_ui": {
      "open_in_tab": true,
      "page": "dashboard.html"
   },
   "permissions": [ "contextMenus", "privacy", "storage", "tabs", "unlimitedStorage", "webNavigation", "webRequest", "webRequestBlocking", "\u003Call_urls>" ],
   "short_name": "uBlock₀ dev build",
   "storage": {
      "managed_schema": "managed_storage.json"
   },
   "update_url": "https://clients2.google.com/service/update2/crx",
   "version": "1.17.3.4",
   "web_accessible_resources": [ "/web_accessible_resources/*" ]
}
 

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.17.3b4
* Browser Name and version: Chrome/72.0.3595.2
* Operating System and version: Lubuntu 18.10 x64

**Comment by uBlock-user** [comment] 2018-11-03 13:04
Duplicate of  https://github.com/uBlockOrigin/uBlock-issues/issues/294

> Optional permission 'file:///*' is redundant with the required permissions;this permission will be omitted.

@gorhill

**Closed** 2018-11-03 13:05 UTC
Labels: duplicate
