### ISSUE TITLE
uBlock chrome window is truncate to a single long unreadable vertical line

### ISSUE THREAD

**Issue by acetriper** [uBlockOrigin/uBlock-issues#2814] opened 2023-09-12 19:25 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

<img width="35" alt="Screenshot 2023-09-12 at 21 14 20" src="https://github.com/uBlockOrigin/uBlock-issues/assets/24705126/c1ac8340-eb74-4622-af2c-d3c1f6a15163">

Ublock usually works well, at some point when I click on the uBlock extension icon in chrome I get only one single long unreadable vertical line as you can see in the screenshot.

This happens also when using the extension in incognito mode without other extensions. 

If I reset it to defaults the window behaviour is back to normal, when I restore my backup of settings, again the window is truncate to a single long unreadable vertical line.

What could be in the settings or settings file that can cause this?

I have accumulated settings that worked well for me and do not want to start from scratch because of this.

Any possible solutions? 

Thank you,

A Ben 

### A specific URL where the issue occurs.

https://github.com/uBlockOrigin/uBlock-issues/issues/new?template=bug_report_from_ubo.yml&configuration=%3Cdetails%3E%0A%0A%60%60%60yaml%0AuBlock+Origin%3A+1.52.0%0AChromium%3A+116%0Afilterset+%28summary%29%3A%0A+network%3A+98108%0A+cosmetic%3A+42607%0A+scriptlet%3A+18581%0A+html%3A+0%0Alistset+%28total-discarded%2C+last-updated%29%3A%0A+removed%3A%0A++plowe-0%3A+null%0A+added%3A%0A++ISR-0%3A+1770-0%2C+now%0A++NLD-0%3A+2902-10%2C+now%0A+default%3A%0A++user-filters%3A+25-12%2C+never%0A++easylist%3A+70589-14%2C+now%0A++easyprivacy%3A+33248-67%2C+now%0A++ublock-badware%3A+7975-145%2C+now%0A++ublock-filters%3A+34689-147%2C+now%0A++ublock-privacy%3A+547-5%2C+now%0A++ublock-quick-fixes%3A+260-194%2C+now%0A++ublock-unbreak%3A+2133-37%2C+now%0A++urlhaus-1%3A+5870-0%2C+now%0Afilterset+%28user%29%3A+%5Barray+of+25+redacted%5D%0Atrustedset%3A%0A+added%3A+%5Barray+of+1438+redacted%5D%0A+removed%3A%0A++chrome-extension-scheme%0AswitchRuleset%3A%0A+added%3A+%5Barray+of+8+redacted%5D%0AuserSettings%3A+%5Bnone%5D%0AhiddenSettings%3A+%5Bnone%5D%0AsupportStats%3A%0A+allReadyAfter%3A+1854+ms%0A+maxAssetCacheWait%3A+21+ms%0A%60%60%60%0A%3C%2Fdetails%3E

### Steps to Reproduce

1. use my own settings file which worked well for a very long period of time.
2. window truncated.
3. restore to defaults - issue gone.

### Expected behavior

when I click on the icon the uBlock window should appear normally and give me the options to use on the current page.

### Actual behavior

since the window is not properly displayed I can not choose any options of activity for uBlock.

### Configuration

configuration is my settings file

**Comment by gorhill** [comment] 2023-09-12 19:30
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2762>.

**Comment by acetriper** [comment] 2023-09-12 23:46
Hi, this is not a duplicate of:
https://github.com/uBlockOrigin/uBlock-issues/issues/2762.
As I am not using chromebook, but macbook pro. 
And I do not have the advanced settings clicked on.
So the same problem result is happening for a different reason.
Could you reopen the case?
Thank you

**Comment by gorhill** [comment] 2023-09-13 00:03
> Could you reopen the case?

No.

Follow the [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1282790) and add to it if you want to help Chromium devs investigate a solution.

**Comment by gorhill** [comment] 2023-09-13 00:14
Are you using a high page zoom value in Chrome settings?

**Comment by acetriper** [comment] 2023-09-13 00:25
I tried now from zoom 100% - 150% same result.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/13/23,
02:24:35 AM

**Comment by gorhill** [comment] 2023-09-13 00:32
I can reproduce a thin popup panel when using page zoom 150%+ in Chromium settings on my monitor. I changed one line of CSS in the popup panel to work around this. See with next dev build whether this works on your side.

**Comment by acetriper** [comment] 2023-09-13 01:22
i'm not on the dev channel, so I guess I would need to install a
separate dev chrome to test it?
When do not change my zoom per page but I go to the general chrome
settings, indeed if its over 150% its one line, if its 125% its still not
displayed correctly but you can see all of the uBlock window + extra an
part that should not be there



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
09/13/23,
03:20:35 AM

**Comment by tkp206093** [comment] 2023-09-16 20:27
Same in 
Microsoft Edge
Version 117.0.2045.31 (Official Build) (64-bit)
uBlock Origin 1.52.0

**Comment by gorhill** [comment] 2023-10-01 23:41
Closing due t lack of feedback.

**Closed by gorhill** 2023-10-01 23:41 UTC
Labels: bug
