### ISSUE TITLE
doesn't show the list

### ISSUE THREAD

**Issue by AroKol78** [uBlockOrigin/uBlock-issues#2629] opened 2023-04-30 12:29 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

- major - all `eye` icons don't work (other icons work) - opens a new tab but doesn't show the list
- minor - `uBlock filters – Resource abuse`= **0** ?

![Screenshot_2023-04-30-13-47-04](https://user-images.githubusercontent.com/70756447/235352584-28c01cd2-94b9-4721-9640-dc3c53585cdb.JPG)

### A specific URL where the issue occurs.

-

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

-

### uBO version

1.49.0

### Browser name and version

FF 112.2.0

### Operating System and version

Android

**Comment by gorhill** [comment] 2023-04-30 12:34
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2271>.

**Closed by gorhill** 2023-04-30 12:34 UTC

**Comment by gorhill** [comment] 2023-04-30 12:35
> Resource abuse = 0

Yes, we are making some change to default filter listset, and resource abuse has been merged with _"uBlock -- Privacy"_. Resource abuse will be removed when majority of people are using 1.49.0 -- we are still receiving reports with people using 1.48.x.
