### ISSUE TITLE
Checkbox to display (filter) temporary rules only

### ISSUE THREAD

**Issue by pintassilgo** [uBlockOrigin/uBlock-issues#1075] opened 2020-05-29 03:11 UTC
[enhancement request]

As a medium mode user, I'm used to change a bunch of rules in panel before I open "My rules" to review changes before saving them. I currently have more than 500 rules and even row highlighting is no longer optimal to find unsaved rules.

I would like to suggest adding a checkbox next to filter input as an alternative filter to display only temporary rules, i.e. the ones that differs from permanent rules.

I'm aware of lock icon, but I like to always open "My rules" because if it's not the first time I'm allowing some host, I merge the two rules into a global rule (`* host.tld * noop`).

Thanks.

**Comment by gwarser** [comment] 2020-05-29 09:17
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/604

**Closed** 2020-05-29 09:20 UTC
Labels: duplicate, enhancement
