### ISSUE TITLE
Crunchyroll Ads Not Being Blocked 

### ISSUE THREAD

**Issue by rushilmehra** [uBlockOrigin/uBlock-issues#702] opened 2019-08-13 17:46 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
On Chrome 76, ever since the removal of the enable-network-service flag, ads have been showing up on crunchyroll for me. There was another thread a couple days ago about this, so I tried the "crunchyroll.com##+js(setInterval-defuser, onAdVideoStart)" filter, but that did not help. HOWEVER, this problem is rather specific and very very odd. For example, if I click on the "shows" tab and watch any random anime - I WON'T GET ANY ADS. If I go to a show that I am currently watching (either from the queue OR search) then I will get an ad. The weird thing is, that if I log into crunchyroll in INCOGNITO mode, the ads go away ENTIRELY. 

[Description of the bug or feature]

### A specific URL where the issue occurs
https://www.crunchyroll.com/hunter-x-hunter/episode-59-bid-x-and-x-haste-611505?t=152
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Add a show to your queue
2. [Second Step] Click through it so it is "watched"
3. [Third Step] Go to the queue and try and watch the NEXT episode in the series

### Expected behavior: Ads should not appear

[What you expected to happen]

### Actual behavior: Ad appears

[What actually happened]

### Your environment

* uBlock Origin version: 1.21.6
* Browser Name and version: Chrome 76
* Operating System and version: Mac OSX 10.14.6

**Comment by rushilmehra** [comment] 2019-08-13 17:48
Upon further testing, **as soon as you add a show to your queue, ads will appear for that show. This problem is directly died to the queue. For some reason the problem ceases to exist in incognito mode.**

**Comment by llacb47** [comment] 2019-08-13 17:52
This is a filter issue.

**Comment by uBlock-user** [comment] 2019-08-13 17:54
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/689

**Closed by uBlock-user** 2019-08-13 17:54 UTC

**Comment by gwarser** [comment] 2019-08-28 09:09
> as soon as you add a show to your queue, ads will appear for that show.

I cannot reproduce.
