### ISSUE TITLE
Adding the @media operator

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#2185] opened 2022-07-22 17:03 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Sometimes the layout of a page changes depending on its width.

For example: https://mail.ru

<details>
<summary>Screenshot</summary>

![mail](https://user-images.githubusercontent.com/20126984/180488077-4c0f634b-6b13-4e01-aed1-cd0a11e4dce2.jpg)
</details>

In this case, the same cosmetic rules act differently. This leads to the need to have an adaptive way of applying the rules.

I propose to add an operator for @media: https://developer.mozilla.org/en/docs/Web/CSS/@media

### A specific URL where the issue occurs

https://mail.ru

### Steps to Reproduce

unknow

### Expected behavior

unknow

### Actual behavior

unknow

### uBlock Origin version

uBlock Origin development build 1.43.1b7

### Browser name and version

Google Chrome 103.0.5060.134

### Operating System and version

Windows 7

**Comment by gorhill** [comment] 2022-07-22 17:45
What would be the specific filter you need here?

**Comment by dimisa-RUAdList** [comment] 2022-07-22 19:57
In this case, you need to get rid of the logo branding (VK). For this I planned to use:
```
mail.ru##.grid__lcol > .mailbox-container > .logo > .logo__img--vk:style(background-size: auto 40px !important; background-position: 135% 50% !important)
mail.ru##.grid__lcol > .mailbox-container > .logo > .logo__img--vk > .logo__text:style(display: block !important; width: 78px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important)
```
But when the width changes, these rules don't move the target elements as intended.

Yes, I know, can use:
`mail.ru##+js(remove-class, logo__img--vk, .logo__img, complete)`

But this results in flickering of the logo, which can be just as annoying for users as the branding. Partially flickering can be removed with:
`mail.ru##.grid__lcol .logo__img--vk:style(opacity: 0 !important)`

But even so, there will be a delay in the appearance of the logo. So I had the idea of adding the @media operator.

Then the rule will look like:
`mail.ru##@media (min-width: *****px) .grid__lcol ***`

**Comment by gorhill** [comment] 2022-07-22 21:01
> Then the rule will look like:
>  `mail.ru##@media (min-width: *****px) .grid__lcol ***`

How about:

    mail.ru##:matches-media (min-width: *****px) .grid__lcol ***

JS-side, uBO would just leverage [Window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) to implement the operator, in which case a match would result in the operator being a passthru, and a non-match would result in an empty set.

**Comment by dimisa-RUAdList** [comment] 2022-07-22 21:04
The syntax for me is not of fundamental importance, the main thing is the very possibility of using a new operator.

**Comment by uBlock-user** [comment] 2022-07-23 14:02
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2100 ?

**Comment by gorhill** [comment] 2022-07-23 14:09
I don't know whether this would also address #2100, I haven't investigated whether the browser properly runs content scripts when rendering the page for printing. The request here is to address filtering issues, while #2100 was not a filtering issue but rather a personal request which I generally decline.

**Comment by uBlock-user** [comment] 2022-07-23 14:32
seems we can't set display property via `:matches-media()` - 

`example.com##body:matches-media((display: block))` appears invalid

This is for a case where body is hidden when trying to print - `https://gakufu.tunegate.me/music/CT00379`

because of a style rule present in inline style - 

```
@media print {
    body { display: none !important; }
} 
```

**Comment by gorhill** [comment] 2022-07-23 14:39
I don't see `(display: block)` as being a valid media query, there is no documentation for `display`.

**Comment by gorhill** [comment] 2022-07-23 14:47
This works:

    gakufu.tunegate.me##body:style(display: block !important)

**Comment by uBlock-user** [comment] 2022-07-23 14:51
Yeah it's used with `print`  here but unfortunately they haven't document any example with that.

> gakufu.tunegate.me##body:style(display: block !important)

That works, very nice.

**Comment by gorhill** [comment] 2022-07-23 14:55
> because of a style rule present in inline style -

If you want to apply specific style for specific media query, you need to use the form:

    example.com##body:matches-media(print):style(display: block)

In any case, this doesn't work for the specific case you provide because I don't think procedural operators are re-run when printing, I believe the browser just starts to apply `@media print` internally. For uBO to work in this case would require to convert `:matches-media` operator-based filters into declarative CSS rules, something which I mention in the commit, but this would require more work.

**Comment by dimisa-RUAdList** [comment] 2022-07-23 17:13
Unfortunately, the new operator `:matches-media()` does not work as well as I expected. The flickering of the logo is observed, characteristic of the `remove-class`. It is this flickering that I wanted to avoid with the new operator.
<details>
<summary>Video uBO media</summary>

![ubo media](https://user-images.githubusercontent.com/20126984/180615312-f710c3d8-2e42-4d59-b38b-b0dff9d49441.gif)</details>

I used:
```
mail.ru##.grid__lcol:matches-media((min-width: 1317px)) .logo__img--vk:style(background-size: auto 40px !important; background-position: 135% 50% !important)
mail.ru##.grid__lcol:matches-media((min-width: 1317px)) .logo__img--vk > .logo__text:style(display: block !important; width: 78px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important)
```
If we add similar rules to AdGuard:
```
mail.ru#$#@media (min-width: 1317px) {.grid__lcol > .mailbox-container > .logo > .logo__img--vk {background-size: auto 40px !important; background-position: 135% 50% !important;}}
mail.ru#$#@media (min-width: 1317px) {.grid__lcol > .mailbox-container > .logo > .logo__img--vk > .logo__text {display: block !important; width: 78px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important;}}
```
You can see that the rules work instantly, and there is no flicker.
<details>
<summary>Video AdGuard media</summary>

![adg media](https://user-images.githubusercontent.com/20126984/180615331-9c3f2e44-0944-4d9b-94c9-9180231a648d.gif)
</details>

Is it possible to achieve the same smooth operation with uBO?

**Comment by gorhill** [comment] 2022-07-23 18:01
> Is it possible to achieve the same smooth operation with uBO?

I've been working in the mean time to generate declarative CSS where possible when using `:matches-media()`, and this seems to work. The problem though is that the logger doesn't handle well such declarative `:matches-media()` occurrences and I don't think I want to get into this now, so what I can do for now is support declarative `:matches-media()` where possible but these instances won't be reported in the logger.

**Comment by dimisa-RUAdList** [comment] 2022-07-23 18:42
With this kind of rule, the logo still flickers. And as I said, it is the flickering that I am trying to get rid of. But I still want to thank you for the speed of implementation.

**Comment by gorhill** [comment] 2022-07-23 18:46
> the logo still flickers

Yes, the improvements are still not committed.

**Comment by dimisa-RUAdList** [comment] 2022-07-24 22:09
I installed version 1.43.1b9 and now the rules work instantly. But when resizing the window, when I use several rule options, they start to interfere with each other.

```
! min-width: 1521px >>>
mail.ru##.grid__lcol .logo__img--vk:matches-media((min-width: 1521px)):style(background-size: auto 40px !important; background-position: 90px 50% !important)
mail.ru##.grid__lcol .logo__img--vk > .logo__text:matches-media((min-width: 1521px)):style(display: block !important; width: 78px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important)
! min-width: 1317px >>>
mail.ru##.grid__lcol .logo__img--vk:matches-media((min-width: 1317px)):style(background-size: auto 40px !important; background-position: 90px 50% !important)
mail.ru##.grid__lcol .logo__img--vk > .logo__text:matches-media((min-width: 1317px)):style(display: block !important; width: 78px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important)
! min-width: 1253px >>>
mail.ru##.grid__lcol .logo__img--vk:matches-media((min-width: 1253px)):style(background-size: auto 40px !important; background-position: 75px 50% !important)
mail.ru##.grid__lcol .logo__img--vk > .logo__text:matches-media((min-width: 1253px)):style(display: block !important; width: 60px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important)
! min-width: 1189px >>>
mail.ru##.grid__lcol .logo__img--vk:matches-media((min-width: 1189px)):style(background-size: auto 40px !important; background-position: 75px 50% !important)
mail.ru##.grid__lcol .logo__img--vk > .logo__text:matches-media((min-width: 1189px)):style(display: block !important; width: 60px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important)
! min-width: 1069px >>>
mail.ru##.grid__lcol .logo__img--vk:matches-media((min-width: 1069px)):style(background-size: auto 40px !important; background-position: 60px 50% !important)
mail.ru##.grid__lcol .logo__img--vk > .logo__text:matches-media((min-width: 1069px)):style(display: block !important; width: 60px !important; height: 40px !important; opacity: 1 !important; position: absolute !important; right: 0 !important; top: 15px !important; background-color: #005ff9 !important)
```

**Comment by gorhill** [comment] 2022-07-24 22:17
> they start to interfere with each other.

There is no guarantee of order about where the rules will appear in the generated stylesheet. You will need to use `(min-width: ...px) and (max-width: ...px)` if you want to be sure one single CSS rule apply on a given width range.

**Comment by dimisa-RUAdList** [comment] 2022-07-24 22:22
Can I have a specific example of the syntax, based on my rules, how to use it?

**Comment by krystian3w** [comment] 2022-07-25 10:14
Maybe possible move stable css declarations outside matches-media (css minify operation).

Then will override unstable width and background-position (also I found `background-position-x` in CSS spec).

**Comment by dimisa-RUAdList** [comment] 2022-07-25 10:25
@gorhill 
Found a problem. In version 1.43.1b9 + [BitBlock](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/bitblock.txt&title=RU%20AdList:%20BitBlock), the rule stopped working: 
`rbc.ru,sportrbc.ru##.l-sticky:has(.forecast:empty) ~ .js-news-feed > .news-feed:style(top: 166px !important)`

Example: `https://www.rbc.ru/`

The purpose of this rule is to remove the indentation in the left column, in cases where the forecast is blocked (using [BitBlock](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/bitblock.txt&title=RU%20AdList:%20BitBlock)).

At the same time, when using the Element picker, the rule works, but only until the page is refreshed.

**Comment by uBlock-user** [comment] 2022-07-25 10:48
@dimisa-RUAdList try force updating the list where the rule is present.

**Comment by dimisa-RUAdList** [comment] 2022-07-25 10:52
@uBlock-user 
The problem is not the lack of an up-to-date version of the filter. The rule is displayed in the logger. And the rule does not work, even if you add it to My filters.

**Comment by uBlock-user** [comment] 2022-07-25 11:02
> The problem is not the lack of an up-to-date version of the filter.

My issue was, after the update, one `:remove()` filter couldn't be disabled any way whatsoever, so force updated the list and the regression went away.

**Comment by dimisa-RUAdList** [comment] 2022-07-25 11:06
This is probably some other problem not related to `rbc.ru`.

**Comment by krystian3w** [comment] 2022-07-25 12:15
Maybe now procedural css is rechecked too rare.

PS. These still fine: #89 & #1247 so regression isn't huge.

**Comment by gorhill** [comment] 2022-07-25 13:50
> the rule stopped working

Found the issue, caused by some changes I made. I will publish a fix shortly.

**Comment by dimisa-RUAdList** [comment] 2022-07-25 14:43
@gorhill 
Now everything works as it should. Both on `mail.ru` and `rbc.ru`. Great job!

**Closed** 2022-07-25 15:41 UTC
Labels: enhancement

**Comment by eladkarako** [comment] 2022-08-05 08:45
doesn't seems to be working for `print` though..  

<hr/>

not sure if it is related,  
since I haven't tested manipulating `StyleSheet` or `StyleSheetList` object directly,  
but chromium and ff seems to ignore injected styles that had `@media` in it,  
when actually printing (either to printer or to pdf).

the only way I have managed to inject a style that actually effected the `print` state,  
is by injecting a link with `media` attribute set to print.  

I.E. `<link href=".." media="print" rel="stylesheet"/>`  
where the inline rules were just `pre{white-space:pre-line !important;}`  
(again, without using `@media`).

**Comment by uBlock-user** [comment] 2022-08-05 09:12
> pre

Does "pre" exist on GitHub ? uBO can only manipulate styles of elements that exist, it cannot create new elements.

**Comment by krystian3w** [comment] 2022-10-19 12:35
Maybe possible add range in media:

<picture>
			<source type="image/webp" srcset="https://caniuse.bitsofco.de/image/css-media-range-syntax.webp">
			<source type="image/png" srcset="https://caniuse.bitsofco.de/image/css-media-range-syntax.png">
			<img src="https://caniuse.bitsofco.de/image/css-media-range-syntax.jpg" alt="Data on support for the css-media-range-syntax feature across the major browsers from caniuse.com">
</picture>

https://caniuse.com/css-media-range-syntax
https://developer.chrome.com/blog/media-query-range-syntax/

**Comment by gorhill** [comment] 2022-10-19 12:43
Not yet supported by csstree: <https://github.com/csstree/csstree/issues/143>

**Comment by krystian3w** [comment] 2022-11-10 09:33
https://github.com/uBlockOrigin/uAssets/issues/8451

**Comment by krystian3w** [comment] 2023-06-16 17:01
For these should be converted:

`https://www.postcourier.com.pg`
