### ISSUE TITLE
Can hide blocking page

### ISSUE THREAD

**Issue by xmha97** [uBlockOrigin/uBlock-issues#2576] opened 2023-04-02 11:00 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi, please add an option to hide this page.

![Screenshot_2023-04-02-14-26-34-179_org mozilla fenix](https://user-images.githubusercontent.com/23485114/229348724-410308e6-a718-4425-b05d-62fe89eb2c08.jpg)

### A specific URL where the issue occurs.

.

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

...

### uBO version

.

### Browser name and version

.

### Operating System and version

.

**Comment by gwarser** [comment] 2023-04-02 11:35
If it's not caused by a popup, then sorry, but no.

I think you may want some other add-on like <https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng/>, which should work on mobile.

**Comment by gwarser** [comment] 2023-04-02 11:38
If you can create your own list, you can hide the `<body>` tag by cosmetic filtering, but it will be also easy to disable, so...


Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/232

**Closed by gwarser** 2023-04-02 11:38 UTC

**Comment by gorhill** [comment] 2023-04-02 11:39
Closing as invalid as there are no repro steps, no explanation on how that page was reached, and it it was opened programmatically by a another site then that would be a filter issue.

**Comment by krystian3w** [comment] 2023-04-03 06:34
Perhaps he wants to block the opening of (P)orn pages - As if the address bar is broken (ignoring the go/enter button).

He may be an addict or has detected that his children are looking there and the uBo pop-up is too weak to discourage. But I suspect that there is not enough API in MV2 to make clicking enter or the go button deactivated at the address bar level.

**Comment by gwarser** [comment] 2023-04-03 06:54
That's why I recommended the LeechBlock.

**Comment by krystian3w** [comment] 2023-04-03 06:55
But these also have modal instead break action after click enter/go button if are not hidden in advanced settings.
