### ISSUE TITLE
Element Picker Doesn't Respond

### ISSUE THREAD

**Issue by BlazeFTL** [uBlockOrigin/uBlock-issues#3338] opened 2024-08-13 03:02 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

[Screenshot_20240813-085724_Spark Launcher](https://github.com/user-attachments/assets/b3940f6b-f282-4aa5-adc8-c850848886cc)
There Seems To Fixed Space (Below Pink/Red Area) Where Element Picker Doesnt Work...This Seems To Be From New FireFox Nightly UI Update
A Video Showcasing The Issue 
https://github.com/user-attachments/assets/8dde7743-5d5f-459f-9771-b66415592b83

### uBO version

Latest Beta

### Browser name and version

FF Nightly 131.0a1

### Operating System and version

Android 13

**Comment by garry-ut99** [comment] 2024-08-13 09:56
Similiar to / or related to / or duplicate of:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1805

If it's not the same issue, then maybe your issue is caused by `Scroll to hide toolbar` (which is enabled by default) : https://github.com/uBlockOrigin/uBlock-issues/issues/3058#issuecomment-1877005118, if you have it enabled, then disable it and see whether the issue still occurs or not.

<hr>

> **A specific URL where the issue occurs.**
> An exact URL is MANDATORY for an issue affecting a web page, even if it happens "everywhere".

You skipped some steps in issue template, you should always provide URL, because it might turn out to be related to a specific websites, like here: https://github.com/uBlockOrigin/uBlock-issues/issues/1805.

**Comment by BlazeFTL** [comment] 2024-08-13 13:14
> caused by `Scroll to hide toolbar`

You Are Right... Disabling It Fixes It...

I Removed Link Because I Can Reproduce It In Every Website

**Closed** 2024-08-13 18:44 UTC
