### ISSUE TITLE
Not working anymore after Firefox update due to missing verification

### ISSUE THREAD

**Issue by jdpoenisch** [uBlockOrigin/uBlock-issues#560] opened 2019-05-05 19:54 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

add-on not working anymore

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

Please consider getting this add-on signed because it is great!

* uBlock Origin version: 1.18.16
* Browser Name and version: Firefox 66.0.3 (64-Bit)
* Operating System and version: Windows 10

**Comment by gorhill** [comment] 2019-05-05 19:57
> I performed a cursory search of the issue tracker to avoid opening a duplicate issue 

Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/558>.

**Closed by gorhill** 2019-05-05 19:57 UTC
Labels: duplicate
