### ISSUE TITLE
Navigating a large site with many small images makes browser and OS unresponsive when blocking both images and JavaScript

### ISSUE THREAD

**Issue by tomasz1986** [uBlockOrigin/uBlock-issues#2422] opened 2022-12-23 11:16 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The problem happens only when both "Block media elements larger than" is set to "0 KB" and "Disable JavaScript" is enabled at the same time. When using only one of the two settings, the site loads and can be scrolled with no issues. However, when both of them are enabled, the site does still load immediately, yet as soon as you try to scroll down, the Chromium browser basically hangs, making the whole operating system completely unresponsive. This state lasts for ~1 minute, and only then the browser and the system becomes responsive. However, if you try to scroll the site one more time, it immediately becomes unresponsive again.

Disclaimer: The URL is my own website. I hope that it is appropriate to link it here. There are no ads or any user tracking scrips on the site. There is a JS script that is used to hide and unhide elements, however the site itself is designed to work fine without JS as well.

Profiles:

- [Profile-20221223T120013-block-both-images-and-js.json.zip](https://github.com/uBlockOrigin/uBlock-issues/files/10294595/Profile-20221223T120013-block-both-images-and-js.json.zip)
- [Profile-20221223T121051-block-only-images.zip](https://github.com/uBlockOrigin/uBlock-issues/files/10294605/Profile-20221223T121051-block-only-images.zip)
- [Profile-20221223T121205-block-only-js.zip](https://github.com/uBlockOrigin/uBlock-issues/files/10294608/Profile-20221223T121205-block-only-js.zip)

### A specific URL where the issue occurs.

https://twilczynski.com/windows/updates

### Steps to Reproduce

1. Open the linked URL.
2. Try to scroll down a bit.
3. See the browser (and the whole OS) become unresponsive.
4. Wait for ~1 minute (may depend on the hardware) for the browser to come back to life.
5. Try to scroll again for the problem to recur.

### Expected behavior

The site should load and scroll smoothly regardless of whether images and JS are disabled or not, especially since the problem doesn't happen when using each of the two settings separately.

### Actual behavior

As soon as you attempt to scroll the site, the browser and the OS become unresponsive. It takes a good ~1 minute for them to become responsive again. Attempting to scroll the site again leads to the same unresponsiveness. In other words, the website is unusable with the two settings enabled at the same time.

### uBO version

1.45.2

### Browser name and version

Chromium 108.0.5359.125 (64-bit)

### Operating System and version

Windows 10 Enterprise 21H2 (build 19044.2251)

**Comment by gwarser** [comment] 2022-12-23 12:35
Unable to reproduce on Linux at all. 

In VM in Win10 I see increased CPU usage, but it disappears as soon as I stop scrolling.

From what I can see, your profiling does not show any heavy uBO code, it does not show any heavy code at all. There seems to be only some browser/GPU/compositor tasks running continuously which can be related.

**Comment by tomasz1986** [comment] 2022-12-23 12:56
Interesting. I will try to test this on a completely different system to see if the problem happens there too then.

For the record, the current hardware is AMD Ryzen 4350G using the integrated GPU with the newest drivers from AMD. The browser is a completely clean install with a new profile. All settings both in the browser and in uBlock Origin are default (with the exception of the two causing the issue).

On a side note, the problem doesn't happen when images and JS are disabled in the browser settings instead of in uBlock.

**Comment by gorhill** [comment] 2022-12-23 13:26
I couldn't reproduce any performance issue, scrolling is fast and even locked to the mouse. Profiling data for `Profile-20221223T120013-block-both-images-and-js.json.zip` shows:

![Screenshot from 2022-12-23 08-18-48](https://user-images.githubusercontent.com/585534/209342887-50d15d7c-8565-4fa5-a78d-7b1ea1ec1d07.png)

In aggregate uBO's CPU usage in measured at ~30ms, which represent a fraction of percent out of the ~5,150ms from outside uBO, while the rest of the 88,000ms is all measured as idle.

Closing as invalid. There is profiling information as requested regarding performance issue claims, but there is no demonstration and analysis of the profiling data showing that uBO is the issue.

**Closed by gorhill** 2022-12-23 13:26 UTC
Labels: unable to reproduce

**Comment by tomasz1986** [comment] 2022-12-23 13:43
I've just tried to reproduce this on a much weaker device (Intel Core M-5Y71, integrated GPU, same OS and browser version) and the site loaded and scrolled super fast with no hiccups there. This does appear to be a system/hardware-specific issue then. Thank you @gwarser for pointing at the GPU 👍. I'm now going to try experimenting with reinstalling the graphics driver and see whether there is any improvement.
