### ISSUE TITLE
Ublock Origin does not hide an element based on general rule, only site specific

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#809] opened 2019-12-05 22:35 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ublock Origin does not hide an element called `###euConsent` on `https://www.virustotal.com/` when a general rule to hide it is applied. It can only be hidden by using a site specific rule `www.virustotal.com###euConsent`.

Here is a screenshot. Note! That element is only visible if you are living inside Europen Union.

![67633368-bfacfe80-f8b7-11e9-83c5-4a88b722b2f5](https://user-images.githubusercontent.com/17256841/70279986-39da7800-17c0-11ea-9dc8-59c4d4728877.png)

### A specific URL where the issue occurs

`https://www.virustotal.com/`

### Steps to Reproduce

1. Add rule: `###euConsent`
2. Go to `https://www.virustotal.com/`
3. Notice how that element is not hid.
4. Add rule `www.virustotal.com###euConsent` and notice how it makes a difference

### Expected behavior:

That element would be hid.

### Actual behavior:

The element was not hid.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 71.0
* Operating System and version: Windows 10

**Comment by gwarser** [comment] 2019-12-05 22:37
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/803

**Comment by peace2000** [comment] 2019-12-05 22:38
Sorry. Just realised that by myself too.

**Closed by gwarser** 2019-12-05 22:37 UTC
