### ISSUE TITLE
Feature Request : Use per-site switches with whole domain

### ISSUE THREAD

**Issue by clavelc** [uBlockOrigin/uBlock-issues#1862] opened 2021-12-07 13:20 UTC
### Description

When using [Per-site switches](https://github.com/uBlockOrigin/uBlock-issues/wiki/Per-site-switches), it would be nice to have a way to apply the rule (ie. allow JavaScript when it is globally disabled) to the whole domain instead of the current site. Maybe pressing a key before clicking. 

This would prevent having to click the button many times in a row in sites which redirect you via http://www.domain.com/ http://login.domain.com/ http://auth.domain.com etc... 

It might actually be beneficial to set this as the default behavior, as dynamic rules will then take over to block scripts from subdomains if needed anyway.

### uBlock Origin version

1.39.2

### Browser name and version

Firefox 94

### Operating System and version

Linux

**Comment by clavelc** [comment] 2021-12-07 13:21
(sorry for the layout, the form is not adapted to feature requests)

**Comment by gorhill** [comment] 2021-12-07 13:56
Duplicate of <https://github.com/gorhill/uBlock/issues/3297>.

**Closed by gorhill** 2021-12-07 13:56 UTC
Labels: duplicate
