### ISSUE TITLE
Feature: invert the custom rules to a list "allowed to filter"

### ISSUE THREAD

**Issue by membersound** [uBlockOrigin/uBlock-issues#1534] opened 2021-03-21 13:07 UTC
I'd love to configure uBlock to be passive most of the time, but filter adds *only* on predefined websites.

My usecase is that I'm running a local DNS Adblock in my network, but still would like to use uBlock to be active on only some pages, like youtube.com

**Comment by gorhill** [comment] 2021-03-21 13:51
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/586>.

[I wrote recently](https://www.reddit.com/r/uBlockOrigin/comments/ltmqrd/only_block_specific_sites/gozotkc/):

> That is not a feature supported by uBO. uBO is for people who share the view that the net is hostile by default and consequently uBO being disabled everywhere by default is incompatible with this view -- it would make no sense to have a malware list enabled by default just to have uBO disabled everywhere by default. AdGuard supports this mode, so you may want to use this instead.

**Closed** 2021-03-21 13:51 UTC
Labels: duplicate
