### ISSUE TITLE
Conflicted with another extension called WebRTC Protect

### ISSUE THREAD

**Issue by Mishasama** [uBlockOrigin/uBlock-issues#1928] opened 2022-01-13 17:13 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

After the recent uBO update. The uBO conflicted with another extension called WebRTC Protect. It makes the WebRTC Protect reports there is another extension controlling the settings.

### A specific URL where the issue occurs

https://add0n.com/webrtc-protect.html

### Steps to Reproduce

1. Install both uBO and WebRTC Protect.
2. Open a new page.
3. See the WebRTC Protect reports.

### Expected behavior

They should not conflict with each other. And keep all IP not leaked by WebRTC.

### Actual behavior

The WebRTC Protect reports there is another extension controlling the settings. And the WebRTC was leaking the IPs.

### Configuration

<details>

```yaml
uBlock Origin: 1.40.4
Chromium: 95
filterset (summary): 
  network: 98029
  cosmetic: 57481
  scriptlet: 19422
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/easylistchina.txt: 25257-16, 3d.3h.9m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt: 1894-2, 3d.3h.8m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt: 63-63, 3d.3h.7m
    https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt: 516-3, 1d.5h.51m
    CHN-0: 27372-25298, 3d.3h.13m
    ublock-annoyances: 4361-9, 3d.3h.6m
  default: 
    JPN-1: 5688-13, 3d.3h.12m
    easylist: 62817-495, 3d.3h.11m
    easyprivacy: 26613-92, 3d.3h.10m
    plowe-0: 3682-825, 11d.7h.20m
    ublock-abuse: 76-0, 1h.45m
    ublock-badware: 3658-67, 2d.19h
    ublock-filters: 30140-175, 1d.1h.50m
    ublock-privacy: 186-4, 1d.1h.48m
    ublock-unbreak: 1716-44, 1d.1h.47m
    urlhaus-1: 8135-0, 17h.46m
filterset (user): [array of 17 redacted]
trustedset: 
  added: [array of 22 redacted]
  removed: 
    chrome-scheme
    edge-scheme
    wyciwyg-scheme
switchRuleset: 
  added: [array of 6 redacted]
urlRuleset: 
  added: [array of 7 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 5819 ms (selfie)
```
</details>

**Comment by u-RraaLL** [comment] 2022-01-13 17:31
Try this:

1. Back up your settings: https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section
2. Edit the file.
3. Find `webrtcIPAddressHidden: true` inside, remove it and save.
4. Restore from backup.

Does it work now?

**Comment by gwarser** [comment] 2022-01-13 17:59
>It makes the WebRTC Protect reports there is another extension controlling the settings.

How does it look like? 

Did you ever changed WebRTC settings manually in your browser? Which browser it is?

**Comment by gorhill** [comment] 2022-01-13 18:08
> Find webrtcIPAddressHidden: true inside, remove it and save

It's not necessary, uBO does not touch webrtc setting in the browser, we have to emphasize this.

Which exact browser are you using? Brave is reportedly interfering with webrtc setting, and people misattribute this to uBO -- uBO no longer ever touch webrtc setting since 1.38.0.

**Comment by Mishasama** [comment] 2022-01-13 20:17
> > Find webrtcIPAddressHidden: true inside, remove it and save
> 
> It's not necessary, uBO does not touch webrtc setting in the browser, we have to emphasize this.
> 
> @Mishasama,
> 
> Which exact browser are you using? Brave is [reportedly interfering with webrtc setting](https://www.reddit.com/r/uBlockOrigin/comments/rn97r3/webrtc_leak_when_using_vpn_with_ublokorigin_active/), and people misdiagnose this to uBO -- uBO no longer ever touch webrtc setting since 1.38.0, so it's just impossible that it interferes.

Chrome 95.0.4638.69
I see the Wiki says uBO does not touch WebRTC anymore. But it seems after the not touch update, the WebRTC protect report conflicted. They both work fine before.

> Try this:
> 
> 1. Back up your settings: https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section
> 2. Edit the file.
> 3. Find `webrtcIPAddressHidden: true` inside, remove it and save.
> 4. Restore from backup.
> 
> Does it work now?
> 
> If it didn't work, perhaps you need to change the setting to `false` instead of removing it.

Not work.

**Comment by gorhill** [comment] 2022-01-13 21:18
I couldn't reproduce a conflict as per your repro steps, and it's expected since uBO does not touch that setting.

You are failing to provide key information:

> - Open a new page.

Which exact web page? This is important to test exactly the same way.

>  - See the WebRTC Protect reports.

How does that look like? There is no popup panel for the WebRTC Protect extension. Where is that report? Provide screenshot.

**Comment by gwarser** [comment] 2022-01-13 21:24
@Mishasama do you see this: 

![image](https://user-images.githubusercontent.com/886325/149411293-b9b048af-fe2c-4c95-8eb7-7cac04b605be.png)

?

Do you have any other add-ons? (Check puzzle piece icon!)

**Comment by Mishasama** [comment] 2022-01-14 03:46
> I couldn't reproduce a conflict as per your repro steps, and it's expected since uBO does not touch that setting.
> 
> You are failing to provide key information:
> 
> > * Open a new page.
> 
> Which exact web page? This is important to test exactly the same way.
> 
> > * See the WebRTC Protect reports.
> 
> How does that look like? There is no popup panel for the WebRTC Protect extension. Where is that report? Provide screenshot.

Any page. That's no matter.

It looks like this.
![image](https://user-images.githubusercontent.com/54498172/149445740-7d59347b-ae64-452c-8a36-8e15b4613547.png)

> @Mishasama do you see this:
> 
> ![image](https://user-images.githubusercontent.com/886325/149411293-b9b048af-fe2c-4c95-8eb7-7cac04b605be.png)
> 
> ?
> 
> Do you have any other add-ons? (Check puzzle piece icon!)

I have other extensions. But only WebRTC Protect is activating. And this problem was gone after disabling uBO.

**Comment by gorhill** [comment] 2022-01-14 10:43
> problem was gone after disabling uBO

You will have to report to Chromium devs then, uBO does **not** touch the `chrome.privacy.network.webRTCIPHandlingPolicy`, so it makes no sense that the browser would report that uBO is using it -- and so far nobody has else has reported such issue, except for those who keep misdiagnosing the issue as originating from uBO. Please file your issue here: <https://bugs.chromium.org/p/chromium/issues/entry>.

> I have other extensions

Please provide screenshot showing all your extensions from `chrome://extensions/` and screenshot showing the issue (as @gwarser provided above), and screenshot of exactly the same but without uBO enabled.

**Comment by uBlock-user** [comment] 2022-01-14 11:55
OP has another webRTC extension installed -- https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml hence the browser behaviour.

**Comment by gorhill** [comment] 2022-01-14 11:57
That's @gwarser's screenshot. But I don't see any other explanation that there is another extension interfering.

**Comment by uBlock-user** [comment] 2022-01-14 11:58
Yeah I was misled as I didn't have the page scrolled enough up to realise that.

**Comment by uBlock-user** [comment] 2022-01-14 12:14
> I have other extensions.

List them all individually @Mishasama

**Comment by gorhill** [comment] 2022-01-15 13:25
Closing as invalid due to failure to provide more information after asked to list all extensions and provide actual evidence with screenshots.

uBO does **not** touch that webrtc setting, hence unless magic is involved, the issue can't be uBO. Best explanation is that OP had another webrtc-controlling extension installed -- possibly <https://github.com/dlinbernard/webrtc-control/issues/3>.

**Closed by gorhill** 2022-01-15 13:25 UTC
Labels: unable to reproduce

**Comment by Mishasama** [comment] 2022-01-15 22:35
> > problem was gone after disabling uBO
> 
> You will have to report to Chromium devs then, uBO does **not** touch the `chrome.privacy.network.webRTCIPHandlingPolicy`, so it makes no sense that the browser would report that uBO is using it -- and so far nobody has else has reported such issue, except for those who keep misdiagnosing the issue as originating from uBO. Please file your issue here: https://bugs.chromium.org/p/chromium/issues/entry.
> 
> > I have other extensions
> 
> Please provide screenshot showing all your extensions from `chrome://extensions` and screenshot showing the issue (as @gwarser provided above), and screenshot of exactly the same but without uBO enabled.
> 
> Also mind providing other important details such as whether this involves incognito tabs/windows, and whether you changed settings in `chrome://flags`.


![040116071248](https://user-images.githubusercontent.com/54498172/149639729-fa3282af-96a4-4f6d-a24d-8b9f84975829.png)
![040116072416](https://user-images.githubusercontent.com/54498172/149639730-bbc861eb-9061-438b-941e-0617dbe8b47c.png)
![040116072516](https://user-images.githubusercontent.com/54498172/149639732-bdf107d9-9370-4e18-85a8-bb8e66f14660.png)
![040116072524](https://user-images.githubusercontent.com/54498172/149639733-518d51d0-545b-405c-b36a-643f7970567b.png)
![040116073102](https://user-images.githubusercontent.com/54498172/149639736-fec6cefd-e78e-4cba-b823-d6fbde749904.png)

**Comment by Mishasama** [comment] 2022-01-15 22:36
> > I have other extensions.
> 
> List them all individually @Mishasama

![QQ截图040116070223](https://user-images.githubusercontent.com/54498172/149639767-b750cdfd-73f4-4833-897e-f11d3d9ba4d9.png)
![QQ截图040116070247](https://user-images.githubusercontent.com/54498172/149639769-038b5106-0c9b-4333-9238-99b6f0ec3b16.png)
![QQ截图040116070302](https://user-images.githubusercontent.com/54498172/149639770-65a60d6c-7831-4579-b80a-7787de237010.png)
![QQ截图040116070353](https://user-images.githubusercontent.com/54498172/149639772-afa8d9ad-e879-43ea-8a6a-412ce797712d.png)
![QQ截图040116070408](https://user-images.githubusercontent.com/54498172/149639773-8cd4b0ce-ecb3-477b-9167-0968ab746beb.png)
![QQ截图040116070420](https://user-images.githubusercontent.com/54498172/149639774-1138e03a-f23a-4585-a8de-abdf04533a5d.png)
![QQ截图040116070436](https://user-images.githubusercontent.com/54498172/149639777-41abaf28-eb8b-4253-924e-1af4a414173a.png)
![QQ截图040116070452](https://user-images.githubusercontent.com/54498172/149639778-3b14f309-441e-4d58-8257-f55a01ab4b7f.png)

**Comment by Mishasama** [comment] 2022-01-15 22:43
Sorry too busy for the late reply.

**Comment by gorhill** [comment] 2022-01-15 22:45
As said, file an issue with Chromium devs, what you say is happening can't happen.

**Comment by gwarser** [comment] 2022-01-15 22:48
Did you enabled everything in `chrome://flags/`???

**Comment by gorhill** [comment] 2022-01-15 23:20
> Try creating new profile and test there.

> - [X] using a new, unmodified browser profile

**Comment by uBlock-user** [comment] 2022-01-16 06:28
@gorhill He has 3 WebRTC specific extensions installed - WebRTC Control, WebRTC Leak Prevent, WebRTC Protect IP Leak, 

There's the cause of your issue @Mishasama

**Comment by u-RraaLL** [comment] 2022-01-16 06:30
> He has 3 WebRTC specific extensions installed - WebRTC Control, WebRTC Leak Prevent, WebRTC Protect IP Leak,

Aren't they disabled?

**Comment by uBlock-user** [comment] 2022-01-16 06:35
He disabled them now, or were they disabled when the issue occurred ?

**Comment by gorhill** [comment] 2022-01-16 11:43
From now on, the only way to report such issue without being immediately closed as _invalid_ is to show that the code at [this line](https://github.com/gorhill/uBlock/blob/554241be46891c12a0d23ba1799856aba1822b64/platform/common/vapi-background.js#L157) is being executed by putting a breakpoint at that line and posting a screenshot of the breakpoint being taken. This can happen only on Firefox Mobile.

**Comment by gorhill** [comment] 2022-02-05 16:59
There has been new development on this curious issue: <https://www.reddit.com/r/uBlockOrigin/comments/sl7p74/disabling_webrtc/hvptao8/>. It appears the browser is caching the information that an extension is toggling on a setting and reused that cached information to make the assumption that the setting is still toggled by the extension despite not being the case. There is a workaround for this, which is to make an explicit API call to make clear that uBO is not using the API. This will be in next release.
