### ISSUE TITLE
Stop pcmag Video autoplay (From Reddit)

### ISSUE THREAD

**Issue by purevertigo** [uBlockOrigin/uBlock-issues#1624] opened 2021-06-12 04:39 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Can't stop autoload of video

pcmag.com/news/slaying-the-cable-monster-what-you-need-to-know-about-hdmi-cables

### A specific URL where the issue occurs

pcmag.com/news/slaying-the-cable-monster-what-you-need-to-know-about-hdmi-cables

### Steps to Reproduce

1. View Page

### Expected behavior:

Player, paused or blocked.

### Actual behavior:

Player not paused or blocked.

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Chrome 91
* Operating System and version: Windows 10

**Comment by gorhill** [comment] 2021-06-24 14:03
I realize this is a duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/610> after all.

**Closed by gorhill** 2021-06-24 14:03 UTC
Labels: something to address
