### ISSUE TITLE
[Suggestion] Provide visual cue for temporary rules

### ISSUE THREAD

**Issue by sofutru** [uBlockOrigin/uBlock-issues#712] opened 2019-08-29 03:52 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

(If you don't accept Pull Requests or Features Requests, can we at least suggest some?

Currently, when setting up some temporary rules for a website, the popup displays a padlock to validate these changes definitively. However there is no way of telling which rules are the temporary ones directly from the popup panel: which one has been changed from its original state and therefore will be committed when I click on the padlock? Providing a visual cue, like a special border colour, would allow to review these temporary rules before validating them.

Visual: http://i.imgur.com/ViNYL87.jpg

another suggestion is to show round border on temporary rules, like this:
https://camo.githubusercontent.com/236bb56fb8ebda7a6d1de5d3091fa95b1dcdcdd8/687474703a2f2f692e696d6775722e636f6d2f636761766d546f2e706e67

@gorhill this is the remake of [this](https://github.com/gorhill/uBlock/issues/86) issue, so you can close it there.

**Comment by gwarser** [comment] 2019-08-29 08:03
Duplicate of https://github.com/gorhill/uBlock/issues/86

I will close this one. It's still good to be here for searching.

BTW, looks like good enhancement, however I never got _lost_ in overview panel.

Maybe not rounded corners (ugly), but this question mark on the middle may be used for something.

**Closed by gwarser** 2019-08-29 08:03 UTC
Labels: enhancement
