### ISSUE TITLE
global onMouseDown handler doesn’t handle SVG links

### ISSUE THREAD

**Issue by flying-sheep** [uBlockOrigin/uBlock-issues#777] opened 2019-11-08 14:07 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Ublock origin attaches a `onMouseDown` event handler which has the assumption that `elem.href` is serializable. That assumption is wrong for `SVGElement`s, where `.href` is a `SVGAnimatedString`, not a js string, so an exception is thrown whenever a SVG link is clicked.

### Details

In contentscript.js, there’s the event handler `onMouseClick` added to every `onMouseDown` event, which calls `vAPI.messaging.send` with `elem.href`:

```js
vAPI.messaging.send('contentscript', {
  what: 'maybeGoodPopup',
  url: elem.href || '',
});
```

`send` in turn calls <code><a href="https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/Port">Port</a>.postMessage</code>, which expects `msg` to be serializable:

```js
port.postMessage({ channel, msgId, msg });
```

As said above, `onMouseClick` violates that expectation by passing an `SVGAnimatedString` when a SVG link is clicked.

### A specific URL where the issue occurs

`https://mermaidjs.github.io/#/flowchart?id=interaction`

### Steps to Reproduce

1. Go to URL
2. Open dev tools and activate “Pause on exceptions” in the debugger
3. Click on the green B in the graph looking like this: 
![grafik](https://user-images.githubusercontent.com/291575/68482180-427b7500-0239-11ea-84f4-cca65cc1b5ee.png)

### Your environment

* uBlock Origin version: 1.23.0
* Browser Name and version: Firefox 70.0.1
* Operating System and version: Arch Linux, current

**Comment by flying-sheep** [comment] 2019-11-08 14:24
@uBlock-user this will happen in all standards-compliant browsers, not just Firefox.

**Comment by uBlock-user** [comment] 2019-11-08 14:24
@flying-sheep can't reproduce on Chromium 80. No exception is thrown.

**Comment by flying-sheep** [comment] 2019-11-08 15:01
Maybe Chrome serializes SVGAnimatedString as regular string … anyway I’m pretty sure that’s not standard behavior. Could be wrong though.

**Comment by flying-sheep** [comment] 2019-11-08 15:02
@gorhill I think we should handle the SVGAnimatedString case by retrieving `elem.href.baseVal`.

**Comment by gorhill** [comment] 2019-11-08 15:07
That code is to prevent false positives, a rare occurrence; I consider it's not worth to add code to deal with a edge case in case of another edge case. I will revisit if ever there is an actual case justifying supporting this.

**Comment by flying-sheep** [comment] 2019-11-08 15:13
OK, makes sense!

**Comment by flying-sheep** [comment] 2019-11-08 16:00
Should be fixed by 067ef5843c182c1fa08112dc0daff1276fc1ce29 then?

**Comment by gorhill** [comment] 2019-11-08 16:52
Yes, this will be in the next dev build.

**Comment by gwarser** [comment] 2019-11-08 17:30
In worst case, if `popup` filter exist for this href URL (`||github.com^$popup` for this example), new tab opened from this link by middle/ctlr click will be closed.

**Closed** 2019-11-08 17:35 UTC
Labels: Firefox, bug, fixed
