### ISSUE TITLE
1.16.15b0 reset ads list after restart

### ISSUE THREAD

**Issue by runboy93** [uBlockOrigin/uBlock-issues#136] opened 2018-07-19 14:01 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Custom filter lists get deactivated after browser restart

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

Open uBlock 1.16.15b0 version.

On the settings tab, go to filters and use custom (url) filters, add some.

You should see that those lists are in use now. Alright, restart browser and go to back settings, if you see same as I do, then you see 0/0 filters in use (uBlock report), lists down below on custom URL list, show normally.

### Expected behavior:

Just like with earlier build I've used (1.16.14 stable), ads list should work normally as they always do.

### Actual behavior:

Added custom ads lists (Fanboy Ultimate, kiss filters), uBlock show that they are activated, looks normal for this point.

Restarted browser again, and already see something strange 0/0 ads blocked after little browsing.

Then went to check filter options, they are still activated. But uBlock show that 0/0 filters activated, quite strange.

### Your environment

* uBlock Origin version: 1.16.15b0
* Browser Name and version: Firefox Android 60
* Operating System and version: Android 8.0

**Comment by runboy93** [comment] 2018-07-19 14:03
And this is only problem with this new build (1.16.15b0), 1.16.14 stable, earlier build works normally.

**Comment by uBlock-user** [comment] 2018-07-19 14:04
Did you enable Private Browsing enabled ?

**Comment by runboy93** [comment] 2018-07-19 14:04
Enabled on all pages.

**Comment by uBlock-user** [comment] 2018-07-19 14:07
Duplicate of https://github.com/gorhill/uBlock/issues/3071

**Comment by gwarser** [comment] 2018-07-19 14:48
What is "kiss filters" and how much free disk space you have.

**Comment by uBlock-user** [comment] 2018-07-19 14:53
He probably meant the ones by [Yumire](https://github.com/Yumire/kiss-filters)

**Comment by gorhill** [comment] 2018-07-19 18:31
I imported `https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts` as an external list, quit Firefox, launched Firefox, and all filters were still loaded in uBO 1.16.15b0.

**Comment by gorhill** [comment] 2018-07-20 02:11
It just occurred to me. If loading from a selfie, all is ok, but as soon as a list update, the issue occur. I will push a fix as soon as possible. I think the issue is that Firefox for Android does not support the `commands` API, and uBO tests for `commands.update` at launch time, this was added in the last version.

**Closed** 2018-07-20 02:13 UTC
Labels: Firefox, information needed

**Comment by gorhill** [comment] 2018-07-20 12:02
Reading through OP comment again, I see that the repro steps were properly provided -- I failed to understand the issue correctly. I read it as custom filter lists showing 0/0 (which is what I looked at), while it was the aggregate sums that were 0/0.
