### ISSUE TITLE
Tor Browser 11.0.1 on Linux - missing Preferences

### ISSUE THREAD

**Issue by jurekb** [uBlockOrigin/uBlock-issues#1855] opened 2021-12-03 11:22 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Tor Browser 11.0.1 on Linux
After installation of uBlock Origin 1.39.2. there is no Preferences to          configure it.
open Tor Browser - Settings - Extensions - uBlock Origin - ... - Manage - ???
Also, Customize Toolbar - no uBO item to add/drag
Also, Details (in comparison to regular Firefox browser) are limited.

### A specific URL where the issue occurs

https://manjaro.org

### Steps to Reproduce

start Tor Browser
install UBO
try to configure (Preferences)

### Expected behavior

Preferences present

### Actual behavior

no Preferences

### uBlock Origin version

1.39.2

### Browser name and version

Tor Browser 11.0.1

### Operating System and version

Linux ArchLinux

**Comment by uBlock-user** [comment] 2021-12-03 11:53
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1833

**Closed by uBlock-user** 2021-12-03 11:53 UTC
