### ISSUE TITLE
Spoof or block HTTP referral header

### ISSUE THREAD

**Issue by j-james** [uBlockOrigin/uBlock-issues#1663] opened 2021-07-18 05:23 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

(The issue is present after disabling uBlock Origin in the browser.)

The HTTP referral header leaks potentially identifying and frequently unwanted information about the user. 

### A specific URL where the issue occurs

https://www.google.com/search?q=test+your+referrer+url+vividata

### Steps to Reproduce

1. Open the specific url above.
2. Click on the first link in the search results: https://members.vividata.ca/test-your-referrer-url/
3. Observe that the previous site can be found from the [HTTP referrer](https://en.wikipedia.org/wiki/HTTP_referer).

### Expected behavior

uBlock Origin could add blocking the HTTP referral header as a privacy setting.

There is (to my knowledge) no upside to the referral header, from a user experience.

### Actual behavior

The referral header is not blocked or spoofed, and sites can find out the previous page you visited. This has privacy implications, particularly around fingerprinting - but more generally, it's just excess information that is usually used in a bad way.

Here's an example of the referral header being used for malicious purposes (click on the article link, potentially NSFW): https://news.ycombinator.com/item?id=3132752

### uBlock Origin version

1.36.2

### Browser name and version

Ungoogled Chromium 91.0

### Operating System and version

Arch Linux 5.12

**Comment by uBlock-user** [comment] 2021-07-18 06:03
Duplicate of https://github.com/gorhill/uBlock/issues/3604

**Closed by uBlock-user** 2021-07-18 06:03 UTC

**Comment by j-james** [comment] 2021-07-18 06:07
@uBlock-user Would you mind leaving open this one instead? Discussion is locked on the old issue tracker.

**Comment by uBlock-user** [comment] 2021-07-18 06:32
>  Discussion is locked on the old issue tracker.

You just commented here, so no need to keep it open.

**Comment by j-james** [comment] 2021-07-18 06:41
Right, but it gets confusing if all discussion happens under a closed issue.

If not no worries.

**Comment by gorhill** [comment] 2021-07-18 12:56
I was looking at this one recently and investigated what could be done, and came to the conclusion the safest approach would be to simply expose the [setting `referrersEnabled`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites) as a global privacy setting.

**Comment by baptx** [comment] 2022-07-22 18:25
Since uMatrix is not supported anymore, it would be nice to have the same switch "Spoof Referer header" in uBlock.
Related: https://github.com/gorhill/uBlock/issues/3604

**Comment by j-james** [comment] 2022-07-22 19:46
Note that Firefox and now Ungoogled Chromium allow disabling the referer in their flags.

**Comment by baptx** [comment] 2022-08-05 17:36
@j-james I heard that but it would be nice to have a per site setting so we can quickly disable it for a site only if there is an issue. Blocking the Referer HTTP header can also be done with an addon like Header Editor (which supports request and response headers) but it is less convenient than the uMatrix switch.
