### ISSUE TITLE
Does not update Malvertising list by Disconnect 

### ISSUE THREAD

**Issue by gallegonovato** [uBlockOrigin/uBlock-issues#936] opened 2020-03-09 08:32 UTC
### Prerequisites

X 

X 

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Does not update Malvertising list by Disconnect 
The link's broken. In ublock 1.25.0

### A specific URL where the issue occurs

ublock Malvertising list by Disconnect from the malware domains section and has a link https://s3.amazonaws.com/lists.disconnec*****/simple_malvertising.txt ?. It puts me like this:

https://ibb.co/g6Fq0Dj

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

ublock Malvertising list by Disconnect from the malware domains section and has a link https://s3.amazonaws.com/lists.disconnec*****/simple_malvertising.txt ?. It puts me like this:

https://ibb.co/g6Fq0Dj

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: Fennec 68.5.0
* Operating System and version: Nexus 6p with Lineageos 15.1

**Comment by uBlock-user** [comment] 2020-03-09 08:47
![Capture](https://user-images.githubusercontent.com/21290713/76196635-9d859e80-6210-11ea-8841-3a10d0be9c03.PNG)

Can you update any other filterlist ?

**Comment by gallegonovato** [comment] 2020-03-09 10:22
I don't update MVPS HOSTS 

https://ibb.co/CpLgGtT
https://ibb.co/mX8HSK9
https://ibb.co/xgJjGNg
https://ibb.co/80t452P
https://ibb.co/88vX4mh
https://ibb.co/TWg3RT1
https://ibb.co/TWg3RT1
https://ibb.co/xgJjGNg

**Comment by uBlock-user** [comment] 2020-03-09 10:27
Something on your end is blocking the network request, run the logger and try to update again.

**Comment by gorhill** [comment] 2020-03-09 11:34
Looks like something outside uBO is blocking the network requests to MVPS and Disconnect servers. You will have to find out on your side, network errors outside uBO can't be fixed by uBO.

**Comment by uBlock-user** [comment] 2020-03-09 12:26
Regarding MVPS - https://www.reddit.com/r/uBlockOrigin/comments/fftqt4/can_no_longer_connect_to_mvps_filter_list_due_to/

**Comment by gallegonovato** [comment] 2020-03-09 14:19
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +131 |  |  | 4b433ca4-626e-4e09-bc56-9bdde1534c24.moz-extension-scheme | 0,3 | xhr | `https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt?_=1` |
| +126 |  |  | 4b433ca4-626e-4e09-bc56-9bdde1534c24.moz-extension-scheme | 0,3 | xhr | `https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt?_=1` |
| +0 |  |  | 4b433ca4-626e-4e09-bc56-9bdde1534c24.moz-extension-scheme | 0,3 | xhr | `https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt?_=1` |
</details>

Re instaler ublock. Malvertising doesn't update

**Comment by gorhill** [comment] 2020-03-09 14:43
As said, logger output shows the issue is outside uBO, you need to investigate on your side what is blocking Disconnect's list, the logger shows uBO itself is not blocking it.

Here is the URL to the list: <https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt>.

Try loading it in the browser and if it fails you will need to investigate yourself why this happens.

Closing the issue as external since uBO is not causing your issue.

**Closed by gorhill** 2020-03-09 14:43 UTC
Labels: unable to reproduce
