### ISSUE TITLE
add support for Cent Browser new multilogin tab

### ISSUE THREAD

**Issue by jcvr1994** [uBlockOrigin/uBlock-issues#569] opened 2019-05-11 20:46 UTC
hi gorhill please add support for Cent Browser new multilogin tab does not block advertising https://www.centbrowser.com/

**Comment by gwarser** [comment] 2019-05-11 21:21
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/369

**Closed by gwarser** 2019-05-11 21:21 UTC
