### ISSUE TITLE
uBO Icon Blank White and sometimes blinks while page loads on Firefox when 'privacy.resistFingerprinting' = true

### ISSUE THREAD

**Issue by jjohns71** [uBlockOrigin/uBlock-issues#32] opened 2018-05-08 14:55 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When Firefox setting privacy.resistFingerprinting is set to 'true' in about:config, the uBO icon shows up as a white block. When a page is being loaded it sometimes flashes between the white block and the standard uBO icon.

When Firefox setting privacy.resistFingerprinting is set to 'false' there appears to be no issue. I believe this issue only started happening with the last 2 beta releases. (1.16.5b2 & 1.16.5b3)

Demo gif is below:
![demo01](https://user-images.githubusercontent.com/6795795/39764447-a0525744-52ad-11e8-88de-279821ee2e2f.gif)

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues

### Steps to Reproduce

1. Enable 'privacy.resistFingerprinting' to true in 'about:config' firefox options
2. Close and relaunch Firefox and observe the uBO icon is now a white box that sometimes flashes on page loads.

### Expected behavior:

uBO icon shows as normal.

### Actual behavior:

uBO icon is white block.

### Your environment

* uBlock Origin version: 1.16.5b3
* Browser Name and version: Firefox 59.0.3 (64 bit)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment] 2018-05-08 15:05
Can't reproduce on Nightly.

**Comment by uBlock-user** [comment] 2018-05-08 15:30
I'm able to reproduce it on the stable, it doesn't flicker but the icon turns into a white block when visiting the aformentioned URL

**Comment by jjohns71** [comment] 2018-05-08 15:37
FYI: For me it is white block everywhere, not just the posted link. 

Also, the flickering I described happens one time toward the end of the posted example gif after clicking on 'Features' link in the gif.

**Comment by uBlock-user** [comment] 2018-05-08 15:47
Yes, it happens everywhere although no flickering on my end. Probably a regression in the dev build.

**Comment by gorhill** [comment] 2018-05-08 15:58
Browser console reports:

> Blocked moz-extension://7a490fe4-6765-4415-95a1-925dc0e4e333/background.html in page moz-extension://7a490fe4-6765-4415-95a1-925dc0e4e333/background.html from extracting canvas data because no user input was detected. moz-extension://7a490fe4-6765-4415-95a1-925dc0e4e333/js/vapi-background.js:689.

uBO now uses canvas to generate the icon image data once which it then uses and reuses afterward. Apparently `resistFingerprinting` gets in the way of using canvas.

**Comment by uBlock-user** [comment] 2018-05-08 16:00
So it's specific to Stable version as that doesn't appear to be happening to Nightly ?

**Comment by gorhill** [comment] 2018-05-08 16:03
> So it's specific to Stable version as that doesn't appear to be happening to Nightly ?

Can this be confirmed? I use Nightly as my main browser, I try to not mess with it's current setting. If this works fine in Nightly, this means there is an issue somewhere in bugzilla about this. In any case, I could peek a pixel in the image data returned to find out whether the data is valid, and abort using image data if not.

**Comment by gwarser** [comment] 2018-05-08 17:10
https://bugzilla.mozilla.org/show_bug.cgi?id=1453916

**Comment by uBlock-user** [comment] 2018-05-08 17:19
According the last one listed, it's fixed in v61.

**Closed** 2018-05-08 19:01 UTC
Labels: Firefox bug
