### ISSUE TITLE
[Suggestion] Night Mode, I just give an idea.

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#65] opened 2018-06-09 06:17 UTC
### Description

[I was wondering if the developers could add a night mode and also "activate it automatically after a certain time of night". I'm not a developer, I just give an idea.]

If you are not interested in my idea, just close this Issue.

**Comment by uBlock-user** [comment] 2018-06-09 06:42
https://github.com/gorhill/uBlock/issues/1869

**Comment by uBlock-user** [comment] 2018-06-09 06:42
Duplicate of https://github.com/gorhill/uBlock/issues/1869

**Closed by uBlock-user** 2018-06-09 06:42 UTC
Labels: duplicate, enhancement
