### ISSUE TITLE
Non-specific cosmetic filters with explicit style properties

### ISSUE THREAD

**Issue by piotrjurkiewicz** [uBlockOrigin/uBlock-issues#324] opened 2018-12-02 17:44 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The documentation says:

"As with the other new cosmetic filtering selectors, the :style can be used only for specific cosmetic filters, i.e. there must be a hostname or entity specified for the filter."

It also says that:

"uBO is able to transparently convert and make use of the AdGuard's "CSS injection rules""

AdGuard, however, does not require these filters to be specific and allows CSS injection rules affecting all websites.

Is there a possibility to uBO to allow the same?

The use case which I think about is for example the Google's infamous 'async-hide' (https://developers.google.com/optimize/). Google promotes placing this code snippet in customer websites. It hides the whole web page (html object) until all Google-owned services become loaded. The problem is that this never happens when urls like `||www.googletagservices.com^` or `||www.google-analytics.com^` are blocked. So the snippet waits the whole 4 second timeout until it unhide website. During that time a blank page is being displayed. You can see this for example on http://www.bankier.pl (using clean settings with just the two rules from above).

`ublock-privacy` filter list deals with that by injecting JS code which tries to unhide website:

https://github.com/uBlockOrigin/uAssets/blob/be747839a7b4399c04102f5f49b995afdd9b334e/filters/resources.txt#L353

https://github.com/uBlockOrigin/uAssets/blob/be747839a7b4399c04102f5f49b995afdd9b334e/filters/resources.txt#L570

The same can be achieved in a cleaner and faster way using filter:

    bankier.pl##html:style(opacity: 1.0 !important)

However, the number of websites using 'async-hide' is so high, that specifying such a filter for each of them is impossible. The non-specific filter:

    ##html:style(opacity: 1.0 !important)

does not work in uBO, as said in documentation.

**Comment by mapx-** [comment] 2018-12-02 17:50
You could use (for all the polish pages)
`pl##html:style(opacity: 1.0 !important)`

**Comment by uBlock-user** [comment] 2018-12-02 17:52
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/131

**Closed by uBlock-user** 2018-12-02 17:52 UTC

**Comment by krystian3w** [comment] 2020-07-06 17:17
Now will work:

`*##html:style(opacity: 1.0 !important)`

A much wider range than the `pl##`.

**Comment by gorhill** [comment] 2020-07-06 23:40
I kind of missed the issue here.

The answer is that this is not an issue in uBO, GA and GTM scripts are redirected to neutered scripts which takes care to defuse the 4 second delays. Whoever still suffer those delays despite using uBO is typically because they are using some other content blockers overriding uBO's redirection.

**Comment by llacb47** [comment] 2020-07-06 23:52
Sometimes GTM is whitelisted, then the 4 second delay comes back. Example: 
```
https://www.reuters.com/news/us
https://www.action.com/en-gb/
(surely more)
```


Is this a problem that can be solved by uBo in some way or is this unavoidable since GTM was whitelisted to fix breakage?

**Comment by gorhill** [comment] 2020-07-07 00:49
I don't see any delay on these pages.
