### ISSUE TITLE
Ability to disable exception filters in third-party lists

### ISSUE THREAD

**Issue by lambic12** [uBlockOrigin/uBlock-issues#347] opened 2018-12-17 09:13 UTC
Hello, I see that my proposition is a duplicate of #3353, which is closed, but I have no other place to ask for it. 

As stated by gorhill "If ever your feature proves to be in high demand, I will reconsider." Well, it looks like approximatively 1 person every month opens an issue to ask for it, which looks not like a small demand. Anyway, I humbly add my voice to create this feature :)

I think I was not the only one to uncheck all exception filters in the legacy version of ABP for firefox, and still in Adblock Latitude in Pale Moon.

A feature to massively disable exception filters from lists (and not one by one with point-and-click or $badfilter) always have been to me a big lack in uBo, especially since uBo is supposed to give the power to the users and not to the filter makers. Also, uBo can disable all cosmetic filters (which have no privacy value) but not third-party lists exception filters (which have a big privacy value), it does not seem very logical ?

I understand this may be a lot of job but anyway...

**Comment by uBlock-user** [comment] 2018-12-17 09:50
You can post here - https://github.com/uBlockOrigin/uBlock-issues/issues/317

**Comment by uBlock-user** [comment] 2018-12-17 09:51
Duplicate of #3353

**Closed by uBlock-user** 2018-12-17 09:51 UTC
