### ISSUE TITLE
Adsbygoogle.js injectable does not validate whether iframe going to be injected is already exist or not

### ISSUE THREAD

**Issue by mmis1000** [uBlockOrigin/uBlock-issues#786] opened 2019-11-19 03:04 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Symptoms: Thousands of iframe created by ublock itself

What happened:

Some poorly written web page repeat

                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <ins class="adsbygoogle" style="display:block" width-responsive="true"></ins>
                    <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>

everywhere instead of only the \<ins\> tag.

And ublock inject iframes everytime when you are loading the script

Possibly violating code: https://github.com/gorhill/uBlock/blob/caa8e7d35ba61214a9d13e7d324b2bd2aa73237f/src/web_accessible_resources/googlesyndication_adsbygoogle.js#L38-L46

It inject iframe without checking whether it already exist or not

### A specific URL where the issue occurs

 https://www.esjzone.cc/detail/1563843171.html

### Steps to Reproduce
1. Make a HTML,
2. Paste `<ins class="adsbygoogle"/><script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>` about 20 ~ 30 times
3. Open it with ublock installed

### Expected behavior:

Nothing happened, as there is just several tags

### Actual behavior:

Ublock inject __thousands__ of iframes into the page, lag the page very seriously.  
You won't even able to open the firefox console

### Your environment

* uBlock Origin version: 1.23.0
* Browser Name and version: Firefox 70~72
* Operating System and version: Android/Windows/Mac

**Comment by uBlock-user** [comment] 2019-11-19 05:26
> Ublock inject thousands of iframes into the page, lag the page very seriously.
You won't even able to open the firefox console

I can't reproduce that but there 1300+ <iframe tags created, so this needs to be addressed.

**Comment by gorhill** [comment] 2019-11-19 13:32
I removed the offending filter for now. The fix to the scriptlet will be in the next release and given that this is fixed in "uBlock filters", this will not be an emergency fix. In hindsight, the generic redirect filter should not have been added in <https://github.com/uBlockOrigin/uAssets/commit/5a47c9567a182d8888d92865a4351afd0891d38d>.

**Comment by gorhill** [comment] 2019-11-19 14:05
So to be clear, the uBO/site interaction issue will be fixed after updating "uBlock filters" -- because uBO won't inject the neutered `adsbygoogle.js` scriptlet on that site.

The fix to the scriptlet itself will be in the next release.

**Closed** 2019-11-19 19:21 UTC
Labels: something to address
