### ISSUE TITLE
Block element missing from context menu in Chrome

### ISSUE THREAD

**Issue by Bison700** [uBlockOrigin/uBlock-issues#2187] opened 2022-07-26 12:05 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [x] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Occasionally the option »Block element« is missing from the context menu.
I need to deactivate and activate uBlock origin then to make it appear again.
Tested on multiple computers and the problem occurs since at least last year.

### A specific URL where the issue occurs

https://www.google.com/

### Steps to Reproduce

1. Open Chrome.
2. Right click anywhere for context menu.
3. Check that »Block element« is there.
4. Open a new incognito tab.
5. Close the incognito tab after waiting 10 seconds and return to the normal Chrome window.
6. Right click anywhere for context menu.
7. Check that »Block element« is missing.

### Expected behavior

In the context menu, the option »Block element« should still be there.

### Actual behavior

In the context menu, the option »Block element« is missing after using an incognito tab (and probably after other unknown actions).

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 84865
  cosmetic: 47581
  scriptlet: 17219
  html: 0
listset (total-discarded, last updated): 
  added: 
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1030-336, never
  default: 
    user-filters: 67-0, never
    DEU-0: 5894-1, never
    easylist: 68049-402, never
    easyprivacy: 27172-572, never
    plowe-0: 3639-0, never
    ublock-abuse: 75-0, never
    ublock-badware: 4171-91, never
    ublock-filters: 31779-109, never
    ublock-privacy: 222-2, never
    ublock-quick-fixes: 202-0, never
    ublock-unbreak: 1797-41, never
    urlhaus-1: 7285-0, never
filterset (user): [array of 67 redacted]
trustedset: 
  added: [array of 8 redacted]
  removed: 
    about-scheme
    chrome-extension-scheme
    chrome-scheme
    edge-scheme
    moz-extension-scheme
    opera-scheme
    vivaldi-scheme
    wyciwyg-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5266 ms
  maxAssetCacheWait: 101 ms
```
</details>

**Comment by gorhill** [comment] 2022-07-26 12:32
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/151>.

**Closed by gorhill** 2022-07-26 12:32 UTC

**Comment by Bison700** [comment] 2022-09-25 22:04
This is not an exact duplicate of the mentioned (fixed) issue and still persists to this day. It is not fixed.

It is very annoying as the »Block element« option is missing from the context menu every time an incognito tab is used (may not be limited to this case).

**Comment by Bison700** [comment] 2022-12-18 23:18
> Duplicate of #151.

Unfortunately the bug still persists, despite the fact that the issue this is said to be a duplicate of (#151) is marked as »fixed«.

Why is this issue marked as duplicate and getting closed, when it still persists?

**Comment by gorhill** [comment] 2022-12-19 00:54
#151 is still opened, which means it still need to be fixed. I removed the label.

> I have to deactivate and activate the extension

A better workaround is to simply use the block element icon from the popup panel.
