### ISSUE TITLE
You need to use a double click on the site in the Opera Speed Dial

### ISSUE THREAD

**Issue by Sonigith** [uBlockOrigin/uBlock-issues#1643] opened 2021-06-26 18:26 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Very often you have to double-click mouse on the website in the Speed Dial to open it

### A specific URL where the issue occurs

https://www.google.com/

### Steps to Reproduce

1. Install uBO
2. Fill the Speed Dial with your favorite sites
3. Try to open the Speed Dial with a new tab and use your favorite sites

### Expected behavior:

Should open the site with one click of the mouse

### Actual behavior:

Blocks opening on the first click

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Opera 77.0.4054.90
* Operating System and version: Windows 7 Professional Service Pack 1

**Comment by gwarser** [comment] 2021-06-27 02:38
Do you see something blocked in [The logger](https://github.com/gorhill/uBlock/wiki/The-logger)? Popup perhaps?

**Comment by gorhill** [comment] 2021-06-27 11:43
> express panel

What's that?

**Comment by Sonigith** [comment] 2021-06-27 18:39
> > express panel
> 
> What's that?

Sorry, Speed Dial

**Comment by gorhill** [comment] 2021-06-27 19:24
I can't reproduce, and there are no other such issue reported, so you will have to investigate more on your side, including beyond uBO, as it is disabled by default for the speed dial page.

**Comment by Sonigith** [comment] 2021-06-27 20:13
> I can't reproduce, and there are no other such issue reported, so you will have to investigate more on your side, including beyond uBO, as it is disabled by default for the speed dial page.

![1](https://user-images.githubusercontent.com/86386195/123558089-013d2d80-d7ae-11eb-83bc-2b37bc2cbe9e.PNG)

**Comment by Sonigith** [comment] 2021-06-27 22:32
As I understand it, it works when I have YouTube and Twitch open, there is a spam permanent blocking, and it works when I click on new sites

**Comment by gwarser** [comment] 2021-06-28 12:39
What is the exact URL of the page you are trying to open and you have problem with? How you are opening the page - in new tab / middle click / from the context menu? How you are opening the speed dial page?

Did you tried different mouse? 

I tried all default pages plus google, YT and wykop.pl; in same tab and in new tab by middle click -  no issues. I tried with clean whitelist - no issues. With no-popups switch - also no issues. Do you have some custom filter lists/filters?

1.35.2, Version:76.0.4017.177

**Comment by uBlock-user** [comment] 2021-06-28 13:02
uBO doesn't run in internal browser pages which is what Opera Speed Dial is, this is Opera's issue. you should file this on their tracker.

**Comment by gorhill** [comment] 2021-06-28 13:46
He posted a screenshot of a log entry for when visiting `google.ru`, that's not the speed dial page.

No case has been made that there is an issue with uBO, and frankly, given the very new GitHub account and hint at lack of technical knowledge, I am convinced this is a case where the user convinced himself of uBO being the issue, and blindly checking all the checkboxes as a result -- this has happened often lately ([example](https://github.com/uBlockOrigin/uBlock-issues/issues/1641#issuecomment-865215913)).

The issue should be closed as _invalid_, and if ever someone is able to **objectively** demonstrate uBO is the issue, it can be re-open.

These invalid issues are tiresome and grinding, I am seriously thinking of restricting the issue tracker to people who have a track record of filing valid issues, and Reddit can be used for those who suspect issues, at least there will be more people to root out invalid issues.

**Comment by uBlock-user** [comment] 2021-06-28 13:54
> He posted a screenshot of a log entry for when visiting google.ru, that's not the speed dial page.

As per the STR he goes to Speed Dial, clicks on the google tab which he added as per step 2 of the STR, expects one click will lead to `google.ru`(which is how it works in Chrome and Firefox) but instead he has to click twice on the thumbnail of Google tile located at the Speed Dial for the `google.ru` page to open, based on that the issue is with the Opera.

**Closed** 2021-06-28 13:55 UTC
Labels: unable to reproduce

**Comment by gorhill** [comment] 2021-06-28 19:45
> yes, as I understand it, it works when I have YouTube and Twitch open, there is a spam permanent blocking, and it works when I click on new sites

I don't understand what you are saying. What is "it" when you say "it works"? What is "spam permanent blocking"?

**Comment by Sonigith** [comment] 2021-06-28 19:46
> > yes, as I understand it, it works when I have YouTube and Twitch open, there is a spam permanent blocking, and it works when I click on new sites
> 
> I don't understand what you are saying. What is "it" when you say "it works"? What is "spam permanent blocking"?

when I have youtube and twitch open, I see permanent blocking in yellow in the logger, apparently at this moment when I click on my sites I get into this blocking
