### ISSUE TITLE
uBlock Origin is delayed: doesn’t start to filter ADS when I launch Chrome: I have to wait about a minute to see it in action.

### ISSUE THREAD

**Issue by MR-Diamond** [uBlockOrigin/uBlock-issues#287] opened 2018-10-26 09:11 UTC
I’m running the current latest version of uBlock Origin and of Google Chrome: uBlock Origin 1.17.0 installed on Google Chrome 70.0.3538.77 (Official Build) (64 bit) on Windows 7 Ultimante 64 bit. Seems not a filter issue, since I have the same setup on this environment/computer but using Firefox 63 with the same version of uBlock origin, and so on: the issue which I’m going to describe only occurs on Chrome. As I start Chrome and I go on a page that is usually full of ads [1], I can see all of them: if I go inside the options of uBlock Origin, in the “third party filters” tab, I notice that no filter is loaded: after about a minute the list is populated and so after this time, uBlock Origin starts to filter ads on the pages, after that I refresh the page and properly works: ads are filtered.

I tried to: disable all others extensions, to delete uBlock Origins cache ad also to uninstall and re-install uBlock Origin (a clean install), but the issue still occurs.
I also tried, as suggested by this template, to check into the logger [2]
At the moment I cannot start Chrome with another new profile, but if strictly necessary, I will do it soon on another computer whit the same setup.
In the meantime let me know which other tests I can do.

[1] http://www.notiziediprato.it/
[2] https://pastebin.com/raw/HNaNg3Yd

**Comment by uBlock-user** [comment] 2018-10-26 09:14
Duplicate of https://github.com/gorhill/uBlock/issues/1327

**Comment by uBlock-user** [comment] 2018-10-26 09:15
Do not remove the template, it's there for a reason.

**Closed by uBlock-user** 2018-10-26 09:14 UTC

**Comment by gorhill** [comment] 2018-10-26 11:55
Also, _"have to wait about a minute"_ is extremely doubtful. uBO is typically ready in less than a second after launch. Such statement is easily dispelled with the browser's performance tools: uBO's `background.html` => Performance => Reload button. This will profile uBO at launch. I get less than 2 seconds with a 12 y/o laptop with no more than 1GB memory.

**Comment by MR-Diamond** [comment] 2018-10-26 12:02
In facts, on the same environment (Windows 7 Ultimate 64 bit) on the same hardware (i5-3210m and 16 GB of ram), on Firefox, uBO loads almost immediately.
I cannot figure out what I have to do with "background.html"; where is located?

**Comment by uBlock-user** [comment] 2018-10-26 12:57
> where is located?

chrome://extensions/ => background.html => Performance => Reload button
