### ISSUE TITLE
connection to googletagmanager.com

### ISSUE THREAD

**Issue by fabi-hub** [uBlockOrigin/uBlock-issues#3464] opened 2024-11-23 22:22 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A connection to googletagmanager.com.
In uBlock googletagmanager.com is marked red, like 100% blocked.

### A specific URL where the issue occurs.

```yaml
https://www.macrumors.com/
```

### Steps to Reproduce

open https://www.macrumors.com/
uBlock shows googletagmanager.com as blocked.
I use nextdns to track the DNS connections and notice it is not blocked.

### Expected behavior

no connection to googletagmanager.com.
Or a connection and uBlock show googletagmanager.com in green or yellow.

Brave had the same problem 3y ago and fixed it https://github.com/brave/brave-browser/issues/14027

### Actual behavior

DNS connection to googletagmanager.com.
![goog](https://github.com/user-attachments/assets/75676a57-71ee-439f-b644-da88a6fb42e6)

### uBO version

1.61.0

### Browser name and version

Firefox

### Operating System and version

Windows 11

**Comment by gorhill** [comment] 2024-11-23 22:37
Duplicate of <https://bugzilla.mozilla.org/show_bug.cgi?id=1861889>.

**Closed by gorhill** 2024-11-23 22:37 UTC

**Comment by gorhill** [comment] 2024-11-23 22:39
> no connection to googletagmanager.com.

It's not a connection to `googletagmanager.com`, it's a query to your DNS server.
