### ISSUE TITLE
Request feature to clean redirections destination url

### ISSUE THREAD

**Issue by imTHAI** [uBlockOrigin/uBlock-issues#1870] opened 2021-12-10 15:25 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I would like the possibility to clean URL redirects **before** the destination URL

### A specific URL where the issue occurs

https://dealabs.digidip.net/visit?url=https%3A%2F%2Fwww.amazon.fr%2Fdp%2FB098K16RX5%3Fsmid%3DA1X6FK5RDHNB96

### Steps to Reproduce

Click on the given link.

### Expected behavior

I would like it cleans it to
https://www.amazon.fr/dp/B098K16RX5?smid=A1X6FK5RDHNB96

clearURLs add-on is able to do that.
[Here](https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/master/data.min.json) is their filter list. 
AdGuard is implementing this feature in a next version.

### Actual behavior

Currently it cleans after, so it's able to remove the &=tags
So all this part &ppref=https%3A%2F%2Fwww.dealabs.com%2Fbons-plans%2Fasus-zenbook-um425qa-14-fhd-amd-ryzen-7-5800h-ram-16go-512-go-w10-azerty-2256311

But I would like to remove https://dealabs.digidip.net/visit?url=

### uBlock Origin version

uBlock Origin 1.39.2

### Browser name and version

firefox 94.0.2 

### Operating System and version

MacOS

**Comment by gorhill** [comment] 2021-12-10 15:37
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/1784>.

**Closed by gorhill** 2021-12-10 15:37 UTC

**Comment by imTHAI** [comment] 2021-12-10 18:28
@gorhill sorry
