### ISSUE TITLE
uBO is leaking DNS (c name uncloak) again

### ISSUE THREAD

**Issue by ThurahT** [uBlockOrigin/uBlock-issues#1294] opened 2020-10-14 00:47 UTC
### Prerequisites

- [✅] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [✅] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [✅] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [✅] I am running the latest version of uBlock Origin
- [✅] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBO is leaking DNS (c name uncloak) again

### A specific URL where the issue occurs

https://old.reddit.com/ https://browserleaks.com/dns

### Steps to Reproduce

1. setup proxy (polipo/privoxy/tinyproxy) and config it to not do own DNS lookups
2. control proxy settings in uBO and FF
3. realize there is DNS leakage when cname is uncloaked in uBO and browserleak page confirms it

### Expected behavior:

uBO should not do DNS lookup when proxied

### Actual behavior:

It does on this machine

### Your environment

* uBlock Origin version: 1.30.2
* Browser Name and version: Firefox ESR 78.3.0esr (64-bit)
* Operating System and version: Devuan GNU/Linux 2.1 (ascii) x86_64 Kernel: 4.9.0-13-amd64 

Pictures:
01: cname uncloak (fastly) - https://i.imgur.com/NktShRP.png
02: uBO settings - https://i.imgur.com/C1tA2Je.png
03: FF settings - https://i.imgur.com/Ci5E2MG.png
04: browserleaks show my real DNS server plus the Tor one - https://i.imgur.com/z8LRasS.png

**Comment by gorhill** [comment] 2020-10-14 01:37
uBO just uses an API to resolve cname, it does not get to decide how the DNS requests are made.

**Comment by gorhill** [comment] 2020-10-14 02:01
Alright I will look at this when I get the time.

If you can investigate why [this does not work anymore](https://github.com/uBlockOrigin/uBlock-issues/issues/911#issuecomment-611480054) that would save me a lot of time -- I am feeling rather burdened at the moment.

**Comment by gorhill** [comment] 2020-10-14 15:10
Did you restart uBO after you changed your proxy settings?

**Comment by gwarser** [comment] 2020-10-14 15:20
This is fixed in Firefox 80, OP is using ESR 78 

https://bugzilla.mozilla.org/show_bug.cgi?id=1618271

**Comment by gorhill** [comment] 2020-10-14 15:50
Sure but there is [code in uBO to disable uncloaking when it detects a proxy](https://github.com/gorhill/uBlock/commit/11d24abea01fdb1c7070a2940dfda6e43cfe0c2c) -- until the fix makes it to Firefox stable.

On my side this workaround code still work fine.

**Comment by gorhill** [comment] 2020-10-14 17:04
Ok I'm hard of understanding... I will have to download 78 and test again. Also, the workaround code should execute only for versions of Firefox below 80.

**Comment by gorhill** [comment] 2020-10-14 17:22
I tried with 78.3.1esr and I could not reproduce. This is the proxy settings I used:

![a](https://user-images.githubusercontent.com/585534/96023359-4e47c200-0e20-11eb-9d53-0c53be4fd7d6.png)

**Comment by ThurahT** [comment] 2020-10-14 21:48
Yes, I followed this issue 6 month ago with uBO 1.25.0 and the fix (1.25.x (can't remember)) solved it for ESR 68.x back then. 
I tested with three different profiles and same issue on all of them (they have different privacy/security settings).

FF ESR got upgraded to 78.x last weekend or so, and I noticed this issue was back as of yesterday. It is very strange that it got introduced again. But yes. I will disable cname for now and wait for FF 80+.

**Comment by gorhill** [comment] 2020-10-14 22:36
How do your proxy settings differ from those in my screenshot?

**Comment by ThurahT** [comment] 2020-10-14 23:37
They're the same. Except I have mine filled with localhost and ports of course, as seen in picture 3.

**Comment by Kein** [comment] 2020-10-16 06:31
I cant repro it, set
```
cnameUncloak true
cnameUncloakProxied true
```
Set DNS to be resolved through proxy (shadowsocks). Tested on 
https://dnsleaktest.com/
and
https://browserleaks.com/dns
No leakage. 

Firefox 81

**Comment by gorhill** [comment] 2020-10-16 09:31
@Kein Well of course, the purpose of `cnameUncloakProxied` when set to `true` is to bypass the built-in protection. Leave to `false` if you do not want uBO to uncloak when a proxy is detected.

**Comment by Kein** [comment] 2020-10-16 09:38
Does not make any difference

**Comment by gorhill** [comment] 2020-10-16 09:54
@Kein **Provide exact steps to reproduce**, one by one without leaving a single one out. I could not reproduce on my side, and when I see "I cant repro it, set `cnameUncloak true`"  which is obviously going to cause the issue by design, then I will require that you take the time and efforts to provide exact repro steps if you are going to argue it makes no difference. Asking me to keep testing again and again with no additional quality information provided is not going to work.

**Comment by Kein** [comment] 2020-10-16 09:58
I'm not asking you to do anything, I just pointed out I cant reproduce the case OP mentioned either on FF81, that all.

**Comment by gorhill** [comment] 2020-10-16 10:18
Duh sorry, I read your "I can't" as "I can". Sorry for the confusion.

**Comment by ThurahT** [comment] 2020-10-16 23:29
Well, I am utterly confused now.. I have two other profiles (same Firefox 78.3.0 ESR) that uses the ghacks pants user.js stuff. And those do not leak DNS. But when I look at the stuff in about:config regarding proxy settings they are exactly the same as the non ghacks profile that do leak DNS and made me report this in the first place.. I do not understand it. I will wait for FF 80+ and see if they really fixed it or nah. But it seems so since people can't reproduce it. As for this issue I am fine about it being closed as can't reproduce and firefox bug. TIA for your time. And thank you for uBO.

**Closed** 2020-10-19 15:25 UTC
Labels: Firefox, external, unable to reproduce

**Comment by CyberMan571** [comment] 2021-07-20 09:24
> I cant repro it, set
> 
> ```
> cnameUncloak true
> cnameUncloakProxied true
> ```
> 
> Set DNS to be resolved through proxy (shadowsocks). Tested on
> https://dnsleaktest.com/
> and
> https://browserleaks.com/dns
> No leakage.
> 
> Firefox 81

Do never forget ISP(ISS) and OS changeable!
They can send fake (request and response) data
