### ISSUE TITLE
With 1.23.1b1 not a single website opens!

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uBlock-issues#764] opened 2019-10-26 20:26 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
with 1.23.1b1 and Firefox 71 b4 not a single website invites!
[Description of the bug or feature]

### A specific URL where the issue occurs
all
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [try 2 open a website]
2. [nothing]
3. [...]

### Expected behavior:

[What you expected to happen]
not a single website invites!
### Actual behavior:

[What actually happened]
not a single website invites!
### Your environment

* uBlock Origin version:1.23.1b1
* Browser Name and version:Firefox 71b4
* Operating System and version:Windows 10 Pro

**Comment by uBlock-user** [comment] 2019-10-26 20:32
@gorhill I just reproduced it after updating to the latest dev build.

![image](https://user-images.githubusercontent.com/21290713/67625590-c3139c00-f85d-11e9-9f54-f4ed689da6e0.png)

**Comment by akks1981** [comment] 2019-10-26 20:34
sry for my bad english ;-)

**Comment by puff-m-d** [comment] 2019-10-26 20:35
Hello,

If what the OP is meaning by "invites" is "loading", I am experiencing the same issue (started with 1.12.1.0 on FF 71 beta 4 and continues with 1.12.1.1). Once uBlock is installed, no websites will load (example: https://github.com).  Nothing shows up in the logger.

If you go to uBlock settings > Filter lists, it appears that no filters are loading as no counts show for the different filter lists.

I have tried removing and reinstalling uBlock with the same results.

Also note that uBlock 1.23.0 stable works fine on FF 71 beta 4, it is just the new 1.23.1.X betas that have the issue...

HTH...
Best regards,
Kent

**Comment by akks1981** [comment] 2019-10-26 20:37
yes uBlock 1.23.0 stable works fine!

**Comment by uBlock-user** [comment] 2019-10-26 20:43
Downgrading back to `1.22.5rc6` and the issue no longer occurs.

**Comment by tgn-ff** [comment] 2019-10-26 20:54
I ran a bisection. The interesting part is that if you run the bisection with the same profile just by reloading the temporary add-on, the issue won't manifest - in Firefox, at least. I had to create a new profile at every step to reproduce.

    b0cbc47d9abb51de884c395b8c1a26771fc8c270 is the first bad commit
    commit b0cbc47d9abb51de884c395b8c1a26771fc8c270
    Author: Raymond Hill <rhill@raymondhill.net>
    Date:   Sat Oct 26 13:13:53 2019 -0400

        Add WASM versions for some bidi-trie methods

        Related issue:
        - https://github.com/uBlockOrigin/uBlock-issues/issues/761

        Changes related to above issue made it possible to
        create WASM versions of methods used in the bidi-trie.
        In this commit, WASM versions for startsWith(), indexOf()
        and lastIndexOf() have been implemented.

     src/js/static-net-filtering.js |  42 ++++--
     src/js/strie.js                | 263 ++++++++++++++++++++++++----------
     src/js/utils.js                |   2 +-
     src/js/wasm/biditrie.wasm      | Bin 0 -> 404 bytes
     src/js/wasm/biditrie.wat       | 311 +++++++++++++++++++++++++++++++++++++++++
     5 files changed, 536 insertions(+), 82 deletions(-)
     create mode 100644 src/js/wasm/biditrie.wasm
     create mode 100644 src/js/wasm/biditrie.wat

**Comment by gwarser** [comment] 2019-10-26 20:56
Are you sure it's b1 and not b0? b0 was fault and was quickly removed from release page. Try updating again.

@tgn-ff yes, this was faulty commit, it's fixed now.

**Comment by uBlock-user** [comment] 2019-10-26 21:01
> Are you sure it's b1 and not b0? 

I updated from 1.22.5rc6 to 1.23.1b1 and the issue started occuring, I never had b0.

**Comment by puff-m-d** [comment] 2019-10-26 21:01
> Are you sure it's b1 and not b0?

I have the issue on both versions...

**Comment by gwarser** [comment] 2019-10-26 21:08
I reproduced in beta (worked fine in Nightly).

Cleaning up storage/default directory fixed the issue - this destroys data!!! You can check if removing uBO and then installing again will fix this (should remove uBO storage).

**Comment by gorhill** [comment] 2019-10-26 21:10
I can't reproduce an issue with 1.23.1b1. The only link provided as an example, `https://github.com/`, works fine. Trying random links from the front page of Hacker News all worked fine.

I suspect some of you still are using a bad uBO 1.23.1b0, maybe some of the code has been cached and is being used. Disable uBO, go to the [release section](https://github.com/gorhill/uBlock/releases), click the `uBlock0_1.23.1b1.firefox.signed.xpi` to force re-installation, then quit the browser, re-launch and re-activate uBO. I do have sometimes to do this to force Firefox to be sure the old version is not used.

**Comment by gorhill** [comment] 2019-10-26 21:13
> Cleaning up storage/default directory fixed the issue

Just forcing a re-install after disabling (not removing) the extension typically always work on my side once the browser is restarted and the extension is re-enabled.

**Comment by uBlock-user** [comment] 2019-10-26 21:17
> Disable uBO, go to the release section, click the uBlock0_1.23.1b1.firefox.signed.xpi to force re-installation, then quit the browser, re-launch and re-activate uBO. I do have sometimes to do this to be sure the old version is not used.

No change on Nightly on my side.

uBO console is still spitting that error too in https://github.com/uBlockOrigin/uBlock-issues/issues/764#issuecomment-546637092

**Comment by gorhill** [comment] 2019-10-26 21:20
Ok I removed `uBlock0_1.23.1b1.firefox.signed.xpi` for the time being, I will investigate those error messages if I can reproduce them.

**Comment by uBlock-user** [comment] 2019-10-26 21:23
> I will investigate those error messages if I can reproduce them.

This is how I reproduce --

Install the previous dev build
Update to the 1.23.1b1, once the update finishes, try browsing to `google.com`

**Comment by tgn-ff** [comment] 2019-10-26 21:27
Considering the issue I had in my bisection (see my previous comment), the only way to be certain that it's fixed is by installing the extension in a clean profile.

**Comment by gorhill** [comment] 2019-10-26 21:31
Ok I think I see the issue, I didn't catch it because my WASm memory was initialized with a large enough value, the issue occurs when uBO must grow the WASM memory.

**Comment by gorhill** [comment] 2019-10-26 21:44
Fixed in [1.23.1b2](https://github.com/gorhill/uBlock/releases).

Sorry, bad day for committing I guess.

**Comment by gorhill** [comment] 2019-10-26 21:49
Well not sure it's working, actually, I now get errors at the console. I delete the release, I will take a break and will try to fix tomorrow whatever is wrong. Best is to stick to [1.22.5rc6.firefox.signed.xpi](https://github.com/gorhill/uBlock/releases/download/1.22.5rc6/uBlock0_1.22.5rc6.firefox.signed.xpi) for now.

**Comment by puff-m-d** [comment] 2019-10-26 21:50
> Fixed in [1.23.1b2](https://github.com/gorhill/uBlock/releases).

Hmmm... I am not seeing the new version...

**Comment by uBlock-user** [comment] 2019-10-26 21:52
Working on my side with 1.23.1b2 and no errors in extension console either.

**Comment by gorhill** [comment] 2019-10-26 22:15
> Working on my side with 1.23.1b2 and no errors in extension console either.

If you delete the `SNFE.bidiTrieDetails` entry in _"Local Storage" in the _Storage_ pane and restart the browser, are there any error at the console?

**Comment by uBlock-user** [comment] 2019-10-26 22:27
Yes, it spams "index out of bounds" multiple times in succession --

![image](https://user-images.githubusercontent.com/21290713/67626766-ee9e8280-f86d-11e9-91ec-c88242c4e14b.png)

**Comment by gorhill** [comment] 2019-10-26 22:38
This happens when loading from a selfie, I forgot to revise the code in there to account for the fact that the memory to allocate might be WASM memory. Will fix tomorrow.

**Closed** 2019-10-27 13:37 UTC
Labels: Firefox, bug, fixed
