### ISSUE TITLE
Ability to rename lists

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uBlock-issues#514] opened 2019-04-06 21:34 UTC
How to add a function to edit the name of the sheets?
Many users write smiles in their names of subscriptions or don't fill them at all (for example, hosts files), it looks awful. How about allowing users to write/edit headline?

What do you think?

![Безымянный](https://user-images.githubusercontent.com/8535285/55675538-b88ab880-58b3-11e9-8b24-0724e561c3f3.png)

**Comment by gorhill** [comment] 2019-04-06 21:59
Duplicate of <https://github.com/gorhill/uBlock/issues/2501>.

**Closed** 2019-04-06 22:00 UTC
Labels: duplicate, enhancement
