### ISSUE TITLE
uBlock Origin and Adguard

### ISSUE THREAD

**Issue by MolotovRussian69** [uBlockOrigin/uBlock-issues#274] opened 2018-10-17 19:27 UTC
Adguard is better than uBlock Origin ! And do not install a spy cookie (detectable by CCleaner) in the Firefox browser when private browsing is enabled!

**Comment by uBlock-user** [comment] 2018-10-17 19:38
Duplicate of #227

**Closed by uBlock-user** 2018-10-17 19:38 UTC
