### ISSUE TITLE
In filter element query edit field dont use regex expression

### ISSUE THREAD

**Issue by GermanAizek** [uBlockOrigin/uBlock-issues#3352] opened 2024-08-21 12:03 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

it is not possible to use `*` symbol to list all id names to block any similar on regex query.

### uBO version

uBlock Origin 1.59.0

### Browser name and version

Firefox

### Operating System and version

Linux Debian 12

**Comment by gwarser** [comment] 2024-08-21 12:16
https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#syntax

**Comment by garry-ut99** [comment] 2024-08-21 13:01
Yes, it's unclear, but most likely a mass spam-duplicate of:
- https://github.com/gorhill/uBlock/issues/1129
- https://github.com/gorhill/uBlock/issues/1670
- https://github.com/gorhill/uBlock/issues/1994
- https://github.com/gorhill/uBlock/issues/2164
- https://github.com/uBlock-LLC/uBlock/issues/1677
- https://github.com/gorhill/uBlock/issues/2595
- https://github.com/uBlock-LLC/uBlock/issues/1725
- https://github.com/uBlock-LLC/uBlock/issues/1758
- https://github.com/uBlockOrigin/uBlock-issues/discussions/2416
- https://github.com/uBlockOrigin/uAssets/discussions/22713

**Closed** 2024-08-21 13:19 UTC
Labels: duplicate
