### ISSUE TITLE
Usability Suggestion: Add column headings to advanced user mode

### ISSUE THREAD

**Issue by R3dXIII** [uBlockOrigin/uBlock-issues#1296] opened 2020-10-15 13:57 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
An extra cell above the resource types and hostnames list as a column heading.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
NA

### Steps to Reproduce

1. [First Step] Click the Ublock icon in the Firefox menu.
2. [Second Step] NA
3. [and so on...] NA

### Expected behavior:

[What you expected to happen]
I would like column headings above the +all link in the popup window.

### Actual behavior:

[What actually happened]
It's difficult to remember which heading is global (all sites) and which is for local rules (current site only).

### Your environment

* uBlock Origin version: v1.30.4
* Browser Name and version: Firefox 81.0.2
* Operating System and version: Windows 10 Pro x64

I would upload a screenshot or two but there is no image button on the toolbar.

**Comment by gorhill** [comment] 2020-10-15 14:02
Duplicate of <https://github.com/gorhill/uBlock/issues/840>.

**Closed by gorhill** 2020-10-15 14:02 UTC
