### ISSUE TITLE
Databases size keeps growing ! cjpalhdlnbpafiamejdnhcphjbkeiagm

### ISSUE THREAD

**Issue by webglgames** [uBlockOrigin/uBlock-issues#1473] opened 2021-01-28 11:33 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
    Add uBlock Origin from Chrome store

2. [Second Step]
    Select all filters and press apply button, wait to finish/complete (without pressing update !)
    _No custom external filter used during the tests, just the ones from within uBlock Origin !_

3. [and so on...]
    Now the total size of directory "Local Extension Settings\cjpalhdlnbpafiamejdnhcphjbkeiagm\" is 14.9 mb !
    Exit and enter again chrome browser, navigate a bit, now exit chrome browser and check the size of the indexed 
    databases as now the "Local Extension Settings\cjpalhdlnbpafiamejdnhcphjbkeiagm\" is 28 mb !!
    Now with the "Auto-update filter lists" DISABLED the size grows to 28 mb, even if first time after indexing the
    databeses in size where 14.9 mb. More with  "Auto-update filter lists" ENABLED the 
    "Local Extension Settings\cjpalhdlnbpafiamejdnhcphjbkeiagm\" total size grow to over 45 mb, sometime 55 mb !!

### Expected behavior:

[What you expected to happen]
It seems no mater what option i choose either that the  "Auto-update filter lists" enabled/disabled the databases
seems to grow to very big sizes.

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Google Chrome Dev 89.0.4389.9 (Official Build) (64-bit)
* Operating System and version: Windows 10 Enterprise 1809 Long-Term Servicing Channel (LTSC) 17763 (64-bit)

![ublockorigin_databases size!](https://user-images.githubusercontent.com/61231114/106132891-64506880-6119-11eb-8a45-712ad36a68d0.jpg)
![ublockorigin_settings](https://user-images.githubusercontent.com/61231114/106132893-64e8ff00-6119-11eb-8363-297ce66f8b56.jpg)

Questions:
Is uBlock Origin currently using 2 databases in the same time and therefor double the cpu & ram usage as 1 for the normal mode and another 1 for incognito mode?

![ublockorigin_2 processes](https://user-images.githubusercontent.com/61231114/106134024-daa19a80-611a-11eb-9b87-80d43cbe878a.jpg)

**Comment by gwarser** [comment] 2021-01-28 12:44
> Now the total size of directory "Local Extension Settings\cjpalhdlnbpafiamejdnhcphjbkeiagm" is 14.9 mb !

Expected. All filter lists will use these few megabytes.

> Exit and enter again chrome browser, navigate a bit, now exit chrome browser and check the size of the indexed
> databases as now the "Local Extension Settings\cjpalhdlnbpafiamejdnhcphjbkeiagm" is 28 mb !!

Expected. uBO created optimized "selfie", to load filters in more efficient way.

> Now with the "Auto-update filter lists" DISABLED the size grows to 28 mb, even if first time after indexing the
> databeses in size where 14.9 mb. More with "Auto-update filter lists" ENABLED the
> "Local Extension Settings\cjpalhdlnbpafiamejdnhcphjbkeiagm" total size grow to over 45 mb, sometime 55 mb !!

Maybe, maybe it's how these browser storage databases work? You should ask browser developers. What probably happens - for performance, removed entries are only marked as deleted, and will be physically removed after some time / after some storage size is reached / when browser will be in idle state...

**Comment by webglgames** [comment] 2021-01-28 13:03
Yes it continue to grow, as sometime i find it at 62 MB !!!!!!

I tested other extensions and i find it that the extensions used 1 process for both Normal & Incognito mode(s) !
As uBlock Origin use 1 process for Normal mode & another 1 process for Incognito mode = twice the cpu & ram usage !!
![ublock_origin_using_2_times_the_cpu_and_ram_usage!!!!!!!!!!](https://user-images.githubusercontent.com/61231114/106141911-a7183d80-6125-11eb-8836-26e4ce289f6a.jpg)

I was expecting for uBlock Origin to work the same as other extensions such only 1 process for both Normal & Incognito mode(s) !
Something is wrong as uBlock Origin it seems to run twice and therefor 2 processes requires double the cpu & ram or calculation usage and therefor a slow down of opening websites !

Please do fix this as 2 running uBlock Origins is like having BitDefender & Kaspersky running both at the same time !

**Comment by gorhill** [comment] 2021-01-28 14:26
> Please do fix this as 2 running uBlock Origins is like having BitDefender & Kaspersky running both at the same time !

Opening a private window will cause uBO to be launched in another process, this is normal and by design, not doing so would break uBO.

**Closed by gorhill** 2021-01-28 14:26 UTC
Labels: something to address

**Comment by gorhill** [comment] 2021-01-28 14:59
https://github.com/gorhill/uBlock/issues/172
