### ISSUE TITLE
slowing down browser (site issue)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#3091] opened 2024-01-24 06:47 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when i visit `https://alliptvlinks.com/iptv-m3u-lists/` on firefox ,after a while browser becomes unresponsive & crashes saying ublock origin is slowing down the browser, stop that extension
there's antiadb but that can be solved later after solving this bug

**The firefox profile => `https://gofile.io/d/NrJQ6j`**

### A specific URL where the issue occurs.

```yaml
https://alliptvlinks.com/iptv-m3u-lists/
```

### Steps to Reproduce

1. visit `https://alliptvlinks.com/iptv-m3u-lists/`
2. wait for website to load complete
3. antiadb kicks in( => this can be solved later ,first bug needs to be fixed)
4. now wait for some seconds
5. a native dialogue from firefox kicks in saying _ublock origin is slowing down the browser ,stop that extension_
6. now refresh the browser ,but its kind of unresponsive
7. sometimes you need to refresh the website in order to reproduce
8. On firefox android browser ,there's too much slowness such that there's lag

### Expected behavior

no slowness of browser and normal performance

### Actual behavior

browser crashes & firefox saying ublock origin is slowing down the browser, stop that extension
![Screenshot (296)](https://github.com/uBlockOrigin/uBlock-issues/assets/20338483/49f9da32-d02e-438d-971a-4f1d36c2bd61)

### uBO version

1.55.1.14 & 1.55

### Browser name and version

firefox 122.0 & firefox android 121.1.0

### Operating System and version

win10 & android

### Notes
- There's consistent antiadb on firefox, but i think that can be solved after this bug fix
- iam using another av extension but that doesn't interfere

**Comment by gwarser** [comment] 2024-01-24 10:38
https://share.firefox.dev/3SsjvTp

**Comment by gwarser** [comment] 2024-01-24 11:13
Yes. Looks like for some reason cookie dialog is removed and anti ad block in mutation observer is reinserting it back (`.rc-panel`). But it's the same file and I have no idea why the cookie dialog is marked as removed. Thought maybe it's Firefox cookiebanner removal setting, but does not seem to be enabled in stable where I'm testing.

**Comment by Rob--W** [comment] 2024-01-24 14:26
I was pinged to take a look at this issue. For posterity, the JS file of the site that triggers the issue is https://pastebin.com/H6wWh78y

In the profile from https://github.com/uBlockOrigin/uBlock-issues/issues/3091#issuecomment-1907863481, I can see that a considerable amount of time is spent in DOM mutations and GC. Based on the source code and the functionality here, that is not too surprising: the website continuously tries to restore any removed DOM nodes, and I suppose that ad blockers try to remove these, which is effectively an infinite loop.

Here is a self-contained test case that does something similar but without any throttling whatsoever, for comparison: https://jsfiddle.net/qg3fsbc0/
When I run this example in a new Firefox profile, I can observe a seemingly unbounded memory growth in the profiler: https://share.firefox.dev/3S5INFs

Here is a slight variation of the test case: https://jsfiddle.net/71q3Lgd8/. Instead of removing nodes immediately in the `MutationObserver` callback, I debounce it with `setTimeout`. Now it also has memory growth, but also stops occasionally to collect garbage (like the original test case in this report): https://share.firefox.dev/3UeBsGs

**Comment by gorhill** [comment] 2024-01-24 14:32
> i will report this to bugzilla

What's the bugzilla entry?

**Comment by gorhill** [comment] 2024-01-24 15:54
I was able to reproduce at first but now I am unable. Are there filters in uBO which have changed to prevent the issue?

Also, I can't see any filters in uBO which causes DOM nodes to be removed on that site, so I wonder what is removing the node -- could be an issue in the site's code itself.

**Comment by gorhill** [comment] 2024-01-24 16:16
> disable quick fixes list & then use firefox with STR provided

Right, still cannot reproduce no matter how often I reload the tab.

**Comment by garry-ut99** [comment] 2024-01-24 21:42
>  i can consistently reproduce the issue on firefox desktop

Same here, it's eating 1 cpu core constantly + huge memory leak constantly (incerasing +120MB per second), I've stopped recording at 12 GB RAM eaten, because it was pointless to continue., as seen: there are 2 similiar messages: one saying "it's website slowing down browser " and the other  saying "it's uBlock Origin slowing down browser" they keep switching alternately all the time, as the website and the extension were interrupting each other. Closing the website tab in browser won't help - the memory leak & and 1 cpu being eaten is still here until the whole browser is closed. I haven't recorded the profile, as my only intention was to show the general fell & look of the issue, also like everbody at the moment, I'm not sure whether it's a website, an extension or a browser to be blamed for the issue, it needs to be investigated.

![Nagrywaj_2024_01_24_22_19_27_910](https://github.com/uBlockOrigin/uBlock-issues/assets/72945564/2483d9dd-875e-4a97-b530-7cd8a33ebc51)

**Comment by gorhill** [comment] 2024-01-24 23:35
The issue is caused by the site's code repeatedly moving one single element from one position to another, forever.

When moving that one single element from one position to another (both positions are children of the body element), Firefox triggers one mutation events with two mutations: one as a removed node, another one as an added node, both being the same element => `div.rcc-panel.group.rcc-panel-fixed`.

The site's code appears to make the assumption that when moving an element from one position to another, an event with a single mutation should occur, where both the `addedNodes` and `removedNodes` would be for the same element. I am guessing this was tested on Chromium-based browser and that the assumption works for such browser.

However Firefox there one event with two mutations, one for the removal, one for the addition. In that case, the site re-add the "removed" node according to its original `nextSibling` value, which means it will be put back to where it was moved from. And so it toggles the element forever between two positions in the DOM on each mutation event.

Position 1:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/30cc7ac3-1bfe-41e1-b137-e6a84f86cbcb)

Position 2:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/26ac0098-7f82-4c10-9a6c-e0765b2873c7)

Code which causes the issue, it inserts back to where it was moved from -- `nextSibling` points to the position before it was moved:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/7dbf6064-eb8e-495e-804f-30a1f7d5f744)

Note that the mutation observer handler makes the assumption that a moved node will result in one single mutation where both `removedNodes` and `addedNodes` are not empty:

    //check only removal here!
    if (
        mutation.removedNodes.length > 0 &&
        mutation.addedNodes.length == 0
    )

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/59ad8c9b-a898-44f8-b665-4d34ff694d3c)

The content blockers' mutation observer ends up being called back non-stop forever too, but their mutation observer can't be faulted here, the flaw is in the site's code.

I could trigger the faulty code path without a content blocker extension, but with Enhanced Tracking Protection set to Strict, and NextDNS DNS-based content blocker (they have a [free trial easy to set up](https://nextdns.io/)).

https://profiler.firefox.com/public/sxk3318j2d7rfb4p5ezq9k3tsnndxs1d5pxy29g/calltree/?globalTrackOrder=01&implementation=js&thread=1&v=10

I did also trigger the issue with Enhanced Tracking Protection set to normal while using NextDNS DNS-based content blocking, but when I tried to reproduce again, no luck, it appears the code path is triggered through a timing issue. I tried with only Enhanced Tracking Protection set to strict without a DNS-based blocker, but I could not, though I believe this could be possible.

**Comment by garry-ut99** [comment] 2024-01-25 08:14
> ghajini: If this antiadb is present on other unreported sites/unfixed sites 

About 131 sites contains this script: https://publicwww.com/websites/%22%2Feazy-ad-unblocker%2F%22/

> ghajini: reviews `/plugins/eazy-ad-unblocker/*$script`

There is already a similiar filter in uBlock - Ads : 
`/wp-content/plugins/eazy-ad-unblocker/*$script,css`
https://github.com/uBlockOrigin/uAssets/blob/12081185b3314717cd302c005044e4079e92b30c/filters/filters-2020.txt#L873

By the way there is also this whitelist rule in uBlock - Ads: : 
`@@/wp-content/plugins/eazy-ad-unblocker/*$script,domain=imgair.net|imgblaze.net|imgfrost.net|pixsera.net|vestimage.site|imgwia.buzz|pixlev.*`
https://github.com/uBlockOrigin/uAssets/blob/12081185b3314717cd302c005044e4079e92b30c/filters/filters.txt#L15087 

Also these scriptlets : 
`alliptvlinks.com##+js(aopr, eazy_ad_unblocker)`
`blog.textpage.xyz##+js(aopr, eazy_ad_unblocker)`
`ruyashoujo.com##+js(aopr, eazy_ad_unblocker_dialog_opener)`

<hr>

I've visited `https://daneiakartes.info/`, with regional Greece list enabled, and encountered anti-adblock popup, and the script is present in the logger but is unblocked, because it has a different name:  `https://daneiakartes.info/wp-content/plugins/antiblocker/js/custom.js?ver=1.1.12` - neither the filter you've provided, nor the filter which is already in uBlock - Ads, will block it, also the slowdown issue hasn't appeared, but I didn't investigate further.

Also have visited another site: `https://blackdesert-info.ru/` with regional RU list enabled, and the anti-adblock script is already blocked by rule from uBlock - Ads :  `/wp-content/plugins/eazy-ad-unblocker/*$script,css`, also no slowdown issue has appeared after whitelisting the anti-adblock files, even with regional RU list disabled, I didn't investigate further.

**Comment by Yuki2718** [comment] 2024-01-25 10:04
> @Yuki2718 reviews `/plugins/eazy-ad-unblocker/*$script`

If blocking this helps, why don't? But EL won't address anti-adb on normal sites.

**Comment by gorhill** [comment] 2024-01-25 12:10
> Is there any way for fixing this at ublock level

There is nothing uBO can do to fix bad code sites like this, the fix is at most filter-based as far  as uBO is concerned.

**Closed as completed** 2024-01-25 12:16 UTC
Labels: external
