### ISSUE TITLE
WebSockets not being blocked

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uBlock-issues#737] opened 2019-09-26 02:18 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

WebSockets are shown as blocked in the logger but are not actually being blocked anywhere, on any site.

### A specific URL where the issue occurs

"Everywhere"
`https://www.videolan.org/`

### Steps to Reproduce

1. Add `||get.videolan.org^$websocket,first-party` to `My filters`
2. Visit `https://www.videolan.org/`

### Expected behavior:

The websocket connection to `get.videolan.org` is blocked and the download counter `#wscounter` (under the download button) is empty.

### Actual behavior:

The websocket connection to `get.videolan.org` is not blocked and the download counter `#wscounter` is populated. The success of the websocket connection can be verified using developer tools as well.

### Your environment

* uBlock Origin version: uBlock Origin 1.22.2
* Browser Name and version: Google Chrome 77.0.3865.90
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment] 2019-09-26 05:51
dev tools -- 

![image](https://user-images.githubusercontent.com/21290713/65661627-c42f8e80-e04f-11e9-838e-af2fdd5859b1.png)

**Comment by gwarser** [comment] 2019-09-26 10:52
On my side,Fx Nightly and Chrome 77, counter is blocked.

In Chrome dev tools status is "finished". Time is Pending maybe because this is UDP connection?

**Comment by uBlock-user** [comment] 2019-09-26 10:55
@gwarser try testing on `https://www.websocket.org/echo.html`

**Comment by gwarser** [comment] 2019-09-26 11:02
![image](https://user-images.githubusercontent.com/886325/65683555-cc8ec600-e05d-11e9-90f4-f849c8294cf1.png)

**Comment by uBlock-user** [comment] 2019-09-26 11:04
Status should say blocked in red, yours is not getting blocked, none of them are getting blocked.

**Comment by gwarser** [comment] 2019-09-26 11:08
When I disconnect my connection simple image requests shows red "failed", but websockets grey "finished" - UDP quirk?

**Comment by uBlock-user** [comment] 2019-09-26 11:19
I don't see any such error - 

![image](https://user-images.githubusercontent.com/21290713/65684481-5ac67480-e07d-11e9-8234-7a92d55039b0.png)

Same issue with uMatrix, I blocked the entire XHR cell and the conneciton is still successful. Something is broken in Chrome ?

**Comment by gwarser** [comment] 2019-09-26 11:24
I can reproduce in uMatrix 1.4, Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by gorhill** [comment] 2019-09-26 13:31
I don't have Chromium 77.

Can the issue be reproduced with AdGuard? Adblock Plus?

**Comment by gorhill** [comment] 2019-09-26 13:37
> Status should say blocked in red

Status... The green box? I will be green if the browser supports websocket -- it does not require to create a websocket connection. So it all works fine in Chromium 76 on my side, just as shown in @gwarser's screenshot.

**Comment by uBlock-user** [comment] 2019-09-26 13:39
> The green box?

What green box ? I meant the status column

**Comment by gorhill** [comment] 2019-09-26 13:40
I don't see a "status" column at the `websocket.org` page, searching for `status` returns `0`.

**Comment by gorhill** [comment] 2019-09-26 13:43
In Chromium 76, the websocket is properly blocked, the status as per Network pane in dev tools is empty, and the transferred bytes is zero, so works fine in Chromium.

**Comment by uBlock-user** [comment] 2019-09-26 13:46
> the status as per Network pane in dev tools is "Finished",

It shouldn't be, it should be "blocked", just like it shows for javascript.

**Comment by gorhill** [comment] 2019-09-26 13:47
> It shouldn't be, it should be "blocked"

File an issue with Chromium devs if you want the Network pabe to show you "blocked", this is not a uBO issue, the Chromium issue of not showing "blocked" shouldn't be our concern here.

**Comment by gorhill** [comment] 2019-09-26 13:49
Npw I just want to know whether the issue also occurs with AdGuard, ABP in Chromium 77 so that it can conclusively be closed deemed a Chromium issue.

**Comment by uBlock-user** [comment] 2019-09-26 13:50
Does it work on the current stable v77 ?

**Comment by uBlock-user** [comment] 2019-09-26 13:55
Nvm, same issue on Chrome 77 too, connection is succesfully established, so a chrome issue.

**Closed by uBlock-user** 2019-09-26 13:55 UTC
Labels: Chromium, bug

**Comment by uBlock-user** [comment] 2019-09-26 14:06
@gorhill Same results with ABP and Adguard on Chrome 77 and 79, extensions show it's blocked but it's not. Devtools shows a successful connection.

/cc @ameshkov

**Comment by gorhill** [comment] 2019-09-26 14:09
And just to be sure, there is also no such message as I get with Chromium 76 at the console?

![a](https://user-images.githubusercontent.com/585534/65695542-ba089280-e045-11e9-8309-205810aaadba.png)

**Comment by uBlock-user** [comment] 2019-09-26 14:11
Yes exactly that. That msg **should** appear when you block a websocket conenction, butit doesn't with v77 and v79 and connection is established anyway.

**Comment by llacb47** [comment] 2019-09-26 14:16
Ok, so this is a browser issue not a uBo issue.

**Comment by gorhill** [comment] 2019-09-26 14:18
> specifically Chromium?

Specifically Chromium 77 and above, as it works fine on my side with Chromium 76.

**Comment by uBlock-user** [comment] 2019-09-26 14:19
Nn Firefox Nightly, connection is blocked, but in Network pane of devtools it doesn't show the blocked attempt.. All I see is the list of network requests which weren't blocked, probably a firefox issue.

**Comment by gorhill** [comment] 2019-09-26 14:26
> probably a firefox issue

<https://bugzilla.mozilla.org/show_bug.cgi?id=1555057>

**Comment by uBlock-user** [comment] 2019-10-03 20:50
https://bugs.chromium.org/p/chromium/issues/detail?id=1011108

**Comment by ameshkov** [comment] 2019-10-04 10:50
@gorhill could you please take a look? It seems that they mostly resolved the issue in v79, but the problem with uMatrix remains:
https://bugs.chromium.org/p/chromium/issues/detail?id=1011108#c7

**Comment by uBlock-user** [comment] 2019-10-04 11:04
I'm on 79.0.3928.0 (Official Build) (64-bit) and I can reproduce, it's not resolved yet..

**Comment by uBlock-user** [comment] 2019-12-13 10:49
Owner of the bug is asking for [feedback](https://bugs.chromium.org/p/chromium/issues/detail?id=1011108#c20), I cannot reproduce on 81.0.3995.0, offer your own feedbacks too.
