### ISSUE TITLE
Add scope indicators to Advanced Mode

### ISSUE THREAD

**Issue by j-james** [uBlockOrigin/uBlock-issues#1590] opened 2021-05-17 06:32 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [~] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
  - It is, this is a feature request

### Description

In Advanced Mode, neither of the two control columns are labelled, which can lead to some confusion about which controls what scope. While reading the wiki tells you this (and of course is always a good idea to do), adding small labels would help by serving as a reference and making it mode clear which does what. It could be pretty small and non-obtrusive.

Here's a quick mockup I made:

![2021-05-16-232530-mockup](https://user-images.githubusercontent.com/35242550/118441969-d1731400-b69e-11eb-8960-c93991bb7f0a.png)

### Your environment

* uBlock Origin version: 135.2
* Browser Name and version: Ungoogled Chromium 89
* Operating System and version: Arch Linux 5.12

**Comment by uBlock-user** [comment] 2021-05-17 06:36
> In Advanced Mode, neither of the two control columns are labelled, 

Hovering your mouse over the `all` column on each side provides tooltips.

**Comment by gorhill** [comment] 2021-05-17 11:30
Duplicate of <https://github.com/gorhill/uBlock/issues/840>.

**Closed by gorhill** 2021-05-17 11:30 UTC
Labels: duplicate
