### ISSUE TITLE
uBlockO causing some sort of DNS leak

### ISSUE THREAD

**Issue by Kraxys** [uBlockOrigin/uBlock-issues#1640] opened 2021-06-19 10:06 UTC
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [ ] uBO is the only extension
    - [x ] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On a clean and fresh Portable FF I have installed 2 extensions: FoxyProxy Standart and uBlock0. No hack performed on ublocko. With FoxyProxy, I set up a socks5 proxy connection, say with a proxy in the US. My ISP is in Spain.  I triple-check that in FoxyProxy UI, _Send DNS through SOCKS5 proxy_ is green. Moreover, in about:config, _network‧proxy‧socks_remote_dns_ is _true_.

1) When uBlockO is wholly disabled (or uninstalled) DNS-leaktest sites such as  https://www.perfect-privacy.com/en/tests/dns-leaktest or https://www.grc.com/dns/dns.htm, only an US Dns IP is displayed, which is perfectly normal.

2) As soon as I  enable uBlockO in _Tools-> Addons_, the same tests on the same sites are both displaying an US Dns IP **and two Spanish Dns IP** (precisely those of my ISP). The same issue occurs **even if I deactivate** uBlockO on each of the previous site.
 

### A specific URL where the issue occurs

https://www.perfect-privacy.com/en/tests/dns-leaktest 
and
https://www.grc.com/dns/dns.htm

### Steps to Reproduce

1. Installing  FoxyProxy and setting up a socks5 proxy with _network‧proxy‧socks_remote_dns_  set to _true_
2. Testing Dns on previous sites: Only Dns relative to the proxy is displayed
3. Installing uBlock, and testing Dns again: The ISP Dns IPs are displayed along with the Dns IP relative to the proxy>.
4.  Deactivating uBlock on each previous sites: Same problem.
5. Completely disabling (or uninstalling) uBlockO, and testing again on the same sites: only the Dns IP relative to the proxy is displayed.

### Expected behavior:
When using a socks 5 proxy with _network‧proxy‧socks_remote_dns_  set to _true_,  every Dns test site should display only the Dns IP relative to the proxy. 

### Actual behavior:
Cf description above

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version:  FF 89.01 (but same problem with previous versions)
* Operating System and version: W10 Home & Enterprise (tested on VM).

**Comment by uBlock-user** [comment] 2021-06-19 10:11
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

Disable _Uncloak canonical names_ in Settings

**Comment by gorhill** [comment] 2021-06-19 13:07
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/911>.

There is now a setting to disable cname-uncloaking, you can disable it yourself as you see fit.

**Closed by gorhill** 2021-06-19 13:07 UTC
