### ISSUE TITLE
Feature: Block Youtube Inline Video Sponsors via API

### ISSUE THREAD

**Issue by Frank-wq2** [uBlockOrigin/uBlock-issues#1289] opened 2020-10-11 15:32 UTC
### Description

i know there are separate addons. but because ublock is a blocker in general it would be nice - if technically possible and not much work or maintenance - to have this also in ublock 

would be a nice feature especially compared to other blockers which do not have it.

to be more specific: just the skipping parts functionality - not the edit segments parts etc. -> therefore are the other addons. so if i use ublock and activate the "list" and i see a youtube video it automatically skips those "sponsor" parts

more info regarding api: https://github.com/ajayyy/SponsorBlock/wiki/API-Docs

@gorhill : Thanks for your hard work.

**Comment by uBlock-user** [comment] 2020-10-11 15:33
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1149

**Closed by uBlock-user** 2020-10-11 15:33 UTC

**Comment by Frank-wq2** [comment] 2020-10-11 15:53
Out of scope of uBO? Too specific?
