### ISSUE TITLE
'Adblock for y..t...' by 'adremover' + ublock origin = no more y..t... ads on chrome

### ISSUE THREAD

**Issue by xinorez** [uBlockOrigin/uBlock-issues#1598] opened 2021-05-21 17:14 UTC
'Adblock for y..t...' by 'adremover' + ublock origin = no more y..t... ads on chrome

Hi, just thought I should let you know, I've found a foolproof albeit annoying way of stopping all Y.. t... ads, including preroll ads:

Download adblock for y..t... by adremover
Disable ublock origin
Restart browser or reload Y.. t... video page until you see this message appear under the video player: 'cleaned by adblock for...'
Enable ublock origin
Reload video again, and if the 'cleaned by adblock' message is still there then there should be no more ads until you have to restart the browser again.

Unfortunately you will have to do this every time you restart the browser, so I hope you can figure out why this works and come up with an under the table fix for this issue, maybe a hidden setting so g corp doesn't immediately fix it on their end.

Either way, thanks very much for contributing to the internet by writing a trio of efficient adblocking add-ons. I don't have any money to contribute so I hope you'll take my thanks and maybe think about incorporating this tip, or else just keep it on the down low so g corp doesn't fix it. Thanks!

**Comment by uBlock-user** [comment] 2021-05-21 17:23
This is a place for report bugs in uBO, not filterlist issues.

Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1597

**Closed by uBlock-user** 2021-05-21 17:23 UTC
