### ISSUE TITLE
Addon not signed for Firefox version ≥77

### ISSUE THREAD

**Issue by allanlaal** [uBlockOrigin/uBlock-issues#996] opened 2020-04-22 11:37 UTC
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ x] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Firefox disabled this addon because it thinks it is unsigned

### A specific URL where the issue occurs

not applicable

### Steps to Reproduce

1. install Firefox nightly (version 77)
2. install addon

### Expected behavior:

addon works

### Actual behavior:

disabled by Firefox

### Your environment

* uBlock Origin version: LATEST
* Browser Name and version: Firefox nightly 77.0a1 (2020-04-21) (64-bit)
* Operating System and version: Ubuntu Linux 20.04 LTS nightly

**Comment by gorhill** [comment] 2020-04-22 11:41
> uBlock Origin version: LATEST

Please provide the exact version number and disclose from where you installed it.

**Comment by gwarser** [comment] 2020-04-22 15:47
uBO dev works fine:

![image](https://user-images.githubusercontent.com/886325/80003450-5baf6f80-84c1-11ea-811d-87481f265010.png)

**Comment by gorhill** [comment] 2020-04-22 15:59
Pretty sure the issue is not with uBO, so closing as invalid. I invite OP to better investigate on his side.

**Closed by gorhill** 2020-04-22 15:59 UTC
Labels: Firefox, unable to reproduce
