### ISSUE TITLE
Blocking shadow-root?

### ISSUE THREAD

**Issue by grishka** [uBlockOrigin/uBlock-issues#880] opened 2020-02-03 09:38 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Yandex uses this `#shadow-root` thing on a number of its projects (at least zen.yandex.ru and pogoda.yandex.ru) to circumvent ad blockers. There aren't any CSS selectors I could reliably use to hide this block without hiding anything else. Procedural filters (`something:has(something)`) don't work inside the shadow root — I tried `div:has(style)` and it didn't match anything even though there is such a div inside the shadow root.

![Снимок экрана 2020-02-03 в 12 25 19](https://user-images.githubusercontent.com/1478258/73641209-b7b3e600-4680-11ea-845f-460b047eda85.png)

Also, I don't think I've ever seen `shadow-root` being used for non-nefarious purposes. Is there a filter rule to block this browser functionality, either for a domain or completely, using uBlock Origin?

### A specific URL where the issue occurs

https://zen.yandex.ru/media/zemexpert/skk-peterburgskii-jertva-gradostroitelnogo-proizvola-v-sanktpeterburge-5e36f42a5098d322f9ed26b0

### Steps to Reproduce

1. Try blocking ads on zen.yandex.ru
2. Realize it's this shadow-root thing

### Expected behavior:

I'm able to hide the `shadow-root` node entirely or at least apply procedural filters within it

### Actual behavior:

I'm powerless, and the only thing that sorta helps against this is the nuclear option of disabling JavaScript.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Vivaldi 2.10.1745.27
* Operating System and version: Mac OS 10.14.6

**Comment by uBlock-user** [comment] 2020-02-03 10:00
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/803

**Closed by uBlock-user** 2020-02-03 10:00 UTC
