### ISSUE TITLE
ClamAV detects as malware

### ISSUE THREAD

**Issue by udoschmitz** [uBlockOrigin/uBlock-issues#1273] opened 2020-09-30 18:45 UTC
/Users/myname/Library/Application Support/Firefox/Profiles/default.eyu/extensions/uBlock0@raymondhill.net.xpi: Urlhaus.Malware.210545-9255010-0 FOUND

**Comment by uBlock-user** [comment] 2020-09-30 18:53
Duplicate of https://github.com/gorhill/uBlock/issues/2315

**Closed by uBlock-user** 2020-09-30 18:53 UTC
