### ISSUE TITLE
Remove MVPS HOSTS, been a year and a half since its last update

### ISSUE THREAD

**Issue by g-k-m** [uBlockOrigin/uBlock-issues#2032] opened 2022-03-05 22:23 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

![image](https://user-images.githubusercontent.com/37273303/156901647-a99719e1-abcd-4bec-93f8-dde2fe1aa9b4.png)

Last update of MVPS hosts:

![image](https://user-images.githubusercontent.com/37273303/156901659-09c78a28-184b-41e4-83bc-5e911ce82586.png)
![image](https://user-images.githubusercontent.com/37273303/156901665-f4f2c5c8-8724-40d9-a77b-e5bcc973190b.png)

The real last update is from september 2020, since then only a single entry was added

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

Observe the pics

### Expected behavior

It's not removed

### Actual behavior

It should be removed?

### uBlock Origin version

uBlock Origin 1.41.8

### Browser name and version

Version 98.0.4758.102

### Operating System and version

Windows 10

**Comment by u-RraaLL** [comment] 2022-03-05 22:45
Basically a duplicate of https://github.com/uBlockOrigin/uBlock-issues/discussions/2005

**Closed** 2022-03-07 15:27 UTC
Labels: fixed

**Comment by tsunami2311** [comment] 2022-12-11 17:25
guy was in [Hospital](https://mvpshostsnews.blogspot.com/) all this time and it was update in september but retired from  list do deteriorating health

**Comment by gothic-bum** [comment] 2022-12-11 20:10
> it was update in september
  
Incorrect.

The filter list was last updated on March-06-2021, as indicated in the list itself.

There was only a "health update" status message added to the *website* in September.

**Comment by krystian3w** [comment] 2022-12-12 08:24
https://github.com/uBlockOrigin/uBlock-issues/issues/2032#issuecomment-1345611041 - It didn't make it to the bad lists, so the old url will dropped to a subscription of its own.

https://github.com/uBlockOrigin/uAssets/blob/master/filters/badlists.txt
