### ISSUE TITLE
Truncation issue with 1.41.2 in Edge and Brave. Not Firefox.

### ISSUE THREAD

**Issue by share3141** [uBlockOrigin/uBlock-issues#1972] opened 2022-02-11 18:07 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

For the Brave / Edge browsers when I bring up the popup by clicking on the UBO on the browser the icon that says "Click to Disable javascript on this site" does not appear.  In fact, the popup is quite large - probably due to the fact that I have increased the size of the font.  I have the same size of font on Firefox but the popup appears much smaller and I can see Disable Javascript icon. I'm sorry I'm not very sophisticated regarding this but I wanted to pass along my issue. It essentially renders UBO impossible to use (for me at least) on Brave / Edge.
![1](https://user-images.githubusercontent.com/20307002/153644132-491316b9-981f-4145-ab07-4eac4d89d7f8.png)

 
![Firefox](https://user-images.githubusercontent.com/20307002/153645284-6d7b5251-40c2-45bb-8c49-3a2f99a47160.png)

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new?assignees=&labels=&template=bug_report.yml

### Steps to Reproduce

I just visit a website and click on the UBO icon in the browser

### Expected behavior

That I would be able to see the entire popup

### Actual behavior

"Click to Disable javascript on this site" icon is not part of the popup.
![1](https://user-images.githubusercontent.com/20307002/153645094-eec0ec30-24b4-4701-baa2-835f148a7aa4.png)

### uBlock Origin version

1.41.2

### Browser name and version

Brave Version 1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit) and Edge Version 98.0.1108.50 (Official build) (64-bit)

### Operating System and version

Windows 21H1 19043, 1526 64bit

**Comment by gorhill** [comment] 2022-02-11 18:11
Please try on current stable Chromium -- I do not test uBO for Brave, only for Chromium, and I expect that uBO will work fine on Chromium-based browsers.

**Comment by gorhill** [comment] 2022-02-11 18:14
> I have increased the size of the font. I have the same size of font

How? You need to details this exactly in steps to reproduce.

**Comment by share3141** [comment] 2022-02-11 18:16
Understand. However, I lack the sophistication to do all of this.  I am 
sorry.  Just trying to be helpful.  Thanks anyway. I will use UBO on 
Firefox.

Raymond Hill wrote:

**Comment by gorhill** [comment] 2022-02-11 18:24
> I lack the sophistication to do all of this

How did you change the font size? That's only what I need to know.

**Comment by gwarser** [comment] 2022-02-11 18:54
![obraz](https://user-images.githubusercontent.com/886325/153652197-e6de32a8-03ba-4315-9135-dccdd88a60be.png)
![obraz](https://user-images.githubusercontent.com/886325/153652264-e5ec0c55-c44e-432c-ab0c-f976c611227e.png)

**Comment by gwarser** [comment] 2022-02-11 19:00
I think it happens on my side when overview panel cannot fit on screen and popup switches to mobile mode.

**Comment by q1800** [comment] 2022-02-11 19:01
This is what I see on Windows 10 21H2 with Microsoft Edge on 500% and Windows on 250% Scale in Display Settings on a 4K 27" Monitor.

![Untitled](https://user-images.githubusercontent.com/95879668/153652978-097af300-3e8c-45ca-ae80-9066c2b92d66.png)

**Comment by gwarser** [comment] 2022-02-11 19:04
Reproduced in Chrome by moving window to the left:

![obraz](https://user-images.githubusercontent.com/886325/153653580-e04f0603-d988-4c67-8fef-9bb4d7395e44.png)

**Comment by gwarser** [comment] 2022-02-11 19:10
Cannot reproduce in Firefox because 

- it does not change popup size when font size is changed, 
- after changing dpi, icon jumps into overflow menu which have its own issues but not this one,
- after rearranging toolbar elements to move button more to the left, uBO popup opens to the right :)

**Comment by share3141** [comment] 2022-02-11 21:13
OK - I figured this out.  The zoom level on both Edge and Brave was set 
to 150%. I set it to 125% and the problem resolved itself. I'm sorry to 
have caused such a mess.  I have things set so large so I can see.  
Thank you.

gwarser wrote:

**Comment by gwarser** [comment] 2022-02-26 17:42
Should be fixed in dev.

<details>
<summary>Images</summary>


![image](https://user-images.githubusercontent.com/886325/155853402-e970b31e-c4cf-48a8-ae08-37f86a7b2b73.png)
![image](https://user-images.githubusercontent.com/886325/155853421-80917f86-5ac2-4639-a98a-bf538bd42d58.png)

</details>

**Closed by gwarser** 2022-02-26 17:42 UTC
Labels: external
