### ISSUE TITLE
Cosmetic filtering not working with some filters

### ISSUE THREAD

**Issue by boromyr** [uBlockOrigin/uBlock-issues#1702] opened 2021-09-01 23:20 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I am running the latest version of uBlock Origin
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

AliExpress.com AliBaba.com google.com 

### Describe the issue

Cosmetic filtering was not found to be working on the above sites. By resetting the application I activated the block filters and managed to the problem in the following filters:
uBlock filters – Annoyances
AdGuard Mobile Ads
AdGuard Base
AdGuard Annoyances

### uBlock Origin version

1.37 and 1.37.3b20(attuale)

### Browser name and version

Edge Dev 95

### Settings

Do not affect the problem

### Notes

Occasionally there are other instances of problems with cosmetic filters that I have yet to figure out the cause of.

**Comment by gorhill** [comment] 2021-09-02 12:01
Can investigate vague, unspecific alleged issue. You will have to provide **exact** steps to reproduce specific cases on our side, otherwise the issue will be closed as _invalid_.

**Comment by gorhill** [comment] 2021-09-02 12:12
I create the following cosmetic filter:

    aliexpress.com##.categories-main

And it properly removed the top-left sidebar when visiting `https://www.aliexpress.com/`. I also tried the generic form `##.categories-main`, and the sidebar was also properly removed.

**Comment by boromyr** [comment] 2021-09-02 12:22
Very simple:
1. start from scratch with uBlock resetting all settings
2. enable the 4 uBlock filters - Annoyances AdGuard Mobile Ads AdGuard Base AdGuard Annoyances
3. on google.com block an item with the "select item" mode 
4. reload the page to test the block.

As a test run I did a generic search on [google](https://www.google.com/search?q=come+misurare+velocit%C3%A0&sxsrf=AOaemvJ-7v5W_ROv6bWYHRyRZeeaX4ZF7w%3A1630584350166&ei=Hr4wYdrQCaOFlQevzKmYBg&oq=come+misurare+velocit%C3%A0&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeOgcIIxCwAxAnOgcIABBHELADOgoILhDIAxCwAxBDOgQIIxAnOgsIABCABBCxAxCDAToICAAQgAQQsQM6BggjECcQEzoKCAAQsQMQgwEQQzoECAAQQzoKCC4QxwEQ0QMQQzoLCC4QgAQQsQMQgwE6CAgAELEDEIMBOgUILhCABDoICC4QgAQQsQNKBQg4EgExSgQIQRgAUMuAAVjypQFg9KcBaAJwAngAgAGgAYgBtRKSAQQ5LjEzmAEAoAEByAELwAEB&sclient=gws-wiz&ved=0ahUKEwja196HoODyAhWjQuUKHS9mCmMQ4dUDCA4&uact=5), and blocked the "People have also asked" element `www.google.com##.Wt5Tfe`
Maybe the google search language can change `.Wt5Tfe`, not sure, the language I use is Italian.

**Comment by boromyr** [comment] 2021-09-02 12:28
In any product lock the social widget `##.product-fix-wrap`, it should be broken with the four filters enabled.

> and the sidebar was also properly removed.

The sidebar is now blocked correctly, but until last night it wasn't.

**Comment by gorhill** [comment] 2021-09-02 12:35
> As a test run I did a generic search on google, and blocked the "People have also asked" element `www.google.com##.Wt5Tfe`

I did a generic search with the expression `generic search`, and then used the element picker to create the filter `www.google.com##.Wt5Tfe`, and it being applied properly, i.e. all works fine on my side, using Chromium 92.0.4515.159 on Linux. I do not have access to "Edge Dev 95".

**Comment by gorhill** [comment] 2021-09-02 12:38
> In any product lock the social widget ##.product-fix-wrap, it should be broken with the four filters enabled.

I can find no instance of a cosmetic filter using `.product-fix-wrap` in any of the four filter lists you mention.

**Comment by yourduskquibbles** [comment] 2021-09-02 14:05
[Web Annoyances Ultralist](https://github.com/yourduskquibbles/webannoyances) has `aliexpress.com##.product-fix-wrap:style(position: static !important;)` in [floating_filters.txt](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/floating_filters.txt) sublist, is user using this maybe but not reported as having it enabled?

**Comment by gorhill** [comment] 2021-09-02 14:55
> In any product

I did ask for an **exact** web page, and "any product" is not an exact web page. I did [randomly picked one](https://www.aliexpress.com/item/1005002032358980.html?spm=a2g0o.ams_97944.topranking.2.2aa5B391B391eI&pdp_ext_f=%7B%22ship_from%22:%22CN%22,%22sku_id%22:%2212000018480193564%22%7D&scm=1007.26694.140541.0&scm_id=1007.26694.140541.0&scm-url=1007.26694.140541.0&pvid=8c81841b-166d-454f-97e1-7f5e0cdba5cc&fromRankId=11647644&_t=fromRankId:11647644) (I shouldn't have to), and I can't reproduce anything that resemble unspecific vague _"should be broken".

As a result, closing as _invalid_, vague unspecific issues which can't be reproduced are unactionable, and are closed as _invalid_. If new information is added to actually allow us to reproduce, I will re-opened.

**Closed by gorhill** 2021-09-02 14:55 UTC
Labels: unable to reproduce
