### ISSUE TITLE
There are no filters to prevent the display of ads.

### ISSUE THREAD

**Issue by saber716rus** [uBlockOrigin/uBlock-issues#3496] opened 2024-12-22 18:02 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Missing filters in the extension settings.

![Снимок экрана 2024-12-22 205400](https://github.com/user-attachments/assets/0e6d5615-bd4c-480c-82b4-63cbee8bf60c)

uBlock Origin: 1.61.2
Chromium: 130
filterset (summary):
 network: 144639
 cosmetic: 70464
 scriptlet: 24587
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40622-143, never
  ublock-badware: 11861-1, never
  ublock-privacy: 1486-22, never
  ublock-unbreak: 2507-0, never
  ublock-quick-fixes: 222-4, never
  easylist: 78958-203, never
  easyprivacy: 53262-156, never
  urlhaus-1: 7995-0, never
  plowe-0: 3537-996, never
  RUS-0: 41063-148, never
filterset (user): [empty]
userSettings:
 autoUpdate: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: ?
 maxAssetCacheWait: 13 ms
 cacheBackend: indexedDB

### A specific URL where the issue occurs.

```yaml
no link
```

### Steps to Reproduce

1. Go to Settings

2. go to filter lists

### Expected behavior

the lists have filters

### Actual behavior

Ad blocking filters are missing

### uBO version

1.61.2

### Browser name and version

yandex browser 24.12.0.1810 

### Operating System and version

windows 11 22631.4602

**Comment by gwarser** [comment] 2024-12-22 18:09
uBO is blocked in Yandex Browser. You can try development build.

**Comment by stephenhawk8054** [comment] 2024-12-22 18:15
https://github.com/uBlockOrigin/uBlock-issues/issues/2627#issuecomment-1528886506

**Comment by gorhill** [comment] 2024-12-22 18:15
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2627>

**Closed** 2024-12-22 18:15 UTC
