### ISSUE TITLE
Cannot open Logger. Element picker/zapper does not switch tabs. (FF Mobile)

### ISSUE THREAD

**Issue by jimbo1qaz** [uBlockOrigin/uBlock-issues#168] opened 2018-08-14 21:28 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I open the uBlock "popup" button, the "element zapper and picker" buttons do not switch back to the page. The logger button is useless because it does not open a logger tab. The options button works fine.

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/uBlock-issues/issues/new

### Steps to Reproduce

1. Press the Firefpx dropdown menu,  click uBlock Origin (#)
2. On the new tab, click Lightning, Eyedropper, or Logger

### Expected behavior:

typing is painful on mobile. considering Github does not show searching on the mobile site. I switched to the desktop site to search for duplicates, reported an indie on desire site, and now i suffer an unusable auto zoom out.

it works

### Actual behavior:

see above

### Your environment

* uBlock Origin version: 1.16.16
* Browser Name and version: Firefox Mobile 61.0.2
* Operating System and version: Android 7.0

**Comment by gorhill** [comment] 2018-08-14 21:36
Was this for the tab already present when you launch the browser? There is a known issue with the first tab, you need to close it and create a new tab. Then all should work fine from there on.

See <https://bugzilla.mozilla.org/show_bug.cgi?id=1410749>.

**Comment by gwarser** [comment] 2018-08-14 22:04
Duplicate of https://github.com/gorhill/uBlock/issues/3148

**Comment by gwarser** [comment] 2018-08-14 22:10
This is new: 

>The logger button is useless because it does not open a logger tab.

Cannot reproduce.

**Comment by gwarser** [comment] 2018-08-14 22:36
When clicking Logger and Element picker buttons in popup:

```
00:29:20.614 Skrypty nie mogą zamykać okien, których nie otworzyły vapi-common.js:161:8
00:29:20.661 [Show/hide message details.] chrome.windows is undefined vapi-background.js:494
wrapper
moz-extension://c54f7323-0559-44b8-b0f4-d089dd9b569c/js/vapi-background.js:494:13
vAPI.tabs.open/<
moz-extension://c54f7323-0559-44b8-b0f4-d089dd9b569c/js/vapi-background.js:540:13
apply self-hosted:4549:5 applySafeWithoutClone
resource://gre/modules/ExtensionCommon.jsm:18:272
wrapPromise/<
resource://gre/modules/ExtensionCommon.jsm:38:256
```

Skrypty nie mogą zamykać okien, których nie otworzyły -> Scripts can not close windows that they have not opened

![screenshot_20180815_002950](https://user-images.githubusercontent.com/886325/44122228-3387a844-a023-11e8-9aa6-314bdef55d08.png)

**Comment by gwarser** [comment] 2018-08-14 22:40
Switching `dom.allow_scripts_to_close_windows` in `about:config` fixes this partially. Popup closes and Element picker can be used, but logger tab did not appear.

**Comment by gorhill** [comment] 2018-08-14 22:42
How do you a new profile with Firefox for Android?

**Comment by gorhill** [comment] 2018-08-14 22:50
Well apparently it's complicated. Anyways, Firefox for Android does not support the `browser.windows` API, so that would be the issue (<https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows#Browser_compatibility>).

**Comment by gwarser** [comment] 2018-08-14 23:09
>How do you create a new profile with Firefox for Android?

I use beta daily, so I tested on fresh stable.

**Comment by gwarser** [comment] 2018-08-14 23:30
@gorhill do you think [`window.open('','_self').close();`](https://github.com/gorhill/uBlock/commit/d6173b5d93538bdda10abede8c00d28253d36818) can be reverted in `vapi-common.js` to auto-close popup?

**Comment by gorhill** [comment] 2018-08-14 23:34
I rather not remove this one for now, it's just a warning at this point, I don't see it happening with Firefox stable (desktop).

**Comment by gorhill** [comment] 2018-08-14 23:38
Ugh.. maybe I missunderstood? This is about the warning in your [screenshot above](https://github.com/uBlockOrigin/uBlock-issues/issues/168#issuecomment-413038191)?

**Comment by gwarser** [comment] 2018-08-14 23:40
Picker does not close popup on Android - no matter on which tab i use it. Logger button works fine - handled differently?

**Comment by gorhill** [comment] 2018-08-15 00:01
> Picker does not close popup on Android

That's news to me, I am pretty sure it used too work. Maybe just forcing the target tab to be active after the picker has been injected would work.

**Comment by gwarser** [comment] 2018-08-15 00:14
Yes, Popup "tab" disappears when I switch to the "page tab" manually. Problem is - it did not do this just after click on the button.

**Comment by gwarser** [comment] 2018-08-15 00:32
Thank you, 1.16.17b6 fixed it. Picker still not switches to page when run on first page after Firefox start, but works for other tabs. I assume this is still this Android quirk from https://github.com/gorhill/uBlock/issues/3148

**Comment by gwarser** [comment] 2018-08-15 00:52
If someone remember issue about ESC key not closing Picker interface (lack of focus on page content?), then last commit probably fixed it too.

**Closed** 2018-08-15 01:58 UTC
Labels: Firefox-Android, fixed
