### ISSUE TITLE
Only getting grey and red switches in the "power button"

### ISSUE THREAD

**Issue by esotericDisciple** [uBlockOrigin/uBlock-issues#1286] opened 2020-10-09 21:09 UTC
This used to only be an issue for the main browser window, where I wasn't able to get a screen shot or even a recording of the issue for some reason (the popup just disappears and was invisible even when I tried recording my interactions with it in OBS—I suspect simplescreenrecorder and other capture tools would be the same). Now that I can't green-light sites anywhere now, the extension has become unusable and that's unacceptable because I don't know if any other adblock is as trustworthy since I stopped following the news following adblocks decision to allow ads (and other damming headlines) after I found ublock...

<img src="/esotericDisciple/img-ref/blob/main/Screenshot_20201009_135247.png?raw=true" alt="Screenshot_20201009_135247.png">

<img src="/esotericDisciple/img-ref/blob/main/Screenshot_20201009_135324.png?raw=true" alt="Screenshot_20201009_135324.png">

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment] 2020-10-09 21:14
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1153

**Closed by uBlock-user** 2020-10-09 21:14 UTC

**Comment by esotericDisciple** [comment] 2020-10-09 21:40
Only I was able to create a new browser and when I add ublock (but noscript instead of umatrix) I was able to get all three colors again (I would have never thought to look for "cell(s)" in the issues search for the green feature, cells are for particle-in-cell method papers and excel spreadsheets)...
