### ISSUE TITLE
Better toggle for dynamic filter area

### ISSUE THREAD

**Issue by Madis0** [uBlockOrigin/uBlock-issues#255] opened 2018-10-04 11:01 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Dynamic filtering mode](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) claims to be only available to [advanced users](https://github.com/gorhill/uBlock/wiki/Advanced-user-features). 
Yet, [there is a read-only mode](https://github.com/gorhill/uBlock/issues/2765#issuecomment-313447832) available for all users:

>Also, regardless of "advanced user" mode, one can toggle it by clicking the "requests blocked" or "domains connected" bars.

However, once (accidentally) opened, it has no explicit header, collapse or close button, so it is very unclear how to hide it again.

Therefore I propose either adding a better indication on how to open/close the panel (an icon in the row of zapper-picker-console-settings perhaps? or an icon in the left edge of the dark gray bar) or remove the read-only mode altogether and keep the whole panel permanent for advanced mode.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

1. Open the uBlock Origin popup by clicking on it's icon
2. Misclick on "requests blocked" or "domains connected"
3. Wonder why the dynamic filtering column opened when you did not have advanced mode enabled; wonder how to close it again

### Expected behavior:

Explicit button for closing and preferably opening the side column

### Actual behavior:

No indication of how the column opened and where to close it from; doesn't even close when toggling "advanced user mode" in settings

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: Firefox 63.0b11
* Operating System and version: macOS 10.14

**Comment by uBlock-user** [comment] 2018-10-04 11:39
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/125

**Comment by gorhill** [comment] 2018-10-04 11:41
I could add an icon on the left on hover -- that would satisfy me not wanting to clutter the UI, and provide a hint that the bar is interactive. I will evaluate the idea.

**Comment by gorhill** [comment] 2018-10-04 11:46
Note that the mouse cursor changes when hovering the "requests blocked"/"domains connected" bars, so I will always considered there was already a hint that the bars are interactive. At some point, the thing is whatever I throw at uBO's UI, there will always be someone reporting having an issue with even the most trivial stuff and I can't every single time change uBO to accommodate every instance of someone overlooking something.

**Comment by uBlock-user** [comment] 2018-10-04 11:52
This confusion arises for non-advanced users who toggle the overview panel accidently, just remove that ability for non-advanced users and make the panel static if you want to address this.

**Comment by Madis0** [comment] 2018-10-04 11:56
>Note that the mouse cursor changes when hovering the "requests blocked"/"domains connected" bars, so I will always considered there was already a hint that the bars are interactive. 

The problem is that even if they are clearly interactive, they don't toggle the content directly under it (on this page, since install, x out of y), so it is still confusing for the user.

>At some point, the thing is whatever I throw at uBO's UI, there will always be someone reporting having an issue with even the most trivial stuff and I can't every single time change uBO to accommodate every instance of someone overlooking something.

I don't agree with you, every other clickable thing in the popup is an icon.

**Comment by Madis0** [comment] 2018-10-04 12:00
What about an icon that looks like **«** and changes to **»** when open? Would also make sense to be the first icon in whichever row you choose.

**Comment by gorhill** [comment] 2018-10-04 12:14
Just want to point out that at this point the argument is based on presumption that there is an actual issue. Is there data showing that a significant (i.e. not anecdotal) amount of non-advanced users are flustered by the overview pane?

**Comment by Madis0** [comment] 2018-10-04 12:32
I've edited the post to prevent making claims I cannot verify. 

Either way, I found several issues that are related to this in some way: [old #648](https://github.com/gorhill/uBlock/issues/648) [old #2467](https://github.com/gorhill/uBlock/issues/2467) [old #3251](https://github.com/gorhill/uBlock/issues/3251) #125 #142. 

The first issue reminded me - you used to have a plus/minus symbols in the headers, that made it more obvious (to me) that the header was clickable and collapsed/expanded something.
![687474703a2f2f692e696d6775722e636f6d2f79486f795a71662e706e67](https://user-images.githubusercontent.com/8611110/46474109-b5225180-c7ea-11e8-8577-84b8290601a6.png)

**Comment by gorhill** [comment] 2018-10-04 12:39
Many of the issues you list would still have been opened even with an icon, it's users basically not paying attention to the documentation when explicitly warned with _required reading_. I have no doubt adding an icon won't prevent someone coming here to open such invalid issues, it's a statistical thing.

**Comment by Grossdm** [comment] 2018-11-07 17:53
@gorhill, I agree with you about there being a statical distribution for these things.

I wanted to comment on your reliance on mouse cursor changes (and also tool tips, I assume) to guide users.
These things are almost completely absent from mobile device interactions.
I'm still using A Samsung Note 3 (my Paleophone), and I do use its stylus to trigger mouse over events.
I have noticed that sometimes the same website on my tablet will provide more mouse event features, e.g. menus that pop open when my stylus hovers (but refusing to open with a tap from either my finger or the stylus).

I thank you very much for the color blindness friendly option! IIRC, in the US 10% of males are afflicted with one of the few forms of color blindness.

Doug®

**Comment by Madis0** [comment] 2019-11-10 09:37
I have found that Nano Adblocker has fixed this issue with a separate button:
![button](https://user-images.githubusercontent.com/8611110/68541903-0cabcd00-03ae-11ea-9dff-709488669a73.png)

Unfortunately, I am not familiar enough with either code base to make a PR.

**Comment by prateekrastogi** [comment] 2020-01-26 15:06
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by gwarser** [comment] 2020-04-30 12:38
![new popup design](https://user-images.githubusercontent.com/886325/80711045-04785300-8af0-11ea-9141-a62ab7717541.gif)

**Closed by gwarser** 2020-04-30 12:38 UTC
Labels: enhancement
