### ISSUE TITLE
Keyboard shortcut to change blocking modes

### ISSUE THREAD

**Issue by vurtomatic** [uBlockOrigin/uBlock-issues#371] opened 2019-01-07 20:25 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Add keyboard shortcut to temporarily disable uBlock Origin or change modes.

### A specific URL where the issue occurs

http://www.petit-bateau.us/women/l/600

### Steps to Reproduce

1. Open uBlock Origin's popup UI
2. Allow 3rd party scripts & frames in local rules to temporarily downgrade from Medium to Easy Mode.

### Expected behavior:

A keyboard shortcut to quickly allow 3rd party frames & scripts downgrade to Easy Mode when uBlock Origin is set to Medium.

### Actual behavior:

Currently only 3 keyboard shortcuts can be set.

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Firefox Nightly 66.0a1 (2019-01-07) (64-bit)
* Operating System and version: MacOS 10.14

**Comment by uBlock-user** [comment] 2019-01-08 09:34
Duplicate of https://github.com/gorhill/uBlock/issues/753

**Comment by gorhill** [comment] 2019-01-08 10:47
The request here is different, it's to downgrade current blocking mode as a whole.

**Comment by vurtomatic** [comment] 2019-01-08 17:36
> The request here is different, it's to downgrade current blocking mode as a whole.

Yes exactly, thank you. When uBlock Origin is in Medium or Hard mode, a lot of pages won't render properly.

It'll make for a smoother web experience if there's a keyboard shortcut that toggles the modes. Right now it's 3 steps: Open popup UI, enable local 3rd party frames & scripts, reload page.

**Comment by Hyundy** [comment] 2019-01-18 11:04
A shortcut for the javascript master switch would be very useful.

**Comment by fabeit** [comment] 2019-03-15 02:38
I second this, ublock is unusable for this purpose without a quick shortcut. Before I was using noScript which had a shortcut, I am happy with how ublock functions but a shortcut is needed.

**Closed** 2019-06-26 19:57 UTC
Labels: enhancement, fixed

**Comment by fabeit** [comment] 2019-08-30 12:17
@gorhill I am confused as to how can I use this solution? How do I assign a keyboard shortcut to toggle blocking profile?

**Comment by gwarser** [comment] 2019-08-30 12:34
Relax blocking mode:

![image](https://user-images.githubusercontent.com/886325/64020978-37b6ac80-cb33-11e9-9fee-01a94175c252.png)

**Comment by vurtomatic** [comment] 2019-08-30 13:45
Thank you so much for implementing this!!

Could this be a toggle? So pressing the shortcut relaxes the blocking mode; pressing the shortcut a second time brings it back to the previous state?

**Comment by gwarser** [comment] 2019-08-30 13:57
>TODO: At this point, I haven't yet decided whether
toggling from the lowest profile should restore the
original highest blocking profile.

https://github.com/gorhill/uBlock/commit/693687fd74fe9a4645f0c9c1e6dbedb56b5fb5d7

I don't think this is good idea for current defaults. I sometimes tap it few times without counting. Maybe _shortcut_ to relax, shift+shortcut to _restrict_(?). Or allow one more parameter in advanced settings to reset to beginning?

**Comment by fabeit** [comment] 2019-08-30 14:00
@gw

> 
> 
> Relax blocking mode:
> 
> ![image](https://user-images.githubusercontent.com/886325/64020978-37b6ac80-cb33-11e9-9fee-01a94175c252.png)
> 
> Firefox:
> 
> ![image](https://user-images.githubusercontent.com/886325/64021179-a85dc900-cb33-11e9-8810-b84c2488f693.png)
> 
> Chrome:
> 
> ![image](https://user-images.githubusercontent.com/886325/64021283-dba05800-cb33-11e9-84f6-c9fb2bbcdc67.png)

Many thanks, unfortunately I am using Waterfox, and it seems there is not menu for add-ons keyboard shortcuts. Unless someone knows a workaround via maybe about:config.

**Comment by vurtomatic** [comment] 2019-08-30 14:01
Yes that's true, it could get confusing.

What I'm noticing is because there is no visual indicator that a state has changed, I'm manually clicking on uBlock Origin's icon to see if it's been relaxed.

Like when UO is active, the icon is red, when deactivated, it's grey.

I wonder if the same red/grey color change could double up as a visual reminder?

**Comment by gwarser** [comment] 2019-08-30 14:18
@vurtomatic icon badge changes color: https://github.com/gorhill/uBlock/commit/7ff750eaf6007bdea4e843d3314fc7275b1ce945 and https://github.com/gorhill/uBlock/commit/07c950f1e5794a7cfc6d091c2f29a76557adc717. Can be configured in [Advanced settings](https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#blockingprofiles)

**Comment by yourduskquibbles** [comment] 2019-08-30 14:50
@gwarser Maybe you want to add screenshots in the [Advanced Settings](https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#blockingprofiles) section to show the badge icons in the various default color modes? 

![image](https://user-images.githubusercontent.com/22258847/64029795-48572a80-cb13-11e9-8119-9117c8f2a73c.png) = `#F00` = red = Hard mode + No scripting

![image](https://user-images.githubusercontent.com/22258847/64029335-5eb0b680-cb12-11e9-865a-e16c64de4178.png) = `#C0F` = purple = Medium mode + No scripting = 


![image](https://user-images.githubusercontent.com/22258847/64029427-8d2e9180-cb12-11e9-8fd0-5549d4140e53.png)  = `#00F` = blue = Medium Mode

![image](https://user-images.githubusercontent.com/22258847/64029861-69b81680-cb13-11e9-91fe-3c2b4d956d63.png) = default

May also be helpful to make the different mode descriptions in the Advanced Setting Mode table link to [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode) | [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode) | [default](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-easy-mode)

**Comment by fabeit** [comment] 2019-08-30 14:58
Can someone please help me with configuring the shortcut in Waterfox? pleeeeeease!

**Comment by gorhill** [comment] 2019-08-30 15:17
> add screenshots in the Advanced Settings section

Probably best added to the "Blocking mode" section. Advanced settings is for advanced users and by the time they access the "Advanced settings" page it is assumed they already understand the purpose of the color.

**Comment by gorhill** [comment] 2019-08-30 15:18
> Can someone please help me

@gwarser showed you a screenshot of uBO's dashboard where you can enter the shortcut.

**Comment by gwarser** [comment] 2019-08-30 15:48
@gorhill he's on Waterfox. No support for shortcuts on Waterfox.

**Comment by fabeit** [comment] 2019-08-30 16:29
> 
> 
> @gorhill he's on Waterfox. No support for shortcuts on Waterfox.

Is this because Waterfox is running an older version of uBO or just because WF has a different architecture? If the former Can we expect the shortcuts to come in Waterfox?

**Comment by vurtomatic** [comment] 2019-08-30 17:34
> @vurtomatic in [1.22.0](https://github.com/gorhill/uBlock/releases/tag/1.22.0) icon badge changes color: [gorhill/uBlock@7ff750e](https://github.com/gorhill/uBlock/commit/7ff750eaf6007bdea4e843d3314fc7275b1ce945) and [gorhill/uBlock@07c950f](https://github.com/gorhill/uBlock/commit/07c950f1e5794a7cfc6d091c2f29a76557adc717). Can be configured in [Advanced settings](https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#blockingprofiles)

Thank you, I wasn't aware because Firefox hasn't updated to the latest.

**Comment by gorhill** [comment] 2019-08-30 17:59
> he's on Waterfox. No support for shortcuts on Waterfox

I was expecting Waterfox would support whatever Firefox supports WebExtensions-wise. uBO only looks for [`browser.commands.update`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands/update) to decide whether to show the _Shortcuts_ pane.

**Comment by gwarser** [comment] 2019-08-30 18:00
![image](https://user-images.githubusercontent.com/886325/64041876-db6a8180-cb60-11e9-9194-7662f4368350.png)

**Comment by gorhill** [comment] 2019-08-30 18:11
I see. So the [Alpha version](https://www.waterfox.net/releases/) should support it, as it appears to be based on Firefox ESR 68.

**Comment by emanruse** [comment] 2019-08-31 16:16
Can somebody please enlighten me how to use this "Relax blocking mode"? The wiki talks about it, here I see a talk about it and screenshots but there is no "Shortcuts" tab in my options at all. I am using uBO 1.22.0 in Chromium (Linux).

**Comment by gorhill** [comment] 2019-08-31 16:22
https://github.com/uBlockOrigin/uBlock-issues/issues/371#issuecomment-526584396

**Comment by gwarser** [comment] 2019-08-31 16:42
@emanruse  https://streamable.com/3ctyn

**Comment by emanruse** [comment] 2019-08-31 19:01
Thank you guys. For some reason that image wasn't loading for me.

@gorhill do you think you could add those clarifying images to the wiki?

**Comment by gwarser** [comment] 2019-08-31 19:24
Done - https://github.com/uBlockOrigin/uBlock-issues/wiki/Keyboard-shortcuts

**Comment by emanruse** [comment] 2019-08-31 19:39
Thanks @gwarser!

**Comment by vurtomatic** [comment] 2019-09-02 17:11
> > TODO: At this point, I haven't yet decided whether
> > toggling from the lowest profile should restore the
> > original highest blocking profile.
> 
> [gorhill/uBlock@693687f](https://github.com/gorhill/uBlock/commit/693687fd74fe9a4645f0c9c1e6dbedb56b5fb5d7)
> 
> I don't think this is good idea for current defaults. I sometimes tap it few times without counting. Maybe _shortcut_ to relax, shift+shortcut to _restrict_(?). Or allow one more parameter in [advanced settings (draft)](https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#blockingprofiles) to reset to beginning?

After using 1.22 a bit with the keyboard shortcut to relax blocking mode and the color indicator, I think it would be nice to have a shift+shortcut to reverse the relaxed mode back to default.
