### ISSUE TITLE
Comments in 'Trusted Sites' get sorted with sites

### ISSUE THREAD

**Issue by CReich02** [uBlockOrigin/uBlock-issues#2798] opened 2023-09-03 19:04 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

According to the [documentation](https://github.com/gorhill/uBlock/wiki/How-to-mark-a-web-site-as-trusted#detailed-syntax) 
> A comment is a line prefixed with #. Comments are ignored by uBO.

But if I try to add a comment before a site and save it my comment gets sorted based on the first non-whitespace character after a #. It's even sorting it by the second # if I add '##Comment'.
I am guessing that this means the comment is just ignored by the uBO engine. If that is the case I this is more of an enhancement request than a bug but I don't see anywhere to submit enhancement requests.

It would be nice to have an option to sort items after a comment independently, or add ## as a region separator. This would allow people to create blocks of trusted site rules with a note saying what they're for.

### A specific URL where the issue occurs.

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#whitelist.html

### Steps to Reproduce

If I were to add the following trusted sites
```
Google.com
## Work Sites
MyWorkSite.org
MyOtherWorkSite.com
```

### Expected behavior

I would like it to sort like this
```
Google.com
## Work Sites
MyOtherWorkSite.com
MyWorkSite.org
```

### Actual behavior

It currently sorts it like this
```
## Work Sites
Google.com
MyOtherWorkSite.com
MyWorkSite.org
```

### uBO version

uBlock Origin 1.51.0

### Browser name and version

Google Chrome Version 116.0.5845.141 

### Operating System and version

Windows 10

**Comment by gwarser** [comment] 2023-09-03 19:54
Duplicate of https://github.com/gorhill/uBlock/issues/2627

Also https://github.com/gorhill/uMatrix/issues/314#issuecomment-128793820

**Closed by gwarser** 2023-09-03 19:54 UTC
