### ISSUE TITLE
Filter list additions

### ISSUE THREAD

**Issue by Ollifi** [uBlockOrigin/uBlock-issues#305] opened 2018-11-12 17:10 UTC
https://github.com/uBlockOrigin/uBlock-issues/issues/304
Instead of just rudely closing the issue, please inform where the filter list addition requests should be posted. A Finnish filter list does not exist at the moment in uBlock Origin, but has been already created a by a new user so it should definitely be added - I will submit the suggestion to correct place, please just inform where it should be done. Thanks!

**Comment by uBlock-user** [comment] 2018-11-12 17:48
There is NO correct place, please don't post filter lists additions requests. This was internally decided by gorhill and the uBO Volunteers. If a list is to be added it will b decided by gorhill and the team, not by posting suggestions here. It's already listed twice(in the template and in the README.MD) and yet you don't read and post it on a whim.

**Comment by uBlock-user** [comment] 2018-11-12 17:49
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/304

**Closed by uBlock-user** 2018-11-12 17:48 UTC

**Comment by jspenguin2017** [comment] 2018-11-12 22:58
Submit the filter to the database: https://github.com/collinbarrett/FilterLists

If it is useful people will know.
