### ISSUE TITLE
Allow My Filter to override Ignore generic cosmetic filters

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#821] opened 2019-12-19 07:53 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, cosmetic filters on My Filters will be applied even when Parse and enforce cosmetic filters option is turned off. I hope the same logic to be applied to Ignore generic cosmetic filters option. I check this option for not only performance, but also to reduce false positives, but I still wanna apply a few generic cosmetic filters such as ##.adsbygoogle. I currently do this by listing all the major TLDs (e.g. com, net, org##.adsbygoogle), but too many TLDs are out there.

### A specific URL where the issue occurs

moz-extension://(uBO ID)/dashboard.html#1p-filters.html

### Steps to Reproduce

1. Write a generic cosmetic filter in My Filters.
2. Go to a site the filter on step1 should work.
3. It won't be applied.

### Expected behavior:

Noted above.

### Actual behavior:

Noted above.

### Your environment

* uBlock Origin version:v1.24.2 on Brave, Firefox, and Firefox Mobile
* Browser Name and version: Brave 1.1.22, Firefox 71.0, and Firefox Mobile 68.3.0
* Operating System and version: Windows 10 and Android 10

**Comment by uBlock-user** [comment] 2019-12-19 08:38
> Currently, cosmetic filters on My Filter will be applied even when Parse and enforce cosmetic filters option is turned off.

@gorhill I can reproduce this. Something broke ? cosmetic filters are getting applied regardless of whether the setting is enabled or not.

**Comment by gwarser** [comment] 2019-12-19 09:17
> Something broke ? Cosmetic filters are getting applied regardless of whether the setting is enabled or not.

By design.

![image](https://user-images.githubusercontent.com/886325/71160962-ce28ee00-2248-11ea-98f9-2b16616f1fa0.png)

**Comment by Yuki2718** [comment] 2019-12-19 09:24
I believe my suggestion will potentially be beneficial to all mobile users, given generic cosmetic filters are turned off by default. They can just copy and paste a solution of some problem posted somewhere w/out toggling the setting.

**Comment by gorhill** [comment] 2019-12-19 12:43
Related: <https://github.com/gorhill/uBlock/issues/1940#issuecomment-338966457>.

**Comment by Yuki2718** [comment] 2019-12-19 16:31
> 
> 
> Related: [gorhill/uBlock#1940 (comment)](https://github.com/gorhill/uBlock/issues/1940#issuecomment-338966457).

So, a single generic cosmetic filter nullifies all the performance benefit of the setting. But as I noted I use this to reduce false positives too. It should also slightly decrease chances you get ad-block warnings.

And a possible solution is, if I understand it correctly, changing its behavior to one somewhat similar to ABP unless a user put too many generic filters? I just want to put exactly 2 filters. The number may increase in future, but I highly doubt it exceeds 20. Maybe you can add a new option that appears only if both I am an advanced user and Ignore generic cosmetic filters are turned on (with an additional warning), or hide a new variable behind the advanced setting. This will negates a benefit in my above comment, but will still be useful to some advanced users.

**Comment by Yuki2718** [comment] 2020-03-18 06:09
I missed https://github.com/uBlockOrigin/uBlock-issues/issues/803 but confirmed *##selector works on current stable build. I guess this issue can be closed, doesn't it?

**Comment by gorhill** [comment] 2020-03-18 11:46
I am still thinking about making the `*` implicit for generic cosmetic filters when the following conditions are all fulfilled:

- Filter is from _"My filters"_
- Option _"Ignore generic cosmetic filters"_ is checked

The only worry is that such behavior could confuse filter list maintainers -- something which would happen when a filter behaves differently according to whether it is from _"My filters"_ or from a filter list.

**Comment by Yuki2718** [comment] 2020-03-18 14:04
Okay, I leave it to you : )

**Comment by gorhill** [comment] 2021-06-24 13:44
Best to keep filters in _"My filters"_ behaving like filters in filter lists, so that filter list authors can reliably craft filters which will behave predictably when transferred to a filter list.

**Closed by gorhill** 2021-06-24 13:44 UTC
Labels: enhancement
