### ISSUE TITLE
Logger incorrectly reporting `header=` filters

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uBlock-issues#1932] opened 2022-01-18 15:22 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I understand this is still experimental but after upgrading to 1.40.8, filters with a `header=` option is incorrectly reported as `header=[object Object]` (literally) in the uBO logger. I also do not see any warning not to open issues about this in the Static filter syntax wiki page.

### A specific URL where the issue occurs

Everywhere but `https://news.ycombinator.com/` may be a good example.

### Steps to Reproduce

1. Pick a header and add `*$script,header={header_name}:{header_value}` to _My filters_.
2. Open DevTools and the uBO logger and visit the site.
3. Use DevTools and the logger to confirm that the response body is blocked.
4. Click on the static filter in the logger to find out where it originates from.

### Expected behavior

Logger correctly reports the filter as `*$script,header={header_name}:{header_value}` and originating from _My filters_. This worked as expected in 1.39.2.

### Actual behavior

Logger reports the filter as `*$script,header=[object Object]` and returns _Static filter could not be found in any of the currently enabled filter lists_.

Some other `header=`-related quirks that I noticed but don't know if you want them filed:
1. Header name is case-sensitive. This means `$header=header_name` will only match `header_name` but not `Header_Name`. This is problematic because some sites (e.g. `https://news.ycombinator.com`) capitalize the first letter of each word in their headers.
2. Regex can only be applied to the `header_value` field but not `header_name` or `header_name:header_value`. My current workaround is to add two filters, one capitalized and one non-capitalized.
3. Logger also returns _Static filter could not be found in any of the currently enabled filter lists_ when there are two regex in one filter, for example `/^regex$/$script,header=header_name:/^header_value$/,_`.
4. Again I understand the `header=` filter option is still experimental, but should this ever move to stable status, it would be nice to have some sort of indication (a different shade/color?) in the uBO logger that only the response is blocked. Currently it looks like (understandably) that a network request is not blocked and then very quickly blocked in the logger.

I can provide a potential use case if you need one to proceed.

### uBlock Origin version

1.40.8

### Browser name and version

Firefox 96.0.1

### Operating System and version

_N/A_

**Comment by gwarser** [comment] 2022-01-18 18:58
Point 3: 

- this is fine `/news\.ycombinator\.com/$header=Server:/nginx/,domain=ycombinator.com`
- this too `/news\.ycombinator\.com/$domain=ycombinator.com,header=Server:/nginx/,_`
- this one cannot be found `/news\.ycombinator\.com/$header=Server:/nginx/,_`

**Comment by gorhill** [comment] 2022-01-28 15:31
> this one cannot be found `/news\.ycombinator\.com/$header=Server:/nginx/,_`

This is not specific to `header` option, this also occurs for `removeparam`:

    /news\.ycombinator\.com/$removeparam=/server=nginx/,_

This happens because the `_` noop option is dropped, it has no internal representation, and when the filter is "decompiled" from its internal representation at logging time, there is no `,_` added to the canonical representation.

For now I will improve the parser to have it better guess that `/news\.ycombinator\.com/$removeparam=/server=nginx/` as a whole is not to be treated as the pattern for a regex-based filter -- we can assume that when `$` is followed by `~?[\w]+[^\$]*$`, surely the while thing is not a regex-based pattern. Maybe this will allow to drop having to use `_` to solve ambiguity.

**Comment by otksm** [comment] 2022-02-19 09:15
More regarding point 1 (and by extension, point 2):

`https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2`

> Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion.  However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2.  A request or response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6).

So it would seem like only websites served through HTTP <= 1.x are affected by point 1. Maybe this in itself is a useful narrowing option (e.g. targeted scripts were only served 
through HTTP/2 websites) and therefore not worth fixing?

**Comment by gorhill** [comment] 2023-12-04 17:22
> this one cannot be found `/news\.ycombinator\.com/$header=Server:/nginx/,_`

I can't reproduce this with latest dev build, probably fixed at some point while improving static filtering parser.

**Comment by gwarser** [comment] 2023-12-04 18:19
Fixed in last commit linked https://github.com/gorhill/uBlock/commit/aa6baf9a29db574038e7aad5373cecf7e48c5889

**Closed** 2023-12-04 18:19 UTC
Labels: bug, fixed
