### ISSUE TITLE
Cosmetic filters interfere with element picker visuals

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#1226] opened 2020-08-28 11:51 UTC
Google Chrome 85.0.4183.83 
uBO 1.29.2 default + RU AdList

Sometimes filter authors need to add rules that enforce the background colors, for example [here](https://ua.news/ru/). In this case, when trying to use element picker, the user sees the following: https://i.imgur.com/lLCzAbN.jpg

**Comment by gorhill** [comment] 2020-08-28 13:02
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/1215>.

**Comment by dimisa-RUAdList** [comment] 2020-08-28 16:07
[Temporary fix](https://hg.adblockplus.org/ruadlist/rev/be13490bd1f2)

**Comment by gorhill** [comment] 2020-08-28 16:10
Why not just use:

    cartoonka.art,multmania.club,tlumtluda.info#?#body:style(background: unset !important)

?

**Comment by dimisa-RUAdList** [comment] 2020-08-28 16:13
They probably periodically assign a background color consistent with the ad.

**Comment by gorhill** [comment] 2020-09-01 18:07
#1215 is now fixed with <https://github.com/gorhill/uBlock/commit/9eb455ab5eb2d5640f4188e71011b7aa22ab8b43>, but this didn't fix the issue here, so re-opening.

Possibly the fix is to move the `svg` inside the protected `iframe` as well, so that in the end nothing else is exposed to the page's DOM.

**Closed** 2020-09-03 17:09 UTC
Labels: bug

**Comment by dimisa-RUAdList** [comment] 2020-09-03 17:24
I will remove the interim fix rules after the new stable release is available in the Google Chrome store.

**Comment by gargul2** [comment] 2020-09-08 13:18
The bug still need further fixing?
Or is that how uBO works now since 1.29.2?
The issue is still present until I remove 
`body { background-color: #a09aaf !important; }` 
from my `profile/chrome/userContent.css` (and restart browser),
this is my `userContent.css`:

```
a:visited {
    color: #009933 !important;
}

@-moz-document url-prefix("moz-extension://3b93d1ad-08b5-4af2-bc8d-4087e348a41e/") 
{
	body { background-color: #a09aaf !important; }
	.root { background-color: #a09aaf !important; }
	.CodeMirror { background-color: #a09aaf !important; }
	#dashboard-nav { background-color: #cccccc !important; }
        div#actions { background-color: #a09aaf !important; }
}
```

In Firefox I have been always using `profile/chrome/userContent.css` custom settings for customize uBO colors, and I never have been having any issues with this particular `body` setting in older versions of uBO, now in uBO 1.29.2 & 1.29.3b10, I must remove the `body` filter to fix Element Picker, otherwise, whenever I try to pick anything I get:

https://user-images.githubusercontent.com/63287518/92480922-dadddf80-f1e5-11ea-97e9-8d10dcc6ec55.gif
https://user-images.githubusercontent.com/63287518/92480931-ddd8d000-f1e5-11ea-8887-bc65fa7532e2.gif

**Comment by uBlock-user** [comment] 2020-09-08 13:30
@gargul2 Not related, the issue here is solved by isolating the Picker from the website, so rules written for any website can never affect the Picker.

**Comment by gorhill** [comment] 2020-09-08 13:38
Your `userContent.css` styles have priority over uBO's styles. Such personal browser customizations are for you to fix.

**Comment by krystian3w** [comment] 2020-10-08 08:57
https://old.reddit.com/r/uBlockOrigin/comments/j76akv/window_blacked_out_when_element_picker_active/

Only a typo with a version is suspect: [`1.3.0`](https://github.com/gorhill/uBlock/releases/tag/1.3.0) instead of `1.30.0`/`1.30.2`

---

All in all, I am also in favour of not fixing it in Addon, Mozilla has marked the file as outdated technology.

**Comment by gorhill** [comment] 2020-10-08 11:30
> in favour of not fixing it in

This can't be fixed anyways, userContent.css has highest precedence -- it's for the users themselves to fix.

**Comment by krystian3w** [comment] 2020-10-08 11:47
So maybe pin these post on reddit.

But how long can it hang on reddit as if it were pinned, because I see that the old topic about the Opera 57+ has "detached" himself due archivisation.
