### ISSUE TITLE
Lose all scrollbars in [My filters, My rules and Trusted sites] settings page.

### ISSUE THREAD

**Issue by tntc4** [uBlockOrigin/uBlock-issues#1287] opened 2020-10-10 07:25 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When uBlock implement new codeMirror functionality, my Settings page lose all the scroll bars.

### A specific URL where the issue occurs

[My filters] [My rules] [Trusted sites]

### Actual behavior:

[See screenshot I have provided]
Notice the line numbers on the left and no scrollbar on the right.
![Screenshot_1](https://user-images.githubusercontent.com/3246834/95648802-b3c74600-0ae2-11eb-98b0-33a971a742d2.png)

### Your environment

* uBlock Origin version: v1.30.2
* Browser Name and version: Chrome Version 70
* Operating System and version: Windows 7 Ultimate (64bit)

**Comment by uBlock-user** [comment] 2020-10-10 07:38
> Chrome Version 70

Why running on such outdated version ?

**Comment by tntc4** [comment] 2020-10-10 07:39
uBlock Origin still working and will receive future fixes... so why not?

**Comment by gorhill** [comment] 2020-10-10 11:39
I can't test such an old version of Chromium on my side. Could you try to add the CSS property `min-height: 0` to the element selected in the screenshot and see if this brings back the scrollbar?

![a](https://user-images.githubusercontent.com/585534/95654110-933fc180-0acb-11eb-892c-c3413b0705b4.png)

**Comment by tntc4** [comment] 2020-10-10 11:49
I tested it now but no scrollbars shown.
This problem is definitely is caused by CodeMirror script you use, because I found something weird.
see screenshot
![Screenshot_2](https://user-images.githubusercontent.com/3246834/95654290-bc7e4300-0b07-11eb-8ddc-2d3f0ea921b9.png)

**Comment by gorhill** [comment] 2020-10-10 11:59
I don't think it's CodeMirror, it probably copy the height from the root container I selected in my screenshot. I think the problem is Chromium not properly implementing `flex`, for example <https://bugs.chromium.org/p/chromium/issues/detail?id=927066>. The solution is to find a workaround, and it will have to apply to the root container.

**Comment by tntc4** [comment] 2020-10-10 12:00
thank you

**Comment by gorhill** [comment] 2020-10-10 12:08
Yes, I started to use `display: flex`, this way I don't need to use JS to resize the CodeMirror editor to fill the available space when you resize the browser. I remember old versions of Chromium having issues with `flex`.

What if you try `min-height: 0` on this element:

![a](https://user-images.githubusercontent.com/585534/95654702-cf752100-0acf-11eb-8bad-f0329bfb4d2e.png)

**Comment by tntc4** [comment] 2020-10-10 12:15
I try your code but it's still not working.
Today I will prepare some testings and I will post more information here.

**Comment by tntc4** [comment] 2020-10-11 18:04
I delete all my rules and test with simple numbers just to fill all the rows untill scroll bars appear.
This is not working on Chrome...
I installed the uBlock Origin latest version on Brave browser (also outdated) and try the same - just put a numbers on every row untill scroll bars appear.
This time it's works but then I inspect the DOM structure and I find the diferences on both browsers.
The element with class **.CodeMirror-vscrollbar** has style rule "**display: block**" on Brave browser, but on Chrome this element does not have this rule.
When I try to put this rule on Chrome browser, the scroll bars appear.
I will provide screenshots to demonstrate the diferences.
### Chrome
![Chrome](https://user-images.githubusercontent.com/3246834/95686173-f84b0280-0c04-11eb-9502-4f54d821bb39.png)
### Brave
![Brave](https://user-images.githubusercontent.com/3246834/95686189-0436c480-0c05-11eb-9104-1797d992b28e.png)

**Comment by gorhill** [comment] 2020-10-11 18:09
Well if you installed Brave I am guessing it's using a more recent version of Chromium -- so your test essentially demonstrate what we already know, that at some point Chromium fixed the issue so that it no longer exists.

**Comment by tntc4** [comment] 2020-10-11 18:11
my Brave broser is Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit) on the time I test these thing.
As you see Chromium: 78.0.3904.97 is also outdated :)

**Comment by gorhill** [comment] 2020-10-11 18:12
I don't understand the point you are making beside the issue does not exist in Chromium 78, hence it was fixed between Chromium 71 and 78.

**Comment by tntc4** [comment] 2020-10-11 18:15
I understand you don't want to invest time to fix this on outdated Browsers, I'm ok with that.
Thank you for you patience :)

**Comment by gorhill** [comment] 2020-10-11 18:28
It's not that I do not want to fix, it's that I can't investigate a fix -- it's best that a solution is investigated by whoever has Chromium 70 installed.

**Comment by tntc4** [comment] 2020-10-11 19:47
I have uploaded Chrome 70 to my dropbox.
[Chrome 70](https://www.dropbox.com/s/3j27zs1w30psjfc/70.0.3538.77_chrome_installer.exe)
If you have virtual mashine you can test it.

**Comment by tntc4** [comment] 2020-10-11 20:48
I hate Google because they remove one usefull option from the Chrome 73+
This option is when a site play a audio the small ison is displayed on the tab, and you can easily mute the tab, yes they put an option mute the site but i want to mute a tab not a whole site.
This is the reason i stick with the Chrome 71.

**Comment by gargul03** [comment] 2020-10-12 07:53
Any issues with using the newest Chrome browser + Chrome extenstions which restore the 'Mute Tab' functionality of versions prior to Chrome 71?: 
- [Mute Tab](https://chrome.google.com/webstore/detail/mute-tab/blljobffcekcbopmkgfhpcjmbfnelkfg)
- [Tab Muter](https://chrome.google.com/webstore/detail/tab-muter/bnclejfcblondkjliiblkojdeloomadd)

**Comment by gargul04** [comment] 2020-10-14 12:42
@tntc4 Any issues using the newest Chrome + Chrome extensions which restore the functionality?: 
- [Mute Tab](https://chrome.google.com/webstore/detail/mute-tab/blljobffcekcbopmkgfhpcjmbfnelkfg)
- [Tab Muter](https://chrome.google.com/webstore/detail/tab-muter/bnclejfcblondkjliiblkojdeloomadd)

**Comment by gorhill** [comment] 2020-10-14 12:53
> If you have virtual mashine you can test it.

I am going to wait for somebody who uses this obsolete version of Chromium to investigate and provide a reasonable fix which does not affect negatively later versions of Chromium.

**Comment by tntc4** [comment] 2020-10-14 12:54
OK thanks.
So I can close this issue now?

**Comment by gorhill** [comment] 2020-10-14 12:59
It's marked as a "good first issue", meaning it's there to be fixed by whoever feels like contributing.

**Comment by rodhod** [comment] 2020-10-16 05:08
can we just add some js to use `display: block` on chrome versions < 78?  (or chrome 74 i think that is when it was fixed). also would changing the css break anything else in newer versions of chrome or firefox?

**Comment by gorhill** [comment] 2020-10-16 09:28
Yes, using block break the page when resizing the browser. CSS is declarative and you can declare properties conditional on browser version.

**Comment by krystian3w** [comment] 2020-11-03 13:19
> you can't declare properties conditional on browser version.

For the detection of chrome 70-78 you can try to use:

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

- As long as the chromium clearly shows what new it has added in CSS as supported or marked as no longer available. If there is nothing in CSS that can detect by `@supports` property, this method is also out of scope.

   - Unless this interferes with the readability of css - you have to strive for something compatible with Chrome old/new and Firefox.

**Comment by tntc4** [comment] 2020-12-14 13:00
sorry for the delay.
I just checked and ... I have scrollbar with uBO v1.31.2 (my filters), but no scrollbars on (my rules) screens.
also on my filters screen the filters area is colapsed.
thanks for the support for older browsers.

check screenshot
![Screenshot_My Filters](https://user-images.githubusercontent.com/3246834/102083621-86698200-3e1c-11eb-890b-78d9356469a5.png)
![Screenshot_My Rules](https://user-images.githubusercontent.com/3246834/102083763-bf095b80-3e1c-11eb-8ed0-4b5ef7e9f49d.png)

**Closed** 2022-09-09 23:52 UTC
Labels: good first issue, wontfix, Chromium
