### ISSUE TITLE
Calculate energy conserved

### ISSUE THREAD

**Issue by Sophivorus** [uBlockOrigin/uBlock-issues#2003] opened 2022-02-23 02:17 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

@gorhill Hi! You're probably aware that uBlock Origin not only blocks ads and trackers, but also saves lots of time and energy, not only from your CPU but also globally by preventing oh-so-many unnecessary requests. In fact, it saves more energy than other content-filtering tools, according to https://www.appropedia.org/Energy_Conservation_with_Open_Source_Ad_Blockers

I think this is no minor fact, especially considering the global efforts to reduce carbon emissions. Thus, if it were possible to estimate, aggregate and display the energy saved, it could be an important extra "selling point", environmentalists would definitely embrace and recommend it, and uBlock Origin may receive lots of new users, contributors and support for its significant contribution to energy conservation.

Thanks to you and everyone involved for developing this awesome tool! Kind regards,

### A specific URL where the issue occurs

https://www.appropedia.org/Energy_Conservation_with_Open_Source_Ad_Blockers

### Steps to Reproduce

1. Open uBlock Origin dialog on any page
2. Look at the number of elements blocked since installation

### Expected behavior

See an estimate of energy saved

### Actual behavior

No estimate of energy saved can be seen

### uBlock Origin version

1.41.2

### Browser name and version

Chrome 98.0.4758.91

### Operating System and version

Chrome OS 98.0.4758.91

**Comment by uBlock-user** [comment] 2022-02-23 05:43
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/781

**Closed by uBlock-user** 2022-02-23 05:43 UTC
