### ISSUE TITLE
Regression with `important` filter option

### ISSUE THREAD

**Issue by DesertBear** [uBlockOrigin/uBlock-issues#1732] opened 2021-09-24 13:14 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBlock Origin is ignoring some rules in "_My Filters_" and therefore not blocking content when it should.

The issue started happening after the extension updated to uBlock Origin 1.38.0.  The rules worked OK in uBlock Origin 1.37.2.

The issue appears to affect rules that use the `$important` tag.

### A specific URL where the issue occurs

See "Steps to Reproduce" section.

### Steps to Reproduce

**Example 1:**

**1)** Add the below filter rule to uBlock Origin "_My Filters_".
```
||www.msn.com^$important
```

**2)** Go to the below URL.

`https://www.msn.com/`

**3)** The page should be blocked by uBlock Origin and a uBlock Origin page should be displayed informing the user that uBlock Origin has prevented the page from loading and giving the user the option to choose whether to temporarily/permanently allow it.  However, this does not happen – the page is not blocked.

![Screenshot A](https://user-images.githubusercontent.com/27423064/134678343-42f8c769-9b61-4ca4-9862-5af444a08f8c.png)

**Example 2:**

**1)** Add the below filter rules to uBlock Origin "My Filters".

Either:
```
||disqus.com^$important
||disquscdn.com^$important
```

Or:
```
||disqus.com^$important,third-party
||disquscdn.com^$important,third-party
```

**2)** Go to the below URL.
`
https://mspoweruser.com/microsofts-pc-health-check-app-is-popping-up-scary-disclaimers-for-unsupported-pcs/`

**3)** The disqus.com third-party content (comments) at the bottom of the page should be blocked by uBlock Origin.  However, this does not happen – the content is not blocked.

![Screenshot B](https://user-images.githubusercontent.com/27423064/134678571-f59cd0b6-39b2-464c-993a-6167366cb880.png)

### Expected behavior

The rules should be honoured and the content blocked.

### Actual behavior

The rules are ignored and the content is not blocked.

### uBlock Origin version

uBlock Origin (1.38.0)

### Browser name and version

The issue occurs in Microsoft Edge Stable (93.0.961.52) and Google Chrome Stable (94.0.4606.61).  ~~This issue does not occur in Mozilla Firefox (92.0.1).~~ **Edit:** The Mozilla Firefox addons page is still using uBlock Origin 1.37.2.

### Operating System and version

Windows 10 - 21H1 (19043.1237)

**Comment by uBlock-user** [comment] 2021-09-24 13:20
https://github.com/gorhill/uBlock/commit/a2a8ef7e851471b3902ff1606f9266bfd93669ed

Not ignoring, `$important` will now only work if there's a exception filter present in any of all subscribed lists(including my filters).

So use `||www.msn.com^` instead.

**Comment by DesertBear** [comment] 2021-09-24 13:42
> > This issue does not occur in Mozilla Firefox (92.0.1).
> 
> Not specific to any browser, will happen everywhere. ~Your Firefox uBO config must have an exception filter present.~ Firefox users haven't been updated to 1.38.0 yet. Once that update occurs, you will be able to repro that behavior there too.

Ah yeah, the Mozilla addons page is still using 1.37.2; I overlooked that.

**Comment by gorhill** [comment] 2021-09-24 14:12
I wish this would have been caught in the dev build -- we really need more people using the dev build.

**Comment by uBlock-user** [comment] 2021-09-24 14:13
Thought this was a side-effect of https://github.com/gorhill/uBlock/commit/a2a8ef7e851471b3902ff1606f9266bfd93669ed, so didn't report.

**Comment by gorhill** [comment] 2021-09-24 14:22
It is a regression, `||www.msn.com^$important` is definitely supposed to strict-block `www.msn.com`.

**Comment by felix-22** [comment] 2021-09-24 14:22
Yeah.

> Not ignoring, `$important` will now only work if there's a exception filter present in any of all subscribed lists(including my filters).
> 
> So use `||www.msn.com^` instead.

- but this is not only `important` option which is discarded, the whole filter is discarded
- when  creating a filter and appending an `important` option, the intention most likely is the whole filter still should work, regardless of the `important` option is being discarded, otherwise many important filters may just stop working..the issue now is the user must create two filters: `||wp.pl^` + `||wp.pl^$important` in case the second one stops working...

**Comment by gorhill** [comment] 2021-09-24 15:00
Fortunately it turns out this regression does not affect many filters in default filter lists, because a number of conditions must be fulfilled for the regression to occur. These are the filters I found _may_ be broken if there exist an exception filter also being triggered:

```
||focus.de^$ghide,important
||pcwelt.de^$ghide,important
||fotzenparty.eu^$important
||d1n3tk65esqc4k.cloudfront.net^$important
||noakauhe.com^$3p,important
||ryllae.com^$3p,important
||79zgycmr.com^$3p,important
||f5v1x3kgv5.com^$3p,important
||lvgvax82bp.com^$3p,important
||metrika.lookmovie.io^$important
||inpagepush.com^$important
```

In any case, I will publish an emergency fix.

**Comment by felix-22** [comment] 2021-09-24 15:36
> gorhill : https://github.com/uBlockOrigin/uBlock-issues/issues/1732#issuecomment-926696368

The problem also or even primarily was present when there was no exception filter existing at all, anyway, the both cases are fixed now (Opera).

**Comment by gorhill** [comment] 2021-09-24 15:45
> The problem also or even primarily was present when there was no exception filter coexisting at all

You are right, my mistake.

**Comment by felix-22** [comment] 2021-09-24 15:53
Hmm, the logger still says `||www.msn.com^$important` given there is no exception filter coexisting.
Is this ok or should it be saying just `||www.msn.com^` given the fact `$important` has been dropped?
I mean is it better to inform an user in the logger:
- about a filter which actually is present in the filter list or
- about a filter which actually is being applied?

As far I know in case of `||www.msn.com^$all` the logger says not about `$all` but rather about what has been actually applied, for ex. `doc`

**Comment by gorhill** [comment] 2021-09-24 15:56
> Is this ok or should it be saying just ||www.msn.com^ given the fact $important has been dropped?

`important` has not been dropped.

**Comment by felix-22** [comment] 2021-09-24 16:03
Ok, whatever, from the commit's description https://github.com/gorhill/uBlock/commit/a2a8ef7e851471b3902ff1606f9266bfd93669ed and from https://github.com/uBlockOrigin/uBlock-issues/issues/1732#issuecomment-926619690 I thought `important` is only being applied if a coexisting exception is found, maybe _matched_ meant something different than _applied_.

**Comment by gorhill** [comment] 2021-09-24 16:20
It's an implementation detail being described, there is no change in behavior for clients of the static network filtering engine.

**Comment by felix-22** [comment] 2021-09-24 16:43
Ok, I understand now: it's an internal performance improvement enhancement, and not a change in terms of functionality.

**Comment by gorhill** [comment] 2021-09-24 16:57
> `||focus.de^$ghide,important`
> `||pcwelt.de^$ghide,important`

I checked these two notable sites to find out how the regression affects them, but after enabling the stock DEU list, I can't see any exception filters reported in the logger, i.e. it appears these filters no longer serve a purpose, meaning this somewhat lowers the severity of the regression.

@okiehsch Are these filters obsolete?

**Comment by okiehsch** [comment] 2021-09-24 17:04
Yes.

**Comment by felix-22** [comment] 2021-09-24 17:56
I've checked `focus.de` and doesn't seem so, I do have exceptions hits on both Firefox and Opera, on uBO stock settings + EasyList Germany (assuming EL Germany is a stock list for Germany), so it seems the important filter is not obsolete:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | @@\|\|focus.de^$generichide | ++ | static.focus.de | 1 | generichide | `https://static.focus.de/fol/dpa_feed_widgets/my_fb_mbl_html/html_php/index_html_SATable_2012.html?customFont=true&initialWidth=300&childId=pym-0-4x3qf&parentTitle=FOCUS%20Online%20-%20Nachrichten&parentUrl=https%3A%2F%2Fwww.focus.de%2F` |
| +0 | @@\|\|focus.de^$generichide | ++ | `www.focus.de` | 1 | generichide | `https://www.focus.de/` |
</details>

A note: in case anybody still uses Fanboy Enhanced Tracking, there are hits as well:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | @@\|\|focus.de^$generichide | ++ | static.focus.de | 1 | generichide | `https://static.focus.de`
| +1 | @@\|\|focus.de^$generichide | ++ | `www.focus.de` | 1 | generichide | `https://cmp.focus.de/index.html?message_id=511992&consentUUID=bdba35ff-6030-4e05-94c7-889eb8bc2eaf&requestUUID=f2f7fd3c-0b84-4bea-ac53-65a4ce2193bf&preload_message=true` |
| +0 | @@\|\|focus.de^$generichide | ++ | `www.focus.de` | 1 | generichide | `https://www.focus.de/` |
</details>

**Comment by okiehsch** [comment] 2021-09-24 18:12
To be clear, the generichide filters for both sites are still part of `EasyList Germany` however I don't see the need to overwrite those filters in `uBO-filters` anymore.
I don't see any blank spaces on either site caused by the generichide filters that's why I removed the important filters.

**Comment by gorhill** [comment] 2021-09-24 18:39
Actually, I had forgotten but the `ghide` filters should not have been affected by the regression, their are matched in another code path not affected by the regression.

**Closed** 2021-09-24 20:52 UTC
Labels: bug

**Comment by uBlock-user** [comment] 2021-09-24 21:03
@gorhill Seems  `$important` filters are counted as `2` now ?

**Comment by felix-22** [comment] 2021-09-25 06:53
Also negated network options are counted differently, example:
`||wp.pl^$~script` is counted as 10 in 1.37.2
`||wp.pl^$~script` is counted as   1 in  1.37.3rc5
The issue introduced somewhere between: 1.37.3rc1-1.37.3rc5

**Comment by uBlock-user** [comment] 2021-09-25 07:12
> negated network options are counted differently

Not related, see https://github.com/gorhill/uBlock/commit/8f98622374ca36e69c60878979583b55615d4dd9

**Comment by felix-22** [comment] 2021-09-25 08:31
The commit you mentioned cannot be the cause, as the issue is already present in  1.37.3rc4 or 1.37.3rc5 which is dated `15.09.2021`, while the commit is dated `23.09.2021`, unless there is another earlier similiar commit I'm unaware of - but I couldn't find any in the change log https://github.com/gorhill/uBlock/compare/1.37.2...1.38.0

> https://github.com/gorhill/uBlock/commit/8f98622374ca36e69c60878979583b55615d4dd9 :
> Before this commit, there was no actual negated types in the
> static network filtering engine

Most likely it seems the commit you've mentioned is an attempt to fix the issue with counting we both spotted, but the fix only applies to the logger.

**Comment by gorhill** [comment] 2021-09-25 11:23
> Seems $important filters are counted as `2` now ?

Yes, side effect of the change. Fixing this would not be trivial, so for now we will have to accept this. On the other hand the fix regarding negated types no longer causes one filter to be counter as multiple ones.

**Comment by gorhill** [comment] 2021-09-25 11:26
> so most likely they are related

They are not, each separate change had both an effect on how filters are counted -- the way filters are counted depends strongly on hidden implementation details, which were changed in both changes.

**Comment by felix-22** [comment] 2021-09-25 12:20
> On the other hand the fix regarding negated types no longer causes one filter to be counter as multiple ones.

Are you talking about the commit uBlock-user mentioned? What you described ("no longer to be counted as multiple ones") does happen already before the commit, hence I'm curious which another (earlier) commit fixed it for 1.37.3rc4 or 1.37.3rc5  (https://github.com/uBlockOrigin/uBlock-issues/issues/1732#issuecomment-927088249).

**Comment by gorhill** [comment] 2021-09-25 12:31
> Are you talking about the commit uBlock-user mentioned?

Yes. Unselect all filter lists, then add the following to _"My filters"_:

    ||example.com^$~xhr

1.38.1b1: 1 filter
1.37.3rc5: 10 filters

Be sure to restart uBO when you switch between versions.

**Comment by felix-22** [comment] 2021-09-25 13:26
Indeed it says now 10 in 1.37.3rc5.  I don't know whether previously something didn't work as expected, or I overlooked / confused the versions, or it could be a typo as well like `||msn.com^$script` (missing `~`) or `||msn.com^~script` (missing `$`) which both shows 1.

**Comment by felix-22** [comment] 2021-09-25 13:54
It is expected now in 1.38.1b1 that each of these counts as 1:
`||msn.com^$~image`
`||msn.com^$~image,~xhr`

**Comment by gorhill** [comment] 2021-09-25 13:56
Yes.

I think further comments about this are best dealt in [a discussion](https://github.com/uBlockOrigin/uBlock-issues/discussions), the issue here is fixed and we are veering off topic.

**Comment by uBlock-user** [comment] 2021-12-10 18:40
> Seems $important filters are counted as 2 now ?

fixed in https://github.com/gorhill/uBlock/commit/54074af029e7e7f3d40e22feccebee2e4d20170e
