### ISSUE TITLE
Using 24+Gb of virtual memory on Firefox/Ubuntu 20.04

### ISSUE THREAD

**Issue by acostaja** [uBlockOrigin/uBlock-issues#1532] opened 2021-03-20 01:26 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by acostaja** [comment] 2021-03-20 01:28
using 24GB of virtual ram, if not an issue its an horrific code

**Comment by uBlock-user** [comment] 2021-03-20 09:24
Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/devtools/docs/profiles) + fully substantiated analysis supporting the claim.

**Closed by uBlock-user** 2021-03-20 09:24 UTC

**Comment by gorhill** [comment] 2021-03-20 11:58
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/994#issuecomment-621149918>.

Virtual memory usage is not physical memory usage, it's just **addressable space** reserved by an application. Typically on a 64-bit OS, you will have something around 256 TB (Terabytes) of addressable virtual memory, so 26 GB / 256 TB = 0.01%.

It's just a side effect of uBO using WASM modules, and is **completely inconsequential**.

If for completely irrational reasons this virtual memory figure still bothers you, you can set [advanced setting `disableWebAssembly`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#disablewebassembly) to `true`, at the cost of rendering uBO less performant.
