### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT when first time launch Chrome

### ISSUE THREAD

**Issue by Rupthya** [uBlockOrigin/uBlock-issues#1016] opened 2020-05-10 02:01 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Getting the "ERR_BLOCKED_BY_CLIENT" error on every tab when launch Chrome first time. A minute later all tabs come back to normal, having the problem like two weeks ago,

There is a same issue report at Google Community also:
https://support.google.com/chrome/thread/41771835

Starting get the issue i aware that there is a massive Chrome error reported by users at the same time:
https://www.forbes.com/sites/gordonkelly/2020/04/30/google-chrome-crash-problem-upgrade-warning-update-chrome-browser/#4c5c0cd75190

### A specific URL where the issue occurs

Nil

### Steps to Reproduce

1. Start Computer and launch Chrome
2. Every exist tabs or new tab would not loading and get "ERR_BLOCKED_BY_CLIENT" error.

### Expected behavior:

Loading Tabs correctly.

### Actual behavior:

Getting "ERR_BLOCKED_BY_CLIENT" error.

### Your environment

* uBlock Origin version:1.26.0
* Browser Name and version: Google Chrome 81.0.4044.138
* Operating System and version: Windows 10 1803 17134.137

### Additional context

i. Disable all extensions except uBlock Origin the issus is gone, 
ii. Enable all extensions except uBlock Origin the issus is gone,

I guessing some extensions / scripts conflict with uBlock Origin, but sorry its hard to rule out which them cause the problem by myself due to my active extensions is over 70...

**Comment by uBlock-user** [comment] 2020-05-10 03:42
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1004

**Closed by uBlock-user** 2020-05-10 03:42 UTC

**Comment by gorhill** [comment] 2020-05-10 11:19
Can you try the [latest dev build](https://github.com/gorhill/uBlock/releases) and see if this fixes the issue?

**Comment by Rupthya** [comment] 2020-05-12 06:43
> Can you try the [latest dev build](https://github.com/gorhill/uBlock/releases) and see if this fixes the issue?

Thanks for quick response,
test with uBlock Origin development build 1.26.3.104 at same environment and same condition, problem solved.
