### ISSUE TITLE
uBO Macbook UI/UX issue

### ISSUE THREAD

**Issue by yoggybernardo** [uBlockOrigin/uBlock-issues#762] opened 2019-10-24 07:00 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Wrong wording for Macbook users when disabling on specific website. Instead of control-click its command-click

### A specific URL where the issue occurs

google.com

### Steps to Reproduce

1. Hover over power icon
2. Says control-click to disable on specific website but it's actually command-click

### Expected behavior:

Disable on specific website

### Actual behavior:

Opens right click menu e.g. inspect etc

### Your environment

* uBlock Origin version: uBlock Origin v1.22.4
* Browser Name and version: Google Chrome Version 77.0.3865.120
* Operating System and version: macOS Catlina 10.15

**Comment by uBlock-user** [comment] 2019-10-24 07:04
Duplicate of gorhill/uBlock#614

**Closed by uBlock-user** 2019-10-24 07:04 UTC
