### ISSUE TITLE
Fix #780 in Chromium with DNS over HTTPS

### ISSUE THREAD

**Issue by kimbo** [uBlockOrigin/uBlock-issues#924] opened 2020-03-03 13:53 UTC
I know there are a lot of things I didn't fill out below. That's mainly because I'm throwing out an idea for fixing #780 for Chromium.

As some of you may know, there's a protocol called DNS over HTTPS (DoH) that allows you to do DNS lookups from the browser. In fact, the RFC explicitly includes that as one of the purposes of DoH:

>  allowing web applications to access DNS information via existing browser APIs in a safe way consistent with Cross Origin Resource Sharing (CORS) 

https://tools.ietf.org/html/rfc8484#section-1

Just wanted to throw it out there that anyone can do a DNS lookup from basically any browser.

A buddy of mine and I are working on a JavaScript library that makes making DoH queries easy in web applications. It's very unstable and likely to change, so I don't know if I can recommend it for use as part of uBlock Origin, but it may be useful for reference if uBlock decides to use DoH - https://github.com/byu-imaal/dohjs.

One thing to consider, though, is *who* we'd be sending these DNS queries to. DoH basically bypasses the client's system DNS resolver, which I imagine may not be to the liking of some users. 

I don't know if this is a good idea. I just thought if might be useful to look into to block the people using CNAMEs to get around blocking.

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment] 2020-03-03 13:55
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/910

**Closed by uBlock-user** 2020-03-03 13:55 UTC
