### ISSUE TITLE
Add a button in the popup (advanced mode) to allow CSS like you can control scripts and images already

### ISSUE THREAD

**Issue by foobar13372** [uBlockOrigin/uBlock-issues#1000] opened 2020-04-24 17:57 UTC
One can allow Images, Script, Inline scripts, 3rd party scripts, 3rd party frames, 3rd party resources, but I am missing a setting to allow CSS (inline, same-site, 3rd party).

On some sites I'd like to allow images and CSS (but not scripts).

It would be nice if a a "red-gray-green" button (whatever they are called) in the popup in advanced mode could be added that gives controll over CSS as well.

**Comment by gwarser** [comment] 2020-04-24 18:42
Duplicate of https://github.com/gorhill/uBlock/issues/3434 ?

**Comment by gorhill** [comment] 2020-04-24 21:31
> I'd like to allow images and CSS (but not scripts).

You can accomplish this with a block rule for 3rd-party scripts.

Closing as duplicate.

**Closed by gorhill** 2020-04-24 21:31 UTC
