### ISSUE TITLE
logger ui - when you open a link from the logger ui the recorded urls are lost

### ISSUE THREAD

**Issue by Mezomix** [uBlockOrigin/uBlock-issues#154] opened 2018-08-02 17:25 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

logger ui - when you open a link from the logger ui the recorded urls are lost

### A specific URL where the issue occurs
everywhere e.g. http://wdr4.radio.de/

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. browse to any page and open the logger ui from ublock origin 
2. open any link from the logger ui in a new tab
3. switch back to the logger ui tab and now the urls are lost and the drop down shows "current tab" instead of the logged tab.

### Expected behavior:

the recorded URLS will be stored

### Actual behavior:

the recorded URLS are lost

### Your environment

* uBlock Origin version: 1.16.15b6
* Browser Name and version: Firefox 62 Beta 13
* Operating System and version: Win10 1803 build 17134.191

**Comment by Mezomix** [comment] 2018-08-02 17:26
update

**Comment by gorhill** [comment] 2018-08-02 17:28
You will have to open the links in a new tab -- the logger is a dynamically updated HTML document and when you navigate away you lose all the dynamic changes, i.e. the entries.

**Comment by Mezomix** [comment] 2018-08-02 17:32
I always open the links in a new tab .... just updated the post

**Comment by Mezomix** [comment] 2018-08-02 17:33
please try to reproduce the issue

**Comment by gorhill** [comment] 2018-08-02 17:37
If "Current tab" is selected, the logger will show you the entries for that last active tab -- if there is one found. If you want to pin the logger to a specific page, just select that page in the drop-down list.

**Comment by Mezomix** [comment] 2018-08-02 17:38
![grafik](https://user-images.githubusercontent.com/42042834/43600687-943a921a-968b-11e8-9124-5330ed81bc01.png)

**Comment by Mezomix** [comment] 2018-08-02 17:40
but this was not the behaivor of the previous versions...

**Comment by gorhill** [comment] 2018-08-02 17:41
You close the tab you opened, so from uBO's point of view there is no longer a tab with the "current" status (the logger excludes itself). Just select a new tab for which you want to see the entries or just select the specific tab you want to watch.

**Comment by gorhill** [comment] 2018-08-02 17:46
The "Current tab" option is different from the other ones: it automatically filter out entries unrelated to the currently active tab, entries in it are automatically deleted when the corresponding tab is closed.

**Comment by joey04** [comment] 2018-08-02 17:59
Sounds like it could be the same underlying problem from the logger-ui refactor I reported 2 months ago: https://github.com/uBlockOrigin/uBlock-issues/issues/54#issuecomment-397827960

(Similar bug of logged entries disappearing when the hotkey is pressed.)

**Comment by uBlock-user** [comment] 2018-08-02 18:02
by-design behaviour, if the scope is set to current tab, then recorded logs will get hidden as the current tab changes(for example navigating to a differnt url in the current tab), they're not lost though. if you go back to the original tab.

**Comment by gorhill** [comment] 2018-08-02 18:47
@joey04 not the same issue, in your case the logger document is reloaded.

Here is the entries being automatically removed with the "Current tab" -- well I am assuming OP closed the newly opened tab, because I can't reproduce the described behavior if I do not close the newly opened tab.

**Comment by gwarser** [comment] 2018-08-02 19:43
Looks like this https://github.com/uBlockOrigin/uBlock-issues/issues/56

**Comment by gorhill** [comment] 2019-04-28 15:15
Closing, I am unable to reproduce anything which is not expected. The "Current tab" entry will always show the events for the currently active tab. To avoid the "Current tab" from following the currently active tab, pick a specific tab entry in the selector.

**Closed by gorhill** 2019-04-28 15:15 UTC
