### ISSUE TITLE
Last permanent rule is marked as changed when rules are added to the bottom

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uBlock-issues#593] opened 2019-05-24 16:01 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
If dynamic rules are added to the bottom, the last permanent rule is displayed as changed. It is probably due to the absence of newline after the last rule.
![ubo](https://user-images.githubusercontent.com/8005688/58344550-af06e100-7e5e-11e9-90f3-f5708be1c76b.png)

### Your environment

* uBlock Origin version: v1.19.5b1
* Browser Name and version: 74.0.3729.169 (64-bit) 
* Operating System and version: Windows 10 v1607 x64

**Comment by uBlock-user** [comment] 2019-05-24 16:51
Provide some more details like a screenshot etc..

**Comment by gwarser** [comment] 2019-05-24 16:56
Like this?

![image](https://user-images.githubusercontent.com/886325/58344247-79a9c580-7e55-11e9-91de-8f8cd22f22d0.png)

**Comment by gorhill** [comment] 2019-05-24 17:11
This was [also reported for uMatrix](https://github.com/uBlockOrigin/uMatrix-issues/issues/106), I agreed this should be fixed.

**Comment by gorhill** [comment] 2019-05-24 17:12
Actually, I can't reproduce what occurs on uMatrix. I will need exact repro steps.

**Comment by gorhill** [comment] 2019-05-24 17:15
Actually never mind, I see the issue.

**Closed** 2019-05-25 17:09 UTC
Labels: bug, fixed
