### ISSUE TITLE
Blank window opened when clicking on link

### ISSUE THREAD

**Issue by kissaev** [uBlockOrigin/uBlock-issues#1531] opened 2021-03-18 01:41 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
When clicking on links like this, opens new blank window. Disabling uBlock for this site did'nt help, only disabling extension helps.
### A specific URL where the issue occurs
[Bug appears in url like this](https://anonymz.com/?https://gist.github.com)

### Steps to Reproduce

1. Click on [link](https://anonymz.com/?https://gist.github.com)

### Expected behavior:

[What you expected to happen]
No blank window's opened

### Actual behavior:

[What actually happened]
When clicking on links like this, opens new blank window

### Your environment

* uBlock Origin version: 1.34.0
* Browser Name and version: Microsoft Edge, Version 89.0.774.54 (Official build) (64-bit)
* Operating System and version: Windows 10 Pro, 20H2, 19042.867

**Comment by gorhill** [comment] 2021-03-18 12:00
Unable to reproduce.

Closing as invalid, unless OP provides actual evidence that this is a uBO issue and not a filter issue. No mention of the logger is a telltale case of not investigating whether this was a filter issue.

**Closed by gorhill** 2021-03-18 12:00 UTC
Labels: unable to reproduce
