### ISSUE TITLE
Starting with v1.17.5b4, static/dynamic filters can now prevent uBlock from updating its lists even with the default whitelist

### ISSUE THREAD

**Issue by FatOrangutan** [uBlockOrigin/uBlock-issues#339] opened 2018-12-14 09:02 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

See title.

### A specific URL where the issue occurs

N/A

### Steps to Reproduce

0. Ensure you have the default whitelist.
1. Add `https://raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt`. Apply changes. Let uBlock fetch the list and wait for the `n used out of n` to appear.
2. Mark the list as 'out of date.' Click 'Update now.'

### Expected behavior:

Update succeeds, as it did in v1.17.5b3.

### Actual behavior:

List is fetched after STR1 but not after STR2. Logger says blocked because of `/popads.` in Easylist, a default filter.

![capture](https://user-images.githubusercontent.com/8336638/49993573-ff733c00-ffac-11e8-879f-cbdc26c83a90.PNG)

### Your environment

* uBlock Origin version: 1.17.5b4
* Browser Name and version: Nightly, Chrome stable (both latest)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment] 2018-12-14 09:22
Tested on default settings, updated succeeds on 1.17.5b4.

**Comment by uBlock-user** [comment] 2018-12-14 09:30
After STR1, I didn't force update immediately, so it didn't happen. If I force update immediately, it does happen.

**Comment by uBlock-user** [comment] 2018-12-14 09:32
@FatOrangutan Add **cgbcahbpdhpcegmbfconppldiemgcoii** to the whitelist and tell me if you can reproduce again.

**Comment by FatOrangutan** [comment] 2018-12-14 09:33
That (and its equivalent in Firefox) fix the issue and are what I've been using on my main profiles since the update.

**Comment by uBlock-user** [comment] 2018-12-14 09:37
This change is likely because of another fix which landed in this commit - https://github.com/gorhill/uBlock/commit/9b27a98f901d415105d3256254f141a4f75e1411

**Comment by uBlock-user** [comment] 2018-12-14 09:44
@gorhill need to add extension ids to the default whitelist to avoid this.

**Comment by gorhill** [comment] 2018-12-14 11:15
I agree that there is something to fix with regard to the big commit, but I don't understand why I can't reproduce here.

**Comment by uBlock-user** [comment] 2018-12-14 11:17
It blocks when you update, but it doesn't block the request when  via Imported the list, was it like this before also ?

**Comment by gorhill** [comment] 2018-12-14 11:18
I keep marking as obsolete and the list still load fine. I need to spend more time digging.

**Comment by gorhill** [comment] 2018-12-14 11:22
Ok, "advanced user" has to be enabled, my understanding is that the issue was with default settings.

**Closed** 2018-12-14 12:03 UTC
Labels: something to address
