### ISSUE TITLE
Filter selector issues

### ISSUE THREAD

**Issue by mdziczkowski** [uBlockOrigin/uBlock-issues#894] opened 2020-02-11 13:07 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ x ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x ] I am running the latest version of uBlock Origin
- [ x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There are following issues with rules selector:

* not working collapse/expand
* no possibility to manage the elements of any rule (there aren't all elements of the rule used and there is no possibility to moddify it)

### A specific URL where the issue occurs

n/a - it happens in the addon's config

### Steps to Reproduce

1. install the addon on mobile with same OS
2. try to configure build in filters:
a) try to collapse / expand categories
b) try to cause that all parts of the rule are used and not only some of them

### Expected behavior:
* collapse / expand of filters should work correctly
* each filter should be able to be expanded / collapsed
* each element of each filter should be selectable / unselectable

### Actual behavior:

* collapse / expand isn't working
* uin each rule I'm unable to select the part's with should be used or not

### Your environment

* uBlock Origin version: latest
* Browser Name and version: Firefox (latest avaliable for this OS)
* Operating System and version: Android 4.4.2 (not rooted)

**Comment by mdziczkowski** [comment] 2020-02-11 13:10
Prerequisites select

**Comment by gorhill** [comment] 2020-02-11 13:14
I don't understand what is being reported.

**Comment by mdziczkowski** [comment] 2020-02-11 13:16
In the build-in filters configuration the interface is mailfunctioning

**Comment by gorhill** [comment] 2020-02-11 13:17
"malfunctioning" is vague -- this does not help.

**Comment by gorhill** [comment] 2020-02-11 13:19
> collapse / expand of filters should work correctly

I can collpase/expand, so this one is unreproducible on my side.

> each filter should be able to be expanded / collapsed
> each element of each filter should be selectable / unselectable

I don't understand this one -- I can check/uncheck fine and apply changes.

**Comment by mdziczkowski** [comment] 2020-02-11 13:32
let me try to explain it to you. The report concerns the configuration of the build-in filters. I had found there following issues:

1. not working collapse/expand
2. there is no possibility to configure any of the rule, that all it's sub-rules are used (for example, in one are used only 5667 of 16695 sub-rules)

**Comment by gorhill** [comment] 2020-02-11 13:35
> not working collapse/expand

Unable to reproduce. If you mean collapsing checked lists, then by design, only un-checked lists are collapsed.

> in one are used only 5667 of 16695 sub-rules

By design uBO discards duplicate filters.

So by design, closing as invalid.

**Comment by gorhill** [comment] 2020-02-11 13:36
If you it's closed in error then provide more detailed information along with annotated screenshots to explain what you think is the issue.

**Closed by gorhill** 2020-02-11 13:35 UTC
Labels: Firefox-Android, something to address
