### ISSUE TITLE
Child divs cannot be 'picked'

### ISSUE THREAD

**Issue by btdmaster** [uBlockOrigin/uBlock-issues#1151] opened 2020-07-13 15:20 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Using the element picker/zapper I cannot select divs that are children of other elements. This could apply to other elements and not strictly divs however I have not done testing on this.

### A specific URL where the issue occurs

https://codepen.io/btdmaster50/pen/LYGQZxq

### Steps to Reproduce

1. Use the Inspector (F12) to find the element to block
2. Attempt to select said element with the element picker or zapper
3. Find that only its parent can be selected, which is less than optimal.

### Expected behavior:

Be able to select the div to be blocked. https://i.imgur.com/2jDRSjL.png

### Actual behavior:

Only able to select the entire body. https://i.imgur.com/XqMRWz7.png

### Your environment

* uBlock Origin version: 1.28.0
* Browser Name and version: Firefox 78.0.1
* Operating System and version: Ubuntu 20.04

**Comment by gorhill** [comment] 2020-07-13 15:24
Duplicate of <https://github.com/gorhill/uBlock/issues/1744>. The element picker is currently not able to work inside frames, only on the top-level document.

Workaround in Firefox: right-click the frame and select _"ThisFrame"_ => _"Show Only This Frame"_, then use the element picker.

**Closed by gorhill** 2020-07-13 15:24 UTC
Labels: duplicate

**Comment by felix-22** [comment] 2021-11-10 11:22
- I see Picker fixed in:
  - https://github.com/gorhill/uBlock/issues/1744
  - https://github.com/gorhill/uBlock/commit/db7f54dbf6c39cf2e6f35359248bf9f408e2d134
- but Zapper still not fixed as pointed out here: 
  - https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-964878717

![dede](https://user-images.githubusercontent.com/75935068/141104277-9d9a5226-44e4-44b4-a48a-5f9b9dd2b0b4.gif)
