### ISSUE TITLE
Updated from 1.26.0 to 1.27.10, Dashboard/Panel Error in Chrome

### ISSUE THREAD

**Issue by john7200** [uBlockOrigin/uBlock-issues#1115] opened 2020-06-19 09:41 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I updated uBlock Origin 1.26.0 to 1.27.10, now the dashboard/panel produces error ERR_FILE_NOT_FOUND whenever I click the uBlock Origin icon (normally it should open uBO dashboard/panel). The only thing I noticed is the new font/design in the option. I do not know if uBO is still working (blocking ads, etc.). uBO icon is red (not grayed out) when browsing. Disabling and enabling uBO did not help. I really regret updating. I should have never updated uBO...

### A specific URL where the issue occurs

No specific URL, this is about uBlock Origin dashboard/panel.

### Steps to Reproduce

1. Updated uBlock Origin from 1.26.0 to 1.27.10
2. Click uBlock Origin to open the dashboard/panel.
3. Error message shows up.

### Expected behavior:

uBlock Origin dashboard/panel opens when uBlock Origin icon is clicked.

Example here was from Firefox. My uBO in Chrome is now broken (dashboard does not show up).

![ublockorigin_dashboard_firefox](https://user-images.githubusercontent.com/47649262/85118848-d398dc80-b25b-11ea-8b32-e92b13ab4f40.png)

### Actual behavior:

Error message shows up instead.

![ublockorigin_dashboard](https://user-images.githubusercontent.com/47649262/85118270-15755300-b25b-11ea-957e-70613f9dd967.png)

Update: Uninstalling and reinstalling uBO does not solve the issue. Dashboard/panel is still showing error message after reinstalling uBO.

### Your environment

* uBlock Origin version: 1.27.10
* Chrome 63.0.3239.132 64-bit
* Windows 8.1 Pro

**Comment by uBlock-user** [comment] 2020-06-19 09:57
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1085

**Closed by uBlock-user** 2020-06-19 09:57 UTC
