### ISSUE TITLE
Can't disable "advanced user" mode

### ISSUE THREAD

**Issue by IPv777** [uBlockOrigin/uBlock-issues#970] opened 2020-03-31 10:29 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I can't disable the Advanced User mode.

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. Check (enable) the "Advanced User" mode
![image](https://user-images.githubusercontent.com/19636346/78016082-9e5eab80-734a-11ea-9e21-47a7a82e3cd3.png)

2. The rights grid will show up
![image](https://user-images.githubusercontent.com/19636346/78016182-bfbf9780-734a-11ea-8b24-d22d76461f43.png)

3. Uncheck the "Advanced User" mode
![image](https://user-images.githubusercontent.com/19636346/78016253-d82fb200-734a-11ea-81be-df10e7a57bbf.png)

### Expected behavior:

The rights grid must go away

### Actual behavior:

The rights grid is still here, even after a restart of Firefox.

### Your environment

* uBlock Origin version: v1.25.2
* Browser Name and version: Mozilla Firefox 74
* Operating System and version: Windows 10

Have a good day :)

**Comment by IPv777** [comment] 2020-03-31 10:31
Update : the bug is present also in Google Chrome

**Comment by uBlock-user** [comment] 2020-03-31 10:35
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/125

**Closed by uBlock-user** 2020-03-31 10:35 UTC
