### ISSUE TITLE
$removeparam doesn't work well with UrlEncoded gb2312 Chinese word

### ISSUE THREAD

**Issue by MkQtS** [uBlockOrigin/uBlock-issues#1717] opened 2021-09-12 15:07 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The url is `https://www.baidu.com/s?wd=%D6%D0%CE%C4&oq=test`, `%D6%D0%CE%C4` is actually a UrlEncoded form of a Chinese word `中文` which encoding with **gb2312**. ![Before using the fliter](https://z3.ax1x.com/2021/09/12/49BxYR.png)

After I add a fliter like this: `||baidu.com/s^$removeparam=oq`, the url became `https://www.baidu.com/s?wd=%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD`, which makes no sense. ![After using the fliter](https://z3.ax1x.com/2021/09/12/49DATH.png)

However, It works well for `https://www.baidu.com/s?wd=%E4%B8%AD%E6%96%87&oq=test`, `%E4%B8%AD%E6%96%87` is also a UrlEncoded form of a Chinese word `中文` encoding with **UTF-8**. After using the fliter, the url became `https://www.baidu.com/s?wd=%E4%B8%AD%E6%96%87`.

I am not sure if it's related to system or browser. When I exactly type `https://www.baidu.com/s?wd=%E4%B8%AD%E6%96%87&oq=test`, the Omnibox would just show `https://www.baidu.com/s?wd=中文&oq=test`. When I type `https://www.baidu.com/s?wd=%D6%D0%CE%C4&oq=test`, the Omnibox would also show `https://www.baidu.com/s?wd=%D6%D0%CE%C4&oq=test`

### A specific URL where the issue occurs

https://www.baidu.com/s?wd=%D6%D0%CE%C4&oq=test

### Steps to Reproduce

1.Open `https://www.baidu.com/s?wd=%D6%D0%CE%C4&oq=test`
2.Add a fliter: `||baidu.com/s^$removeparam=oq`
3.Refresh

### Expected behavior

The url becomes `https://www.baidu.com/s?wd=%D6%D0%CE%C4`

### Actual behavior

The url became `https://www.baidu.com/s?wd=%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD`

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 93.0.4577.63

### Operating System and version

Windows 10, 21H1

**Comment by gorhill** [comment] 2021-09-12 15:17
I can reproduce. It seems the issue is when parsing the query parameters using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams) -- this is surprising, I would expect this API to properly handle encoded query values.

**Comment by gorhill** [comment] 2021-09-12 16:41
Fix is in 1.37.3rc2, but rc1 dev build in Chrome store is pending review, so I don't know when rc2 will be available in Chrome store.

**Closed** 2021-09-12 19:02 UTC
Labels: bug, fixed

**Comment by gwarser** [comment] 2021-09-13 09:15
@MkQtS from where did you originally get this gb2312-encoded "中文"?

**Comment by vtriolet** [comment] 2021-09-13 12:06
It looks like a similar `URLSearchParams` issue will cause encoded parameter values to be displayed incorrectly on the strict-blocking page:

https://github.com/gorhill/uBlock/blob/89064478dda8c32b467e95cbd7dfbd3f8ecdde07/src/js/document-blocked.js#L155-L164

![ubo_encoded_params_strict_blocking](https://user-images.githubusercontent.com/85783377/133079466-92f7adda-38bd-4bc8-bd49-8a9349a38340.png)
-- Screenshot from 1.37.3rc2

(I'm not sure if the protocol is to file a new ticket, but I thought I'd at least mention it here first for confirmation.)

**Comment by gorhill** [comment] 2021-09-13 13:13
The document-blocked page does not use URLSearchParams(), but rather URL(). I am pretty sure this is a site issue since it appears it custom-encode some parts of the URL which should be encoded using encodeURIComponent(), but uBO will have to be ready for invalid decodeURIComponent().

**Comment by gorhill** [comment] 2021-09-13 13:13
I am pretty sure this is a site issue since it appears it custom-encode some parts of the URL which should be encoded using encodeURIComponent(), but uBO will have to be ready for invalid decodeURIComponent().

**Comment by gwarser** [comment] 2021-09-13 20:11
@MkQtS I ask because I tried various ways and I always get correct utf-8 encoding. There is even `ie=utf-8` parameter in search URL.
