### ISSUE TITLE
Simplify user interface facilitating preset modes (hard - medium - easy - very easy)

### ISSUE THREAD

**Issue by Kees1958** [uBlockOrigin/uBlock-issues#1493] opened 2021-02-09 07:39 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Feature request: simplify user interface

As a retired sales and former system designer (specialist in usability), an other enhancement request triggered me to suggest a simplification (because I checked the Wiki). In the Wiki of uBlock the different modes are explained in detail (hard - medium - easy and very easy). 

Looking at the GUI I noticed something awkward: these modes are not part of the user interface. When talking about (content filtering) modes is the way to explain the functionality of uBlockOrigin, why not make things easy and straight forward and use these modes in the GUI?

I value the detailed insights uBO provides in advanced mode, so this enhancement request is not a suggestion to replace it.  I would like this enhancement as an option in the flexible GUI. That is why I used the existing less/more user interface to visualize what I propose

### A specific URL where the issue occurs

not relevant, but here you go used github as an example: github.com

### Steps to Reproduce

Picture below 
left - current simple gui 
middle - protection mode applicable as default (for all)
right - overwrite default for current webiste (and all subdomains)

### Expected behavior:
Add a slider for protection mode and an optional select box to overwrite the mode for a specific website.

![image](https://user-images.githubusercontent.com/30925856/107330619-1bea6080-6ab2-11eb-8dde-64023b0515bc.png)

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by Kees1958** [comment] 2021-02-09 07:50
@gorhill in hard mode I would like to allow CSS also by default (like images) :-)

**Comment by uBlock-user** [comment] 2021-02-09 08:44
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1019

**Closed by uBlock-user** 2021-02-09 08:44 UTC

**Comment by LennyFox** [comment] 2021-02-09 10:26
I think it looks good, great simplification, pity this request is rejected. @Kees1958 has got a point, the wiki is all about blocking modes, but they are not present in the GUI

**Comment by gorhill** [comment] 2021-02-09 13:06
> Pity it is rejected without discussing the merits

Issue #1019 is not rejected, is still opened.

**Comment by uBlock-user** [comment] 2021-02-09 13:20
@LennyFox Duplicates are ALWAYS closed, read before you jump to invalid conclusions.
