### ISSUE TITLE
Scriptlet doesn't work

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uBlock-issues#2343] opened 2022-10-28 06:36 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [ ] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [ ] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [ ] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

scriptlet doesn't work
[Gif](https://imgur.com/KncMPoJ)
```adb
root-nation.com##+js(set-constant, td_ad_background_click_link, undefined)
root-nation.com##+js(abort-on-property-read, td_ad_background_click_target)
```
<details>

```yaml
uBlock Origin: 1.44.5b19
Firefox: 106
filterset (summary): 
  network: 100049
  cosmetic: 125758
  scriptlet: 23876
  html: 831
listset (total-discarded, last-updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31522-61, 6m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1545-0, 6m
    fanboy-cookiemonster: 42166-304, 6m
    ublock-annoyances: 4733-4, 6m
    RUS-0: 40428-261, 6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32956-105, 6m
    ublock-badware: 3942-0, 6m
    ublock-privacy: 288-0, 6m
    ublock-abuse: 76-0, 6m
    ublock-unbreak: 1886-8, 6m
    ublock-quick-fixes: 418-0, 6m
    easylist: 62398-337, 6m
    easyprivacy: 30816-1484, 6m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 451 ms (selfie)
  maxAssetCacheWait: 171 ms
```
</details>

The stable version doesn't have this problem.

### A specific URL where the issue occurs.

`https://root-nation.com/ua/`

### Steps to Reproduce

Click on the background

### Expected behavior

Background is not clickable

### Actual behavior

Background clickable

### uBO version

1.44.5b19

### Browser name and version

Firefox 106.0.2

### Operating System and version

Windows 10 22H2 x64

**Comment by gwarser** [comment] 2022-10-28 08:20
`td_ad_background_click_link` is undefined even before being filtered, `td_ad_background_click_target` throws with the filter.

**Comment by dportvine** [comment] 2022-10-28 08:48
@gwarser 
1.44.5b19 vs 1.44.4
[Gif](https://imgur.com/Z6pE6VA)

**Comment by garry-ut99** [comment] 2022-10-28 13:21
I can reproduce only in `1.44.5b19`, can't in `1.44.5b17` and any lower versions.

**Comment by gorhill** [comment] 2022-10-28 14:12
Looks like the scriptlet injection is more racy in b19 than in b17.

**Comment by gorhill** [comment] 2022-10-28 14:19
Yesterday I committed another change after I published b19, and with that change it seems I can't reproduce the issue. So lets see if the issue is still there with b20.

**Comment by dportvine** [comment] 2022-10-28 14:33
I have no problem with version 1.44.5b20.

**Comment by dportvine** [comment] 2022-10-28 14:37
No, it didn't help 😞
[Gif](https://imgur.com/oaYnxHF)

**Comment by gorhill** [comment] 2022-10-28 14:48
Once I enable RUS list, I can reproduce.

**Comment by gorhill** [comment] 2022-10-28 15:11
In b21 I restore the original behavior of not injecting scriptlets on navigation events, while this should still fix <https://www.reddit.com/r/uBlockOrigin/comments/ye6abt/ublock_origin_not_blocking_ads_in_the_sidebar_of/>.

**Comment by dportvine** [comment] 2022-10-28 18:56
I have no problem in version 1.44.5b21.

**Comment by vlaszlo** [comment] 2022-10-28 18:58
spiegel.de works again now, too.

**Closed** 2022-10-29 05:51 UTC

**Comment by gorhill** [comment] 2022-11-06 22:10
As part of the fix to <https://github.com/uBlockOrigin/uBlock-issues/issues/2350>, I restored the change I reverted above. It turns out going through that code made me realize there was [a flaw in how I detected whether the scriptlets had been injected or not](https://github.com/gorhill/uBlock/commit/49df063191496f5118e381acf7b2962386857f99#diff-91b364713e60c5b5cbb694ed5deabcefba6c2375e759336bc9c45ba46154ad99L99), which I [fixed](https://github.com/gorhill/uBlock/commit/49df063191496f5118e381acf7b2962386857f99#diff-91b364713e60c5b5cbb694ed5deabcefba6c2375e759336bc9c45ba46154ad99R107) at the same time I fixed #2350. Though I verified that the cases here still appear fixed, please just confirm it still is the case with 1.44.5rc3.

**Comment by vlaszlo** [comment] 2022-11-06 22:32
I'm not seeing ads on spiegel.de, so it's still seems fixed from here, too.

**Comment by dportvine** [comment] 2022-11-07 06:35
Everything works for me in version 1.44.5rc4
