### ISSUE TITLE
reverse proxified woes

### ISSUE THREAD

**Issue by slowfar** [uBlockOrigin/uBlock-issues#443] opened 2019-03-01 12:20 UTC
PoC demonstrating uBlock Origin circumvention for google tagmanager & analytics.  

https://news.ycombinator.com/item?id=19252358

via https://github.com/cowlicks/privacypossum/issues/159

**Comment by gwarser** [comment] 2019-03-01 12:28
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/441

**Closed by gwarser** 2019-03-01 12:28 UTC
