### ISSUE TITLE
Default filter lists unselected internally (i.e. not unselected by user)

### ISSUE THREAD

**Issue by parkerjeremy44** [uBlockOrigin/uBlock-issues#2604] opened 2023-04-21 22:42 UTC
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://old.reddit.com/`

### Category

ads

### Description

Ads are showing up now when they didn't before

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.0
Chromium: 112
filterset (summary): 
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated): [none]
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 68 redacted]
 removed: 
  edge-scheme
  wyciwyg-scheme
switchRuleset: 
 added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 621 ms (selfie)
 maxAssetCacheWait: 4 ms
popupPanel: 
 blocked: 0
```
</details>

**Comment by gorhill** [comment] 2023-04-22 00:39
There has been a bit too many reports of all filter lists being unselected for my taste.

It does seem something is going on, but whatever it is, it's probably very difficult to reproduce.

A new code path was added in 1.49.0 in order to unselect default lists which are no longer default when `assets.json` updates, but reading carefully through the code, I can't see how this could happen.

In any case, I've added more checks for unexpected conditions when `assets.json` updates, such that uBO will skip checking which default lists should be disabled when uBO detects one of those abnormal conditions: <https://github.com/gorhill/uBlock/commit/6294829e68b2f6eb2afe133205a36cbc8bb529ed>

It's a shot in the dark, but given the severity of all lists being unselected, I will give it a try and publish an emergency release for this change.

**Comment by gorhill** [comment] 2023-04-22 00:44
Cases beside the one reported here:

- https://github.com/uBlockOrigin/uAssets/issues/17701

**Comment by stephenhawk8054** [comment] 2023-04-22 02:05
Can browser update affects extension's storage? The day the reports began to show, 2 of my chromium browsers (vanilla chromium and brave) started to update new version too.

**Comment by gorhill** [comment] 2023-04-22 02:12
I can't tell really. That's the problem with those reports of broken uBO, it's quite rare given the user base, and when it's reported there is not much to work with, for example: <https://github.com/uBlockOrigin/uBlock-issues/issues/2341>.

**Comment by stephenhawk8054** [comment] 2023-04-22 02:19
So if I understand correctly, https://github.com/gorhill/uBlock/commit/6294829e68b2f6eb2afe133205a36cbc8bb529ed is for checking if default lists being turned off when launching? Can uBO auto force update in that case?

**Comment by gorhill** [comment] 2023-04-22 02:32
That code is executed only when `assets.json` updates. It was originally added in [this commit](https://github.com/gorhill/uBlock/commit/2cd062898c0f6007ea9b44b36472c210baa1b0e4#diff-bb0a23b7c8c08b99549300d4571ee50f0fcbb877eb8b84fb2d4c4c3ec1ffc1c4R1608).

**Comment by ghajini** [comment] 2023-04-22 06:21
sorry if iam making.noise
isn't this same as https://github.com/uBlockOrigin/uBlock-issues/issues/2136 except different browser ...

also **_user selected settings are also lost_**

eg i enabled these, but they are lost when this happens

```
ignore generic cosmetic filters
block csp reports
iam an advanced user
```

**Comment by Wouter0100** [comment] 2023-04-22 12:28
I've had another case myself, all of a sudden started w/o any changes. Purge all caches + update now + apply changes fixed it.

**Comment by gorhill** [comment] 2023-04-22 13:43
I am having a real hard time to find out what could cause the reported symptoms.

So far I have perfectly mimicked the reported symptoms by manually replacing the content of `assets.json` with only `{}`. Of course, no remote servers should ever return `{}` when fetching `assets.json`.

**Comment by gorhill** [comment] 2023-04-22 14:55
I might have found the most likely explanation for the reported cases. It would have to do with corrupted storage, hence why it's rare. When I mimick corrupted storage to find out what uBO ends up doing, I do get zero filter lists loaded, and troubleshooting information looks like (I removed unimportant entries):

```
uBlock Origin: 1.49.1b1
Chromium: 112
filterset (summary): 
 network: 0
 cosmetic: 0
 scriptlet: 0
 html: 0
listset (total-discarded, last-updated): [none]
supportStats: 
 allReadyAfter: 115 ms
 maxAssetCacheWait: 4 ms
```

Especially, the section `listset` for reported cases is atypical, as it does not show that default lists were removed, which would be the case if the default lists were unselected.

The storage-reading code in uBO is ready to deal with not receiving the fetched items from storage, the issue is that uBO was not dealing with Promise rejection, which would cause the code paths dealing with failure to fetch items from storage to not be taken.

**Comment by u-RraaLL** [comment] 2023-04-22 17:20
How feasible would it be to add a check for unselected (or not loaded at all) default filter lists in uBO's report widget that would advise users to purge and update lists before they proceed? And perhaps do the same with lists that haven't been updated in a while?

This could potentially reach a bigger percentage of uBO's userbase than the ones that have/are willing to make a github account.

**Comment by gorhill** [comment] 2023-04-22 17:24
Being discussed: <https://github.com/uBlockOrigin/uBlock-issues/discussions/2582>

**Comment by parkerjeremy44** [comment] 2023-04-23 16:41
> You have no filter lists enabled:
> 
> * Restart the browser
> 
> Go to _Filter lists_ pane. If it shows there are no filter lists enabled:
> 
> * Click _Purge all caches_
> * Click _Update now_
> 
> If there are still no filter lists enabled, remove then reinstall uBO.


**This worked! Thanks for your help.**

**Comment by gorhill** [comment] 2023-04-23 17:37
> This worked! Thanks for your help.

Please report here if it ever happens again -- currently I suspect just to people who had either uBO or their browser udpated. I would like to know if this also happens when neither the browser or uBO updates to a new version.

**Comment by peace2000** [comment] 2023-04-24 20:18
New case: https://github.com/uBlockOrigin/uAssets/issues/17770 (Don't know if the log the user provided gives useful troubleshooting info, but linking just in case.

**Comment by gorhill** [comment] 2023-04-25 16:15
It's possible to use uBO without filter lists, that would be bad for people using uBO this way to have lists always unilaterally re-enabled.

Best is to get to the bottom of the issue and fix it.

**Comment by mapx-** [comment] 2023-04-25 16:33
yes but you can test if there are no dynamic rules

**Comment by stephenhawk8054** [comment] 2023-04-26 04:42
> When I mimick corrupted storage to find out what uBO ends up doing, I do get zero filter lists loaded

Could you reproduce the same symptom with older main releases (1.48, 1.47, 1.46 ... ), so we might know when it started to have this issue or it has been always there?

I remember we didn't have this many reports when previous versions updated.

**Comment by gorhill** [comment] 2023-04-26 11:46
I could not really reproduce the exact same symptoms. What I reproduced left uBO in a broken state, where I could not do what most people are doing. i.e. purge and update all filter lists. The _Filter lists_ pane was completely broken for me.

I looked into the reports quite a lot and they all share two key details: they all report that uBO was loaded from a selfie. I didn't reproduce this. The other one is that they all report that the internal variables which contains all the available filter lists is seemingly empty, not even user filter list is being reported.

When I look at the code, these two things can't happen.

The only explanation I see where this can happen, is that a selfie was created before uBO reached the point where it loads filter lists in launch sequence, and of course this is not supposed to happen.

Again, the only explanation I see for this to happen is that for selfie purpose, uBO started to use `browser.alarms` API in 1.49.0, and I suspect the API does not behave in ways I expect it to behave, i.e. I suspect that sometimes there is an alarm event fired when uBO is launched -- possibly from a an alarm event that was pending when uBO was exited the previous time. This would cause uBO to create a selfie while no filters are in memory and the available filter lists (including _My filters_ list) have not yet been scanned.

For now I will get rid of `alarms` API usage.

**Comment by garry-ut99** [comment] 2023-04-27 09:02
> [bugs.chromium.org/p/chromium/issues/detail?id=958809](https://bugs.chromium.org/p/chromium/issues/detail?id=958809)
> [alarms fires erratically sometimes](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/0i8hjjXr-JM) >>  https://bugs.chromium.org/p/chromium/issues/detail?id=1368619

Also other bugs in Alarms (which might be related or not):
https://bugs.chromium.org/p/chromium/issues/detail?id=1285798
https://bugs.chromium.org/p/chromium/issues/detail?id=1321331
https://bugs.chromium.org/p/chromium/issues/detail?id=1368619
https://bugzilla.mozilla.org/show_bug.cgi?id=1359403

**Comment by gorhill** [comment] 2023-04-28 15:12
Similar reports are no longer showing up, and none of the last ones were for 1.49.2, so this probably confirm usage of `browser.alarms` was at the root of the issue. Closing, I will re-open if new reports for 1.49.2 with the same troubleshooting information signature are showing up.

**Closed by gorhill** 2023-04-28 15:12 UTC

**Comment by xvello** [comment] 2023-05-16 20:18
Heya @gorhill, I'm wondering whether the fix for this issue could have created a regression for custom lists not being refreshed anymore. I see a significant drop in usage since the release of 1.49.2. I don't have enough telemetry to confirm that the drop is really uBO users, but the timing looks pretty suspicious.

I wrote more context in https://github.com/uBlockOrigin/uBlock-issues/discussions/2659

**Comment by gwarser** [comment] 2023-05-17 05:32
If people wander here searching for solution to custom list being disabled in 1.49.2 - https://github.com/gorhill/uBlock/commit/1a9a8aae0c8969dad9743e31dd465c8892b89f32
