### ISSUE TITLE
"Block element" interface can block view.

### ISSUE THREAD

**Issue by MarjaE2** [uBlockOrigin/uBlock-issues#1714] opened 2021-09-10 21:59 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [] uBO is the only extension
- [] uBO with default lists/settings
- [] using a new, unmodified browser profile

### Description

Since the "Block Element" interface opens in lower right corner, it's not well-equipped to block position:sticky elements which stick to that corner.

### A specific URL where the issue occurs

https://www.usatoday.com/story/news/politics/elections/2020/08/06/election-2020-war-games-trump-vs-biden-race-show-risk-chaos/5526553002/

### Steps to Reproduce

1. Open https://www.usatoday.com/story/news/politics/elections/2020/08/06/election-2020-war-games-trump-vs-biden-race-show-risk-chaos/5526553002/
2. Scroll or page down.
3. Try to use "block element" in the context menu to block the position:sticky video element in that corner.

Migraine warning for position: sticky, and for the video if you haven't blocked all autoplay.

### Expected behavior

The "block element" interface shouldn't block the view of the entire element it's blocking, because that makes it hard to block all the problem elements and none of the others.

### Actual behavior

The "block element" interface blocks the view.

Note: I was not able to test with a new unmodified user profile, as required above, because smooth scrolling, autoplaying videos, and news videos, which often contain strobe lights and scrolling text, all give me awful migraines.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Operating System and version

MacOS 10.14.6

**Comment by uBlock-user** [comment] 2021-09-10 22:04
> The "block element" interface blocks the view.

You could just pick the picker and move it to another place on the screen to un-block the view.

**Comment by uBlock-user** [comment] 2021-09-10 22:06
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/615

**Closed by uBlock-user** 2021-09-10 22:06 UTC

**Comment by gorhill** [comment] 2021-09-11 13:39
Labelling as _invalid_ since [the documentation properly mentions](https://github.com/uBlockOrigin/uBlock-issues/wiki/Element-picker) how to deal with this:

> **Tip:**
> 
> You can easily move element picker dialog using mouse, by grabbing and dragging by empty space between buttons

> - [x] I checked the documentation to understand that the issue I report is not a normal behavior

Many cases of people not truthfully checking the boxes lately, so I am entertaining closing the issue tracker to non-collaborator to avoid all these invalid issues which are wasting our time.

**Comment by felix-22** [comment] 2021-09-11 14:38
Yeah, they are almost unstoppable: https://github.com/reek/anti-adblock-killer/issues/4179#issuecomment-712672647

**Comment by uBlock-user** [comment] 2021-09-11 17:39
> so I am entertaining closing the issue tracker to non-collaborator to avoid all these invalid issues which are wasting our time.

GitHub now offers Discussions feature, so you could do this while enabling that feature.
