### ISSUE TITLE
`allow` dynamic filter rule aren't override existing rules

### ISSUE THREAD

**Issue by calendulish** [uBlockOrigin/uBlock-issues#2702] opened 2023-06-26 06:54 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`allow` dynamic filter rule should override existing rules, but when `no-remote-fonts: * true` is present the behavior isn't what expected.

```
* https://fontsite.com/font font allow < work as expected, allowing the font
* https://fontsite.com/font * allow < still blocking
* fontsite.com * allow < still blocking
```

I know that I could allow font sources through static filters, but the problem is with the consistency of dynamic filters behavior. If I use `*` and `allow` I expect everything to be allowed as described in the documentation.

> allow: matching network request will be allowed.
>     allow dynamic filters rules override any existing static and dynamic block filters.

### A specific URL where the issue occurs.

https://www.indiegala.com

### Steps to Reproduce

1. block remote fonts with `no-remote-fonts: * true`
2. see some fonts are blocked, e.g.: `https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0`
3. try to allow this font with `* htpps://maxcdn.bootstrapcdn.com/font-awesome/ * allow`
4. see on log the rule has applied to the css but not to the font
5. try to change the rule to `* htpps://maxcdn.bootstrapcdn.com/font-awesome/ font allow`
6. now it works... but `*` should not include fonts?!

### Expected behavior

`allow` rule should override any existing static and dynamic block filters

### Actual behavior

`allow` isn't overriding some rules when used with `*` instead of a specific type

### uBO version

1.50.0

### Browser name and version

LibreWolf 114.0.1-2

### Operating System and version

Windows 11

**Comment by gorhill** [comment] 2023-06-26 12:41
Duplicate of <https://github.com/gorhill/uBlock/issues/363>.

**Closed by gorhill** 2023-06-26 12:41 UTC
Labels: duplicate
