### ISSUE TITLE
uBlock Origin Browser Error Page: "This page has been blocked by an extension"

### ISSUE THREAD

**Issue by DesertBear** [uBlockOrigin/uBlock-issues#2063] opened 2022-03-22 18:34 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

I closed and reopened the web browser (probably within about 5 seconds) and instead of loading a webpage it showed the below error page instead.

**Address bar:**
```
extension://odfafepnkmbhccpbejgmiehpchacaeak/web_accessible_resources/empty?secret=is1p3u
```

**Page body:**
```
odfafepnkmbhccpbejgmiehpchacaeak is blocked
This page has been blocked by an extension
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT
```

**Screenshot:**
![Screenshot](https://user-images.githubusercontent.com/27423064/159548018-1666772f-6e4b-4593-9b71-b2cf3c01e474.png)

**1)** The issue has only occurred once; I have been unable to reproduce the issue again.

**2)** Microsoft Edge is set to delete all browsing history when closed.  So previous browsing activity shouldn't be related to the issue.

**3)** https://www.startpage.com/ is set as the default opening page, therefore Startpage should have been shown in the tab when opening the browser, instead of the error page.

**4)** It's possible that it could be related to the setting "_Suspend network activity until all filter lists are loaded_" as I have been experimenting with this setting recently.  However, I'm not entirely sure the issue is related to this setting, as I have had that setting enabled for the past week, without experienced the error page.

`"suspendUntilListsAreLoaded": true`

**5)** It was not due to the browser updating itself; the browser last updated 4 days ago.

**6)** uBlock Origin is the only extension installed.

-----
Windows 10 - 21H2 (19044.1586)
Microsoft Edge - 99.0.1150.46
uBlock Origin - 1.41.8 (Microsoft Edge Store version)

### A specific URL where the issue occurs

https://www.startpage.com/

### Steps to Reproduce

This issue cannot be reliably reproduced.

### Expected behavior

The browser should have opened and loaded startpage.com

### Actual behavior

The browser opened and displayed an error page.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Chromium: 99
filterset (summary): 
  network: 85451
  cosmetic: 86911
  scriptlet: 21617
  html: 0
listset (total-discarded, last updated): 
  added: 
    adguard-annoyance: 50988-157, 2d.17h.25m
    block-lan: 43-0, 2d.17h.25m
    ublock-annoyances: 4372-152, 2d.17h.25m
  default: 
    user-filters: 90-0, never
    easylist: 64409-47, 2d.17h.25m
    easyprivacy: 26708-213, 2d.17h.25m
    plowe-0: 3709-818, 2d.17h.25m
    ublock-abuse: 72-0, 2d.17h.25m
    ublock-badware: 3922-84, 2d.17h.25m
    ublock-filters: 30400-461, 2d.17h.25m
    ublock-privacy: 200-2, 2d.17h.25m
    ublock-unbreak: 1736-45, 2d.17h.25m
    urlhaus-1: 9466-0, 5h.58m
filterset (user): [array of 90 redacted]
trustedset: 
  added: [array of 6 redacted]
hostRuleset: 
  added: [array of 20 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1499 ms (selfie)
  maxAssetCacheWait: 235 ms
```
</details>

**Comment by gwarser** [comment] 2022-03-22 19:55
>4) It's possible that it could be related to the setting "Suspend network activity until all filter lists are loaded"

It's related.

>5) It was not due to the browser updating itself; the browser last updated 4 days ago.

Maybe some add-on updated and opened "what's new" page?

**Comment by DesertBear** [comment] 2022-03-22 23:40
uBlock Origin is the only extension installed.  Therefore, there were no updates or "What's new" pages prior to this error page being displayed.

There is however a common theme in both our cases: it appears the issue is triggered after the browser is closed and then reopened within a short period of time.  For me it was a manual close and re-open; for the Reddit poster, they updated the browser which closed and re-opened the browser.

I'm not sure whether this is related or not, however I have seen the browser sometimes temporarily redirect to _about:blank_ before loading a webpage.  In the below video for example, the second time the browser is opened (at 10 seconds) you can see the address bar quickly redirect to _about:blank_ before loading www.startpage.com again.  As mentioned, it may not be relevant.

**Video A:**
https://user-images.githubusercontent.com/27423064/159592945-54864471-813b-4f64-ad78-3859305778f5.mp4


And as per the next video, I have now reproduced this issue again by opening and closing Microsoft Edge multiple times in Windows Sandbox.  When it fails, the address bar goes from www.startpage.com (the default page when opening the browser) to the extension error page.  This is with the following conditions set in Windows Sandbox:

**1)** Default uBlock Origin settings, except:

The "_Suspend network activity until all filter lists are loaded_" setting is enabled.


**2)** Default Microsoft Edge settings, except:

In `edge://settings/startHomeNTP`, it is set to open _https://www.startpage.com/_ when the browser starts.


**Video B:**
https://user-images.githubusercontent.com/27423064/159592990-fad1adbf-744d-4839-89f3-4fd140c74bbc.mp4

**Comment by dcm** [comment] 2022-03-25 17:38
[Reddit poster](https://github.com/uBlockOrigin/uBlock-issues/issues/2063#issuecomment-1075579747) here, this happened again after opening Brave just after signing into my macOS account. The tab opened to the right of the tab that had been active before I last closed Brave (which was actually this very page).

URL this time was `chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/empty?secret=sfq60f`.

As I stated in that Reddit post, this does not seem like a big deal to me, but is strange.

I did some quick searches through the code and I'm pretty convinced this is related to the setting "Suspend network activity until all filter lists are loaded". Not sure what the state is that brings this about though.

**Comment by gorhill** [comment] 2022-03-25 18:21
>  I'm pretty convinced this is related to the setting "Suspend network activity until all filter lists are loaded"

It is related, that is why it is not enabled by default in Chromium-based browsers.

**Comment by dcm** [comment] 2022-03-25 19:04
Ah that's interesting, since restored Chromium tabs -- I think -- only load when you activate them. 

Maybe a "fix" of sorts could be replacing the `empty` file with an html page just saying "loading uBO" and give the users an option to have that page automatically close itself (rather, the extension would automatically close it) once uBO is loaded (otherwise users would wonder what random page sometimes appears when they open their browsers).

**Comment by gorhill** [comment] 2022-03-25 19:28
I prefer to identify the root cause of the issue rather than just fixing the sumptoms. I haven't had time yet to look into this.

**Comment by gwarser** [comment] 2022-03-31 10:51
@dcm @DesertBear if you can reproduce, can you check if this still happens in latest dev version https://github.com/gorhill/uBlock/releases ?

**Comment by DesertBear** [comment] 2022-04-01 19:20
I have been unable to reproduce the issue so far in uBlock Origin development build 1.42.1b1.

**Closed** 2022-04-02 14:43 UTC
