### ISSUE TITLE
'$popup' not working

### ISSUE THREAD

**Issue by nicekon** [uBlockOrigin/uBlock-issues#1659] opened 2021-07-14 01:32 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dood.watch/d/bnyc4jrdf5sx`

### Describe the issue

`*$popunder,domain=dood.watch`

popunder ad is showing but rules not working

### uBlock Origin version

1.36.2

### Browser name and version

Chrome 91.0.4472.114

### Settings

Activate only user filters

**Comment by gwarser** [comment] 2021-07-14 06:43
I don't see a popup?

**Comment by uBlock-user** [comment] 2021-07-14 06:45
> Activate only user filters

Did you disable all other default lists ?

**Comment by gwarser** [comment] 2021-07-14 07:06
Blocked in Firefox, but context is missing? 
![image](https://user-images.githubusercontent.com/886325/125578389-bc55e0f1-5a79-4937-8841-3fd8ee938816.png)

**Comment by nicekon** [comment] 2021-07-14 08:04
> > Activate only user filters
> 
> Did you disable all other default lists ?

@uBlock-user 
Every filter has disabled all filters.
To test the $popunder option.
If you turn off all filters and connect the site, the popunder pop-up may appear.

<img width="1441" alt="스크린샷 2021-07-14 오후 5 03 13" src="https://user-images.githubusercontent.com/792574/125586335-8f8519dd-9fe6-4203-89a4-52ae6874f660.png">

**Comment by nicekon** [comment] 2021-07-14 08:07
@gwarser The popunder ads is not blocked by the `*$popup` rule in chrome.

**Comment by gorhill** [comment] 2021-07-14 09:28
Confusing, the opening comment states:

> - [x] uBO with default lists/settings

Then later in another comment:

 > Every filter has disabled all filters ... If you turn off all filters

So does it happen with the default settings/lists? And if this requires to disable default filter lists?

**Comment by nicekon** [comment] 2021-07-14 12:01
> Confusing, the opening comment states:
> 
> > * [x]  uBO with default lists/settings
> 
> Then later in another comment:
> 
> > Every filter has disabled all filters ... If you turn off all filters
> 
> So does it happen with the default settings/lists or does this requires to disable default filter lists?

I'm sorry for confusion.

All filters were disabled. Only user rules were activated.

Thank you.

**Comment by gorhill** [comment] 2021-07-14 13:44
uBO's onCreatedNavigationTarget() listener is not being called, so it appears to be a browser extension framework issue, and given that the issue is not reproducible with default filter lists, unlikely I will spend further time on investigating further for a workaround (if any).

**Comment by nicekon** [comment] 2021-07-15 07:26
Thank you for your reply. I am working on a filter list in Korea.  Popunder ads are used on so many sites. Script files associated with popunder are difficult to block because they vary from site to site. Some sites are lucky to be blocked, but advertisements are often exposed on most sites.

Blocking URLs has limitations in blocking popunder ads. Using the $popunder rule is much more helpful. I hope that that can be resolved. Thank you.

**Comment by gorhill** [comment] 2021-07-15 10:25
Note that I could not reproduce a `popunder` case, I reproduced exactly what you show in your screenshot, which is a `popup` case (your red arrow).

In such case, uBO's [onCreatedNavigationTarget()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCreatedNavigationTarget) listener is not being called, which is necessary for uBO to find out which tab opened the popup and thus properly filter it -- I don't see how this can be solved safely without onCreatedNavigationTarget() working as expected.

**Comment by nicekon** [comment] 2021-07-15 10:50
The popunder ad runs a small square pop-up window at the bottom right; it opens a new window where the ad is displayed afterwards (see video).

Please refer to the script file address where the popunder is activated. I hope it helps.

**video**
https://youtu.be/XIfivN4NX0g

**popunder script file**
https://practisecolander.com/f0/6f/53/f06f53688194268edaf23d2b44a59e27.js

**Comment by gorhill** [comment] 2021-07-15 12:37
Don't use `popuunder` please, this is not a `popunder` from uBO's point of view, this is a `popup`, i.e. the document in the main tab stays the same.

**Comment by gorhill** [comment] 2021-07-15 14:36
> Blocked in Firefox, but context is missing?

It's because the popup is opened from an `about:blank` frame, and uBO reports this context, i.e. no hostname.

**Comment by gorhill** [comment] 2021-07-15 15:40
Just disabling "uBlock filters" was enough to reproduce the issue, no need to disable all the other lists, which allows to reproduce the issue without having to allow all ads and trackers.

**Comment by nicekon** [comment] 2021-07-16 01:35
> Don't use `*$popunder` please, this is not a `popunder` from uBO's point of view, this is a `popup`, i.e. the document in the main tab stays the same.

Oh, I see. I expected the $popunder to block the popunder ad. What I'm saying is that the popunder ad is being used on a lot of sites, and the script opens a new window after hiding the http referer property of header. I hope it helps.

**Comment by gwarser** [comment] 2021-07-16 09:27
@nicekon can you try latest dev build <https://github.com/gorhill/uBlock/releases>? It look fixed to me.

**Comment by nicekon** [comment] 2021-07-16 09:41
Thank you for answering. Unfortunately, I still see pop-up ads.

**video**
https://youtu.be/4qW5yP4gI3U

**Comment by gorhill** [comment] 2021-07-16 12:05
`*$popup` works though. The problem is that with the synthetic event -- because onCreatedNavigationTarget() failed to fire -- uBO does not know from which tab the popup was created.

**Comment by gorhill** [comment] 2021-07-16 15:39
I looked into this a bit more and this is not something which can be fixed in uBO, this has to be fixed in Chromium.

**Closed** 2021-07-16 17:37 UTC
Labels: Chromium, external
