### ISSUE TITLE
Youtube homepage and comment does not load properly

### ISSUE THREAD

**Issue by mentatss** [uBlockOrigin/uBlock-issues#1719] opened 2021-09-13 16:24 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

![image](https://user-images.githubusercontent.com/83447048/133120610-bf7561ff-506a-4bc6-981b-0dace36c3075.png)
Around 2 out of 5 times, YT homepage will look like this, with nothing but side bar and search box loaded.
Also sometime when watching video, the comment also won't load.
Refresh the page solve the issue.

### A specific URL where the issue occurs

https://www.youtube.com/

### Steps to Reproduce

1. Open Youtube
2. Open any video
3. Sometime homepage and comments won't load properly

### Expected behavior

Comments load when scroll down.
Homepage shows videos.

### Actual behavior

Comment won't load.
Homepage only shows search box and sidebar.

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 93

### Operating System and version

Windows 10

**Comment by gorhill** [comment] 2021-09-13 16:29
> - [x] I verified that this is not a filter issue

How did you verified that this is not a filter issue?

**Comment by mentatss** [comment] 2021-09-13 16:34
> ed

I thought it's not a filter issue since I just use UBO with all default setting, install and run, no change made.

**Comment by gorhill** [comment] 2021-09-13 16:39
I can't reproduce with default settings and up to date filter lists. Did you try without uBO? Or with another blocker?

**Comment by felix-22** [comment] 2021-09-13 16:45
It's youtube's issue like I said: https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-907346135

> I thought it's not a filter issue since I just use UBO with all default setting, install and run, no change made.

Default filters can be still the cause as well, you have to disable the predefined filter lists to be sure that the filters are not to blame as well.

**Comment by felix-22** [comment] 2021-09-16 11:09
> mentatss :
> ### I tried to reproduce the issue when...
>     * [x]  uBO is the only extension
>     * [x]  using a new, unmodified browser profile

Really? Taking a closer look at your screenshoot I see something that looks like an extension, is it an extension?:
![1](https://user-images.githubusercontent.com/75935068/133600411-273af3e4-5425-4760-a4cc-f8aa938d030e.png)

Further I see some custom bookmarks on the bookmark bar, does not look like a new, unmodified browser profile:
![2](https://user-images.githubusercontent.com/75935068/133600735-e978bc11-434f-498a-9e40-58f532ee4fa8.png)

Of course, this doesn't immediately mean that you haven't checked on another clean profile without any add-ons, but considering:
- that the screenshot is not from a clean profile without add-ons
- a lot of users are lying, ticking the boxes, when in fact they didn't do it at all

it is reasonable to assume that there is a possibility that you may not have completed the steps you marked as completed as well, could you explain this.

**Comment by mentatss** [comment] 2021-09-16 17:18
Ok for some reasons I haven't encountered the problem for the last 2 days.
Today I tried a new profile with nothing but UBO installed and got a new problem: The related videos on the right won't load.
![image](https://user-images.githubusercontent.com/83447048/133656535-4b92dee0-1b61-4355-a930-28020238f75b.png)

**Comment by uBlock-user** [comment] 2021-09-16 17:20
That's a known Youtube issue, only happens on some videos.

**Closed by uBlock-user** 2021-09-16 17:20 UTC
Labels: unable to reproduce
