### ISSUE TITLE
ADs still appearing for the first few minutes upon opening firefox

### ISSUE THREAD

**Issue by Mr-ex777** [uBlockOrigin/uBlock-issues#133] opened 2018-07-18 15:19 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I've used ublock origin for a while now and after firefox updated to firefox quantum (I remember), there is a good full 5 minutes that advertisements will appear as if ublock didn't block them for around 5 minutes before ublock fully boots and blocks the ads. I had not saw this problem before updating firefox, but after updating it it seems to just act as if it didn't exist before going into blocking the ads. Extremely annoying. Please help?

### A specific URL where the issue occurs

https://www.youtube.com/

Usually i start at youtube, but the problem happens everywhere.

### Steps to Reproduce

1. Use ublock on firefox
2. For the first 5 minutes, ads will not be blocked. 
3. After 5 minutes, ads will be automatically blocked.

### Expected behavior:

Ublock blocks advertisements instantly.

### Actual behavior:

Ublock stays null for 5 minutes as if it wasn't detecting ads then blocks ads after 5 minutes

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Firefox Quantum 61.0.1 (64-bit)
* Operating System and version: Windows 7 64 Bit Operating Version

**Comment by uBlock-user** [comment] 2018-07-18 15:38
Duplicate of https://github.com/gorhill/uBlock/issues/1327

**Closed by uBlock-user** 2018-07-18 15:38 UTC

**Comment by gorhill** [comment] 2018-07-18 16:00
Also, uBO loads in a fraction of second, if you find that it takes 5 minutes to have an effect, you have a bigger problem elsewhere with your Firefox installation, which you will have to investigate on your side (I never ever experienced such a delay).

Regarding your only one example, Youtube, pages are loaded dynamically by modifying the DOM, so if uBO suffered known browser issue <https://github.com/gorhill/uBlock/issues/1327>, you need to force a reload of the page.
