### ISSUE TITLE
[Feature request] Add RegEx for dynamic filterrules

### ISSUE THREAD

**Issue by j-lakeman** [uBlockOrigin/uBlock-issues#2242] opened 2022-09-03 09:34 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I have JavaScript blocking enabled, but wish to be able to deactivate it for a range of webpages, e. g. all with the string "git" in them. I really appreciate the regex function in the exception rules section and would like to have something comparable for the dynamic rules section.

### A specific URL where the issue occurs

https://github.com/

### Steps to Reproduce

lorem ipsum

### Expected behavior

Being able to use regex like `no-scripting: /^.git./ false`

### Actual behavior

```
no-scripting: github.com false
no-scripting: gitlab.com false
```

### uBlock Origin version

1.44.0

### Browser name and version

Firefox 104.0.1 (64-Bit)

### Operating System and version

macOS Big Sur 11.6.8

**Comment by Yuki2718** [comment] 2022-09-03 10:58
I tend to wish if it supported entity filter i.e. `* www.example.* * noop`. This will save lots of adjustment for rapidly changing movie sites. The regex in dynamic rule will be in most cases not tokenizable as in the example, and also it's kinda against the spirit of the feature - the suggested rule allows githiimamalwaresite .com too.

**Closed as completed** 2022-09-03 11:50 UTC
Labels: enhancement, declined

**Comment by gorhill** [comment] 2022-09-03 12:10
There is no tokenization taking place in dynamic filtering rules, it's all lookup tables using hostnames as keys, hence why it's fast compared to static filtering -- and using lookup tables means no possibility of regex or wildcards. I do not intend to change this.

**Comment by Yuki2718** [comment] 2022-09-03 13:05
Forgive me for thought experiment. Will this be too much code change to add a user-editable variable, say, `?` (whatever simbol but to distinguish from wildcard).
1. User defines what TLDs he wants to include into `?` e.g. `?-means: app,buzz,com`
2. Whenever user create a rule with `?` manually via dynamic rules pane, uBO internally translates to rules of all these TLDs i.e.
```
* * www.example.app * noop
* * www.example.buzz * noop
* * www.example.com * noop
```
but in the pane it shows as `* www.example.? * noop` Too many use of this will cause high RAM usage as the actual numbers of rules diverge (particularly `example1.? example2.? * noop`) but those who use this are expected to be sensible. It's impossible to incorporate all the public suffix but those rTLDs used by rapid-changing sites are limited. Once you have defined most of TLDs actually used, it frees up the needs for regular adjustment to some extent.

**Comment by gorhill** [comment] 2022-09-03 13:47
> Will this be too much code change to add a user-editable variable

Yes.

The purpose of dynamic filtering is not to converge toward static filtering capabilities; the purpose is to be a point-and-click way to add/remove hostname-based firewall-like rules. Any sort of syntax for which there are no point-and-click user interface is not a good fit for dynamic filtering, that's fall into static filtering realm. Beside, proposing complications like this should always, _always_ with real world cases to support such propositions. When you start to look at _real_ world cases, I highly doubt they will prove to be valid use cases.

**Comment by Yuki2718** [comment] 2022-09-03 13:55
> I highly doubt they will prove to be valid use cases.

I meant e.g. kisscartoon.*, kissanime.*, and all similar sites which regularly change TLDs but okay, thx for taking time.

**Comment by gorhill** [comment] 2022-09-03 14:33
> I meant e.g. `kisscartoon.*`, `kissanime.*`

People visit specific ones, so they will point-and-click for the one they end up visiting. An actual use case would go in _details_ to show why it's really tedious for dynamic filtering users to point-and-click on the kisscartoon sites they happen to visit. I highly doubt someone would complain that they need the feature because they visited 10 kisscartoon sites and had to set the same set of rules, and if so, I would advise them that since they are willing to manually create rules, might as well use static filtering with a filter such as `...$domain=kisscartoon.*,denyallow=...`. There is just no convincing _actual_ and _detailed_ use cases being made to justify the amount of work requested from others.

I gather that if people who request such features would have to do the actual work themselves to implement it while also able to apprehend the sprawling complications to the point-and-click user interface, and the future workload of merely maintaining all that new code, they would realize the task of managing a few dynamic rules with the current implementation is completely trivial in comparison.

**Comment by gwarser** [comment] 2024-12-30 15:03
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/439
