### ISSUE TITLE
advance user can't be turned off again

### ISSUE THREAD

**Issue by LarsErikOsterud** [uBlockOrigin/uBlock-issues#491] opened 2019-03-28 03:28 UTC
### Prerequisites

Start Firefox.
Reset uBlock Origin to standard.
Only the small drop down is from the icon (not the left advaced part).

### Description

Advanced icon drop down list does not got back to non-advanced
when you remove the "x" for "i am an advanced user"

### Steps to Reproduce

Change to "I am an anvaced user" (set "x" in the box).
The left advanced pane in the drop down from the icon is showing.
Change to "not an advance user (remove "x" in the box).
The left advanced pane in the drop down from the icon is still showing.

### Expected behavior:

When you remove the "x" from "I am an advanced user" the
advanced part of the icon dropdown dialog (left part) should be gone

### Actual behavior:

The advanced part of the icon dropdown dialog is still there.
only way to get rid of is is the "reset to standard" button.

### Your environment

* uBlock Origin version: 1.18.12
* Browser Name and version:  Firefox 67.0b5 (64-bit)
* Operating System and version: WIndows 10

**Comment by uBlock-user** [comment] 2019-03-28 06:27
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/125

**Closed by uBlock-user** 2019-03-28 06:27 UTC
