### ISSUE TITLE
Comment support in the My Rules list

### ISSUE THREAD

**Issue by PSalant726** [uBlockOrigin/uBlock-issues#1438] opened 2021-01-05 00:17 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
In the `My Rules` list, it would be nice to be able to include comments for organizational purposes. My specific desired use case would be to include a trailing comment on rules that I need to keep configured in order to support other extensions that may intercept requests for various purposes.

For example, the [LocalCDN](https://www.localcdn.org/) extension currently requires keeping a list of rules configured in order to to properly intercept requests for assets. I would otherwise be `block`ing requests to some of these domains, and it's not currently possible to make any note of the fact that these rules are deliberately configured to support another extension. An example of my desired configuration could look like:
```
* ajax.googleapis.com * noop   ! Supports LocalCDN
```
(This preserves the `!` comment syntax currently available in the `My Filters` list.)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
This is a feature request.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]
When configuring a dynamic filtering rule via the `My Rules` page, trailing comments on a given line are persisted on save.

### Actual behavior:

[What actually happened]
When configuring a dynamic filtering rule via the `My Rules` page, trailing comments have no specified syntax. Any attempt to create one is treated as a syntax error, and the comment is removed upon saving.

### Your environment

* uBlock Origin version: 1.32.2
* Browser Name and version: FF 85.0b4 (64-bit)
* Operating System and version: macOS 10.15.7 and macOS 11

**Comment by gorhill** [comment] 2021-01-05 12:16
Duplicate of <https://github.com/gorhill/uBlock/issues/333>.

**Closed by gorhill** 2021-01-05 12:16 UTC

**Comment by PSalant726** [comment] 2021-01-05 13:18
@gorhill I believe this is a different feature request. The linked issue is asking for the ability to create comments as entire lines, and ultimately leads to [this discussion](https://github.com/gorhill/uMatrix/issues/314#issuecomment-128793820) about preserving the order of rules in the UI.

I am simply looking to be able to append a comment to the end of a rule, which I believe would be a much smaller change, no?

**Comment by gorhill** [comment] 2021-01-05 13:37
The "My rules" pane is just a view on the internals of uBO, and the internal representation is not plain text, and there is no place for concept such as comment in internal representation. Not only uBO wouldn't know what to do with a comment, it wouldn't know when to discard/restore it when one toggle a rule using point-and-click. This just doesn't work, and what appears to be trivial and described as a short single sentence would involve rewrite large swatch of codes from the ground up.
