### ISSUE TITLE
Adguard Base Filters should be renamed AdGuard English filter

### ISSUE THREAD

**Issue by superlex** [uBlockOrigin/uBlock-issues#70] opened 2018-06-13 14:26 UTC
Hi,
Adguard Base Filters is now titled AdGuard English filter:

> ! Title: AdGuard English filter
> ! Description: Filter list that specifically removes adverts on English language websites. English filter is supposed to work along with EasyList.

https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt

On the contrary, old AdGuard English filter is now titled AdGuard Base filter:

> ! Title: AdGuard Base filter
> ! Description: EasyList + AdGuard English filter. This filter is necessary for quality ad blocking.

https://filters.adtidy.org/extension/ublock/filters/2.txt

**Comment by gorhill** [comment] 2018-06-13 15:13
Duplicate of #35.

**Closed by gorhill** 2018-06-13 15:13 UTC
Labels: duplicate, enhancement

**Comment by uBlock-user** [comment] 2018-06-13 15:22
@gorhill He's suggesting to rename Adguard Base Filters to Adguard English Filters in the 3p-filters.html page, as the mainatainer has done it so.

**Comment by gorhill** [comment] 2018-06-13 15:43
The list was not renamed to "English", it always have been named this way. The other issue shows the statement by @ameshkov that this filter list is really intended as a generic one, just like EasyList is a generic one.

**Comment by uBlock-user** [comment] 2018-06-13 15:48
If you say so, I felt a bit confusing how the `! Title` of  the filterlist Adguard Base Filter was changed to Adguard English Filter, so I avoided tagging it duplicate on the first glance.

**Comment by ameshkov** [comment] 2018-06-13 15:51
Seems to be our mistake, the filter was renamed to `AdGuard Base filter` everywhere except the `_without_easylist` version. We'll fix it, thanks for notifying me.

**Comment by superlex** [comment] 2018-06-13 16:19
Thanks :)
