### ISSUE TITLE
Add filters adblockid for indonesia country

### ISSUE THREAD

**Issue by 3xploiton3** [uBlockOrigin/uBlock-issues#979] opened 2020-04-07 08:28 UTC
more active maintain

https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt
https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid-plus.txt

**Comment by uBlock-user** [comment] 2020-04-07 08:37
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/958

**Closed by uBlock-user** 2020-04-07 08:37 UTC
