### ISSUE TITLE
Element Picker and Zapper Mode not working on Thunderbird RSS Feeds

### ISSUE THREAD

**Issue by click-click** [uBlockOrigin/uBlock-issues#1729] opened 2021-09-20 14:40 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Element Picker and Zapper modes do not work on RSS feed content viewed in Thunderbird. If I enter About Thunderbird and select the Releases link. picker and zapper work fine.

### A specific URL where the issue occurs

http://feeds.feedburner.com/TheWindowsClub

### Steps to Reproduce

Create an RSS feed in Thunderbird from the URL above
Select one of the listed entries to be viewed
Select element picker for that content
Nothing happens

### Expected behavior

I assumed element picker and Zapper modes worked the same as in Firefox. If I select the link of the RSS feed entry, the content can be shown in Firefox and it displays the same as it does in Thunderbird. The only difference is the the picker and zapper modes work with Firefox, but not with Thunderbird. 

### Actual behavior

Element Picker and Zapper Modes do not react/work on any RSS Feed content in Thunderbird

### uBlock Origin version

1.37.2

### Browser name and version

Thunderbird 78.14

### Operating System and version

w7, w8.1, w10

**Comment by gwarser** [comment] 2021-09-20 17:14
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/825

**Comment by gwarser** [comment] 2021-09-20 17:24
> Create an RSS feed in Thunderbird from the URL above
> Select one of the listed entries to be viewed
> Select element picker for that content
> Nothing happens

This works for me:

![image](https://user-images.githubusercontent.com/886325/134046429-37951269-d480-4d52-988d-8071f6c89cca.png)

**Closed** 2021-09-20 18:50 UTC
Labels: duplicate

**Comment by click-click** [comment] 2021-09-21 12:46
I tried the v93 portable beta  version and picker and zapper modes are  working there, so I guess you are right about WebExtentions being messed up in v78. Thanks for testing. Will wait till the next portable v91.2 ESR is released.
Thanks for taking the time to test and verify.
