### ISSUE TITLE
Bug with `Custom accent color`

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uBlock-issues#1979] opened 2022-02-12 12:58 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Since uBlock version 1.41.0 There is an extra option to set your own custom accent color. 
Although it works fine if you pick one of the 10 pre-installed colors, it does not work properly if you choose another random color. 

When ik pick the color `RGB(252,158,125)` The actual accent color is way more dark then the color picked. 
<details><summary>See this printscreen</summary> 

![image](https://user-images.githubusercontent.com/81161435/153712078-99f90446-37f2-4813-a28b-a86635fe113a.png)
</details>

The strange thing is: if you pick `RGB(49,42,101)` the color is a little bit lighter.

<details><summary>See this printscreen</summary> 

![image](https://user-images.githubusercontent.com/81161435/153712162-689edd35-eb59-4091-b0ab-804b4f303e24.png)

</details>

*It doesn't matter if your theme is Light or Dark*

### A specific URL where the issue occurs

uBlock settings pane

### Steps to Reproduce

1. Go to the uBlock settings pane
2. Pick a custom accent color **But NOT a pre-installed**
3. Pick `RGB(252,158,125)` or `RGB(49,42,101)`
4. You will see that the color in the checkboxes are different than the color you picked.

### Expected behavior

The custom accent color should be the same as the one I picked.

### Actual behavior

The custom accent color is different (darker or lighter) from the one I picked

### uBlock Origin version

1.41.0

### Browser name and version

MS Edge version 99

### Operating System and version

Windows 10, 21H2

**Comment by gwarser** [comment] 2022-02-12 13:00
This is a feature to make sure elements always have proper contrast. "Lightness" of the color is always the same, you can change only the hue.

**Comment by gwarser** [comment] 2022-02-12 13:02
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1957

**Closed by gwarser** 2022-02-12 13:02 UTC
