### ISSUE TITLE
[BUG] Zapper mode and picker mode in Firefox desktop/android is no longer working.

### ISSUE THREAD

**Issue by ThomasBaruzier** [uBlockOrigin/uBlock-issues#3273] opened 2024-06-18 22:32 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I cannot select any element when trying to use the picker or zapper mode. The issue relies on the selection method used, depreciated by Firefox (127.0-1 on Arch Linux):
```js
Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture touch-simulator.js:216:20
```
Again, it's not an issue where the bug occurs after using the mode (for instance, a reappearing element, like shown in the wiki), but the clicking/selection of the element to block in the first place.
Maybe this issue is a duplicate, but searching the issue tracker for keywords related to the console error doesn't yield any results.

### A specific URL where the issue occurs.

```yaml
Every website, but since you ask for a link: https://mail.google.com
The only exception seems to be images.
```

### Steps to Reproduce

1. Enter picker or zapper mode in latest Firefox
2. Try to click anything except images

### Expected behavior

Be able to click and select an element in these modes.

### Actual behavior

These modes don't select anything except images.

### uBO version

uBlock Origin 1.58.0, latest as of writing

### Browser name and version

Firefox 127.0-1

### Operating System and version

Arch Linux, fully updated

**Comment by garry-ut99** [comment] 2024-06-19 09:25
> Thomas

No problem on Windows and Android on my side, so maybe you disabled cosmetic filtering, especially given you still can Pick images.

> These modes don't 

As for Zapper mode, for me it always works, regardless of cosmetic filtering disabled.

Zapper mode doesn't work only if I try to use it without closing Picker mode first, I have to close Picker mode before using Zapper mode, otherwise Picker mode still remains active despite Zapper mode icon has been clicked, the same happens vice-versa: clicking Picker mode icon won't work unless Zapper mode is closed first.

Not sure whether "to not allow the other mode before closing the previous mode" is a feature by design or a bug, because I didn't investigate it as for now.

**Comment by TyraVex** [comment] 2024-06-19 11:16
> > These modes don't select anything except images.
> 
> Make sure cosmetic filtering is not disabled https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering
> 
> Please share troubleshooting information, you will find it in uBO dashboard, on the bottom of the Support tab.
> 
> Duplicate of #1795?



> > Thomas
> 
> No problem on Windows and Android on my side, so maybe you disabled cosmetic filtering, especially given you still can Pick images.
> 
> > These modes don't
> 
> As for Zapper mode, for me it always works, regardless of cosmetic filtering disabled.
> 
> Zapper mode doesn't work only if I try to use it without closing Picker mode first, I have to close Picker mode before using Zapper mode, otherwise Picker mode still remains active despite Zapper mode icon has been clicked, the same happens vice-versa: clicking Picker mode icon won't work unless Zapper mode is closed first.
> 
> Not sure whether "to not allow the other mode before closing the previous mode" is a feature by design or a bug, because I didn't investigate it as for now.

Indeed, cosmetic filtering was disabled for some reason and this caused the picker/zapper mode to not be able to pick anything.

Thank you for this solution, and pardon me for the inconvenience.

**Comment by ThomasBaruzier** [comment] 2024-06-19 11:17
> > These modes don't select anything except images.
> 
> Make sure cosmetic filtering is not disabled https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering
> 
> Please share troubleshooting information, you will find it in uBO dashboard, on the bottom of the Support tab.
> 
> Duplicate of #1795?



> > Thomas
> 
> No problem on Windows and Android on my side, so maybe you disabled cosmetic filtering, especially given you still can Pick images.
> 
> > These modes don't
> 
> As for Zapper mode, for me it always works, regardless of cosmetic filtering disabled.
> 
> Zapper mode doesn't work only if I try to use it without closing Picker mode first, I have to close Picker mode before using Zapper mode, otherwise Picker mode still remains active despite Zapper mode icon has been clicked, the same happens vice-versa: clicking Picker mode icon won't work unless Zapper mode is closed first.
> 
> Not sure whether "to not allow the other mode before closing the previous mode" is a feature by design or a bug, because I didn't investigate it as for now.

Indeed, cosmetic filtering was disabled for some reason and this caused the picker/zapper mode to not be able to pick anything.

Thank you for this solution, and pardon me for the inconvenience.

**Closed** 2024-06-19 11:17 UTC

**Comment by ThomasBaruzier** [comment] 2024-06-19 12:50
> Given you had it disabled on two different devices (Desktop and Mobile), I wonder how could you mistakenly disable it on 2 different devices at the same time, perhaps you had uBO backup with cosmetic filtering disabled, which then you imported into the both devices.

Yes, it is because of backups both of my devices were affected.

> It caused only Picker to not be able to pick anything (except images).
> Not sure whether "to not allow the other mode before closing the previous mode" is a feature by design or a bug, because I didn't investigate it as for now.

That was the reason why zapper mode didn't worked in this case.

Thanks for the explanations.
