### ISSUE TITLE
Chrome browser Translator no works

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uBlock-issues#2345] opened 2022-10-28 19:05 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Chrome browser Translator no works whit the adblocker ( see the steps )

### A specific URL where the issue occurs.

https://www.warcrafttavern.com/wow-classic/news/more-som-to-wotlk-transfer-updates/

### Steps to Reproduce

1. Example sites: `warcrafttavern.com` or `fotocasa.com`
2. Go to: `https://www.warcrafttavern.com/wow-classic/news/more-som-to-wotlk-transfer-updates/`
3. Click Right Button.. and "Traducir a Español" in my case and all ok
4. Now click on a link on the site and return to the previous page
5. The Translator no appears
6. I need refresh the page

![Captura1](https://user-images.githubusercontent.com/33556647/198711929-add62194-96a9-4548-a6fa-e5ac8df69eb3.png)

### Expected behavior

Maybe it should work 

### Actual behavior

No idea why that happens

### uBO version

1.44.4

### Browser name and version

Chrome 107.0

### Operating System and version

Windows 11

**Comment by gwarser** [comment] 2022-10-28 19:15
Translator does not appear because page is already translated. No difference with uBO disabled.

**Comment by gorhill** [comment] 2022-10-28 19:24
Happens when blocking `https://www.googletagmanager.com/gtm.js?id=GTM-PG3T4ZJ&l=dataLayer`. This happens with any content blocker blocking that resource.

**Comment by gorhill** [comment] 2022-10-28 20:46
I cannot reproduce when I disable EasyPrivacy, so still a filter issue.

**Comment by gorhill** [comment] 2022-10-28 20:47
Closing as filter issue.

**Closed** 2022-10-28 20:46 UTC
Labels: filterlist

**Comment by gorhill** [comment] 2022-10-28 20:50
Actually, I can reproduce without any content blocker installed, by just disabling JavaScript for the site, so best is to report the issue to Chromium developers.
