### ISSUE TITLE
disabling cosmetic filtering causes element picker to not work

### ISSUE THREAD

**Issue by MinuteAd8502** [uBlockOrigin/uBlock-issues#1658] opened 2021-07-12 17:12 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When I disable cosmetic filtering on some site by clicking on toolbar icon (click to disable cosmetic filtering on this site) then element picker button does not work, not entering element picker mode

### A specific URL where the issue occurs

https://vukajlija.com/

### Steps to Reproduce

1. go to url
2. disable cosmetic filtering on that site
3. enter element picker mode (refreshing site may be needed before step 3)

### Expected behavior

i expect to be able to select elements and see their id list and url list on bottom right corner

### Actual behavior

it only works when cosmetic filtering enabled, otherwise nothing happens

### uBlock Origin version

1.36.0

### Browser name and version

Firefox 91

### Operating System and version

Windows 10 21H1

**Comment by gwarser** [comment] 2021-07-12 17:17
Duplicate of https://github.com/gorhill/uBlock/issues/3212

Was fixed today https://github.com/gorhill/uBlock/commit/e983f9a76e1ace241410e384bba1968fd1f93aae

**Closed by gwarser** 2021-07-12 17:17 UTC

**Comment by gorhill** [comment] 2021-07-12 17:49
> i expect to be able to select elements and see their id list

Even with the fix, you won't see "their id list" (assuming you refer to the list of suggested cosmetic filters), since it's pointless to create cosmetic filters for a site for which cosmetic filtering is disabled.
