### ISSUE TITLE
Auto update filter list / add back purge button

### ISSUE THREAD

**Issue by whytf** [uBlockOrigin/uBlock-issues#3263] opened 2024-06-04 13:29 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I read that there is automatic filter update every hour, however thats far from the truth, whenever i visit site that updates their ad strategy often, it is either broken or ads shows up, before i used to just purge and update all lists in 2 clicks, now i have to unselect every single one, click apply, select every single one again and click update, just because someone decided that the button was unused.

I use this option too "Suspend network activity until all filter lists are loaded"

### A specific URL where the issue occurs.

```yaml
"everywhere" with often ad changes
youtube.com
facebook.com
twitch.tv
cnn.com
```

### Steps to Reproduce

1. Open any website that changes ad strategies often

### Expected behavior

Either ublock updates all the lists on start or after couple minutes which would fix the problem right there

Or

purge button could be back so i can do it in 2 clicks instead of 30

### Actual behavior

ads show, partly broken but still visible and obstructing

### uBO version

1.58.0

### Browser name and version

Brave 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)

### Operating System and version

Windows 11 Enterprise 23H2 (OS Build 22631.3593)

**Comment by gorhill** [comment] 2024-06-04 14:17
> I read that there is automatic filter update every hour, however thats far from the truth

It's not "far from the truth", it is exactly how it works.

**Comment by whytf** [comment] 2024-06-04 16:31
Well that must be pure coincidence that it never fixes on it's own and i have to do what purge button used to do, but someone knew better.

**Comment by whytf** [comment] 2024-06-04 16:33
Even after waiting for several "1 hour" parts it didn't refresh the lists therefore same problem until i purged it myself

**Comment by garry-ut99** [comment] 2024-06-04 17:02
As far I know filter lists are updated every 5 hours, and uBO checks every 1 hour whether there are updated filter lists available, one should not confuse checking interval (every 1h) with filter lists updating interval (every 5h):
https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#auto-update-filter-lists

By the way, there are main/official threads for "Pure button" discussion:
https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#purge-all-caches
Creating duplicate issues shoud be avoided, as there already exists a big pile of unnecessarily created duplicates.

As far I know the current approach instead of the old "Purge button", is that uBO devs should provide you a quick hot-fix link if you need to update some filter lists quickly.

**Comment by gwarser** [comment] 2024-06-04 17:52
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/3090

**Closed** 2024-06-04 17:52 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2024-06-05 00:15
> I use this option too "Suspend network activity until all filter lists are loaded"

It's not guaranteed to work, it's possible that just forcing a webpage reload yourself _after_ uBO shows as ready would fix your issue.

**Comment by garry-ut99** [comment] 2024-06-05 08:57
Yes, it's also mentioned in documentation, I'm just providing some links:
- https://github.com/uBlockOrigin/uBlock-issues/wiki/Toolbar-icon
- https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#suspend-network-activity-until-all-filter-lists-are-loaded

It seems OP mixes two different cases of why ads leak for him, as some leaking / breakages might be unrelated to filter list updates (every 5 hour), they might be caused by Chromium's unability to filter ads at browser launch, even despite an user already has his filter lists up to date.

**Comment by gorhill** [comment] 2024-06-05 11:58
> same problem

It's impossible to investigate exactly your problem if you are not very specific about it.

There are no widespread reports of the issue you mention. I personally never ever force a manual update and do not suffer the issue you mention (using Firefox). Provide a lot of details of what the "problem" is, which exact webpage, what exactly is wrong on that webpage, troubleshooting information, how many extensions you use, whether this occurs at browser launch, etc.

**Comment by whytf** [comment] 2024-06-21 19:11
> Yes, lack of information from OP to properly diagnose.
> 
> > whytf: now i have to unselect every single one, click apply, select every single one again and click update
> 
> No need to unselect & select anything: just simply clicking filter list clock icons should be sufficient to force differential update immediately if available, unless you want to say that clicking clock icons doesn't work for you.

Oh right, just click 37 times instead of 74, UI design of the century

**Comment by garry-ut99** [comment] 2024-06-22 08:38
> whytf: Oh right, just click 37 times instead of 74

It was not supposed to be a solution for your issue, it's'only a 2x faster version of your wrong workaround, while it stll doesn't solve your main issue, it at least halves its nuisance, better than nothing.

> whytf: UI design of the century

And it has nothing to do with UI design, we already told you in previous comments that in normal conditions uBO should check for new filter lists automatically every hour (in practice real update occurs every 5 hours), and we said that if auto update fails for you, this indicates the occurrence of some kind of malfunction on your side, we can't investiage it without more details from you.

Maybe you should try to reproduce your issue on other browsers, for example Chrome instead of Brave, to rule out a possibility that your issue is related to Brave. Have you done it already? You should have done it already before reporting your issue....nobody knows whether you did it or not, because you didn't mention about it, hence we have to assume you still didn't. While uBO officaily supports Chrome, it doesn't necessarily mean that there won't be problems on other Chromium forks, because other forks might contain modifications which can interferre with uBO and which uBO can't predict. Once you confirm that your issue still occurs in Chrome, we can try to continue to solve your issue.

> whytf : UI design of the century

Unless you mean not the issue with auto-update broken on your side, but you mean that 1 hour / 5 hours check / update intervals is still insufficient for you, in such case you should continue your discussion in official threads mentioned in https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#purge-all-caches to not mix your auto-update malfunction issue with the whole auto-update / purge button discussion, as they are two separate things.

**Comment by whytf** [comment] 2024-06-24 17:22
> should check 

key word should

**Comment by gorhill** [comment] 2024-06-24 19:52
It all has been explained in details why the button was removed, and how people who do not understand how things work ended up thinking the button was magically creating filters out of thin air. I can't inject into people's head understanding of all the intricacies of filter lists update if they still do not understand after reading the documentation. If you still think you understand more than we do after reading the documentation, then it means you do not trust that we know what we are doing, in which case best is that you uninstall uBO and find something that suits you better.

Locking this thread, we do not need to keep repeating what has already been said, and we do not need to endless notifications leading nowhere on an already closed issue.
