### ISSUE TITLE
when viewing filters or editing my filters on kiwi

### ISSUE THREAD

**Issue by idontveapc** [uBlockOrigin/uBlock-issues#2906] opened 2023-10-26 07:13 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [x] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

when you're viewing a filterlist and you search or edit it, the top panel options hide (popup) under the search bar on kiwi browser. it happens as soon as you tap enter button (when searching).

editing my filters gets impossible as optios are gone.

### A specific URL where the issue occurs.

1. chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/popup-fenix.html 2. chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html 3. chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=easylist

### Steps to Reproduce

1. open kiwi browser and open μblock origin "dashboard"
2. go to **`Filter lists`** and choose to view a filter list.
3. in the filterlist search for a domain or filter.
4. as you'd see options are gone, you can't even search anything else.

same is as with Filter list on My filters.

### Expected behavior

keep the options visible or usable.

### Actual behavior

option hiding themselves in the filters viewer.

### uBO version

1.52.2

### Browser name and version

Kiwi Browser 116.0.5845.72

### Operating System and version

android ...

**Comment by gwarser** [comment] 2023-10-26 07:58
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2791

**Closed by gwarser** 2023-10-26 07:58 UTC
