### ISSUE TITLE
ctrl-click does not disable uBlock0 on the current page

### ISSUE THREAD

**Issue by lovasoa** [uBlockOrigin/uBlock-issues#913] opened 2020-02-28 10:27 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On MacOS, uBlock0 instructs users to "ctrl+click to disable uBlock0 on this page", but it doesn't work

### Steps to Reproduce

1. Click on the extension's icon 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/552629/75540724-e07b9100-5a1c-11ea-842e-a1ede32d72b8.png">
2. Hover over the blue button
<img width="374" alt="image" src="https://user-images.githubusercontent.com/552629/75540776-f9844200-5a1c-11ea-98d8-e1bac44c8d75.png">
3. Press ctrl, and while keeping it pressed, click the button

### Expected behavior:
uBlock0 is disabled on the current page

### Actual behavior:

A context menu appears
<img width="377" alt="image" src="https://user-images.githubusercontent.com/552629/75540886-394b2980-5a1d-11ea-9866-aba53684779c.png">

### Your environment

* uBlock Origin version: 1.25.0
* Browser Name and version: Firefox desktop 73.0.1 
* Operating System and version: MacOS 10.15.3 (19D76)

**Comment by uBlock-user** [comment] 2020-02-28 10:37
Duplicate of https://github.com/gorhill/uBlock/issues/614

**Closed by uBlock-user** 2020-02-28 10:37 UTC
