### ISSUE TITLE
Dark Mode hides icons. Chromium, Linux

### ISSUE THREAD

**Issue by mooselimb** [uBlockOrigin/uBlock-issues#1105] opened 2020-06-09 08:56 UTC
### Prerequisites

- [ Yes] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ Yes] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [Yes ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [No ] uBlock Origin is the only extension
    - [ No] uBlock Origin with default lists/settings
    - [ No] using a new, unmodified browser profile
- [Yes - version  1.27.10] I am running the latest version of uBlock Origin
- [Yes ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The dark icons in Ublock's GUI makes it difficult to use when Chromium
is set to dark mode.
Using Chromium on Linux so not sure if this is the same for Firefox etc.

### A specific URL where the issue occurs

N/A - Not a website problem.

### Steps to Reproduce

1. In the Chromium url bar goto: chrome://flags/
2. Search for "Force Dark Mode for Web Contents" in search box
3. Set "Force Dark Mode for Web Contents" to either of the following:   

        Default
        Enabled
        Enabled with simple HSL-based inversion 
        Enabled with simple CIELAB-based inversion
        Enabled with simple RGB-based inversion
        Enabled with selective image inversion
        Enabled with selective inversion of non-image elements
        Enabled with selective inversion of everything
        Disabled

4. Relaunch Chromium

### Expected behavior:

When set to a dark options Ublock GUI icons should contrast the background. 
When text is light on dark background, icons should be light too.

### Actual behavior:

   Results on Ublock GUI of "Force Dark Mode for Web Contents" settings are as follows:
   
              Default -       Dark icons & black text on light background.  Works correctly. Same as 'Disabled' I think.
              Enabled -       Dark Icons & white text on dark background.   Does not work.
              HSL -           Dark icons & white text on grey background.   Works better, but not ideal.
              CIELAB -        Dark Icons & white text on dark background.   Does not work.
              RGB -           Dark icons & white text on dark-yellow background. Works better but not ideal.
    selective image -         Dark Icons & white text on dark background.   Does not work.
    selective non-image -     Dark Icons & white text on dark background.   Does not work.
    selective everything -    Dark Icons & white text on dark background.   Does not work.
              Disabled -      Dark icons & black text on light background.  Works correctly.

              
As you can see the GUI has dark icons throughout.
The following is the list of setting when white/light icons would be preferable.

"Force Dark Mode for Web Contents" set to:

    Enabled
    Enabled with simple HSL-based inversion 
    Enabled with simple CIELAB-based inversion
    Enabled with simple RGB-based inversion
    Enabled with selective image inversion
    Enabled with selective inversion of non-image elements
    Enabled with selective inversion of everything

    
### Your environment

* uBlock Origin version:    1.27.10
* Browser Name and version:   Chromium Version 83.0.4103.61 (Official Build) Arch Linux (64-bit)
* Operating System and version:   Manjaro - Linux kernel 5.6.15-1-MANJARO x86_64 GNU/Linux
* Desktop Environment:   KDE Plasma 5.18.5
* KDE Frameworks:  5.70.0
* GTK2 :  gtk2 2.24.32-2 
* GTK3 :  gtk3 1:3.24.20-1

### Additional

I'm happy to copy the icons to a light version but I cannot code so am
unable to help with implementation.
Where are the icons? Can't seem to find them.

Is there a simple bit flip? Or a way to match the text colour?

Thanks in advance.

**Comment by mooselimb** [comment] 2020-06-09 09:13
Here is a screenshot with "Force Dark Mode for Web Contents" flag set to 

  Enabled with selective inversion of everything

![UBlockOrigin-Dark-Mode-20200609_075113](https://user-images.githubusercontent.com/66665059/84129233-9c475600-aa39-11ea-818e-d408bf3d8a05.png)

**Comment by uBlock-user** [comment] 2020-06-09 09:36
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1090

**Closed by uBlock-user** 2020-06-09 09:36 UTC

**Comment by gorhill** [comment] 2020-06-09 11:20
Look like a Chromium issue to me, the icon uses the `fill` property for the color, and so it appears Chromium is not taking into account the `fill` property. Probably best to report this to Chromium devs.
