### ISSUE TITLE
uBO LOG / Buttons & dropdown Not Working in Opera

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uBlock-issues#2163] opened 2022-07-09 00:32 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

I just install opera and ubo in my laptop and all the "bar" and buttons not working... even the "info" mini-icon and the dropdown for select other pages.

example in green:
![qrasqwtqwt](https://user-images.githubusercontent.com/33556647/178084477-52aa0d86-1ee7-42be-9948-909bb8668e05.PNG)

### A specific URL where the issue occurs

uBO Extension

### Steps to Reproduce

1. open uBO Log in any page
2. some features don't work

### Expected behavior

-

### Actual behavior

-

### Configuration

Opera Browser + uBO

**Comment by gwarser** [comment] 2022-07-09 10:00
Logger in separate window does not work correctly if you open the one in sidebar for a moment (only default entries in dropdown, buttons disabled or working only for one tab). Also does not work in other way - separate window -> sidebar. Sidebar can be activated on install, so logger will not work moments after installation (it will disconnect eventually I think - started working for me after third try).

**Comment by gorhill** [comment] 2022-07-09 16:14
> Logger in separate window does not work correctly if you open the one in sidebar for a moment

Yes, by design, there can be only one logger open at any given time. In any case, OP does not mention doing so, he says plainly, open logger, doesn't work, which I can't reproduce, and the amount of useful information provided is pointlessly low. Closing as invalid.

**Closed by gorhill** 2022-07-09 16:14 UTC
Labels: bug
