### ISSUE TITLE
Unify dynamic filtering rule syntax

### ISSUE THREAD

**Issue by farnoy** [uBlockOrigin/uBlock-issues#685] opened 2019-07-30 10:47 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I noticed that the rule syntax: `facebook.com facebook.net image allow` is not permitted in UBO, but works in uMatrix. I'd like to propose adding this functionality to UBO.

Specifically, the valid syntax for UBO rules today seems to be:

| rule type | source | destination | request type | action |
|---|---|---|---|---|
| **Type-based** | `*`<br>_hostname_ | `*`<br>&nbsp; | `*`<br>`image`<br>`inline-script`<br>`1p-script`<br>`3p`<br>`3p-script`<br>`3p-frame` | `block`<br>`noop`<br>`allow` |
| **Hostname-based** | `*`<br>_hostname_ | <br>_hostname_ | <br>`*` | `block`<br>`noop`<br>`allow` |

What I propose:

| rule type | source | destination | request type | action |
|---|---|---|---|---|
| **Unified** | `*`<br>_hostname_ | `*`<br>_hostname_ | `*`<br>`image`<br>`inline-script`<br>`1p-script`<br>`3p`<br>`3p-script`<br>`3p-frame` | `block`<br>`noop`<br>`allow` |

### A specific URL where the issue occurs

None

### Steps to Reproduce

None
### Expected behavior:

None

### Actual behavior:

None

### Your environment

* uBlock Origin version: 1.21.2
* Browser Name and version: Firefox 68.0.1
* Operating System and version: Linux 5.2.3

**Comment by uBlock-user** [comment] 2019-07-30 10:55
sounds like https://github.com/gorhill/uBlock/issues/1038 ?

**Comment by gorhill** [comment] 2019-07-30 10:58
Duplicate of <https://github.com/gorhill/uBlock/issues/1038>.

**Closed by gorhill** 2019-07-30 10:58 UTC
Labels: enhancement

**Comment by gorhill** [comment] 2019-07-30 11:03
The current syntax is the way it is because it matches the UI to set rules in the popup panel. What is proposed here can either not be represented in the popup panel, or lead to absurd rule such as `foo.com bar.com 1p-script block`.

**Comment by farnoy** [comment] 2019-07-30 11:19
Fair enough, I did not consider the example you gave. Is it still true that you don't want to over-complicate the UI? Or are you rejecting this because the syntax I proposed does not make sense?

**Comment by gorhill** [comment] 2019-07-30 11:55
I don't want dynamic filtering to become more complicated than it is now or having to change the UI. 

At the end of the day, requests for feature **must** come with many convincing use real, actual cases (with steps to repro, URLs) in support for those features.
