### ISSUE TITLE
Waiting for extension uBlock Origin on two different machiens

### ISSUE THREAD

**Issue by timthelion** [uBlockOrigin/uBlock-issues#477] opened 2019-03-20 17:56 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Chromium hangs with "Waiting for extension uBlock Origin". Web pages do not load and the extension does not respond when you click on the extension icon. This is happening on two separate debian computers.

### A specific URL where the issue occurs

Everywhere, for example duckduckgo.com

### Steps to Reproduce

1. Install uBlockOrigin
2. Use it for a-while

### Expected behavior:

Ublock origin has worked great for years.

### Actual behavior:
Pages never load and I see "Waiting for extension uBlock Origin"
Reinstalling plugin fixes the issue, but the issue returns after a while.

### Your environment

* uBlock Origin version:  1.18.8
* Browser Name and version: Version 57.0.2987.98 Built on 8.7, running on Debian 9.6 (64-bit)
* Operating System and version: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux 
debian/ stretch

I know that there's not much info here, but I've experienced this on two different debian machines, so I wanted to see if it is happening to anyone else.

**Comment by kulfoon** [comment] 2019-03-20 18:17
https://github.com/uBlockOrigin/uBlock-issues/issues/461

**Comment by uBlock-user** [comment] 2019-03-20 18:37
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/461

**Closed by uBlock-user** 2019-03-20 18:37 UTC
