### ISSUE TITLE
Random JS files were added automatically as filter lists

### ISSUE THREAD

**Issue by CapacitorSet** [uBlockOrigin/uBlock-issues#884] opened 2020-02-05 03:02 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin (well, the latest available on Firefox)
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

While using Firefox, all of a sudden new websites would load incorrectly. I'd see the page with some very basic styling, and no CSS or pictures were loaded.

After some debugging it turns out that three random filter lists had been somehow added - one Google Analytics script, another analytics script from a math website, and an unknown script from the same website:

![Screenshot](https://i.imgur.com/FTfhwdJ.jpg)

(Note that while I browse youmath.it from time to time, it was not open at the time this issue occurred.)

The "filter lists" being JS files, they contained `/*`, which matched and blocked any resource:

![Screenshot](https://i.imgur.com/Yzl1xLP.jpg)

Removing these bogus filter lists let me browse normally again.

### A specific URL where the issue occurs

Not relevant.

### Steps to Reproduce

Can't reproduce.

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox Nightly 74
* Operating System and version: Arch Linux

**Comment by CapacitorSet** [comment] 2020-02-05 03:03
I know that this bug can't be reproduced easily if at all, but I figured I'd report it with my debugging session in case someone else ran into the same issue.

**Comment by gorhill** [comment] 2020-02-05 12:38
The only way to have these entries imported as lists is to expressly import them from the related text area at the bottom of the _"Filter lists"_ pane, or to manually edit the `externalLists` entry in a backup file before importing it.

**Comment by CapacitorSet** [comment] 2020-02-05 13:27
>The only way to have these entries imported as lists is to expressly import them from the related text area at the bottom of the "Filter lists" pane, or to manually edit the externalLists entry in a backup file before importing it.

I figured as much, but there's no way I could possibly have done so myself - much less with the third file, which I don't recognize nor looks like something I'd want to block, or with youmath.it, which I rarely browse. Hence the bug report, hopefully someone else can confirm it.

**Comment by gorhill** [comment] 2020-02-05 13:55
> there's no way I could possibly have done so myself

There is no code to assign external lists other then through the text area or through the backup file, and I never ever saw such weird behavior reported. I have seen people in the past thinking the text area was a place to import filters, they failed to understand it was for filter **lists**.

**Comment by gorhill** [comment] 2020-02-05 14:46
Do you have _AdGuard Base_ filter list enabled? I see the following filter in that list:

    ||youmath.it/plugins/system/CssJsCompress/js.php^

The two other URLs in you screenshots are probably URLs which are also normally getting blocked by uBO with default lists.

**Comment by gorhill** [comment] 2020-02-05 14:48
I want to keep the issue opened despite it being unreproducible -- there have been cases on reddit that uBO would suddenly block too much, I feel this could be related to the issue reported here.

**Comment by CapacitorSet** [comment] 2020-02-05 15:44
>Do you have AdGuard Base filter list enabled?

Curiously enough, I do not, and if I visit youmath.it the script is not blocked.

**Comment by gorhill** [comment] 2020-06-14 19:14
Closing this as there is still nothing actionable since then -- other than user error, I am unable to think of how this could happen, there is just no code path to cause uBO to randomly import URLs as external lists.

**Closed by gorhill** 2020-06-14 19:14 UTC
Labels: unable to reproduce
