### ISSUE TITLE
[feature suggestion] variables in custom-rules

### ISSUE THREAD

**Issue by eladkarako** [uBlockOrigin/uBlock-issues#2169] opened 2022-07-12 15:55 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I've got those 3 rules,  
with a repeating section,  
which I've wandered if I could managed in a one go...

`google.com##:matches-path(/search) div a[href]:has-text(/(istockphoto\.com|freepik\.com|theitbros\.com|droidrant\.com|informer\.com|hamal\.co\.il|b144\.co\.il|rest\.co\.il|easy\.co\.il|booking\.com|medreviews\.co\.il|maariv\.co\.il|indeed\.com|leaan\.co\.il|pool\.org\.il|calcalist\.co\.il|mako\.co\.il|news\.co\.il|homecenter\.co\.il|prosites\.co\.il|nearform\.com|quiznext\.in|quora\.co|devdiscourse\.com|uqora\.com|quorahub\.com|4pda\.ru|a-2-z\.co\.il|alibaba\.|aliexpress\.|amazon\.|amsi\.org\.au|animevietsub\.tv|anstrex\.com|astrateg\.co\.il|baeldung\.com|bimstore\.co|books\.google\.com|brainly\.in|bugzilla\.mozilla\.org|byjus\.com|codepen\.io|cuemath\.com|cyberciti\.biz|danielzrihen\.co\.il|daniweb\.com|digitalocean\.com|digitalvibe\.co\.il|exedb\.com|experts-exchange\.com|facebook\.|fialkov\.co\.il|fiverr\.com|flickr\.com|githubhot\.com|gramhir\.com|icteachers\.co\.uk|inca\.co\.il|instagram\.com|jetbrains\.com|jsfiddle\.net|last\.fm|linkedin\.|linuxconfig\.org|makeuseof\.com|medium\.com|metatube\.com|news\.com|nytimes\.com|pictaram\.com|pinterest\.com|pixwox\.com|plus\.google\.com|prezi\.com|quora\.com|reversim\.com|safaribooksonline\.com|simania\.co\.il|sitelinks\.info|smoove\.io|spiceworks\.com|srch\.co\.il|start-seo\.co\.il|stumbleupon\.com|tabnine\.com|taboola\.com|theguardian\.com|thewindowsclub\.com|toppr\.com|tumblr\.com|tumgir\.com|twitter\.com|upsiteseo\.co\.il|vedantu\.com|w3schools\.com|wattpad\.com)/i):upward(div.ZINbbc,div.Gx5Zad,div.g.tF2Cxc,div.ULSxyf,div.g)`

`google.com##:matches-path(/search) .g:has-text(/(istockphoto\.com|freepik\.com|theitbros\.com|droidrant\.com|informer\.com|hamal\.co\.il|b144\.co\.il|rest\.co\.il|easy\.co\.il|booking\.com|medreviews\.co\.il|maariv\.co\.il|indeed\.com|leaan\.co\.il|pool\.org\.il|calcalist\.co\.il|mako\.co\.il|news\.co\.il|homecenter\.co\.il|prosites\.co\.il|nearform\.com|quiznext\.in|quora\.co|devdiscourse\.com|uqora\.com|quorahub\.com|4pda\.ru|a-2-z\.co\.il|alibaba\.|aliexpress\.|amazon\.|amsi\.org\.au|animevietsub\.tv|anstrex\.com|astrateg\.co\.il|baeldung\.com|bimstore\.co|books\.google\.com|brainly\.in|bugzilla\.mozilla\.org|byjus\.com|codepen\.io|cuemath\.com|cyberciti\.biz|danielzrihen\.co\.il|daniweb\.com|digitalocean\.com|digitalvibe\.co\.il|exedb\.com|experts-exchange\.com|facebook\.|fialkov\.co\.il|fiverr\.com|flickr\.com|githubhot\.com|gramhir\.com|icteachers\.co\.uk|inca\.co\.il|instagram\.com|jetbrains\.com|jsfiddle\.net|last\.fm|linkedin\.|linuxconfig\.org|makeuseof\.com|medium\.com|metatube\.com|news\.com|nytimes\.com|pictaram\.com|pinterest\.com|pixwox\.com|plus\.google\.com|prezi\.com|quora\.com|reversim\.com|safaribooksonline\.com|simania\.co\.il|sitelinks\.info|smoove\.io|spiceworks\.com|srch\.co\.il|start-seo\.co\.il|stumbleupon\.com|tabnine\.com|taboola\.com|theguardian\.com|thewindowsclub\.com|toppr\.com|tumblr\.com|tumgir\.com|twitter\.com|upsiteseo\.co\.il|vedantu\.com|w3schools\.com|wattpad\.com)/i)`

`duckduckgo.com##.result:has-text(/(istockphoto\.com|freepik\.com|droidrant\.com|informer\.com|hamal\.co\.il|b144\.co\.il|rest\.co\.il|easy\.co\.il|booking\.com|medreviews\.co\.il|maariv\.co\.il|indeed\.com|leaan\.co\.il|pool\.org\.il|calcalist\.co\.il|mako\.co\.il|news\.co\.il|homecenter\.co\.il|prosites\.co\.il|nearform\.com|quiznext\.in|devdiscourse\.com|uqora\.com|quorahub\.com|4pda\.ru|a-2-z\.co\.il|alibaba\.|aliexpress\.|amazon\.|amsi\.org\.au|animevietsub\.tv|anstrex\.com|astrateg\.co\.il|baeldung\.com|bimstore\.co|books\.google\.com|brainly\.in|bugzilla\.mozilla\.org|byjus\.com|codepen\.io|cuemath\.com|cyberciti\.biz|danielzrihen\.co\.il|daniweb\.com|digitalocean\.com|digitalvibe\.co\.il|exedb\.com|experts-exchange\.com|facebook\.|fialkov\.co\.il|fiverr\.com|flickr\.com|githubhot\.com|gramhir\.com|icteachers\.co\.uk|inca\.co\.il|instagram\.com|jetbrains\.com|jsfiddle\.net|last\.fm|linkedin\.|linuxconfig\.org|makeuseof\.com|medium\.com|metatube\.com|news\.com|nytimes\.com|pictaram\.com|pinterest\.com|pixwox\.com|plus\.google\.com|prezi\.com|quora\.com|reversim\.com|safaribooksonline\.com|simania\.co\.il|sitelinks\.info|smoove\.io|spiceworks\.com|srch\.co\.il|start-seo\.co\.il|stumbleupon\.com|tabnine\.com|taboola\.com|theguardian\.com|thewindowsclub\.com|toppr\.com|tumblr\.com|tumgir\.com|twitter\.com|upsiteseo\.co\.il|vedantu\.com|w3schools\.com|wattpad\.com)/i)`

I was wondering if there is/  
or may I suggest such feature,  
to help reduce a lot of repeating segments,  
like so:  

```txt
--VAR-regexp-for-crappy-sites=/(istockphoto\.com|freepik\.com|droidrant\.com|informer\.com|hamal\.co\.il|b144\.co\.il|rest\.co\.il|easy\.co\.il|booking\.com|medreviews\.co\.il|maariv\.co\.il|indeed\.com|leaan\.co\.il|pool\.org\.il|calcalist\.co\.il|mako\.co\.il|news\.co\.il|homecenter\.co\.il|prosites\.co\.il|nearform\.com|quiznext\.in|devdiscourse\.com|uqora\.com|quorahub\.com|4pda\.ru|a-2-z\.co\.il|alibaba\.|aliexpress\.|amazon\.|amsi\.org\.au|animevietsub\.tv|anstrex\.com|astrateg\.co\.il|baeldung\.com|bimstore\.co|books\.google\.com|brainly\.in|bugzilla\.mozilla\.org|byjus\.com|codepen\.io|cuemath\.com|cyberciti\.biz|danielzrihen\.co\.il|daniweb\.com|digitalocean\.com|digitalvibe\.co\.il|exedb\.com|experts-exchange\.com|facebook\.|fialkov\.co\.il|fiverr\.com|flickr\.com|githubhot\.com|gramhir\.com|icteachers\.co\.uk|inca\.co\.il|instagram\.com|jetbrains\.com|jsfiddle\.net|last\.fm|linkedin\.|linuxconfig\.org|makeuseof\.com|medium\.com|metatube\.com|news\.com|nytimes\.com|pictaram\.com|pinterest\.com|pixwox\.com|plus\.google\.com|prezi\.com|quora\.com|reversim\.com|safaribooksonline\.com|simania\.co\.il|sitelinks\.info|smoove\.io|spiceworks\.com|srch\.co\.il|start-seo\.co\.il|stumbleupon\.com|tabnine\.com|taboola\.com|theguardian\.com|thewindowsclub\.com|toppr\.com|tumblr\.com|tumgir\.com|twitter\.com|upsiteseo\.co\.il|vedantu\.com|w3schools\.com|wattpad\.com)/i

google.com##:matches-path(/search) div a[href]:has-text(--VAR-regexp-for-crappy-sites):upward(div.ZINbbc,div.Gx5Zad,div.g.tF2Cxc,div.ULSxyf,div.g)`

google.com##:matches-path(/search) .g:has-text(--VAR-regexp-for-crappy-sites)

duckduckgo.com##.result:has-text(--VAR-regexp-for-crappy-sites)

```

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

1. store repeated segment in a variable (similar to what CSS has).
2. easy to maintain, reuse across existing rules.
3. volume of rules reduces, readability increases, easier to maintain. (..profit) 

### Expected behavior

introducing a variable,  
available for the custom rule set.

### Actual behavior

a lot of repeating stuff, which is a pain to maintain.

### uBlock Origin version

1.43.1b3

### Browser name and version

Chromium 105

### Operating System and version

W10

**Comment by gorhill** [comment] 2022-07-12 16:40
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/330>.

**Closed by gorhill** 2022-07-12 16:40 UTC

**Comment by eladkarako** [comment] 2022-07-12 16:55
oh boy! that's an old one, no wonder I didn't find it.. 
anyway, thanks.
