### ISSUE TITLE
Auto-reloading on each blocking change in the panel

### ISSUE THREAD

**Issue by vitorgalvao** [uBlockOrigin/uBlock-issues#672] opened 2019-07-16 13:27 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I use uBlock Origin in Hard Mode, meaning that with every new site I want to unbreak there is a cycle of:

1. Click uBlock Origin’s icon.
2. Disable/enable blocking in a cell.
3. Reload.
4. Repeat until done.

Since this is done one field at a time, it’s a bit cumbersome to repeat so many steps. Would be be possible to have just:

1. Click uBlock Origin’s icon.
2. Disable/enable blocking in a cell. The page auto-reloads and the uBlock Origin panel is kept open (or auto-reopens, if that’s unfeasible).

Even if only auto-reloading is possible without the panel reopening or not closing, it would already speed up my process. I’m fine with this behaviour not being the default, if it’s an option.

### A specific URL where the issue occurs

Not applicable, as it’s a feature request.

### Steps to Reproduce

Not applicable, as it’s a feature request.

### Expected behavior:

Not applicable, as it’s a feature request.

### Actual behavior:

Not applicable, as it’s a feature request.

### Your environment

* uBlock Origin version: 1.20.0
* Browser Name and version: Google Chrome 75.0.3770.100
* Operating System and version: macOS 10.14.5 (18F132)

**Comment by gwarser** [comment] 2019-07-16 14:31
Weird - on Firefox panel stays open after click on reload button, and this button is only few centimeters away.

**Comment by uBlock-user** [comment] 2019-07-16 14:54
> on Firefox panel stays open after click on reload button

Yep, Firefox behaviour by default.

**Comment by gorhill** [comment] 2019-07-21 15:19
The cause of the popup closing on reload is a regression from a very old commit:

https://github.com/gorhill/uBlock/commit/2b60436ecea7eb05d35dae4fb8026694e2a95b8c#diff-d52e64ec0d4dde211713e732342f2ccb

This was added for the sake of Firefox for Android, where it makes sense to automatically switch to the target tab after forcing a reload. The fix is to do this only when using a mobile device.

I won't make the tab load automatically though.

**Comment by gorhill** [comment] 2019-07-21 15:52
> I won't make the tab load automatically though.

However I added the ability to press F5 to force a reload.

**Closed** 2019-07-21 16:03 UTC
Labels: enhancement, fixed

**Comment by mrochaaa** [comment] 2019-08-05 23:55
+1 to add Auto-Reload, when making some change in the panel, but add also an setting to choose if keep or not the panel open. Is just 2 settings, and many find it useful, today need so many clicks, frankly is annoying...  And simple toogle need many clicks. This settings may be for Advanced users only... Why not?

Auto Reload = true
Keep popup open = false

Simple :)
