### ISSUE TITLE
Option to ignore third-party whitelist

### ISSUE THREAD

**Issue by lambic12** [uBlockOrigin/uBlock-issues#1452] opened 2021-01-19 17:57 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Like many people, I'd like to have an advanced option to ignore third-party exception rules, as Nano adblocker had.

I know that it was asked in the past, but I cannot find it on the issue tracker.

I know the usual objections against this feature :
- "if you don't trust lists, don't use them" > I trust them to some extent but I want to use them as a subset for a more restrictive set of rules of my own, which is often broken by exception filters. For example, easylist is good against ads but not against tracking, if you want to forbid tracking, some of your rules will be overriden by easylist exceptions.
- "use $badfilter" > It is really time-consuming to track exceptions and put $badfilter one by one. It's impossible to do this for all the exceptions.
- "use $important" > I do, but it has countereffects, because after that, making an exception of my own, even very partial, is no more possible.
- "use dynamic filtering" > dynamic filtering is not precise at all about the resources. You allow or block a whole domain. Just useful if you want to resolve a problem quickly, but not to elaborate a precise list of your own.

Thank you for studying again this feature request, that lots of people are waiting for.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by uBlock-user** [comment] 2021-01-19 17:59
Duplicate of https://github.com/gorhill/uBlock/issues/3353

**Closed by uBlock-user** 2021-01-19 17:59 UTC

**Comment by gorhill** [comment] 2021-01-19 19:43
It's a duplicate of your **own** previous request: <https://github.com/uBlockOrigin/uBlock-issues/issues/347> -- there is no excuse for doing this.
