### ISSUE TITLE
Change the "Go back" button to "Close" in "Open link in new tab", etc. (hosts list)

### ISSUE THREAD

**Issue by MS-PC** [uBlockOrigin/uBlock-issues#202] opened 2018-09-05 02:39 UTC
I do not know if this could have a solution.

1.- Search something in Google, example: Softonic
2.- Right click on an option ==> "Open link in new tab" or "Open link in new window", etc.
3.- A "list hosts" blocks it
4.- Click on "Go back"

When opening a new tab does not have a previous page loaded, so you can not go back. My suggestion is that the button "Go back" be replaced by "Close", only when previously you have used the options of the context menu "Open link in new tab" or "Open link in new window", etc.

**Comment by uBlock-user** [comment] 2018-09-05 07:36
> Click on "Go back"

There's no go back button, it's Close this Window.

![](https://i.gyazo.com/4c27cf82a70daad202d8de1e948a85fa.png)

**Comment by gorhill** [comment] 2018-09-05 10:50
Please respect the template.

Also, provide better detailed steps-to-reproduce: _"Right click on an option"_ is not enough, you need to state the exact URL which was clicked, and what list blocked it if it's not a default one. Etc.

Like @uBlock-user, I could not reproduce.

**Comment by gwarser** [comment] 2018-09-05 12:51
I can reproduce on Firefox stable and Nightly, uBO dev 1.16.21b4

STR:
- subscribe to "Dan Pollock’s hosts file" or simply add `||softonic.com^` to "My filters"
- search for "Softonic" on google https://www.google.com/search?q=Softonic&ie=utf-8&oe=utf-8&client=firefox-b
- right click on [Download software for Windows - Softonic](https://en.softonic.com/windows) and select "Open Link in New Tab" or new window
- "Go back" button, clicking on it reloads strict blocking page


When I try on this link here on GitHub:  https://en.softonic.com/windows I see "Close this window" button, but nothing happens after I click on it.

**Comment by gorhill** [comment] 2018-09-05 12:55
I can reproduce with @gwarser steps.

It's because that page was loaded as a result of a redirect. So there is a previous entry in the history, and this is what uBO uses to know whether "Go back" or "Close window" is to be used.

**Comment by uBlock-user** [comment] 2018-09-05 12:56
Since `Go back` button didn't appear in Chromium, I assumed it was removed and that the behaviour for all browsers.

**Comment by uBlock-user** [comment] 2018-09-05 12:59
> Consider this by design

So this will not fixed ?

**Comment by gorhill** [comment] 2018-09-05 13:01
No, uBO lookup `window.history.length` and if it's not 0 it uses the "Go back" button.

**Closed** 2018-09-05 13:12 UTC
Labels: Firefox, enhancement, wontfix
