### ISSUE TITLE
Firefox container support

### ISSUE THREAD

**Issue by pcause** [uBlockOrigin/uBlock-issues#1108] opened 2020-06-12 15:26 UTC
It would be helpful to have container support in firefox, where if a page is in a container the ublock settings are just applied to that container and pages in that container.  I Have a google container and while I disable google globally, I could let google be enabled globally in that container.

**Comment by uBlock-user** [comment] 2020-06-12 15:32
Duplicate of https://github.com/gorhill/uBlock/issues/3091

**Closed by uBlock-user** 2020-06-12 15:32 UTC
