### ISSUE TITLE
Inconsistent "My Filters" filtering behaviour

### ISSUE THREAD

**Issue by unicorndreams** [uBlockOrigin/uBlock-issues#216] opened 2018-09-10 10:04 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Inconsistent "My Filters" filtering behaviour

### A specific URL where the issue occurs

https://nicemovie.site/
https://nicemovie.site/nicemovie/7c09Ee8ceXA/south-indian-movies-dubbed-in-hindi-2018
https://imgg-cdn.mgid.com/2933/2933655_492x328.jpg

### Steps to Reproduce

1. Access any video in site: https://nicemovie.site/
(e.g., https://nicemovie.site/nicemovie/7c09Ee8ceXA/south-indian-movies-dubbed-in-hindi-2018, just because it's short, so it won't irk too much).
2. Open any ad JPEG image from nicemovie.site on a new tab (e.g., https://imgg-cdn.mgid.com/2933/2933655_492x328.jpg).
3. Enter a new "My Filters" rule: ||mgid.com*jpg
4. Reload video Page tab.
5. Reload JPEG image tab.
6. Remove the "jpg" or "\*jpg" from the rule: ||mgid.com* or ||mgid.com
7. Reload video tab.
8. Reload JPEG image tab.

### Expected behavior:

After adding the new rule (||mgid.com*jpg), all JPEG images from "mgid.com" should be blocked, so the video Page from nicemovie.site should reload without the ads. The standing alone image from mgid.com should also be blocked, as it matches the same rule. When removing "jpg" or "\*jpg" from the rule (||mgid.com), nothing different should happen, as the ads should already be removed (because all ads on nicemovie.site are JPEG images and removing the "jpg" string from the rule would just instruct uBO to remove everything from mgid.com, not only JPEG images).

### Actual behavior:

The ads on nicemovie.site are correctly blocked after creating the new rule (||mgid.com*jpg), but the stand alone image isn't blocked, being loaded normally, despite matching the same rule. When the "jpg" or "\*jpg" is removed from the rule, the ads are still correctly blocked on the video Page, but, now, the stand alone image from mgid.com is also blocked, as it should have been with the full original rule.

### Your environment

* uBlock Origin version: 1.16.20 (latest)
* Browser Name and version: Firefox 61.0
* Operating System and version: Windows 7 64 bits

**Comment by uBlock-user** [comment] 2018-09-10 10:48
> but the stand alone image isn't blocked, being loaded normally, despite matching the same rule

If you want to block all resources from directly making any connection to that server, use `||mgid.com^`

**Comment by unicorndreams** [comment] 2018-09-10 11:03
Yes, I know ||mgid.com\* would lock everything from mgid.com, but, first, that's not the point of the issue, second, that's not what I want. I want to be able to block specific file types from specific sites, not only when they are third parties, but also direct access (their URL on the address bar). That only works when setting a general rule, like ||mgid.com\*, but not when specifying the type, like ||mgid.com\*jpg (JPEG are blocked when third party, but not when directly accessed). mgid.com is used just as an example. That inconsistent behaviour has plagued uBO since long, but I've always thought it was a problem with my rules (because third party sites are blocked and direct access is only partially blocked, so it took me time to realise I was unable to specify file types or other "keywords").

**Comment by unicorndreams** [comment] 2018-09-10 11:05
What?! Are you kidding me?! You closed my issue without even reading my arguments?!

**Comment by gorhill** [comment] 2018-09-10 11:08
I am surprised at the result, I need to investigate.

**Comment by uBlock-user** [comment] 2018-09-10 11:09
> That inconsistent behaviour has plagued uBO since long,

not an inconsistent behaviour, it has been like this fundamentally since the beginning.

See - https://github.com/gorhill/uBlock/wiki/Strict-blocking

> that's not the point of the issue, second, that's not what I want.

You reported it as bug, this is not a bug, are you suggesting this as a feature request ?

**Comment by gorhill** [comment] 2018-09-10 11:13
Ok never mind, I had forgotten a few details.

This is by design. The thing to keep in mind: strict-blocking does not exist on other blockers, and thus by using filter lists which were first meant for other blockers mean uBO must be careful when strict-blocking. Hence the current behavior.

The current behavior was fine tuned as a result of these issues:

- https://github.com/chrisaljoudi/uBlock/issues/1128
- https://github.com/chrisaljoudi/uBlock/issues/1212

Thus closing as by design.

As @uBlock-user said, if you want to strict-block whole document, use `document` option, this option is not implicit if the filter matches more than just a hostname.

**Comment by uBlock-user** [comment] 2018-09-10 11:13
@gorhill is `||mgid.com*jpg` supposed to enforce strict blocking ?

**Closed by gorhill** 2018-09-10 11:13 UTC
Labels: invalid

**Comment by gorhill** [comment] 2018-09-10 11:15
No, my bad, I had forgotten about details of the code. This happens because of the fix for <https://github.com/uBlock-LLC/uBlock/issues/1212>.

**Comment by unicorndreams** [comment] 2018-09-10 19:33
Thanks for replying! I'll fiddle with the "document" option a little more (I could never make it work, I guess it doesn't do what I expect it to do...)

**Comment by uBlock-user** [comment] 2018-09-11 11:33
Refer to [Static-filter-syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax), that's a place to start.

**Comment by uBlock-user** [comment] 2018-09-16 17:39
Haven't tested, but try `||*.png^$image,document`, that should block direct access and resources altogether.
