### ISSUE TITLE
Restore does not include userFilters anymore

### ISSUE THREAD

**Issue by ygoe** [uBlockOrigin/uBlock-issues#2853] opened 2023-10-06 20:16 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I installed this extension in a new Firefox profile and restored my settings from a file exported from another computer. But my user filters are not restored. They're in the file but ignored on restore. This has worked in the past.

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. Add user filters
2. Export settings
3. Import settings on another computer

### Expected behavior

User filters are imported

### Actual behavior

They're not, the input field remains empty

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Firefox: 118
filterset (summary):
 network: 106784
 cosmetic: 44620
 scriptlet: 18635
 html: 1056
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 35857-92, 7m
  ublock-badware: 7188-0, 7m
  ublock-privacy: 587-0, 7m
  ublock-unbreak: 2179-0, 7m
  ublock-quick-fixes: 176-0, 7m
  easylist: 71567-700, 7m
  easyprivacy: 33211-722, 7m
  urlhaus-1: 11180-0, 7m
  plowe-0: 3717-1, 7m
  DEU-0: 7096-3, 8m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 612 ms
 maxAssetCacheWait: 251 ms
```
</details>

**Comment by gwarser** [comment] 2023-10-07 08:05
Cannot reproduce. Can you share your backup file? Are you mixing `my-ubloc-kstatic-filters_-_*.txt` file with `my-ublock-backup_-_*.txt`?

**Comment by thesobercoder** [comment] 2023-10-09 06:26
@gorhill Facing the same issue as well. Here is my backup file -

```json
{
  "timeStamp": 1696832713577,
  "version": "1.52.2",
  "userSettings": {
    "importedLists": []
  },
  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-quick-fixes",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "urlhaus-1",
    "plowe-0"
  ],
  "hiddenSettings": {},
  "whitelist": [
    "about-scheme",
    "amazon.com",
    "amazon.in",
    "chrome-extension-scheme",
    "chrome-scheme",
    "daily.dev",
    "edge-scheme",
    "github.com",
    "godaddy.com",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme",
  ],
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false",
  "userFilters": ""
}
```

**Comment by gwarser** [comment] 2023-10-09 06:56
@thesobercoder your backup is not valid syntactically, there is extra comma in whitelist array

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/886325/80fdf0d5-32aa-4aca-aba6-5d0f99d75071)

**Comment by thesobercoder** [comment] 2023-10-09 07:27
@gwarser It's funny that the syntax is incorrect because I directly pasted this content from the backup that the extension is created. I know the last comma is not valid as JSON, but that should be handled while exporting. My problem was specifically with whitelists, which have the same issue as the `userFilters`. The issue might lie in how the extension is exporting the JSON.

**Comment by garry-ut99** [comment] 2023-10-09 08:14
I've been unable to reproduce the reported issue, however, I've experienced another issue few times it has happened that when I clicked OK to import the backup, the browser closed itself, there was no crash in about:crashes nor dump file in CrashDumps folder...

**Comment by gorhill** [comment] 2023-10-09 13:29
> here is the correct JSON that I exported, and I'm directly pasting here

I could restore without any issue in both Firefox and Chromium, result:

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 104039
 cosmetic: 39901
 scriptlet: 18734
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 3-0, never
  easylist: 71567-13, now
  easyprivacy: 33222-64, now
  plowe-0: 3718-1065, now
  ublock-badware: 7191-133, now
  ublock-filters: 34985-143, now
  ublock-privacy: 559-6, now
  ublock-quick-fixes: 195-32, now
  ublock-unbreak: 2136-30, now
  urlhaus-1: 10725-0, now
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 925 ms
 maxAssetCacheWait: 27 ms
```

**Comment by thesobercoder** [comment] 2023-10-09 14:31
@gorhill Is there a way to share debug info with you? I tried it now, it still doesn't work for me.

**Comment by gorhill** [comment] 2023-10-09 14:41
Are there any errors reported in uBO's own dev console?

**Comment by thesobercoder** [comment] 2023-10-09 14:49
@gorhill The console from the background.html shows no error/info/debug messages when I do the import.

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/1915249/d3ef1471-9368-4324-879e-07266de46a34)

**Comment by thesobercoder** [comment] 2023-10-09 15:09
@gorhill I will try and debug tonight and let you know what I find. Thanks for pointing me to the correct file(s) to debug.

**Comment by thesobercoder** [comment] 2023-10-10 10:24
@gorhill OK I did some basic debugging and found something strange. The `restoreUserData` function is not all being called when I click the `Restore from file...` button. To double that the debugger is working I placed a breakpoint on the `backupUserData` and when I clicked the `Back up to file...` button, the debugger indeed took me to the breakpoint I placed on the `backupUserData` function. I'm not sure why the breakpoint is not being hit, unless the event handler is somehow deregistered. Please let me know how I can continue debugging this issue.

**Comment by gwarser** [comment] 2023-10-10 14:25
@ygoe is your file renamed to `.json`?

**Comment by ygoe** [comment] 2023-10-12 20:52
Sorry, I was very busy the past few days.

I haven't renamed anything. Export on one PC, copy files as-is, import on other PC.

Am I mixing up something? Dunno, I just used the export and import buttons on the first settings page of the extension. Are there more I have to care about to get a full backup and restore?

**Comment by gwarser** [comment] 2023-10-12 21:11
> I just used the export and import buttons on the first settings page of the extension.

This should work. 

Can you share your backup file? (Or with different settings but with this bug)

**Comment by ygoe** [comment] 2023-10-12 21:38
Here's a file I created like this (with a few array entries removed afterwards). Interestingly, it's a JSON content with a .txt extension.

[ublock-sicherung_2023-10-12_23.34.25.txt](https://github.com/uBlockOrigin/uBlock-issues/files/12887292/ublock-sicherung_2023-10-12_23.34.25.txt)

When I restored this on another computer in a fresh Firefox profile, the content of "my filters" and "exclude rules" (translated from German) were missing, but I can see them in the exported file. So they were not imported from the file. And that time, I haven't touched the file.

**Comment by gwarser** [comment] 2023-10-12 21:54
> it's a JSON content with a .txt extension.

Correct

> When I restored this on another computer in a fresh Firefox profile, the content of "my filters" and "exclude rules" (translated from German) were missing

Works fine here. ("Trusted sites"?)

**Comment by gorhill** [comment] 2023-10-12 23:46
> Here's a file I created like this

Still can't reproduce with your file. If you can reproduce on your side, it would help if you can step in the code [as mentioned above](https://github.com/uBlockOrigin/uBlock-issues/issues/2853#issuecomment-1753125687).

**Comment by gorhill** [comment] 2023-10-19 15:27
In case it's not clear, the fix is in the dev build, i.e. 1.52.3b?, not the current stable version 1.52.2 of uBO.

**Closed** 2023-10-26 00:14 UTC
Labels: enhancement, feedback needed, fixed
