### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT on Google

### ISSUE THREAD

**Issue by dialexg91** [uBlockOrigin/uBlock-issues#1977] opened 2022-02-12 08:11 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

uBlock blocks Google giving ERR_BLOCKED_BY_CLIENT, what's going on??

### A specific URL where the issue occurs

google.com

### Steps to Reproduce

I don't know

### Expected behavior

not show such error

### Actual behavior

ERR_BLOCKED_BY_CLIENT on Google

### uBlock Origin version

1.41.2

### Browser name and version

Kiwi Browser 98

### Operating System and version

Android

**Comment by uBlock-user** [comment] 2022-02-12 08:29
Does it work if you refresh the tab ?

**Comment by Artins90** [comment] 2022-02-12 10:06
I am experiencing the same problem.
It happens only when launching Chrome and landing on google.com as the homepage, the error message goes away in under 1 second.
Subsequent visits to google.com don't show the error message, I think this is indeed due to the suspend network activity functionality.

**Comment by uBlock-user** [comment] 2022-02-12 10:57
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1973

**Closed by uBlock-user** 2022-02-12 10:57 UTC
