### ISSUE TITLE
Popup firewall scrollbar is cropped / doesn't go all the way down

### ISSUE THREAD

**Issue by Prometheos2** [uBlockOrigin/uBlock-issues#3014] opened 2023-12-08 21:51 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I have an issue in the popup UI's firewall section: the scrollbar does not go all the way down (it seems cropped?).

For example, on this website, I have this firewall list: 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/45640841/7fc47be2-892c-4962-9bb2-3e2511bab8ef)
But it's missing the last element, only visible when expanding All (the last sub-element is still missing) or when using filters:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/45640841/d3a240d9-6eba-49e3-8799-d548d890bbc7)

It only seems to happen when the add-on is put on the bookmark bar, the main toolbar seems to work properly: 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/45640841/782542c2-1aba-4b06-98a7-77bebebeaef4)

### A specific URL where the issue occurs.

https://honkai-star-rail.fandom.com/wiki/Trailblazer/Media?file=Honkai-_Star_Rail_Second_Closed_Beta_Trailer_-_Your_Choice_-_Honkai-_Star_Rail

### Steps to Reproduce

1. put the add-on icon on the bookmark bar
2. enable the menu bar
3. open the pop-up
4. (wait until everything is loaded)
5. try to scroll all the way down

### Expected behavior

To be able to scroll all the way down and see all filters

### Actual behavior

I was unable to see and enable the last website (which enables the video viewer)

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 121
filterset (summary):
 network: 296021
 cosmetic: 163009
 scriptlet: 43539
 html: 1328
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2507-1, 15h.37m
  adguard-generic: 80568-7507, 1d.16h.1m
  adguard-spyware-url: 1351-200, 1d.16h.1m
  block-lan: 54-0, 23d.20h.37m
  curben-phishing: 78159-29, 4h.26m
  fanboy-thirdparty_social: 68-0, 3d.20h.38m
  fanboy-cookiemonster: 49130-281, 21h.58m
  fanboy-social: 15962-22, 3d.9h.17m
  ublock-annoyances: 6073-668, 2h.49m
  dpollock-0: 11609-467, 4h.26m
  FRA-0: 28755-374, 1d.16h
  adguard-spyware: 76717-17038, 1d.16h
  [3 lists not shown]: [too many]
 default:
  user-filters: 7-0, never
  ublock-filters: 36702-145, 2h.49m
  ublock-badware: 7557-11, 2h.49m
  ublock-privacy: 924-52, 2h.49m
  ublock-unbreak: 2202-1, 2h.49m
  ublock-quick-fixes: 172-2, 4h.27m
  easylist: 75859-950, 2h.49m
  easyprivacy: 33072-884, 2h.49m
  urlhaus-1: 10190-0, 4h.26m
  plowe-0: 3776-1, 4h.26m
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 6 redacted]
switchRuleset:
 added: [array of 212 redacted]
hostRuleset:
 added: [array of 429 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 largeMediaSize: 200
hiddenSettings: [none]
supportStats:
 allReadyAfter: 9301 ms (selfie)
 maxAssetCacheWait: 4279 ms
```
</details>

**Comment by gorhill** [comment] 2023-12-08 22:08
Unable to reproduce.

> - [x] using a new, unmodified browser profile

Did you really do that step?

**Comment by gorhill** [comment] 2023-12-08 22:17
There is no issue, the requests to `youtube.com` are not always made, so you won't see `youtube.com` in the overview pane regardless of where the icon is located. You can easily see this when opening the popup panel in its own tab (ctl-shift-click the "all" cell):

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/585534/5ed1122a-a4fb-4f40-9049-a6fb0e7a9960)

**Comment by Prometheos2** [comment] 2023-12-08 22:47
> The requests to youtube only occurs when the site shows you the overlay below, which won't be shown to you in subsequent page load once you close the overlay.

The link automatically opens the overlay on my end, so *youtube.com* was automatically requested. (Should I update the steps to reproduce?)
However, I just noticed the problem appears with _wikia-services.com_ when not opening the overlay: depending on where the icon was placed, _uBlock_ either goes all the way down to _wikia-services.com_ or stops at _scorecardresearch.com_

Personal bookmark bar:
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/45640841/78179f98-b739-43cc-aaed-1a3f9fa51d0f)
Main toolbar: 
![image](https://github.com/uBlockOrigin/uBlock-issues/assets/45640841/5e32fe00-b59a-414e-8c22-5ee7a0f4880e)

**Comment by gorhill** [comment] 2023-12-09 01:35
If I can't reproduce, it's not actionable. I did put the icon in the bookmark toolbar and the popup panel was fine -- I was at first mistaken that youtube entry should have been there. The arrow down shows fine. Again:

> Did you really do that step?

Many people customize with Firefox's own settings and this can lead to this. uBO doesn't chose the size of the popup panel, the browser does, and if the browser is not properly sizing the popup panel container, it's being interfered with.

**Comment by Prometheos2** [comment] 2023-12-09 02:01
>> Did you really do that step?
>
> Many people customize with Firefox's own settings and this can lead to this. uBO doesn't chose the size of the popup panel, the browser does, and if the browser is not properly sizing the popup panel container, it's being interfered with.

I did create a new profile, but I misunderstood and thought "unmodified" only referred to modifying the files; sorry about that.
It turns out it is the menu bar; activating it breaks the scroll bar.

**Comment by gorhill** [comment] 2023-12-09 02:44
> out it is the menu bar; activating it breaks the scroll bar

I enabled the menu bar and I am still unable to reproduce the issue.

**Comment by gwarser** [comment] 2023-12-09 11:10
I can reproduce when I set resolution to 1366x768.

**Comment by gorhill** [comment] 2023-12-09 14:48
@gwarser THis cannot be fixed by uBO, uBO is given a viewport to render in by the browser, and that viewport extends beyond the screen. The browser is causing the viewport to extend beyond the screen, it's out of control of uBO. Same as <https://github.com/uBlockOrigin/uBlock-issues/issues/1100>.

**Closed by gorhill** 2023-12-09 14:48 UTC

**Comment by gorhill** [comment] 2023-12-09 15:38
To confirm, using the browser tools, the height of the popup panel container set by the browser is 544px, but the viewport inside that container is 600px, more specifically, the `panelview` is 631px x 544px, then the `stack` element in it is 631px x 600px. These are completely out of uBO's view, 600px just what it's being given.

Maybe there is an opened issue about this somewhere in bugzilla.

**Comment by gwarser** [comment] 2025-01-23 17:00
https://bugzilla.mozilla.org/show_bug.cgi?id=1943386

**Comment by gwarser** [comment] 2025-01-30 22:04
@gorhill can you take a look? https://bugzilla.mozilla.org/show_bug.cgi?id=1943386#c7

**Comment by DimitrisKalaboukas** [comment] 2026-04-20 08:16
@gorhill [SponsorBlock](https://github.com/ajayyy/SponsorBlock)’s popup UI is indeed scrollable, so a uBO-side solution may be in their code.
