### ISSUE TITLE
uBlock crashes Firefox on specific pages

### ISSUE THREAD

**Issue by jamesblonde007** [uBlockOrigin/uBlock-issues#1396] opened 2020-12-13 17:21 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Firefox crashes when opening this site with uBlock activated. De-activating uBlock fixes the issue.

### A specific URL where the issue occurs

`http://mac-torrent-download.net`

### Steps to Reproduce

1. Activate uBlock
2. Open above URL

### Expected behavior:

No crash

### Actual behavior:

Browser crash

### Your environment

* uBlock Origin version: 1.31.0
* Browser Name and version: Firefox 83.0
* Operating System and version: MacOS 10.15.7

**Comment by gorhill** [comment] 2020-12-13 17:28
Duplicate of #1354.

**Closed by gorhill** 2020-12-13 17:28 UTC

**Comment by jamesblonde007** [comment] 2020-12-15 10:43
> Duplicate of #1354.

Hello, how is this a duplicate? The other issue is for Apple Silicon. This issue is for Intel.

**Comment by gorhill** [comment] 2020-12-15 12:42
If your browser crash, report to the browser devs, uBO is HTML/CSS/JS, it's not supposed to crash the browser, the same way a web page is not supposed to crash the browser.
