### ISSUE TITLE
Element picker and zapper nonfunctional on Chrome 57

### ISSUE THREAD

**Issue by nauved** [uBlockOrigin/uBlock-issues#681] opened 2019-07-22 03:49 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Unable to select any items with the element picker or zapper.
All filters were disabled with !
It was working a few days ago and still works fine in Firefox 60.7.1esr (32-bit)

### A specific URL where the issue occurs

mail.yahoo.com - duckduckgo.com - startpage.com - I had to use stylus to get rid of the gunk that reappeared after the latest update.

### Steps to Reproduce

1. Click on ublock origin icon
2. Click on element picker or zapper
3. Nothing is highlighted on the page and nothing can be selected

### Expected behavior:
I was expecting to see elements hi-lighted and dialog box in the RH corner.

### Actual behavior:
The picker and zapper are non-functional

### Your environment
* uBlock Origin version: uBlock Origin v1.21.2
* Browser Name and version: Chromium Version 57.0.2987.98 Built on 8.7, running on Debian (Devuan)
* Operating System and version: Devuan 1.0 Jessie 32 bit fully updated

**Comment by uBlock-user** [comment] 2019-07-22 07:35
Open `My Rules` and look for `no-cosmetic-filtering:`, if present, remove it and try again.

**Comment by gorhill** [comment] 2019-07-22 11:35
> All filters were disabled with !

What does that mean?

Use the logger to find out what uBO is doing -- since you are not using default settings, you probably have custom settings causing this.

**Comment by uBlock-user** [comment] 2019-07-22 13:21
Filters don't get automatically disabled with `!`, either he or someone disabled them, since OP has not responded yet all we can do is speculate.

**Comment by nauved** [comment] 2019-07-22 13:57
> Open `My Rules` and look for `no-cosmetic-filtering:`, if present, remove it and try again.

Good morning.  Finally our of bed but will be busy today with work on the house so possibly not available to respond immediately.  Here is the content of 'My Rules'.  'Disable cosmetic filtering' is also unchecked in Settings.

no-large-media: behind-the-scene false
no-remote-fonts: * true
no-scripting: behind-the-scene false
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop

**Comment by gorhill** [comment] 2019-07-22 14:01
Since we can't reproduce any issue here with the element picker, you will have to go through the entries you left un-checked in the template.

**Comment by nauved** [comment] 2019-07-22 14:03
> > All filters were disabled with !
> 
> What does that mean?
> 

When I started to investigate, the first place I looked was "My Rules".  Every line was preceded with " ! " .  I manually removed every one.  It looks like those rules originated from using the 'element' picker over many months.

> Use the logger to find out what uBO is doing -- since you are not using default settings, you probably have custom settings/filters causing this.

I will do this but probably not today.

**Comment by uBlock-user** [comment] 2019-07-22 14:05
Did you try testing on default settings yet ?

**Comment by nauved** [comment] 2019-07-22 14:15
> Did you try testing on default settings yet ?

I have not.  I assume that would wipe everything in My Rules so I will need to backup so I can rebuild.  I have been very cautious about what I touch in uBO because it is so powerful.  My changes have been mostly cosmetic filtering.  But I won't rule out that I inadvertently did something stupid.  Even a stray mouse click could do something if not paying attention.  I am old - 77 today - and have learned to be very methodical in how I approach things

The picker and zapper are still non-functional on Chromium this morning.  :(

**Comment by uBlock-user** [comment] 2019-07-22 14:18
You can take the backup via Settings tab located in Dashboard.

**Comment by nauved** [comment] 2019-07-22 14:22
> Since we can't reproduce any issue here with the element picker, you will have to go through the entries you left un-checked in the template.

Not quite sure what/where you are suggesting I do.

Thanks to all for getting on this.  I am crippled without the element picker , , , the web is such an ugly place these days.

**Comment by nauved** [comment] 2019-07-22 14:23
> You can take the backup via Settings tab located in Dashboard.

Thanks!  Will report when I crawl out from under a day of chaos in my personal environment.

**Comment by uBlock-user** [comment] 2019-07-22 14:24
> Not quite sure what/where you are suggesting I do.

Try to reproduce when only uBO is enabled, all other extensions disabled, then try again with uBO on default settings which I already suggested before and then try with a new Chromium profile.

**Comment by gorhill** [comment] 2019-07-22 14:26
You can create a new profile in Chromium so that you do not have to change your current one, see <https://www.ghacks.net/2016/03/26/use-multiple-chrome-profiles/>.

Once the new profile is created, select it and add latest uBO to it and see if you still suffer the issue. This will tell us whether the issue is with your current profile.

**Comment by nauved** [comment] 2019-07-22 14:27
> > Not quite sure what/where you are suggesting I do.
> 
> Try to reproduce when only uBO is enabled, all other extensions disabled, then try again with uBO on default settings which I already suggested before and then try with a new Chromium profile.

I will have to figure out how/where to do each one of those actions so it's going to take some time.  Please be patient.

Oh, thanks, gorhill, for pointing me in the right direction.

**Comment by uBlock-user** [comment] 2019-07-22 14:28
Just do what gorhill suggested then, so that it's easier to recognise the cause.

**Comment by nauved** [comment] 2019-07-22 19:11
This is what my chromium settings page looks like:
![settings](https://user-images.githubusercontent.com/35517371/61656532-96604f00-ac86-11e9-8489-8f92bf13e90e.png)

I am not going to sign into sync because I have no need for it and in any case, certainly would never allow those "hooks" into my communications. .

The link you sent me to sees me as a different user than when I start this issue but everything else is the same - bookmarks, extensions etc.  What am I missing.  Maybe simplicity?

I fired up a Devuan ascii VM and installed uBlock Origin 1.21.4 on Chromium 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9/Devuan 2 (32-bit) and it's working as expected.

Maybe I should backup and reinstall uBO on jessie where it's malfunctioning?

**Comment by nauved** [comment] 2019-07-22 20:31
Don't know why you closed this.  I just backed up everything.  Deleted uBlock Origin 1.21.4, reinstalled and it's still non-functional.  In fact it's worse.  I have not altered any settings and when I click on the tootlbar icon, the dropdown is grayed out and there is no option for the element picker or zapper.  When I click to activate, the "on" symbol turns blue but as soon as I move the cursor, it turns gray again. 
![grayed-out](https://user-images.githubusercontent.com/35517371/61663149-90259f00-ac95-11e9-996a-ebe5abfe4527.png)

**Comment by uBlock-user** [comment] 2019-07-22 20:47
because you said it works on new Chromium profile -- 

>  installed uBlock Origin 1.21.4 on Chromium 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9/Devuan 2 (32-bit) and it's working as expected.

**Comment by uBlock-user** [comment] 2019-07-22 20:50
Starting to think it's a compatibility issue with Chromium 57.

**Comment by nauved** [comment] 2019-07-22 20:55
> Starting to think it's a compatibility issue with Chromium 57.
Thank you!  I agree.  Is it possible downgrade and pin to a previous version?

**Comment by uBlock-user** [comment] 2019-07-22 21:00
Open the console via F12 and grab a screenshot of any errors/warnings. Then browse to `chrome://extensions/` and click on background.html on the uBlock Origin tile and grab another screenshot screenshots of any errors/warnings, post both screenshots here.

**Comment by gorhill** [comment] 2019-07-22 21:02
> Then browse to `chrome://extensions/` and click on `background.html` on the uBlock Origin tile

To be clear, "Developer mode" needs to be enable first in `chrome://extensions/`.

**Comment by uBlock-user** [comment] 2019-07-22 21:03
True, I forgot to add that.

**Comment by uBlock-user** [comment] 2019-07-22 21:12
@gorhill I reproduced it on v57. Extension console reports these errors --

![](https://i.gyazo.com/d7ce6c5c5b0c6d9452d86f7cffed5622.png)

**Comment by gorhill** [comment] 2019-07-22 21:19
Ok, I mistakenly used trailing commas in argument lists of Array.push() and Array.unshift(). I would have expected JSHint to catch this, I didn't even know this was syntactically correct, but [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Function_calls) it says it's accepted syntax, but this became supported in Chromium 58 only.

**Comment by nauved** [comment] 2019-07-22 21:31
Sorry.  Been afk for a while and can't stay long.

Thank you for listening and identifying the problem before I could get to it.  When it's corrected, I assume an update will happen automatically.  Then I can reinstate my filters and settings and will be able to do my work without cringing at the abomination that the web has become.  uBO is an AMAZING tool!!  Much appreciated.

**Comment by gorhill** [comment] 2019-07-22 21:37
Would you be willing to try the dev build of uBO? The code reported in the dev console is easy to fix, however now I worry if fixing this would uncover more such cases elsewhere -- I should publish a stable release only when I am sure uBO executes fine in Chromium 57 with the fixes.

**Comment by nauved** [comment] 2019-07-22 21:40
Sure.  It can't be more broken than it is now.  Might need some spoon-feeding though . . .

**Comment by nauved** [comment] 2019-07-22 21:41
I see you've patched it already.  But I have no idea how to get that into where it needs to go.

**Comment by gorhill** [comment] 2019-07-22 21:42
I will tell you when the dev build is available in Chrome store.

**Comment by nauved** [comment] 2019-07-22 21:43
Great!  Thanks.  I'm going off to that cup of tea that's steeped.  bbiab

**Comment by gorhill** [comment] 2019-07-22 22:17
The development build of uBO is available at:
https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii

Please see if this version works all fine.

**Comment by nauved** [comment] 2019-07-22 22:22
OK.  Checking it now.

**Comment by nauved** [comment] 2019-07-22 22:28
The picker and zapper functions are now visible as is the blue but they are non-functional.  After clicking, nothing is activated on the page to select.  Just a normal cursor.

**Comment by uBlock-user** [comment] 2019-07-22 23:08
After the update, I can no longer reproduce. Working as expected.

![](https://i.gyazo.com/46db920a98bcf4b8a99ac3bd23bbf0f6.png)

![](https://i.gyazo.com/6ad0f42fc1969f60c33577c67bc9d08f.png)

Tested on 57.0.2987.133 (64-bit)

**Comment by gorhill** [comment] 2019-07-22 23:12
I could download a Chromium 57 following [these instructions](https://superuser.com/questions/920523/where-can-i-download-old-stable-builds-of-chromium-from), and I confirm that all worked fine on my side also.

**Comment by uBlock-user** [comment] 2019-07-22 23:15
@nauved Yours is not the stable build of v57, so upgrading to 57.0.2987.133 should fix it.

**Comment by gorhill** [comment] 2019-07-22 23:18
The version I tested is  57.0.2987.0 and it worked fine.

**Closed** 2019-07-22 23:21 UTC
Labels: Chromium, external, fixed

**Comment by nauved** [comment] 2019-07-22 23:25
Hahaha!  User error!!  I missed that there were 2 uBO icons and I had clicked the old one.  The dev build works fine.  Thanks so much for fixing this.  You guys ROCK!!

**Comment by gorhill** [comment] 2019-07-22 23:30
I will release an emergency fix in 1.21.6.
