### ISSUE TITLE
Fanboy’s Annoyance subscription for ABP, not specifically for uBO

### ISSUE THREAD

**Issue by PhoenixIndigo** [uBlockOrigin/uBlock-issues#2222] opened 2022-08-19 18:28 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

In the list of irritating elements, the version of the Fanboy's Annoyance subscription for [ABP](https://secure.fanboy.co.nz/fanboy-annoyance.txt), and not for [uBO](https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt). Although on the site https://www.fanboy.co.nz/ there is a version for [uBO](https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt): https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt

### A specific URL where the issue occurs

moz-extension://7d4c3759-8669-45bb-b7f8-250eb5401a14/dashboard.html#3p-filters.html

### Steps to Reproduce

1. In the settings of the filter lists, the fanboy's Annoyance list for ABP, and not for uBO.

### Expected behavior

Subscription for uBO

### Actual behavior

Subscription for ABP

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 156456
  cosmetic: 265466
  scriptlet: 39780
  html: 751
listset (total-discarded, last updated): 
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31282-76, 4h.24m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1492-402, never
    https://filters.adtidy.org/extension/ublock/filters/1.txt: 30412-389, 4h.24m
    https://secure.fanboy.co.nz/enhancedstats.txt: 2996-10, 4h.24m
    https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91342-36555, 4h.24m
    https://shorturl.at/cfqKV: 12-0, 4h.24m
    adguard-generic: 67063-5704, 4h.24m
    adguard-mobile: 8154-150, 4h.24m
    adguard-spyware: 26476-1118, 4h.24m
    adguard-annoyance: 56503-1871, 4h.24m
    adguard-social: 18234-2208, never
    ublock-annoyances: 4537-8, 4h.24m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33225-236, 4h.24m
    ublock-badware: 4247-0, 4h.24m
    ublock-privacy: 247-0, 4h.24m
    ublock-abuse: 76-0, 4h.24m
    ublock-unbreak: 1842-1, 4h.24m
    ublock-quick-fixes: 417-0, 4h.24m
    easylist: 69596-650, 4h.24m
    easyprivacy: 27390-9898, 4h.24m
    urlhaus-1: 4622-0, 4h.24m
    plowe-0: 3632-4, 4h.24m
    RUS-0: 42062-3896, 4h.24m
filterset (user): [empty]
trustedset: 
  removed: 
    about-scheme
modifiedUserSettings: 
  cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3155 ms
  maxAssetCacheWait: 2046 ms
```
</details>

**Comment by krystian3w** [comment] 2022-08-19 18:47
Liar: https://secure.fanboy.co.nz/fanboy-annoyance.txt has recommended:


```
! Include ubO specific
!#include fanboy_annoyance_specific_uBO.txt
```

**Comment by krystian3w** [comment] 2022-08-19 18:48
Duplicate of #1574

**Comment by krystian3w** [comment] 2022-08-19 18:59
Liar: https://secure.fanboy.co.nz/fanboy-annoyance.txt has recommended:


```
! Include ubO specific
!#include fanboy_annoyance_specific_uBO.txt
```

**Comment by krystian3w** [comment] 2022-08-19 19:08
Lier: https://secure.fanboy.co.nz/fanboy-annoyance.txt has recommended:


```
! Include ubO specific
!#include fanboy_annoyance_specific_uBO.txt
```

**Closed** 2022-08-19 19:29 UTC
Labels: invalid
