### ISSUE TITLE
DNS resolved locally when using a proxy via Firefox Multi-Account Containers

### ISSUE THREAD

**Issue by lxgr** [uBlockOrigin/uBlock-issues#2574] opened 2023-04-01 21:22 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This seems to be a variant of https://github.com/uBlockOrigin/uBlock-issues/issues/911:

When using both uBlock and [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) (technically a third-party addon, but it's only the configuration UI for the native "Containers" functionality), the proxy detection from https://github.com/gorhill/uBlock/commit/3f7ece94691f048377512990a38c0317820bf77f isn't working correctly.

Is there any way that uBlock can detect this type of proxying in a different way?

### A specific URL where the issue occurs.

- https://browserleaks.com/ip

### Steps to Reproduce

1. Install uBlock
2. Activate Firefox MUC from the settings (this will prompt installing the Container management extension), create a container and configure it to use a SOCKS 5 proxy. (A HTTP proxy might work as well, but I haven't tried that.)
3. Enable a packet trace (tcpdump, Wireshark, any application-level firewall etc.)
4. Visit any website in the container.

Alternatively, directly visit something like https://browserleaks.com/ip and you can observe a DNS leak directly, assuming the proxy host uses a distinguishable DNS server.

### Expected behavior

Any DNS requests will go only through the proxy.

On https://browserleaks.com/ip, only the proxy host's DNS will be visible under "DNS leak test".

### Actual behavior

In the packet tracer, you can see local DNS requests not passing through the SOCKS connection.

On https://browserleaks.com/ip, you can see both the local and proxy DNS resolver.

### uBO version

1.48.2

### Browser name and version

Firefox 111.0.1

### Operating System and version

MacOS 13.3

**Comment by gwarser** [comment] 2023-04-02 12:05
Does it stop leaking if you turn off "Uncloak canonical names"?

**Comment by gwarser** [comment] 2023-04-02 15:55
This is still counts as "extension-based proxy service", so:

>Important note when using extension-based proxy service: Extension-based proxy services usually are performed on the fly through a [browser API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest). In such a case, uBO's DNS queries to uncloak canonical names will NOT be caught and proxied by an extension-based proxy service. So you may want to disable this setting when using an extension-based proxy service.

https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#uncloak-canonical-names

**Comment by gwarser** [comment] 2023-04-02 15:59
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1743

![image](https://user-images.githubusercontent.com/886325/229364490-391ddc27-1732-425d-950b-14417a3343e3.png)

**Closed by gwarser** 2023-04-02 15:59 UTC

**Comment by lxgr** [comment] 2023-04-02 19:23
> Does it stop leaking if you turn off "Uncloak canonical names"?

It does!

And I do see the point regarding this being an "extension-based proxy", although to my understanding the extension is only used for configuring their behavior, with the actual functionality being provided by a native browser API: https://hacks.mozilla.org/2017/10/containers-for-add-on-developers/

That said, I'm not sure if that native API offers a way for extensions to be proxied in the same way, per-site, as the tab content, so this might not be possible to do anyway. (My understanding is that this is what is preventing "proxied CNAME uncloaking" from being possible with normal extensions.)

**Comment by gorhill** [comment] 2023-04-03 14:46
The [proxy detection code path](https://github.com/gorhill/uBlock/blob/1.48.4/platform/firefox/vapi-background-ext.js#L111-L127) is taken only for Firefox 80 and earlier, due to <https://bugzilla.mozilla.org/show_bug.cgi?id=1618271>, which was DNS leakage affecting browser- or system-wide proxy settings. Once that issue was fixed in Firefox, there was no point for the special code path.

An issue still exists though with extension-based proxying, as uBO is unable to determine whether the proxying is browser-/system-wide, or extension-based (in which case the proxying can be per-tab). So the chosen solution in this case is to warn in the documentation that using extension-based proxying can cause DNS leaks. Ideally uBO would be able to know whether the proxying is local or global, and if local then skip uncloaking CNAME, but it's not information available to uBO. It would have to be a per-network request property.

**Comment by lxgr** [comment] 2023-04-04 00:31
That makes sense. Appreciate the answer, thank you!
