### ISSUE TITLE
:: before and :: after

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uBlock-issues#387] opened 2019-01-20 09:43 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The "create" button is not active when I want to create a filter.

### A specific URL where the issue occurs

[Go to](https://www.thefreedictionary.com/aglet)

### Steps to Reproduce

1. Open the Elements panel
2. Select an 'Thesaurus'(icon "new!")
3. Select an item a::before "new!" icon

### Expected behavior:

Why can not select an item and block it if uBO understands what I want.

![default](https://user-images.githubusercontent.com/28482376/51437491-cfa00e00-1ca7-11e9-9a8f-8dd8a9842980.png)

![1](https://user-images.githubusercontent.com/28482376/51437502-e0e91a80-1ca7-11e9-98b7-b645f5d8efc9.png)

### Your environment

* uBlock Origin version: 1.17.7rc1
* Browser Name and version: Opera|Beta
* Operating System and version: Windows 7 Pro x64

P.S.
Sorry for my English...

**Comment by uBlock-user** [comment] 2019-01-20 10:01
Duplicate of https://github.com/gorhill/uBlock/issues/2515

**Closed by uBlock-user** 2019-01-20 10:01 UTC

**Comment by krystian3w** [comment] 2019-01-20 21:45
Works only in filter list on my filters panel.
