### ISSUE TITLE
`Esc` can't close the popup dialog on the `Logger`

### ISSUE THREAD

**Issue by dnknn** [uBlockOrigin/uBlock-issues#1170] opened 2020-07-22 02:19 UTC
> Yes, repeat with #596 , @Conder000  posted in May 2019, 
because a whole year has passed and it has **not yet** been realized.
So, let me reinforce this question so that I can better understand its meaning.👇

### Expected behavior⠅ 👆  &emsp;&emsp;Actual behavior⠅ Nothing happens.

----

![Esc](https://user-images.githubusercontent.com/10995302/88125321-a1cfb880-cc01-11ea-9d46-cebd29edbab6.png) <kbd>Esc</kbd> is 🌌**global** common criteria, such as closing dialogs. 
> Compared to mouse clicking, `Esc` will be **very very very easy/fast/relaxed**.

&emsp;
👁seeing gif 👇
![esc](https://user-images.githubusercontent.com/10995302/88123769-32a49500-cbfe-11ea-822c-75e8af7dea72.gif)

**Comment by gwarser** [comment] 2020-07-22 06:43
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/596

**Closed by gwarser** 2020-07-22 06:43 UTC
