### ISSUE TITLE
active rule count for each active filter.

### ISSUE THREAD

**Issue by raingart** [uBlockOrigin/uBlock-issues#261] opened 2018-10-08 16:19 UTC
I want to ask whether it is possible to implement an active rule counter for each active filter.
I (and perhaps others) would like to see the effectiveness of different filters not only for a specific site, but for example for a certain period of time.
To find the minimum effective filter list. And exclusion for example, overlapping rules.

Simply, most users somehow visit a small list of sites. And probably there isn’t much sense to pull the filter out of the ~ 50,000 rules for several sites that appeared on the google request list.

I hope I clearly explained. Just a digital counter of active rules for site/s, divided into specific filters. For example:
-site-name:
-- filter_name_1.txt: 10-rules actived
-- filter_name_2.txt: 6-rules actived
-- filter_name_3.txt: 1-rules actived

**Comment by gwarser** [comment] 2018-10-08 18:02
Hmmm. Filter list level statistics. More limited than https://github.com/uBlock-LLC/uBlock/issues/1316 and https://github.com/gorhill/uBlock/issues/983
It is still unlikely to happen.

**Comment by gorhill** [comment] 2018-10-08 18:10
Duplicate of <https://github.com/gorhill/uBlock/issues/1353>.

**Closed by gorhill** 2018-10-08 18:10 UTC
Labels: duplicate, enhancement
