### ISSUE TITLE
Controls API

### ISSUE THREAD

**Issue by mrochaaa** [uBlockOrigin/uBlock-issues#691] opened 2019-08-05 21:58 UTC
Need add API, I say an API, to toggle local javascript, global images, cosmetic filter etc. For instance to use Foxy Gestures or Shorkeys addons with custom scripts. The "API" receiver can be optional setting

The other addon no need see what ublock is doing, the other addon need just toogle "Javascript on this site" or toggle "cosmetic filter on this site" this is quite possible just need an little ublock api. Sorry but uBO admins is closing very fast valid suggestions.

Is not possible an "API"?

https://github.com/marklieberman/foxygestures/issues/299

**Comment by gwarser** [comment] 2019-08-05 22:13
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/690

**Closed by gwarser** 2019-08-05 22:13 UTC

**Comment by uBlock-user** [comment] 2019-08-05 22:21
Declined by gorhill before - https://github.com/gorhill/uBlock/issues/3352#issuecomment-371645748
