### ISSUE TITLE
Improve/refine syntax highlighter

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1134] opened 2020-07-01 12:11 UTC
Instead of having countless issues opened for every single improvements/refining that could be brought to the syntax highlighter, here is one meta issue to handle them all. I will list all the actionable items in the top comment. Feel free to report un-handled cases or suggest more refinements.

To do:
- [x] Add a filter list which purpose is to validate the static filtering parser
    - Done:
        - `https://raw.githubusercontent.com/gorhill/uBlock/master/docs/tests/static-filtering-parser-checklist.txt`
        - Subscribe to it and disable it after the list is imported, then use asset viewer to see the result.
- [x] `*$xhr,empty` should be reported as valid
- The following redirect rules should be reported as invalid:
    - [x] `*$beacon,redirect-rule=empty`
    - [x] `*$ping,redirect-rule=empty`
    - [x] `*$websocket,redirect-rule=empty`
- [x] Detect invalid `!#` directives
    - [x] Support auto-completion for valid directives
- [ ] Detect unmatched `!#if`-`!#endif` directives
- [ ] Handle line continuation -- I need to read and wrap my mind around [CodeMirror's state object](https://codemirror.net/doc/manual.html#modeapi)
- [ ] Detect and fix regex-based filters starting with `/.*`: they are inefficient and the leading `.*` accomplishes nothing.
- [ ] Ambiguous option separator, see <https://github.com/uBlockOrigin/uBlock-issues/issues/1134#issuecomment-717797011>.

Nice to have:
- [ ] Buttons to navigate to next/prev problematic filter in asset viewer and _"My filters_
- [ ] Warn in gutter about untokenizable static network filters
- [x] Create clickable links for URLs present in comments
    - Implemented as follow: double clicking the URL will select whole URL, at which point you can use your browser's "Open in new tab" feature on the selection.
- [x] Code folding ability:
    - [x] `!#if ...` / `!#endif` blocks
    - [x] `!#include` blocks

**Comment by Yuki2718** [comment] 2020-07-02 11:26
`Warn in gutter about untokenizable static network filters`
This will be huge plus!

**Comment by gwarser** [comment] 2020-07-11 20:11
This is invalid now: 

   $all,~document

https://github.com/easylist/easylist/issues/5621#issuecomment-657119424

**Comment by gorhill** [comment] 2020-07-12 14:35
I will fix this asap. However I would like to understand the purpose of that `/adguard.` filter in EasyList. Someone knows?

**Comment by krystian3w** [comment] 2020-07-12 14:46
Maybe some ad engine have name "`adguard`...".

**Comment by Yuki2718** [comment] 2020-07-12 16:05
> I will fix this asap. However I would like to understand the purpose of that `/adguard.` filter in EasyList. Someone knows?

Apparently came from the Fanboy's list so @ryanbr would know. Clearly it has nothing to do with AdGuard.
https://github.com/easylist/easylist/commit/648b822ef4719f9e1b92c5a6cfa7b2648cfdac5f

**Comment by gwarser** [comment] 2020-07-12 16:41
This look like first occurrence: https://github.com/ryanbr/fanboy-adblock/commit/d51ac922b8efe25d9619f6443e1fff04e96cc219

**Comment by gorhill** [comment] 2020-07-12 16:51
If I am getting this right, that `/adguard.` filter has always been rejected by uBO, since it does not use the `all` property, `~document` can't be used on its own.

I am trying to assess whether I should publish an emergebcy fix for the `all,~document` regression.

**Comment by gwarser** [comment] 2020-07-12 17:51
`~document` was added recently https://github.com/easylist/easylist/commit/24784f0f041210b22732ed9e2fd01c7a91ded0db

**Comment by gorhill** [comment] 2020-07-12 18:57
> This is puzzling: easylist/easylist#5286

Yeah, `/adguard.` on its own would never cause strict-blocking to kick in, so it's unclear what the original issue was.

 The other cases seems to be about not blocking 1st-party secondary resources without wholly disabling filterin -- so probably they are targeting ABP specifically.

**Comment by gwarser** [comment] 2020-07-12 19:34
> Yeah, `/adguard.` on its own would never cause strict-blocking to kick in, so it's unclear what the original issue was.

This was fixed after https://github.com/gorhill/uBlock/commit/41636c59fb4208544b4bb23a5ac6273399cab625 and I think it was fixed very recently in legacy builds.

**Comment by gwarser** [comment] 2020-07-18 14:22
Are filters with errors actually dropped? Because:

>My filters 1 used out of 1

    ||testwa-blokada.eu.example^$script,domain=gameplanet.onet.pl/gry-online/

![image](https://user-images.githubusercontent.com/886325/87854505-cdf1ed80-c912-11ea-8318-18e94d687348.png)

**Comment by gorhill** [comment] 2020-07-18 14:40
That one is not dropped but on the other hand it will never match, since no hostname will ever match `gameplanet.onet.pl/gry-online/`.

I don't think uBO should drop whole filter because one `domain=` value is invalid, for example:

    ||testwa-blokada.eu.example^$script,domain=gameplanet.onet.pl/gry-online/|example.com

Surely we still want to enforce the filter on `example.com` despite that `gameplanet.onet.pl/gry-online/` is not a valid domain.

This is why I chose to treat invalid `domain=` values as soft error, i.e. the filter will not be dropped, and neither the value (or else that would cause the filter to become broader). It gets complicated with negated invalid hostname though...

**Comment by gwarser** [comment] 2020-07-26 10:47
Turns out some people imported uMatrix ruleset recipes as filter list in uBO https://www.reddit.com/r/uBlockOrigin/comments/hy3nsy/rulesets_for_english_websites_breaking_youtube/

**Comment by gorhill** [comment] 2020-07-26 11:56
> `randomwebsite.org/* $inline-script`

That will be taken care with <https://github.com/uBlockOrigin/uBlock-issues/issues/1118>.

**Comment by jspenguin2017** [comment] 2020-08-24 23:46
Here's a suggestion for the filter viewer/editor, although not exactly related to syntax highlighting: 

When double-clicking on a domain name, the whole domain should be selected, instead of just the part that was clicked on. 

Use cases: 
- Quickly select and copy domain
- Quickly select and search domain (double-click, then `Ctrl+F`)

---

Current behavior: 
![image](https://user-images.githubusercontent.com/7283682/91106868-0df27180-e631-11ea-8f49-99a82ebbdf85.png)

Suggested behavior: 
![image](https://user-images.githubusercontent.com/7283682/91106888-1f3b7e00-e631-11ea-831c-9c56340113d5.png)

---

Also when double-clicking on the suffix of a cosmetic filter, it should select the entire suffix (the entire CSS selector). Although I'm not sure if this is easy to implement.

**Comment by jspenguin2017** [comment] 2020-09-16 03:47
It looks like IPv6 addresses are marked as invalid inside `$domain` option, is this intended? The rule is compiled, but I haven't tested whether it actually works. 
![image](https://user-images.githubusercontent.com/7283682/93289474-ab0d7980-f79b-11ea-937a-73649a98823d.png)

**Comment by gwarser** [comment] 2020-10-28 09:05
![image](https://user-images.githubusercontent.com/886325/97415130-20c14500-1905-11eb-8914-2f27ff1fd9ce.png)

    ||video-weaver..hls.ttvnw.net/v/playlist/.m3u8$replace=/#EXT-X-DATERANGE:ID="stitched-ad[\s\S](#EXT-X-PROGRAM-DATE-TIME)(?![\s\S]?#EXTINF:\d.\d+\,live)[\s\S]|(#EXT-X-DATERANGE:ID="stitched-ad[\s\S]?(#EXT-X-PROGRAM-DATE-TIME)([\s\S]?(#EXTINF:\d.\d+\,live)))/\$5/

**Closed** 2022-11-19 18:00 UTC
Labels: enhancement, TODO

**Comment by krystian3w** [comment] 2022-11-19 21:56
https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-position

https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset

**Comment by gwarser** [comment] 2023-09-23 09:36
Removed?

**Comment by gwarser** [comment] 2023-09-23 10:48
This is not a bug, because it still works.

But if you think it should be changed, then this deserves its own enhancement bug, because now injectable resources are detected by the `.js` suffix.

**Comment by garry-ut99** [comment] 2024-09-03 07:39
[Improve extraction of tokens from regex-based filters](https://github.com/gorhill/uBlock/commit/426395aa0373249cda1f2ca4bb69b4f7a5f33722) - worth to mention also about this commit, as a part of it is related to **untokenizable regex syntax highlighting** (and it doesn't contain any reference to this thread, nor any key words in the title, like: syntax, highlight, linter).

**Comment by garry-ut99** [comment] 2024-10-25 08:09
>  * [ ]  Handle line continuation -- I need to read and wrap my mind around [CodeMirror's state object](https://codemirror.net/doc/manual.html#modeapi)

> [703c525](https://github.com/gorhill/uBlock/commit/703c525b01aa3fb9dab94d6a9918a0a69c6d18da)  ==> [ca80d28](https://github.com/gorhill/uBlock/commit/ca80d2826bfd92a3081f20da8ba60138509a183b) ==> [051cb27](https://github.com/gorhill/uBlock/commit/051cb27f9b7a036b3da9b7d936adbc7e31e232db) ==> [01b1ed9](https://github.com/gorhill/uBlock/commit/01b1ed9a982965378d732ab0cb4bcd68727fe910)

Line continuation support works fine, but highlighting is still not fixed, a filter is highlighted as invalid, despite it is valid and works fine when visiting site:

```adb
onet.pl## \
    body
```
![img](https://github.com/user-attachments/assets/e208e787-43e3-4cc2-bed0-9f74ffd06f57)

**Comment by SomeNameDee** [comment] 2025-03-20 17:02
Seconding the line continuation bug:
Filters using the line continuation syntax (line ending with "` \`") will still process correctly, but all the associated lines will be fully highlighted as errors.

**Comment by freezer2022** [comment] 2026-03-07 12:29
### Issue 1: Content obstructed (and therefore the space stolen) by a virtual keyboard:

On Mobile, In Filter list _asset-viewer_ and in _My Filters_:
- after typing  a search phrase and then pressing either a _find next_ or a _find previous_ button, the virtual keyboard is not being hidden
- even after manually hiding the virtual keyboard, and then pressing either a _find next_ or a _find previous_ button, the virtual keyboard is still being restored
- it can be reproduced on different devices, browsers and virtual keyboards
- the issue is not present when using native browsers's search functionality in any browser, therefore it's either uBO doing it, or it's a some CodeMirror's quirk
- if it's uBO doing it, then it would be good to know whether it's on purpose or not, even if it's on purpose, it would be good to have a simple checkbox, which after being ticked would keep the virtual keyboard hidden when pressing _next_ / _previous_ buttons
- the explanation: there are situations:
   - when a an user wants a virtual keyboard to be present during iterating over the found items, so that he can easily modify the string in the fly if needed
   -  but on the other hand there are situations when an user wants the virtual keyboard to be kept hidden and not obstructing free space during iterating over found results

<hr>

### Issue 2: Misaligned yellow vertical marker 

On Desktop, In Filter list _asset-viewer_ and in _My Filters_:
- when searching for a string, the yellow vertical marker is significantly misaligned
- it can be reproduced on different devices, browsers (both chromium & firefox)
- the issue is not present (or at least is much smaller) when using native chromium's search functionality, therefore it's either uBO doing it, or it's a some CodeMirror's quirk
- it seems that it's caused by a fact that the marker is not excluding space occupied by _up_ and _down_ scroll bar arrows, and considers them as a legitimate space to place marks
-  if it's uBO doing it, then it would be good to know whether it's on purpose or not, even if it's on purpose, it would be good to have a simple checkbox, which after being ticked would keep the _up_ and _down_ arrows excluded
- to get the best results of reproducing the issue you can open EasyList in _asset-viewer_ and search for the following filters separately:

| Text to search | Description | Screenshoot<br> (with the issue present) | Screenshoot <br> (how it looks on Native chromium search) |
|-----------|-----------|-----------|-----------|
| `&rb=&uuid=$third-party`   | the marker will be at the top of the up arrow      | [link 1a](https://github.com/user-attachments/assets/26e6fe7c-40c9-40ab-adfd-74d2acf1e262)      | [link 1b](https://github.com/user-attachments/assets/aa1bef89-d0d1-4775-aadc-fa84f1a26d0e)      |
| `###block-frontpageabovepartnersad`   | the marker will be significantly above the scroll bar      | [link 2a](https://github.com/user-attachments/assets/ea76e605-6f13-47dc-a4c9-2ba565b6ddef)      | [link 2b](https://github.com/user-attachments/assets/78b0b706-7137-432b-a648-bc89b43912da)      |
| `runningmagazine.ca##.repeater-bottom-leaderboard`   | the marker will be significantly below the scroll bar      | [link 3a](https://github.com/user-attachments/assets/3f38539e-39ad-494c-9eb7-82c92937e7fe)      | [link 3b](https://github.com/user-attachments/assets/7baf6766-d9a9-4d31-88a2-0d32e56718a1)      |
| `@@\|\|xfreehd.com^$generichide`   | the marker will be at the bottom of the bottom arrow (actually invisible)      | [link 4a](https://github.com/user-attachments/assets/047c44e9-c3a6-4a61-a5ed-f578004c94c7)      | [link 4b](https://github.com/user-attachments/assets/f37a8975-0e2c-4a47-b61e-0e84a0369400)      |
