### ISSUE TITLE
Scriptlets remove-node-text.js and trusted-replace-node-text.js destroy DOM elements

### ISSUE THREAD

**Issue by Torbins** [uBlockOrigin/uBlock-issues#3492] opened 2024-12-19 22:50 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

For example we have part of HTML:
`<p><span class="regin0.xxxx">Please contact us at contact@example.com if you see this on another site.</span><a name="L6"></a> 「Hey, Jig, Shiasha-san. Good work」<span class="eloun0.xxxx">Several dragons looked at the human girl in amazement.</span></p>`
And we have following rule:
`example.com##+js(replace-node-text,p,「,- )`

### A specific URL where the issue occurs.

```yaml
https://www.foxteller.com/novel/643/33/the-witch-and-the-mercenary/033
```

### Steps to Reproduce

1. Add rule above to the list of custom rules
2. Reload web page

### Expected behavior

HTML becomes like this:
`<p><span class="regin0.xxxx">Please contact us at contact@example.com if you see this on another site.</span><a name="L6"></a> - Hey, Jig, Shiasha-san. Good work」<span class="eloun0.xxxx">Several dragons looked at the human girl in amazement.</span></p>`

### Actual behavior

HTML becomes like this:
`<p>Please contact us at contact@example.com if you see this on another site. - Hey, Jig, Shiasha-san. Good work」Several dragons looked at the human girl in amazement.</p>`

### uBO version

1.61.2

### Browser name and version

Firefox 133.0.3

### Operating System and version

Windows 11 24H2

**Comment by krystian3w** [comment] 2024-12-20 10:31
Seems fine for `remove-node-text`, p will be empty.

IDK possibly repair for `trusted-replace-node-text`, fails on `#text` as node hook.

**Comment by gwarser** [comment] 2024-12-20 12:38
Try using `#text` as node name. 

(Does not work for me on the page - racing.)

**Comment by gorhill** [comment] 2024-12-22 15:05
This is the expected behavior: replace the `textContent` of an element (`<p>` in your case) is going to remove everything under `p` and replace with a `#text` node in which instances of `「` are replaced with `-`.

Additionally, the text on that page is added dynamically, whereas `trusted-replace-node-text` is active only until the `DOMContentLoaded` is received.

In any case, event the following filter accomplishes nothing on my side:

    foxteller.com##+js(replace-node-text, #text, 「, -, stay, 1, quitAfter, 30000)

How did you make it work at all?

**Comment by krystian3w** [comment] 2024-12-22 15:10
Seems still fails.

> https://github.com/user-attachments/assets/8e4e5388-bfde-4ec5-b0f1-e29648aacd22

**Comment by gorhill** [comment] 2024-12-22 15:23
> Seems still fails

Ok it's because `trusted-replace-note-text` doesn't look deep into mutations, only superficially. The primary purpose of `trusted-replace-node-text` was not to comprehensively replace text on a web page, this is at most a side effect.

For the purpose of replacing text on a web page, it's best to add a procedural cosmetic `replace-text()` operator -- but this would require concept of _trusted source_ for procedural cosmetic filters, and there is no framework for this at this point, and this would be unrelated to the issue here.

Closing as `wontfix`, the `trusted-replace-node-text` scriptlet works as expected, according to its intended limitations. If uBO's filter list maintainers think those limitations should be revised according to real world cases, I will reconsider.

**Closed by gorhill** 2024-12-22 15:23 UTC
