### ISSUE TITLE
Cannot zap, access or block elements in Microsoft Teams

### ISSUE THREAD

**Issue by mprz1024** [uBlockOrigin/uBlock-issues#2646] opened 2023-05-09 15:15 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When using https://teams.microsoft.com/ in Chrome, whether in a tab or as a Chrome Progressive Web App (PWA), uBlock Origin can't access elements when trying to pick/zap/create rules. It seems to get stuck in some sort of IFRAME that has the content and it cannot see anything inside besides that, so only buttons on the left and this whole panel can be addressed, and I cannot block annoyances from this app.

I can see the elements if I use F12, and even if I type in the rule manually (such as block class whatever) into the picker, it doesn't delete the element on preview or create, so I guess it really can't access what's in there. Screenshot:

![Screenshot 20230509_170807](https://github.com/uBlockOrigin/uBlock-issues/assets/4671222/669bab41-7d2a-480a-b6be-66c38fb73ded)

### A specific URL where the issue occurs.

https://teams.microsoft.com/

### Steps to Reproduce

1. Go to https://teams.microsoft.com/. You may need a Teams account.
2. Try to create a rule (I use Alt+X), and move the mouse around. Select anything in the centre of the screen e.g. during a meeting or chat, and it'll come up as in the screenshot, without actually selecting the element.
3. Optional: Even if you override it with the element class manually, it won't be able to kill the element.

### Expected behavior

uBlock Origin should work in https://teams.microsoft.com/ as in any other website

### Actual behavior

It cannot access most elements in https://teams.microsoft.com/

### uBO version

1.49.2

### Browser name and version

Google Chrome 112

### Operating System and version

Debian GNU/Linux 11

**Comment by gorhill** [comment] 2023-05-09 15:20
I won't be able to investigate since this requires an account. Probably a shadow root issue, duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2346>. I will let you confirm it's the case, and if no feedback I will close as duplicate.

**Comment by gorhill** [comment] 2023-05-09 20:53
By the way, did you try right-clicking over the element you want to filter, and select _"Block in frame..."_?

**Comment by krystian3w** [comment] 2023-05-10 07:39
Reporter can't right click on iframed chat box, MS has blocked the action of clicking above the field for adding a new message - so those willing to do so have to click very close to the field for writing a new message for the use context menu and the "block item in frame" option to work; so I opened picker in iframe:

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/f3f83867-cced-4905-99ce-6255f8fe0c97)

In chat box I don't see usage shadow root/shadow DOM yet.



There are two outputs:

- close as invalid + filter issue

- move between repositories and let the will of heaven happen whether someone wants to test how `set-constant` or `aeld` will work to unlock right click action without break Teams - when the unprotected space through which to enter the iframe is too small for people with mobility disabilities.

**Comment by gorhill** [comment] 2023-05-10 12:42
Thanks for investigating @krystian3w.

So I will close as _invalid_, since it was a matter of _Block in frame..._. The fact that the site prevent right-click on some element is not something to be solved here, and this should be a browser issue, for example Firefox allows to bypass sites eating right-clicks.

**Closed by gorhill** 2023-05-10 12:42 UTC
Labels: feedback needed

**Comment by krystian3w** [comment] 2023-05-10 13:55
A link to this Firefox novelty would be rather useful (search results are overflowing with methods like deactivating all JS which will whisk away Teams loading), if this is a separate WebExtension rather uninteresting to me, it could be ported for Chrome (as those already published are failing).
I somehow missed the news about this and would further recommend just using a specific WebExtension, `*.user.js` file or analyzing if a properly written `set-constant`, `aeld` or `remove-attr` (in correct world) works for this.

And not to be outdone, there is an option in Chrome devtools to remove listeners - as someone has determined which MS has blocked clicking on 3/4 of the frame area without save as `aeld` or improved aeld if listener is invisible/unaddressable now.

**Comment by gorhill** [comment] 2023-05-10 13:59
> A link to this Firefox novelty would be rather useful

Shift right-click
