### ISSUE TITLE
Can't open logger window

### ISSUE THREAD

**Issue by DeepChirp** [uBlockOrigin/uBlock-issues#2249] opened 2022-09-07 16:01 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The logger window cannot be opened on `Microsoft Edge`, clicking the icon of the recorder has no effect, only right-click and open in a new tab.

### A specific URL where the issue occurs

No need

### Steps to Reproduce

1. Click on the uBlock Origin icon.
2. Click the logger icon.

### Expected behavior

Logger window appears.

### Actual behavior

Logger window doesn't appear.

### uBlock Origin version

1.44.0

### Browser name and version

Microsoft Edge 104.0.1293.70 (64-bit)

### Operating System and version

Windows 11 21H2 (22000.856)

![2022-09-07_23-58-28](https://user-images.githubusercontent.com/66902050/188925055-36a46b28-20a9-41dd-a3f6-ea0d07e6bdc5.gif)

**Comment by gwarser** [comment] 2022-09-07 16:57
Click it once with Shift pressed - should open in new tab.

Something is broken with "new window" mode.

**Comment by Nojuuu** [comment] 2022-09-15 22:12
Same seems to happen on Brave but only with latest uBO dev build?

**Comment by effleurager** [comment] 2022-09-27 12:42
This is happening also on Chrome 104.0.5112.101 with µBlock 1.14.4 on macOS 12.5.1, so it can probably be found with a bisect of the Chromium source

**Comment by krystian3w** [comment] 2023-04-21 07:59
Maybe corruption in extension folder, for me help backup settings and refresh addon.

I didn't checked import backup without reset - maybe possible skip reset.

**Comment by Bartolomeus-649** [comment] 2023-06-05 14:39
I experience this as well in Microsoft Edge Version 113.0.1774.57 (Official build) (64-bit).

What kind of logs/tracing/troubleshoot-info would be helpful to understand what's going on a bit more?

**Comment by Bartolomeus-649** [comment] 2023-06-06 10:31
as soon as I opened up the devtools for the extension it all started to work again.

**Comment by zachpoblete** [comment] 2023-09-16 01:27
Still happens on Edge v116.0.1938.81. Wish I was knowledgeable enough to implement https://github.com/uBlockOrigin/uBlock-issues/issues/2249#issuecomment-1576997333:

> You can put a breakpoint where the logger's tab or window is created. By default it opens as a popup window, unless you changed this.
> 
> * Popup window creation: https://github.com/gorhill/uBlock/blob/83c8233c33e94ee124ae6bbf8694341232f72849/platform/common/vapi-background.js#L392
> * Tab creation: https://github.com/gorhill/uBlock/blob/83c8233c33e94ee124ae6bbf8694341232f72849/platform/common/vapi-background.js#L464

**Comment by gorhill** [comment] 2023-11-29 01:37
Still unable to reproduce, closing as stale issue.

**Comment by ZazzleAlex** [comment] 2024-03-11 21:30
I just ran into this on Chrome 122, Mac 14.3.1. When I open dev tools for background.html I see an error in the console:
`Unchecked runtime.lastError: Invalid value for bounds. Bounds must be at least 50% within visible screen space.`

And when I set a breakpoint, I can see that `webext.windows.create()` is indeed throwing the error and returning `null`.
https://github.com/gorhill/uBlock/blob/c2c80be8976a7f7687733acca341776d4be21a15/platform/common/vapi-background.js#L675

<img width="1198" alt="debugging" src="https://github.com/uBlockOrigin/uBlock-issues/assets/88680590/d44db8ea-aa73-4716-858f-76244491542b">

**Comment by ArgonAlex** [comment] 2024-03-11 21:31
I just ran into this on Chrome 122, Mac 14.3.1. When I open dev tools for background.html I see an error in the console:
`Unchecked runtime.lastError: Invalid value for bounds. Bounds must be at least 50% within visible screen space.`

And when I set a breakpoint, I can see that `webext.windows.create()` is indeed throwing the error and returning `null`.
https://github.com/gorhill/uBlock/blob/c2c80be8976a7f7687733acca341776d4be21a15/platform/common/vapi-background.js#L675

<img width="1198" alt="debugging" src="https://github.com/uBlockOrigin/uBlock-issues/assets/88680590/d44db8ea-aa73-4716-858f-76244491542b">

**Comment by gorhill** [comment] 2024-03-11 22:23
What's your screen resolution?

**Comment by ArgonAlex** [comment] 2024-03-13 01:21
I was able to reproduce the issue a Windows machine as well as my Mac. I don't think screen resolution matters. It seems that when you move the logger window such that most of it is off screen and then close it, the extension is caching that last position in localStorage and then the next time you try to open it, it attempts to use that last position, which fails.

I was able to get the logger to open again by calling `vAPI.localStorage.removeItem('popupLoggerBox')`.

I haven't tested this, but I suspect this may have originally happened when I closed the logger on an external monitor at work, then I attempted to open it again with the monitor disconnected, or at home where I have a different monitor configuration. The cached position would possibly be invalid in these situations.

**Comment by gorhill** [comment] 2024-03-13 13:58
Thanks for pinpointing the issue, I can also reproduce on my side with Linux, I just drag the popup window as low as possible at the bottom, then close it, and it won't re-open afterward. I will provide a new code path for when the popup window fails to be created.

**Comment by gorhill** [comment] 2024-04-15 00:26
No feedback, assumed fixed.

**Closed by gorhill** 2024-04-15 00:26 UTC
Labels: bug
