### ISSUE TITLE
Firefox ESR (v78): uBlock Origin could not be verified for use in Firefox and has been disabled.

### ISSUE THREAD

**Issue by allanlaal** [uBlockOrigin/uBlock-issues#1611] opened 2021-06-02 16:34 UTC
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x ] uBO is the only extension
    - [x ] uBO with default lists/settings
    - [- ] using a new, unmodified browser profile
- [ x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlockOrigin is disabled on Firefox ESR as of today:
about:addons says:

`uBlock Origin could not be verified for use in Firefox and has been disabled.`

### A specific URL where the issue occurs

any

### Steps to Reproduce

1. install Firefox ESR 
2. try to install/enabld uBlock Origin

### Expected behavior:

works

### Actual behavior:

addon disabled

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version:  Firefox ESR (based on v78)
* Operating System and version:  Ubuntu Mate 20.10

**Comment by uBlock-user** [comment] 2021-06-02 16:35
> try to install/enabld uBlock Origin

installation source ?

**Comment by gorhill** [comment] 2021-06-02 17:06
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/996>.

please refrain from opening issue which you are unwilling to follow through, and are most likely invalid.

**Closed by gorhill** 2021-06-02 17:06 UTC
Labels: duplicate, invalid
