### ISSUE TITLE
Web detects ublock filters and filter requests

### ISSUE THREAD

**Issue by gallegonovato** [uBlockOrigin/uBlock-issues#839] opened 2020-01-04 17:38 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Good afternoon:

There's a website that detects the filters I have in ublock origin. The web is https://browserleaks.com in the section of Content Filters in this link of the same web https://browserleaks.com/proxy . And I think I should not detect them. If not I am wrong. Or if I am wrong I don't know if they know somehow so I don't do it.

I also wanted to ask you for a filter for cryptomonics and something to avoid recaptcha or google analytics, AdSense, AdWords and other similar things from google.

A hug and thanks for your help

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

Good afternoon:

There's a website that detects the filters I have in ublock origin. The web is https://browserleaks.com in the section of Content Filters in this link of the same web https://browserleaks.com/proxy . And I think I should not detect them. If not I am wrong. Or if I am wrong I don't know if they know somehow so I don't do it.

I also wanted to ask you for a filter for cryptomonics and something to avoid recaptcha or google analytics, AdSense, AdWords and other similar things from google.

A hug and thanks for your help

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Fennec 68.2
* Operating System and version: Android Lineageos 15.1

**Comment by uBlock-user** [comment] 2020-01-04 17:40
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/153

**Closed by uBlock-user** 2020-01-04 17:40 UTC
