### ISSUE TITLE
Can't write any filters on Android

### ISSUE THREAD

**Issue by Kusresa** [uBlockOrigin/uBlock-issues#7] opened 2018-04-20 21:50 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Using 1.16.0 I'm trying to write a filter on Android but it doesn't work. If I want to type `||example.com` once I type the period `example` will disappear and I'll be left with `||.`. Same thing happens if I type `!#if` then press space then the `if` disappears. I've tried using multiple keyboards including ASK.

### Steps to Reproduce

1. Try to type `||example.com` in My Filters

### Expected behavior:

I can type it out normally and get `||example.com`

### Actual behavior:

I can't type it out and instead get `||.`

### Your environment

* uBlock Origin version: 1.16.0
* Browser Name and version: Firefox beta
* Operating System and version: Android

**Comment by gorhill** [comment] 2018-04-20 22:09
Unable to reproduce.

> once I type the period example will disappear and I'll be left with ||.

It sounds to me as a keyboard issue -- some Android keyboard can cause weird behvior, see <https://github.com/gorhill/uBlock/issues/3646>.

I personally use [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard) -- no issue so far.

**Comment by Kusresa** [comment] 2018-04-20 22:17
But I'm using AnySoftKeyboard too. I also tried this on 1.15.24 and it works fine there.

**Comment by gorhill** [comment] 2018-04-20 22:28
Note that I tried with Nightly, not Beta.

**Comment by Kusresa** [comment] 2018-04-20 22:36
You think this could be an issue with beta then? Seems odd it doesn't affect Nightly or Stable but affects Beta but I guess it could be possible.

I don't know what on my side could be affecting this because I installed 1.15.24 and it works normally but when I install 1.16.0 with the exact same profile and settings it doesn't.

**Comment by gorhill** [comment] 2018-04-20 23:04
Need more people to try to reproduce.

By your description, it's as if `example` is selected and replaced with `.`.

**Comment by gwarser** [comment] 2018-04-21 12:00
I can reproduce this on AOSP keyboard on Firefox beta, UBO 1.16.0.
Also one more weird thing:

 - type `example`
 - clear it by backspace
 - type `|`
 - `example|` is shown


I find lot of keyboard bugs on bugzilla. I think this may be related to auto-correction. @Kusresa, try to disable all you can find in your keyboard settings about misspelled word auto-correction or auto-suggestion, for example "Spacebar and punctuation automatically correct mistyped words"

**Comment by gorhill** [comment] 2018-04-21 12:15
> I think this may be related to auto-correction.

I checked to be sure, and `autocorrect` attribute is properly set to `false` by CodeMirror -- so it could be a regression in Firefox beta.

Still, how would this explain that 1.15.24 reportedly is not suffering the issue?

**Comment by gwarser** [comment] 2018-04-21 12:37
I can reproduce in 1.15.24, and keyboard settings is "Show personalized suggestions (Display suggested words while typing)"

**Comment by Kusresa** [comment] 2018-04-21 22:29
I can confirm using AnySoftKeyboard disabling `Show suggestions` (which seems to be a header option to disable many sub-options such as `User-dictionary`, `Auto capitalization`, `Quick fixes` etc.) allows me to type properly again. But I don't know why because if I disable all sub-options underneath "Show suggestions" manually but leave the header enabled I still get the disappearing text issue. It's weird that giving suggestions itself would be causing this issue. 

But still doesn't explain why I didn't have to change anything for it to work on properly 1.15.24. Maybe this is a regression in beta.

**Comment by gorhill** [comment] 2018-04-23 09:35
Closing as invalid, as the issue is outside uBO.

**Comment by gorhill** [comment] 2018-04-23 20:57
I am re-opening because of [this comment on Reddit](https://www.reddit.com/r/uBlockOrigin/comments/8ed3ta/adroidfirefox_problem_adding_a_filter/dxuij6r/):

> I cannot reproduce this on their demos https://codemirror.net/demo/ ... Also, their code is two versions ahead.

I checked and this is true. We need to find an explanation for this.

**Comment by gorhill** [comment] 2018-04-23 21:54
I updated CodeMirror to 5.37, and this seems to have fixed the issue on my side -- after I enabled the setting pointed out by @gwarser above I could reproduce at will, even with only two characters `ex` then `.`. I suspect this is the change which solved the issue: <https://github.com/codemirror/CodeMirror/commit/9cb7b7d5e556d5be9340729ea6403dee7fe06d55>.

I need feedback that issue is fixed for others before closing as fixed.

**Comment by gwarser** [comment] 2018-04-23 22:14
It's fixed for me.

**Comment by Kusresa** [comment] 2018-04-23 22:49
Fixed for me too (works now with suggestions enabled).

**Comment by gorhill** [comment] 2018-04-23 23:18
Alright then, fixed with <https://github.com/gorhill/uBlock/commit/75b148b3070f915bce316a8d3a312a5da554e065>.

**Closed by gorhill** 2018-04-23 23:18 UTC
Labels: fixed
