### ISSUE TITLE
"Dynamic filtering" popup still shown after "advanced user" is unchecked

### ISSUE THREAD

**Issue by Tenshi447** [uBlockOrigin/uBlock-issues#790] opened 2019-11-20 11:55 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBO's popup would not collapse into the default small, compact one when "I am an advanced user" is unchecked.

Kindly inform me and remove this post if it violates anything. (I did look around but might have missed something)

### A specific URL where the issue occurs

Any URL.

### Steps to Reproduce

1. Use uBO's default settings.
2. Open any website.
3. Go to Dashboard/Setting and enable "I am an advanced user".
4. Switch back to the website.
5. Click uBO icon on browser's bar and confirm the appearance of Dynamic filtering popup.
6. Now **disable** "I am an advanced user".
7. Again, switch to the website and see that Dynamic filtering popup's still present. 

### Expected behavior:

The Dynamic filtering popup would disappear after I uncheck the "I am an advanced user" _just like_ the default setting (when it was never enabled once). 

### Actual behavior:

The Dynamic filtering popup is still there **but now more minimal** (not showing 3rd party scripts/frames) after I uncheck "I am an advanced user".

### Your environment

* uBlock Origin version: uBlock Origin v1.23.0
* Browser Name and version: Chrome 78.0.3904.108 (64-bit)
* Operating System and version: Windows 10 Version 1703 Build 15063

**Comment by uBlock-user** [comment] 2019-11-20 12:04
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/125

**Closed by uBlock-user** 2019-11-20 12:04 UTC

**Comment by Tenshi447** [comment] 2019-11-20 12:10
> Duplicate of #125

Ah, it seems I didn't check carefully enough. Thank you!
