### ISSUE TITLE
Cookie Domain Problem with Scriptlets

### ISSUE THREAD

**Issue by JoviDong** [uBlockOrigin/uBlock-issues#3191] opened 2024-04-01 13:20 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I have been attempting to use scriptlets in uBlock Origin to modify cookies on the website expedia.com. Specifically, I have tried using both set-cookie and trusted-set-cookie scriptlets to set a cookie with the domain ".expedia.com" in order to make it accessible across subdomains. However, I have encountered an issue where the domain of the cookie is being set to "www.expedia.com" instead of ".expedia.com".

### A specific URL where the issue occurs.

```yaml
https://www.expedia.com/
```

### Steps to Reproduce

1.Navigate to the website expedia.com.

2.Use the following scriptlet syntax in uBlock Origin to set a cookie:
expedia.com##+js(set-cookie, id, 999) or
expedia.com##+js(trusted-set-cookie, id, 999)

3.Verify the domain of the set cookie using browser developer tools.

![0](https://github.com/uBlockOrigin/uBlock-issues/assets/39184341/c5ec8384-39b5-4469-aea6-58cec9ed6492)

### Expected behavior

I expect the cookie to be set with the domain ".expedia.com", allowing it to be accessible across subdomains of expedia.com.

### Actual behavior

The domain of the cookie is being set to "www.expedia.com" instead of ".expedia.com", which restricts its accessibility to the specific subdomain.

### uBO version

uBlock Origin development build 1.56.1rc5

### Browser name and version

Google Chrome Version 123.0.6312.86

### Operating System and version

Windows 11

**Comment by garry-ut99** [comment] 2024-04-01 14:31
> JoviDong :  I expect the cookie to be set with the domain ".expedia.com", allowing it to be accessible across subdomains of expedia.com.


Duplicate of:
-   https://github.com/uBlockOrigin/uBlock-issues/issues/2893

Already possible with additional `domain` parameter as explained in the above comment and in the above the link, 
just that Wiki / documentation hasn't been updated yet:  https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#trusted-set-cookiejs-
it can be added to the "Wiki" section of the TO-DO tasks list :   [ Issues/Tasks list #3151 ](https://github.com/uBlockOrigin/uBlock-issues/issues/3151)

<hr>

> stephenhawk8054 : Use `set-cookie` or `trusted-set-cookie`

Only `trusted-set-cookie` works with `domain`.

**Comment by gorhill** [comment] 2024-04-01 14:32
> documentation hasn't been updated yet

I just updated it.

**Closed by gorhill** 2024-04-01 14:32 UTC
