### ISSUE TITLE
Add a pane in the dashboard (Firefox only) to assign keyboard shortcuts

### ISSUE THREAD

**Issue by jefferysmall** [uBlockOrigin/uBlock-issues#106] opened 2018-06-29 16:30 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I would like to see keyboard shortcuts added to allow the element picker and element zapper operations to be launched without the two-step process of opening the menu and then selection the desired operation.  This would be especially useful and a time saver when working on a page where you want to block a series of elements.

So far as I can tell, uBO isn't supporting keyboard shortcuts at the moment.

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.16.8
* Browser Name and version: Firefox 60.0.2
* Operating System and version: Xubuntu 18.04

**Comment by uBlock-user** [comment] 2018-06-29 17:24
They were removed by gorhill after a issue was raised, see - https://github.com/gorhill/uBlock/issues/2723#issuecomment-310044763

**Comment by aplaice** [comment] 2018-06-29 17:24
This is an issue with Firefox itself — there is no UI for reassigning webextension shortcuts:

https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

uBlock Origin provides several "commands" (including entering element picker and element zapper mode) for which shortcuts could be assigned, but does not set any pre-defined shortcuts for them (AFAIK because these occasionally collided with various other, sometimes system, shortcuts and people complained...). Unfortunately this means that without support from the browser (i.e. Firefox) for changing/assigning shortcuts, you can't actually use them.

On Chrom(e|ium) shortcuts can be easily set, by going to `chrome://extensions/shortcuts`.

Bug on the old tracker: https://github.com/gorhill/uBlock/issues/2870


There is, however, now an option for a webextension to reassign its own shortcuts (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/update).

Potentially, uBlock Origin could work around the Firefox bug by providing a UI for reassigning its own shortcuts. Would a patch providing such support be considered (or is it out-of-scope for uBlock Origin)?

**Comment by uBlock-user** [comment] 2018-06-29 17:32
Duplicate of https://github.com/gorhill/uBlock/issues/3473

**Comment by jefferysmall** [comment] 2018-07-10 17:30
For whatever it's worth, the latest release of the Flagfox 6.1.0 just re-implemented user-customizable keyboard shortcuts.

* Reimplemented support for customizable hotkeys for actions, instead of just one default (new WebExt API)

**Comment by happysurf** [comment] 2018-07-20 05:55
I don't see any pane in dashboard for that, in UBO 1.16.15.1.

**Comment by happysurf** [comment] 2018-07-20 06:18
I have set my shortcut on UBO 1.15.16.1 + Firefox 63beta but then doesn't work.

![shortcuts](https://user-images.githubusercontent.com/13637587/42986316-5b5d5e8c-8bf5-11e8-9043-b2ed84b042c0.png)

**Comment by uBlock-user** [comment] 2018-07-20 06:36
If those keys are already in use, it will not work.

**Comment by happysurf** [comment] 2018-07-20 06:46
I have solved the problem with these shortcuts:
![shortcuts](https://user-images.githubusercontent.com/13637587/42987379-626e9322-8bf9-11e8-82f2-f04834fb0773.png)

**Comment by uBlock-user** [comment] 2018-07-20 07:14
`Ctrl+Shift+X` and `Ctrl+Shift+Z` doesn't work on my end either, `Ctrl+Shift+L` works though.

**Comment by happysurf** [comment] 2018-07-20 07:26
> Ctrl+Shift+L works though.

Yes, exactly.

**Comment by uBlock-user** [comment] 2018-07-20 12:33
Debugged console log of the extension, if it is of any help - 

![](https://i.gyazo.com/6a405b8da9b6eb6c576b377a585aa752.png)

**Comment by gorhill** [comment] 2018-07-20 12:41
Issue is not uBO, Firefox never calls uBO with a lot of Ctrl-... shortcuts apparently. Maybe I should just forbid using Ctrl, because these are apparently ok to use, but they don't work as far as I can tell.

**Comment by gorhill** [comment] 2018-07-20 12:55
I am going to have to reject "Ctrl" shortcuts, Firefox does not return an error when a shortcut is not going to be actually triggered for an extension. I looked at Flagfox and it also does not allow Ctrl-based shortcuts.

**Comment by gorhill** [comment] 2018-07-20 16:35
Using the browser toolbox, I can see Firefox is already defining a command for ctrl-shift-z => "redo":

![a](https://user-images.githubusercontent.com/585534/43014072-fd1e05fa-8c18-11e8-8f93-de0e9d4a3d14.png)

For instance, I couldn't spot one for ctrl-shift-u in Firefox-defined command, and as expected it worked with uBO.

Maybe it could be argued that there is something to fix on Firefox's side, i.e. that the `commands.update` API should return an error informing that a shortcut is reserved and already in use.

**Comment by gorhill** [comment] 2018-07-20 16:42
Related: <https://bugzilla.mozilla.org/show_bug.cgi?id=1325692>

**Comment by jefferysmall** [comment] 2018-07-20 17:00
I would like to experiment with this in Firefox but I do not understand where to go to try and set these shortcuts.  I don't see any options in the uBlock Dashboard. Could someone please point me in the right direction.  Is it something you can add to a config file?  Thanks.

Firefox: 61.0.1
uBlock: 1.16.12
OS: Xubuntu 18.04

**Comment by uBlock-user** [comment] 2018-07-20 17:14
> Could someone please point me in the right direction.

Install the latest dev build and then browse to shortcuts tab via the dashboard.

**Comment by gorhill** [comment] 2018-07-20 17:36
You can install dev build from the [Releases section](https://github.com/gorhill/uBlock/releases). Click on the most recent uBlock0.firefox.signed.xpi link. Dev builds auto-update to more recent dev builds.

**Comment by jefferysmall** [comment] 2018-07-20 18:38
Great!  Thanks for the information.

**Comment by jefferysmall** [comment] 2018-07-20 18:45
Works great for me in Firefox 61.0.1.  I can use Alt-P, Alt-Z and Alt-L without problem.  Any chance of adding a shortcut to open the Dashboard (specifically set to the My filters tab if possible)?

**Comment by jefferysmall** [comment] 2018-07-20 18:54
For whatever it's worth, I also noticed that trying to enter Shift-Alt-{letter}  or Ctrl-Alt-{letter} combinations are not recognized and collapse to Alt-{letter} or Ctrl-{letter} respectively.

And while it might really be off-topic, FYI, I have a Sun type-6 keyboard with many additional function keys mapped beyond F12, and none of these are recognized by the Shortcuts menu fields.  Not a problem, but I thought I would mention it.

Firefox: 61.0.1
OS: Xubuntu 18.04

**Comment by aplaice** [comment] 2018-07-20 19:12
In the case of the Shift-Alt-{letter} combinations, they seem to be recognised correctly if you press the keys in the order `Alt`, `Shift`, `{letter}`, but not in the order `Shift`, `Alt`, `{letter}`, and the same for Ctrl.

The lack of support for function keys beyond F12, is a Firefox (not uBlockOrigin) limitation:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values

**Comment by jefferysmall** [comment] 2018-07-20 19:41
Yes, pressing Alt/Ctrl and then Shift does work when setting the shortcut, but you must also then press the keys in that sequence to execute the shortcut as well.  This does not work if you want to use a Ctrl-Alt or Alt-Ctrl combination.  Alt and Ctrl seem to be mutually exclusive.  Also, the meta key doesn't appear to be available.  This is all just user feedback, not an indication of a problem.

**Comment by gorhill** [comment] 2018-07-20 19:44
These are all Firefox by-design behaviors, read the link posted above, we will have to live with these until they decide to centralize shrotcut assignement UI. I consider the issue fixed.

I will revised as needed when someone report back with information re. "Command key" above

**Comment by Betsy25** [comment] 2018-07-20 20:54
There still is a minor issue with Azerty keyboards though, for example in the Shortcuts pane, trying to assign Alt-Z will enter Alt-W in the input & will react to Alt-W.

**Comment by gorhill** [comment] 2018-07-20 20:58
> Alt-Z will enter Alt-W in the input & will react to Alt-W

This needs fixing, I will look into it.

**Comment by gorhill** [comment] 2018-07-20 21:01
I activated the French keyboard layout here, and the shortcuts were properly read (Linux Mint). So I can't reproduce.

**Comment by gorhill** [comment] 2018-07-20 21:07
@Betsy25 Can you tell me what is reported [in this applet](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code#Try_it_out) when you enter Alt-Z?

**Comment by Betsy25** [comment] 2018-07-20 21:14
> @Betsy25 Can you tell me what is reported in this applet when you enter Alt-Z?

Pressing Alt-Z in the keyboard gives me : 
KeyboardEvent: key='Alt' | code='AltLeft'
KeyboardEvent: key='z' | code='KeyW'

**Comment by gorhill** [comment] 2018-07-20 21:15
Just to be sure... The physical key you pressed had "Z" on it?

**Comment by Betsy25** [comment] 2018-07-20 21:16
> Yep, on an Azerty keyboard, the physical keys were Alt and Z.

**Comment by Betsy25** [comment] 2018-07-21 15:09
I can confirm that the layout weirdness is fixed with the latest dev build.

**Closed** 2018-07-21 15:11 UTC
Labels: Firefox, duplicate, fixed

**Comment by yourduskquibbles** [comment] 2018-07-24 20:13
@gorhill It appears that if `privacy.resistFingerprinting` is set to 'true' in 'about:config' of Firefox v 61.0.1 it will prevent the shortcut keys from being able to be set. 

It seems that once the key binding is set by setting `privacy.resistFingerprinting` to false, the shortcuts will continue to work regardless of the `privacy.resistFingerprinting` is set as 'true' or 'false'.

I looked over the bugzilla issues you posted in this thread and didn't see it brought up and I'm really not sure if this is a firefox bug or uBlock Origin bug so wanted to bring it to your attention.

**Comment by gorhill** [comment] 2018-07-24 20:47
uBlock Origin has no knowledge of that flag, it merely just call `browser.commands.update()`, there is nothing more for uBO to do to assign shortcuts. That `resistFingerprinting` flag is not officially supported by Firefox, use at your own risk.

**Comment by GuardianMajor** [comment] 2018-07-25 18:21
@gorhill Forgive me if I am being dense here, but I don't see that tab, did I miss a special consideration that would make it appear?

**Comment by aplaice** [comment] 2018-07-25 18:38
@GuardianMajor What version of uBO do you have installed? (The current latest version on AMO is [1.16.14](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/#detail-relnotes), while the added functionality is only in version 1.16.15(x), which you can download from [GitHub](https://github.com/gorhill/uBlock/releases).)

(Also [see above](https://github.com/uBlockOrigin/uBlock-issues/issues/106#issuecomment-406673026).)

**Comment by gorhill** [comment] 2018-07-25 20:29
You need uBO 1.16.15b? + Firefox 60+, the API needed to dynamically assign shortcuts (`commands.update`) [became available with FF60](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands#Browser_compatibility).

**Comment by GuardianMajor** [comment] 2018-07-25 21:00
@aplaice I have the latest beta which is what I always run directly from GitHub.

@gorhill Yes, figured that was a given, why else would I know it was meant to be there 😄 But the last part is helpful, thank you, I will check but I think this particular browser version might not have it.

**Comment by LiCybora** [comment] 2018-08-14 07:56
The current keyboard shortcut pages not work for Apple Mac Keyboard layout. 

1. Press 'Command' having no response (There is no catcher for Command Key in 'shortcuts.js').
2. Press 'control' which able to record shortcut, but unable to call. (Because Mac treat 'Ctrl' as 'Command')
3. Press 'Alt', but unable to bind with any other key. (Because in Mac, Alt+P will type π, but there is no catcher of π in 'shortcut.js')

> I do not listen to MacOS-specific key press. I will need someone with MacOS to report to me what is the key & code names for the "Command" key.

I have a quick hack to make things work. Here maybe what you want @gorhill ?
https://github.com/gorhill/uBlock/compare/master...LiCybora:uBlock-master?expand=1

**Comment by Korb** [comment] 2025-12-02 12:38
> uBlock Origin provides several "commands" (including entering element picker and element zapper mode) for which shortcuts could be assigned

Thanks, I was just looking for them mentioned here!

![Image](https://github.com/user-attachments/assets/95b7b59e-5966-4f22-9364-168a79aec7a3)

---
_Mozilla Firefox 146.0 (64-bit), Microsoft Windows 10.0.26200.7309_
