### ISSUE TITLE
Cannot whitelist (green), only grey options enabled (to no effect)

### ISSUE THREAD

**Issue by vogelfreiheit** [uBlockOrigin/uBlock-issues#1208] opened 2020-08-15 13:04 UTC
### Prerequisites

- [x ] I verified that this is not a filter issue
- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I have tried to narrow this down to a filter issue but so far I have been unable to find any meaningful informaiton out of the logger. At some point after an update, I no longer had the option to greenlight/whitelist specific domains per site. I only get a grey option in place, which does not produce the desired effect.

This screenshot shows a previous greenlighted domain and then the grey option shown for one without settings, without the option to greenlight it: https://i.imgur.com/oSihq2e.png

### A specific URL where the issue occurs

https://www.humblebundle.com/

### Steps to Reproduce

1. Hover over whitelist option for a given domain. No green option shown, only grey.

### Expected behavior:

Greenlighting of domains per site working as expected.

### Actual behavior:

No option to whitelist/greenlight domains.

### Your environment

* uBlock Origin version: Latest stable
* Browser Name and version: Chrome, latest version
* Operating System and version: Win10 x64 and Ubuntu/Fedora, latest stable releases up to date

**Comment by uBlock-user** [comment] 2020-08-15 13:13
Duplicate of #1153

**Closed by uBlock-user** 2020-08-15 13:13 UTC
