### ISSUE TITLE
Request: Granular placeholder settings for dynamic filtering

### ISSUE THREAD

**Issue by Metaception** [uBlockOrigin/uBlock-issues#50] opened 2018-05-27 01:09 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] ~~I tried to reproduce the issue when...~~ Feature request, not a bug
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The current **Hide placeholders of blocked elements** setting applies to all network requests. However, with a global block of 3rd-party `iframe`, I am finding it difficult to notice when the block is breaking a site as the space occupied by the `iframe` is hidden. I presume similar logic applies to 3rd-party `script` and `image`.

I would like to suggest more granularity in placeholder settings to show placeholders for certain class of filters while hiding the rest. Forgive me if this is not technically feasible or I am misunderstanding something.

### A specific URL where the issue occurs

https://priceonomics.com/introducing-priceonomics-charts/

### Your environment

* uBlock Origin version: 1.16.8
* Browser Name and version: Firefox 60.0.1
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment] 2018-05-27 08:43
https://github.com/gorhill/uBlock/issues/2688

Is that what you're suggesting ?

**Comment by Metaception** [comment] 2018-05-27 09:16
Kinda related, but not the same feature.
That issue is asking for more visible placeholders to help with identifying blocked features.

I am OK with the blank placeholders that currently exist, but I would like to only show some of them. Currently, if you set uBlock to show placeholders, you can see the missing iframes, but you will also see blocked image ads taking space too. I was hoping that a more granular setting will allow the ads to be collapsed, while allowing the iframes to show a placeholder.

**Comment by uBlock-user** [comment] 2018-05-27 10:02
> Currently, if you set uBlock to show placeholders, you can see the missing iframes, but you will also see blocked image ads taking space too.

Where? There are no blank placeholders in uBlock Origin, that's why it was suggested to add them to uBO too, just like uMatrix has them.

**Comment by Metaception** [comment] 2018-05-27 10:45
Blank as in just empty space that is not collapsed.

**Comment by gwarser** [comment] 2018-05-27 10:47
>Where
Firefox

**Comment by Metaception** [comment] 2018-05-27 10:54
> Although, what you're suggesting can be done by differentiating ads and blocked iframes in two categories as blacklisted elements and blocked elements.

That was my thought as well. However, I left the implementation details vague in case further granularity would be desirable such as separate settings for images, scripts, and iframes.

I was unsure how useful that would be though, as I only block iframes.

**Comment by uBlock-user** [comment] 2018-05-27 10:57
> Firefox

A screenshot would expand on that better.

**Comment by Metaception** [comment] 2018-05-27 11:01
Would you like me to provide a picture?
It just be me toggling the Hide Placeholder setting though.

Or are you asking what @gwarser meant?

**Comment by gorhill** [comment] 2018-05-27 13:36
Duplicate of <https://github.com/gorhill/uBlock/issues/3619>.

**Closed** 2018-05-27 14:43 UTC
Labels: duplicate, enhancement

**Comment by gwarser** [comment] 2018-05-27 17:33
@uBlock-user 
![screenshot_20180527_193228](https://user-images.githubusercontent.com/886325/40588893-d98906ca-61e4-11e8-8a2f-fb163a383885.png)
