### ISSUE TITLE
Add a uMatrix Like Option

### ISSUE THREAD

**Issue by seniorm0ment** [uBlockOrigin/uBlock-issues#1891] opened 2021-12-21 12:09 UTC
Would really like to see a mode for uBlock Origin that basically adds in the uMatrix interface, for very clear and easy granular control.
Seeing uBlockO seems to be the "replacement" for uMatrix now. I still run them side by side though, because uMatrix offers granularity and clarity that uBlock does not when it comes to blocking cookies, css, images, media, scripts, xhr, frame, other columns, as well as easily being able to adjust by domain, subdomain, tld, or *.

Again this could be optional, but it would allow users to do everything uMatrix does, but in uBlock Origin, requiring one less extension.

**Comment by gwarser** [comment] 2021-12-21 12:31
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1324

**Closed by gwarser** 2021-12-21 12:31 UTC
