### ISSUE TITLE
YouTube showing "Playback Error" on certain videos with uBlock (and other adblockers) enabled

### ISSUE THREAD

**Issue by VarvatosVex** [uBlockOrigin/uBlock-issues#933] opened 2020-03-07 12:54 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

What it says on the tin. Adblocking on YouTube is currently partially broken.
It could possibly be a filtering issue, but it seems like Google is restructuring their entire advertisement backend for YouTube, since I've never seen this error happen in this strange a manner before.

I know this may not be the place for it, but it would be nice to have at least somewhere other than reddit to discuss the actual technical aspects of this issue and how to resolve it.

Example screenshot of the issue:
https://i.redd.it/23crz33hqoj41.png
(Courtesy of reddit)

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=23Md5K9D0Q4
(Error appearance is determined by YouTube ad algorithm, so it might not show for you)

### Steps to Reproduce

1a. Visit https://www.youtube.com/ and click on a suggested video.
1b. Visit a video directly via a link on another website or app.
2. Error either happens or does not happen, most likely depending on video monetization status and your current queue status in the internal YouTube advertisement algorithm.

### Expected behavior:

Video is expected to play as normal. We all know how youtube normally plays videos, right?

### Actual behavior:

Video frame is grayed and the text "An error occured. Please try again later." is shown in the top center. Followed by a cryptic "Playback ID" (alphanumeric, mixed caps, similar to video ID) and a "Learn More" link.

This "error screen" will display for approximately 3-5 or so seconds, before the video frame "refreshes" itself (for a lack of another word) and regular video playback starts as normal.

Refreshing the entire page normally will also clear the error screen and cause the video to play as normal. This seems to fix the issue in 100% of the cases (until the error happens again on another video at a later time), most likely because the advertisement algorithm is notified of the error and chooses to not show an ad again on that video.

### Your environment

* uBlock Origin version: v1.25.0
* Browser Name and version: Firefox Developer Edition 74.0b9 (64-bit)
* Operating System and version: Windows 10 Version 1903 (OS Build 18362.657)

**Comment by uBlock-user** [comment] 2020-03-07 13:04
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/925

**Closed by uBlock-user** 2020-03-07 13:04 UTC

**Comment by gorhill** [comment] 2020-03-07 13:18
Adding `invalid` label because _"I performed a cursory search of the issue tracker to avoid opening a duplicate issue"_ was checked.
