### ISSUE TITLE
Setting page is broken in MS Edge 130.0.2849.46

### ISSUE THREAD

**Issue by mryx007** [uBlockOrigin/uBlock-issues#3419] opened 2024-10-18 11:27 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.

### Description

With the new Edge update to version 130, the settings page no longer works. It only opens a blank page. Same with the dev version of Ublock. It works normally in Chrome. Reinstalling does not work. 

### **it works as long as you do not reset or reinstall Ublock. If you do not make any changes, the setting page works**

this page opens but is completely empty
extension://odfafepnkmbhccpbejgmiehpchacaeak/dashboard.html

### uBO version

1.60

### Browser name and version

Edge

### Operating System and version

Windows 11

**Comment by SagePtr** [comment] 2024-10-19 01:04
Also newly installed uBlock Origin on MSEdge 130.0.2849.46 doesn't work at all, showing yellow icon with exclamation mark on every page.

**Comment by gwarser** [comment] 2024-10-19 06:51
@mryx007 Still works for me, even after reinstallation. Corrupted profile or some tiered testing?

**Comment by mryx007** [comment] 2024-10-19 08:07
> Also newly installed uBlock Origin on MSEdge 130.0.2849.46 doesn't work at all, showing yellow icon with exclamation mark on every page. Upd: If I import the extension from Chrome to Edge - it works without problem.

exactly the yellow icon appears and nothing works. Maybe it's the combination of Edge 130 and Windows 11 24H2

**Comment by MmyGgithubAaccount** [comment] 2024-10-19 10:07
> Also newly installed uBlock Origin on MSEdge 130.0.2849.46 doesn't work at all, showing yellow icon with exclamation mark on every page. Upd: If I import the extension from Chrome to Edge - it works without problem.

Also note to others: the import only works if ublock was installed from the chrome webstore. Won't work for "sideloaded" extensions

**Comment by Nekroz88** [comment] 2024-10-19 17:22
Same problem here.
Seems like Edge update broke the addon maybe. Last time v129 broke the profile and I had to reset/make new settings profile.
This time v130 I cannot load dashboard page at all, blank page, all white, nothing to click.
Edge profile is my mail profile, and extension is synced.

**Comment by u-RraaLL** [comment] 2024-10-19 17:36
If creating a new profile worked last time, why don't you try again? And if the issue return with the next update, maybe it's worth reporting to Edge?

**Comment by Nekroz88** [comment] 2024-10-19 17:57
> If creating a new profile worked last time, why don't you try again? And if the issue return with the next update, maybe it's worth reporting to Edge?

Creating new Edge profile = I'll have to use regular local profile, and that won't fix the issue with mail profile with ext synced.

Plus, I just did a clean install Windows on my PC fews hours ago, started Edge directly at v130. 
And thus starting Edge like this counts as "new profile" as well.

**Comment by u-RraaLL** [comment] 2024-10-19 18:35
I'm not sure what you mean by mail profile. Anyway, did you try simply reinstalling uBO or even just turning it off and on again in the extensions tab?

**Comment by Nekroz88** [comment] 2024-10-19 18:38
> I'm not sure what you mean by mail profile. Anyway, did you try simply reinstalling uBO or even just turning it off and on again in the extensions tab?

Yes, just like other people above. Havent tried installing from Chrome Store, and probably will not do that.

**Comment by garry-ut99** [comment] 2024-10-19 19:10
- https://www.reddit.com/r/uBlockOrigin/comments/1f87kei/ublock_origin_stopped_working_on_microsoft_edge/
- https://www.reddit.com/r/uBlockOrigin/comments/1ekrgal/ubo_stopped_working_in_edge/

> This time v130 I cannot load dashboard page at all, blank page, all white, nothing to click.

- https://github.com/uBlockOrigin/uBlock-issues/issues/3217

**Comment by MDnnrd** [comment] 2024-10-19 22:12
Is the incompatibility issue with Chromium based v.130 now related to Google's attempts to hinder ad blocking extensions related to MV3 that will eventually affect all Chromium based browsers? I am aware of the newer extension Lite that still works, but I like the ability to see the list of blocked links. Thanks for your hard work!

**Comment by wUEZRs** [comment] 2024-10-20 08:52
Same issue. Uninstalled uBO to test the Lite version. Unfortunately Lite does not work properly with YouTube so I swapped back. Swapping back I found the uBO being yellow and reinstalling it not working - and the settings pane empty

**Comment by Justice5656** [comment] 2024-10-20 09:13
> I had* the same issue. Uninstalled uBO to test the Lite version. Unfortunately Lite does not work properly with YouTube so I swapped back. Swapping back I found the uBO being yellow and reinstalling it not working - and the settings pane empty.
> 
> To fix it I deleted the Profile in edge, uninstalled the extension, reset the browser and removed history, then signed in again with my profile and manually installed uBlock Origin again. All good.

If you delete your profile in Edge, you lose all your saved passwords and settings right? (I want to avoid this)

**Comment by Nekroz88** [comment] 2024-10-20 11:20
> If you delete your profile in Edge, you lose all your saved passwords and settings right? (I want to avoid this)

If you fix like them, you will have to:
- Sign out of your account + delete every browser data + reset every settings => Create new local profile (not sign in) => Go to Edge store to add uBO immediately => then configure its settings => and now you can sign back in to get your other synced data such as passwords, etc....

But this would be too much of a hassle just to make an extension work....., I would rather use Adguard than spending such time just trying to make uBO work....

**Comment by gorhill** [comment] 2024-10-20 12:18
We can't reproduce such issue here. If we can't reproduce, we can't investigate, and if we can't investigate, we can't fix.

What is needed is someone with dev skills looking at the browser tools for uBO itself and see what is failing in the initialization code path.

**Comment by Nekroz88** [comment] 2024-10-20 12:52
> We can't reproduce such issue here. If we can't reproduce, we can't investigate, and if we can't investigate, we can't fix.
> 
> What is needed is someone with dev skills looking at the browser tools for uBO itself and see what is failing in the initialization code path.

Hello, I think this will help reproduce the issue. Because I just tried it on different PC and it did for me.
- Make a new or use your existing Microsoft account, to login to Edge.
- Add uBO to Edge from MS Edge store (no need to turn it on or off).
- Go to Sync settings, use Re-sync or Reset Sync option, for the browser to sync your extension data/settings to cloud.
- Delete that profile entirely, or just use another instance of Edge (like Beta or Dev).
Login to Edge using that MS account, let browser install addons by itself using synced settings.
- Now the issue will happen.

**Comment by stephenhawk8054** [comment] 2024-10-20 13:22
Creating a new microsoft account requires me to solve 20 captchas?!!
![image](https://github.com/user-attachments/assets/c80a5776-1f9d-4bd7-802a-3b6679455761)

**Comment by iam-py-test** [comment] 2024-10-20 15:00
I followed the steps to reproduce and can not. Edge syncs and installs uBo, but the dashboard opens fine and the "not ready" icon disappears as normal. uBo works as normal.
Thanks

**Comment by gorhill** [comment] 2024-10-20 15:07
I tried the steps with both Edge Linux and Edge Windows 10 (both in a VM), and could not reproduce an issue. uBO was force-installed in both Edges after signing in and was properly functioning in both cases.

**Comment by MmyGgithubAaccount** [comment] 2024-10-20 16:09
> I tried the steps with both Edge Linux and Edge Windows 10 (both in a VM), and could not reproduce an issue. uBO was force-installed in both Edges after signing in and was properly functioning in both cases.
> 
> We really need someone who can reproduce the issue to investigate using browser tools.

Might need to be on the beta channel?
![image](https://github.com/user-attachments/assets/e814e66c-98f2-4050-b0b0-47a4d8405452)

And I am on windows 11 build 27729.1000 if that matters

**Comment by MmyGgithubAaccount** [comment] 2024-10-20 16:42
I get this issue on new installs every time and can try to help debug this if someone can tell me what data to gather and how

What I've noticed is that the page keeps "refreshing"

https://github.com/user-attachments/assets/0cf530af-7d64-41c2-bec5-df9033b7b72c

https://github.com/user-attachments/assets/84a11ae5-4b64-481c-86ab-343d91f87931

These are the issues reported for the dashboard, but I'm not sure if it's relevant
![image](https://github.com/user-attachments/assets/0f6a1cdf-bc96-4c0f-a309-bd7391fe10f3)

And there's nothing in the console

**Comment by gorhill** [comment] 2024-10-20 17:11
I have the same errors reported but I can access the dashboard, all work as expected.

What needs to be looked at are the dev tools for the background process, accessible through the extensions page, with "developer tools" switch toggled on, click on "background.html" link of uBO.

**Comment by MDnnrd** [comment] 2024-10-20 17:27
I found this; I am on the Insider Preview Beta version:
[image: image.png]

**Comment by MDnnrd** [comment] 2024-10-20 17:34
When I selected the collect errors button on the extension options, this
came up:
[image: image.png]

**Comment by MDnnrd** [comment] 2024-10-20 17:37
![Screenshot 2024-10-20 133556](https://github.com/user-attachments/assets/8af569e6-e0b7-425f-bdb6-6d70ca0fe6c7)
![Screenshot 2024-10-20 133650](https://github.com/user-attachments/assets/38b0d9e4-2a61-4060-9dfd-6a349c6f1d18)

**Comment by gorhill** [comment] 2024-10-20 17:38
This is a caught exception (inside a `try-catch` block), it's inconsequential.

**Comment by MmyGgithubAaccount** [comment] 2024-10-20 18:03
![image](https://github.com/user-attachments/assets/b4f360c2-1755-40ba-b777-942da4cb02f3)
Same stuff for background.html
Nothing in console again

**Comment by gorhill** [comment] 2024-10-20 18:20
I think people suffering the issue should report to Edge developers. When uBO works in Chromium and Google Chrome, it is expected it will work as well in other Chromium-based browsers, unless they made breaking changes to extensions framework.

**Comment by Alpengreis** [comment] 2024-10-20 23:02
Same problem here. Worked before Edge Update - I had unfortunately decided to deinstall Ublock. Few days later Edge received an update - and today I decided to install Ublock again ... nothing works, just a yellow Ublock icon - that's all ...

**Comment by Nekroz88** [comment] 2024-10-21 00:22
Made a report in both Edge feedback and Edge Insider discussions:
https://techcommunity.microsoft.com/t5/discussions/edge-130-0-2849-46-official-build-64-bit-broke-extension-s/m-p/4275093#M63397
Anybody else who has the same issue may report in this as well.

**Comment by ZenFluxFurr** [comment] 2024-10-21 07:24
Same problem since i got ublock, gonna see it work someday mabe. 
Says it can't filter at browser launch. Can't access dashboard or any other settings - they just load blank page. 


OK i found how to open ublock dashboard lol. 
In edge settings create and switch to fresh profile > install ublock to new profile > open ublock dashboard> change back to your old edge profile > open ublock dashboard.

**Comment by garry-ut99** [comment] 2024-10-21 08:42
Another fresh report, someone has said that other adblockers are broken as well:
> https://www.reddit.com/r/MicrosoftEdge/comments/1g84kdm/no_ad_blocker_extension_is_working_anymore_with/ :
> NB. I don't seem to be able even to open the settings page of extensions like Adblock or ublock origin. 

In the current thread, it would be useful if you check other adblockers than uBlock as well, if they are broken, then most likely the issue is on Edge's side or users's side.

**Comment by MDnnrd** [comment] 2024-10-21 21:12
I wonder if it might be something specific to the particular version of the beta/insider version as I installed the Dev version of Edge and the extension works fine on it. We'll see when the beta one gets the next update.

**Comment by emjay2d** [comment] 2024-10-22 05:52
> I wonder if it might be something specific to the particular version of the beta/insider version as I installed the Dev version of Edge and the extension works fine on it. We'll see when the beta one gets the next update.

Thankyou. Dev version worked for me.

**Comment by GarThor** [comment] 2024-10-22 06:15
+1 also broken here.  Just after I updated to windows 11 in fact.  (dunno if that's exactly the cause, but...)

Edge Version 130.0.2849.46 (Official build) (64-bit)

**Comment by Bloodsmite** [comment] 2024-10-22 10:09
To recreate the problem simply open setting and reset settings.  You'll instantly be faced with the same problem that everyone here is experiencing.

**Comment by stephenhawk8054** [comment] 2024-10-22 10:39
> reset settings

You mean the `Reset to default settings` in uBO?

**Comment by Bloodsmite** [comment] 2024-10-22 10:44
> > reset settings
> 
> You mean the `Reset to default settings` in uBO?

My bad. Yes, that's what I meant.

"To recreate the problem simply open UBO setting and reset settings to default. You'll instantly be faced with the same problem that everyone here is experiencing."

**Comment by stephenhawk8054** [comment] 2024-10-22 10:58
I can't reproduce it. Do you need to log in to Microsoft in that profile?

https://github.com/user-attachments/assets/65843bbd-89ee-48e3-9a0c-81fc97269503

**Comment by Bloodsmite** [comment] 2024-10-22 11:02
> I can't reproduce it. Do you need to log in to Microsoft in that profile?
> 
>  msedge_R6F6jED7z0.mp4

Yes, I was logged in to my account at the time.

**Comment by stephenhawk8054** [comment] 2024-10-22 13:40
I can't reproduce with those steps when logged in either.

**Comment by Nekroz88** [comment] 2024-10-23 00:37
Reported both in Edge feedback and tech community:
https://techcommunity.microsoft.com/t5/discussions/edge-130-0-2849-46-official-build-64-bit-broke-extension-s/m-p/4275093

If anyone else still has the issue, may ad well report in tech forum so this issue can get noticed more easily.

**Comment by chris985** [comment] 2024-10-23 03:46
I can confirm I had the exact same issue reported here. I didn't do anything special. I just reinstalled Windows and let Edge bring in my SYNC data. I noticed that ublock was Yellow and not working. I tried removing and readding it and nothing worked. The extension did not work, it was in yellow, and the extension options page would not load. The whole extension seemed to be frozen up.

**FIX**

This is what worked for me, I tested it twice and confirmed this works. Someone mentioned this above but didn't really specify how to do it. Not sure why this happens but at least there is a fix. I'm giving step by step, I promise its easy and quick to actually do. And best of all this involves making a TEMPORARY profile and will not do anything to your old one, nor are we having to do anything complicated or recreate a profile.

1. Open Edge and see that it has the yellow icon for ublock.
2. Right click and remove from edge to uninstall the extension
3. Reinstall the extension (Go to the extension button, Get more from the store, search "ublock origin", "Get" and install it.) It should redownload but still have the yellow icon
4. Click on your profile in the upper left and choose "Set up New Personal Profile" (it does not work with Guest as they can't add extensions) 
5. A new window opens, choose not to import any data.
6. Go to the extension button, Get more from the store, search "ublock origin", "Get" and install it.
7. It should download and install and activate, it will have the good ol' red icon again!
8. Go to the extension button, "Extension Options" and be sure that loads as well (it should!)
9. Go back to the other window with your "broken" uBlock extension and close the window completely
10. You should now have one window open, and this is with your new profile that you created
11. Go to the upper left profile and choose your broken old profile
12. A new window will open up, with your old profile, and ublock should be red again! yay!!!
13. Switch windows and close the window with your "temporary profile"
14. Close the window with your now fixed profile
15. Open Edge one more time and ensure it stuck, it should be good to go now! (Be sure it goes to your normal profile and not the temporary one)
16. You can now delete the old profile if you want (I did) just go back up to the avatar, select the Profile 2 or whatever it called your TEMPORARY profile that you made, go to Settings and click on the trash can. BE SURE ITS THE TEMPORARY ONE
17. Enjoy the web without annoying ads, and without this weird annoying issue

**Comment by gorhill** [comment] 2024-10-23 12:26
The more people +1 [this report](https://techcommunity.microsoft.com/t5/discussions/edge-130-0-2849-46-official-build-64-bit-broke-extension-s/m-p/4275093), the more chance Edge developers are going to look into this issue.

A reminder that this reportedly also affect other blockers, not just uBO.

**Comment by ScottBeeson** [comment] 2024-10-23 17:39
Just to add more data, both users I experienced this with were logged into Edge with a M365 account.  Both were also primarily Chrome users. Not sure if relevant.

**Comment by gorhill** [comment] 2024-10-23 18:59
Quite probably related Edge issue: `https://github.com/microsoft/MicrosoftEdge-Extensions/issues/179`

**Comment by Dboingue** [comment] 2024-10-24 03:46
> Upd: If I import the extension from Chrome to Edge - it works without problem.

what do you mean exactly. You use chrome to get the extension, and the unpack it or something and use that in develop mode back into edge.  Or do you use edge on the chrome web store?

I have always used the chrome web store because there are more reviews there.  I get the same problem as many here. After I did an illadvidsed reset just to be able to look at default settings and saving those.  Now stuck. with that problem.

I did not dare "remove the extension"  yet. and then proceed as you might suggest (either understanding). should I?

**Comment by Dboingue** [comment] 2024-10-24 03:53
> 1. Open Edge and see that it has the yellow icon for ublock.
> 2. Right click and remove from edge to uninstall the extension

just checking: is 2 really necessary. or did you try without it.   I ask because of the user visible signals being the same and possibly only needing the rest of yours steps.  I guess I could try both ways... I was fearing it was google having pushed its implementatino of v3...

**Comment by stephenhawk8054** [comment] 2024-10-24 03:57
> what do you mean exactly. You use chrome to get the extension, and the unpack it or something and use that in develop mode back into edge.

I guess he means install uBO from google chrome store: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

**Closed** 2024-10-25 09:30 UTC
Labels: unable to reproduce, external, Edge

**Comment by LoonyKey** [comment] 2024-10-25 09:44
> I can confirm I had the exact same issue reported here. I didn't do anything special. I just reinstalled Windows and let Edge bring in my SYNC data. I noticed that ublock was Yellow and not working. I tried removing and readding it and nothing worked. The extension did not work, it was in yellow, and the extension options page would not load. The whole extension seemed to be frozen up.
> 
> **FIX**
> 
> This is what worked for me, I tested it twice and confirmed this works. Someone mentioned this above but didn't really specify how to do it. Not sure why this happens but at least there is a fix. I'm giving step by step, I promise its easy and quick to actually do. And best of all this involves making a TEMPORARY profile and will not do anything to your old one, nor are we having to do anything complicated or recreate a profile.
> 
> 1. Open Edge and see that it has the yellow icon for ublock.
> 2. Right click and remove from edge to uninstall the extension
> 3. Reinstall the extension (Go to the extension button, Get more from the store, search "ublock origin", "Get" and install it.) It should redownload but still have the yellow icon
> 4. Click on your profile in the upper left and choose "Set up New Personal Profile" (it does not work with Guest as they can't add extensions)
> 5. A new window opens, choose not to import any data.
> 6. Go to the extension button, Get more from the store, search "ublock origin", "Get" and install it.
> 7. It should download and install and activate, it will have the good ol' red icon again!
> 8. Go to the extension button, "Extension Options" and be sure that loads as well (it should!)
> 9. Go back to the other window with your "broken" uBlock extension and close the window completely
> 10. You should now have one window open, and this is with your new profile that you created
> 11. Go to the upper left profile and choose your broken old profile
> 12. A new window will open up, with your old profile, and ublock should be red again! yay!!!
> 13. Switch windows and close the window with your "temporary profile"
> 14. Close the window with your now fixed profile
> 15. Open Edge one more time and ensure it stuck, it should be good to go now! (Be sure it goes to your normal profile and not the temporary one)
> 16. You can now delete the old profile if you want (I did) just go back up to the avatar, select the Profile 2 or whatever it called your TEMPORARY profile that you made, go to Settings and click on the trash can. BE SURE ITS THE TEMPORARY ONE
> 17. Enjoy the web without annoying ads, and without this weird annoying issue

Thx u so much, bro. you saved me)
