### ISSUE TITLE
The overview panel will not show everything if the uBO's icon is placed in the Firefox overflow menu

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uBlock-issues#1604] opened 2021-05-26 03:43 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
You can't see about two domains in the overview panel.

### A specific URL where the issue occurs

`https://www.wired.com/`

### Steps to Reproduce

1. Install uBO
2. Click `Customize toolbar...` in Firefox application menu.
3. Move uBO's icon from toolbar to overflow menu
4. Open the website which connects to many 3rd party domain .

### Expected behavior:

uBO shows all domains.
<details><summary>Screenshot:</summary>

![Expected](https://user-images.githubusercontent.com/82331005/119597427-f04e7480-be1b-11eb-8d94-114128f5de60.png)
</details>

### Actual behavior:
The last two domains are hidden.
<details><summary>Screenshot:</summary>

![Actual](https://user-images.githubusercontent.com/82331005/119597409-e88ed000-be1b-11eb-82fa-43acec316726.png)
</details>

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firefox / v88.0.1 (stable) and latest Nightly
* Operating System and version: Windows 10 / macOS Big Sur / Ubuntu 20.04

**Comment by uBlock-user** [comment] 2021-05-26 06:20
Firefox issue -- https://bugzilla.mozilla.org/show_bug.cgi?id=1373490

**Comment by gorhill** [comment] 2021-05-26 11:26
I am pretty sure this is a duplicate of an issue already filed in the past about this.

**Comment by gorhill** [comment] 2021-05-26 11:39
I can't find the issue for now, but I do remember commenting on bugzilla about this and that the height of the missing bottom part matched the height of the header "uBlock Origin" header at the top (which is controlled by Firefox).

**Comment by uBlock-user** [comment] 2021-05-26 12:33
@gorhill duplicate of https://github.com/gorhill/uBlock/issues/3607 ?

**Comment by gwarser** [comment] 2021-05-28 13:53
https://github.com/uBlockOrigin/uBlock-issues/issues/785#issuecomment-622327450

**Closed** 2021-08-28 22:07 UTC
Labels: fixed, external, Firefox
