### ISSUE TITLE
Show full punnycode in the uBlock popup if network.IDN_show_punycode is set to true

### ISSUE THREAD

**Issue by aurora-of-earth** [uBlockOrigin/uBlock-issues#535] opened 2019-04-21 12:41 UTC
If the <code>network.IDN_show_punycode</code> is set to true on Firefox, uBlock must show the correct punnycode-format hostname in the popup window to avoid confusion.

- Look at <a href="https://www.xn--80ak6aa92e.com/">www.xn--80ak6aa92e.com</a> on Firefox with <code>network.IDN_show_punycode</code> enabled.

**Comment by uBlock-user** [comment] 2019-04-21 12:54
Duplicate of https://github.com/gorhill/uBlock/issues/2550

the popup will show a small sign in the dynamic filtering popup -- https://github.com/gorhill/uBlock/issues/2550#issuecomment-296387762

**Closed by uBlock-user** 2019-04-21 12:54 UTC

**Comment by gorhill** [comment] 2019-04-21 13:03
And anyways, uBO does not have access to entries in `about:config`.

**Comment by uBlock-user** [comment] 2019-04-21 13:07
@gorhill I don't see the small sign in Chromium though, any reason ?
