### ISSUE TITLE
Ublock Origin Element Picker/Element Remover does not work

### ISSUE THREAD

**Issue by Pflanzenkeks** [uBlockOrigin/uBlock-issues#2806] opened 2023-09-06 23:36 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

A few days ago I browsed with firefox and came across a cookie/privacy banner you needed to accept or decline in the most anoying way possible. So I tried to element pick and erase it as a filter, but i could not highlight the foreground and the background showed the colour for element picker selection but I could not interacte furthermore. The only thing i could do was click around the banner as if i did not have element picker enabled, but i can see the box on the right side but it is transparent 
 or press esc and the element picker closes. But because of time concern I did not bother so I left it as it was.

Now today I tried to erase on another website in chrome another cookie banner aswell but the same behaviour as above are shown to me. I researched a little and came across this html element called "< dialog > < / dialog >" which interferes with the element picker as it would always be in foreground and ignores anything else.

### A specific URL where the issue occurs.

`https://www.blogmojo.de/chatgpt-alternative/`

### Steps to Reproduce

1. Visit Website
2. Now Try to Element pick or Erase the Privacy Settings Banner
3. Here it fails even on multiple Browsers
![1](https://github.com/uBlockOrigin/uBlock-issues/assets/31259691/e9d98332-b4ea-42c5-b6e7-322a00da2583)
![2](https://github.com/uBlockOrigin/uBlock-issues/assets/31259691/5d427efa-468e-48bc-aa57-58643657a610)

### Expected behavior

it should be pickable and erasable as other elements

### Actual behavior

the banner ignores and stays on foreground as you did not have chosen the element picker and can be normal interacted with. And furthermore you can not interacted with the Element picker Box on the bottom right corner. It is grayed out/transparent
![3](https://github.com/uBlockOrigin/uBlock-issues/assets/31259691/47888786-d3fa-4f6e-9185-5f748e818c36)

### uBO version

uBlock Origin 1.51.0

### Browser name and version

Google Chrome Version 116.0.5845.180

### Operating System and version

Windows 10 Pro 64-Bit

**Comment by FanOfRootBeer** [comment] 2023-09-07 00:22
` https://www.blogmojo.de/wp-content/cache/asset-cleanup/js/item/content__e68f47e53d7d8286b46dd948cece81d2-js-vb1085aa38d9bec96d8d03a05e518747db7e4c237.js`
filter:
```
blogmojo.de##+js(rmnt, script, antiAdBlocker)
```

**Comment by gwarser** [comment] 2023-09-07 06:29
uBO UI ends up below the `<dialog>`. This is how the dialog works when shown in modal mode. Probably one of these cases where you need to use Dev Tools.

Wondering if `<dialog>` can be used by uBO to show the picker.

**Comment by gwarser** [comment] 2023-09-07 06:33
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2027

**Closed by gwarser** 2023-09-07 06:33 UTC
