### ISSUE TITLE
Cloud Storage in uBlock Origin seem unsupported in Microsoft Edge account sync

### ISSUE THREAD

**Issue by funnybones2015** [uBlockOrigin/uBlock-issues#1735] opened 2021-09-25 16:47 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Cloud Storage in uBlock Origin seem unsupported in Microsoft Edge account sync

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

NA

### Expected behavior

The settings and rules could be synced by Microsoft Edge account cloud storage.

### Actual behavior

The settings and rules couldn't be synced by Microsoft Edge account cloud storage for now.

### uBlock Origin version

1.38.0

### Browser name and version

Microsoft Edge 94.0.992.31

### Operating System and version

Windows 10 20H2 19042.1237

**Comment by gwarser** [comment] 2021-09-25 18:46
Was Edge issue year ago: https://www.reddit.com/r/uBlockOrigin/comments/gq1h4u/cloud_support_for_edge/

@nikrolls ?

**Comment by gwarser** [comment] 2021-09-25 19:00
Do you see any errors in `edge://sync-internals/`?

**Comment by funnybones2015** [comment] 2021-09-26 02:19
> Was Edge issue year ago: https://www.reddit.com/r/uBlockOrigin/comments/gq1h4u/cloud_support_for_edge/
> 
> @nikrolls ?

This news only shows that the extension sync has been supported by Chromium-based Edge browser. but I mean when cloud storage is enabled, the settings and adblock rules in the uBlock Origin couldn't be downloaded from Microsoft Edge account system and overwrite the default ones. The cloud storage in Edge doesn't work.

![image](https://user-images.githubusercontent.com/15063728/134790845-5f7f0f06-ffcd-4a5a-851f-ff56ff40963f.png)

**Comment by funnybones2015** [comment] 2021-09-26 02:23
> Do you see any errors in `edge://sync-internals/`?

I didn't see any errors in `edge://sync-internals/` and how to identify errors by the way?

**Comment by nikrolls** [comment] 2021-09-26 03:00
Extension settings sync is fully supported and working for me with uBlock Origin on Edge 94 (current stable build).

**Comment by funnybones2015** [comment] 2021-09-26 03:55
> Extension settings sync is fully supported and working for me with uBlock Origin on Edge 94 (current stable build).

When you delete this extension and reinstall it, then check "enable cloud storage" option, could the "import from cloud storage" and "import from cloud storage and combine with the existing settings" show up in the second tab “rule list”?

These two import from cloud storage options couldn't show up in my computer, so I couldn't use the cloud storage feature.

![msedge_hTmxepZqZK](https://user-images.githubusercontent.com/15063728/134792946-cc9bc78d-2946-4999-9bfe-4d1f49316fd5.png)

**Comment by gorhill** [comment] 2021-09-26 12:14
> These two import from cloud storage options couldn't show up in my computer, so I couldn't use the cloud storage feature.

Did you upload data to the cloud storage? If there is nothing to import, the import buttons won't show.

**Comment by funnybones2015** [comment] 2021-09-26 12:34
> > These two import from cloud storage options couldn't show up in my computer, so I couldn't use the cloud storage feature.
> 
> Did you upload data to the cloud storage? If there is nothing to import, the import buttons won't show.

yes, I've uploaded data to cloud storage.

**Comment by gorhill** [comment] 2021-09-26 14:38
I tried with MS Edge on Ubuntu, and I could export to cloud storage without any issue, even without an account -- so I can't reproduce such issue. Whoever can reproduce will have to investigate on their side, I can't investigate what I can't reproduce.

> I've uploaded data to cloud storage.

How exactly? I clicked the export button and the cloud storage widget immediately filled with the exported data, even without having to log in into an account.

> When you delete this extension and reinstall it

When you uninstall uBO, this clears all storage uBO was using, so do not expect to have cloud storage present after you re-install it. I seems to be you were expecting the cloud storage to still be filled after re-installing, which is not the case.

**Comment by funnybones2015** [comment] 2021-09-26 15:08
> I tried with MS Edge on Ubuntu, and I could export to cloud storage without any issue, even without an account -- so I can't reproduce such issue. Whoever can reproduce will have to investigate on their side, I can't investigate what I can't reproduce.
> 
> > I've uploaded data to cloud storage.
> 
> How exactly? I clicked the export button and the cloud storage widget immediately filled with the exported data, even without having to log in into an account.
> 
> > When you delete this extension and reinstall it
> 
> When you uninstall uBO, this clears all storage uBO was using, so do not expect to have cloud storage present after you re-install it. I seems to me you were expecting the cloud storage to still be filled after re-installing, which is not the case.
Do you use MS Edge on Windows?
yes, the cloud storage widget will show up even without having to log into an account. But actually, the data couldn't be really uploaded to the cloud (because there is no cloud service system working at all). In the Google Chrome browser, if you export the data to cloud storage, next time you reinstall uBlock Origin and enable cloud storage option, the three cloud storage buttons (including the export and import cloud storage buttons) will all appear. you could import the settings previously stored in cloud into the newly installed Chrome browser. But Edge browser couldn't realize this.

**Comment by funnybones2015** [comment] 2021-09-26 15:08
> I tried with MS Edge on Ubuntu, and I could export to cloud storage without any issue, even without an account -- so I can't reproduce such issue. Whoever can reproduce will have to investigate on their side, I can't investigate what I can't reproduce.
> 
> > I've uploaded data to cloud storage.
> 
> How exactly? I clicked the export button and the cloud storage widget immediately filled with the exported data, even without having to log in into an account.
> 
> > When you delete this extension and reinstall it
> 
> When you uninstall uBO, this clears all storage uBO was using, so do not expect to have cloud storage present after you re-install it. I seems to me you were expecting the cloud storage to still be filled after re-installing, which is not the case.

Do you use MS Edge on Windows?
yes, the cloud storage widget will show up even without having to log into an account. But actually, the data couldn't be really uploaded to the cloud (because there is no cloud service system working at all). In the Google Chrome browser, if you export the data to cloud storage, next time you reinstall uBlock Origin and enable cloud storage option, the three cloud storage buttons (including the export and import cloud storage buttons) will all appear. you could import the settings previously stored in cloud into the newly installed Chrome browser. But Edge browser couldn't realize this.

**Comment by gorhill** [comment] 2021-09-26 15:20
> But Edge browser couldn't realize this.

If Edge browser has that limitation, it's not a uBO issue. uBO merely use the `storage.sync` API, and all the rest is left to the browser. I will close this issue as a browser issue, so far I don't see any issue with uBO itself, and nobody else than you can reproduce an issue, it appears you just expected the cloud storage to still be present after you uninstall/reinstall uBO, which is out of uBO's control, the browser gets to decide when to wipe out cloud storage when you uninstall an extension. Report to Edge devs if you think that behavior is wrong.

**Closed by gorhill** 2021-09-26 15:20 UTC
Labels: unable to reproduce, Edge

**Comment by nikrolls** [comment] 2021-09-26 19:20
I just tried this myself, again. I'm able to remove uBlock Origin from Edge, reinstall it, and cloud storage is still there. It also syncs cloud storage properly between multiple installs on different devices signed into the same Microsoft account.

**Comment by funnybones2015** [comment] 2021-09-27 03:12
> I just tried this myself, again. I'm able to remove uBlock Origin from Edge, reinstall it, and cloud storage is still there. It also syncs cloud storage properly between multiple installs on different devices signed into the same Microsoft account.

Hi Nikrolls, did you use the last stable version of Edge on Windows 10? 
Now I describe my operation process here:
First, I downloaded the uBlock Origin from Edge extension store, install it and enable the cloud storage and make some custom settings and export the data to cloud storage. Then the export to and import from cloud storage icons all appear.
![image](https://user-images.githubusercontent.com/15063728/134839908-20c577d3-1347-40b1-982e-0bd30daa2e2f.png)


A few minites later, I delete this extension and reinstall it from Edge extension store and enable the cloud storage. Then the import from cloud storage icons didn't show up.

![image](https://user-images.githubusercontent.com/15063728/134839629-b2161cdf-7b45-4346-8cd0-f05ea0a08441.png)

**Comment by nikrolls** [comment] 2021-09-27 06:42
Yes, as stated above I used Edge 94. I verified that this is working using those steps you provided, as well as across separate devices.

I think investigation into edge://sync-internals is probably prudent, including any errors in the About tab, and looking into the "Extension settings" section of the Sync Node Browser tab.

**Comment by funnybones2015** [comment] 2021-09-27 07:33
> Yes, as stated above I used Edge 94. I verified that this is working using those steps you provided, as well as across separate devices.
> 
> I think investigation into edge://sync-internals is probably prudent, including any errors in the About tab, and looking into the "Extension settings" section of the Sync Node Browser tab.

This is the About tab screenshot below:
![image](https://user-images.githubusercontent.com/15063728/134863878-88418e7a-af88-4ec9-a6b6-7b6500baeee0.png)

This is the Extension settings screenshot:

![image](https://user-images.githubusercontent.com/15063728/134864099-1bd9e368-54e1-40be-b94c-5a8aba8f564b.png)


Pls kindly help me check if any errors. Thank you so much in advance~~
