### ISSUE TITLE
Element Picker Mode Doesn't Work on Amazon.co.uk [specifically .CO.UK]

### ISSUE THREAD

**Issue by madranet** [uBlockOrigin/uBlock-issues#485] opened 2019-03-24 13:44 UTC
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

As per title: the Element Picker Mode doesn't work on Amazon.co.uk –and specifically Amazon.CO.UK.  It works as expected on Amazon.COM

### A specific URL where the issue occurs

https://amazon.co.uk

### Steps to Reproduce

1. visit Amazon.co.uk
2: Select Element Picker

![2019-03-24_13-30-12 2 2](https://user-images.githubusercontent.com/669658/54880261-cd3e6980-4e3a-11e9-8504-2715a6aeaa0a.png)

3: Hover over elements on page

### Expected behaviour:

Page elements highlight

### Actual behaviour:

No effect [mouse is hovering over top banner in area indicated by white rectangle].

![2019-03-24_13-34-10](https://user-images.githubusercontent.com/669658/54880220-6751e200-4e3a-11e9-9796-33700ca008b5.png)

By contrast: 

1. visit Amazon.com
2: Select Element Picker
3: Hover over elements on page

### Expected behaviour:

Page elements highlight

### Actual behaviour:

Page elements highlight as expected  [mouse is hovering over top banner in area indicated by white rectangle].

![2019-03-24_13-33-20](https://user-images.githubusercontent.com/669658/54880218-5e611080-4e3a-11e9-8e39-bbe0ef28c053.png)

### Your environment

* uBlock Origin version: 1,18,10
* Browser Name and version: Yandex 19,3
* Operating System and version: OSX Mojave

**Comment by gorhill** [comment] 2019-03-24 13:46
Duplicate of <https://github.com/gorhill/uBlock/issues/3212>.

**Closed by gorhill** 2019-03-24 13:46 UTC
