### ISSUE TITLE
uBO 1.16.1rc2always crashes on Chromium 68

### ISSUE THREAD

**Issue by gallieni** [uBlockOrigin/uBlock-issues#11] opened 2018-04-23 09:02 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues), NOT here.
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

uBlock Origin 1.16.1rc2 (1.16.1rc2 from the Releases section and 1.16.1rc1 from Releases section) immediately crashes on Chromium 68.
Tested on a clean system without any leftover Chromium profiles.
uBO 1.15.24 works fine.
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

Install Chromium 68: https://github.com/henrypp/chromium/releases/download/v66.0.3359.117-r540276-win32/chromium-nosync.exe (current stable build without WebRTC)
Install uBlock Origin 1.16.1rc2

### Expected behavior:
uBO should work.
[What you expected to happen]

### Actual behavior:

[What actually happened]
uBO crashes indefinitely, restarting uBO and/or Chromium doesn't help.
### Your environment

uBlock Origin version: 1.16.1rc1 and 1.16.1rc2
Browser Name and version: Chromium 68.0.3399.0 x32 (no WebRTC)
Operating System and version: Windows 7 x86

**Comment by uBlock-user** [comment] 2018-04-23 11:28
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/9

**Closed by uBlock-user** 2018-04-23 11:28 UTC
Labels: duplicate

**Comment by uBlock-user** [comment] 2018-04-23 11:29
Stick to builds **WITH** WebRTC, aka SYNC builds, until this get sort out.

**Comment by gorhill** [comment] 2018-04-23 11:53
So again a case of ticking _"I performed a cursory search of the issue tracker to avoid opening a duplicate issue"_ without actually performing the search. The duplicate is downright [impossible to miss](https://github.com/uBlockOrigin/uBlock-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+crash).

What can be done about this?

**Comment by uBlock-user** [comment] 2018-04-23 11:55
This is what happens when everyone gets into a panic mode, need to activate chilldown mode.

**Comment by joey04** [comment] 2018-04-23 13:51
> So again a case of ticking "I performed a cursory search of the issue tracker to avoid opening a duplicate issue" without actually performing the search. The duplicate is downright impossible to miss.

> What can be done about this?

Honestly, gorhill, I doubt there's much you can do. If anything, you're a victim of your own success here -- and I mean that in a genuinely complimentary way. You've made such a powerful tool, but the vast majority of your users will never truly understand how it works. So when anything goes wrong they generally won't know what to do, other than report an issue. (Of course we don't see the sensible and careful ones who actually do check for duplicates and such.)

I'm reminded of [this comment](https://github.com/gorhill/uBlock/issues/3406#issuecomment-368283489) on the main tracker which stated it well:

> From my experience, as someone who has helped hundreds of people with their computers, people never actually read any documentation unless absolutely necessary. This includes all kinds of readmes, licenses, and other similar documents (such as CONTRIBUTING.md too). If people have read them, then I am pretty sure that at least half of the reported "issues" would not have had existed in the first place. I am not saying that it should be like that. I am rather just stating the reality, especially since GitHub is not some kind of a closed mailing list for developers, but is an open platform where anyone can register and post.

> Is is due to their laziness? Maybe. I actually believe that they simply do not consider the software and its issues important enough to spend more time on studying them. They just want a "quick fix".
