### ISSUE TITLE
Noscript prevents operation of scriptlets

### ISSUE THREAD

**Issue by deliciouslytyped** [uBlockOrigin/uBlock-issues#1975] opened 2022-02-11 21:13 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

## Meta
I clicked through the bug report checkboxes because the cause of the issue is obvious, and I wanted it written down somewhere.
Perhaps there may be a solution as well.

I could not find any information anywhere when searching for things like "ublock scriptlet noscript", which seems odd because this shouldn't be such an obscure configuration?

## Description
it should be documented that using scriptlets with NoScript is not supported, or some alternative method be supplied to achieve scriptlet functionality.
I'm not familiar with extension development, however presumably the issue is that scriptlets are injected into the same "context" that page JS is run in. Naturally, NoScript blocks this code, but disabling NoScript is a greater loss than a uBlock scriptlet not being able to run, because it's most of the time not desirable to allow the page to run any javascript at all.

Scriptlets are useful and it's a shame to not be able to use them with NoScript.
Perhaps there could be a way to run scriptlets separate from the code belonging to the domain that NoScript is blocking? - or does that go too much into userscript territory, and I should instead be using greasemonkey?

The duckduckgo example is not my actual target but it illustrates the issue.
Is there an alternative approach to removing css classes from a specific element? That's all I really want in this specific case.

### A specific URL where the issue occurs

https://duckduckgo.com/

### Steps to Reproduce

0. Have noscript, enable all blocking by default, additionally you may enable debugScriptlets in ublock advanced options.
1. go to duckduckgo.com, open the dev console, reload the page. note the logo is visible and no `debugger;` is triggered.
2. add filter rule: duckduckgo.com##+js(rc, logo_homepage, #logo_homepage_link)
3. reload duckduckgo.com. note the logo is still visible and no `debugger;` is triggered.
4. enable duckduckgo.com scripts in noscript, reload the page
5. debugger fires and the logo disappears after continuing

### Expected behavior

Scriptlets should fire.

### Actual behavior

Scriptlets did not fire.

### uBlock Origin version

1.41.2

### Browser name and version

Firefox 85.0.2

### Operating System and version

NixOS

**Comment by gwarser** [comment] 2022-02-11 21:34
You can override `.logo_homepage` style properties by `:style(...)`.

**Comment by uBlock-user** [comment] 2022-02-11 21:35
**Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).**

As per dev tools.

**Comment by uBlock-user** [comment] 2022-02-11 21:36
> Scriptlets did not fire.

**Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).**

As per dev tools.

**Comment by uBlock-user** [comment] 2022-02-11 21:41
> because it's most of the time not desirable to allow the page to run any javascript at all.

You don't need NoScript, uBO has its own [no-script](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-scripting) mode. Use that.

**Comment by gorhill** [comment] 2022-02-11 22:48
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/235>.

**Closed by gorhill** 2022-02-11 22:48 UTC
Labels: duplicate
