### ISSUE TITLE
Using multiple userResourcesLocation lists

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uBlock-issues#226] opened 2018-09-15 19:15 UTC
Description
I would like to make a suggestion that in addition to the single userResourcesLocation in AdvanceSettings  we be allowed to use a multiple scriplets lists

Would be nice feature instead of combining both and having to hand remove dups. Maybe limit to 2-3 as not to get too bizarre with it.

**Comment by troysjanda** [comment] 2019-01-25 18:08
Any dissuasion on this suggestion? I saw that Gorhill added the ability to update scriptlets now. Can this work as the filtertab does,  Ability to add more than one resource and they parse and subtract duplicates and from that make a single Resourceslist?

**Comment by uBlock-user** [comment] 2019-01-26 08:43
@gorhill

**Comment by gorhill** [comment] 2019-04-20 21:38
Fixed with <https://github.com/gorhill/uBlock/commit/a52b07ff6ef6e6b16785e237178e1cd6f38a1833>.

**Comment by gorhill** [comment] 2019-04-20 21:40
> subtract duplicates

Any duplicate will result in the previous resource being replaced by the latter one. The resource files are loading order of URL appearance, and uBO stock resource file is always loaded first.

**Closed** 2019-04-20 21:41 UTC
Labels: enhancement, fixed

**Comment by troysjanda** [comment] 2019-04-20 21:54
Thanks Mr. Gorhill. much appreciated

**Comment by felix-22** [comment] 2021-09-27 18:18
A duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/224
