### ISSUE TITLE
UBlock Origin and the private navigation Firefox

### ISSUE THREAD

**Issue by Gouldek** [uBlockOrigin/uBlock-issues#246] opened 2018-09-25 19:07 UTC
The filters of uBlock Origin recovers in zero and redo updated in every restart of the Firefox browser.

UBlock Origin does not work in private navigation...

Firefox 62.02 64 Bit and Firefox Nightly 64 Bit, on Windows 8.1 and Windows 10.

**Comment by gwarser** [comment] 2018-09-25 19:50
Duplicate of https://github.com/gorhill/uBlock/issues/3071

**Closed** 2018-09-25 19:50 UTC
Labels: duplicate
