### ISSUE TITLE
uBO 1.49 in Chromium doesn't seem able to handle case-insensitive hiding rules well

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uBlock-issues#2631] opened 2023-05-03 22:22 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I began noticing in mid-April that case-insensitive attribute values no longer worked correctly in uBO in Chromium browsers (whereas they worked before, and still works in "AdGuard for Chromium" and in uBO in Firefox). For instance `deviantart.com##a[data-hook][href*="/art/"][href*="-adopt-" i]`.

My perception of the situation is that uBO's methods to hide elements, are treating attribute values as case-sensitive even if they have the `i` at the end to mark case-insensitivity. The logger, on the other hand, correctly treats them as case-insensitive, leading to that going to the logger → `</>` shows the elements that were *supposed* to be hidden, as having a red tint over them to show that the logger treats them as hidden.

Pasting case-insensitive entries into the element picker and clicking "Choose", does at times seem to correctly hide the elements case-insensitively, though simply pasting hundreds of entries into "My Filters" only works inconsistently at best.

I incorrectly believed in the past 2 weeks that this was a Chromium engine update bug, but I'm now 80% confident that it's a regression in uBO 1.49 or 1.48.

### A specific URL where the issue occurs.

https://www.deviantart.com/search?q=adopt

### Steps to Reproduce

1) Add `deviantart.com##a[data-hook][href*="/art/"][href*="-adopt-" i]` to a custom filterlist, then add the custom filterlist to uBO.
2) Visit deviantART and search for "adopt".
3) See that results whose URLs match "Adopt" or "ADOPT" are not blocked.

### Expected behavior

`deviantart.com##a[data-hook][href*="/art/"][href*="-adopt-" i]` blocks deviantART search results whose URLs case-insensitively match `-adopt-`.

### Actual behavior

`deviantart.com##a[data-hook][href*="/art/"][href*="-adopt-" i]` either only case-sensitively block deviantART search results whose URLs match `-adopt-`, or fails to block anything at all (The exact outcome seems to differ depending on unknown causes).

### uBO version

1.49.2

### Browser name and version

Chrome 112.0.5615.138 x64, as well as Vivaldi 6.0.2979.18 x64

### Operating System and version

Windows 11 22H2 x64

**Comment by gorhill** [comment] 2023-05-03 22:32
I cannot reproduce, I get 4 elements hidden with your cosmetic filter at the given webpage:

![Screenshot from 2023-05-03 18-30-09](https://user-images.githubusercontent.com/585534/236065183-9c6bd590-e8c0-4476-a035-8902c31e8b9f.png)

**Comment by DandelionSprout** [comment] 2023-05-03 22:37
This is what the results are supposed to be (Tested in AdGuard):

<details>

![image](https://user-images.githubusercontent.com/22780683/236065597-2b816822-8bfc-4f9f-9180-86806e5b1948.png)

</details>

Whereas these are the results on my end with uBO 1.49.2:

<details>

![image](https://user-images.githubusercontent.com/22780683/236065809-2a623d40-3557-4b18-aee3-5e6464c97643.png)

</details>

**Comment by gorhill** [comment] 2023-05-03 22:45
I get the same result as uBO with AdGuard and your filter, at that webpage.

Furthermore, the dev console returns exactly the same elements as uBO's targeted elements:

    > 18:44:23.508 document.querySelectorAll('a[data-hook][href*="/art/"][href*="-adopt-" i]');
    > 18:44:23.530 NodeList(4) [a, a.uU5En, a, a.uU5En]

**Comment by gorhill** [comment] 2023-05-03 22:53
The proper way to investigate this is not to show screenshots, it's to dig to find an exact element which you think should have been targeted by the filter while it is not. The browser's own dev tools confirm uBO properly targeted the matching elements, which is expected since it's the browser doing the work in the end when a cosmetic filter is declarative.

**Comment by DandelionSprout** [comment] 2023-05-03 23:01
Doing additional research now, I'm wondering if me using `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/a.txt` and `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiCartoonHipsterList.txt` (which combined have 3,300 specific entries for deviantART) could be hitting some kind of max cache limit; though I need to squeeze in a nap before a café job in 7 hours. I promise I'll continue looking into the case within 24 hours.

**Comment by gorhill** [comment] 2023-05-03 23:05
I collated all the `a.href` on that page and this is what I get:

<details><summary>all a.href</summary

```
https://www.deviantart.com/onldaff/art/Adopt-auction-24-CLOSED-719442875
https://www.deviantart.com/onldaff/art/Adopt-auction-24-CLOSED-719442875
https://www.deviantart.com/onldaff
https://www.deviantart.com/onldaff
https://www.deviantart.com/mortymillian/art/ADOPT-AUCTION-OPEN-893131000
https://www.deviantart.com/mortymillian/art/ADOPT-AUCTION-OPEN-893131000
https://www.deviantart.com/mortymillian
https://www.deviantart.com/mortymillian
https://www.deviantart.com/chomga-anna-dakota/art/adoptable-pack-OPEN-1-3-909240075
https://www.deviantart.com/chomga-anna-dakota/art/adoptable-pack-OPEN-1-3-909240075
https://www.deviantart.com/chomga-anna-dakota
https://www.deviantart.com/chomga-anna-dakota
https://www.deviantart.com/nomii66/art/adopt-auction-CLOSED-922689540
https://www.deviantart.com/nomii66/art/adopt-auction-CLOSED-922689540
https://www.deviantart.com/nomii66
https://www.deviantart.com/nomii66
https://www.deviantart.com/byeeol/art/ADOPTABLE-AUCTION-CLOSED-883011031
https://www.deviantart.com/byeeol/art/ADOPTABLE-AUCTION-CLOSED-883011031
https://www.deviantart.com/byeeol
https://www.deviantart.com/byeeol
https://www.deviantart.com/nititi-adoptable/art/Adoptable-4-CLOSED-796305685
https://www.deviantart.com/nititi-adoptable/art/Adoptable-4-CLOSED-796305685
https://www.deviantart.com/nititi-adoptable
https://www.deviantart.com/nititi-adoptable
https://www.deviantart.com/byeeol/art/ADOPTABLE-AUCTION-CLOSED-868625102
https://www.deviantart.com/byeeol/art/ADOPTABLE-AUCTION-CLOSED-868625102
https://www.deviantart.com/byeeol
https://www.deviantart.com/byeeol
https://www.deviantart.com/finchwing/art/Adoptables-batch-bid-CLOSED-650528937
https://www.deviantart.com/finchwing/art/Adoptables-batch-bid-CLOSED-650528937
https://www.deviantart.com/finchwing
https://www.deviantart.com/finchwing
https://www.deviantart.com/reiki-kun/art/Adopts-Bubble-Tea-Babes-CLOSED-731501374
https://www.deviantart.com/reiki-kun/art/Adopts-Bubble-Tea-Babes-CLOSED-731501374
https://www.deviantart.com/reiki-kun
https://www.deviantart.com/reiki-kun
https://www.deviantart.com/hauket/art/Halloween-Ren-Fairs-AUCTION-closed-569729555
https://www.deviantart.com/hauket/art/Halloween-Ren-Fairs-AUCTION-closed-569729555
https://www.deviantart.com/hauket
https://www.deviantart.com/hauket
https://www.deviantart.com/piffi-sisters/art/CLOSED-ADOPT-Auction-15-400443019
https://www.deviantart.com/piffi-sisters/art/CLOSED-ADOPT-Auction-15-400443019
https://www.deviantart.com/piffi-sisters
https://www.deviantart.com/piffi-sisters
https://www.deviantart.com/sr1023/art/Areques-Adoptable-closed-852295241
https://www.deviantart.com/sr1023/art/Areques-Adoptable-closed-852295241
https://www.deviantart.com/sr1023
https://www.deviantart.com/sr1023
https://www.deviantart.com/amsbt/art/Werewolf-Adoptables-AUCTION-OPEN-691600180
https://www.deviantart.com/amsbt/art/Werewolf-Adoptables-AUCTION-OPEN-691600180
https://www.deviantart.com/amsbt
https://www.deviantart.com/amsbt
https://www.deviantart.com/nunaku/art/Adoptable-Cosmic-Traitor-931246486
https://www.deviantart.com/nunaku/art/Adoptable-Cosmic-Traitor-931246486
https://www.deviantart.com/nunaku
https://www.deviantart.com/nunaku
https://www.deviantart.com/vel0w/art/NB-MORAY-EEL-ADOPTABLE-AUCTION-48H-OPEN-887177285
https://www.deviantart.com/vel0w/art/NB-MORAY-EEL-ADOPTABLE-AUCTION-48H-OPEN-887177285
https://www.deviantart.com/vel0w
https://www.deviantart.com/vel0w
https://www.deviantart.com/dreamyskullz/art/Adoptable-Menhera-Kitty-CLOSED-747304969
https://www.deviantart.com/dreamyskullz/art/Adoptable-Menhera-Kitty-CLOSED-747304969
https://www.deviantart.com/dreamyskullz
https://www.deviantart.com/dreamyskullz
https://www.deviantart.com/thesketchnest/art/Closed-Citrus-Tide-Pool-880927911
https://www.deviantart.com/thesketchnest/art/Closed-Citrus-Tide-Pool-880927911
https://www.deviantart.com/thesketchnest
https://www.deviantart.com/thesketchnest
https://www.deviantart.com/toxiccatxd/art/Adopt-Set-Price-424-SOLD-892757997
https://www.deviantart.com/toxiccatxd/art/Adopt-Set-Price-424-SOLD-892757997
https://www.deviantart.com/toxiccatxd
https://www.deviantart.com/toxiccatxd
https://www.deviantart.com/rianiie/art/adoptable-auction-01-CLOSED-892329339
https://www.deviantart.com/rianiie/art/adoptable-auction-01-CLOSED-892329339
https://www.deviantart.com/rianiie
https://www.deviantart.com/rianiie
https://www.deviantart.com/toxiccatxd/art/Sketch-Design-Adopt-18-SOLD-894549062
https://www.deviantart.com/toxiccatxd/art/Sketch-Design-Adopt-18-SOLD-894549062
https://www.deviantart.com/toxiccatxd
https://www.deviantart.com/toxiccatxd
https://www.deviantart.com/skelefrog/art/CLOSED-Frog-s-Big-Ol-Chimereon-Guest-Auction-792426148
https://www.deviantart.com/skelefrog/art/CLOSED-Frog-s-Big-Ol-Chimereon-Guest-Auction-792426148
https://www.deviantart.com/skelefrog
https://www.deviantart.com/skelefrog
https://www.deviantart.com/dynavera/art/CLOSED-856890260
https://www.deviantart.com/dynavera/art/CLOSED-856890260
https://www.deviantart.com/dynavera
https://www.deviantart.com/dynavera
https://www.deviantart.com/mohnot/art/Adoptables-auction-39-open-877083763
https://www.deviantart.com/mohnot/art/Adoptables-auction-39-open-877083763
https://www.deviantart.com/mohnot
https://www.deviantart.com/mohnot
https://www.deviantart.com/byeeol/art/ADOPTABLE-AUCTION-CLOSED-871455906
https://www.deviantart.com/byeeol/art/ADOPTABLE-AUCTION-CLOSED-871455906
https://www.deviantart.com/byeeol
https://www.deviantart.com/byeeol
```

</details>

Only four matches `-adopt-` in a case-insensitive way.

**Comment by DandelionSprout** [comment] 2023-05-04 17:19
I seem to have found a fix for it today, but have been unsure how to word it, since it seems to make extensive debugging no longer all that necessary, and that the fix and cause sounds odd:

The problem turned out to not be with the `deviantart.com##a[data-hook][href*="/art/"][href*=-adopt- i]` syntax entries I used, but rather with the `deviantart.com#?#div[style^="width:"][style*="display:"]:has(a[href*="/art/"][href*=-adopt- i])` syntaxing that I used in the same lists, the latter of which somehow seemed to break hiding in such a way that neither syntax worked as intended.

Given the extreme rarity of this situation, especially so for filterlist makers, I chose to convert the latter syntax into singular very long entries like https://github.com/DandelionSprout/adfilt/blob/bad553effe8b3581b9a7083c9b3ab85b290ef5bf/DeviantARTQualityArtMagnifier.txt#L11, which somehow managed to fix the problem, despite me never being sure what the exact cause was (My loose bet is on cache problems).

**Comment by gorhill** [comment] 2023-05-04 17:22
> `[href*=-adopt- i]`

You are missing quotes: `[href*="-adopt-" i]`

**Comment by gorhill** [comment] 2023-05-08 20:29
Closing as _unable to reproduce_ since I was not able to reproduce an issue.

**Closed by gorhill** 2023-05-08 20:29 UTC
