### ISSUE TITLE
uBO not working on Latest Firefox Quantum

### ISSUE THREAD

**Issue by Kogam22** [uBlockOrigin/uBlock-issues#559] opened 2019-05-04 14:20 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
The problem is according to mozilla they are signing addons after verifying them. So, they had an option to disable this by going to `about:config` and setting `extensions.langpacks.signatures.required` to false which I did. By it's not working. Even other extensions are marked as legacy. Tried again after restarting Firefox to no avail.

If I try downloading from the addons website, I see this : 
![image](https://user-images.githubusercontent.com/22547069/57180288-aac15680-6ea4-11e9-8299-f2bae6432735.png)

### A specific URL where the issue occurs
N/A
[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step] Install Firefox.
2. [Second Step] Install uBO.
3. [and so on...] Change `extensions.langpacks.signatures.required` and restart browser.

### Expected behavior:

[What you expected to happen]

Should've worked after changing the boolean.

### Actual behavior:

[What actually happened]

Didn't work. Then I tried in The Developer version of Firefox and it did work. I Hope it works in the normal one too.

### Your environment

* uBlock Origin version: v1.18.16
* Browser Name and version: Firefox Quantum v66.0.3 (64-bit)
* Operating System and version: Windows 10

**Comment by gorhill** [comment] 2019-05-04 14:27
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/559>.

**Comment by Kogam22** [comment] 2019-05-04 14:27
@gorhill Duplicate of same ?

**Closed by gorhill** 2019-05-04 14:27 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2019-05-04 14:28
Bad cut and paste. Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/558>.

**Comment by Kogam22** [comment] 2019-05-04 14:29
Oh so it was #558. Thanks @gorhill .
