### ISSUE TITLE
The extension does not block ads on twitch

### ISSUE THREAD

**Issue by Gomido** [uBlockOrigin/uBlock-issues#1360] opened 2020-11-23 22:14 UTC
# Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

By simply watching the stream, it often takes an advertising break. uBlock used to block ads in stream, now it doesn't.

### A specific URL where the issue occurs

https://www.twitch.tv/channel_name

### Steps to Reproduce

1. Open Twitch.tv
2. Select random channel
3. Just wait watching stream

### Expected behavior:

When turned on, the stream should run immediately, and there should be no ad breaks while watching

### Actual behavior:

Advertising appears frequently when the stream is launched. Similarly, there is a break for advertising.
https://i.imgur.com/FbIdepN.png

### Your environment

* uBlock Origin version: uBlock Origin development build v1.31.1b2
* Browser Name and version:  Chrome 87.0.4280.66
* Operating System and version: Windows 10 20H2 (19042.610)

**Comment by krystian3w** [comment] 2020-11-23 22:21
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/5184

**Comment by krystian3w** [comment] 2020-11-23 22:23
Twitch po prostu już umie nadpisywać szybko działanie skryptletu `twitch-videoad`.

Pomóc może tylko dodanie obsługi parametrów, jak Twitch nie skonwertuje reklam na SSAI niekompatybilne z #760.

**Comment by gwarser** [comment] 2020-11-23 22:31
This is working for now: https://www.reddit.com/r/uBlockOrigin/comments/jjesgn/fix_for_ublock_origin_on_twitch_i_updated_the/

**Closed by gwarser** 2020-11-23 22:31 UTC
