### ISSUE TITLE
uBO's content scripts broken on inactive tabs at browser launch with TamperMonkey or ViolentMonkey enabled

### ISSUE THREAD

**Issue by gh0sti** [uBlockOrigin/uBlock-issues#1612] opened 2021-06-03 17:00 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Cosmetic filtering not working in Brave browser

### A specific URL where the issue occurs

reddit.com
sponsor posts are showing up, sign up for reddit gold, and the element picker when selected doesn't work or load and right click  context menu block ad stopped working.  

This feature was working as of yesterday in Brave. All lists are up to date.

### Steps to Reproduce

1. Run brave browser stable and have ublock origin stable installed
2. load reddit.com or old.reddit.com
3. try blocking cosmetic ads, sponsor ads, or try using element picker

### Expected behavior:

For the element picker to work and for cosmetic ads to be blocked

### Actual behavior:

none of the ads are being blocked properly on Reddit

### Your environment

* uBlock Origin version: 1.35.2 also 1.35.3.7
* Browser Name and version: Brave Browser 1.25.68
* Operating System and version: Windows 10 21H1

**Comment by uBlock-user** [comment] 2021-06-03 17:14
Disable Brave's built-in blocker and then try again.

**Comment by gorhill** [comment] 2021-06-03 17:43
I am unable to reproduce.

However when trying to confirm the page I was looking at did have `.promotedlink` elements in it, using the logger's DOM inspector, I did confirm it had those elements. When I toggled off the cosmetic filtering switch and forced a reload of the page, the `.promotedlink` elements became visible. Toggling cosmetic filtering switch back on and forcing a reload of the page, the `.promotedlink` elements disappeared.

**Comment by gh0sti** [comment] 2021-06-03 18:10
I did turn off braves built in adblocker and still cosmetic filtering isn't working correctly.

**Comment by gorhill** [comment] 2021-06-03 22:04
Closing this as external. If somebody who can reproduce investigates and find that there is something to change in uBO, then I will reopen.

**Comment by trlkly** [comment] 2021-06-03 22:08
I am seeing this issue on http://boards.straightdope.com using Chrome 91. I noticed it right after the upgrade. 

The element picker won't show up, and cosmetic filters don't load. So, for instance, the ad div on the top shows, even though the ad itself is blocked, and I can't use the element picker to try and hide it. 

I didn't see any errors in the console on the background.html page for the addon. 

After reading this bug, I tried looking through the settings to see if there was something I could disable, but nothing I found changed anything. I lowered my security settings, disable the ad trial, and so on, but nothing changed. 

Oddly, reddit.com seems to work just fine. So perhaps this is a different bug. But it does say Chromium 91 in the title.

**Comment by gorhill** [comment] 2021-06-04 11:30
Simlar reports involving browsers based on Chromium 91, with symptoms which suggest uBO's content scripts aren't injected:

- https://www.reddit.com/r/uBlockOrigin/comments/npu743/element_picker_no_longer_working_on_some_pages/
    - "I opened the exact same page on a new tab and there it worked!"
- https://www.reddit.com/r/uBlockOrigin/comments/nrzx3l/ublock_doesnt_properly_activate_on_relaunched/
    - "It works only on the new tabs, not the already launched ones."
- https://www.reddit.com/r/uBlockOrigin/comments/nmsr4e/reddit_and_youtube_ads_no_longer_blocked_after/
- https://www.reddit.com/r/uBlockOrigin/comments/nlsnxu/suddenly_im_seeing_ads_everywhere/

It seems something changed in Chromium 91 which is causing this issue. In [this report](https://www.reddit.com/r/uBlockOrigin/comments/npu743/element_picker_no_longer_working_on_some_pages/
), user narrowed down to already opened tab at launch, and that the only workaround was to open the page in a new tab. I still can't reproduce on my side, so there might be something else required to trigger the issue.

**Comment by Beanzy** [comment] 2021-06-04 23:09
Seems to reliably occur on pinned tabs for me fwiw.

**Comment by uBlock-user** [comment] 2021-06-04 23:21
follow through this [comment](https://github.com/uBlockOrigin/uBlock-issues/issues/1609#issuecomment-851635744) and report back with results.

**Comment by Yuki2718** [comment] 2021-06-05 07:30
No issue on Brave 1.25.70 (Chromium: 91.0.4472.77)

**Comment by trlkly** [comment] 2021-06-05 08:15
I can confirm that opening a new tab does work, but not if I middle click on the reload button. I have to actually middle click on a link the window.  However, I've only seen it affect the one site I mentioned, which was the page I first loaded after upgrading to Chrome 91. 

Possibly more useful info: I also notice that an extension I installed as a temporary workaround does not have this problem, so perhaps looking at what it does differently could be illuminating: 

https://chrome.google.com/webstore/detail/click-to-remove-element/jcgpghgjhhahcefnfpbncdmhhddedhnk

**Comment by gorhill** [comment] 2021-06-05 11:17
> not if I middle click on the reload button

Is it possible this is a one time issue following browser update? Does the issue occurs again for tabs that were opened after the update?

I think what would help is stepping in the code of the content script in the afflicted tab to find out if and why it's bailing out (possibly at [that line](https://github.com/gorhill/uBlock/blob/0718d816e1f509f0b36cdb1cf3f490a0045efe99/src/js/contentscript.js#L107)), which it seems is what is happening.

**Comment by Kobata** [comment] 2021-06-05 13:56
Some debugger results:

A tab that is broken fails at [these lines](https://github.com/gorhill/uBlock/blob/0718d816e1f509f0b36cdb1cf3f490a0045efe99/src/js/contentscript.js#L1324-L1329), specifically, that there is *never* a response to the message, and so `bootstrapPhase1` never happens.

Unfortunately the basic page debugger doesn't seem to be able to get much farther than that, since the other vapi stuff is never loaded into even working pages.

**Comment by gorhill** [comment] 2021-06-05 14:03
> there is never a response to the message

Thanks for helping investigate this.

> since the other vapi stuff is never loaded into even working pages

Not sure I understand your statement here. What is the "other vapi stuff" you are referencing here? I gather than if your breakpoint at the line you link to is taken, this means the global `vAPI` variable is present in uBO's content script.

Now given your finding, I would be curious if the message is received by uBO's background process, and to find out whether this is the case, a breakpoint can be put at [that line](https://github.com/gorhill/uBlock/blob/0718d816e1f509f0b36cdb1cf3f490a0045efe99/src/js/messaging.js#L676) in the background process (not sure if you know how to debug the background process: need to enable "Developer Mode" in `chrome://extensions/` then click uBO's `background.html` link).

**Comment by Kobata** [comment] 2021-06-05 14:14
> Not sure I understand your statement here. What is the "other vapi stuff" you are referencing here? 
Figuring out how to debug the extension was what I needed there.

The extension side appears to receive it and then die [here](https://github.com/gorhill/uBlock/blob/0718d816e1f509f0b36cdb1cf3f490a0045efe99/src/js/messaging.js#L636), and indeed one thing I noticed was the broken page doesn't have `contentscript-extra.js` loaded.

Which.... if I follow how everything's going, eventually calls [`chrome.tabs.executeScript`](https://developer.chrome.com/docs/extensions/reference/tabs/#method-executeScript), which is listed as deprecated since 91, although that shouldn't mean it's immediately broken.

**Comment by gorhill** [comment] 2021-06-05 14:50
> then die here

When you say it dies, do you mean an exception is thrown and execution is aborted at that line, preventing the message handler from returning an answer? (i.e. a breakpoint is never triggered at [that line](https://github.com/gorhill/uBlock/blob/0718d816e1f509f0b36cdb1cf3f490a0045efe99/src/js/messaging.js#L648)?)

`contentscript-extra.js` is used to enforce procedural cosmetic filters, so the issue would occur typically on sites for which there are procedural cosmetic filters, so `reddit.com`, `youtube.com` for instances.

If an exception is thrown by `chrome.tabs.executeScript`, I could wrap the call into a try-catch block to prevent severe breakage, though that would still break features enabled by programmatic content script injection.

**Comment by Kobata** [comment] 2021-06-05 14:52
I do not see any errors in either log, it simply... stops at that point, and never continues.

**Comment by gorhill** [comment] 2021-06-05 15:00
Alright, I have no idea how to work around this then. The call works fine on my side, so it appears it starts to fail for unknown reasons at some point. If you try to reproduce in a new tab, it works fine? If so, you still suffer the issue for that new tab at next browser launch?

**Comment by gorhill** [comment] 2021-06-05 15:02
There are a number of opened issues in Chromium issue tracker involving `tabs.executeScripts`, but I can't tell if any of these is related to the issue reported here: <https://bugs.chromium.org/p/chromium/issues/list?q=tabs.executeScript>.

**Comment by gorhill** [comment] 2021-06-05 15:04
Did you try to put a breakpoint somewhere in the `contentscript-extra.js` code to find out if it's injected, but fail to complete or something?

**Comment by Kobata** [comment] 2021-06-05 15:11
> If you try to reproduce in a new tab, it works fine?
New tabs work correctly.
> If so, you still suffer the issue for that new tab at next browser launch?
Tabs fail if they are *not* the currently active tab in the window on launch. It remains persistent until next relaunch, in which case the currently active tab for that relaunch (and any newly created tabs) are fine, and all background tabs are broken.

> Did you try to put a breakpoint somewhere in the `contentscript-extra.js` code to find out if it's injected, but fail to complete or something?
`contentscript-extra.js` does not trigger a breakpoint, or even show up on the main frame's content script source list (this is a bit weird on reddit, since it *does* appear to but only in their background chat app iframe, not the main site's page)

**Comment by gorhill** [comment] 2021-06-05 15:17
Do you have other extensions installed beside uBO? I am trying to find out why I can't reproduce, and I am wondering if this could be occur because another extension based on MV3 is in use. The mystery now is why this can't be reproduced by all.

**Comment by Kobata** [comment] 2021-06-05 15:24
I do have others, playing with enabling them it appears [tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) being enabled at the same time is the direct cause. Which, finding the files for, is still a V2.

**Comment by gorhill** [comment] 2021-06-05 15:50
Great! Thanks for helping narrow down the issue -- I installed Tampermonkey and now I could reproduce the issue on `https://www.reddit.com/`, I will see what I can find with investigating further.

**Comment by gorhill** [comment] 2021-06-05 16:30
I could also reproduce the issue with ViolentMonkey, and the issue seems to be with the `declarativeContent` API. If I comment out [this code](https://github.com/violentmonkey/violentmonkey/blob/8a319d0312004ef827efbf34c56e0f66602726cf/src/background/index.js#L166-L179) in ViolentMonkey, the issue goes away.

**Comment by gorhill** [comment] 2021-06-05 17:21
Here is a minimal extension which breaks uBO's use of `tabs.executeScript()`:

manifest.json
```json
{
   "background": {
      "scripts": [ "background.js" ]
   },
   "manifest_version": 2,
   "name": "declarativeContent issue",
   "permissions": [ "declarativeContent" ],
   "version": "1.0.0"
}
```

background.js
```javascript
const api = chrome.declarativeContent;
api.onPageChanged.getRules(['inject'], rules => {
    if (rules.length) return;
    api.onPageChanged.addRules([{
        id: 'inject',
        conditions:[ new api.PageStateMatcher({pageUrl:{urlContains:"://"}}) ],
        actions:[ new api.RequestContentScript({js: ["empty.js"]}) ]
    }]);
});
```

empty.js
```javascript
```

**Comment by gorhill** [comment] 2021-06-05 18:17
https://bugs.chromium.org/p/chromium/issues/detail?id=1216788

**Comment by ryanbr** [comment] 2021-06-06 01:51
If its a recent regression, is there a specific commit that caused the breakage. Which could be highlighted in the report

**Comment by uBlock-user** [comment] 2021-06-07 10:42
> I can reproduce the issue on M91 branch following the reproduce steps on the description but there is no the issue on M92, M93 or the current ToT.

Seems this issue is isolated to v91.

**Comment by FTOH** [comment] 2021-06-09 03:48
Another way to reproduce
1. Enable TamperMonkey
2. Duplicate tab (middle click on refresh button or via context menu)

To fix issue on some tab:
1. Close tab (Ctrl+W)
2. Reopen tab (Ctrl+Shift+T)

**Comment by gh0sti** [comment] 2021-06-09 19:14
So looks like Google has to fix the issue in the next Chromium update. I didn't even think to check tampermonkey which I do have that extension enabled but kept thinking it had to deal with brave shields.

**Comment by derjanb** [comment] 2021-06-10 18:40
FWIW: In Tampermonkey you can work around the problem by setting "Injection Mode" to "Instant" ("Config Mode" needs to be set to "Advanced" in order to see this setting), since then no declarativeContent rule is used anymore.

**Comment by derjanb** [comment] 2021-06-10 20:07
> However, I also didn't restart the browser.

I think a browser restart is necessary.

> if they do merge the fix to M91, would that mean we'd get an out-of-band update to Chrome that would fix this?

Looks like they will merge the fix. And yes, I think so.

**Closed** 2021-06-10 20:24 UTC
Labels: Chromium, external

**Comment by nihaals** [comment] 2021-06-15 13:05
The [fix](https://github.com/chromium/chromium/commit/1210d51d3ea3dee472310a590d8af454896d0f62) is part of `91.0.4472.106` and Chrome stable has [bumped its version](https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop_14.html) to include the fix, so you should see a Chrome update soon:tm: as it rolls out
