### ISSUE TITLE
Parse and enforce cosmetic filters is blocking Gmail conversation threads

### ISSUE THREAD

**Issue by GitHub-mnm** [uBlockOrigin/uBlock-issues#2024] opened 2022-03-02 05:30 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Within Settings, the option to Parse and enforce cosmetic filters when checked, is now blocking Gmail conversation threads. You can see the emails but after clicking on one, the email conversations disappear and you only see the subject. so you can't read emails. When this feature is unchecked and the Gmail page is refreshed, you can see  the email conversations. If left unchecked, this presents another problem and you can see annoying ads everywhere.

### A specific URL where the issue occurs

Gmail

### Steps to Reproduce

1. Go to uBlock Origin's gear icon for Settings
2. check the option to Parse and enforce cosmetic filters to enable
3. open Gmail. click on an email
4. the  conversations disappear and you only see the subject. so you can't read emails. 
5. return to uBlock Origin's gear icon for Settings
6. uncheck the option to Parse and enforce cosmetic filters
7. Go back to Gmail and refresh
8. you can now see your email conversations

### Expected behavior

in the past, checking the option to Parse and enforce cosmetic filters would result in being able to read Gmail conversations without any problem.

### Actual behavior

the opposite happens 

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 97.0.1 (64-bit)

### Operating System and version

Mac OS Big Sur 11.6.4

**Comment by uBlock-user** [comment] 2022-03-02 05:32
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906

**Closed by uBlock-user** 2022-03-02 05:32 UTC
