### ISSUE TITLE
Copy function is grayed out

### ISSUE THREAD

**Issue by yaniyaniyaniyaniyaniyani** [uBlockOrigin/uBlock-issues#3067] opened 2024-01-10 21:57 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I attempt to copy from a web page the copy item in the menu is grayed out. Happens on 90%+ of web sites. Happens on both Linux and Windows and on Firefox Minefield and Developer.

It's been reported on Bugzilla. It's been going on for over 2 months and I'd thought it would have been reported previously.

### A specific URL where the issue occurs.

facebook.com

### Steps to Reproduce

1. Attempt a copy
2. Menu is grayed out
3. Switching to read mode in FF or just hitting the uBO icon in the taskbar fixes the issue for that page. 

### Expected behavior

Copy not grayed out

### Actual behavior

As above

### uBO version

uBlock Origin 1.54.0

### Browser name and version

Firefox developer 122

### Operating System and version

Windows but it happens in Linux too

**Comment by gorhill** [comment] 2024-01-11 00:28
Duplicate of <https://github.com/uBlockOrigin/uAssets/discussions/21700>.

**Closed by gorhill** 2024-01-11 00:28 UTC
