### ISSUE TITLE
Show a warning to users who enable only the built-in lists

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBlock-issues#442] opened 2019-02-28 21:50 UTC
Even an advanced user might enable a built-in list such as `uBlock Annoyances` without enabling one of the required third-party lists first. Example: https://github.com/uBlockOrigin/uAssets/issues/5030. 

In this case, uBlock Origin could show an exclamation mark or a plain text message telling these people to enable `Adguard Annoyances` or `Fanboy's Annoyances` as well.

**Comment by okiehsch** [comment] 2019-02-28 21:57
You can use `uBlock Annoyances` as a standalone list my [comment](https://github.com/uBlockOrigin/uAssets/issues/5030#issuecomment-468447115) was meant to say that no filters will be added to `uBlock Annoyances` if the issue is already fixed in `Adguard Annoyances` or `Fanboy's Annoyances`, so enabling those lists is not required.
`uBlock Annoyances` as a standalone list is for example useful if someone is annoyed by all those pesky sites that disable right-click ability.

**Comment by adranger** [comment] 2019-02-28 22:38
Yes, you can. That's why I'm saying it's a good idea to tell people that the built-in lists are supplemental, and not all-inclusive replacements.

**Comment by okiehsch** [comment] 2019-02-28 22:47
I can see that point, my comment was not meant to reject your idea outright only to clarify.

**Comment by jsEveryDay** [comment] 2019-03-01 03:43
I guess you could show an icon with a tool tip to tell the users this is important, nothing as a "warning or alert". But all you can say is ublock recommends this, which I find unnecessary and its better for ublock to remain neutral as is.

**Comment by gorhill** [comment] 2019-03-15 14:15
I will just move "uBlock filters -- Annoyances" to the "Annoyances" section.

**Closed** 2022-09-09 23:29 UTC
Labels: enhancement
