### ISSUE TITLE
Dont disable prerender option by default to leverage the new speculative rules api

### ISSUE THREAD

**Issue by Tylopilus** [uBlockOrigin/uBlock-issues#3111] opened 2024-02-09 09:17 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

With the new speculative rules API in the works: https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API
We have now the possibility to make pageloads an instant. Sadly uBlock Origin shuts this down as it disables prerendering in chrome unless you actively activate that feature. > https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-prefetching

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/45148577/871bb1e5-fced-4492-871b-a5ac6f63bbef)

Please don't make it disabled by default as it is mandatory for users to experience the new API

### A specific URL where the issue occurs.

```yaml
https://speculative-rules.glitch.me/
```

### Steps to Reproduce

1. go to https://speculative-rules.glitch.me/ and open the devtools -> application -> background services -> speculative loads
2. hover links and see error
3. navigate to settings: chrome://settings/performance
4. hover the puzzle icon in the preload pages section to get the info that it is coming from uBlock origin

### Expected behavior

uBlock Origin does not shut this feature down and works along side it

### Actual behavior

Prerendering is completely disabled.

### uBO version

1.55.0

### Browser name and version

Google Chrome Version 121.0.6167.139 (Official Build) (arm64)

### Operating System and version

MacOS Sonoma 14.2.1 (23C71)

**Comment by uBlock-user** [comment] 2024-02-09 09:54
Enable it yourself - https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-prefetching

**Comment by Tylopilus** [comment] 2024-02-09 10:16
This setting prohibits a newly specced feature which has nothing todo with the old prefetch-things. So just a `enable it yourself` does not solve the issues that the users of my website cannot experience instant page loads

**Comment by u-RraaLL** [comment] 2024-02-10 11:22
Quoting from the spec you linked to:

> Prerendering uses memory and network bandwidth. If you prerender something the user doesn't navigate to, these are wasted (although the result may populate the HTTP cache if headers allow, allowing later use). The upfront cost of a prerender is much larger than the upfront cost of a prefetch, and there are more conditions that could make content unsafe to prerender (see [Unsafe speculative loading conditions](https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API#unsafe_speculative_loading_conditions) for more details). As a result, you are encouraged to adopt prerendering more sparingly, carefully considering cases where there is a high likelihood of the page being navigated to, and you think the user experience benefit is worth the extra cost.

> Prerendering is more risky to adopt than prefetching and should therefore be done more sparingly, in cases where it is worth it. There are more unsafe conditions to watch out for with prerendering so, while the reward is higher, the risk is too.

> Content can be potentially unsafe to prerender if any of the following conditions are observed:
> - The page runs JavaScript or loads images that cause side effects such as sending analytics, recording ad impressions, or otherwise modifying the state of the application as if the user had already interacted with it.

It doesn't sound like something that should be enabled by default in uBO. There will definitely be some sites trying to take advantage of this.

If a user wants to sacrifice their defenses in favor of speed, it's ultimately their choice and they have the option to enable it.
uBO's stance will remain privacy-first though.

**Comment by gorhill** [comment] 2024-02-14 13:42
As per @u-RraaLL's comment, closing as wontfix.

**Closed by gorhill** 2024-02-14 13:42 UTC
Labels: wontfix

**Comment by nicok1** [comment] 2024-03-20 00:19
A small addition:

If I disable prefetch and try prerender with [Speculation_Rules_API](https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API), edge dev tools shows "Error - The prerender was not executed because the user has disabled preloading in their browser settings." -> As intended

But If I allow it, edge returns:
"An unauthorised JavaScript API was used on the previously rendered page, which is currently not supported. (Internal Mojo interface: extensions.mojom.RendererHost)" -> Not working. After disabling uBlock, it works. 

I would like that to work.

**Comment by gwarser** [comment] 2024-04-04 22:26
https://bugzilla.mozilla.org/show_bug.cgi?id=1816539#c9
