### ISSUE TITLE
support disabling subdomain propagation for specific domains

### ISSUE THREAD

**Issue by Rudxain** [uBlockOrigin/uBlock-issues#3104] opened 2024-02-05 00:46 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Some domains have homepages without subdomain (such as `www.*`), which causes dyna-rules to inappropriately apply subdomain-propagation.

What if a user wants to
```
no-scripting: * true
no-scripting: discord.com false
```
without having to add
```
no-scripting: support.discord.com true
```
?

What about
```
* * 3p-script block
github.com * 3p-script noop
```
without needing
```
docs.github.com * 3p-script block
```
?

### A specific URL where the issue occurs.

```yaml
https://discord.com/
```

### Steps to Reproduce

Examples in description

### Expected behavior

This isn't unexpected. It's in the docs

### Actual behavior

Already explained

### uBO version

1.55.0

### Browser name and version

\*

### Operating System and version

\*

**Comment by u-RraaLL** [comment] 2024-02-05 07:45
Duplicate of #1277.

**Closed by u-RraaLL** 2024-02-05 07:45 UTC
