### ISSUE TITLE
No sites load with extension enabled. Disabling extension fixes issue. Unable to use extension.

### ISSUE THREAD

**Issue by sixside** [uBlockOrigin/uBlock-issues#3228] opened 2024-05-02 16:46 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Latest version of Chrome (Version 124.0.6367.119 (Official Build) (64-bit))  on Windows. Having the extension enabled causes any webpage to hang on request. No site loads at all. As soon as I toggle off (i.e. disable) the extension the site loads. 

### A specific URL where the issue occurs.

```yaml
I've tried many URLs, all have the same exact behavior. yahoo.com google.com ibm.com
```

### Steps to Reproduce

1. Disable all extensions.
2. Load a website (yahoo.com), it works.
3. Enable ublock extension.
4. Load a website (any site), browser hangs, spinning loading nothing renders.
5. Disable ublock extensions, the site from step 4 then loads fine.

### Expected behavior

All sites should load and block ads.

### Actual behavior

Sites never load. It's almost as if there is no server response at all.

### uBO version

1.57.0

### Browser name and version

Chrome 124.0.6367.119 (Official Build) (64-bit))

### Operating System and version

Windows 10Pro

**Comment by uBlock-user** [comment] 2024-05-02 16:57
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/3217

**Closed by uBlock-user** 2024-05-02 16:57 UTC
