### ISSUE TITLE
The logger doesn't log applied cosmetic bait filter

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#2045] opened 2022-03-12 14:40 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

https://github.com/AdguardTeam/AdguardFilters/issues/112099
On mobile a cosmetic bait `##.ad-text` triggered anti-adb before I fix by https://github.com/uBlockOrigin/uAssets/commit/710707d1543ff13042d1bee40331c163427f87f0 and https://github.com/uBlockOrigin/uAssets/commit/be0beb14c2d1750f72fcfb1c057eafc2972de07d but was not shown in the logger.

### A specific URL where the issue occurs

`https://divnil.com/wallpaper/iphone13/item_4/best-3d-hd-wallpaper-galaxy-1080x1920_b4977c1e44d8a399f671d3c72dbcfd31.html`

### Steps to Reproduce

1. Change UA to mobile
2. Add `||jsdelivr.net/npm/just-detect-adblock@$badfilter` and `*##.ad-text` and visit the site, anti-adb should be triggered
3. Yet the only comsetic log is `##.adsbygoogle` despite `##.ad-text` should have been applied - you can check by adding `divnil.com#@#.ad-text` or something.

### Expected behavior

`##.ad-text` should be logged

### Actual behavior

Not

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 98.0 with UA changed to  Mozilla/5.0 (Android 11; Mobile; rv:93.0) Gecko/93.0 Firefox/93.0

### Operating System and version

Windows 10

**Comment by gorhill** [comment] 2022-03-12 15:22
This happens because the code in `https://cdn.jsdelivr.net/npm/just-detect-adblock@1.1.0/dist/bundle.umd.min.js` adds a `div` with the bait classes, then immediately remove the bait `div` after checking that whether it is visible. uBO's logger code executes asynchronously using a mutation observer, so by the time the mutation observer handler is called, uBO can't find a match for `ad-text` in the live DOM.

A possible fix is to also test for match in removed nodes reported by the mutation observer.

**Comment by sugarfreesweetener** [comment] 2022-09-15 16:17
https://github.com/AdguardTeam/AdguardFilters/issues/124354

On `https://metin2hub.com/`, after allowing all first-party scripts and refreshing, I still encountered anti-adblock; after disabling cosmetic filtering and refreshing the web page, the anti-adblock did not appear (until after enabling cosmetic filtering a refreshing the web page)

**Comment by garry-ut99** [comment] 2023-01-18 11:32
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/521 

(and by the way this comment: https://github.com/uBlockOrigin/uBlock-issues/issues/2045#issuecomment-1065901458 is a duplicate of this comment: https://github.com/uBlockOrigin/uBlock-issues/issues/521#issuecomment-482114381 as well)

**Comment by gwarser** [comment] 2023-01-18 13:25
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/521

**Closed by gwarser** 2023-01-18 13:25 UTC
Labels: something to address
