### ISSUE TITLE
macos powerswitch tooltip should say cmd not ctrl

### ISSUE THREAD

**Issue by StefanoChiodino** [uBlockOrigin/uBlock-issues#350] opened 2018-12-22 11:04 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On macos the tooltip suggests using ctrl instead of cmd.

I've seen this mentioned in a couple of issues and PR in the main repo, where I don't have power to comment, but they are more than a year old and this is still an issue.

https://github.com/gorhill/uBlock/issues/614
https://github.com/gorhill/uBlock/issues/2338

### A specific URL where the issue occurs

n/a

### Steps to Reproduce
Click on the uBlock icon, hover on the powerswitch, read the second paragraph.

### Expected behavior:

It should either only mention the cmd modifier on macos, or mention both.

I naively just changed the text, but can't submit a PR https://github.com/StefanoChiodino/uBlock/commit/f41a00a5962154fd1b80bcf51e58800c4f38aa49

### Actual behavior:

Only ctrl is mentioned.

### Your environment
* MacOs, latest
* uBlock Origin v1.17.4
* Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Thank you so much for working on this plugin!!!

**Comment by uBlock-user** [comment] 2018-12-22 11:43
Duplicate of https://github.com/gorhill/uBlock/issues/614

**Closed by uBlock-user** 2018-12-22 11:43 UTC
