### ISSUE TITLE
alert-buster.js doesn't work on Firefox

### ISSUE THREAD

**Issue by theel0ja** [uBlockOrigin/uBlock-issues#2079] opened 2022-04-05 10:17 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

alert-buster.js doesn't work on Firefox, while it works on Chromium.

<img width="1132" alt="Screenshot 2022-04-05 at 13 17 55" src="https://user-images.githubusercontent.com/5832930/161732800-9dcde68b-a14a-4937-b197-5e0866f8d831.png">

### A specific URL where the issue occurs

https://ylilauta.org/

### Steps to Reproduce

1. Install uBlock Origin on Firefox
2. Enable Finnish Easylist Additions, which has a rule for ylilauta.org
3. Get alerts on ylilauta.org even when alert-buster.js should be activated

### Expected behavior

No alerts, logged into console. Works correctly on Chromium (tested with uBO 1.41.8 on Chromium 100.0.4896.62)

### Actual behavior

Alerts are still shown, like seen in the picture in the "Description"

### uBlock Origin version

1.42.0

### Browser name and version

Tested on Firefox 98.0.2 and 99.0b8 (DevEdition)

### Operating System and version

macOS 12.3.1

**Comment by krystian3w** [comment] 2022-04-05 10:30
Race conditions?

Few possible disable by set/aopr/aopw.

**Comment by gorhill** [comment] 2022-04-05 12:23
Unable to reproduce an alert in the first place. You will have to provide details on how to trigger this alert.

**Comment by gorhill** [comment] 2022-04-05 13:04
The issue is that the CSP for the page prevent inline scripts from being injected:

> Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

Firefox's behavior differs from Chromium here.

**Comment by gorhill** [comment] 2022-04-05 13:17
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/235>.

**Closed by gorhill** 2022-04-05 13:17 UTC
Labels: bug

**Comment by krystian3w** [comment] 2022-04-05 13:18
For my side Tampermkoney disable most CSP with almost empty script in expert mode.

In then method I can still use google toolbar to translate pages, use `$cps` and `$inline-script filtering.

So works better than `csp.enabled` and I guess better than scriptlet doctor.

**Comment by Cerberus-tm** [comment] 2022-09-12 15:18
> For my side Tampermkoney disable most CSP with almost empty script in expert mode.

Hey, this sounds highly useful, how do you do this, or what should there be in the Tampermonkey script in Firefox?

**Comment by Cerberus-tm** [comment] 2022-09-12 17:41
> @Cerberus-tm Install [Scriptlet Doctor](https://github.com/JustOff/scriptlet-doctor): https://github.com/JustOff/scriptlet-doctor/releases/download/1.2.5/scriptlet-doctor-quantum-1.2.5.xpi
> 
> Don't forget to disable "Limit to domains".

Hey, thanks, I was going to try Scriptlet Doctor too, though it won't download at the moment.

But I was also curious about the solution using Tampermonkey.
