### ISSUE TITLE
Popup window does not have a scroll bar in the connected hosts list

### ISSUE THREAD

**Issue by h6a8ke1k** [uBlockOrigin/uBlock-issues#1035] opened 2020-05-16 00:34 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The connected hosts list in the popup window does not have a scroll bar. If the number of hosts are large, only the hosts from the beginning that fit in the area of the component are displayed and I cannot scroll down to see the other hosts.

### A specific URL where the issue occurs

Any web page which connects to many hosts. e.g. cnn.com

### Steps to Reproduce

1. Open a web page.
2. Click on the uBlock Origin icon in the extensions list.
3. The popup window is opened and I can neither find the scroll bar in the connected hosts list nor scroll down to see more hosts.

### Expected behavior:

There is a scroll bar in the connected hosts list UI component and I can scroll down and see more hosts that does not fit in the area of the display.

### Actual behavior:

I cannot scroll down the list of connected hosts. I cannot see the hosts that go beyond the display area.
It happens both when expended or not.
![1](https://user-images.githubusercontent.com/46216438/82105796-08040080-96d2-11ea-8917-efd3a017c26a.png)
![2](https://user-images.githubusercontent.com/46216438/82105799-0d614b00-96d2-11ea-9b3e-eaebd87e4475.png)

### Your environment

* uBlock Origin version: 1.27.0
* Browser Name and version: Firefox 68.8.0 ESR
* Operating System and version: Windows 10 x86_64

**Comment by gorhill** [comment] 2020-05-16 00:47
I cannot reproduce, I need to investigate why this happens.

As a workaround, you can set `uiFlavor` to `classic` in [advanced setting](https://github.com/gorhill/uBlock/wiki/Advanced-settings) in order to get the old popup panel. This requires a restart of the browser to take effect.

**Comment by gorhill** [comment] 2020-05-16 01:32
This will be fixed in 1.27.2, which I just submitted to AMO.

**Comment by kulfoon** [comment] 2020-05-16 06:16
> gorhill : This requires a restart of the browser to take effect.

It does not, switching an addon off/on is enought.

**Closed** 2020-05-16 09:28 UTC
Labels: bug, fixed
