### ISSUE TITLE
Option to ignore all exception filters.

### ISSUE THREAD

**Issue by 7b4a82cee25ea77cbf9f8250fcec650d** [uBlockOrigin/uBlock-issues#259] opened 2018-10-08 04:36 UTC
Sorry if this has been suggested before, I couldn't find it when I searched. Exceptions seem to be abused rather often to allow ads/analytics through. It would be nice to have a global option to ignore exception filters, like with no-csp-reports: and no-scripting: and similarly an option to disable or enable per site.

**Comment by uBlock-user** [comment] 2018-10-08 05:35
Duplicate of https://github.com/gorhill/uBlock/issues/3353

**Closed by uBlock-user** 2018-10-08 05:35 UTC
