### ISSUE TITLE
When uBO will be updated to the latest version officially?

### ISSUE THREAD

**Issue by ballios** [uBlockOrigin/uBlock-issues#834] opened 2020-01-01 13:23 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I've been using uBO for a couple of years, love it! Period.
But I'm still with v1.23, My Chrome 79.0.3945.88 doesn't update the app to the latest version 1.24.2. Checked CWS, which still shows 1.23 posted too.
Forced Chrome updates didn't help either... 
Tried to enable enable javascript-harmony flag in Chrome settings, (although uBO page says the trick works for Chrome v54 and older), to no avail yet.
When uBO will be updated to the latest version 1.24.2 officially?

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.23.0
* Browser Name and version: Chrome 79.0.3945.88
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment] 2020-01-01 14:02
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/828

**Closed by uBlock-user** 2020-01-01 14:02 UTC
