### ISSUE TITLE
Convenience option: buttons or hotkeys for different filter list settings

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uBlock-issues#1736] opened 2021-09-25 21:35 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When maintaining filter lists, there's often a need to disable / enable different lists in order to see how a site works when specific lists are either disabled or enabled. The more lists you have in use, the more you'll have to toggle them off/on, one by one. I would find it really useful if there were buttons that allow me to switch between various filter list configurations via 1 mouse click.

EDIT:
Also hotkeys, such as pressing 1, 2, 3 or 4 in the filter list settings page to assign different filter list configurations could be another approach instead of physical buttons.

### A specific URL where the issue occurs

moz-extension://bef72a12-ee16-4609-82fa-66fedc2d5405/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Open filter list settings page

### Expected behavior

There would be buttons (maybe 4 at least?) that allow me to quickly switch between various filter list configurations via 1 mouse click.

### Actual behavior

There is no way to easily switch between various filter list configurations.

### uBlock Origin version

1.37.3rc3

### Browser name and version

Firefox 92.0

### Operating System and version

Windows 10

**Comment by gothic-bum** [comment] 2021-09-25 23:34
As a suggestion, perhaps you could create multiple borwser profiles that have specific filter lists enabled.

**Comment by peace2000** [comment] 2021-09-26 00:20
> 
> 
> As a suggestion, perhaps you could create multiple browser profiles that have specific filter lists enabled.

Thanks for a suggestion but that sounds a bit unpractical, especially the profile switching part.

**Comment by felix-22** [comment] 2021-09-26 05:55
> gothic-bum : As a suggestion, perhaps you could create multiple browser profiles that have specific filter lists enabled.

It is what I have been doing for many years, as a workaround for the lack of functionality that peace2000 is requesting, but having a functionality OP is requesting, wouldn't be a bad idea.

**Comment by uBlock-user** [comment] 2021-09-26 06:05
@peace2000 related to https://github.com/uBlockOrigin/uBlock-issues/issues/1019 ?

**Comment by felix-22** [comment] 2021-09-26 06:08
A duplicate of: https://github.com/gorhill/uBlock/issues/1458

**Comment by peace2000** [comment] 2021-09-26 10:49
@felix-22 Hi, those linked issues are not duplicates of this. Personally, I don't need an option to to select or deselect a category.

I want to be able to activate specific list configurations via 1 mouse click. Configurations that I have personally made.

If this were implemented, I would personally e.g. assign these settings behind hotkeys or buttons:

1.) Activate my personal, everyday filter list configuration (and this would deselect all the other lists)
2.) Deselect all filter lists (so that I can easily, after that select one specific list and see how a site works when it's solely enabled)
3.) Select Easylist and the Finnish Easylist (and this would deselect all the other lists, I want to make sure that when testing a site, it's handled entirely by EL and Finnish EL and adblocking doesn't rely on other lists).

Other maintainers might find other configurations useful for their maintenance purposes.

**Comment by felix-22** [comment] 2021-09-26 12:17
> peace2000 :  I don't consider those linked issues duplicates of this.

- the main idea is the same in all the linked requests: to easily manage / select / deselect bigger groups of filters 
- the fact that everyone wants to implement it in their own way, does not mean that these requests are no longer duplicates
- all of the linked requests should be treated as one and the same, and if it were to be implemented, it would be based on selecting the best ideas from each of these requests
- if each such requests were to be considered as separate, there would be 100 similar requests and it would be pointless...

**Comment by v00v** [comment] 2021-10-05 10:25
Saidly gorhill even declined the basic check all filters =( https://github.com/uBlockOrigin/uBlock-issues/issues/172#issuecomment-413836348

**Comment by gorhill** [comment] 2022-11-20 17:07
This would require to add a lot of code and increase code complications as a result, and I am not motivated to make maintenance work ever more of a burden, especially when there is an easy workaround for the scenario here, which is to use different browser profile. It's one click in Chromium, and one click in Firefox assuming the `about:profiles` page is already opened.

**Closed by gorhill** 2022-11-20 17:07 UTC
Labels: enhancement
