### ISSUE TITLE
Filters list tab empty and non-functional

### ISSUE THREAD

**Issue by Latias4Ever** [uBlockOrigin/uBlock-issues#643] opened 2019-06-21 21:07 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock Origin updated to 1.20.0, as I tried to open a page that usually has ads that are blocked, the page started showing ads, and upon stopping the page from loading, it crashed. YouTube ads also started to show. After checking the filters list tab, it's fully empty, showing up like this: https://i.imgur.com/tAtwz0J.png

Attempting to check any of the boxes doesn't get recorded, and moving from the filters tab to another says that I have "unsaved changes".

### A specific URL where the issue occurs

https://www.youtube.com/watch?v=Aq6ZDWHhBk8

### Steps to Reproduce

1. Updated to 1.20.0.
2. Open Filters List.

### Expected behavior:

Filters tab not being empty and fully functional. Ads and scripts being blocked.

### Actual behavior:

Filters list tab appears empty and is completely non-functional: https://i.imgur.com/tAtwz0J.png
Ads appear everywhere, unblocked.

### Your environment

* uBlock Origin version: 1.20.0.
* Browser Name and version: Chrome Version 53.
* Operating System and version: Windows 8.1.

**Comment by uBlock-user** [comment] 2019-06-21 21:15
> Chrome Version 53

Seems specific to version 53

**Comment by Latias4Ever** [comment] 2019-06-21 21:17
I hope this doesn't mean that uBlock will become incompatible with this version, I'm not sure how to detect the issue that causes the Filters tab to not work, but I hope I won't be forced to update my browser to a version I don't wish to use.

**Comment by uBlock-user** [comment] 2019-06-21 21:20
> I hope this doesn't mean that uBlock will become incompatible with this version

That seems to be the case here, if it can't be fixed with a workaround, then expect a version bump.

**Comment by gorhill** [comment] 2019-06-21 21:20
Any errors reported in the dev console of the page?

**Comment by Latias4Ever** [comment] 2019-06-21 21:26
No, the dev console shows nothing in the page, even in the Filters tab. Even if I open the html file on the Sources tab.

**Comment by gorhill** [comment] 2019-06-21 21:31
Actually since you say ads are not blocked, the errors are probably in uBO's dev console. Can you look there?

- Go to `chrome://extensions/`
- Enable "Developer mode"
- Click "background.html" in uBO's tile
- See what is reported in the console.

**Comment by gorhill** [comment] 2019-06-21 21:34
On a hunch I went to see since when asyntc/await have been available in Chromium, and [as per MDN's documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function), it's available since version 55, so I suspect this is the issue.

**Comment by Latias4Ever** [comment] 2019-06-21 21:35
Ahh, here we go. Here are the errors displayed: https://imgur.com/a/rHWLDyQ

**Comment by gorhill** [comment] 2019-06-21 21:46
This confirms the issue is with async/await.

Can you search in `chrome://flags/` for a flag which might be available to enable async/await?

**Comment by gorhill** [comment] 2019-06-21 21:50
I believe `chrome://flags/#enable-javascript-harmony` might be it.

**Comment by Latias4Ever** [comment] 2019-06-21 21:56
It seems to have worked! In fact another extension I had that stopped working due to async/await also started working once again! However uBlock started crashing quite a lot, it took quite a few reloads, but it's working now. Hopefully this doesn't result in issues in the future, maybe it was being overloaded due to all the filtering it was doing (since I have a lot of tabs open and relaunching Chrome opened all of them again).

**Comment by uBlock-user** [comment] 2019-06-21 22:00
That's only a stop-gap measure fyi, issues like these are bound to popup if you don't update your browser which is now outdated.

**Comment by gorhill** [comment] 2019-06-21 22:00
I going to consider this the official "fix", this way I can keep modernizing uBO's code base while older versions of Chromium can still work by merely toggling the flag.

**Closed** 2019-06-21 22:00 UTC
Labels: Chromium, something to address
