### ISSUE TITLE
Whitelisted cosmetic filters in logger

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uBlock-issues#79] opened 2018-06-17 13:55 UTC
Currently whitelisted element filters such as `oxforddictionaries.com#@#.banbox` are not shown in the logger. I had a difficult time trying to diagnose via the logger why the particular element wasn't getting blocked until I manually checked the filter lists.

It would be great if whitelisted cometic filters can be logged just like whitelisted network requests are.

_**Note:** Using uBO 1.16.10 on Chrome 67 with the default filters and settings._

**Comment by uBlock-user** [comment] 2018-06-17 14:21
Duplicate of https://github.com/gorhill/uBlock/issues/127

**Closed by uBlock-user** 2018-06-17 14:21 UTC
Labels: duplicate

**Comment by grenzor** [comment] 2018-06-17 16:41
One question, is there no badfilter equivalent option to override whitelisted element filters in filter lists? Seems filter lists have the last say for these while every other filter type the user can override.

**Comment by mapx-** [comment] 2018-06-17 16:45
if you want to override:  
`example.com#@#.filter1`

use
`example.com##.filter1,fake`

(or whatever you want replacing `fake`)

**Comment by uBlock-user** [comment] 2018-06-17 17:11
@grenzor Use an invalid CSS selector preceded by a comma

**Comment by gotitbro** [comment] 2018-06-18 10:30
@gorhill Is there any plan on addressing this? Looks like many similar issues have been submitted regarding this.
