### ISSUE TITLE
Ublock 1.41.2 update ignores 'my filters'

### ISSUE THREAD

**Issue by reaper666735** [uBlockOrigin/uBlock-issues#1978] opened 2022-02-12 11:08 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

since the latest update items i choose in the element picker mode (who end up in my filter list) are not being hidden anymore, reverting back to 1.40.8 fixes this issue 

### A specific URL where the issue occurs

https://outlook.live.com/mail/inbox

### Steps to Reproduce

1. Use element picker mode
2. Add [ outlook.live.com##.f1vx9l62.f124akge.f1l02sjl.f1ctqxl6.f122n59.f22iagw.___lluazi0 ] and or [ outlook.live.com##._1elFdDtE02urszo_h9-MJw.full ]  to the list  (it's just a sidebar and banner frame)
3. After reload or browser restart they are back

### Expected behavior

well i expected it to be hidden even after reload :p

### Actual behavior

it seems to stay as long as you don't leave the page, otherwise it seems to not load from my filter list

### uBlock Origin version

1.41.2

### Browser name and version

Waterfox (G4.0.7)

### Operating System and version

win 10  21h2

**Comment by g0blin-NN** [comment] 2022-02-12 14:44
@reaper666735 did you change user agent? return native and look.

**Comment by Nojuuu** [comment] 2022-02-12 16:22
Are you sure you didn't use element zapper instead?

**Comment by reaper666735** [comment] 2022-02-12 16:29
@g0blin-NN  did not change anything except the update'd UB lol

@Nojuuu  oh i'm very sure i used the "Element picker" ....

**Comment by gorhill** [comment] 2022-02-12 16:53
Did you rule out that the element might have a randomly generated classes at each reload? You need to make the case you know the issue is not a filter one, hence why I ask how did you rule out it's not a filter issue. Without this, the issue will be closed as invalid.

**Comment by gorhill** [comment] 2022-02-12 17:01
I use Firefox stable 97 and I could pick and remove the sidebar on the right using the filter:

    outlook.live.com##._1dBL6mV6xRANqjh_Z8BjN6 > ._1fti_QgAzqGWPGlqh_FSvI

No issue upon reload of the page -- using default settings/lists.

**Comment by reaper666735** [comment] 2022-02-12 17:07
it's based on Gecko from Firefox, release notes say it's on version 91.6 of that engine

**Comment by reaper666735** [comment] 2022-02-12 17:09
also as i stated when i revert back to 1.40.8 i have no more issue ?, if it really was the random generated class as you suggested

**Comment by gorhill** [comment] 2022-02-12 17:19
> as i stated when i revert back to 1.40.8 i have no more issue ?

As stated, no issue with Firefox stable, so try with Firefox stable, Waterfox is not officially supported.

**Comment by gwarser** [comment] 2022-02-12 20:44
Is "My filters" selected on "Filter lists" tab and shows how many filters are used?

**Comment by anew742** [comment] 2022-02-12 21:20
> Is "My filters" selected on "Filter lists" tab and shows how many filters are used?

Yes. But the weird part is that after updating back to 1.41.2, my filters now work and persist even after a restart. So whatever the problem is, it's fixed by downgrading then re-updating. 
No clue how or why that happens, but it works now so ¯\_(ツ)_/¯  
Hopefully it'll stay working, but if not I can always revert to an older version

**Comment by reaper666735** [comment] 2022-02-12 21:26
in a weird way i'm happy i'm not the only one to report it now lol, i was feeling like it just had to be me ......

**Comment by Gamer60446** [comment] 2022-02-13 02:31
I have the same issue with Firefox. In addition to custom filters not working, promoted content on Reddit and some YouTube ads will also start appearing when the bug is triggered, at least for me. I noticed that if I purge all caches and then update all filters, my custom filters will start working and all ads should be gone. However, they will randomly stop working again after some time and I don't know exactly what triggers it. I can confirm that downgrading to 1.40.8 fixes the issue.

**Comment by gorhill** [comment] 2022-02-13 13:19
From what I read, this suggest a specific cosmetic filter is being problematic. It would be useful to share your custom filters for those suffering the issue.

**Comment by Nojuuu** [comment] 2022-02-13 14:09
@gorhill https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-1038135518 maybe related?

**Comment by uBlock-user** [comment] 2022-02-13 14:27
@Nojuuu very bad regression, breaks uBO and blocks all network connections to any site alltogether(unable to browse any website). This warrants an emergency fix.

@gorhill ![Capture](https://user-images.githubusercontent.com/21290713/153757656-4a20a975-0724-4507-8e55-9920d65e6881.PNG)

**Comment by gorhill** [comment] 2022-02-13 14:45
This is not a regression, this has always been in there, it just needed a argument-less `removeparam` filter to expose the problem.

**Comment by krystian3w** [comment] 2022-02-13 16:46
Maybe poor filterlist used `@@*$ehide` and user don't saw this (no check commits or use logger).

**Comment by u-RraaLL** [comment] 2022-02-13 16:54
@krystian3w that doesn't explain why the problem disappears when a user drops down to 1.40.8.

There was another instance on reddit just now: https://www.reddit.com/r/uBlockOrigin/comments/srmcy6/paradox_interactives_featured_content_antifeature/

**Comment by fluffymormegil** [comment] 2022-02-13 16:56
Hi, I'm the reddit poster who raised the issue the user above just linked to. 

The entirety of my ruleset is:
`! 11/06/2019 https://forum.paradoxplaza.com
forum.paradoxplaza.com###\#pdx-cookie > .pdx-cookie--toggle.pdx-cookie-bottom-bar__toggle

! nuke paradox's stupid space-wasting featured content area
forum.paradoxplaza.com##.thfeature_featuredGrid
forum.paradoxplaza.com##h3.block-header

`

**Comment by krystian3w** [comment] 2022-02-13 16:58
1.40.8 may also fail if page have enabled A/B Test to use new names after refresh.

**Comment by krystian3w** [comment] 2022-02-13 16:59
IMO paradox plaza need accept cookies instead only hide or remove by `:remove()`.

**Comment by u-RraaLL** [comment] 2022-02-13 17:00
> IMO paradox plaza need accept cookies instead only hide or remove by `:remove()`.

The issue was with the featured grid filter, though.

**Comment by krystian3w** [comment] 2022-02-13 17:01
Better teach about GDPR breakges.

**Comment by fluffymormegil** [comment] 2022-02-13 17:01
Yeah, the thing to permanently suppress their intrusive cookie button (the little bottom-of-window widget appears even if you're logged in and have accepted cookies!) worked fine.

**Comment by krystian3w** [comment] 2022-02-13 17:26
CSS specifity form custom subrcribied file also may disable filter after refresh - but on 1.40.8 tested without import settings?

**Comment by Nojuuu** [comment] 2022-02-13 17:44
>  when you mentioned needing our custom filters are you referring to "My Filters" or the filter lists "Custom" tab ?

To reproduce your setup needs your filters and troubleshooting information from support tab

**Comment by one-way-ticket** [comment] 2022-02-14 14:44
> > There are no records of the "My Rules" in Logger.
> 
> I gather you mean _"My filters"_.

Yes, of course. "My filters", you right.

> From what I read, this suggests a specific cosmetic filter is being problematic -- quite possibly a highly generic one. It would be useful to share your custom filters for those suffering the issue.
> 
> In uBO 1.41.2, highly generic cosmetic filters are wrapped into `:is(...):not(html,body)`, where `...` is the highly generic cosmetic filters, and this is done so as to fix #1692. Now I wonder whether a particular cosmetic filter is incompatible for being wrapped into `:is(...):not(html,body)` -- which by the way happens only for Firefox 84+.
> 
> So bottom line, I need information about your custom filters if this issue is to go forward.

My filters is very easy:

```
! **hide posts blacklisted users on forum.ixbt.com**
! forum.ixbt.com##.column.left > table[id^="post"][onmousedown^="selected_name="][onmousedown*="nickname"]
forum.ixbt.com##.column.left > table[id^="post"][onmousedown^="selected_name="][onmousedown*="'77'"]
forum.ixbt.com##.column.left > table[id^="post"][onmousedown^="selected_name="][onmousedown*="%u0411%u0440%u0443%u043D%u043E%20%u0424%u0435%u0440%u0440%u0430%u0440%u0438"]
forum.ixbt.com##.column.left > table[id^="post"][onmousedown^="selected_name="][onmousedown*="%u042D%u0440%u0435%u0448%u043A%u0438%u0433%u0430%u043B%u044C"]
forum.ixbt.com##.column.left > table[id^="post"][onmousedown^="selected_name="][onmousedown*="%u0428%u0438%u043C%u043E%u043D"]
forum.ixbt.com##.column.left > table[id^="post"][onmousedown^="selected_name="][onmousedown*="%u042F%u0441%u043D%u044B%u0439"]
forum.ixbt.com##.column.left > table[id^="post"][onmousedown^="selected_name="][onmousedown*="user2f"]

! **trash on https://forums.overclockers.ru/**
forums.overclockers.ru###wrapcentre > table:nth-of-type(2) > tbody > tr > td:nth-of-type(2)

! **fix for panopticlick.eff.org**
@@||panopticlick.eff.org/static/fp2.js|$script,domain=panopticlick.eff.org

! **popup notifications on https://translate.google.com/**
translate.google.com##.notification-area > .tlid-notification-container.notification-container

! **trash on yandex**
yandex.by,yandex.kz,yandex.ru,yandex.ua,yandex.uz##body[class*="logged "][class*=" b-page_"] div[class*="media-grid"][class*="media-content"]

! **fix for boxberry.ru**
@@/tracking/get?$domain=boxberry.ru
```

**Comment by anew742** [comment] 2022-02-14 15:08
For reference, the main filters I noticed that broke with the update:
www.reddit.com##.premium-banner
youtube.com##.ytp-ce-element-show

**Comment by krystian3w** [comment] 2022-02-14 17:51
Try delete `-show`.

**Comment by Thomas-SW** [comment] 2022-02-15 15:26
Hello everyone,

I had the same problem.
v1.41.2 ignores "my filters".
I haven't tried much, but for example this filter doesn't work anymore: "www.zdf.de##.b-live-tv"
So I switched back to v1.40.8 and it's fine.

Today I switched from FF 78.15 ESR to the current version 91.6 ESR and also updated uB to v1.41.2

Now it works without problems...
Maybe this information will help.

**Comment by u-RraaLL** [comment] 2022-02-15 16:01
Let's see if this comment leads anywhere: https://www.reddit.com/r/uBlockOrigin/comments/srmcy6/comment/hx0ky2z/

**Comment by gwarser** [comment] 2022-02-15 19:43
Maybe it's the Defender messing with browser storage?

**Comment by krystian3w** [comment] 2022-02-15 21:25
For me rare no works generic to hide social share in disqus frames, but filter specified by domain also no help and this looks like bug with iframes about:blank.

#688

**Comment by twiz-git** [comment] 2022-02-16 12:58
I seem to have fixed the issue, at least for myself:

- Operating system: Windows 10
- Firefox version: 78.13.0esr (64-bit)
- uBlock Origin version(s): 1.40.8, 1.41.0, 1.41.2, 1.41.3b1, 1.41.3b2
- Affected versions: 1.41.0, 1.41.2, 1.41.3b1, 1.41.3b2

Create a new profile -> Install uBlock -> Test -> Works as intended.

1. Navigate to about:profiles -> click "Create a New Profile" -> click "Launch profile in new browser"
2. Navigate to https://github.com/gorhill/uBlock/releases -> click "uBlock0_1.41.x.firefox.signed.xpi"
3. Click "Continue to Installation" -> click "Add" -> click "Okay, Got It"
4. Navigate to https://old.reddit.com/ -> click uBlock icon -> click "Enter element picker mode"
5. Click left (minimized) side bar 'grippy' element -> select "##.initialized.listing-chooser" from Cosmetic filters
6. Reload page -> see that it works.
7. Restart firefox -> navigate to https://old.reddit.com/ -> see that it works.

Return to original profile -> Test -> Does not work as intended.

8. Navigate to "about:profiles" -> click "Create a New Profile" -> click "Launch profile in new browser"
9. Navigate to https://old.reddit.com/ -> see that it does not work.

Disable/Reset options until it works.

10. Navigate to about:addons -> disable all addons, restart Firefox.
11. Navigate to about:addons -> enable uBlock Origin, restart Firefox.
12. Navigate to old.reddit.com -> Check problem still exists: it does.
13. **>> Click uBlock icon -> Open the dashboard -> Filter lists -> Purge all caches -> Update now.**
14. **>> Navigate to old.reddit.com -> Check problem still exists: it does not.**

You probably only need to clear cache/update, but I listed all my steps for completeness.

**Comment by gorhill** [comment] 2022-02-16 14:27
So Firefox version appears important, so whoever has reported having the issue, please disclose your browser version.

**Comment by alessiot89** [comment] 2022-02-16 14:41
I am on firefox ESR 78.15.0

**Comment by reaper666735** [comment] 2022-02-16 14:46
and once again i'm on Waterfox but it could be somehow it might be related to that version more then we might realise

**Comment by gorhill** [comment] 2022-02-16 14:53
> i thought the latest update upped the min. to 68 only ?

Yes, but there seems to be an unforeseen issue, which is what we are trying to narrow.

**Comment by gorhill** [comment] 2022-02-16 16:52
Looking at the code, there is a bit of a race condition in Firefox-based browsers, whereas uBO assumes the browser version to be 91, while waiting for the real version number to come through a promise. However I find it difficult that filter lists would be compiled before the promise is fulfilled, as it is one of the first thing uBO does at launch.

At this point I am contemplating seriously to revert <https://github.com/gorhill/uBlock/commit/7c8aec250f03580bbd761810bf5bf26d277683b0> -- I have a strong suspicion the issue might be related to this -- and bring back the commit in a subsequent dev cycle with more testing being done (please use the dev build if you want such issues to be found before stable release).

**Comment by reaper666735** [comment] 2022-02-16 18:03
i guess we will just have to wait and see (test) if that will fix it :p

**Comment by gorhill** [comment] 2022-02-16 20:07
A commit which might be at the root of the issue here has been reverted, and the change is available in [1.41.5b1](https://github.com/gorhill/uBlock/releases) or above. I will wait for feedback as to whether this makes a difference or not.

**Comment by reaper666735** [comment] 2022-02-17 12:11
just doing a quick test on several sites i have filters on does seem to show 1.41.5b1 to be working as it should again :), ofc i will keep testing wit this build and keep you informed should anything happen ;)

**Comment by one-way-ticket** [comment] 2022-02-17 17:43
> A commit which might be at the root of the issue here has been reverted, and the change is available in [1.41.5b1](https://github.com/gorhill/uBlock/releases) or above. I will wait for feedback as to whether this makes a difference or not.

Install version 1.41.5b1 on FF 78.15 ESR.
The problem no longer arises. "My filters" works.
Thanks!

**Comment by coldimmune** [comment] 2022-02-19 17:09
All my mobile devices use Firefox Android 68 and experienced the same issue -- the 1.41.5b1 fixed it.

It may be outdated and unsupported, but in my defense, Fenix should be classified as beneath us. Just a dogshit browser.

**Comment by Candlemass** [comment] 2022-02-21 00:34
I was having the same problem on Android mobile 68.x (Don`t use the shitty new fenix verson). Reverting to 1.40.8 solved the problem but didn`t have dark mode so I settled on 1.14.6 since it`s the latest stable version with that feature and so far seems to be resolved. I will report back if this changes for any reason.

It`s more apparent than ever why a lot of users don`t upgrade once they find something that works. Far too much breakage occurring these days of essential features in exchange of implementing new ones...

**Closed** 2022-02-21 12:01 UTC
Labels: unable to reproduce

**Comment by HoldOffHunger** [comment] 2022-07-23 14:23
*SOLVED.*

--Remove uBlock Origin
--Install uBlock Origin v. 1.18.17.16 from here https://www.crx4chrome.com/crx/149207/

I like how this problem is super easy to reproduce and demonstrate.  But I like a lot better having the solution!

**Comment by e-t-l** [comment] 2022-09-27 13:18
I was having the same issue on some sites, including Reddit, and updating to v1.44.5b6 did fix the issue with My Filters created using Element Picker not persisting across page refreshes. 

@gorhill You might like to know, however, that I encountered a separate issue: ALL elements of Reddit were blocked (aka when the page finished loading, it was blank white) until I a) disabled cosmetic filtering on Reddit (not ideal), or b) checked Ignore Generic Cosmetic Filters in UBO settings (still problematic, because I'd like generic filters to apply to _most_ sites).

**Comment by gorhill** [comment] 2022-09-27 13:39
There was an issue with `nth-of-type()`-based filters causing the behavior you describe. If your filters have been compiled by a previous dev build of uBO, just force a recompilation by clicking _purge all caches_ then _update now_.

**Comment by gorhill** [comment] 2022-09-27 13:40
Just force a _purge all cache_ the _update now_ to ensure all your filters are recompiled with using the latest fixes.

**Comment by e-t-l** [comment] 2022-09-28 22:35
@gorhill Now this is strange. I'm on v1.44.5b6, I purged and updated caches, but my Element Picker-created filter on Reddit is still not working! I'm no longer encountering a totally blank page, though. When I disable cosmetic filtering on Reddit, it still doesn't work (aka the element is not blocked). However, when I check Ignore Generic Cosmetic Filters in UBO settings, suddenly _my_ filter _does_ work, and the annoying element is blocked! I have no idea how to diagnose this further.

**Comment by gorhill** [comment] 2022-09-28 22:41
Share troubleshooting information, and which filter you say is not working when _"Ignore Generic Cosmetic Filters"_ is not checked.

**Comment by e-t-l** [comment] 2022-09-29 17:43
Affected filter: `www.reddit.com##.kEQVd8aneM1tVkcIKUyDT`

Troubleshooting information: 
```
uBlock Origin: 1.44.5b8
Firefox: 105
filterset (summary): 
  network: 388117
  cosmetic: 164875
  scriptlet: 39004
  html: 779
listset (total-discarded, last-updated): 
  added: 
    https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt: 0-0, 19h.13m
    https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter.txt: 155490-2442, 19h.13m
    https://raw.githubusercontent.com/AFNIL-AntiFakeNewsInternationalList/AFNIL/master/AFNIL-ABP-uBO.txt: 5794-1562, 19h.13m
    https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt: 2625-20, 19h.13m
    https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7252-143, 19h.13m
    https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/add-dead.txt: 20-0, 19h.13m
    https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/add-risk.txt: 2567-5, 19h.13m
    https://raw.githubusercontent.com/austinheap/sophos-xg-block-lists/master/add-spam.txt: 73-0, 19h.13m
    https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/ABP-Clickbait-Blocklist.txt: 12-0, 19h.13m
    https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/BreakingTheNews.txt: 1-0, 19h.13m
    https://raw.githubusercontent.com/marktron/fakenews/master/fakenews: 2197-2, 19h.13m
    https://raw.githubusercontent.com/ryanbr/fanboy-adblock/master/fake-news.txt: 584-242, 19h.13m
    https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/newsletter_filters.txt: 2027-2, 19h.13m
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-48, 19h.13m
    https://winhelp2002.mvps.org/hosts.txt: 8730-738, 19h.13m
    https://www.fanboy.co.nz/enhancedstats.txt: 2989-67, 19h.13m
    adguard-generic: 70138-5615, 19h.14m
    adguard-spyware: 26705-1614, 19h.14m
    curben-phishing: 75328-5, 19h.14m
    adguard-annoyance: 59684-5440, 19h.14m
    [8 lists not shown]: [too many]
  default: 
    user-filters: 49-4, never
    ublock-filters: 33694-379, 19h.15m
    ublock-badware: 4324-6, 19h.14m
    ublock-privacy: 273-1, 19h.14m
    ublock-abuse: 76-0, 19h.14m
    ublock-unbreak: 1875-2, 19h.14m
    easylist: 62254-18655, 19h.14m
    easyprivacy: 30638-14428, 19h.14m
    urlhaus-1: 7155-0, 19h.14m
    plowe-0: 3670-1800, 19h.13m
filterset (user): [array of 49 redacted]
trustedset: 
  added: [array of 73 redacted]
  removed: 
    edge-scheme
switchRuleset: 
  added: [array of 30 redacted]
hostRuleset: 
  added: [array of 15 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  contextMenuEnabled: false
  ignoreGenericCosmeticFilters: true
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateAssetFetchPeriod: 120
  autoUpdatePeriod: 7
  selfieAfter: 11
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 68901 ms (selfie)
  maxAssetCacheWait: 19384 ms
```

**Comment by e-t-l** [comment] 2022-09-30 22:10
> please report which filter list seems to trigger the issue

Can do. Sorry, didn't mean to act like I was dumping a huge task on you. You asked for troubleshooting info so I copied and pasted. I don't really know what I'm looking for - But why would another filter from a filter list cause mine not to work? Is there some order of precedence I'm not understanding (and if so, shouldn't it be reversed? Seems like the user's My Filters should override anything in an imported list, shouldn't it?)

> still subscribed to filter lists which have been abandoned since a long time

How do I tell which ones are abandoned? And does abandoned mean none of the filters are relevant anymore?

**Comment by gorhill** [comment] 2022-09-30 22:14
> How do I tell which ones are abandoned?

Open the list in a tab. If it does not load, remove it. If it load, check the last time it was updated. If it's more than a year, it's useless and may interfere negatively. When it comes to filter lists, more is not better. Some of these abandoned lists might be at the root of the long load time issue I can see in your troubleshooting information. Probably best to reset to default lists and add lists **only** when it actually do solve an actual issue you are trying to solve.

**Comment by e-t-l** [comment] 2022-10-01 01:00
Thanks.

> Open the list in a tab. If it does not load, remove it. If it loads, check the last time it was updated.  

Do I need to do this with ALL lists (including the ones uBlock ships with) or only for the lists I have added under the Custom heading?

> Probably best to reset to default lists

Likewise, does "default" mean any/all of those non-Custom lists, or only the ones UBO has enabled upon fresh install?

**Comment by gorhill** [comment] 2022-10-01 19:06
@e-t-l  Reset to default settings will cause your custom filters in _My filters_/_My rules_/_Trusted sites_ to be wiped out so you may want to export them first.

**Comment by gorhill** [comment] 2022-10-01 19:37
By the way, I would still like to know what list is causing your cosmetic filter to stop working, there has been changes in this area in the latest dev builds, and this might just help me fix a difficult to reproduce issue. Narrowing down to which list would help a lot.

**Comment by e-t-l** [comment] 2022-10-01 22:44
Ah. Sorry. I had gone thru the lists and removed the ones that didn't load or were over a year old, but I didn't stop to refresh reddit and see if it was affected each time. At this point, my issue is resolved. 

I only did this with Custom Lists and have not disabled any of the UBO-included lists, so we can safely say none of those are the issue.
