### ISSUE TITLE
set-cookie name adds %20 on spaces

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#3038] opened 2023-12-21 00:55 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Trying to set a cookie with a space, set-cookie with a space will translate too %20.

`sugar.it##+js(set-cookie, isFirstTime-Modal Newsletter, 1)` or (assuming this was valid) `sugar.it##+js(set-cookie, 'isFirstTime-Modal Newsletter', 1)`

### A specific URL where the issue occurs.

https://www.sugar.it/

### Steps to Reproduce

`sugar.it##+js(set-cookie, isFirstTime-Modal Newsletter, 1)`  should stop the newsletter popup from showing.

### Expected behavior

Allow spaces in set-cookies names

### Actual behavior

the name being set adds %20

### uBO version

uBlock Origin 1.54.0

### Browser name and version

Brave

### Operating System and version

Windows

**Comment by gwarser** [comment] 2023-12-21 07:23
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2777#issuecomment-1677178891

**Closed** 2023-12-21 07:25 UTC
Labels: duplicate
