### ISSUE TITLE
Allow filter list expiry time below 12 hours

### ISSUE THREAD

**Issue by llaurenss** [uBlockOrigin/uBlock-issues#2899] opened 2023-10-23 17:19 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I wanted to self host a modified version of the quick fixes filter list with a more frequent updating interval. But it seems that setting the expiry time lower than 12 hours doesn't change anything and the filter list will still only expire after 12 hours. 

### A specific URL where the issue occurs.

/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Create a filter list
2. Set the expiry time to 1 hour or anything below 12 hours with the `! Expires:` parameter
3. add the list to ublock origin
4. wait the given time and notice it won't be marked as outdated

### Expected behavior

Would be great to see uBlock add support for expiry time below 12 hours even if this is just for custom lists

### Actual behavior

Expiry time limited to a minimum of 12 hours. 

### uBO version

1.52.2

### Browser name and version

Firefox 118.0.2

### Operating System and version

Windows 10 19045.3570

**Comment by gothic-bum** [comment] 2023-10-23 18:38
It is not an issue/bug, and it is normal behavior.
  
By design, 12 hours is the minimum value for the expires directive.

**Comment by llaurenss** [comment] 2023-10-23 18:49
Now with the almost daily anti adblock updates by Youtube it would be nice to have the minimum value be lowered. So I'll try to rewrite it more as a feature request in that case.

**Comment by gothic-bum** [comment] 2023-10-23 19:01
Lowering the value would place additional load on the serving infrastructure which is already dealing with bandwidth issues / limits.

**Comment by llaurenss** [comment] 2023-10-23 19:12
I think you're misunderstanding me, I'm not asking to change the expiry time of the default filters, I can very well understand why that limit is in place for those. I'm asking for custom filters (hosted on my own server) to not have the same restrictions

**Comment by gothic-bum** [comment] 2023-10-23 19:18
You can create a feature request:  
  
https://github.com/uBlockOrigin/uBlock-issues/discussions/new?category=ideas

**Comment by garry-ut99** [comment] 2023-10-24 12:52
> llaurenss :  Allow filter list expiry time below

A duplicate of 6 same issues, which all of the were declined : 
- https://github.com/uBlockOrigin/uAssets/issues/16715#issuecomment-1454872794
- https://github.com/gorhill/uBlock/issues/1333#issuecomment-178706420
- https://github.com/gorhill/uBlock/issues/3117
- https://github.com/uBlockOrigin/uAssets/issues/6526#issuecomment-551524711
- https://github.com/uBlockOrigin/uBlock-issues/issues/2199#issuecomment-1205490004
- https://github.com/uBlockOrigin/uBlock-issues/issues/1165#issuecomment-1441591772

> gorhill : https://github.com/gorhill/uBlock/issues/1333#issuecomment-178706420 : The only time updating filters is an issue is if a filter-related issue occurs on a specific web site while knowing the fix has been added to one of the filter lists -- a rare occurrence.

> gorhill : https://github.com/uBlockOrigin/uBlock-issues/issues/2199#issuecomment-1205490004 : If you have filter issues on a given site, than just force a manual update.

However, as time passes and the situation changes dynamically, not sure whether it still holds against what stated in the current request by llaurenss : https://github.com/uBlockOrigin/uBlock-issues/issues/2899#issuecomment-1775818131 + https://github.com/uBlockOrigin/uBlock-issues/issues/2899#issuecomment-1775863407

**Comment by stephenhawk8054** [comment] 2023-10-24 13:03
Previously, even with a shorter interval for external lists, users cannot get full fixes due to trusted filters not able to be available for external lists. 

However, with the development of trusted lists set by users here: https://github.com/uBlockOrigin/uBlock-issues/discussions/2895#discussioncomment-7348103 , I think an **_advanced user_** can achieve shorter update interval of quick fix list without loading more requests to uBO repos:

- Fork and sync `uAssets`
- Auto set up `Last modified` and `Expires` time for the lists
- Add users' repo as a trusted source of lists
- Turn off uBO's quick fix and add users' own quick fix list

The only issue now is the `Expires` time (currently minimum is 12 hours)

**Comment by DandelionSprout** [comment] 2023-10-25 13:14
I notice that this thread (except the OP post) **only** discusses the uAssets lists, whereas 3rd-party lists haven't been discussed at all. I'd be in favour of this kind of technical support, so that 3rd-party list makers can set lower times, even if I myself have yet to edit my lists to use any value lower than 1 day at the time of writing.

**Comment by gwarser** [comment] 2023-10-25 13:21
Gorhill is working on this <https://github.com/AdguardTeam/FiltersCompiler/issues/192>. So there is a huge chance that in next version you will be able to serve differential updates with much higher frequency.

**Comment by gwarser** [comment] 2023-10-31 20:33
6 hours https://github.com/gorhill/uBlock/commit/153783cfaa10d87f8362f7e977445081fc40d439 

Differential updates https://github.com/gorhill/uBlock/commit/d05ff8ffebf8a35a9048c52837fa60a7a55f222f#diff-bb0a23b7c8c08b99549300d4571ee50f0fcbb877eb8b84fb2d4c4c3ec1ffc1c4

**Closed by gwarser** 2023-10-31 20:33 UTC
Labels: enhancement

**Comment by THEtomaso** [comment] 2023-11-22 17:41
> https://github.com/gorhill/uBlock/commit/2360bc02f301f572852b1609a97dedaf4b55929f

In uBO v1.54.0, `! Expires: Never` now prevents filter lists from updating, even when forced.
Could this be a bug/side-effect caused by the above change, or is it by design?

Details/discussion here:
https://github.com/DandelionSprout/adfilt/discussions/779/#discussioncomment-7644721

**Comment by gorhill** [comment] 2023-11-22 18:35
The list does update, it's just always seen as out of date.

**Comment by THEtomaso** [comment] 2023-11-22 19:33
OK, but in previous uBO versions, when forcing an update, the clock icon would appear regardlessly, simply indicating a succesfull update check.
In uBO v1.54.0, the out-of-date icon appears instead, resulting in an endless recheck.
In light of recent changes, which aims to lower uBO's number of requests and bandwidth usage, wouldn't its former behaviour be more appropriate for cases like this?
