### ISSUE TITLE
ublock mistakenly  treats 1st-party resources as 3rd-party when a domain has CNAME  and "Uncloak canonical names" enabled

### ISSUE THREAD

**Issue by tx9191** [uBlockOrigin/uBlock-issues#2084] opened 2022-04-10 02:27 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [x] uBO is the only extension
- [x] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The domain "www.juwanshe.com" has a CNAME that is "wwwjuwanshe.pp8.com", and there is a rule "||pp8.com^$3p" in EasyPrivacy List. When visiting http://www.juwanshe.com/roms/detail/19106, requests to www.juwanshe.com trigered the said rule and were blocked.
![图片](https://user-images.githubusercontent.com/5088446/162597885-8337d7e7-5379-427d-a56c-b96dff79a623.png)

### A specific URL where the issue occurs

http://www.juwanshe.com/roms/detail/19106

### Steps to Reproduce

1. Add "||pp8.com^$3p" to static rule list.
2. Enable "Uncloak canonical names".
3. Visit http://www.juwanshe.com/roms/detail/19106

### Expected behavior

The page should be shown properly.

### Actual behavior

The web page was broken.

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 99.0 64bit

### Operating System and version

Windows 10 21H2

**Comment by gorhill** [comment] 2022-04-10 10:45
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/1062>.

**Closed by gorhill** 2022-04-10 10:45 UTC
