### ISSUE TITLE
Bug on Gmail

### ISSUE THREAD

**Issue by deck2k** [uBlockOrigin/uBlock-issues#2011] opened 2022-02-25 20:24 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Bug with lastest version, hide the body of mail in Gmail.

### A specific URL where the issue occurs

mail.google.com

### Steps to Reproduce

1 Open mail.google.com
2. Open random mail in inbox
3.  Dont Show the body of mail.

### Expected behavior

Show body content

### Actual behavior

Dont show

### uBlock Origin version

1.41.4

### Browser name and version

Google Chrome Versión 98.0.4758.102 (Build oficial) (64 bits)

### Operating System and version

Windows 10 20H2

**Comment by gwarser** [comment] 2022-02-25 20:34
How you verified it's not a filter issue?

**Comment by gwarser** [comment] 2022-02-25 20:37
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906

**Closed by gwarser** 2022-02-25 20:37 UTC
