### ISSUE TITLE
Cosmetic filters and scriptlets don't get injected for an iframed website

### ISSUE THREAD

**Issue by uBlock-user** [uBlockOrigin/uBlock-issues#963] opened 2020-03-27 13:20 UTC
### Description

As above and discussed internally at https://github.com/orgs/uBlockOrigin/teams/ublock-issues-volunteers/discussions/177

### A specific URL where the issue occurs

`https://www.underhentai.net/shujii-no-inbou/`

### Steps to Reproduce

- Open the logger, browse to `https://www.underhentai.net/shujii-no-inbou/` (NSFW) in a new tab

- Scroll down abit untill the episode listing appears.

- Click the watch button for the first episode under `Online` category and be led to `https://www.underhentai.net/watch/?id=1790&ep=0`

- Switch to the logger page, put `streamz.`  as the filter, observe that scriptlets are not listed by the logger even though uBO is injecting 3 scriptlets as per uBlock Filters list --

```
streamz.cc##+js(acis, Math, zfgloaded)
streamz.cc##+js(window.open-defuser)
streamz.cc##+js(set, jQuery.adblock, false)
```
Cosmetic filters are not injected themselves, to reproduce, add `streamz.cc###video_1` and refresh the page, player will still appear working even though it's supposed to be hidden with the above filter.

### Expected behavior:

Scriptlets applied to an iframed domain appear as expected.

### Actual behavior:

Scriptlets applied to an iframed domain do not appear.

### Your environment

* uBlock Origin version: 1.25.3rc0
* Browser Name and version: Firefox 76
* Operating System and version: Win 10

**Comment by gorhill** [comment] 2020-03-27 14:04
So far from what I can tell is that uBO's content scripts are not injected by Firefox, this would explain why either cosmetic filtering or scriptlets are not injected, so the logger is reflecting this correctly.

I don't know why Firefox is not injecting uBO's content scripts -- I wonder if this has to do with the `streamz.cc` iframe having a `sandbox` attribute set, this needs further investigation.

**Comment by gorhill** [comment] 2020-03-27 14:26
There is <https://bugzilla.mozilla.org/show_bug.cgi?id=1610394>, which has been marked as a duplicate of <https://bugzilla.mozilla.org/show_bug.cgi?id=1411641>.

**Closed** 2020-04-15 13:54 UTC
Labels: Firefox, external
