### ISSUE TITLE
uBlock Origin does not work in PWAs on Firefox for Android

### ISSUE THREAD

**Issue by interbugma** [uBlockOrigin/uBlock-issues#766] opened 2019-10-29 13:25 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Opening a PWA in Firefox for Android via home icon/shortcut makes uBlock Origin not work within this window. Other addons do work. For example, uMatrix works well with settings you set up in your browser previously.

### A specific URL where the issue occurs

https://mobile.twitter.com/home
(note: I have no method of knowing exact url for the shortcut firefox creates)

### Steps to Reproduce

1. Open Firefox on Android with uBlock Origin
2. Go to https://mobile.twitter.com/home
3. Press on home icon next to address bar
4. Add Twitter's PWA shortcut to home screen
5. Launch twitter from this shortcut
6. Notice promoted articles pop up
7. Test if other addons work.

### Expected behavior:

Addon just keeps blocking content with existing settings. I don't expect being able to use it otherwise, but rather retaining background functionality in the way uMatrix does.

### Actual behavior:

Otherwise filtered content shows up.

### Your environment

* uBlock Origin version: uBlock Origin v1.23.0
* Browser Name and version: Firefox on Android, 68.2.0
* Operating System and version: Android 9

**Comment by gorhill** [comment] 2019-10-29 13:37
How do you know uMatrix works?

Did you try with another content blocker?

**Comment by gorhill** [comment] 2019-10-29 13:50
https://bugzilla.mozilla.org/show_bug.cgi?id=1411068

?

**Comment by interbugma** [comment] 2019-10-29 13:51
I know the uMatrix works because if I disable the script in browser, it is reflected in PWA.

Also, I tinkered with this a bit. If I quit the browser and launch PWA first, uBO does it's job. Only after I open firefox and let it run in background do I get promoted articles. Tested this 5 times now and it's consistent.

**Comment by gorhill** [comment] 2019-10-29 13:55
Did you try with other blockers? I am not set up to debug Firefox for Android. If other blockers suffers as well (try AdGuard), then this would suggest an issue with PWA framework rather than uBO specifically.

**Comment by gwarser** [comment] 2019-10-29 20:40
Discussed 2m ago on Reddit: https://www.reddit.com/r/uBlockOrigin/comments/csnme1/mobile_pwa_blocking/

Some issues with cosmetic filtering.

**Comment by gorhill** [comment] 2020-03-20 16:21
I tried with Firefox Preview Nightly and I couldn't spot promoted tweets in my timeline.

@interbugma, can you confirm whether the issue is present is Firefox Preview Nightly?

I will close the issue if no feedback on this issue in the coming days.

**Comment by gwarser** [comment] 2020-03-20 17:25
Works for me on DDG case from Reddit link https://www.reddit.com/r/uBlockOrigin/comments/csnme1/mobile_pwa_blocking/


Popup from "Access popup UI" button in logger needs adjustment to mobile UI (will be handy in PWA).

**Comment by interbugma** [comment] 2020-03-25 14:46
@gorhill I can no longer confirm that the issue is present in firefox at all since I didn't have it in the last few weeks. Initially I noticed that I would have less chance of having ads if I quit the firefox completely and launched it from web app (without main app being "opened"). But not even this functioned with 100% replication rate. Given that I no longer have the issue, it's solved on my end.

**Closed** 2020-03-25 14:47 UTC
Labels: Firefox-Android, something to address
