### ISSUE TITLE
Doesn't work any longer on Android devices (FF says, ublock wasn't signed and though can't be installed

### ISSUE THREAD

**Issue by NoComment1965** [uBlockOrigin/uBlock-issues#561] opened 2019-05-05 20:53 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gorhill** [comment] 2019-05-05 20:54
Duplicate of #558.

**Closed by gorhill** 2019-05-05 20:54 UTC
Labels: duplicate

**Comment by NoComment1965** [comment] 2019-05-05 21:08
Since a short time ublock origin can't be installed on Firefox. "Add to Firefox" leads to "AddOn isn't signed".
Manual download on github as well as other versions from addons.mozilla.org doesn't work, because FF tells that downloads are damaged (RARE: ALL versions - old, originally functioning versions as well - not working). Please verify! Tested on Android 8.1.0, different devices (Samsung mobile and tablet, both running on Android 8.1.0).

**Comment by uBlock-user** [comment] 2019-05-05 21:22
Firefox issue exclusive, fix -- `https://www.ghacks.net/2019/05/05/firefox-66-0-4-with-add-on-signing-fix-release-on-its-way/`
