### ISSUE TITLE
Support for "replace=" AdGuard filters

### ISSUE THREAD

**Issue by Mathnerd314** [uBlockOrigin/uBlock-issues#577] opened 2019-05-17 03:41 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

This was previously filed as [issue 2669](https://github.com/gorhill/uBlock/issues/2669) on the old bug tracker and was closed because the replace rules were only implemented in AdGuard Standalone. However as of 2018 Adguard's [page](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier) says that the replace rules are supported in AdGuard's Firefox add-on. I think that for feature parity replace rules should be implemented in uBlock or at least reconsidered.

### A specific URL where the issue occurs

The base AdGuard filters with replace rules are available from:
https://filters.adtidy.org/extension/firefox/filters/2.txt
There are 151 $replace filters in there. I tried looking at a few but they didn't seem to do anything useful as the sites had changed or disappeared.

### Steps to Reproduce

1. Create a filter rule with $replace like
```
||example.com^$replace=/examples/illustrations/
```

### Expected behavior:

Replace rule fires when browsing to example.com, so the page is full of the word "illustrations". See full documentation at Adguard's [page](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier).

### Actual behavior:

Filter rule is ignored. For comparison this works in AdGuard 3.0.13.

### Your environment

* uBlock Origin version: 1.19.2
* Browser Name and version: Firefox Developer Edition 68.0b1 (64-bit)
* Operating System and version: Windows 10 Home 1803

**Comment by uBlock-user** [comment] 2019-05-17 05:36
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#compatibility-with-different-versions-of-adguard-7

That hasn't changed, so not possible in Chromium and in Firefox we already have HTML Filtering.

**Comment by uBlock-user** [comment] 2019-05-17 05:37
Duplicate of https://github.com/gorhill/uBlock/issues/2669

**Closed by uBlock-user** 2019-05-17 05:36 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2019-05-17 11:19
Also, just like `rewrite`, there are security concerns to be had when giving filter list maintainers the ability to insert new text in the content of a resource. And as usual, _real world_ cases which can't be solved otherwise is always what is needed when requesting new filtering capabilities.
