### ISSUE TITLE
Is it possible to add some kind of password protection?

### ISSUE THREAD

**Issue by stbeep1** [uBlockOrigin/uBlock-issues#1434] opened 2021-01-04 04:10 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Is it possible to add a password protection before allowing user to change any settings or turn off uBO any website or bypass uBO Temporarily/Permanently ? 
Since some user will accidentally edit those settings or turned off uBO. This will be very useful for education environment.

### Your environment

* uBlock Origin version: v1.31.2
* Browser Name and version: Google Chrome 85
* Operating System and version: both Windows 10 (2004) and Chrome OS 85.

**Comment by uBlock-user** [comment] 2021-01-04 05:05
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1129

You can use create policies too.

**Comment by stbeep1** [comment] 2021-01-04 06:14
I have checked  #1129, but our cases is not the same, please consider reopening my "issue".

**Comment by stbeep1** [comment] 2021-01-04 06:20
The differences between me and #1246  is  #1129 is only installing uBO as a standard user, but for my environment, I force installed the uBO extension on all managed devices (like a BYOD Chromebook or Windows laptop). So that, I requested for the password protection feature, mostly for education environment. **Since some user will accidentally edit those settings or turned off uBO. Having the password protection feature will be very useful for education environment.** Please consider reopening my "case"  #1434 Thanks

**Comment by stbeep1** [comment] 2021-01-04 07:12
@gorhill Please consider reopening my "case" #1434 Thanks

**Comment by uBlock-user** [comment] 2021-01-04 07:18
Like I said before you can setup admin policies to force users to abide by those settings.

**Comment by stbeep1** [comment] 2021-01-04 07:23
> Like I said before you can setup admin policies to force users to abide by those settings.

I tried setting up admin policies a few times on different OS/devices, but it cannot prevent users accidentally edit those settings or turned off uBO.

**Comment by gwarser** [comment] 2021-01-04 11:54
Will it be enough to hide "Open the dashboard" button in uBO popup? `popupPanelLockedSections` can be used for this.

**Comment by stbeep1** [comment] 2021-01-04 12:00
> Will it be enough to hide "Open the dashboard" button in uBO popup? 
Well, I think that's not enough.

**Comment by stbeep1** [comment] 2021-01-04 12:05
![image](https://user-images.githubusercontent.com/76418860/103533398-00df6c00-4ec8-11eb-830d-a41cccf310ad.png)
@gwarser It will be great if uBO's settings page looks something like this.

**Comment by gwarser** [comment] 2021-01-04 12:09
You can reduce uBO popup to big blue power button only, block access to add-on manager by policy and manage uBO settings by policy.

**Comment by stbeep1** [comment] 2021-01-04 12:10
> You can reduce uBO popup to big blue power button only, block access to add-on manager by policy and manage uBO settings by policy.

Yes, I know and I did tried that. But currently, the policies that I can config in admin consle we're extremely limited for uBO.

**Comment by stbeep1** [comment] 2021-01-04 12:17
Is it possible to implement that? We really want to have the flexibility to manage those BYOD devices. Because in different situations we have different configures for end users.

**Comment by gorhill** [comment] 2021-01-04 12:44
Password protection is way beyond what I want to deal in uBO, you are requesting me to deal with crypto stuff in uBO.

Forget about password protection, best is that you detail exactly the capabilities and settings you want to control as an admin, and from there I will see what can be done.

**Comment by gwarser** [comment] 2021-01-04 12:52
>But currently, the policies that I can configure in admin consle we're extremely limited for uBO.

It uses complete uBO settings backup - it can set everything, how it is limited for you?

>We really want to have the flexibility to manage those BYOD devices. Because in different situations we have different configures for end users.

This sounds like you need better policy manager - not something uBO related. XY problem?

BYOD as "Bring your own device"? How this can be managed at all?

**Comment by stbeep1** [comment] 2021-01-04 12:56
I felt sad to hear from you.
But There's no reason for me to request something unless. I considered some kind of password protection is necessary for the education/enterprise environment.￼￼ Even there's are admin policies for uBO, it's still not enough. Please consider that again and I hope you can understand my situation. @gorhill

**Comment by gorhill** [comment] 2021-01-04 13:02
You said you want to replace ABP with uBO. I don't see any such feature in ABP, so why would you think it's required in uBO -- especially that unlike ABP, here is not a business but entirely volunteer driven work.

I will decline this as duplicate of #1129.

If you want specific settings to be admin-controlled in any way, please open specific issue for each of them.

**Closed by gorhill** 2021-01-04 13:02 UTC
Labels: something to address

**Comment by stbeep1** [comment] 2021-01-04 13:11
> > But currently, the policies that I can configure in admin consle we're extremely limited for uBO.
> 
> It uses complete uBO settings backup - it can set everything, how it is limited for you?

### The main problem is that even we forced installed uBO via google admin console and pushed out the settings, end users can still change them when they want. I can describe this as 08:00AM we pushed out the settings then users mess around in the settings page, the can still change the settings unless they reboot their devices. So that, I said it's limited for us. What do you think about that?

**Comment by stbeep1** [comment] 2021-01-04 13:16
> 
> > We really want to have the flexibility to manage those BYOD devices. Because in different situations we have different configures for end users.
> 
> This sounds like you need better policy manager - not something uBO related. XY problem? 
Well, I don't think so, since "Regulations" cannot prevent users accidentally edit those settings or turned off uBO at anytime. I just saw a reddit post and many users were having the same issues as well.

> 
> BYOD as "Bring your own device"? How this can be managed at all?

We have an AUP.

**Comment by gorhill** [comment] 2021-01-04 13:16
Well in the [other issue here](https://github.com/uBlockOrigin/uBlock-issues/issues/1433), you stated (my emphasis):

> Sometimes I want to whitelist a website for my users, but **I wanted to allow them to whitelist other websites**.

How is this compatible with the issue here?

If you want specific setting to be read-only, we can discuss this, password protection is not the proper approach.

**Comment by gorhill** [comment] 2021-01-04 13:20
Note that you can already restrict the popup panel to be minimal so as to prevent a user from using the extra capabilities in it:

![a](https://user-images.githubusercontent.com/585534/103539213-a281a180-4e65-11eb-9ecb-0f2227a97a1a.png)

**Comment by stbeep1** [comment] 2021-01-04 13:20
> If you want specific setting to be read-only, we can discuss this, password protection is not the proper approach.
Well, specific setting to be read-only is also a good thing.

**Comment by stbeep1** [comment] 2021-01-04 13:25
Side note: uBO is still my still my favourite Chrome extensions since 2015. I am not a uBO haters or any "business oriented movement guy" that I of thing. I totally agree the perspective/idea of the uBO team.
