### ISSUE TITLE
'blocking remote fonts option' blocks also local fonts

### ISSUE THREAD

**Issue by make-it-really-easy** [uBlockOrigin/uBlock-issues#1524] opened 2021-03-10 16:38 UTC
When you have turned on 'blocking remote fonts option' it blocks also local fonts.

Blocking remote fonts is good for privacy - it prevents the remote server to know that your website is loaded.

But this option spoils webpages that really care about privacy and do not load fonts from remote servers.

**Comment by gorhill** [comment] 2021-03-10 16:49
Duplicate of #888 -- which is an issue you also opened.

Do not abuse the issue tracker and the time of volunteers.

**Closed by gorhill** 2021-03-10 16:49 UTC

**Comment by make-it-really-easy** [comment] 2021-03-11 10:26
I thought that I could not write at closed thread. That issue is not clarified. It was not understood by the reader . That is why I wanted to make it more clear.

**Comment by make-it-really-easy** [comment] 2021-03-17 14:21
'privacy and remote fonts' 

I can not write at the closed thread.

I have not also known that replying to email actually make post at the forum.

That issue is not clarified.

That option is for privacy.

Blocking remote fonts is good for privacy - it prevents the remote server to know when your website is loaded (remote server know which website loads the fonts  ).  But this option spoils webpages that really care about privacy and do not load fonts from remote servers and keeps them locally at the same place - where it keeps pictures, html, css, js documents and so on.
