### ISSUE TITLE
Filter - Porn Site Rule Blocking HTTPs?

### ISSUE THREAD

**Issue by Roshke** [uBlockOrigin/uBlock-issues#1371] opened 2020-12-01 07:58 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
Enable Ublock enter Any Site and Page will be Blank or Corrupted
2. [Second Step]
Disable Ublock and Site loads again.
3. [and so on...]

### Expected behavior:

[What you expected to happen]
To load Sites like google.com normally.

### Actual behavior:
Here's a Pictrue of the Filter that is Causing this
https://i.imgur.com/rwocdJe.png

### Your environment

* uBlock Origin version: Latest from Chrome Store
* Browser Name and version: Latest version of Google Chrome
* Operating System and version: Latest version of Windows 10

**Comment by uBlock-user** [comment] 2020-12-01 08:03
Purge all caches and then force update all filterlists.

**Comment by gorhill** [comment] 2020-12-01 13:11
Duplicate of #1365.

**Closed by gorhill** 2020-12-01 13:11 UTC
