### ISSUE TITLE
uBlock for Thunderbird lacks the all-important Ad Select and Block function of uBlock

### ISSUE THREAD

**Issue by McBobb** [uBlockOrigin/uBlock-issues#1242] opened 2020-09-13 02:30 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock for Thunderbird lacks the all-important Ad Selector and Block function. It is about the only way things like mailing list email ads can be blocked.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

N/A

### Steps to Reproduce

1. [First Step] Always relevant at all times.
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen] The uBlock dropdown panel to have an Eyedropper or Ad-Zapper icon to allow you to select to block ads

### Actual behavior:

The dropdown panel has neither of those icons

### Your environment

* uBlock Origin version: 1.29.3.15
* Browser Name and version: Firefox 80.0.1
* Operating System and version: Windows 10 Home, ver 1909 Build 18363.1082

**Comment by r-a-y** [comment] 2020-10-17 23:59
Duplicate of #825.

**Comment by gwarser** [comment] 2020-10-18 00:23
Duplicate of #825

**Closed by gwarser** 2020-10-18 00:23 UTC
Labels: Thunderbird, something to address
