### ISSUE TITLE
Off button with an option to disable only some lists per-site

### ISSUE THREAD

**Issue by geekley** [uBlockOrigin/uBlock-issues#1109] opened 2020-06-14 03:04 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently, the on/off button can only disable all lists per-site.
Please add an option to **disable only some lists for a certain site**. For example, I might want to disable ad-blocking lists, but keep tracking and malware lists on.
Opera and Vivaldi's native ad-blockers kind of do this by having separate ad/tracking lists.

The most complete implementation I suggest is the following.

1. Categorize lists into editable **Blocking List Groups**. Example: Ads, Resource Abuse, Annoyances, Privacy, Malware. **You should be able to edit groups and categorize lists into groups freely, even custom lists.** Properties of a Group:
    - Id, e.g. `abuse`
    - Display name, e.g. `Resource Abuse`
    - Blocking lists, e.g. `[NoCoin, etc]`
    - Whether or not the group is **enforced** (can't be disabled per-site). For example, if Malware group is enforced, there won't be a per-site off option for Malware, and even the big off button will still keep those lists on.
2. Add additional toggles next to the on/off button (maybe inside a dropdown). Each option has the name of a group. Turning it off whitelists that group for the site.
    - Presumably, the whitelist would have some syntax corresponding to this behavior, that specifies that a whitelist entry for a site is only for a specific group. For example: `@abuse::example.com`

So, for example,, when a site has an anti-adblocker, you would be able to disable all advertisement lists with a single click on that group's toggle, and keep others lists (such as malware, tracking) enabled.

### A specific URL where the issue occurs

Not applicable.

### Steps to Reproduce

Not applicable.

### Expected behavior:

Not applicable.

### Actual behavior:

Not applicable.

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Vivaldi 3.1.1929.34 Stable (64 bits)
* Operating System and version: Windows 7

**Comment by uBlock-user** [comment] 2020-06-14 04:53
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/267

**Closed by uBlock-user** 2020-06-14 04:53 UTC
Labels: enhancement
