### ISSUE TITLE
::before pseudo-element + procedural filters like :has-text() doesn't work

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2786] opened 2023-08-25 16:59 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

This filter only works on Chromium (v115) and doesn't work on Firefox (v116):
```adb
www.bing.com##li.b_algo:has(div) h2::before:style(content: 'Second Text' !important; color: #E6000D !important;)
```

But this one without `:has()` works in both browsers:
```adb
www.bing.com##li.b_algo h2::before:style(content: 'First Text' !important; color: #E6000D !important;)
```

![image](https://github.com/uBlockOrigin/uBlock-issues/assets/17685483/77484ac1-4d35-446b-860c-ede880d4da46)

### A specific URL where the issue occurs.

`https://www.bing.com/search?go=Search&q=download+vlc&qs=ds&form=QBRE`

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

1.51.1rc1 dev

### Browser name and version

.

### Operating System and version

.

**Comment by gwarser** [comment] 2023-08-25 18:35
Native `has` not enabled in Firefox yet?

**Comment by gorhill** [comment] 2023-08-25 18:39
It's not possible to programmatically query a selector using `::before`, so it's not something that can be fixed. Your selector `li.b_algo:has(div) h2::before` requires procedural filters for platforms not supporting native `:has()`, thus that filter can't work.

uBO should report such filter as en error in Firefox, so that is the thing to fix.

**Comment by garry-ut99** [comment] 2023-08-26 07:51
Duplicate of: 
- https://github.com/uBlockOrigin/uBlock-issues/issues/2090

<br>
<hr>

> https://github.com/uBlockOrigin/uBlock-issues/issues/2786#issuecomment-1693783513 : Your selector `li.b_algo:has(div) h2::before` requires a procedural filter for platforms not supporting native `:has()`, thus that filter can't work.

<br>

Even with: `layout.css.has-selector.enabled` flag enabled in Firefox, it still doesn't work.

**Comment by krystian3w** [comment] 2023-08-26 18:14
It works as vanilla with enabled experimental preference (not flag):

![obraz](https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/c068fbf5-4dfb-452e-8edf-fa3bc9bdd827) |
--- |

Apparently, the implementation of this is being delayed (it was supposed to be from 116, and in two days already the release of 117), even the Night edition 118 (It was not switched to active status or removed so that someone could not so block CSS4 as a performance threat.).

**Comment by krystian3w** [comment] 2023-08-31 17:06
May post was not spam...

**Comment by JobcenterTycoon** [comment] 2023-11-10 13:20
Native `has` will be enabled by default in Firefox 121 https://caniuse.com/?search=%3Ahas()

**Comment by u-RraaLL** [comment] 2023-12-10 13:47
> Native `has` will be enabled by default in Firefox 121 https://caniuse.com/?search=%3Ahas()

But:

> Pseudo-elements are also not valid selectors within `:has()` and pseudo-elements are not valid anchors for `:has()`.

**Closed** 2024-01-17 09:42 UTC
Labels: bug, fixed
