### ISSUE TITLE
UI broken on mobile (Fennec)

### ISSUE THREAD

**Issue by angriness-sleek** [uBlockOrigin/uBlock-issues#1063] opened 2020-05-21 15:36 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The UBO UI is cut from the left on mobile as it doesn't open as a popup on PC but as a new window
![IMG_20200521_203917_359](https://user-images.githubusercontent.com/62484249/82573252-12604780-9b75-11ea-9f06-f961015e7304.jpg)

### A specific URL where the issue occurs

https://github.com/uBlockOrigin/
but literally on every site

### Steps to Reproduce

1. Install Fennec Fdroid from Fdroid, or any other Firefox for mobile
2. Install UBO
3. Open a website
4. Click the 3 dots and open unlock Origin

### Expected behavior:

The layout should be visible as a whole as in PC, not a cut in half layout.
Example (on pc):

![IMG_20200521_205101_490](https://user-images.githubusercontent.com/62484249/82574517-cb735180-9b76-11ea-8f46-4428c12332fd.jpg)

### Actual behavior:
A cutout layout as shown in the picture attached

### Your environment

* uBlock Origin version: 1.27.0
* Browser Name and version: Fennec Fdroid v68.8.0
* Operating System and version: Vanilla Android 10
* smallest width in android developer  #settings: 597dp
which is why my cutout portion is much smaller than show in this issue: https://github.com/uBlockOrigin/uBlock-issues/issues/1051 
And in contrast to that issue, the panel is ALWAYS cutout for me for every site

**Comment by gwarser** [comment] 2020-05-21 20:42
>smallest width in android developer #settings: 597dp

On my phone with 552 I see mobile interface, with 600 - desktop interface. Everything fits nicely.

**Comment by gwarser** [comment] 2020-05-21 20:43
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1051

**Closed by gwarser** 2020-05-21 20:43 UTC
Labels: Firefox-Android

**Comment by angriness-sleek** [comment] 2020-05-21 20:45
I did tell why I made another issue because #1051 had it breaking sometimes, while its broken for me always

**Comment by angriness-sleek** [comment] 2020-05-21 20:49
Alright you helped me fixed it, when I changed DPI to 552 and then checked, the layout is complete now, set to mobile, switching back to 597 or 600 does not seem to change it again. Thanks I guess..'

**Comment by gwarser** [comment] 2020-05-21 21:10
> switching back to 597 or 600 does not seem to change it again.

It will change after browser restart.

**Comment by gorhill** [comment] 2020-05-22 11:08
@angriness-sleek side note, what is the reason you are using _allow_ rules instead of _noop_ rules?
