### ISSUE TITLE
Can't copy/cut/paste all of my custom filter

### ISSUE THREAD

**Issue by tawissus** [uBlockOrigin/uBlock-issues#928] opened 2020-03-04 23:47 UTC
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

It is impossible to cut/copy paste all custom filters.

### Expected behavior:

It should be possible to cut/copy/paste every filter inside the settings / own filter list. Sometimes I want to cut all new picked filters to paste them in my own filter list.

* uBlock Origin version: 1.25
* Browser Name and version: Firefox Android
* Operating System and version: Android 10

**Comment by gorhill** [comment] 2020-03-05 00:14
I csn select all by double tapping the gutter.

**Comment by peace2000** [comment] 2020-03-05 18:42
https://github.com/uBlockOrigin/uBlock-issues/issues/903

This seems to be an issue with Android 9 and 10.

**Comment by uBlock-user** [comment] 2020-03-05 18:51
Duplicate of #903

**Closed by uBlock-user** 2020-03-05 18:51 UTC
Labels: Firefox-Android, unable to reproduce

**Comment by tawissus** [comment] 2020-03-05 18:53
Ah. Yes my phone uses Android 10.
Double tapping only mark a word or a part of one filter. 
If I use Gboard to mark and cut all filters only some filters were copied/pasted.

**Comment by gorhill** [comment] 2020-03-05 19:02
> Double tapping only mark a word or a part of one filter

Tap in the gutter.

**Comment by tawissus** [comment] 2020-03-05 19:10
Oh. Than you! 
I needed a little time to translate gutter.
