### ISSUE TITLE
Nothing is blocked in Thunderbird

### ISSUE THREAD

**Issue by starborn1701** [uBlockOrigin/uBlock-issues#2652] opened 2023-05-12 11:56 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

I installed uBlock Origin 1.49.2 in Thunderbird 102.10.0 on Fedora 37 without any problems several days ago. Since then not a single request has been blocked. 
![thunder](https://github.com/uBlockOrigin/uBlock-issues/assets/113305132/eab70a03-5475-433e-93f6-da436831c355)

### A specific URL where the issue occurs.

www.google.com

### Steps to Reproduce

1. Open E-Mail
2. Allow remote content
3. No request is blocked

### Expected behavior

I except the requests to be blocked, for example to Google Analytics

### Actual behavior

Nothing happens.

### uBO version

1.49.2

### Browser name and version

Thunderbird 102.10.0

### Operating System and version

Fedora37

**Comment by gorhill** [comment] 2023-05-12 11:57
uBO doesn't worl on email, just feeds.

**Comment by gwarser** [comment] 2023-05-12 17:02
Maybe should be marked as duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1839
and even more, #1839 should be duped to https://github.com/uBlockOrigin/uBlock-issues/issues/825#issuecomment-639653511 with at least a possible solution to content scripts in messages?

**Comment by gorhill** [comment] 2023-11-29 01:04
Duplicate of #1839.

**Closed by gorhill** 2023-11-29 01:04 UTC
Labels: enhancement, Thunderbird
