### ISSUE TITLE
add support input schema for lists containing multiple domains

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uBlock-issues#594] opened 2019-05-25 01:05 UTC
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

many developers have to build a filter lists of domains for their filters from scratch.
the idea is to use jointly developed domain templates for a group of sites with the same design.

potential benefits
- reduct the filter list size 
- remove multiple duplicated domians
- easy add/remove domian from the multiple filter lines/rules in one time
- more modulare filters, folded like lego blocks

### A specific URL where the issue occurs

https://github.com/AdguardTeam/FiltersRegistry/issues/63#issuecomment-494471056
https://github.com/gorhill/uBlock/issues/3406#issuecomment-355748757

### Expected behavior:

example rule to solve that problem
```
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist##examplerule
```

### Actual behavior:

an exemplary filter list in which this problem occurs
https://github.com/yourduskquibbles/webannoyances/blob/caba2705e80537a571324af997dc35a8af1ca398/filters/css_style_filters.txt#L25

<details><summary>screenshot</summary>

![2019-05-25](https://user-images.githubusercontent.com/5884000/58366073-38ed9300-7ecd-11e9-9501-9589b5736eec.png)

</details>

### Your environment

* uBlock Origin version: ubo latest
* Browser Name and version: chrom
* Operating System and version: w10

**Comment by gwarser** [comment] 2019-05-25 10:21
Isn't this another mutation of https://github.com/uBlockOrigin/uBlock-issues/issues/330 (and dupes)?

**Comment by uBlock-user** [comment] 2019-05-25 10:25
Yeah sounds like a duplicate of that.

**Closed** 2019-05-25 10:46 UTC
Labels: something to address

**Comment by gorhill** [comment] 2019-05-25 11:03
If it's a duplicate of #330, why was `https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist##examplerule` given as an example? It's just a list of hostnames.

**Comment by KonoromiHimaries** [comment] 2019-05-25 11:18
> all the hostnames in that file would apply to the cosmetic filter ##example?

@gorhill yes, it's a clean and aesthetic solution

**Comment by KonoromiHimaries** [comment] 2019-05-25 11:34
@gorhill or you can assign a link to the name and use a template on filter list

example

```
!# set source https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist = %example%
```

example usage

```
%example%##examplerule
%example%##examplerule2
```

**Comment by uBlock-user** [comment] 2019-05-25 17:06
Duplicate of #330
