### ISSUE TITLE
addEventListener-defuser don't work

### ISSUE THREAD

**Issue by yingziwu** [uBlockOrigin/uBlock-issues#1812] opened 2021-11-11 16:14 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The [addEventListener-defuser](https://github.com/gorhill/uBlock/wiki/Resources-Library#aeldjs-) don't always work.

### A specific URL where the issue occurs

https://www.zhihu.com/question/51459956/answer/245693096

### Steps to Reproduce

1. Open Firefox and install uBlockOrigin.
2. Add the following rules to "My filters".

  ```
  www.zhihu.com##+js(aeld, click)
  www.zhihu.com##+js(aeld, copy)
  www.zhihu.com##+js(aeld, keydown)
  www.zhihu.com##+js(aeld, keypress)
  www.zhihu.com##+js(aeld, keyup)
  www.zhihu.com##+js(aeld, mousedown)
  www.zhihu.com##+js(aeld, mouseout)
  www.zhihu.com##+js(aeld, mouseover)
  www.zhihu.com##+js(aeld, selectionchange)
  ```

3. Visit the website Zhihu, eg. https://www.zhihu.com/question/51459956/answer/245693096

### Expected behavior

The eventListener that mentioned above don't been attached. 

### Actual behavior

The eventListener are attached.
![Screenshot_20211111_235709](https://user-images.githubusercontent.com/22741471/141331213-67be308d-3852-49ca-b502-f7be16a6c810.png)
![Screenshot_20211111_235725](https://user-images.githubusercontent.com/22741471/141331228-2425fcd7-0f0b-4b78-944b-0182e855334a.png)
![Screenshot_20211111_235736](https://user-images.githubusercontent.com/22741471/141331237-60dbbed7-cc6e-4961-a7ba-e61f715af95c.png)

### uBlock Origin version

1.38.6

### Browser name and version

Name: Firefox,Version: 94.0.1, Build ID: 20211104013219, Distribution ID: archlinux

### Operating System and version

Archlinux, Linux 5.14.16-zen1-1-zen

**Comment by uBlock-user** [comment] 2021-11-11 16:43
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/235

**Closed by uBlock-user** 2021-11-11 16:43 UTC
