### ISSUE TITLE
Can't use set-constant.js multiple times for same parent property

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uBlock-issues#156] opened 2018-08-09 10:30 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Set-constant.js doesn't work for subdomains.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
`https://wiadomosci.wp.pl/`
### Steps to Reproduce

For example, add this:
```
wp.pl##script:inject(set-constant.js, WP.crux.set, noopFunc)
||std.wpcdn.pl/wpjslib/*/wpjslib-chunk-notification.js
```
Then go to wiadomosci.wp.pl and you should not see GDPR message with blur, but it's here. But if you add `wiadomosci.wp.pl##script:inject(set-constant.js, WP.crux.set, noopFunc)`, then everything is ok.

### Your environment

* uBlock Origin version: 1.16.14
* Browser Name and version: Chromium 68.0.3440.75 
* Operating System and version: Manjaro 17.1.11 Hakoila

**Comment by uBlock-user** [comment] 2018-08-09 11:09
> GDPR message with blur

Can't reproduce. I don't see any GDPR msg with blur.

**Comment by hawkeye116477** [comment] 2018-08-09 11:31
If you test with Polish Filter, then you must also probably test previous version without that long filter `open.fm,dobreprogramy.pl,www.wp.pl,wiadomosci.wp.pl,sportowefakty.wp.pl,money.pl,kobieta.wp.pl,gwiazdy.wp.pl,portal.abczdrowie.pl,parenting.pl,moto.wp.pl,tech.wp.pl,horoskop.wp.pl,gry.wp.pl,opinie.wp.pl,turystyka.wp.pl,tv.wp.pl,morizon.wp.pl,komorkomania.pl,gadzetomania.pl,fotoblogia.pl,finanse.wp.pl,pudelek.pl##script:inject(set-constant.js, WP.crux.set, noopFunc)` :smile: Also GDPR message may be geolocked.

**Comment by gwarser** [comment] 2018-08-09 11:36
I cannot reproduce with or without POL filter list.

**Comment by gorhill** [comment] 2018-08-09 11:56
Unable to reproduce:

![a](https://user-images.githubusercontent.com/585534/43897261-7511617a-9ba9-11e8-8162-0f9ab55fb717.png)

The proper way to make the case that `set-constant.js` does not work is not by looking at web page behavior, it's by stepping in code. If the filter does not work after all, it's a filter issue.

**Comment by hawkeye116477** [comment] 2018-08-09 12:38
@uBlock-user I don't think so, I tested with default settings and disabled other extensions. If I didn't do that, then I wouldn't check it :smile: But strange is that, I tested again and now it works correct.
But @F4z told me, that still reproduce that.

**Comment by gorhill** [comment] 2018-08-09 12:54
> But @F4z told me, that he still reproduce that.

He needs to make the case that the scriptlet is not executing, not that the page behave one way or another. Scriptlets are subject to timing issues, moreso depending on one's environment. For example, the more extensions installed which inject content scripts, the more chance uBO's scriptlets will be injected later, etc. In any case, the important point here is to provide evidence `set-constant.js` itself does _not_ execute.

**Comment by F4z** [comment] 2018-08-09 13:03
First screenshot with `wp.pl##script:inject(set-constant.js, WP.crux.set, noopFunc)` only, second screenshot when I added `wiadomosci.wp.pl##script:inject(set-constant.js, WP.crux.set, noopFunc)`.
<details><summary>First screenshot</summary>

![image](https://user-images.githubusercontent.com/11742596/43900436-355e7900-9be5-11e8-9d1c-434730c2ff13.png)

</details>

<details><summary>Second screenshot</summary>

![image](https://user-images.githubusercontent.com/11742596/43900392-09db8e80-9be5-11e8-9d35-e440b96da208.png)

</details>

<br>

It's not important to me, so if you can't reproduce it then this issue can be closed.

**Comment by gorhill** [comment] 2018-08-09 13:24
> so if you can't reproduce

After I enabled POL, I can reproduce the GDPR warning. However after I disabled POL, I confirm that `set-constant.js` is executed, and I get the warning with both `wp.pl` or `wiadomosci.wp.pl`:

![a](https://user-images.githubusercontent.com/585534/43901528-b67ad73e-9bb5-11e8-9d84-d1ff20f7cb63.png)

**Comment by gorhill** [comment] 2018-08-09 13:27
How about:

    wp.pl##script:inject(cookie-remover.js, STabid)

Seems to work on my side.

**Comment by F4z** [comment] 2018-08-09 18:53
Thank you for your answer, I checked it once again and now this rule - `wp.pl##script:inject(set-constant.js, WP.crux.set, noopFunc)` - works correctly, it's strange, because I didn't change anything.

**Comment by F4z** [comment] 2018-08-13 20:07
One more question, I disabled Polish filter list and added these two rules:
`pilot.wp.pl##script:inject(set-constant.js, WP.crux.sealed, falseFunc)`
`pilot.wp.pl##script:inject(set-constant.js, WP.crux.set, noopFunc)`
then opened this website - `https://pilot.wp.pl/tv` and only (the second) one of these rules works (please look on a screenshot).
Is it by design, bug or something wrong on my end?

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11742596/44053307-9225e0e4-9f3f-11e8-99bf-82f9bf1c163d.png)

</details>

**Comment by gorhill** [comment] 2018-08-14 11:00
I see what the problem is.

**Comment by prateekrastogi** [comment] 2020-01-26 15:05
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by gargul03** [comment] 2020-10-12 12:39
We most probably have found an issue with `set-constant` scriplet, it came from https://github.com/AdguardTeam/AdguardFilters/issues/65244, I reported ads on WP.PL, but the issue was not fixed and it was closed, when I asked why, AdamWr told me: https://github.com/AdguardTeam/AdguardFilters/issues/65244#issuecomment-706588048) it's fixed in uBO `1.28.4` and older uBO versions and he doesn't know why the filter doesn't work in newer uBO vesions, and he said he suspects `set-constant` being most probably broken on new uBO versions, I checked and I confirm the issue (despite the fact krystian3w can't reproduce https://github.com/AdguardTeam/AdguardFilters/issues/65244#issuecomment-707000855):

Steps to reproduce:
1. Disable all filter lists (it is not necessary, can be reproduced with default lists enabled (+ PL) as well)
2. Visit `www.wp.pl` and notice ads.
3. Enable AdGuard Base filter or just add a filter AdamWr mentioned: 
`www.wp.pl##+js(set-constant, Object.prototype.advViewability, undefined)` to My Filters pane.
4. Notice: 
- on uBO 1.28.4 or lower, `set-constant` is visible in the logger and the ads are gone
- on uBO 1.29.2 or above, `set-constant` is not visible in the logger and the ads are not gone

I don't know whether this is:
- a uBO's bug 
- or this is just how the new  `set-constant` works and we need to create a new / different filter

**Comment by gorhill** [comment] 2020-10-12 13:18
I can reproduce. I find that setting the [`configurable` property](https://github.com/gorhill/uBlock/blob/26985f04a9925e918245232018de9edf50c35521/assets/resources/scriptlets.js#L757) to `false` restore the behavior of 1.28.4.

**Comment by gorhill** [comment] 2020-10-12 13:28
So I guess I should restore the behavior and another (more complex) solution will have to be developed.

**Comment by gorhill** [comment] 2020-10-12 14:58
Actually, it just occurred to me that I can simply prevent the targeted property itself to not be configurable while allowing the parent properties leading to the target property to be configurable so as to allow trapping multiple times the same chain of properties.

**Comment by gwarser** [comment] 2020-10-12 15:55
https://github.com/AdguardTeam/AdguardFilters/issues/65244#issuecomment-707201075

**Closed by gwarser** 2020-10-12 15:55 UTC
Labels: bug

**Comment by krystian3w** [comment] 2020-10-14 12:18
https://github.com/AdguardTeam/AdguardFilters/issues/65519

**Comment by gwarser** [comment] 2020-10-15 15:59
@gorhill there seems to be one more corner case when one list redefines as `null` property set by other list as `undefined` (or vice-versa). `Object.defineProperty` throws, because property is not configurable (as far as I can understand when stepping through code).

Case is https://github.com/AdguardTeam/AdguardFilters/issues/65519

Add to My filters:

	thingiverse.com##+js(set-constant, blockedElement.className, null)
	thingiverse.com##+js(set-constant, blockedElement.className, undefined)

Open: `https://www.thingiverse.com/thing:2873324`.

cc: @krystian3w

**Comment by gorhill** [comment] 2020-10-15 16:40
To fix this would take a lot of non-trivial code, not sure it's worth it if this can be reasonably be fixed in filter lists. Maybe that non-trivial code will occur in some future but for now it's far off.

**Comment by gorhill** [comment] 2020-10-15 16:50
>  it works with `""`, but does not with any other constant

`""` is not a valid constant, you need to use `''`.

And yes, after investigation, I confirm what I said above.

**Comment by addisr** [comment] 2020-10-19 15:35
@gorhill I think this broke [this rule](https://github.com/tomasko126/easylistczechandslovak/blob/eefa73f4b3c8bc6181dde763288c33decfcae1ba/filters_ublock.txt#L5). Kinda. Property seems overridden but console says `Uncaught TypeError: can't redefine non-configurable property "adblock"` and some features of the website are broken.

**Comment by gorhill** [comment] 2020-10-19 15:55
@addisr Thanks for feedback. I can reproduce, and I have a fix. Now I wonder if this warrants an emergency fix.

**Comment by uBlock-user** [comment] 2020-10-20 08:11
> Now I wonder if this warrants an emergency fix.

CNBC is now broken - https://www.reddit.com/r/uBlockOrigin/comments/jeei8n/ublockfilters_is_breaking_cnbc/

**Comment by gwarser** [comment] 2020-10-20 14:38
Isn't https://github.com/gorhill/uBlock/commit/2b262b24e2c4a38957f0be3544dcf28cf60f9e7d actually fixing what I said above in https://github.com/uBlockOrigin/uBlock-issues/issues/156#issuecomment-709423918 ?

**Comment by krystian3w** [comment] 2020-10-20 14:40
Maybe.
