### ISSUE TITLE
When "Block remote fonts" is enabled, JavaScript is executed regardless of the uMatrix settings

### ISSUE THREAD

**Issue by diabonas** [uBlockOrigin/uBlock-issues#502] opened 2019-04-01 12:22 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension → the issue happens in conjunction with uMatrix, which is the only other installed extension
    - [x] uBlock Origin with default lists/settings → except "Block remote fonts", as indicated in the description below
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In Firefox, when the uBlock Origin option "Block remote fonts" is enabled, JavaScript is not blocked any more by uMatrix.

### A specific URL where the issue occurs

https://javatester.org/javascript.html

### Steps to Reproduce

1. Create a fresh Firefox profile.
2. Install uBlock Origin and uMatrix from https://addons.mozilla.org.
3. Remove the default `* 1st-party * allow` rule from uMatrix so that JavaScript is disabled on all websites by default.
4. Enable "Block remote fonts" under "Settings/Default behavior" in uBlock Origin.
5. **Restart Firefox** (until the restart, everything works as expected).
6. Open <https://javatester.org/javascript.html> and observe that JavaScript is executed. 

    Note that the site additionally displays the `<noscript>` tag "JavaScript IS NOT WORKING in your web browser", unless "Spoof <noscript> tags when 1st-party scripts are blocked" is disabled in uMatrix. However that doesn't mean that JavaScript is not running: the site displays the JavaScript and browser version, which wouldn't work with JavaScript disabled.
7. For comparison, disable "Block remote fonts" in uBlock Origin and see how the test site renders with JavaScript disabled.

    Note that if you re-enable "Block remote fonts", JavaScript will stay disabled until you restart the browser.

### Expected behavior:

JavaScript should not be executed if it is disabled in uMatrix.

### Actual behavior:

JavaScript is executed on the test page and other websites if "Block remote fonts" is enabled in uBlock Origin, regardless of the uMatrix settings.

### Your environment

* uBlock Origin version: 1.18.14
* uMatrix version: 1.3.16
* Browser Name and version: Firefox 66.0.2
* Operating System and version: Arch Linux (rolling release), also confirmed on Windows 7 Professional SP1

**Comment by gwarser** [comment] 2019-04-01 13:10
Finally official issue for this :)

**Comment by diabonas** [comment] 2019-04-01 13:26
Yikes, that's an ugly situation... Thank you very much for the pointers, I already suspected this might be an upstream issue, but didn't have an idea what to look for.

**Comment by gorhill** [comment] 2019-04-01 13:42
It can be fixed, but it's not a trivial one. This will require "compiling" the rules which can cause CSP directives injection into a `contentScripts.register()` -- a non-trivial workaround which would become pointless once the issue is fixed in Firefox. Now that is the "simple" part, even more complicated is enforcing the `csp=` directives in filter lists -- forget about this part.

It would be much simpler if this was just fixed in Firefox.

**Comment by uBlock-user** [comment] 2019-04-01 17:24
I opened that bug almost a year ago on bugzilla, no action has been taken so far, it's been queued into oblivion...

**Comment by Thorin-Oakenpants** [comment] 2019-04-03 14:19
> Finally official issue for this :)

:grin:

**Comment by Cerberus-tm** [comment] 2019-04-16 19:58
Hmm, this looks ugly. I haven't completed the steps in the first post. But I block remote fonts and Javascript by default, using Ublock Origin; even so, the Javascript isn't running for me on that site. So it is as desired and expected in my Firefox. Javascript is allowed for 1st-party in Umatrix. How come I am not affected? Is it because of other Ublock rules I might have?

**Comment by gorhill** [comment] 2019-04-16 22:23
> How come I am not affected?

Because you are blocking inline JavaScript and inline fonts with uBO -- so uBO injects both CSP, the issue is when two or more extensions try to inject CSPs.

**Comment by uBlock-user** [comment] 2019-04-16 22:44
> the issue is when two or more extensions try to inject CSPs.

and at the website which itself doesn't any CSP headers in response header.

**Comment by Cerberus-tm** [comment] 2019-04-16 22:48
> 
> 
> > How come I am not affected?
> 
> Because you are blocking inline JavaScript and inline fonts with uBO -- so uBO injects both CSPs, the issue is when two or more extensions try to inject CSPs.

And Umatrix + Ublock don't inject each its own CSP?

**Comment by gorhill** [comment] 2019-04-16 22:50
> Umatrix + Ublock don't inject each its own CSP?

You said:

> Javascript is allowed for 1st-party in Umatrix

**Comment by Cerberus-tm** [comment] 2019-04-19 23:40
> 
> 
> > Umatrix + Ublock don't inject each its own CSP?
> 
> You said:
> 
> > Javascript is allowed for 1st-party in Umatrix

Sorry, I'm a total layman. I'm afraid I wouldn't know when an extension injects a CSP. So when Javascript is allowed for 1st party in Umatrix, Umatrix doesn't inject a CSP on that page?

Is it only when Umatrix would *forbid* Javascript (following the result of its rules) that it injects a CSP? So if I tell Umatrix to block Javascript for site X, but then tell it to allow Javascript for a subdomain of site X—so that, as a result, Javascript is allowed on the subdomain—, then Umatrix is *not* injecting a CSP on pages of that subdomain?

And is it that a CSP for Javascript can only interfere with another Javascript CSP, not with e.g. an XHR rule, not even on the same subdomain? But inline Javascript and normal Javascript rules *can* interfere with each other?

Is the best strategy, then, to always allow Javascript in Umatrix, for all domains, and manage all Javascript rules in Ublock?

Or is there another general strategy or work-around to follow?

Sorry for all these question. One last one: Noscript can still block Javascript on a page even when combined with blocking rules from Umatrix and Ublock (I tested this). I wonder how that works. Presumably it does this through some unusual way that wouldn't  work for Ublock/Umatrix?

**Comment by Cerberus-tm** [comment] 2019-04-19 23:47
> 
> 
> > the issue is when two or more extensions try to inject CSPs.
> 
> and at the website which itself doesn't insert any CSP headers in response header.

Ah, so there is no problem as long as the website itself doesn't use a Javascript CSP? Or am I mistaken?

**Comment by gwarser** [comment] 2019-04-20 09:37
https://github.com/ghacksuserjs/ghacks-user.js/issues/664

Read more, write less, ask questions on reddit.

>Noscript can still block Javascript...

Because NS forces its listener in a loop.

>Ah, so there is no problem as long as the website itself doesn't use a Javascript CSP?

ANY CSP.

**Comment by gwarser** [comment] 2020-04-15 00:08
Is this real??? https://bugzilla.mozilla.org/show_bug.cgi?id=1462989#c81

**Comment by uBlock-user** [comment] 2020-04-16 07:24
Fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1462989#c90

**Closed by uBlock-user** 2020-04-16 07:24 UTC
Labels: Firefox, external
