### ISSUE TITLE
Different behavior starting with 1.47.0 - blocking localhost connections with certain blocklist

### ISSUE THREAD

**Issue by d-Rickyy-b** [uBlockOrigin/uBlock-issues#2512] opened 2023-02-26 20:38 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Hi there, thank you for creating uBlock.

Today I noticed a weird behavior of uBlock when accessing local services running on localhost. I run Duplicati as backup solution on my system. It runs a webinterface on http://localhost:8200. Since Updating to version >=1.47.0 I could no longer access any local service accessed by the hostname `localhost`. **Yes (!)**, the issue is being caused by a custom filter list, as can be seen in the screenshot below.  **BUT** the issue does reproducably first occur on version 1.47.0 of uBlock and onwards. So I consider this a uBlock issue. The issue does NOT appear when only using the default lists!

![grafik](https://user-images.githubusercontent.com/5798157/221435322-c8ce0a70-f486-44a2-8e8a-8a93677e4367.png)

I was able to verify (by testing each version released on github) that the latest version where I do not face this issue is 1.46.0. So I assume that the issue was introduced in any of these commits: https://github.com/gorhill/uBlock/compare/1.46.0...1.47.0

___
### Workaround
Yes, a workaround could be to disable uBlock for localhost. Still I am wondering why uBlock behaves that way and if it also affects other blocklists in similar ways?

### A specific URL where the issue occurs.

http://localhost:8200

### Steps to Reproduce

1. Install uBlock version >=1.47.0
2. Install [this filter list](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts)
3. Open any local service (e.g. http://localhost:8200)

### Expected behavior

The local service opens just fine

### Actual behavior

The uBlock Alert screen pops into existence and prevents access to the site.

![grafik](https://user-images.githubusercontent.com/5798157/221435644-150783e9-f7cd-4c27-9705-95422cc12de9.png)

Even after adding an exception and **proceed**ing to the site, only html responses are coming through. All the rest is still being blocked.

### uBO version

1.47.0

### Browser name and version

Firefox 110.0 & MS Edge Version 110.0.1587.56

### Operating System and version

Windows 10

**Comment by gorhill** [comment] 2023-02-26 22:02
> a workaround could be to disable uBlock for localhost

For now you can add the following filter to _My filters_:

    localhost$badfilter

I will publish a new revision to fix this.

**Comment by gothic-bum** [comment] 2023-02-26 23:26
> I will publish a new revision to fix this.
  
Isn't `||localhost^`functioning as designed by strict-blocking the site and then only allowing the root document after clicking *Proceed*?

**Comment by iam-py-test** [comment] 2023-02-26 23:27
The issue is that many HOSTs lists (such as the one used by the OP) include:
```
127.0.0.1 localhost
```

**Comment by gothic-bum** [comment] 2023-02-26 23:43
> gorhill's fix should ensure `127.0.0.1 localhost` is ignored, but `||localhost^` should still work
  
Thanks for the clarification, that makes a bit more sense.
    
----  
  
> if for some reason someone wants to completely block localhost  
  
Note that is it included as a third-party in uBO's own "Block Outsider Intrusion into LAN" filter list:  
  
    ||localhost^$third-party,domain=~localhost|~127.0.0.1|~[::1]|~0.0.0.0|~[::]|~local

So perhaps the conversion of `127.0.0.1 localhost` could/should be similar to this, rather than ignoring it entirely.

**Comment by iam-py-test** [comment] 2023-02-26 23:53
> So perhaps the conversion of 127.0.0.1 localhost could/should be similar to this, rather than ignoring it entirely.

I disagree; that is designed to block websites from accessing localhost (i.e. to probe your device), and even then, this breaks some websites which have legitimate reasons for contacting software on your device.
I think converting this automatically could cause lots of unintended behavior; converting it like a normal HOSTs entry blocks people from visiting localhost, and blocking it 3rd party breaks from the normal HOSTs-entry parsing. It can (in my opinion) be safely assumed that the list maintainer didn't intend to block localhost at all (as that isn't what would happen in a normal HOSTs file).
I am not part of the uBo team, so my opinion doesn't really matter (I don't have a say in anything; it's up to gorhill to decide).

**Comment by gorhill** [comment] 2023-02-27 01:13
The right thing to do is to restore the previous behavior, the new one is a regression -- caused by the [templating code I added](https://github.com/gorhill/uBlock/commit/fe5fdfe5ed9289ec5cabd2aa050a64deffd09f0c) toward the end of the dev cycle.

**Comment by gorhill** [comment] 2023-03-26 19:04
Assumed fixed in 1.47.4.

**Closed by gorhill** 2023-03-26 19:04 UTC
Labels: bug
