### ISSUE TITLE
My filters stopped working on Firefox after last update 

### ISSUE THREAD

**Issue by mahmoud1973** [uBlockOrigin/uBlock-issues#1909] opened 2021-12-29 06:28 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Google.com 

### Describe the issue

I was using these filters in (my filters) to block pictures on all websites including google.com but it stopped working suddenly few days ago after the latest version
Here are the filters

```

*##[src^="data:image"],important
*||encrypted-vtbn2.gstatic.com/video$media
*https://encrypted-vtbn*.gstatic.com/video
*||*$media,important
*||*$image,important
*||video.twimg.com
*||upload.wikimedia.org^$image,important
*||*$generichide,important
www.reddit.com##.TopPosts
*##[src^="blob:"],important
youtube.com#@#[src^="blob:"],important

```

It seems that all the filters stopped working 

### Notes

I tried installing kiwi browser and ubo latest version and my filters worked fine.
Also i tried removing and re-installing ubo on Firefox , same problem  and only on Firefox 

### Configuration

<details>

```yaml
uBlock Origin: 1.40.2
Firefox Mobile: 95
filterset (summary): 
  network: 80014
  cosmetic: 21813
  scriptlet: 16421
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30732-268, never
    ublock-badware: 3633-1, never
    ublock-privacy: 181-1, never
    ublock-abuse: 81-0, never
    ublock-unbreak: 1725-0, never
    adguard-mobile: 7016-171, 1m
    easylist: 62254-24120, never
    easyprivacy: 26549-491, never
    urlhaus-1: 8168-0, never
    plowe-0: 3715-3, never
filterset (user): [array of 11 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 2810 ms
```
</details>

**Comment by gwarser** [comment] 2021-12-29 08:22
These work:

```
*##[src^="data:image"],important
||encrypted-vtbn2.gstatic.com/video$media
https://encrypted-vtbn*.gstatic.com/video
$media,important
$image,important
||video.twimg.com
||upload.wikimedia.org^$image,important
$generichide,important
www.reddit.com##.TopPosts
*##[src^="blob:"],important
youtube.com#@#[src^="blob:"],important
```

**Comment by gorhill** [comment] 2021-12-29 13:00
Provide exact steps which I can reproduce for each filter, I won't investigate vague _"filters not working on google.com"_, you need to tell me exactly which exact filters on which exact URL are not supposedly working.

**Comment by gwarser** [comment] 2021-12-29 13:31
Images should not load on `https://www.google.com/search?q=home&client=firefox-b-d&tbm=isch`

`*||*...` filters are no longer apply.

```
*||*$media,important
*||*$image,important
*||*$generichide,important
```

I cannot find such filters in filter lists. Wildcards are marked as grey in editor, maybe they should be red? Or does this filter actually apply to something?

**Comment by mahmoud1973** [comment] 2021-12-29 13:34
> These work:
> 
> ```
> *##[src^="data:image"],important
> ||encrypted-vtbn2.gstatic.com/video$media
> https://encrypted-vtbn*.gstatic.com/video
> $media,important
> $image,important
> ||video.twimg.com
> ||upload.wikimedia.org^$image,important
> $generichide,important
> www.reddit.com##.TopPosts
> *##[src^="blob:"],important
> youtube.com#@#[src^="blob:"],important
> ```
> 
> Your broken syntax probably stopped working after [gorhill/uBlock@3b7a265](https://github.com/gorhill/uBlock/commit/3b7a265ee274f82eb70e23195cbda2b510bb3476)

It's not blocking the pictures on Google search and other sites for me. Are you using latest Firefox android?

**Comment by mahmoud1973** [comment] 2021-12-29 13:40
> Images should not load on `https://www.google.com/search?q=home&client=firefox-b-d&tbm=isch`
> 
> `*||*...` filters are no longer apply.
> 
> ```
> *||*$media,important
> *||*$image,important
> *||*$generichide,important
> ```
> 
> I cannot find such filters in filter lists. ~Wildcards~ `*||*` part is marked as grey in editor, maybe they should be red? Or does this filter actually apply to something?

![Screenshot_20211229-153707](https://user-images.githubusercontent.com/18405194/147668013-f0df71ab-1628-4379-b317-44d7646e1b4a.jpg)
![Screenshot_20211229-153755](https://user-images.githubusercontent.com/18405194/147668021-ce2042da-49d4-4deb-b94a-3ba79a082541.jpg)

This is how they look like in kiwi and Firefox browsers. It's working good on kiwi and stopped working on Firefox after last update. I'm not sure how to fix this.

**Comment by mahmoud1973** [comment] 2021-12-29 13:43
> Provide exact steps which I can reproduce for each filter, I won't investigate vague _"filters not working on google.com"_, you need to tell me which exact filters on which exact URL are not supposedly working.

1- open google.com and search for dummy
2- switch to images results.
3- pictures are loading on Firefox (they should not load)
4- on kiwi browser the pictures are blocked as they shoud.

**Comment by mahmoud1973** [comment] 2021-12-29 13:47
> Images should not load on `https://www.google.com/search?q=home&client=firefox-b-d&tbm=isch`
> 
> `*||*...` filters are no longer apply.
> 
> ```
> *||*$media,important
> *||*$image,important
> *||*$generichide,important
> ```
> 
> I cannot find such filters in filter lists. ~Wildcards~ `*||*` part is marked as grey in editor, maybe they should be red? Or does this filter actually apply to something?

These filters should block all pictures on all domains. It was working fine on Firefox 4 days ago till the update. While it is still working on kiwi.

**Comment by gorhill** [comment] 2021-12-29 14:19
Ok what is happening is that for a filter such as:

    *||*$...

The end result is that the pattern ends up being:

    ||

Which means uBO tries to find `||` in the URL for a match to occur.

This is the expected behavior, and if this was not the case before, than this was a bug which was fixed by the [commit pointed out](https://github.com/gorhill/uBlock/commit/3b7a265ee274f82eb70e23195cbda2b510bb3476) by @gwarser.

For hostname anchoring to occur, `||` should always be the first thing to appear, except when the filter is an exception, in which case `@@` will be the first thing to appear. By placing a `*` before `||`, this tells uBO that the double pipe is not a hostname-anchor specifier, it tells uBO that the double pipe is part of the pattern.

**Comment by gorhill** [comment] 2021-12-29 14:28
Closing, since the filters work as expected.

@mahmoud1973, best is that you read carefully the documentation [about filter syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax) (also follow the links to external documentation) -- if you want to use hostname-anchoring, do not prepend a `*` to `||` -- nowhere in the documentation does it say you need to do this.

**Closed by gorhill** 2021-12-29 14:28 UTC
