### ISSUE TITLE
`alt`s are considered "empty placeholders"

### ISSUE THREAD

**Issue by Rudxain** [uBlockOrigin/uBlock-issues#2978] opened 2023-11-23 20:33 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

`alt` HTML attributes are hidden when "Hide placeholders of blocked elements" is `true`, even if "Cosmetic Filtering" is disabled

### A specific URL where the issue occurs.

`https://rudxain.github.io/RX-wiki/wiki/Berdly_The_Defrosted`

### Steps to Reproduce

0. Find a site with `alt`s in its tags/elements.
1. Make sure to block all elements with `alt`s before the browser caches them, otherwise the resource will be shown instead of the `alt`. We can also do a hard-reload to invalidate the cache.
2. Load the site.
3. See no `alt`s. (the default settings hide "placeholders")

### Expected behavior

The wiki/docs says that it "collapses empty space", so if an `alt` is available it should be shown

### Actual behavior

The `alt`s are hidden, perhaps completely removed from the DOM (I only tested on Fenix, not desktop)

### uBO version

1.53.0

### Browser name and version

Firefox 120.0

### Operating System and version

Android 12.0

**Comment by gorhill** [comment] 2023-11-23 20:49
All content blockers work that way, and if not this could be used by advertisers to keep their advertisements somewhat visible by simply having `alt` attribute added to their element.

Closing as wontfix, by design.

**Closed by gorhill** 2023-11-23 20:49 UTC
Labels: wontfix

**Comment by Rudxain** [comment] 2023-11-23 20:57
@gorhill Well, then I propose adding a new dynamic rule for `alt`s. This would allow users to (for example) block images and videos, but keep the `alt`s.

strawman example:
```adblock
* * image block
* * image-alt noop
```
This strawman doesn't take into account non-image alts, but I guess I made my point clear

**Comment by gorhill** [comment] 2023-11-23 21:03
You can just uncheck the option _"Hide placeholders of blocked elements"_.

**Comment by Rudxain** [comment] 2023-11-24 05:49
> You can just uncheck the option _"Hide placeholders of blocked elements"_.

So users are expected to toggle that setting **every time** they switch between some sites?

UX would be much better if we could configure which hostnames have their alts allowed (`noop`) or blocked.

I'm willing to open a PR to implement this, I just need some time to get familiar with the codebase

**Comment by Rudxain** [comment] 2024-08-12 20:58
`no-large-media` seems like a good-enough alternative to the feature, but I haven't tested if it actually preserves `alt`s.

I'm posting this in case it might help anyone

**Comment by iam-py-test** [comment] 2024-08-12 23:34
no-large-media does not hide the blocked elements, and does display the alt text.
Thank you
