### ISSUE TITLE
Element Picker does not work for certain sites

### ISSUE THREAD

**Issue by allanwind** [uBlockOrigin/uBlock-issues#889] opened 2020-02-07 23:15 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

On certain sites  the Element Picker does not work.  When you click ... | uBlock origin | Element Picker Symbol the uBlock tab is closed but the UI is not injected into the tab of interest.  It does work as expected on other sites for example google.com.

I used the remote debugger and the only log event on my phone was:

Scripts may not close windows that were not opened by script.

and it happens for both working and non-working site.  It appears to be a different issue than #81 as it does work google.com.  Also, I reproduced this with both the latest stable version and the b5 as of last night.

I cannot reproduce this issue with uBlock 1.24.4, Firefox 68.4 on Linux (desktop), i.e. it appears to specific to Mobile.  That said, reddit.com is doing a lot mobile specific stuff including aggressively pushing their app which makes the site annoying to browse on mobile.

### A specific URL where the issue occurs

https://reddit.com

### Steps to Reproduce

1. Open https://reddit.com
2. Click ... | uBlock origin | Element Picker Symbol the uBlock tab

### Expected behavior:

The uBlock tab should be closed and the tab with the reddit.com should have the element picker ui element injected.

### Actual behavior:

The ublock tab is closed but the element picker ui is not injected into the reddit.com tab.

### Your environment

* uBlock Origin version: 1.24.4, 1.24.5b3 
* Browser Name and version: Firefox Browser (Mobile) 68.4.2
* Operating System and version: Android 9

**Comment by uBlock-user** [comment] 2020-02-07 23:38
Enable cosmetic filtering ?

**Comment by Yuki2718** [comment] 2020-02-08 00:17
I know it is only for confirmed issue so hasn't reported but I experienced the same problem a few times. I doubt it has sth to do w/ reddit, it rather seemed to be a problem of some tab(s) open at the time. Restart the browser, reload the tabs, close and open uBO dashboard etc. eventually fixed it, please test @allanwind. I still don't figure out conditions to reproduce.

**Comment by Yuki2718** [comment] 2020-02-08 00:19
> 
> 
> Enable cosmetic filtering ?
> 
> Did you click on the element after clicking on the picker icon ?

In my case, cosmetic is ofc enabled and if I click sth just a usual event (e.g. if it was a link, go to the site) occurred.

**Comment by allanwind** [comment] 2020-02-08 00:24
The global "Disable cosmetic filtering" was not set, however, the 
per site cosmetic filter was disabled.  Sorry, this is 
embarrassing. I have used uBlock Origin for a very long time,
and must have disabled that per site setting by accident.

Maybe the flash and element picker icons shouldn't be clickable if 
the cosmetic filtering is not enabled?  Those two icons have a 
dependency on the feature but visually you cannot tell that is
the case.


/Allan
-- 
Allan Wind
Yaxto - Runs Your Business
<https://yaxto.com>

**Comment by Yuki2718** [comment] 2020-02-08 00:35
Then this issue should be closed, as I so far have no idea to reproduce what I said.

**Comment by uBlock-user** [comment] 2020-02-08 05:55
Duplicate of https://github.com/gorhill/uBlock/issues/3212

**Closed by uBlock-user** 2020-02-08 05:55 UTC
Labels: unable to reproduce

**Comment by gorhill** [comment] 2020-02-08 11:15
> Maybe the flash and element picker icons shouldn't be clickable if
the cosmetic filtering is not enabled?

The zapper must still be usable without cosmetic filtering, so the solution is to make the zapper independent from the picker code. As for the picker, someone may still want to create network-based filters, so in that case the solution is to ensure the picker can still function without the DOM filterer code present.
