### ISSUE TITLE
HTML Filters are not applied upon 301 moved permanently

### ISSUE THREAD

**Issue by 2000me** [uBlockOrigin/uBlock-issues#942] opened 2020-03-10 22:05 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Serch terms: 301, moved permanently
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Upon redirect (301 Moved Permanently) HTML filters are not applied.

### A specific URL where the issue occurs
`
https://taz.de/!5670441/`

### Steps to Reproduce

1. Check I am an advanced user (required reading)
2. Add rules and filters

```
* * 3p block
taz.de * 1p-script block
taz.de * inline-script block
```

```
taz.de##^.community.full
taz.de##^.rack.article
taz.de##^.sect_description
taz.de##^.shariff
taz.de##^.tail
taz.de##^#footer
taz.de##^#reward:xpath(../..)
```

3. Visit `https://taz.de/!5670441/`.
4. Observe the 301 to `https://taz.de/Buergermeister-Wahl-in-Stuttgart/!5670441/`.
5. Observe that the above rules are applied.
6. Observe that the above filters are not applied.
7. Visit `https://taz.de/Buergermeister-Wahl-in-Stuttgart/!5670441/`.
8. Observe that the rules are applied.
9. Observe that the filters are applied.

### Expected behavior

Filters are applied for the redirected URL.

### Actual behavior

Only rules are applied. Filters are not applied.

### Environment

* uBlock Origin version: 1.25.2
* Browser Name and version: Firefox 74.0
* Operating System and version: macOS Catalina 10.15.3

**Comment by gorhill** [comment] 2020-03-16 15:29
The `StreamObject` created by uBO fires a `Channel redirected` error, and as a result uBO is unable to act on the stream data. I have researched <https://bugzilla.mozilla.org/> and so far I found nothing related to this issue -- I can't tell whether this is a per-design Firefox behavior or an issue to be fixed in Firefox.

**Comment by krystian3w** [comment] 2020-03-20 09:10
Other link to test:

`https://bit.ly/2Wqw7Ol`

```ruby
>>> https://bit.ly/2Wqw7Ol

> --------------------------------------------
> 301 Moved Permanently
> --------------------------------------------
Status:	301 Moved Permanently
Code:	301
Server:	nginx
Date:	Fri, 20 Mar 2020 09:08:35 GMT
Content-Type:	text/html; charset=utf-8
Content-Length:	154
Cache-Control:	private, max-age=90
Content-Security-Policy:	referrer always;
Location:	https://gorhill.github.io/uBlock/tests/procedural-html-filters.html
Referrer-Policy:	unsafe-url
```

**Comment by krystian3w** [comment] 2020-03-20 09:20
@gwarser  maybe need change title, redirect 302 (temporarily moved) also is affected.

**Comment by gwarser** [comment] 2020-03-20 13:30
In @krystian3w example this can be https://bugzilla.mozilla.org/show_bug.cgi?id=1530408 "filterResponseData from the WebRequest API returns unexpected data" (for cached and compressed responses).

**Comment by gwarser** [comment] 2020-03-20 13:44
ESR is working fine. I will try bisecting.

**Comment by mixedpuppy** [comment] 2020-03-23 20:02
> The `StreamObject` created by uBO fires a `Channel redirected` error, and as a result uBO is unable to act on the stream data. I have researched https://bugzilla.mozilla.org/ and so far I found nothing related to this issue -- I can't tell whether this is a per-design Firefox behavior or an issue to be fixed in Firefox.

This is intended behavior and was implemented in [Bug 1444539](https://bugzilla.mozilla.org/show_bug.cgi?id=1444539).  When a redirect error occurs like this the request should restart, onBeforeRequest should receive another call and you should start a new filter.

A side note on the above, there are several potential issues, potentially related to [Bug 1590898](https://bugzilla.mozilla.org/show_bug.cgi?id=1590898) with this right now that I'm digging into.

**Comment by gwarser** [comment] 2020-03-23 20:24
@mixedpuppy I bisected this in https://bugzilla.mozilla.org/show_bug.cgi?id=1623921 to be caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1590898

**Comment by gorhill** [comment] 2020-03-23 20:45
> onBeforeRequest should receive another call and you should start a new filter.

The filter is started at onHeadersReceived() time, and only for 20x response status (i.e. after the redirect occurred), and the filter created at that time is the one failing with the "Channel redirected" error.

**Comment by mixedpuppy** [comment] 2020-03-23 21:57
> > onBeforeRequest should receive another call and you should start a new filter.
> 
> The filter is started at onHeadersReceived() time, and only for 20x response status (i.e. after the redirect occurred), and the filter created at that time is the one failing with the "Channel redirected" error.

Well, the only reason that error is emitted is due to a start request occurring where the channel is not the same as when the filter was created.  The current code actually checks the redirect chain for the load in that case as well.

Any chance you can reproduce with a minimal extension?

**Comment by gorhill** [comment] 2020-03-24 15:33
@mixedpuppy 

Here is a zip archive of a minimal extension which reproduces the issue:

[uBO-issue-942.zip](https://github.com/uBlockOrigin/uBlock-issues/files/4376163/uBO-issue-942.zip)

To be loaded via _"Load Temporary Add-on..."_.

**Comment by mixedpuppy** [comment] 2020-03-24 22:44
Ok, I've figured out the cause, it is outlined in bugzilla.

**Closed** 2020-04-09 17:34 UTC
Labels: Firefox, bug, external, fixed

**Comment by uBlock-user** [comment] 2020-04-09 18:08
fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1597159#c16

**Comment by 2000me** [comment] 2020-04-09 20:48
verified using Firefox Nightly 77.0a1 (2020-04-09)

**Comment by krystian3w** [comment] 2023-11-05 20:40
https://github.com/uBlockOrigin/uBlock-issues/issues/2931 someone can check bugzilla?
