### ISSUE TITLE
Ubo logger issue on firefox Android 63.0.2

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uBlock-issues#342] opened 2018-12-15 17:56 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Don't know how to describe this but I recorded in video
https://streamable.com/83zmt

...reported here

https://www.reddit.com/r/uBlockOrigin/comments/a6fy57/logger_issue_on_firefox_android_6303/
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

Logger should repor all activities of all tabs when I select `all` in logger

### Actual behavior:

Logger just reverse back to another tab(1st tab window)/inactive window when I select to filter all tabs
***This behavior doesn't happen on firefox desktop browser***

### Your environment

* uBlock Origin version: 1.17.4
* Browser Name and version: Firefox Android 63.0.2 stable
* Operating System and version: Android 7

**Comment by uBlock-user** [comment] 2018-12-15 18:35
You didn't post any Steps to Reproduce, add that too.

**Comment by gorhill** [comment] 2018-12-15 18:37
Well he posted a video that show the issue pretty well.

I can't reproduce on my side however.

**Comment by ghajini** [comment] 2018-12-15 18:49
it happens on firefox Android 63.0.2 which is stable ver as of now

**Comment by gorhill** [comment] 2018-12-15 21:03
I am giving this another look, maybe I did not understand properly the first time. The issue is that the tab selector is not working fine?

**Comment by Grossdm** [comment] 2018-12-16 06:52
@ghajini, you had at least one other addon installed and enabled - there was a menu item for it.

___

You had this in your own OP:

    I tried to reproduce the issue when...
        uBlock Origin is the only extension

___

My guess is that @gorhill and @uBlock-user probably won't want to spend time on this if you won't disable your other addons.

**Comment by uBlock-user** [comment] 2018-12-16 06:57
gorhill will look into this as he said in the previous comment, I can't as I don't use Firefox on Android.

**Comment by gorhill** [comment] 2018-12-16 09:49
So it's a tab selector issue, that I can reproduce.

**Comment by gwarser** [comment] 2018-12-16 22:57
First part of video is probably this https://github.com/uBlockOrigin/uBlock-issues/issues/56 This was also affecting desktop and is fixed in 64.

Second part is "famous first tab" on Android. Softonic was opened  (I assume) in first tab after Firefox start, and this tab is always broken. Here wee see Softonic does not have "title" in logger dropdown, but only URL, and switching to "All" switches back to Softonic. I can reproduce this in Fx beta. It's "magically" fixed after first tab is closed (can be reopened in new tab and all will work fine after that).

**Comment by ghajini** [comment] 2020-02-22 11:37
Iam experiencing some lags on firefox android, here is profiling result....

https://perfht.ml/2ujBZgv

**Comment by gorhill** [comment] 2020-02-22 12:39
There is nothing about uBO in that profiling result.

**Comment by gorhill** [comment] 2020-07-23 13:24
Closing: probably no longer an issue.

**Closed by gorhill** 2020-07-23 13:24 UTC
Labels: Firefox-Android, bug
