### ISSUE TITLE
Please Stop Declining #2801

### ISSUE THREAD

**Issue by esotericDisciple** [uBlockOrigin/uBlock-issues#671] opened 2019-07-15 21:40 UTC
It's ableist of you to not have a means of selecting multiple elements at once for adding to the blocklist...

### Prerequisites

- [. ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [. ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [. ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [. ] uBlock Origin is the only extension
    - [. ] uBlock Origin with default lists/settings
    - [. ] using a new, unmodified browser profile
- [. ] I am running the latest version of uBlock Origin
- [. ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:up-to-date
* Browser Name and version:waterfox 56.
* Operating System and version:Manjaro-KDE-64bit

**Comment by uBlock-user** [comment] 2019-07-15 22:00
Duplicate of https://github.com/gorhill/uBlock/issues/2801

**Closed by uBlock-user** 2019-07-15 22:00 UTC

**Comment by gwarser** [comment] 2019-07-19 23:41
Keyboard shortcut can be set in current Firefox and Chrome.
