### ISSUE TITLE
WebRTC IP Leak

### ISSUE THREAD

**Issue by thankuverymuch** [uBlockOrigin/uBlock-issues#1297] opened 2020-10-16 05:07 UTC
ublock WebRTC option does not work
There seems to be a conflict with opera own WebRTC option
Real IP leak when ublock webrtc option is set in opera vpn

I confirmed that it does not work in firefox and chrome
webrtc test was done at doileak.com

**Comment by uBlock-user** [comment] 2020-10-16 07:27
> Real IP leak when ublock webrtc option is set in opera vpn

only local IP is hidden, not your public IP, anyways fill the template and do not bypass it.

**Comment by thankuverymuch** [comment] 2020-10-16 07:37
The answer sounds like garbage
Have you tested it?
It's a useless option in the latest Firefox, Chrome, and Opera.
It messes up the settings of Opera

**Comment by uBlock-user** [comment] 2020-10-16 07:44
>  It messes up the settings of Opera
The Opera's WebRTC option is undoing uBO's settings and uBO will only hide your local/LAN IP address, your public IP address will always be seen- https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

**Comment by gorhill** [comment] 2020-10-16 09:41
Fill the template properly if you have evidence it does not work.

> Real IP leak

The option is:

> Prevent WebRTC from leaking **LOCAL** IP addresses

There is a link aside the option to the [documentation](https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address):

> Keep in mind that this feature is to prevent leakage of your non-internet-facing IP adresses. The purpose of this feature is not to hide your current internet-facing IP address -- so be cautious to not misinterpret the results of some WebRTC-local-IP-address-leakage tests found online.

Also:

> Chromium-based browsers
> ...
> If you are using an extension-based VPN, this setting won't [prevent your ISP IP address from leaking](https://code.google.com/p/chromium/issues/detail?id=457492#c44).

**Comment by thankuverymuch** [comment] 2020-10-16 10:43
You are telling a useless story now.
When ublock webrtc setting is checked and tested, my real IP is displayed.
To make the setting of the opera jammed.
Turning off ublock option hides IP due to opera's webrtc settings

**Comment by gorhill** [comment] 2020-10-16 10:55
Please provide repro steps as asked in the template, I don't know anything about "opera vpn". Respect the template before lecturing us on how we deal with issues.

**Comment by thankuverymuch** [comment] 2020-10-20 17:11
I'm just talking about a bug that ublock's webrtc option forces off opera's webrtc option.

**Comment by gwarser** [comment] 2020-10-20 20:24
By default Opera 71.0.3770.148 has WebRTC option set to "Use any suitable network interface (recommended)"  

Installing uBO changes nothing.

Switching uBO option "Prevent WebRTC from leaking local IP addresses" makes it "Use default public network interfaces only" and disables this widget in settings:

![image](https://user-images.githubusercontent.com/886325/96639360-e878a000-1321-11eb-8434-20ed70c4c47e.png)

Disabling uBO option "Prevent WebRTC from leaking local IP addresses" makes it work again and restores previous selection.

For everything above `doileak.com` reports that my public IP is visible (I don't have any private IP)  
"Your browser supports WebRTC! Your real IP address is visible to every website you visit."  

Choosing Opera option "Disable non-proxied UDP" makes Doileak report: "WebRTC IP Leak: We could not detect an IP via WebRTC."

All works as expected. What is the issue?

**Comment by uBlock-user** [comment] 2020-10-20 21:00
> What is the issue?

I believe the user prefers Opera's behaviour instead of uBO's, so in that case, the solution is to disable uBO's setting and let Opera control the behaviour.

**Comment by thankuverymuch** [comment] 2020-10-20 21:13
> All works as expected. What is the issue?

If ubo's webrtc ip address leak prevention option is checked, my real ip is leaked even if vpn is used. If the option is turned off, the IP is hidden due to Opera's webrtc option. Why does this option exist? If you think this isn't the problem, it looks like there's a problem with your head.

**Comment by uBlock-user** [comment] 2020-10-20 21:16
> Why does this option exist?

To prevent the leakage of local/LAN IP address, if you like Opera's behaviour of hiding both, just use that.

**Comment by gorhill** [comment] 2020-10-20 21:59
I had no idea Opera had such a setting, hence why I asked for repro steps.

**Comment by gorhill** [comment] 2020-10-20 22:03
I aapreciate there is an issue but I am unhappy with @thankuverymuch's resistance to properly fill rhe template and provide detailed repro steps. We will take it from here.

**Comment by gorhill** [comment] 2020-10-20 22:05
All the typos is because I am on phone and efiting does not work well on Fenix.

**Comment by gwarser** [comment] 2020-10-20 22:41
With Opera VPN enabled, when using "Use default public network interfaces only" preference IP is leaking always. Does not matter if it's set manually or by uBO.

**Comment by gwarser** [comment] 2020-10-20 22:45
Wow, this was unexpected, looks like my LTE modem is working as local network. With "Use default public and private network interfaces only" Doileak reports: "Your local IP: 192.168.8.101
. Your public IP:XXXX"

**Comment by uBlock-user** [comment] 2020-10-21 09:25
Now occuring with Vivaldi - https://www.reddit.com/r/uBlockOrigin/comments/jf9lj1/activating_prevent_webrtc_from_leaking_local_ip/

**Comment by uBlock-user** [comment] 2021-03-19 05:07
essentially duplicate of https://github.com/gorhill/uBlock/issues/2853 ?

**Comment by gwarser** [comment] 2021-09-14 16:11
Option removed https://github.com/uBlockOrigin/uBlock-issues/issues/1723

**Closed by gwarser** 2021-09-14 16:11 UTC
Labels: enhancement
