### ISSUE TITLE
uBlock triggering issues

### ISSUE THREAD

**Issue by TimonTheMicro** [uBlockOrigin/uBlock-issues#268] opened 2018-10-14 10:25 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBlock doesn't always trigger if the browser run first time since hardware reboot.
### A specific URL where the issue occurs

https://www.google.pl/webhp?complete=0

*Using filter:
(autogenerated by pick tool)
! 14.10.2018, 00:37:40 https://www.google.pl/webhp?complete=0
||www.google.pl/logos/doodles/2018/teachers-day-2018-poland-4618434682814464-law.gif$image

### Steps to Reproduce

1. Just open the browser

### Expected behavior:

I would expect that uBlock Origin would work even when a browser runs first time since hardware reboot.

### Actual behavior:

like in the previous versions, ublock won't trigger sometimes, for example when browser does a cold start.
Sometimes it won't work also on certain web pages which runs first time so only refreshing helps to make
uBlock trigger and work properly.
I know the bug since few years but I decided to post the issue because I thought someone already noticed it.

*Installed addons:
Cookie PopUp blocker
Default Bookmark Folder
Disable JavaScript
ImageBlock
Show/Hide passwords
uBlock Origin
Video Blocker
View background image
View image
Youtube VIdeo and Audio Downloader (Dev Edt.)

### Your environment

* uBlock Origin version: newest
* Browser Name and version: Firefox Quantum 62.0.3
* Operating System and version: Windows 8.1

**Comment by kowith337** [comment] 2018-10-14 11:33
Have you check?
- I am an advanced user ([required reading](https://github.com/gorhill/uBlock/wiki/Advanced-user-features)) checkbox
- Set `suspendTabsUntilReady` to `true`

**Comment by uBlock-user** [comment] 2018-10-14 11:44
Duplicate of https://github.com/gorhill/uBlock/issues/1327

**Closed by uBlock-user** 2018-10-14 11:44 UTC
