### ISSUE TITLE
Single asterisk in my filters is not working anymore

### ISSUE THREAD

**Issue by pkraskov** [uBlockOrigin/uBlock-issues#1094] opened 2020-06-03 20:33 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I don't use any filters except the only one asterisk "*" on My filters tab to archive the effect of blocking any site except manually whitelisted. After update to latest version I found that this functionality does not work anymore.
I did small research and found that the last version where it still works is 1.20.2. 

### A specific URL where the issue occurs

http://wikipedia.org/

### Steps to Reproduce

1. uncheck all filters except My filters
2. put the only one character "*" in My filters tab
3. make sure you don't have whitelisted sites
4. try to open any site

### Expected behavior:

Site should be blocked. 

### Actual behavior:

Site is not blocked.

### Your environment

* uBlock Origin version: checked with 1.27.10, 1.21.0, 1.20.2 (works)
* Browser Name and version: Firefox 68.8.0esr 64-bit linux
* Operating System and version: Debian 9

**Comment by uBlock-user** [comment] 2020-06-03 20:42
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/687

**Closed by uBlock-user** 2020-06-03 20:42 UTC
