### ISSUE TITLE
No Large Media setting with 0KB should block all images

### ISSUE THREAD

**Issue by brianvanburken** [uBlockOrigin/uBlock-issues#543] opened 2019-04-24 06:33 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When I set the "No Large Media" setting to 0KB almost all the images are blocked. Except when the image does not have a content-length header. This is known behaviour as described in https://github.com/uBlockOrigin/uBlock-issues/issues/188. But, when someone, like me, inputs 0KB then we want to block all images. Even those without a content-length header. Because an image is always bigger than 0KB. uBlock Origin block even these images.

### A specific URL where the issue occurs

Any site that has images that return no content-length header. I came across an image on this site: https://hexdocs.pm/pow/Pow.html. 

### Steps to Reproduce

1. Set "No Large Media" to 0KB
2. Visit a site with images that return no content-length headers. Like: https://hexdocs.pm/pow/Pow.html
3. Set images not blocked

### Expected behavior:

All images blocked with a setting of 0KB

### Actual behavior:

Images without content-length headers are not blocked

### Your environment

* uBlock Origin version: 1.18.16
* Browser Name and version: Google Chrome, version 74.0.3729.108 (Official Build) (64-bit)
* Operating System and version: macOS Mojave, version 10.14.4

**Comment by uBlock-user** [comment] 2019-04-24 06:41
Duplicate of https://github.com/gorhill/uBlock/issues/1473

**Comment by gorhill** [comment] 2019-04-24 11:06
The request is different here. The other request was asking to block at onBeforeRequest time, while here it just ask that images with no `Content-Length` header should be assumed too large if the threshold size is 0. Sounds reasonable to me.

**Closed** 2019-04-24 17:12 UTC
Labels: enhancement, fixed

**Comment by user0022** [comment] 2024-12-06 22:56
Hello!
I wanted to ask about the same thing, but checking to avoid duplicates showed the question had already been asked, and a good solution provided!

Yet I must assume it doesn't work anymore, as I come accross the same problem today (me or any user I guess).
A small example here: https://searx.bndkt.io/search?q=ara%20parrot&language=en&time_range=&safesearch=0&categories=general
And I can see when watching network activity that going to the Images tab loads much more data.

So probably it can be fixed to work again?
Thank you.

**Comment by gorhill** [comment] 2024-12-06 23:24
Fixed earlier today, now in latest dev build: https://github.com/gorhill/uBlock/releases

**Comment by user0022** [comment] 2024-12-07 01:27
Thank you!
