### ISSUE TITLE
[UI] miss clicking reload messes up logic

### ISSUE THREAD

**Issue by mrx23dot** [uBlockOrigin/uBlock-issues#2966] opened 2023-11-19 00:07 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Addon's refresh button can get out of sync with internal state, read on:

### A specific URL where the issue occurs.

https://www.torproject.org/download/languages/

### Steps to Reproduce

Change any of:
![2023-11-19_000213_0M](https://github.com/uBlockOrigin/uBlock-issues/assets/4163396/93c1291c-ce28-4c59-8d2b-16a6d783c32d)

instead of addon's refresh button miss click to close addon window (click outside)

Now addon closes,
when I open the addon again the refresh button is not there anymore.
(it thinks I already clicked it)

I have to go all the way to other side of the screen to refresh the page.

### Expected behavior

refresh button should be still there the 2nd time I open it,
or why hide it at all.

### Actual behavior

Refresh button only shows up first time when I change an option.

### uBO version

1.53.0

### Browser name and version

Firefox 104

### Operating System and version

win10

**Comment by gorhill** [comment] 2023-11-19 00:29
> refresh button should be still there the 2nd time I open it,

By design, the refresh button is temporary, it disappears if you click it or close the popup panel:

It's not a given reload is wanted after changing a rule, so having it there with no way to get rid of it would be annoying.

There is no 100%-proof way to detect page full load, which can lead to sticky reload button in the popup panel.

You can always reload the page using the browser's own reload button.

Closing as `wonfix`.

**Closed by gorhill** 2023-11-19 00:29 UTC

**Comment by gorhill** [comment] 2023-11-19 15:27
> until it's clicked

Then people will open an issue about the reload icon in the popup panel not being removed after they forced a reload through the browser's own reload button.

I said, I prefer to not change the current behavior.

**Comment by gwarser** [comment] 2023-11-22 21:31
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/2464
