### ISSUE TITLE
Regarding logger change

### ISSUE THREAD

**Issue by Kusresa** [uBlockOrigin/uBlock-issues#343] opened 2018-12-16 04:24 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

@gorhill 
I tried to post this in the commit comments of https://github.com/gorhill/uBlock/commit/8214a0b17dd0a9fc8645230ee3a99155c37fac71 but it seems it is restricted to only some people.
About the inline script row, does that mean it's not possible to create static inline-script static filters using the logger anymore? Was useful dealing with some annoyances/ads quickly to create filters straight from the logger. 

Is there some way to only show the inline-script row when inline scripts are detected on the page instead of only when there is an inline-script block filter?

**Comment by uBlock-user** [comment] 2018-12-16 06:01
> About the inline script row, does that mean it's not possible to create static inline-script static filters using the logger anymore?

Yes. The inline-script row will only appear if you created a static filter using `$inline-script`.

**Comment by gorhill** [comment] 2018-12-16 12:30
As with uMatrix, I could have a content script find out whether the page (or one of its embedded frames) contains inline script tags or equivalent (i.e. `onload=`-like attributes) and report this to the logger.

**Comment by gwarser** [comment] 2018-12-22 09:44
>What browser?

"Both", checked in Firefox Nightly and Chromium stable.

**Comment by gwarser** [comment] 2019-05-07 19:59
https://old.reddit.com/r/uBlockOrigin/comments/blumm0/inline_script_doesnt_get_blocked/

**Comment by uBlock-user** [comment] 2019-05-07 20:22
Can't reproduce it


![](https://i.gyazo.com/1dd4cd021bba83e92d88298c9836c010.png)

**Comment by gorhill** [comment] 2019-05-07 20:40
I have a fix for that locally as part of <https://github.com/uBlockOrigin/uBlock-issues/issues/552>. I am waiting to final release of 1.18.18 for committing all this. The fix however is to go back to how it was: `inline-script` will be shown only if they are blocked, there is no other simply way to keep the logger consistent. If one wants to find out whether there are inline scripts in a page, it will require to disable inline-scripts one with either the `no-scripting` switch or the `inline-script` rule.

**Comment by gwarser** [comment] 2019-05-16 20:45
"Won't fixed" by https://github.com/gorhill/uBlock/commit/915c1f1f3c78597e00b1860b4ff6b20aa081f0f1 ?

**Comment by gorhill** [comment] 2019-05-16 22:16
Yes, wontfix, not worth the complication.

**Closed** 2019-05-16 22:24 UTC
Labels: wontfix

**Comment by uBlock-user** [comment] 2019-05-16 23:10
The behaviour is back to being the one I mentioned in https://github.com/uBlockOrigin/uBlock-issues/issues/343#issuecomment-447619978
