### ISSUE TITLE
Keyboard shortcut to toggle Javascript on Firefox

### ISSUE THREAD

**Issue by ctison** [uBlockOrigin/uBlock-issues#1447] opened 2021-01-12 23:06 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

It would be nice to toggle Javascript from a keyboard shortcut on Firefox.

![image](https://user-images.githubusercontent.com/17789536/104384692-2ad10800-5532-11eb-86a4-8daff95bf964.png)

---

![image](https://user-images.githubusercontent.com/17789536/104384751-489e6d00-5532-11eb-9721-bad37cd1489e.png)
> Manage Extension Shortcuts menu on Firefox 84

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Firefox 84
* Operating System and version: MacOS 11

**Comment by gorhill** [comment] 2021-01-13 02:48
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/692>.

**Closed by gorhill** 2021-01-13 02:48 UTC
