### ISSUE TITLE
Protect RegExp.prototype.test method in scriptlets.js

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uBlock-issues#1741] opened 2021-09-27 13:04 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

ygosu.com patches RegExp.prototype.test, which prevents aost.js from functioning

![RegExp test](https://user-images.githubusercontent.com/53560467/134920722-2e3ecdff-6ad0-4140-9e00-abf5bc4c280a.jpg)

Please protect the test method.
```
[uBlock/assets/resources/scriptlets.js]
238  238     }
     239     const _test = RegExp.prototype.test;        // Add
239  240     const reNeedle = new RegExp(needle);
274  275     const stack = lines.join('\t');
275          const r = reNeedle.test(stack);             // Remove
     276     const r = _test.call(reNeedle, stack);      // Add
276  277     if (

```
### A specific URL where the issue occurs

`https://ygosu.com/`

### Steps to Reproduce

If you run the following commands in devtool, you will see that the test method has been patched.
```
RegExp.prototype.test.toString()
/th:\d+\s+[a-zA-Z]\d\/<@/.test("th:123 A9/<@ must be true")
```

### Expected behavior

n/a

### Actual behavior

n/a

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Firefox 94.0a1 (2021-09-26)

### Operating System and version

n/a

**Comment by avotoko** [comment] 2021-09-28 22:14
I think it's possible to change aost.js to handle 'HTMLImageElement.prototype.src'

![diff](https://user-images.githubusercontent.com/53560467/135172901-fce86986-9356-418a-a5a2-9b5543306373.jpg)
.
```
    const makeProxy = function(owner, chain) {
        const pos = chain.indexOf('.');
        if ( pos === -1 ) {
            let v, des;
            try {
                v = owner[chain];
            }
            catch(e){
                des = Object.getOwnPropertyDescriptor(owner, chain);
                if (! des){ return; }
            }
            Object.defineProperty(owner, chain, {
                get: function() {
                    if ( mustAbort(new ErrorCtor(magic)) ) {
                        throw new ReferenceError(magic);
                    }
                    return ! des ? v : des.get ? des.get.call(this) : des.hasOwnProperty("value") ? des.value : void 0;
                },
                set: function(a) {
                    if ( mustAbort(new ErrorCtor(magic)) ) {
                        throw new ReferenceError(magic);
                    }
                    ! des ? (v = a) : des.set ? des.set.call(this, a) : des.hasOwnProperty("value") ? (des.value = a) : void 0;
                },
            });
            return;
        }

```

**Comment by avotoko** [comment] 2021-09-29 04:24
If we are going to fix the test method to be protected, we need to consider whether we should also protect other functions and methods that are called after the site script is executed.

**Comment by avotoko** [comment] 2021-09-29 13:57
I'm closing this issue for now.
Assuming that `aost` will be used on `ygosu.com`, there are more issues that need to be overcome.
For example, when `XMLHttpRequest.prototype.send` is intercepted by `aost`, the descriptor retrieved by `getOwnPropertyDescriptor` looks different. It is quite possible that they will detect this difference and stop loading the content images.
For the time being, I will personally pursue ways to overcome these issues.

**Comment by uBlock-user** [comment] 2021-09-29 14:20
Keeping it open until gorhill addresses it.

**Comment by avotoko** [comment] 2021-10-04 11:20
yet-another-abort-on-stack-trace.js

-  It works on properties that exist at runtime.
-  The target property must have a function-valued `value` or getter/setter.
-  It is not affected by patches from site-side scripts.
-  If you detect the execution of this script, please let me know how to do it.


```
/// yet-another-abort-on-stack-trace.js
/// alias yaaost.js
// Very experimental
(function() {
    let chain = '{{1}}';
    let needle = '{{2}}';
    let logLevel = '{{3}}';
    let opts = '{{4}}';
    chain = 'btoa', needle = '/debugger|injectedScript/', logLevel = '1', opts = 'debug:1';
    const reRegexEscape = /[.*+?^${}()|[\]\\]/g;
    if ( needle === '' || needle === '{{2}}' ) {
        needle = '^';
    } else if ( /^\/.+\/$/.test(needle) ) {
        needle = needle.slice(1,-1);
    } else {
        needle = needle.replace(reRegexEscape, '\\$&');
    }
    for (let a = opts.split(" "), i = (opts = {}, 0) ; i < a.length ; i++){
        let kv = a[i], idx = kv.indexOf(':'), k = kv.substring(0, idx), v = kv.substring(idx + 1);
        if (! k){ continue; }
        if (k === "protectionDepth" || k === "stackDepth"){
            Number.isInteger(v = v * 1) && (opts[k] =  v);
        }
        else {
            opts[k] =  v;
        }
    }
    const reNeedle = new RegExp(needle);
    const magic = String.fromCharCode(Math.random() * 26 + 97) +
        Math.floor(
            (0.25 + Math.random() * 0.75) * Number.MAX_SAFE_INTEGER
        ).toString(36).slice(-8);
    const log = console.log.bind(console);
    const ErrorCtor = self.Error;
    const stackDesc = Object.getOwnPropertyDescriptor(Error.prototype, "stack"),
            _stackTraceLimit = Error.stackTraceLimit,
            _prepareStackTrace = Error.prepareStackTrace,
            _exec = RegExp.prototype.exec,
            _test = RegExp.prototype.test,
            _includes = String.prototype.includes,
            _indexOf = String.prototype.indexOf,
            _replace = String.prototype.replace,
            _slice = String.prototype.slice,
            _split = String.prototype.split,
            _startsWith = String.prototype.startsWith,
            _trim = String.prototype.trim,
            _forEach = Array.prototype.forEach;
            _join = Array.prototype.join,
            _push = Array.prototype.push,
            _defineProperty = Object.defineProperty,
            _getOwnPropertyDescriptor = Object.getOwnPropertyDescriptor,
            _getOwnPropertyNames = Object.getOwnPropertyNames,
            _bind = Function.prototype.bind,
            _toString = Function.prototype.toString,
            _toLocaleString = Function.prototype.toLocaleString,
            _Reflect_apply = Reflect.apply,
            _Reflect_construct = Reflect.construct;
            _dummy = void 0;
    const mustAbort = (function(){
        return function(err) {
            let docURL = self.location.href;
            const pos = _indexOf.call(docURL, '#');
            if ( pos !== -1 ) {
                docURL = _slice.call(docURL, 0, pos);
            }
            // Normalize stack trace
            const lines = [];
            const _stack = stackDesc ? stackDesc.get.call(err) : err.stack;
            for ( let line of _split.call(_stack, /[\n\r]+/) ) {
                if ( _includes.call(line, magic) ) { continue; }
                line = _trim.call(line);
                let match = _exec.call(/(.*?@)?(\S+)(:\d+):\d+\)?$/, line);
                if ( match === null ) { continue; }
                let url = match[2];
                if ( _startsWith.call(url, '(') ) { url = _slice.call(url, 1); }
                if ( url === docURL ) {
                    url = 'inlineScript';
                } else if ( _startsWith.call(url, '<anonymous>') ) {
                    url = 'injectedScript';
                }
                let fn = match[1] !== undefined
                    ? _slice.call(match[1], 0, -1)
                    : _trim.call(_slice.call(line, 0, match.index));
                if ( _startsWith.call(fn, 'at') ) { fn = _trim.call(_slice.call(fn, 2)); }
                let rowcol = match[3];
                lines.push(' ' + _trim.call(`${fn} ${url}${rowcol}:1`));
            }
            lines[0] = `stackDepth:${lines.length-1}`;
            const stack = _join.call(lines, '\t');
            const r = _test.call(reNeedle, stack);
            if (
                logLevel === '1' ||
                logLevel === '2' && r ||
                logLevel === '3' && !r
            ) {
                log(_replace.call(stack, /\t/g, '\n'));
            }
            return r;
        };
    })();
    const patchedFunc = {};
    const patch = (function(){
        return function patch(obj, prop, callback, opts){
            opts = opts || {};
            const log = console.log;
            const org = _getOwnPropertyDescriptor(obj, prop), copy = {};
            if (! org){ log("[yaaost] error: no own property", prop, "in", obj); return; }
            log("[yaaost] property descriptor of", prop + ":", org);
            let patched;
            for (let k in org){
                copy[k] = org[k];
                if (typeof org[k] === "function"){
                    log("[yaaost] patching descriptor." + k);
                    patched = true;
                    copy[k] = (function(){
                        let temp = {
                            [org[k].name]: function(){
                                const _stl = ErrorCtor.stackTraceLimit, _pst = ErrorCtor.prepareStackTrace;
                                ErrorCtor.stackTraceLimit = "stackDepth" in opts ? opts.stackDepth : _stackTraceLimit,
                                ErrorCtor.prepareStackTrace = _prepareStackTrace;
                                const err = new ErrorCtor(magic);
                                ErrorCtor.stackTraceLimit = _stl, ErrorCtor.prepareStackTrace = _pst;
                                return callback(org[k], this, arguments, new.target, err, new ReferenceError(magic));
                            },
                        };
                        _forEach.call(_getOwnPropertyNames(org[k]), prop=>{
                            temp[org[k].name][prop] = org[k][prop];
                        });
                        temp[org[k].name].toString = _bind.call(org[k].toString, org[k]);
                        temp[org[k].name].toLocaleString = _bind.call(org[k].toLocaleString, org[k]);
                        _defineProperty(temp[org[k].name].toLocaleString, "name", { value: "toLocaleString" });
                        temp[org[k].name].toLocaleString.toString = _bind.call(Function.prototype.toString, org[k].toLocaleString);
                        const depth = "protectionDepth" in opts ? opts.protectionDepth : 2;
                        log("[yaaost] protection depth:", depth);
                        for (let obj = temp[org[k].name].toString, 
                            obj2 = temp[org[k].name].toLocaleString.toString, 
                            toString = _bind.call(_toString, _toString),
                            i = 0 ; i < depth ; obj = obj.toString, obj2 = obj2.toString, i++){
                            _defineProperty(obj, "name", { value: "toString" });
                            obj.toString = toString;
                            _defineProperty(obj2, "name", { value: "toString" });
                            obj2.toString = toString;
                        }
                        return temp[org[k].name];
                    })();
                    patchedFunc[copy[k]] = org[k];
                }
            }
            if (! patched){
                log("[yaaost] error: descriptor has no get/set/value");
                return;
            }
            log("[yaaost] defineProperty", prop, copy);
            _defineProperty(obj, prop, copy);
        };
    })();
    (function(){
        ["assign", "entries", "getOwnPropertyDescriptor", "getOwnPropertyDescriptors", "getOwnPropertyNames", "getOwnPropertySymbols", "getPrototypeOf", "hasOwn", "is", "keys", "values"].forEach(prop => {
            patch(Object, prop, function(target, thisArg, arguments, newTarget){
                for (let i = 0 ; i < arguments.length ; i++){
                    patchedFunc[arguments[i]] && (arguments[i] = patchedFunc[arguments[i]]);
                }
                return _Reflect_apply(target, thisArg, arguments);
            });
        });
        ["hasOwnProperty", "propertyIsEnumerable"].forEach(prop => {
            patch(Object.prototype, prop, function(target, thisArg, arguments, newTarget){
                patchedFunc[thisArg] && (thisArg = target);
                return _Reflect_apply(target, thisArg, arguments);
            });
        });
    })();
    const makeProxy = (function(){
        return function(owner, chain) {
            const pos = chain.indexOf('.');
            if ( pos === -1 ) {
                patch(owner, chain, function(target, thisArg, arguments, newTarget, err, refErr){
                    if ( mustAbort(err) ) {
                        throw refErr;
                    }
                    return newTarget ? _Reflect_construct(target, arguments, newTarget) : _Reflect_apply(target, thisArg, arguments);
                }, opts);
                return;
            }
            const prop = chain.slice(0, pos);
            let v = owner[prop];
            chain = chain.slice(pos + 1);
            if ( v ) {
                makeProxy(v, chain);
                return;
            }
            log("[yaaost] error: no property", prop, "in", owner);
        };
    })();
    const owner = window;
    makeProxy(owner, chain);
    const oe = window.onerror;
    window.onerror = function(msg, src, line, col, error) {
        if ( typeof msg === 'string' && msg.indexOf(magic) !== -1 ) {
            return true;
        }
        if ( oe instanceof Function ) {
            return oe(msg, src, line, col, error);
        }
    }.bind();
})();
```
This is the filter for ygosu.com using `yaaost`.
```
! disable not working filter
ppss.kr,ygosu.com#@#+js(aost, XMLHttpRequest.prototype.send, /th:\d+\s+[a-zA-Z]\d\/<@[^\t]+\t\s[a-zA-Z]\d@|th:\d+\s+in[a-zA-Z\d:;]+\t\s[a-zA-Z]\d\si/)
! working filter
ppss.kr,ygosu.com##+js(yaaost, Element.prototype.attachShadow, /th:\d+\s+[a-zA-Z]{2}\/<\/[a-z.]+<\/<@|\t\s[a-zA-Z]{2}\.<[a-z]+>/, 2)
ppss.kr,ygosu.com##+js(yaaost, Element.prototype.removeAttribute, /\t\s[a-zA-Z]{2}\/<\/<\/<@|(\t\sObject+\.[a-zA-Z]+ [:a-zA-Z\d]+){3}/, 2)
```

**Comment by avotoko** [comment] 2021-10-04 11:39
>This is the filter for ygosu.com using yaaost.

The filter stopped working right after I posted. Under investigation.

**Comment by jcubic** [comment] 2021-11-29 19:52
Adding my few cents, I didn't test this but I'm doing a lot of patching and meta programming in my own code. And was wondering maybe you can try to use Proxy object as prototype. With some trickery you can change the function that will look like it was not changed and allow to use original unmodified function while keeping patched version on the site. I can try to create a POC to see if something like this is possible. This can be fun project and usage of proxy, that is indistinguishable from original object in JavaScript. 

PS: was searching the repo because Spotify blocking no longer works. Maybe some new cloak mechanism need to be invented. Note that if I will succeed with my POC I will write article about this.

**Comment by jcubic** [comment] 2021-11-29 20:09
I'm thinking about API like this:
```javascript 
cloak(function(RegExp, Number,...) {
   // your code
}, RegExp, Number, ...);
```
the only problem I see is that you will need to use `new RegExp()` instead of regex literals, but it's small thing to pay if you want to hide your code.

I don't yet know if it would work and how the API would look like. The symbol can be added to access internals.

let me know if you're interested. Now I have to try to implement this.

**Comment by gorhill** [comment] 2021-11-29 20:22
The problem is understood here, it's just a case of caching the prototype method locally in the scriplet before the page patches it.

**Comment by MasterKia** [comment] 2022-08-29 16:05
`soft98.ir` 
This site is also now hooking the `RegExp.test`:
```js
var Gt = ut && /Firefox/i.test(navigator.userAgent),
        Xt = (c.get("Function.prototype.toString"), Function.prototype.toString = Qt, RegExp.prototype.test),
        t = (RegExp.prototype.test = function (e) {
            return e !== String(Qt()) && Xt.call(this, ...arguments)
        },
```

**Comment by mapx-** [comment] 2022-09-14 12:48
@gorhill 

add regexp-utils to protect regexp.prototype.test method

https://github.com/AdguardTeam/Scriptlets/commit/d1ef3662e2a574191f407d069dcdc333541781af

**Comment by gorhill** [comment] 2023-07-14 11:59
Closing as per <https://github.com/gorhill/uBlock/commit/5c9c87e485308cb2dc6da102a0e20d8fce84124e>.

**Closed by gorhill** 2023-07-14 11:59 UTC
Labels: something to address
