### ISSUE TITLE
Cannot edit picker window if modal is open

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1637] opened 2021-06-16 14:50 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [ ] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Editing rules in picker-window is made impossible if cookie-modal is open on `www.lego.com`.

### A specific URL where the issue occurs

`https://www.lego.com/ja-jp`

### Steps to Reproduce

1.

![lego1](https://user-images.githubusercontent.com/58900598/122241045-353a6800-cefd-11eb-9d72-7c04c5741627.png)

2.

Open the picker, choose the modal and try to edit the rule.

![lego2](https://user-images.githubusercontent.com/58900598/122241099-408d9380-cefd-11eb-956d-e3aeff9deed9.png)

### Expected behavior:

Editable

### Actual behavior:

Described. It may be editable if you open dev tools and choose something in Inspect tab.

### Your environment

* uBlock Origin version: 1.35.2/1.35.3rc4
* Browser Name and version: Firefox 89.0/Chrome 91.0.4472.106
* Operating System and version: Windows 10

**Comment by Yuki2718** [comment] 2021-06-16 14:58
The picker is interrupted only for minutes after page load.

**Comment by gorhill** [comment] 2021-06-16 15:14
Looks like a duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/1098>. If I remove the `blur`, `focus`, `focusin`, focusout` listeners, the focus is no longer stolen from the picker. Using the following filter also fixes the focus-stealing behavior:

    lego.com##+js(aeld, /blur|focus(in|out)?/)

**Comment by Yuki2718** [comment] 2021-06-16 15:21
Should the filter be added?

**Comment by gorhill** [comment] 2021-06-16 15:35
> Should the filter be added?

I guess not, from what I peruse looking around, most people who care to use the picker don't even try to modify the suggested choice, let alone editing the field manually. AdGuard suffers the same issue if one expand the "Advanced settings" part of the picker to try to edit manually -- which is also probably rarely used.

**Comment by Yuki2718** [comment] 2021-06-16 15:42
Okay, maybe this can be closed.

**Closed** 2021-06-16 15:51 UTC
Labels: external

**Comment by peace2000** [comment] 2021-11-12 21:19
This site https://www.mehilainen.fi/ suffers from the same issue. Can't edit filter in element picker.
