### ISSUE TITLE
Improve wording: Remove master and blacklist & whitelist terminology

### ISSUE THREAD

**Issue by sudwhiwdh** [uBlockOrigin/uBlock-issues#1132] opened 2020-06-28 17:14 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

In response to recent events, I ask you to help ensure that your add-on no longer discriminates by language.
This applies to the naming of the development branch, the filter lists in the add-on itself and the wiki pages such as https://github.com/gorhill/uBlock/wiki/Dashboard:-Whitelist.

**Comment by uBlock-user** [comment] 2020-06-28 17:15
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1114

**Closed by uBlock-user** 2020-06-28 17:15 UTC
