### ISSUE TITLE
Add a keyboard shortcut to toggle remote font blocking

### ISSUE THREAD

**Issue by thermosflasche** [uBlockOrigin/uBlock-issues#3358] opened 2024-08-30 03:44 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Similar to #3295, but more specific—it doesn't include the `toggle-large-media` shortcut proposed there.

uBO has a [keyboard shortcut for toggling JavaScript for the actual browser tab](https://github.com/gorhill/uBlock/blob/bc641fc02445058617b7d3a7df1542681281bc9c/src/js/commands.js#L174). It would be useful to have a keyboard shortcut like that but for remote font blocking.

As a side note, just like #3295's author, this issue is carried by a personal need: I have remote fonts disabled by default, and choose to enable them on a per-website basis.

### A specific URL where the issue occurs.

```yaml
URLs whose remote fonts wish to be blocked.
```

### Steps to Reproduce

1. Go to browser's shortcuts configuration (for instance, Firefox' Add-ons and Themes => Manage Extension Shortcuts).
2. Look for uBO's shortcuts.

### Expected behavior

Find a shortcut for toggling remote font blocking.

### Actual behavior

No such shortcut.

### uBO version

1.59.0

### Browser name and version

LibreWolf 129.0.1-1 (`librewolf-bin` from AUR)

### Operating System and version

Artix Linux

**Comment by garry-ut99** [comment] 2024-08-30 06:37
> Similar to #3295, but more specific—it doesn't include the `toggle-large-media` shortcut proposed there.

Still qualifies as a duplicate of #3295, unless you want another person to come and to create another separate thread with same description and with the only difference that a request will be to create a shorcut for `toggle-large-media` only and not for `remone-fonts`, I think whoever wants either shortcut, should continue and express his opinion in #3295, instead of creating new variants/combinations of the original thread.

**Closed** 2024-08-30 07:04 UTC
Labels: duplicate

**Comment by ioc2e3** [comment] 2025-06-23 00:43
Hope ...

Disable remote fonts by default ...

Hope ...

Provide option ...

Use to switch remote font shield ...

.
