### ISSUE TITLE
Integrate Duckgogo Tracker List - new script

### ISSUE THREAD

**Issue by Update45623** [uBlockOrigin/uBlock-issues#1154] opened 2020-07-14 10:41 UTC
now also Blokada integrated the list with 4.7

https://community.blokada.org/t/introducing-duckduckgo-tracker-radar-to-blokada/469

-> text from that page: 

"How is it made?

Considering the data model of the Tracker Radar, generating a verbatim list of hosts would not work well and cause many issues for host list based content blockers, like Blokada.

Instead, we have developed a script 15 that generates the blocklist in a bit different way. First of all, it will generate hosts with subdomains (and not top level domains), and will not include entries for very common subdomains, like www or api, that could easily break things. Second, it will only include entries for domains, for which the Tracker Radar detected enough of tracking resources for that subdomain. This, again, helps to eliminate entries that could break things. And finally, some categories, like CDN or Online Payment, are also ignored and not included in the list.

With this approach, we decided to err on the side of caution. Currently, the final list includes over 3k hosts, which seem to nicely compliment the more common blocklists."

Script:
https://github.com/blokadaorg/blokadaorg.github.io/blob/master/scripts/ddg.py

perhaps also nice for better security in ublock. if not, just close the issue!

**Comment by uBlock-user** [comment] 2020-07-14 11:15
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7073

**Closed by uBlock-user** 2020-07-14 11:15 UTC
