### ISSUE TITLE
Text clipped in overview panel

### ISSUE THREAD

**Issue by 95440b97d** [uBlockOrigin/uBlock-issues#813] opened 2019-12-09 21:07 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Text clipped in overview panel on Firefox with a large minium font size set.

A large minium font size is set to make pages better readable.

### A specific URL where the issue occurs

This does not apply to specific web pages but the attached screenshot is taken on https://arstechnica.com/.

### Steps to Reproduce

1. Create fresh browser profile.
2. Install ublock origin.
3. Set minium font size: Preferences -> Language and Appearance -> Advanced -> Minimum font size = 20.
4. Go to any web page.
5. Open ublock overview panel.

### Expected behavior:

Text in ublock overview panel should not be clipped.

### Actual behavior:

Text is clipped in overview panel.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 71.0
* Operating System and version: Arch Linux (Gnome on Xorg).

Text clipped:
![ublock](https://user-images.githubusercontent.com/22228993/70472765-94791a00-1ac7-11ea-80ae-5cbf4562948b.png)

Minimum font size:
![fonts](https://user-images.githubusercontent.com/22228993/70472783-9c38be80-1ac7-11ea-91e5-7d667a5020da.png)

**Comment by uBlock-user** [comment] 2019-12-09 21:50
By-design nature of how Firefox applies that setting to everything including the extension popup UI.

**Comment by uBlock-user** [comment] 2019-12-09 21:56
Duplicate of https://github.com/gorhill/uBlock/issues/2086 ?

same issue with uMatrix -- https://github.com/uBlockOrigin/uMatrix-issues/issues/44

**Comment by uBlock-user** [comment] 2019-12-09 22:03
Setting `popupFontSize` to `20px` or `21px` will serve a workaround for your case.

**Comment by gorhill** [comment] 2020-02-20 16:42
I can no longer reproduce with latest dev build, so possibly fixed with <https://github.com/gorhill/uBlock/commit/8adad98a0d61>.

**Closed by gorhill** 2020-02-20 16:42 UTC
Labels: Firefox, something to address
