### ISSUE TITLE
Add a scope selector in the extension popup with dynamic filtering

### ISSUE THREAD

**Issue by j-james** [uBlockOrigin/uBlock-issues#1563] opened 2021-04-24 05:38 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [~] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior
  - It is, this is a feature request

### Description

Currently, when on a URL that has subdomains (as an example, Old Reddit), it is impossible to define Dynamic Filters for that subdomain. This of course can be worked around by manually writing rules, but it would be much appreciated if it could be done in the interface as well.

### A specific URL where the issue occurs

`https://old.reddit.com`

### Steps to Reproduce

1. Enable Advanced Mode for Dynamic Filtering
2. [Second Step]
3. [and so on...]

### Expected behavior:

![Screenshot from 2021-04-23 22-32-52](https://user-images.githubusercontent.com/35242550/115948608-e257ad80-a483-11eb-9c3b-ce032c77f0bf.png)

My suggestion would be for different parts of the URL under the power button to be clickable to change the scope. The scope in question would be **bold**. 

For example, the default scope is **old.reddit.com** (even though only old.**reddit.com** is bolded in the above screenshot - I hope that doesn't serve another purpose). To change the scope to all of old.**reddit.com**, I would click the **reddit** part of the url. For all .com domains, old.reddit.**com** would be clickable.

This would act similar to the scope selector in uMatrix.

### Actual behavior:

There is no way that I know of to apply Dynamic Filtering to a subdomain from the UI.

### Your environment

* uBlock Origin version: 1.34.0
* Browser Name and version: Ungoogled Chromium 88.0
* Operating System and version: Linux 5.11

**Comment by uBlock-user** [comment] 2021-04-24 10:00
Sounds like https://github.com/gorhill/uBlock/issues/3297 ?

**Comment by j-james** [comment] 2021-04-24 10:43
Kind of, that seems more about the default setting rather than implementing an actual scope selector. This issue probably supersedes it.

Out of curiosity, are the open issues on the old uBlock tracker still considered active?

**Comment by uBlock-user** [comment] 2021-04-24 10:46
> Out of curiosity, are the open issues on the old uBlock tracker still considered active?

Yes.

**Comment by gorhill** [comment] 2021-04-24 11:55
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/730, which has been set as duplicate of https://github.com/gorhill/uBlock/issues/3297.

**Closed by gorhill** 2021-04-24 11:55 UTC
Labels: enhancement

**Comment by j-james** [comment] 2021-04-24 18:30
@gorhill Would you mind leaving this issue open instead, since it's on the new tracker and non-contributors can participate?

**Comment by gorhill** [comment] 2021-04-24 18:31
People can freely comment here.

**Comment by ccoager** [comment] 2023-08-10 13:53
I can't comment on the old ticket tracker so I'll add my feedback here.  I think a feature like this would be very desirable to those that use medium/hard mode and have to modify rules often.

A few more ideas to implement in the UI:
- Use an expanded field on the source domain like the UI is already doing for destination domains.  Clicking on the "..." would expand/shrink the list of domains.  If you have advanced user enabled, the panel would auto-expand already like it does for destination domains.  Then click and highlight the source domain to interact with when adding rules.  If you don't highlight a domain, it would default to the domain in the URL.
- Make the source domain a drop-down menu to select which to interact with.  Default to the domain in the URL.

Another idea could be to add an advanced setting boolean for source domains to add rules on the root level domain or not.  This could also work in conjunction with the default source domain selected for the UI implementation.

**Comment by Penguin-Guru** [comment] 2025-08-17 01:24
Unless there is already some way of doing this through the U.I. that I am not currently aware of, I think this is a very useful and important feature. It is not a duplicate of #730, since that was explicitly interpreted as not requesting a scope selector. It is also quite different from [3297](https://github.com/gorhill/uBlock/issues/3297), since no default behaviour would be changed. The U.X. @omentic outlined expecting is exactly what I would expect as well, perhaps with the addition of a slight background and/or font colouration to complement the bold font in indicating the active scope. I can't imagine this feature would be a burden on any existing users and it doesn't seem too hard to implement-- in fact, for all I know, the code might be almost identical to the existing functionality in uMatrix. @gorhill, I hope you will consider it. I might try making the change myself if I think I can but I have no experience developing browser extensions and I am not at all confident in my JavaScript.

Incidentally, I think the active scope should also be used when editing cosmetics via the U.I.
