### ISSUE TITLE
Element picker, zapper and procedural filtering not working on facebook.com

### ISSUE THREAD

**Issue by zakius** [uBlockOrigin/uBlock-issues#1571] opened 2021-04-29 15:15 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
As in title, it seems that extension is unable to inject scripts into website

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
`https://facebook.com`

doesn't have to be logged in

### Steps to Reproduce

1. Open website
2. Click extension icon
3. Click picker/zapper icon

or 

1. Add procedural filter from settings
2. Load website

### Expected behavior:

[What you expected to happen]

Picker/Zapper interface loads over website

or

Procedurally selected element is hidden

### Actual behavior:

[What actually happened]

Nothing

### Your environment

* uBlock Origin version: 1.35.0 installed from AMO
* Browser Name and version: Waterfox Classic 2021.04.2
* Operating System and version: Windows 10 19042.928

Additional notes:

- Works fine in Nightly
- Before submitting issue had outdated and I believe legacy variant of extension that displayed the same behavior, had to remove it first to install from AMO, everything else, including other websites, works just fine 
- I found the #1569 but it was closed due to not using proper template so I believe this one is not considered duplicate

**Comment by gorhill** [comment] 2021-04-29 15:23
Waterfox is not officially supported. Can you reproduce with Firefox?

**Comment by gorhill** [comment] 2021-04-29 15:36
> Waterfox Classic 2021.04.2

This is based on which version of Firefox?

**Comment by zakius** [comment] 2021-04-29 15:50
Latest Quantum-ESR-Current works fine

it's based on 56 with some newer features backported, once I tried building a complete list but failed
looking at the earlier mentioned issue and using mozregression I found first good Firefox version to be 67a1, if you're willing to support earlier I'd be grateful but seeing that it's older than now abandoned old-ESR I'm assuming you won't be interested, thanks for your time anyway

**Comment by uBlock-user** [comment] 2021-04-29 15:52
> it's based on 56

You should install uBlock-Legacy instead

**Comment by zakius** [comment] 2021-04-29 15:59
> 
> 
> > it's based on 56
> 
> You should install uBlock-Legacy instead -- https://github.com/gorhill/uBlock-for-firefox-legacy/releases

is there any benefit except of picker working on facebook? as far as I can tell everything else works just fine with newer builds and I appreciate improvements they bring

**Comment by gorhill** [comment] 2021-04-29 16:26
> I found first good Firefox version to be 67a1

The other similar report was stating Firefox 66.0. I will download a portable version of Firefox 66.0 to find out is I can reproduce, and if so, what is the issue. If I identify the issue, I will decide whether to increase the minimum supported version to 68.0 (currently it's 57.0) or whether to fix it if it's trivial.

**Comment by gorhill** [comment] 2021-04-29 16:58
The issue seems to be that uBO finds that `self.vAPI instanceof Object` is `false` at <https://github.com/gorhill/uBlock/blob/0f580ec20446e4fd508363d7f86bcdc43f9f0503/platform/chromium/vapi-client.js#L238>.

Changing the code to `self.vAPI instanceof Object` fixes this. So given how trivial is the fix, I will fix the issue.

I have no clue why using `self.vAPI` fails, and on `facebook.com` while this works fine elsewhere. There must be an issue which was fixed between 66.0 and 67.01a, would be nice to find it for reference.

**Comment by zakius** [comment] 2021-04-29 17:12
First of all: thank you for looking into this further and fixing it

I may run mozregression against nightlies to get better reference point but I am unable to look into the code itself

**Comment by zakius** [comment] 2021-04-29 19:02
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=4e98200ee53017fe8cd037abf948ebaabd33f229&tochange=b482c6618d72ac38a9a82fbccf425e0a7f8b6129

this is as accurate as I am able to pinpoint with my knowledge of mozregression, tried throwing these two changelists at it but got no builds in between and can't find anything that seems to directly affect that

**Comment by gorhill** [comment] 2021-04-29 20:37
Thanks for taking the time to narrow down to these bugzilla issues, I can't see anything obvious at first, maybe I will maybe give it another go if I have time, though more of interest to Waterfox as a fix to import.

**Comment by gorhill** [comment] 2021-04-29 20:46
The fix is in the latest dev build.

**Closed by gorhill** 2021-04-29 20:46 UTC
