### ISSUE TITLE
Accessing localStorage delays startup

### ISSUE THREAD

**Issue by agi90** [uBlockOrigin/uBlock-issues#899] opened 2020-02-20 19:51 UTC
While working on https://bugzilla.mozilla.org/show_bug.cgi?id=1616421 we noticed that uBlock accesses `localStorage` at startup and that causes a sync wait on disk (see profile at https://perfht.ml/2PblvOW). From looking at the code it seems like we can easily avoid that so I'll submit a patch shortly.

### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Install uBlock in Fenix
2. Connect profiler
3. Load a page
4. Observe uBlock causing sync disk access

### Expected behavior:

uBlock should not access localStorage when starting up

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.24.5b5
* Browser Name and version: Fenix Nightly, 75
* Operating System and version: Samsung S10, Android 10

**Comment by gorhill** [comment] 2020-02-20 20:27
I added logging trace to find out where `localStorage` is accessed at launch, here are the results:

    localStorage.getItem('deviceName') vapi-common.js:237:21
    localStorage.getItem('immediateHiddenSettings') vapi-common.js:237:21
    localStorage.getItem('SNFE.bidiTrieDetails') vapi-common.js:237:21
    localStorage.getItem('FilterOrigin.trieDetails') vapi-common.js:237:21
    localStorage.getItem('FilterHostnameDict.trieDetails') vapi-common.js:237:21
    localStorage.getItem('cosmeticSurveyingMissCountMax') vapi-common.js:237:21

**Comment by gwarser** [comment] 2020-02-20 21:07
Seems to be this one in cloud storage:

            deviceName: vAPI.localStorage.getItem('deviceName') || ''

![image](https://user-images.githubusercontent.com/886325/74978652-61d79000-542d-11ea-8a25-787fa1548753.png)

**Comment by gorhill** [comment] 2020-02-20 21:10
I think it's just the first one, the others are virtually instantaneous.

In any case, I think the bulk of the delay is probably the loading of filters in memory, the network requests are held back until uBO's filtering engines are populated -- so far I am skeptical not loading from `localStorage.getItem()` is going to make a noticeable difference.

**Comment by gorhill** [comment] 2020-02-20 21:33
@agi90 

> so I'll submit a patch shortly.

I made changes on my side to bypass `localStorage()` on mobile platform at launch time, this will be in the next dev build.

**Comment by gorhill** [comment] 2020-02-20 21:57
I tried very informally to see a difference in latest desktop Firefox stable, and skipping `localStorage.getItem()` seemed to reduce the launch time by 60ms on my side -- though I didn't test thoroughly. If the gain seem reproducible I might disable `localStorage` access at launch on all platforms -- currently it's done only for Firefox mobile. Changes are in latest dev build, 1.25.1b0.

**Comment by gorhill** [comment] 2020-02-20 22:10
@gwarser 

2,339 ms... !

I thought you were simply reporting what you saw in @agi90's profiling results and so I didn't look carefully... Is this your own profiling results? The profiling results posted by @agi90 shows `vAPI.cloud / getItem()` at ~237 ms.

**Comment by gwarser** [comment] 2020-02-20 22:45
This is profile from bugzilla report:

https://bugzilla.mozilla.org/show_bug.cgi?id=1616421#c1

> With ublock: https://perfht.ml/2P5p6Ow

**Comment by agi90** [comment] 2020-02-20 23:17
Ah awesome! Thank you @gorhill I can confirm I don't see the wait anymore with the latest master.

**Comment by snorp** [comment] 2020-02-20 23:31
Ideally, uBlock would abandon `localStorage` entirely in favor of the `storage` Web Extension API[1] or another asynchronous mechanism. It's Very Bad to use a synchronous API on the main thread, as delays of over 2s as seen in the profile on Bugzilla are entirely possible. The browser is unable to do any other work during that time (with caveats).

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage

**Comment by agi90** [comment] 2020-02-21 06:16
Just to put in perspective, I just recorded this profile of my S10 (so a newer-ish phone) where this call takes 2.5 seconds: https://perfht.ml/2PddUz9

I suspect it might take longer depending on the size of the localStorage db but I have no proof, so using a fresh profile might be misleading.

**Comment by uBlock-user** [comment] 2020-02-21 07:03
Doesn't this occur on th desktop platform ?

**Comment by gorhill** [comment] 2020-02-21 12:46
> I just recorded this profile of my S10

Just to be clear, that is with 1.24.4, right, i.e. without the fix above?

> uBlock would abandon localStorage entirely

Ok, I will revisit and remove all instances of localStorage use. As a first step for now access is removed from launch code.

**Comment by agi90** [comment] 2020-02-21 17:29
> Just to be clear, that is with 1.24.4, right, i.e. without the fix above?

Correct, that profile was recorded with uBlock before the fix

**Closed** 2020-03-06 14:29 UTC
Labels: Firefox-Android, bug

**Comment by h1z1** [comment] 2020-03-15 15:17
Curious change..  What happens if that doesn't trigger before use now?

**Comment by gwarser** [comment] 2020-04-18 16:13
Follow-up: https://github.com/gorhill/uBlock/commit/0bcf04d3dda2065a6a16c86b05fa3c95c8918ae9

I think this commit fixed storage lockups on startup on mobile devices (broken uBO state, cleaned-like cookies).
