### ISSUE TITLE
CNAME uncloaking fails if Firefox uses DNS over HTTPS

### ISSUE THREAD

**Issue by mhnestler** [uBlockOrigin/uBlock-issues#1190] opened 2020-07-31 00:46 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When DNS over HTTPS (DoH) is enabled, uBO's CNAME uncloaking feature does not work. No uncloaked hostnames appear in the popup (in blue nor any other color) and dynamic filtering is not aware of them.

It does not matter what DoH provider you use. I reproduced this with Cloudflare (Default) and with Custom: https://dns.quad9.net/dns-query.

At first I was suspicious that the DoH provider was sending different data compared to my ISP's DNS. However, that is not the problem, as a manual query to DoH shows (this is the same example as further below):
```
$ curl -H 'accept: application/dns-json' 'https://mozilla.cloudflare-dns.com/dns-query?name=cdn.vox-cdn.com&type=A'
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"cdn.vox-cdn.com","type":1}],"Answer":[{"name":"cdn.vox-cdn.com","type":5,"TTL":3593,"data":"z.vox-cdn.com."},{"name":"z.vox-cdn.com","type":5,"TTL":86393,"data":"prod.vox.map.fastly.net."},{"name":"prod.vox.map.fastly.net","type":1,"TTL":23,"data":"151.101.116.124"}]}
```

### A specific URL where the issue occurs

https://www.vox.com/

### Steps to Reproduce

1. In Firefox's Preferences > General > Network Settings > Settings..., ensure that "Enable DNS over HTTPS" is checked. (This is the default.) If you change the setting, restart the browser before proceeding.
2. Ensure uBO is not in hard mode (ensure that 3rd party requests are allowed). (This is just to make a shorter set of steps.)
3. Navigate to a site that has resources on domains that use CNAME. For example, navigate to https://www.vox.com/.
4. Open the uBO popup.
5. Click "+ all" to display all subdomains. Compare the list to the Expected / Actual behaviors.
6. Uncheck "Enable DNS over HTTPS", restart the browser, and do the above steps again, to see that this fixes the problem.

### Expected behavior:

On https://www.vox.com/, one domain in uBO's popup list is vox.map.fastly.net. One subdomain is prod.vox.map.fastly.net, listed in blue, mapped from cdn.vox-cdn.com.

Additional step/behavior: If you block 3rd-party requests (hard mode), and you no-op cdn.vox-cdn.com, assets from it should still get blocked because you did not unblock vox.map.fastly.net.

### Actual behavior:

On https://www.vox.com/, in uBO's popup list, there is vox-cdn.com, and subdomain cdn.vox-cdn.com, but NOT vox.map.fastly.net.

Additional step/behavior: If you load the page while blocking 3rd-party requests (hard mode), and you no-op cdn.vox-cdn.com, assets from it load, which is wrong behavior because it should get uncloaked to a domain which would still be blocked.

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Firefox 80.0b1 (also reproduced on Firefox 79.0)
* Operating System and version: macOS 10.15.5 (also reproduced on Ubuntu 18.04)

**Comment by uBlock-user** [comment] 2020-07-31 05:14
> When DNS over HTTPS (DoH) is enabled, uBO's CNAME uncloaking feature does not work

I have DoH enabled and TRR value set to `3`, works fine as expected.

>  in uBO's popup list, there is vox-cdn.com, and subdomain cdn.vox-cdn.com

There's no guarantee that a domain will supply its CNAME whenever you browse to it. Sometimes it will, sometimes it won't.

**Comment by gwarser** [comment] 2020-07-31 10:22
4 months ago https://www.reddit.com/r/uBlockOrigin/comments/fitnss/cname_uncloaking_does_not_work_with_some_providers/

**Comment by gorhill** [comment] 2020-07-31 11:47
uBO uses the `browser.dns.resolve()`, API, it has not control beyond that of how CNAME are resolved -- and has no knowledge of how DNS is setup on your browser or computer. If you think CNAME are not resolved while they should be, you need to bring the issue to Firefox devs.

@uBlock-user 

> TRR value set to 3, works fine as expected

What is this TRR value you speak of? I found `network.trr.mode` in `about:config` but changing that setting to 3 did nothing.

**Comment by mhnestler** [comment] 2020-07-31 12:21
> There's no guarantee that a domain will supply its CNAME whenever you browse to it. Sometimes it will, sometimes it won't, based on your DNS-resolver's geographic location.

I find it hard to believe this is the cause, for two reasons:

1. When I query Cloudflare's DoH service's JSON API using curl, I get the CNAME record(s).
2. The issue is 100% reproducible for me across every site I've tried. Here are more examples. With DoH, **none** of the following show up. I could go on and on.
   - https://www.yahoo.com/
       - prod-rotation-v2.guce.aws.oath.cloud <-- guce.yahoo.com
       - ds-geoycpi-uno-lite.gycpi.b.yahoodns.net <-- udc.yahoo.com
       - edge.gycpi.b.yahoodns.net <-- s.yimg.com
   - https://www.nytimes.com/
       - d3torq5rsusku9.cloudfront.net <-- dd.nytimes.com
       - gstaticadssl.l.google.com <-- fonts.gstatic.com
       - ghs.googlehosted.com <-- purr.nytimes.com
       - nytimes.map.fastly.net <-- a1.nyt.com
    - https://www.cnn.com/
       - e12596.dscj.akamaiedge.net <-- dynaimage.cdn.cnn.com
       - s3-1-w.amazonaws.com <-- cnn-rel-disc-proto.s3.amazonaws.com
       - f.ssl.fastly.net <-- img.bleacherreport.net
       - sni1gl.wpc.kappacdn.net <-- cdn.cookielaw.org
       - edge-geo.nc0.co <-- agility.cnn.com
       - turner-tls.map.fastly.net <-- www.i.cdn.cnn.com

> I have DoH enabled and TRR value set to `3`, works fine as expected. For, example `ghacks.net` sometimes serves me via `marfeel.map.fastly.net` and sometimes via `marfeelcdn.com` as the CNAME.

Just now I tried setting network.trr.mode to `3` (meaning DoH only) and observed the same results I described. Before, it had been set to `2` (meaning DoH with fallback to normal DNS).

It's interesting that it (sometimes) works right for you, but not for me.

> What is this TRR value you speak of? I found `network.trr.mode` in `about:config` but changing that setting to 3 did nothing.

https://wiki.mozilla.org/Trusted_Recursive_Resolver#DNS-over-HTTPS_Prefs_in_Firefox

**Comment by uBlock-user** [comment] 2020-07-31 12:22
@gorhill https://wiki.mozilla.org/Trusted_Recursive_Resolver#DNS-over-HTTPS_Prefs_in_Firefox

**Comment by uBlock-user** [comment] 2020-07-31 12:24
> The issue is 100% reproducible for me across every site I've tried

Because of your geo-graphical location. I'm not served with CNAMEs when I visit `vox.com` and that is not surprising because CDNs decide the route, not uBO.

**Comment by gorhill** [comment] 2020-07-31 12:35
> The issue is 100% reproducible for me across every site I've tried.

I forgot to mention: yes, I am able to reproduce.

**Comment by mhnestler** [comment] 2020-07-31 12:35
@uBlock-user 
Perhaps Firefox's issue, yes.

Definitely not my location only. That would imply that when I use Cloudflare DNS, not a single CDN chooses to serve me via CNAME. But even more clearly, look at fonts.gstatic.com (CNAME gstaticadssl.l.google.com). I don't think that's a CDN.

**Comment by uBlock-user** [comment] 2020-07-31 12:39
CNAMEs are definitely route based and routes are served based on your location, we regularly receive site breakage issues where one filterlist maintainer can reproduce breakage via CNAMEs while another filterlists maintainer can't(CNAME doesn't appear for them) simply because of their varying location.

**Comment by mhnestler** [comment] 2020-07-31 12:40
@gorhill 
> uBO uses the `browser.dns.resolve()` API, it has not control beyond that of how CNAMEs are resolved -- and has no knowledge of how DNS is setup on your browser or computer. If you think CNAMEs are not resolved while they should be, you need to bring the issue to Firefox devs.

\*sigh\* I know you must be right, but we know how long bugs sit in bugzilla. Thanks for the quick response.

**Comment by gorhill** [comment] 2020-07-31 12:41
I was not able to find a bug related to this in bugzilla, so I will try to make a minimalist extension to reproduce the issue then I will open an issue about this.

**Comment by mhnestler** [comment] 2020-07-31 12:47
@gorhill Cool. Thanks for your tireless work.

@uBlock-user Of course what you say about CDNs in general is true. But here is a minimal example to prove that that is not the point here. It is my own employer's site, and I have access to the DNS configuration of it. The host `wbweb.weatherbuild.co` has a CNAME of `wbweb.us-east-1.elasticbeanstalk.com` no matter where you are in the world.

Thanks to all, again, for such prompt responses!

**Comment by uBlock-user** [comment] 2020-07-31 13:01
> The host wbweb.weatherbuild.co has a CNAME of wbweb.us-east-1.elasticbeanstalk.com no matter where you are in the world.

Hmmm, I can reproduce the issue consistently with this case.

**Comment by opusforlife2** [comment] 2020-08-02 20:33
This presents a dilemma.
- If you choose to keep DoH enabled in Firefox, you lose CNAME uncloaking.
- If you choose to disable DoH in Firefox, you lose Encrypted SNI. (Doesn't matter if your system resolver has DoT/DoH or not. Firefox only checks for internal resolver.)

**Comment by uBlock-user** [comment] 2020-08-02 20:40
I set TRR mode to `2`, so a lesser of two evils as I definitely do not want to lose ESNI.

**Comment by opusforlife2** [comment] 2020-08-03 19:02
Yeah. Tracking by your snooping ISP is worse than tracking by a website you can visit that tracks you through CNAMEs. One of them is avoidable.

**Comment by mhnestler** [comment] 2020-08-07 16:56
In case anyone is looking for the programmatic way to reproduce this as a Firefox bug, independent of uBO:

Open a webextension console. (go to about:debugging -> This Firefox, click Inspect on any extension that has `dns` permission.)

```
await browser.dns.resolve('wbweb.weatherbuild.co', ['canonical_name'])
Object { addresses: (2) […], canonicalName: "wbweb.weatherbuild.co", isTRR: true }
await browser.dns.resolve('wbweb.weatherbuild.co', ['canonical_name', 'disable_trr'])
Object { addresses: (2) […], canonicalName: "wbweb.us-east-1.elasticbeanstalk.com", isTRR: false }
```

**Comment by opusforlife2** [comment] 2020-08-16 15:20
> I was not able to find a bug related to this in bugzilla, so I will try to make a minimalist extension to reproduce the issue then I will open an issue about this.

Did you? I can't navigate Bugzilla so I can't check on my own. It's like a whole other dimension whose rules I fail to understand.

**Comment by gorhill** [comment] 2020-09-21 13:00
https://bugzilla.mozilla.org/show_bug.cgi?id=1666249

**Comment by valenting** [comment] 2020-09-24 08:30
I landed the patch in nightly. Can someone check if it fixes the problem?

**Comment by uBlock-user** [comment] 2020-09-24 09:04
Tested on `network.trr.mode` set to `3` and/or `2`, CNAMEs are being filtered(appearing in popup panel/logger) on vox/github/reddit on Nightly, so working as expected.

**Closed by uBlock-user** 2020-09-24 09:04 UTC
Labels: Firefox, external
