### ISSUE TITLE
Higher disk usage from twitter when uBlock Origin is enabled

### ISSUE THREAD

**Issue by mariomadproductions** [uBlockOrigin/uBlock-issues#2030] opened 2022-03-04 12:50 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

Higher disk usage from twitter when uBlock Origin is enabled.

### A specific URL where the issue occurs

https://twitter.com/home

### Steps to Reproduce

1. Open https://twitter.com/home
2. Observe disk activity (with a hard drive, you can simply hear that there are more writes)

### Expected behavior

Same/similar disk activity levels as when uBlock Origin is disabled.

### Actual behavior

Higher disk activity than when uBlock Origin is disabled.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.2
Chromium: 98
filterset (summary): 
  network: 86722
  cosmetic: 76384
  scriptlet: 27697
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    adguard-generic: 62081-660, 1d.20h.53m
    adguard-mobile: 7282-43, 1d.20h.52m
  default: 
    user-filters: 0-0, never
    easylist: 64087-926, 1d.20h.54m
    easyprivacy: 26634-244, 1d.20h.51m
    ublock-abuse: 72-0, 1d.20h.58m
    ublock-badware: 3899-252, 1d.20h.57m
    ublock-filters: 30232-3068, 1d.20h.59m
    ublock-privacy: 204-2, 1d.20h.56m
    ublock-unbreak: 1720-93, 1d.20h.55m
filterset (user): [empty]
trustedset: 
  added: [array of 2 redacted]
  removed: 
    chrome-scheme
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3359 ms (selfie)
  maxAssetCacheWait: 1466 ms
```
</details>

**Comment by uBlock-user** [comment] 2022-03-04 12:52
Closing as invalid as per --

> Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/devtools/docs/profiles) + fully substantiated analysis supporting the claim.

**Closed by uBlock-user** 2022-03-04 12:52 UTC

**Comment by mariomadproductions** [comment] 2022-03-04 13:38
> Closing as invalid as per --
> 
> > Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data from [Firefox Profiler](https://profiler.firefox.com/)/[Chromium Profiler](https://developer.chrome.com/devtools/docs/profiles) + fully substantiated analysis supporting the claim.

Chrome link is dead - can you share instructions for this so I can make a new issue or re-open this one?

**Comment by uBlock-user** [comment] 2022-03-04 13:56
https://developer.chrome.com/docs/devtools/evaluate-performance/reference/

**Comment by gorhill** [comment] 2022-03-04 14:23
_one_ profiling session is not enough, there need to be two, one with uBO, one without uBO. Additionally, even if it's shown that there is a _significant_ difference with and without, it would have to be shown uBO itself is the cause, as if the cause is thewebpge itself, then it's a filter issue.
