### ISSUE TITLE
Picker Mode does not work when Disable cosmetic filtering is enabled

### ISSUE THREAD

**Issue by SulpherStaer** [uBlockOrigin/uBlock-issues#1487] opened 2021-02-05 16:51 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The Element Picker mode does not function correctly when 'Disable cosmetic filtering' is enabled. It does not grey out the screen and enter element selection mode. Element Zapper, which as a user seems to perform a similar method of selecting an element, does still function.

### A specific URL where the issue occurs

youtube.com
github.com

### Steps to Reproduce

1. In uBlock Origin Dashboard, under Default behavior, enable 'Disable cosmetic filtering'
2. Go to any site (I personally tested on youtube & github.com
3. Click the badge to open the quick menu
4. Enter Element Picker Mode

### Expected behavior:

I expect the website to 'gray out', and red selection boxes to appear to select particular elements.

### Actual behavior:

The site did not grey out, and no red selection boxes appeared.

### Your environment

* uBlock Origin version: 1.32.4
* Browser Name and version: Google Chrome 88.0.4324.150 (64bit)
* Operating System and version: Windows 10 (Build 19041.746)

**Comment by uBlock-user** [comment] 2021-02-05 17:03
Duplicate of gorhill/uBlock#3212.

**Closed by uBlock-user** 2021-02-05 17:03 UTC

**Comment by SulpherStaer** [comment] 2021-02-05 17:08
Ah, yes. I did not check the old area when looking if this bug was already reported. My apologies.
