### ISSUE TITLE
uBlock Origin preventing Gmail from displaying body of email in Firefox

### ISSUE THREAD

**Issue by ChrisTheCat** [uBlockOrigin/uBlock-issues#2017] opened 2022-02-27 14:37 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

When viewing Gmail in Firefox, if uBlock Origin is enabled, the body of the message does not display.

Others are having this problem too, as reported at https://support.google.com/mail/thread/152369047/body-of-email-not-showing?hl=en

### A specific URL where the issue occurs

https://mail.google.com/mail/u/0/#inbox/FMfcgzGmvBwZJNmLzHxMthLzQNGpxJnJ

### Steps to Reproduce

1. Open Gmail in Firefox
2. Open an email, see no body of the message
3. Disable uBlock Origin > body of message instantly appears

### Expected behavior

Entire email body shouldn't be blocked

### Actual behavior

Entire email body was blocked

### uBlock Origin version

1.41.8

### Browser name and version

Firefox 91.6.0esr (64-bit)

### Operating System and version

macOS 12.2.1

**Comment by uBlock-user** [comment] 2022-02-27 14:42
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/11906

**Closed by uBlock-user** 2022-02-27 14:42 UTC

**Comment by Esteban70x7** [comment] 2022-02-28 17:24
I have the same problem.

**Comment by mapx-** [comment] 2022-02-28 17:38
update the filter lists
