### ISSUE TITLE
Help icon on some settings toggles setting rather than opening help

### ISSUE THREAD

**Issue by dtgriscom** [uBlockOrigin/uBlock-issues#1860] opened 2021-12-07 02:57 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

The uBlock0 Dashboard page has many "?" icons next to the various settings; clicking most of the "?" icons opens a new tab on the relevant wiki page. However, on the "Filter lists" page, two of the icons seem non-functional:

- "Parse and enforce cosmetic filters"
- "Ignore generic cosmetic filters"

These two settings have the usual "?" icon to their right. However, clicking the icon doesn't open the wiki page; it instead toggles the setting's checkbox. (I haven't found any other uBlock0 settings where this is true.)

### A specific URL where the issue occurs

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html

### Steps to Reproduce

1. Open Dashboard
2. Switch to "Filter lists" page
3. Click "?" icon to right of "Import" setting at bottom; notice that it opens new tab showing the relevant wiki page (good)
4. Click "?" icon to right of "Parse and enforce cosmetic filters" setting.

### Expected behavior

opens new tab showing the relevant wiki page

### Actual behavior

It toggles the setting rather than going to the wiki (bad)

### uBlock Origin version

Installed today (12/6/2021)

### Browser name and version

Chrome 96.0.4664.55

### Operating System and version

macOS 10.14.6

**Comment by gorhill** [comment] 2021-12-07 13:57
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/1172>.

**Closed by gorhill** 2021-12-07 13:57 UTC

**Comment by dtgriscom** [comment] 2021-12-07 14:11
Sorry... I **did** try to find it in the existing issues....
