### ISSUE TITLE
Copy/paste issue

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uBlock-issues#62] opened 2018-06-08 14:05 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

uBO allows you to cut and copy empty lines

### Steps to Reproduce
1) Create a new rule, using the Element Picker.
2) Open the 'My filters' window.
3) Highlight the new rule that you just created, and select "Cut".
4) Now, locate a empty line in your filter list, where you'd like to place this new rule (most people like to have things sorted alphabetically).
5) Right-click on the empty line and select "Cut" (imagining that you did this by accident).

### Expected behavior:
The empty line should be ignored, and the clipboard should still contain the new rule that you created

### Actual behavior:
You have now got a empty line stored in your clipboard, and the new rule that you created in step 1 above is gone!

Of course, you can relocate the missing rule, simply by avoiding to press the 'Apply changes' button, then close and reopen the window.
But nevertheless.. Shouldn't uBO disallow cutting or copying empty lines?

### Your environment

* uBlock Origin version: 1.16.4.1 (XUL) **[*]**
* Browser Name and version: Pale Moon v27.9.2,x64
* Operating System and version: Win8.1Pro,x64

--

**[*]** Speaking of the XUL version..
Would it be possible to fix this small issue too?:
`https://github.com/uBlockOrigin/uBlock-issues/issues/22/#issuecomment-384240402`

**Comment by gwarser** [comment] 2018-06-08 14:19
Cuts new line character.
Works like this in CodeMirror demo pages http://codemirror.net/demo/search.html
I think is by design.

**Comment by gwarser** [comment] 2018-06-08 14:27
Seems to be configurable:

>lineWiseCopyCut: boolean
    When enabled, which is the default, doing copy or cut when there is no selection will copy or cut the whole lines that have cursors on them.

http://codemirror.net/doc/manual.html

**Comment by uBlock-user** [comment] 2018-06-08 14:35
> Right-click on the empty line and select "Cut" (imagining that you did this by accident).

I cannot select cut, it's greyed out.

**Comment by uBlock-user** [comment] 2018-06-08 14:41
Cannot reproduce on Chromium, however I can reproduce this on Firefox Nightly. This is more or less, default browser behaviour.

**Comment by gwarser** [comment] 2018-06-08 15:19
@uBlock-user try ctrl+x I can reproduce this way on Chromium 66

**Comment by uBlock-user** [comment] 2018-06-08 15:22
> try ctrl+x

Yes, that does cut the empty line and the previous cut filter gets replaced..

**Comment by gorhill** [comment] 2018-06-08 15:36
Looks like a Firefox issue to me, the Cut/Copy entries are enabled in the menu even for empry lines in plain textarea elements.

**Comment by gorhill** [comment] 2018-06-08 15:37
> Of course, you can relocate the missing rule, simply by avoiding to press the 'Apply changes' button, then close and reopen the window.

Just Undo the changes (Ctrl-Z).

**Comment by gorhill** [comment] 2018-06-08 15:39
Given how trivial it is to undo, really I don't plan to spent time on such a trivial issue. Closing as "wontfix".

**Closed by gorhill** 2018-06-08 15:39 UTC
Labels: Chrome, Firefox, wontfix

**Comment by gwarser** [comment] 2018-06-08 15:57
This is [CodeMirror](https://codemirror.net/) feature.
Just put `lineWiseCopyCut: false` to initialization function, and it's gone.
