### ISSUE TITLE
Request for the popup

### ISSUE THREAD

**Issue by mikhoul** [uBlockOrigin/uBlock-issues#24] opened 2018-04-29 23:34 UTC
First thanks for your work :+1: 

Could you ad in the popup over the local/global columns a label to identify those 2 columns ?

Like this:

![GitHub Logo](https://i.imgur.com/0Lmqtfz.png)

It would help to remember especially for the newbies and non tech people the purpose of those 2 columns.

Regards :octocat: 

_N.B._: I've asked the same request to maintainer of Nano Adblocker since I use both ad-blockers on different systems.

**Comment by okiehsch** [comment] 2018-04-30 03:49
Duplicate of https://github.com/gorhill/uBlock/issues/840

A detailed explanation by gorhill why he declined the original issue: https://github.com/gorhill/uBlock/issues/840#issuecomment-149564896

This was quite some time ago and since then that part of the user interface has been made availablle to every user, so maybe he reconsidered.

**Closed** 2018-04-30 05:41 UTC
Labels: duplicate

**Comment by gwarser** [comment] 2018-04-30 07:10
Tooltip is already here - move your mouse over first row (it's first row only, to prevent distraction).
