### ISSUE TITLE
Can not open element-picking-mode

### ISSUE THREAD

**Issue by Magicool-1** [uBlockOrigin/uBlock-issues#81] opened 2018-06-21 20:26 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Not able to open element picker

### A specific URL where the issue occurs

```
www.google.com
www.youtube.com
www.github.com
www.gitlab.com
```

### Steps to Reproduce

1. Right click
Click on Block Element
or
2. Click on uBlock icon
Click on "Enter element picker mode"

### Expected behavior:

Element picker should open.

### Actual behavior:

1: Right click menu disappears and nothing happens
2: after clicking on element-picking-mode nothing happens

### Your environment

* uBlock Origin version:  1.16.10
* Browser Name and version: Chrome 67.0.3396.87 + Firefox 60.0.2
* Operating System and version: Windows 10 Pro 64bit 1803

**Comment by uBlock-user** [comment] 2020-02-07 23:36
Enable cosmetic filtering ?

**Comment by Yuki2718** [comment] 2020-02-08 00:15
I know it is only for confirmed issue so hasn't reported but I experienced the same problem a few times. I doubt it has sth to do w/ reddit, it rather seemed to be a problem of some tab(s) open at the time. Restart the browser, reload the tabs, close and open uBO dashboard etc. eventually fixed it, please test @allanwind. I still don't figure out conditions to reproduce.

**Comment by uBlock-user** [comment] 2020-02-08 06:01
Duplicate of https://github.com/gorhill/uBlock/issues/3212

**Closed by uBlock-user** 2020-02-08 06:01 UTC
Labels: unable to reproduce
