### ISSUE TITLE
[FEATURE REQUEST] uMatrix like interface

### ISSUE THREAD

**Issue by puchu** [uBlockOrigin/uBlock-issues#2226] opened 2022-08-21 20:33 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

the current interface in advanced mode mixes different requests like pictures, scripts, xhr,... together. Would be nice to get an enhanced mode where it's possible to block/allow requests in an interface that mimics the uMatrix interface and allows for ex. to allow only pictures but no scripts from a specific domain

### A specific URL where the issue occurs

everywhere

### Steps to Reproduce

.

### Expected behavior

an uMatrix like interface in advanced mode

### Actual behavior

a mode generalized interface

### Configuration

<details>

```yaml
uBlock Origin: 1.44.0
Firefox: 103
filterset (summary): 
  network: 80252
  cosmetic: 45369
  scriptlet: 17646
  html: 725
listset (total-discarded, last updated): 
  default: 
    user-filters: 28-0, never
    ublock-filters: 33209-72, 4d.6h.44m
    ublock-badware: 4237-0, 4d.6h.44m
    ublock-privacy: 247-0, 4d.6h.44m
    ublock-abuse: 76-0, 4d.6h.44m
    ublock-unbreak: 1871-0, 4d.6h.44m
    easylist: 69526-595, 4d.6h.44m
    easyprivacy: 27354-581, 4d.6h.44m
    plowe-0: 3635-3, 4d.6h.44m
    urlhaus-1: 4828-0, 4d.6h.44m
    ublock-quick-fixes: 401-0, 4d.6h.44m
filterset (user): [array of 28 redacted]
trustedset: 
  added: [array of 1 redacted]
  removed: 
    edge-scheme
hostRuleset: 
  added: [array of 22 redacted]
modifiedUserSettings: 
  autoUpdate: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1584 ms (selfie)
  maxAssetCacheWait: 129 ms
```
</details>

**Comment by gothic-bum** [comment] 2022-08-21 20:41
>  * [x]  I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue

Duplicate of:
https://github.com/uBlockOrigin/uBlock-issues/issues/1324

**Comment by puchu** [comment] 2022-08-21 21:11
maybe he changed his mind?
The current interface is too generic and compared to the uMatrix interface it's a step backwards.

**Comment by gothic-bum** [comment] 2022-08-21 22:29
> maybe he changed his mind?

Perhaps, but note that he is well aware of the request and has declined it multiple times. I highly doubt that creating a duplicate for the same issue is going to change his mind.

> i would also be fine to do a PR but i would need some help to implement it. I'm more into C/C++

I'm sure this would be welcomed by many users, some of whom would likely be willing to provide help. As a suggestion, you may want to post this on [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).

**Comment by puchu** [comment] 2022-08-21 22:37
the actual problem with the current solution is, that let's say site A needs pictures from site B to work.
That's fine, but the current uBlock interface only allows to whitelist a complete domain/sub-domain for everything aka
scripts, frames, pictures, xhr, .... and that's very messy, because although i only need the pictures of site B to make site A work. If site B gets compromised the current implementation would also load the maybe malicious scripts from site B or load compromised frames.

The dev of uBlock actually showed me how to handle this problem correctly aka uMatrix and i can't forget about his perfect solution for this complicated problem :)

**Comment by gothic-bum** [comment] 2022-08-21 22:49
> the current uBlock interface only allows to whitelist a complete domain/sub-domain for everything aka
scripts, frames, pictures, xhr, ....  
  
Although this is a limitation of the popup user interface, you can still manually create rules (noop, etc) that are more specific.

**Comment by puchu** [comment] 2022-08-21 22:58
same interface but just a few more columns aka "script, frame, image, ..." would fix the problem :)

**Comment by puchu** [comment] 2022-08-21 23:01
same interface but just a few more columns aka "script, frame, image, ..." would fix the problem

**Comment by gorhill** [comment] 2022-08-22 16:28
Duplicate of <https://github.com/gorhill/uBlock/issues/1038>, which has been declined.

**Closed by gorhill** 2022-08-22 16:28 UTC
