### ISSUE TITLE
Apple Silicon Constant Crashes

### ISSUE THREAD

**Issue by funkymonkeyboy** [uBlockOrigin/uBlock-issues#1354] opened 2020-11-21 17:33 UTC
### Prerequisites

- [x} I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When installing and using ublock origin extension, Firefox crashes immediately

### A specific URL where the issue occurs

www.mullvad.net

### Steps to Reproduce

1. Install Firefox 84 beta 3 on Apple M1 Silicon MacBookAir
2. Install UBlock Origin extension
3. Firefox Crashes

### Expected behavior:

Firefox Crashes

### Actual behavior:

Firefox Crashes

### Your environment

* uBlock Origin version: 1.31.0
* Browser Name and version: Firefox 84 beta 3
* Operating System and version: MacOS 11.0.1

**Comment by gwarser** [comment] 2020-11-21 18:13
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/1352

Try this:

Open `about:config` and change `javascript.options.wasm` to `false`.

**Closed by gwarser** 2020-11-21 18:13 UTC

**Comment by gorhill** [comment] 2020-11-21 18:47
Browser crashes need to be reported to browser developers, especially for a beta platform such as "Apple Silicon", https://bugzilla.mozilla.org/show_bug.cgi?id=1648496#c2>.

**Comment by ELLIOTTCABLE** [comment] 2020-11-27 18:38
This is not a duplicate of #1352, FYI; they are two separate issues. I am also experiencing both, but I opted to report this one (the constant crashes) up-stream instead of here.

Also, just to clarify, Apple Silicon is no longer beta — we're not experiencing these issues on the DTK, or on a beta OS; this is on release-software, on release-hardware, that's shipped to hundreds of thousands of users! Extremely not "beta." (That said, apparently Firefox's upstream support for ARM *is* still "beta", very sadly. Just clarifying.)

@funkymonkeyboy Feel free to CC yourself here; also feel free to help us figure out how to reproduce it, if you can. https://bugzilla.mozilla.org/show_bug.cgi?id=1678443

**Comment by ELLIOTTCABLE** [comment] 2020-11-27 18:51
Over in #1352, it was suggested to try:

> This ("Open `about:config` and change `javascript.options.wasm` to false.") does not seem to prevent uBO from using wasm on my side. Toggling [`disableWebAssembly`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#disablewebassembly) to `true` does work reliably though.

I managed to disable Firefox's `javascript.options.wasm`, but that didn't fix the crashes. I *was not* able to disable uBlock's own `disableWebAssembly`, because attempting to open uBlock's settings page reliably and instantly crashes Nightly.

Is there a way I could directly set that configuration value without opening the settings-page? (=

**Comment by gorhill** [comment] 2020-12-13 17:31
> I managed to disable Firefox's `javascript.options.wasm`

As pointed out a bit later in that same bug, you need to also toggle `javascript.options.wasm_trustedprincipals` to `false`.
