### ISSUE TITLE
"Save Page As..." fails

### ISSUE THREAD

**Issue by alice0775** [uBlockOrigin/uBlock-issues#2053] opened 2022-03-15 10:52 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] using a new, unmodified browser profile

### Description

"Save Page As..." fails

### A specific URL where the issue occurs

`https://ncode.syosetu.com/n5530cf/29/`

### Steps to Reproduce

1. Start Firefox98 or Nightly100.0a1 with clean new profile
2. Install this addon from amo `https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/`
3. Open `https://ncode.syosetu.com/n5530cf/29/`
4. "Save Page As..." from menu or context menu

### Expected behavior

The download should complete successfully.

### Actual behavior

The download fails. I must retry from download panel.

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 100
filterset (summary): 
  network: 82054
  cosmetic: 41560
  scriptlet: 16512
  html: 627
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    ublock-filters: 30899-29, 29m
    ublock-badware: 3976-3, 29m
    ublock-privacy: 204-0, 29m
    ublock-abuse: 72-0, 29m
    ublock-unbreak: 1739-0, 29m
    easylist: 64155-596, 29m
    easyprivacy: 26685-572, 29m
    urlhaus-1: 10713-1, 29m
    plowe-0: 3671-2, 29m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 2640 ms
  maxAssetCacheWait: 983 ms
```
</details>

**Comment by mapx-** [comment] 2022-03-15 11:05
I disabled uBO completely from FF, the download fails as well

**Comment by gorhill** [comment] 2022-03-15 14:11
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/986>?

See <https://bugzilla.mozilla.org/show_bug.cgi?id=1445211>.

**Closed** 2022-03-15 18:09 UTC
Labels: duplicate
