### ISSUE TITLE
Every click produces an image instead of the element to actually block

### ISSUE THREAD

**Issue by Nazosan** [uBlockOrigin/uBlock-issues#1961] opened 2022-02-04 05:10 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

I believe this is actually an intentional mechanism from website designers targeting ad blockers.  I've been seeing this on more and more websites recently.  Basically when you try to pick a specific element to get rid of it seems to work, but grabs some image file (a .jpg, .png, etc etc, usually with a similar sort of filename like the one in the example being "skybox.")  Even if you click create and block that image file, it still just shows up again the next time you try to create a filter.  In most cases you can block that image as many times as you want with it never going through (so it's not just a single layer but some kind of mechanism that is able to loop or trick it into always thinking it's there even if it's not actually.)  So far it has mostly been a minor annoyance, but I wanted to pass this along in case it really is a mechanism specifically being used to try to stop ad blockers (or at least how most of us end users use them.)  This particular example is basically harmless, but it could lead to effectively making it impossible for most of us to use the blocking mechanism.  (Of course someone who knows enough to delve into the actual code or using the element inspectors can surely find it manually, but, unfortunately, most of us end users can't really do that.)  I mostly just want to pass this along just in case they have found some mechanism that can currently make using such tools for end users to actually block ads impossible, though I don't know if it's on purpose or not (but then with the filenames being stuff like "skybox" and etc it sounds intentional to me.)

In the example URL I provided I was trying to remove the message about cookies at the top.  There was no actual option to reject and I did not wish to accept.  This particular message was actually small and not particularly in the way, but it covers some text so it was bugging me.  Not important in this specific case, but I've seen other websites use it for much larger and more obnoxious elements in the past few days (sorry, I don't remember their URLs to give a better example.)  In this particular case, attempting to "pick" the cookie warning box at the top produces a URL to block a "skybox.jpg" image which doesn't even seem to be visible.  Subsequent attempts to "pick" the warning box again produce the same skybox.jpg file instead of the actual element that displays the box.

Sorry if this is in the wrong section.  It was unclear to me and I simply wanted to pass it along.  (I do not have a reddit account, nor do I wish to create one.)

### A specific URL where the issue occurs

https://blog.marekrosa.org/2022/01/space-engineers-warfare-2-broadside.html

### Steps to Reproduce

1.  Click on uBlock Origin icon and select the "pick" tool.
2.  Attempt to pick certain popup/blocking/etc elements on certain sites.
3.  Block the image file that it picks.
4.  Attempt again to pick the element from before.

### Expected behavior

It should provide the actual section/etc to block (eg often a div I think) for blocking but instead gets an image the user can't even see.

### Actual behavior

Doesn't allow one to pick the actual element.

### uBlock Origin version

1.40.8

### Browser name and version

Google Chrome Version 97.0.4692.99 (Official Build) (64-bit)

### Operating System and version

Windows 10 Professional x64 & Windows 8.1 Professional x64 (two computers)

**Comment by gwarser** [comment] 2022-02-04 10:45
It should be fixed in dev build - https://github.com/gorhill/uBlock/commit/ebaa8a8bb28aef043a68c99965fe6c128a3fe5e4

**Closed** 2022-02-04 10:54 UTC

**Comment by gwarser** [comment] 2022-02-04 10:57
> In the example URL I provided I was trying to remove the message about cookies at the top.

It's blocked by "Fanboy’s Annoyance" `/cookienotice.` filter.

**Comment by gorhill** [comment] 2022-02-04 12:26
It's not a bug, you have to select the proper filter from the list of suggested filters to accomplish what you want. The commit linked to merely pick a different candidate among all of the available one, that does not change that utlimately you have to ensure the proper candidate is picked according to what you want to do.

**Comment by Nazosan** [comment] 2022-02-04 13:31
Sorry if I'm misunderstanding what you're saying on that last post, but it doesn't give you any choices.  When you pick the box area for the notice it only shows the image file as the thing to block.  There are no sliders or anything else to select anything different.  On the ones I tried the non-existent image was covering the areas I was trying to remove and I couldn't click through it to select the box or anything else.

Anyway, if it's already fixed that's cool.  I'm using the app store version, so I'll just have to wait for it to propagate.  Right now I'm not seeing this on many sites and it's usually on harmless stuff, so it's not a big rush thing for me.

**Comment by gorhill** [comment] 2022-02-04 13:47
> you pick the box area for the notice

I am not able to reproduce a notice -- including when using VPN for Sweden.

**Comment by Nazosan** [comment] 2022-02-04 15:00
Huh.  That is quite odd then.  I can't really explain it:
![SkyboxSample](https://user-images.githubusercontent.com/13072654/152551240-51e40baa-389c-46fc-8c57-20772d649c02.jpg)

**Comment by gorhill** [comment] 2022-02-04 15:02
In your screenshot, I can see another candidate filter offered by the picker, in the "Cosmetic filters" section. Just try this other one and see if it accomplish better what you want.

**Comment by Nazosan** [comment] 2022-02-04 15:04
Sorry, I added an edit.  It does work that way.  I would swear in the past I didn't have to manually click on the separate part for it to offer such an option, but once I click the part below cosmetic filters I get the correct options.

**Comment by gorhill** [comment] 2022-02-04 15:11
In the past uBO would select the cosmetic filter by default instead of the network one. This was changed by mistake at some point and the network filter became selected by default. Now in the next release the picker will again select the cosmetic filter by default.

Regardless, in the end, users have to ensure that the proper filter candidate is selected according to what they want, uBO just conveniently picks one among all those offered, but it can't read mind about what you are trying to do. I posted a video a long time ago about this (linked also in the documentation): <https://www.youtube.com/watch?v=8TvCGWwQr5o>. In short, don't use the _Create_ button immediately, pick the best candidate which match the result you want, use _Preview_ to confirm.

**Comment by Nazosan** [comment] 2022-02-04 15:57
Yeah, it all makes perfect sense now.  Actually, I didn't even realize you could click between those at all so I learned something useful.  I suppose some sort of clearer visual indicator those are cliclable might lead to less user confusion (they look like plain text.)  Just a thought.  Either way I think it is safe to say all confusion is cleared up now.  Thanks for your patience.
