### ISSUE TITLE
Mobile UI improvements

### ISSUE THREAD

**Issue by Serkan-devel** [uBlockOrigin/uBlock-issues#498] opened 2019-03-31 18:11 UTC
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ x] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [ x] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I recall that there were issues raised by @shytikov about the relatively clunky user experience when using ublock on firefox for android as in [this issue thread](https://github.com/gorhill/uBlock/issues/1890).

Later, @kazzqik has made a redesign which was more suitable for usage, but would have look nice on the desktop as well. The UI that was proposed looked overall better than the current upstream UI.

Howerver the changes were held back by upstream due to the fear that some people might dislike it.

I think only a few people might find the change bad, but most of the comments except the maintainer find the usability improvements better anyways.

### A specific URL where the issue occurs

Url of the browser extension

### Steps to Reproduce

1. Install ublock on firefox for android
2. open ublock
3. try to edit settings or manager filters this way

### Expected behavior:

It's easier to manager on mobile

### Actual behavior:

It requires zooming in and out of the screen to manage all settings on a smaller screen

### Your environment

* uBlock Origin version: 1.18.10
* Browser Name and version: Firefox 65.0.1
* Operating System and version: Android 7.1.2

**Comment by uBlock-user** [comment] 2019-03-31 18:25
Duplicate of https://github.com/gorhill/uBlock/issues/1890

**Closed by uBlock-user** 2019-03-31 18:25 UTC

**Comment by Serkan-devel** [comment] 2019-04-01 13:23
@uBlock-user  Well, yeah 
![image](https://user-images.githubusercontent.com/16866642/55330730-0e192c80-5492-11e9-9bc5-9f523ade39b6.png)

**Comment by Serkan-devel** [comment] 2019-04-01 13:24
has it been gridlocked?

**Comment by uBlock-user** [comment] 2019-04-01 17:22
The issue there is still opened, no need to open it again for the second time, hence closed.

**Comment by ghajini** [comment] 2019-04-01 19:00
UI of ublock origin firefox android should resemble like new androids material design and not old style

**Comment by Serkan-devel** [comment] 2019-04-02 06:30
Yes it might be open, but it has been disabled for most users. You might be able to comment, but around 95% of the users there can't comment on that issue thread anymore, hence the screenshot.

Also to note at the older ublock issue tracker: https://github.com/gorhill/uBlock/issues/3726
> Issue tracker here is deprecated.

> Reason: the new issue tracker allows me to grant full permissions to volunteers in processing issues without having to grant full commit rights to code repository.

**Comment by uBlock-user** [comment] 2019-04-02 07:37
You and the rest here can comment here not that it's going to change anything by commenting, but doesn't need to be kept open to comment as this is still a duplicate.

> Also to note at the older ublock issue tracker

Tracker is deprecated, not the issues, also deprecated only for submitting issues. The issues there are still to be considered.

**Comment by gorhill** [comment] 2019-04-02 14:04
The reason I refused the changes were because the [guidelines](https://github.com/gorhill/uBlock/issues/1890#issuecomment-343737201) here were not respected -- when I tried the fork many things were broken and required code changes. Afterward, over time, this is the approach I have taken, incremental changes so as to not break everything -- no grand redesign. I will keep doing so to address usability issues in small screens, as time allows.

**Comment by Grossdm** [comment] 2019-05-20 18:38
@uBlock-user I hope this is not too obvious a question, but I wonder if either it is possible or has been tried to migrate the issues in the old issue tracker to the new one.
It would seem that this could help with some of the legacy or transitional concerns that arise.

Just a passing thought, trying to help.

Many thanks to everyone who contributes to uBlock and its related projects!

**Comment by uBlock-user** [comment] 2019-05-20 18:43
> but I wonder if either it is possible or has been tried to migrate the issues in the old issue tracker to the new one.

Possible ? Yes. With the help of a github option called Transfer Issue. 

Will it happen ? Upto to @gorhill. He's the maintainer of the old tracker.

**Comment by Grossdm** [comment] 2019-05-20 20:36
@uBlock-user,
Thank you for your prompt reply.

If contributors such as yourself think this might be helpful, perhaps you could suggest it to @gorhill. 

Thanks again.

**Comment by bojovyletoun** [comment] 2022-06-22 11:13
On mobile devices: Would it be possible to bring back "logger button" to the popup? It is really useful for me in the popup. I use it really frequently (every browser session) and this is extremely longer path to open it ended with looking up for the tiny blue "logger" title hidden in the text.  . 6 taps instead 4 and also keeps Dashboard opened on the unused tab Support., rather than my filters or my rules.
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools #

In the commit I saw the logger button (with class .mobile) has display: none
