### ISSUE TITLE
uAssets commit included in released version is not recorded since 1.45.3b1

### ISSUE THREAD

**Issue by rathann** [uBlockOrigin/uBlock-issues#2499] opened 2023-02-17 10:45 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Since commit https://github.com/gorhill/uBlock/commit/17590c5a0c80838fced07ad00f804415c7315efa the uAssets commit included in a release is no longer recorded. Before, I could follow the uBlock tag (say, 1.45.2) and find out which exact uAssets commit was referenced in the submodule. This makes building a uBlock Origin package that matches what you release in github releases or at addons.mozilla.org for a Linux distribution unnecessarily hard.

It'd be best if you could tag the uAssets repo with the corresponding uBlock Origin release tag or provide some other way to pin down the exact uAssets commit used in a given release.

### A specific URL where the issue occurs.

https://github.com/uBlockOrigin/uAssets/

### Steps to Reproduce

1. Download released uBO source tarball from github, e.g. https://github.com/gorhill/uBlock/archive/1.47.0/uBlock-1.47.0.tar.gz
2. Unpack the source (`tar xzf uBlock-1.47.0.tar.gz`)
3. Run `tools/pull-assets.sh`

### Expected behavior

The uAssets source corresponding to the released version is pulled.

### Actual behavior

The current uAssets git master source is pulled.

### uBO version

1.47.0

### Browser name and version

Firefox 110

### Operating System and version

Fedora 37

**Comment by gorhill** [comment] 2023-02-17 13:58
Whoever is free to do something about this, personally I prefer to not spent time on this.

**Comment by gorhill** [comment] 2023-05-01 13:31
Duplicate of #1535,

**Closed by gorhill** 2023-05-01 13:31 UTC
Labels: enhancement, help wanted
