### ISSUE TITLE
Cookie Informer

### ISSUE THREAD

**Issue by Polpite** [uBlockOrigin/uBlock-issues#231] opened 2018-09-19 11:41 UTC
Firefox 62 64 bit, Windows 8.1 64bit and Windows 10 64 bit.

ALERT! UBlock Origin installs a cookie informer when we parametrized the extension in the browser! Detectable by CCleaner.

Thanks.

**Comment by gwarser** [comment] 2018-09-19 11:52
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/227

**Closed by gwarser** 2018-09-19 11:52 UTC
