### ISSUE TITLE
uBO does not "see" exception created into the logger

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uBlock-issues#2507] opened 2023-02-22 14:29 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

uBO does not "see" exception created into the logger

### A specific URL where the issue occurs.

cnn.com, other pages

### Steps to Reproduce

- open the logger
- go to `cnn.com`
- go into logger, select only `xhr` blocked requests
- click one of the xhr rows, create this exception filter: `@@*$xhr,domain=cnn.com`
- refresh the page (F5) => `xhr` requests still blocked
- ctrl-F5 => `xhr` requests still blocked
- go into "my filters", add a newline before `@@*$xhr,domain=cnn.com` => refresh the cnn page => finally the `xhr` requests are whitelisted

### Expected behavior

`xhr` requests to be whitelisted after creating the exception

### Actual behavior

whitelisting is ignored

### uBO version

last uBO dev build, other old versions

### Browser name and version

chrome, firefox last / old versions

### Operating System and version

windows 10

**Comment by garry-ut99** [comment] 2023-02-22 15:20
I can reproduce, but it seems a duplicate of: https://github.com/uBlockOrigin/uBlock-issues/issues/732, because doing the last step ("add a newline before") fixes https://github.com/uBlockOrigin/uBlock-issues/issues/732 as well and `badfilter` works just like `@@*$xhr,domain=cnn.com`

Additional info:
- the logger also says: "filter not found in any of enabled filter lists", 
then after the last step ("add a newline before"), when the filter works, 
the logger correctly says that the filter found in "My Filters"
- also an alternative fix instead of "add a newline before": 
despite F5 or CTRL+F5 doesn't fix the bug, closing and reopening the tab (`cnn.com`) does work

**Closed** 2023-02-23 07:50 UTC
Labels: fixed
