### ISSUE TITLE
Add $path modifier of Adguard or any equivalents of this

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBlock-issues#1690] opened 2021-08-21 07:20 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

https://github.com/AdguardTeam/CoreLibs/issues/124#issuecomment-846907007
The modifier is useful at least on Japanese sites and `blog.livedoor.jp` is the best example where thousands of different structure of pages share the same domain. This resulted in tons of verbose filters in my personal lists to avoid false positive, otherwise a filter working for a page breaks another page. An actual case reported to me (`https://jbbs.shitaraba.net/bbs/read.cgi/internet/25463/1598352715/206`) is that `blog.livedoor.jp###containerWrap > #container > .blog-title-outer + #content.hfeed` made for `http://blog.livedoor.jp/sexykpopidol/` breaks `http://blog.livedoor.jp/kknao81/`. Currently for this very reason I ignore some ad-placeholder on `blog.livedoor.jp` in AdGuard Japanese, which can fully be resolved if the modifier becomes available.

(Not worth your time but in `https://blog.livedoor.com/ranking/` you can pick many `blog.livedoor.jp` sites with different structure each.)

### A specific URL where the issue occurs

blog.livedoor.jp

### Steps to Reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### uBlock Origin version

1.37.2

### Browser name and version

Irrelevant

### Operating System and version

Irrelevant

**Comment by uBlock-user** [comment] 2021-08-21 07:37
We wouldn't need to use `$shide` to partially disable cosmetic filtering on google shopping pages(https://github.com/uBlockOrigin/uAssets/issues/9642, https://github.com/uBlockOrigin/uAssets/issues/9694)  if we could use `$path` to narrow google product ads to google search engine pages only.

**Comment by felix-22** [comment] 2021-08-21 10:24
Related: https://github.com/gorhill/uBlock/issues/3275

**Comment by gorhill** [comment] 2021-08-21 12:04
> An actual case reported to me

This works now without having to further complicate the code base and neither have to wait:

    blog.livedoor.jp##link[rel="alternate"][href*="sexykpopidol"]:upward(html) #containerWrap > #container > .blog-title-outer + #content.hfeed

**Comment by Yuki2718** [comment] 2021-08-21 12:14
@gorhill I already fixed the issue and the point is not that I can't address them within the current arsenal. I can fix each case, but every time the rules become more complex and verbose.

**Comment by Yuki2718** [comment] 2021-08-21 12:25
But okay it seems `link[rel="alternate"][href*=...]:upward(html)` can always be used in case of `blog.livedoor.jp`. Since in the current uBO procedural engine will only be triggered if the first matching node exists, it can hardly be a matter. How about another point made by @uBlock-user ?

**Comment by gorhill** [comment] 2021-08-21 12:34
I could add a procedural operator like so:

    blog.livedoor.jp##:match-location(/sexykpopidol) #containerWrap > #container > .blog-title-outer + #content.hfeed

This way implementation becomes quite trivial without having to further complicate the code base for all cosmetic filters. The disadvantage is that this is a procedural cosmetic filters, **but** it's opened to optimisation, i.e. a filtering engine could have special treatment for such filter in order to have them injected early along with other plain CSS selector-based filters.

Also an advantage is that we just keep reusing the same now familiar operator-based approach, which was the entire point of these operators, that is easy to extend with little to no impact on codebase complexity.

**Comment by uBlock-user** [comment] 2021-08-21 12:38
Would it be possible to have whitelist approach with `:match-path` ? I would like simply skip a path such as `/shop` at google/bing.

**Comment by gorhill** [comment] 2021-08-21 12:39
If argument to `:match-path()` can be a regex, than you can just use a negative lookahead?

**Comment by Yuki2718** [comment] 2021-08-21 12:43
Sounds great! The reason AG use `[path=...]` is that they already use a similar `[app=...]` but probably they can transform `[path=...]` to `:match-path()` just like they do for other filters, so I have no problem.

**Comment by uBlock-user** [comment] 2021-08-21 12:44
`:not(:match-path(/shop))` would do.

**Comment by gorhill** [comment] 2021-08-21 12:50
Trying to come out with a name I won't feel like changing in the future, please advise. Should it be:

    `:matches-path(...)`
    `:match-path(...)`
    `:path-has-text(...)`

Keep in mind this is the list of supported operators for now: <https://github.com/gorhill/uBlock/blob/b44d9219c321cf42379b1b7e8711728321ef0a16/src/js/static-filtering-parser.js#L1818-L1838>. Consistency is important.

**Comment by uBlock-user** [comment] 2021-08-21 12:57
Third can be changed to `:has-path()` as `:path-has-text()` sounds un-necessarilly longer.

**Comment by Yuki2718** [comment] 2021-08-21 13:04
> Trying to come out with a name I won't feel like changing in the future, please advise. Should it be:
> 
> * `:matches-path(...)`
> * `:match-path(...)`
> * `:path-has-text(...)`
> * ?
> 
 Consistency is important.

I'm not English-native but it appears `match-path` is inconsistent with `matches-css`.

**Comment by gorhill** [comment] 2021-08-21 13:07
I am also not English-native, and I wonder whether `:matches-css()` was the right choice, so I wouldn't want to repeat the same mistake, and if this was a mistake, I can always deprecate `:matches-css()` and instead make `:match-css()` official. I often make mistakes with those trailing `s` in English, so I am not a reference on when to properly use these.

**Comment by uBlock-user** [comment] 2021-08-21 13:09
Both are fine, no need to change anything regarding `:matches-css()`

**Comment by gorhill** [comment] 2021-08-21 14:09
`:matches-path()` will be in next dev build, 1.37.3b11.

If you look at the commit, you can see the required changes to the code were very little (even with an opportunistic unrelated changes in there), meaning risk of regression is virtually zero -- so I far prefer this approach than supporting a new spec which would require a **whole** lot of work and assuming I would be fine with all the specs, I would work on this only in a far, undetermined future, with a lot of potential regression (including in performance) as a result.

**Comment by uBlock-user** [comment] 2021-08-21 15:30
@gorhill on `https://www.google.com/search?q=Under+Armour+Sportstyle+Logo+Tank&newwindow=1&sxsrf=ALeKk012vqIPWbQDpDef2IwbreyIoADXPw:1627344963115&source=lnms&tbm=shop&sa=X&ved=2ahUKEwin-s-z_IHyAhVPUxUIHW_cCCQQ_AUoAXoECBMQAw&biw=2560&bih=1297`

Filter `www.google.*##:not(:matches-path(/\/search\?q\=\*tbm=shop|\/shopping/)) [href^="/aclk"][href$="adurl="]:not(>  *:upward([class^="sh-sr__shop-result-group"])):upward(3)` gets applied even though we're exclusing `tbm=shop` from the path via `:not`.

To repro add the following filters -- 

```
www.google.*##:not(:matches-path(/\/search\?q\=\*tbm=shop|\/shopping/)) [href^="/aclk"][href$="adurl="]:not(>  *:upward([class^="sh-sr__shop-result-group"])):upward(3)
www.google.*#@#[href^="/aclk"][href$="adurl="]:not(:scope > :upward([class^="sh-sr__shop-result-group"])):upward(3)
@@||www.google.*/search?q=*tbm=shop$shide,badfilter
```
 and then visit `https://www.google.com/search?q=Under+Armour+Sportstyle+Logo+Tank&newwindow=1&sxsrf=ALeKk012vqIPWbQDpDef2IwbreyIoADXPw:1627344963115&source=lnms&tbm=shop&sa=X&ved=2ahUKEwin-s-z_IHyAhVPUxUIHW_cCCQQ_AUoAXoECBMQAw&biw=2560&bih=1297`

Am I falling short somewhere ?

**Comment by gorhill** [comment] 2021-08-21 15:41
I missed [this comment](https://github.com/AdguardTeam/CoreLibs/issues/124#issuecomment-851904545):

> I guess we'd better cover path+query right away and not wait for it to be requested from us.

So I went with path only, but I will modify to match against path + query.

**Comment by uBlock-user** [comment] 2021-08-21 16:09
Still happens on `1.37.3b13` build as per the above repro...

**Comment by gorhill** [comment] 2021-08-21 16:24
You regex is:

    /\/search\?q\=\*tbm=shop|\/shopping/

You are escaping the `*`, meaning you are trying to match a literal asterisk in the URL, while there is no such character. Is this more what you intended?

    //search\?q=.*?tbm=shop|/shopping/

**Comment by uBlock-user** [comment] 2021-08-21 16:28
`tbm=shop` is not always accompanied with `?` sometimes it's `&`.

**Closed** 2021-08-21 16:36 UTC
Labels: enhancement

**Comment by gorhill** [comment] 2021-08-21 16:37
> `tbm=shop` is not always accompanied with `?` sometimes it's `&` btw...

The `?` in `q=.*?tbm=shop` is not a literal `?`, `.*?` means non-greedy match to make regex faster.

**Comment by uBlock-user** [comment] 2021-08-21 16:45
Yeah, I realised it after I commented, not used to crafting regexes everyday, thanks for helping out.

**Comment by eladkarako** [comment] 2022-05-18 12:01
not sure if this was answer before.  
trying to specify a hiding rule to a specific sub-domain,  
without matching any of the sub domains.

this won't work:  
`https://example.com##:matches-path(/^/$/) .ads:upward(div)`  
or  `||example.com##:matches-path(/^/$/) .ads:upward(div)`

and this matches all other subdomains as well.

`example.com##:matches-path(/^/$/) .ads:upward(div)`

is there a way to limit the hiding rule to just `example.com` alone?

(`subdomain.example.com` should be unaffected).

**Comment by gorhill** [comment] 2022-06-03 16:51
> this won't work

You are using invalid syntax.

> subdomain.example.com should be unaffected

Exclude `subdomain.example.com`:

    example.com,~subdomain.example.com##...
