### ISSUE TITLE
Regression Bug: Element Picker & Zapper does not work when Cosmetic Filtering for site is disabled

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uBlock-issues#25] opened 2018-04-30 14:40 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When cosmetic filtering is either globally disabled, or disabled for a specific domain, the Element Picker and Element Zapper no longer work. I remember this functionality working in previous builds so I went back and tested old releases and it looks like the last release this feature worked on was 1.14.16. All releases since 1.14.18 appear to have the regression bug present.

### A specific URL where the issue occurs

https://www.nytimes.com

### Steps to Reproduce

1. Load https://www.nytimes.com & verify cosmetic filters are enabled for the site and use the element picker tool or element zapper to verify it is working.
2. Toggle cosmetic filters off and reload https://www.nytimes.com
3. Verify that the element picker and zapper now fail to load with cosmetic filters turned off.

### Expected behavior:

On 1.14.16 and below, the element picker worked when cosmetic filters was disabled, this was useful for filter testing.

### Actual behavior:

Cosmetic filtering disabled causes the Element Picker and Element Zapper to not work.

### Your environment

* New Chrome Test Profile with no other extensions installed
* Default Filters enabled, no settings changed from uBlock default settings.
* uBlock Origin version: I tested that the Element Picker works with cosmetic filtering disabled on 1.14.14 & 1.14.16
* uBlock Origin version: I tested that the Element Picker does NOT work with cosmetic filtering enabled on 1.14.18, 1.14.20, 1.15.8, 1.15.8, 1.15.10, 1.15.18, 1.16.0, 1.16.2, & 1.16.3b1
* Browser Name and version: Chrome 66.0.3359.139
* Operating System and version: 64bit Windows 10

**Comment by uBlock-user** [comment] 2018-04-30 14:48
Duplicate of https://github.com/gorhill/uBlock/issues/3212

**Closed by uBlock-user** 2018-04-30 14:48 UTC
Labels: duplicate
