### ISSUE TITLE
the extension blocks the start page google

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uBlock-issues#1973] opened 2022-02-11 18:13 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

with enabled Pause network activity until all filter lists have run the extension blocks the start page for a fraction of a second, and then loads it. if you disable this setting, the page loads as usual. in edge it does not help to get rid of the problem, works only in google chrome

### A specific URL where the issue occurs

google.ru

### Steps to Reproduce

make it home page google.ru
close browser
open browser

### Expected behavior

page should load without error

### Actual behavior

I get an error after which the page starts to load

### uBlock Origin version

1.41.2

### Browser name and version

google chrome 98

### Operating System and version

windows 11 x64

**Comment by gorhill** [comment] 2022-02-11 18:17
> with enabled Pause network activity until all filter lists have run

You will have to disable this setting if you do not want the current behavior.

**Comment by uBlock-user** [comment] 2022-02-11 18:17
If the filter lists do no load in time, network requests will be suspended. Disable _Suspend network activity until all filter lists are loaded_

**Comment by gorhill** [comment] 2022-02-11 18:21
Closing as "by design", un-check the _"Suspend network activity until all filter lists are loaded"_ setting if the current behavior is not wanted.

**Comment by gorhill** [comment] 2022-02-11 18:23
For more details, see [Browser launch](https://github.com/gorhill/uBlock/wiki/uBlock-Origin-works-best-on-Firefox#browser-launch) -- what you are seeing is an attempt at mitigating Chromium not being able to wait for extension to be ready before firing network requests.

**Comment by electrifying** [comment] 2022-02-11 18:37
> > with enabled Pause network activity until all filter lists have run
> 
> You will have to disable this setting if you do not want the current behavior.

I did that, but it only fixes the problem in chrome.  it doesn't work in Microsoft edge browser.

**Comment by gorhill** [comment] 2022-02-11 18:38
What version of uBO did you use for Edge browser? I think the reload was unconditional with uBO 1.40.8, this has changed in 1.41.2 to be only if network requests were seen, and now there is a setting to disable the behavior.

**Comment by gwarser** [comment] 2022-02-11 18:40
Edge was updated to 1.41.0

**Comment by dialexg91** [comment] 2022-02-12 19:19
> > with enabled Pause network activity until all filter lists have run
> 
> You will have to disable this setting if you do not want the current behavior.

didn't work, and the issue has happened on Facebook too, this is horrible, changing to Adguard right now

**Comment by gorhill** [comment] 2022-02-13 15:27
Whoever is suffering the reported issue, please check with the dev build whether this works to their satisfaction. The behavior has been changed to be disabled by default in Chromium-based browsers. If you enabled it, check whether it's not better, as there is no more blocked connections, but just redirected ones to an empty resources.

The dev build to use to verify the fix is [1.41.3b2](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) or above, but the Chrome store may take a while before making this version available to all.

**Comment by LevelZero-dev** [comment] 2022-02-16 10:29
On Edge v98.0.1108.43 we had this same issue of the startup page being blocked with 1.41.2 of uBlock Origin.
Installing 1.41.3b2 does seem to resolve this issue in our environment.

**Comment by Jurgenner** [comment] 2022-02-16 10:32
Can also confirm this to be working with Chrome 98.0.4758.82 and uBlock 1.41.3b2. The error is quite a major PITA in a work environment setting, so hopefully the main release gets updated soon.

Thank you for your work with the extension for gorhill and the rest of uBlock team!

**Comment by gorhill** [comment] 2022-02-18 15:34
The fix is in 1.41.4, the Chrome Web Store is just taking long to review the submission.

**Comment by Jurgenner** [comment] 2022-02-23 14:37
> The fix is in 1.41.4, the Chrome Web Store is just taking long to review the submission.
Web Store has updated the version today and can confirm 1.41.4 to work. Thank you @gorhill!

**Closed** 2022-02-23 14:43 UTC
Labels: something to address
