### ISSUE TITLE
abort-on-property-read.js does not work in Quantum

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBlock-issues#413] opened 2019-02-05 18:35 UTC
Firefox 65
uBlock Origin v1.18.4
EasyList
RU AdList
https://tv.yandex.ru/
https://i.imgur.com/dDmrQBk.jpg
`tv.yandex.ru##+js(abort-on-property-read.js, Element.prototype.attachShadow)` not work in Quantum, while in Google Chrome is fine.

**Comment by uBlock-user** [comment] 2019-02-05 18:50
because of website's CSP ?

![](https://i.gyazo.com/32a4f752066b5359f693d02f753dd3b5.png)

**Comment by uBlock-user** [comment] 2019-02-05 19:06
See - https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by uBlock-user** [comment] 2019-02-05 19:10
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/235

**Closed by uBlock-user** 2019-02-05 19:10 UTC
