### ISSUE TITLE
ClamAV Detect as CoinMiner

### ISSUE THREAD

**Issue by antuketot76** [uBlockOrigin/uBlock-issues#700] opened 2019-08-10 17:54 UTC
Is this false positive by [ClamAV](https://www.clamav.net/) ?
For both Firefox and TOR Browser

![image](https://user-images.githubusercontent.com/33280865/62825061-b1b4df00-bbe0-11e9-8ded-51d2ff255d85.png)

### Your environment

* uBlock Origin version: uBlock Origin v1.21.2
* Browser Name and version: 
![image](https://user-images.githubusercontent.com/33280865/62825098-6bac4b00-bbe1-11e9-8e35-f18128d6bf85.png)
![image](https://user-images.githubusercontent.com/33280865/62825143-f68d4580-bbe1-11e9-9785-a25867b6c6ba.png)

* Operating System and version:
Manjaro Linux XFCE (64Bit)
Kernel Linux 4.1.9.62-1

**Comment by uBlock-user** [comment] 2019-08-10 17:56
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/698

**Closed by uBlock-user** 2019-08-10 17:56 UTC
