### ISSUE TITLE
[IPv6-only + NAT64] IPv4-only sites initially fail to load in a NAT64 environment

### ISSUE THREAD

**Issue by kotarou3** [uBlockOrigin/uBlock-issues#450] opened 2019-03-07 06:43 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Currently my internet connection consists of:
- *No* IPv4 address
- Globally routable IPv6 address
- NAT64 and DNS64 to access IPv4-only resources

When initially accessing a IPv4 only website (e.g. https://www.westpac.com.au), the page fails to load with a "Server Not Found" and "Hmm. We’re having trouble finding that site." error.

Refreshing the page then loads the page properly (though v4 resources from different domains may fail to load - refreshing again usually fixes those too).

This happens in a clean profile of Firefox v65, where uBlock Origin is the only addon installed with default settings.

Wireshark/tcpdump shows that Firefox in fact successfully opens a TCP connection to the website, but then ~4s later shuts it down cleanly without any actual data traffic.

This seems related to the "Disable pre-fetching (to prevent any connection for blocked network requests)" setting, since disabling that fixes the issue.
However, not having uBlock Origin installed but manually setting `network.prefetch-next` to `false` does not cause the issue.

### A specific URL where the issue occurs

https://www.westpac.com.au, which would resolve into something like 64:ff9b::13.32.161.141 aka 64:ff9b::d20:a18d under NAT64/DNS64.
(Accessing the NAT64 IP directly works fine)

### Steps to Reproduce

0. Make sure you have no IPv4 address assigned to your network interface, and your connection supports NAT64/DNS64
1. Create a new Firefox profile
2. Install uBlock Origin
3. Try to access a v4 only website (e.g. https://www.westpac.com.au)
4. Observe it fails to load
5. Refresh the page
6. Observe it now loads
7. Further refreshes also continue to load the page

To speed up reproducing the bug and not have to create a new profile each time, set Firefox to clear caches on shutdown and not remember history (so it acts like incognito mode). Then simply restarting Firefox and accessing the website again is enough to trigger the bug.

Disabling the "Disable pre-fetching (to prevent any connection for blocked network requests)" option fixes the bug.

### Expected behavior:

Page to load successfully on first attempt

### Actual behavior:

Page does not load on first attempt, but only subsequent attempts such as via a refresh.

### Your environment

* uBlock Origin version: 1.18.4
* Browser Name and version: Firefox 65.0.1 64bit
* Operating System and version: Debian testing/buster with Firefox installed from unstable/sid

**Comment by uBlock-user** [comment] 2019-03-07 07:11
> set Firefox to clear caches on shutdown and not remember history

That also enables **private browsing mode** which has a Firefox bug associated with it in https://github.com/gorhill/uBlock/issues/3071

I cannot reproduce it on deb build, you may try that.

Duplicate of https://github.com/gorhill/uBlock/issues/3071

**Comment by kotarou3** [comment] 2019-03-07 07:14
It is very much not a duplicate issue, since it happens even without that setting enabled (enabling it just makes it easier to reproduce reliably without the need to recreate a profile).

Are you sure you properly disabled IPv4 before trying to reproduce? Not just disabled in the browser, but actually *not have any IPv4 address assigned* to your network interface

**Comment by uBlock-user** [comment] 2019-03-07 07:17
> Are you sure you properly disabled IPv4 before trying to reproduce? Not just disabled in the browser, but actually not have any IPv4 address assigned to your network interface


Your STR doesn't mention any of that. I do not have IPv6, only IPv4 address so I cannot disable IPv4 under any circumstances otherwise I will lose internet connectivity and if I have to do that, it obviously has nothing to do with uBO because uBO doesn't deal with network interface/ ip ranges.

**Comment by kotarou3** [comment] 2019-03-07 07:22
I stated the IPv6-only part of the issue both in the bug title and description, just not STR. I've added it to the STR as well to make sure it's not missed.

I suspect it might not be a uBO issue, but a Firefox issue, but I need to dig deeper on exactly what is going on first

**Comment by uBlock-user** [comment] 2019-03-07 07:23
Can you reproduce on Chromium ?

**Comment by kotarou3** [comment] 2019-03-07 07:55
Could not reproduce on Chromium.

I've also successfully reproduced the bug without uBO installed, so it's definitely not a uBO bug, so feel free to close this again :)

I've reported directly to Mozilla now: https://bugzilla.mozilla.org/show_bug.cgi?id=1533273

**Comment by uBlock-user** [comment] 2019-03-07 07:59
Did you modify `network.http.speculative-parallel-limit` in about:config ?

**Closed** 2019-03-07 08:07 UTC
Labels: Firefox, external

**Comment by kotarou3** [comment] 2019-03-07 08:10
As part of trying to reproduce the bug without uBO, yes.
But prior to that no.

How does uBO specifically end up setting the property?
1. Enable "Disable pre-fetching" from the UI (actually enabled by default for fresh installs of uBO)
2. This sets the `prefetchingDisabled` user setting: https://github.com/gorhill/uBlock/blob/886c8c2dd72977ee9820f5b1df8d46e6f8567ad9/src/settings.html#L23
3. Which clears the `prefetching` setting in the vAPI: https://github.com/gorhill/uBlock/blob/b9b0c3fba4baf679864345be53b86884e0bb90d8/src/js/ublock.js#L368
4. Which clears `chrome.privacy.network.networkPredictionEnabled`: https://github.com/gorhill/uBlock/blob/138e1bf55866e4a97c2ef192ffb4d6489ff7e498/platform/chromium/vapi-background.js#L231
5. Which sets `network.http.speculative-parallel-limit` to 0: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/parent/ext-privacy.js#56

**Comment by gwarser** [comment] 2019-03-07 09:28
Firefox prefetching related prefs:

```
network.dns.disablePrefetch
network.http.speculative-parallel-limit
network.predictor.enable-prefetch
network.prefetch-next
network.preload
```

uBO uses [privacy/network api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/network#Properties) which toggles these:

```
network.dns.disablePrefetch
network.http.speculative-parallel-limit
network.prefetch-next
```
