### ISSUE TITLE
Have a real cloud sync for the settings and the checked filter lists 

### ISSUE THREAD

**Issue by spamme2** [uBlockOrigin/uBlock-issues#565] opened 2019-05-07 16:05 UTC
### Prerequisites

- [ X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ X] using a new, unmodified browser profile
- [ X] I am running the latest version of uBlock Origin
- [ X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
I have a few computers running with some virtual machines and I create occasionally new ones. Cloud sycing is a fantastic feature for a faster initialization of new virtual machines, above all when you want them to be already prepared with your favorite applications and settings. For this reason I love the cloud sync function of firefox, all my preferred addons are automatically installed and configured ... or better almost all, one of them always requires that I open the setting and click 10 checkboxes to activate many filter lists and finally click the update button. I know there is a manual "cloud storage" feature in uBlock, but as the name says, this is exactly a cloud storage not a sync, because if I uncheck a filter list and check another filter list, this change is not propagated to all instances of firefox in all virtual machines. Moreover the checked filter lists aren't synced between firefox instances, every firefox instance has its own list of the checked filter lists.
I have a dream, that one day when I spawn a new virtual machine and I sign in in firefox, ublock origin syncs automatically also my settings and the list of the checked filter lists. That day would be a fantastic day.

**Comment by uBlock-user** [comment] 2019-05-07 16:20
uBO doesn't have it's own cloud sync, it merely makes it possible to use browser's own cloud sync feature to sync extensions and their data across the services offers by the browser vendor. That's all.

**Comment by uBlock-user** [comment] 2019-05-07 18:39
Duplicate of https://github.com/gorhill/uBlock/issues/3572

**Closed by uBlock-user** 2019-05-07 18:39 UTC
Labels: something to address
