### ISSUE TITLE
Cloud storage autosync option

### ISSUE THREAD

**Issue by CRY3rn** [uBlockOrigin/uBlock-issues#244] opened 2018-09-24 22:12 UTC
I am well aware of the design decision to not have the cloud storage syncing automated to prevent loss of data (https://github.com/gorhill/uBlock/wiki/Cloud-storage). However, I don't think I'm alone in saying that having the option to assume that risk for the benefit of personal convenience would be amazing, especially for users with many devices that have uBlock (and uMatrix) installed.

Maybe have it under the "I am an advanced user" settings?

**Comment by uBlock-user** [comment] 2018-11-19 20:50
Duplicate of https://github.com/gorhill/uBlock/issues/783

**Closed by uBlock-user** 2018-11-19 20:50 UTC
Labels: enhancement
