### ISSUE TITLE
Future of using easylist as default

### ISSUE THREAD

**Issue by max06** [uBlockOrigin/uBlock-issues#738] opened 2019-09-27 10:14 UTC
In the last days we had serious trouble caused by the easylists maintainers by adding generic url parts without domain limitation, affecting many more projects than intended. 

Feedback got ignored, requests to revert the changes rejected. I'm questioning if a small group of people not showing responsibility should be able to destroy parts of the internet, as well as destroying the reputation of innocent companies and projects.

Please read https://github.com/easylist/easylist/issues/4067 for details and think about not enabling those lists per default.

**Comment by gorhill** [comment] 2019-09-27 11:19
I've neutralized the filters for uBO users: <https://github.com/uBlockOrigin/uAssets/commit/e8017aad054c5723cfe831be31fa6a78ae319688>.

**Comment by max06** [comment] 2019-09-27 11:20
Thank you very much for that quick reaction!

I would still think abut keeping the easylists as default in your tool.

**Comment by uBlock-user** [comment] 2019-09-27 11:28
They removed those filters after all -- https://github.com/easylist/easylist/commit/0b2ea95733151178c0815da53a2456fa0ba38e1b

**Comment by max06** [comment] 2019-09-27 11:29
Yes, for now. I'm pretty sure they'll wait some days and try it again then.

**Comment by gorhill** [comment] 2019-09-27 11:30
I want to keep it opened. I went through the discussion thread and I do see an issue.

A filter such as `/v1/events` is obviously way too generic, this should never have been added in the first place, this hightlight there is really an issue. It's difficult to tell exactly why it was [added as a generic filter](https://github.com/easylist/easylist/commit/c543fd6edb3774c1bf301c63b1d47c7459e42654) rather than just for the site which was apparently targeted -- `ozon.ru` (where btw I couldn't see requests matching `/events` on that site).

Such generic filters is likely to cause widespread breakage -- we even had to [`badfilter` generic filters with more targeted keywords](https://github.com/uBlockOrigin/uAssets/blob/e8017aad054c5723cfe831be31fa6a78ae319688/filters/unbreak.txt#L402) because they were causing breakage.

In the big picture, breakage will cause users to disable their blocker, which is a worst outcome than allowing one specific tracking script on one specific web site -- which can be addressed with a well targeted filter.

The list at issue here is EasyPrivacy, not EasyList. A potential replacement is AdGuard Tracking Protection, so we should evaluate whether it can be a replacement if it lowers the likelihood of breakage for uBO users.

**Comment by wachri** [comment] 2019-09-27 11:31
> This thread is being watched by them (as the event logging urls have been changing). Not assuming everyone is in the event logging/tracking business. but most them will be aware of this thread.
>
> I've removed the filters for the time being, 0b2ea95 It'll be reviewed again later.

https://github.com/easylist/easylist/issues/4067#issuecomment-535870849

**Comment by max06** [comment] 2019-09-27 11:34
@gorhill You're absolutely right. Just want to point out that easylist, easyPrivacy and some more are all managed by the same people. And judging by their reaction something like that will probably happen again in any of those.

**Comment by ryanbr** [comment] 2019-09-27 22:38
Some companies have a heavy interest in any filters we add, When issues arise having valid examples of breakages and not just companies just trying to circumvent the list by issuing fake faults. "Feedback got ignored," when you have a thread from many people, you can't address every user comment or question. 

I adjusted the filters twice (based on the sample urls given) before removing the filter. If someone believes we added a filter by accidentally or the filters were overreaching, then having a valid example of these page(s) is broken. But the thread lacked a lot of real world examples, and the examples we did have were already fixed.

This is why we have Issue report forms.

**Comment by gorhill** [comment] 2019-09-28 11:41
> the thread lacked a lot of real world examples

I am going to argue that for generic filters, the burden of proof is reversed and first on filter list maintainers: your generic filters also lacked a lot of real world examples.

There should have been a at least a sufficient commit history to make the case that `/v1/events` was worth converting into a generic, but there was none, it went from no filter to one very generic filter with questionable keywords and with one single case made (in the commit title).

Generic filters need a commit history similar to `/v1/events$domain=[...]` where the list of domains keep growing _over time_, and where eventually the list become large enough to the point it makes sense to entertain whether the specific filter should be converted into a generic one -- and even then depending on the keywords involved it still could be hard to make the case for _genericity_.

**Comment by ryanbr** [comment] 2019-10-01 10:48
Understood. Though any generic filter we add to EL/EP will always have some level possible problematic issues. Some sites would act perfectly fine, where other sites would have issues. Its supplying us the website and example of why its broken so we can then reproduce it. Depending on the breakage, the example given, and/or a recent recent added filter we'll either remove the filter or whitelist the affected site.

In the case of /v1/events filters, we didn't really have many (or any real world testable examples) that weren't already fixed with list updates to the filters. (adding | end of string and specific filter strings).

I probably should've acted sooner, but I wanted to see the breakage (reproduce the fault) in action before making the call, like any other issue report from any other user.

My intention was not to break people web sites, and for that I apologise.

**Closed** 2019-10-01 12:49 UTC
Labels: filterlist, something to address

**Comment by kulfoon** [comment] 2020-04-25 01:23
As for: https://github.com/uBlockOrigin/uBlock-issues/issues/738#issuecomment-536180398, agree, and there is another example of such similiar issue with generic filters in EasyList: https://github.com/easylist/easylistgermany/issues/70 - creating a generic filter for a single website, even though there is no breakage side-effect, but there is a performance degradation side-effect which for example collides with gorhill's efficiency based aproach.

**Comment by kulfoon** [comment] 2020-04-25 16:56
@gorhill, @jspenguin2017, @mapx, @okiehsch, @DandelionSprout, @Yuki2718

**Comment by jspenguin2017** [comment] 2020-04-25 18:54
@kulfoon I don't think that's a problem. The rules looks safe and tokenizable. As for the specific issue, I'll open a new issue in Quick Reports.

**Comment by gorhill** [comment] 2020-04-25 19:04
> there is a performance side-effect which for example collides with gorhill's efficiency based aproach.

I don't see a performance issue with any of the filters added. Adding one single generic cosmetic filter on top of the thousands already being enforced makes no difference performance-wise. The DOM surveyor code has to execute with or without that added generic cosmetic filter, so performance should not be invoked to argue against it.

**Comment by kulfoon** [comment] 2020-04-25 21:43
> gorhill: I don't see a performance issue 

So how you at the same time do see a performance issue here ( as I already mentioned in https://github.com/easylist/easylistgermany/issues/70#issuecomment-618364234 ):

> <details not-open>
> <summary> From uBO:</summary>
> 
> > Generic cosmetic filters are those cosmetic filters which are meant to apply on all web sites.
> > 
> > Though handled efficiently by uBlock₀, generic cosmetic filters may still contribute measurable memory and CPU overhead on some web pages, especially for large and long-lived ones.
> > 
> > Enabling this option will eliminate the memory and CPU overhead added to web pages as a result of handling generic cosmetic filters, and also lower the memory footprint of uBlock₀ itself.
> > 
> > It is recommended to enable this option on less powerful devices.
> 
> ![1](https://user-images.githubusercontent.com/43844449/80094967-75a38d80-8567-11ea-9e77-152404a0425e.gif)
> 
> </details>

How can one see and not see a performance issue at the same time? Perhaps remove the tiptool then? Wtf? Why denying yourself, a hypocrisy or what.

> gorhill: Adding one single generic cosmetic filter on top of the thousands already being enforced makes no difference performance-wise. 

The one generic filter is just an example, it's obvious that there might be already hundreds or thousands of them ( as I already mentioned in: https://github.com/easylist/easylistgermany/issues/70#issuecomment-618364234 ).

Also keep in mind we're talking about genericfilters which cover just a single website, an example (from https://github.com/easylist/easylistgermany/issues/70#issuecomment-617803752):   https://github.com/easylist/easylist/commit/e146cf33959684e6a8da2d51ce48aa313fafb35b https://publicwww.com/websites/Ad_SmartBrokerBar/ I have nothing against generic filters which cover multiple websites.

============================================================

Another example of a person who is denying himself is Khirin, as I wrote in my comment: https://github.com/easylist/easylistgermany/issues/70#issuecomment-618364234:

> kulfoon: A mystery for me is Khirin accepting my point of view (to not fix potential non-existing cases, see: https://github.com/easylist/easylist/issues/5220#issuecomment-613288321), and now he suddenly start denying himself by upvoting his friend's solution: see https://github.com/easylist/easylistgermany/issues/70#issuecomment-618218175 which, the solution, does fix potential non-exisiting cases/pages. 

Is he just supporting his repo's friend, no matter whether his friend is right or not...or what is it, wtf? Another one who is denying himself, a hypocrisy or what, he didn't even reply, is he outargumented or what.

============================================================

Not mentioning uBlock-user, who was hidding comments in one thread: https://github.com/uBlockOrigin/uBlock-issues/issues/971, but not in another: https://github.com/uBlockOrigin/uBlock-issues/issues/984. Again a hypocrisy or what.

============================================================

Guys just stop denying yourself all the fukin time.

See this [cool movie](https://www.youtube.com/watch?v=2q3MPDIA5yc),  see those fukin morons downvoting, one must be an idiot to downvote it.

This is all bullshit, fck it, I'm out, let's everbody [dance now ](https://www.youtube.com/watch?v=F1d41395fVY) =)

**Comment by gorhill** [comment] 2020-04-25 22:49
@kulfoon, one generic cosmetic filter or 10,000 generic cosmetic filters is essentially equivalent, both cases require that the DOM surveyor execute. Only zero generic cosmetic filters prevent the DOM surveyor from executing.

All I see is you wanting to argue for the sake of arguing.

**Comment by uBlock-user** [comment] 2020-04-26 07:21
> Not mentioning uBlock-user, who was hidding comments in one thread: #971,

You don't seem to understand logic at all before calling everyone around here a hypocrite, #981 is the topic where everyone is discussing whether a HOSTS list should be added or not, and then you come out of nowhere, and hijack the thread to start another discussion about yet another HOSTS listing which was already going in #981 in #971 even though #971 was solely opened for reminding gorhill about removing that particular HOSTS file and you even start and pinging 3rd-parties. 

> All I see is you wanting to argue for the sake of arguing.

Yes, and now you're grave digging this old thread and causing uncessary notification spam to me and everybody else, just stop.

**Comment by uBlock-user** [comment] 2020-04-26 07:47
> Not mentioning uBlock-user, who was hidding comments in one thread: #971,

You don't seem to understand logic at all before calling everyone around here a hypocrite, #981 is the topic where everyone is discussing whether a HOSTS list should be added or not, and then you come out of nowhere, and hijack the thread to start another discussion about yet another HOSTS listing which was already going in #981 in #971 even though #971 was solely opened for reminding gorhill about removing that particular HOSTS file and you even start pinging 3rd-parties. 

> All I see is you wanting to argue for the sake of arguing.

Yes, and now you're grave digging this old thread and causing unnecessary notification spam to me and everybody else, just stop.

**Comment by uBlock-user** [comment] 2020-04-26 07:49
> Not mentioning uBlock-user, who was hidding comments in one thread: #971,

You don't seem to understand logic at all before calling everyone around here a hypocrite, #984  is the topic where everyone is discussing whether a HOSTS list should be added or not, and then you come out of nowhere, and hijack the thread to start another discussion about yet another HOSTS listing which was already going in #984  in #971 even though #971 was solely opened for reminding gorhill about removing that particular HOSTS file and you even start pinging 3rd-parties. 

> All I see is you wanting to argue for the sake of arguing.

Yes, and now you're grave digging this old thread and causing unnecessary notification spam to me and everybody else, just stop.
