### ISSUE TITLE
scriptlet doesn't work on `data; base64` script

### ISSUE THREAD

**Issue by MasterKia** [uBlockOrigin/uBlock-issues#2573] opened 2023-04-01 17:49 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

- Go to:
`https://public-psychology.ir/author/alireza/`

- Notice that right-click is blocked.
The reason is:
```js
<script type="text/javascript" src="data:text/javascript;base64,ZG9jdW1lbnQub25jb250ZXh0bWVudT1mdW5jdGlvbihldmVudCl7aWYoZXZlbnQudGFyZ2V0LnRhZ05hbWUhPSdJTlBVVCcmJmV2ZW50LnRhcmdldC50YWdOYW1lIT0nVEVYVEFSRUEnKXtldmVudC5wcmV2ZW50RGVmYXVsdCgpfX07ZG9jdW1lbnQub25kcmFnc3RhcnQ9ZnVuY3Rpb24oKXtpZihldmVudC50YXJnZXQudGFnTmFtZSE9J0lOUFVUJyYmZXZlbnQudGFyZ2V0LnRhZ05hbWUhPSdURVhUQVJFQScpe2V2ZW50LnByZXZlbnREZWZhdWx0KCl9fQ==](view-source:data:text/javascript;base64,ZG9jdW1lbnQub25jb250ZXh0bWVudT1mdW5jdGlvbihldmVudCl7aWYoZXZlbnQudGFyZ2V0LnRhZ05hbWUhPSdJTlBVVCcmJmV2ZW50LnRhcmdldC50YWdOYW1lIT0nVEVYVEFSRUEnKXtldmVudC5wcmV2ZW50RGVmYXVsdCgpfX07ZG9jdW1lbnQub25kcmFnc3RhcnQ9ZnVuY3Rpb24oKXtpZihldmVudC50YXJnZXQudGFnTmFtZSE9J0lOUFVUJyYmZXZlbnQudGFyZ2V0LnRhZ05hbWUhPSdURVhUQVJFQScpe2V2ZW50LnByZXZlbnREZWZhdWx0KCl9fQ==)" defer></script>
```
Which corresponds to:
```js
document.oncontextmenu = function(event) {
    if (event.target.tagName != 'INPUT' && event.target.tagName != 'TEXTAREA') {
        event.preventDefault()
    }
};
document.ondragstart = function() {
    if (event.target.tagName != 'INPUT' && event.target.tagName != 'TEXTAREA') {
        event.preventDefault()
    }
}
```

- Add:
`public-psychology.ir##+js(aopw, document.oncontextmenu)`
(or `aopr`)

- Right-click is fixed on that page. 

- Now click on one of thumbnails (`##.featured`) to go to another article, wait until the page is loaded and try to right-click, notice that it's blocked.

So at the first page the filter works, then after navigating to another page it doesn't work.

### A specific URL where the issue occurs.

`https://public-psychology.ir/author/alireza/`

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBO version

1.48.3b3 dev

### Browser name and version

Firefox 111.0.1

### Operating System and version

.

**Comment by mapx-** [comment] 2023-04-01 18:02
I cannot reproduce, however you could use acs with the third parameter

`public-psychology.ir##+js(acs, document.oncontextmenu, , /^data:/)`

**Comment by mapx-** [comment] 2023-04-01 18:45
chrome all fine
FF nothing works from the filters above

**Comment by mapx-** [comment] 2023-04-01 18:46
I have an issue in firefox, I need bypassing the cache

**Comment by mapx-** [comment] 2023-04-01 18:50
in the new page the stuff is is managed here:
`https://public-psychology.ir/wp-content/litespeed/js/912fcd358dd5d784e91a044fffe27262.js?ver=5fd5a`

**Comment by mapx-** [comment] 2023-04-01 18:59
yes, me too

**Comment by mapx-** [comment] 2023-04-01 19:04
this is working - test for breakage

`||public-psychology.ir^$csp=script-src * 'unsafe-inline' 'unsave-eval'`

**Comment by gwarser** [comment] 2023-04-01 19:09
`filterlist`?

**Comment by gwarser** [comment] 2023-04-01 20:26
Filter list issue. It's known that DOM APIs can cause issues for scriptlets.

**Comment by gorhill** [comment] 2023-04-01 23:05
One way I can reproduce easily is to click on an article, go back, then go forward. I get 100% reproducibility after I go forward. A race condition is difficult to explain because it's a built-in property which is always present. I will investigate to understand what is happening.

**Comment by gorhill** [comment] 2023-10-02 13:43
I think this may have been fixed with <https://github.com/gorhill/uBlock/commit/4cac9d185bf522c69b0a262c8778990e3cf2b14d>.

**Closed as completed** 2023-10-04 04:55 UTC
Labels: fixed
