### ISSUE TITLE
uBO shows domains from previously visited gmail website in dynamic filtering pane

### ISSUE THREAD

**Issue by valynor** [uBlockOrigin/uBlock-issues#2511] opened 2023-02-24 21:07 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When I switch from the Gmail website to a different website (but in the same tab), uBO shows blocked Google domains in the dynamic filtering pane.  The same thing happens on a different Mac (same OS/browser/uBO version). 

I'm using uBO in medium blocking mode. 

### A specific URL where the issue occurs.

https://mail.google.com/mail/u/0/#inbox

### Steps to Reproduce

1. open a fresh tab
2. go to https://mail.google.com/mail/u/0/#inbox
3. go to https://teddit.adminforge.de/r/Hanklights/  (this is where I noticed it first, but can be any other website that doesn't open connections to Google)
4. open the uBO popup and look at the dynamic filtering pane

### Expected behavior

https://teddit.adminforge.de/r/Hanklights/ should only show this in the dynamic filtering pane: 

![Screenshot 2023-02-24 at 21 58 05](https://user-images.githubusercontent.com/23384233/221290652-0d93b089-a7c8-4468-87f7-f10f53f8a92f.png)

### Actual behavior

.. but it actually shows THIS: 

![Screenshot 2023-02-24 at 21 59 19](https://user-images.githubusercontent.com/23384233/221290867-03f44aec-b2cc-4f26-a394-e984de9d930d.png)

If I reload https://teddit.adminforge.de/r/Hanklights/ the Google domain disappears from the list. 
Without previous visiting Gmail in the same tab, https://teddit.adminforge.de/r/Hanklights/ never shows or opens any connections to google. 

### uBO version

1.47.2

### Browser name and version

Brave 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64) 

### Operating System and version

macOS 13.2.1

**Comment by gorhill** [comment] 2023-02-24 21:14
Duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2363>

**Closed** 2023-02-24 21:14 UTC
Labels: duplicate
