### ISSUE TITLE
`json-prune-fetch-response` not working in older Firefox and Chromium versions

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uBlock-issues#2838] opened 2023-09-25 15:46 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

In Firefox ESR version `102` and Chromium version `103.0.5060.134`, `json-prune-fetch-response` does not work on YouTube.

It works normally on newest Firefox and Chromium stable versions (both are `117`).

The current filter being used is

```adb
youtube.com,youtubekids.com,youtube-nocookie.com##+js(json-prune-fetch-response, [].playerResponse.adPlacements [].playerResponse.playerAds [].playerResponse.adSlots playerResponse.adPlacements playerResponse.playerAds playerResponse.adSlots adPlacements playerAds adSlots)
```

I'm not sure from which browser version that the filter starts to work.

---

The 3 `trusted-replace-fetch-response` filters still work normally on older browser versions

```adb
youtube.com,youtubekids.com,youtube-nocookie.com##+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}\]\,/, , player?key=)
youtube.com,youtubekids.com,youtube-nocookie.com##+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/, , player?key=)
youtube.com,youtubekids.com,youtube-nocookie.com##+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, , player?key=)
```

### A specific URL where the issue occurs.

`https://www.youtube.com/`

### Steps to Reproduce

1. Disable these current 3 filters so it's easier to reproduce

```adb
youtube.com,youtubekids.com,youtube-nocookie.com#@#+js(trusted-replace-fetch-response, /\"adPlacements.*?\"\}\}\}\]\,/, , player?key=)
youtube.com,youtubekids.com,youtube-nocookie.com#@#+js(trusted-replace-fetch-response, /\"adSlots.*?\}\]\}\}\]\,/, , player?key=)
youtube.com,youtubekids.com,youtube-nocookie.com#@#+js(trusted-replace-fetch-response, /\"playerAds.*?\}\}\]\,/, , player?key=)
```

2. Access `https://www.youtube.com/`
3. Click on any video
4. Click on some videos on the right side bar

(Access youtube link directly or refreshing youtube link won't trigger the issue since the ads are not in `fetch` response in that case)

### Expected behavior

The ads are pruned from the `fetch` response

### Actual behavior

The ads are not pruned from the `fetch` response

### uBO version

1.52.0

### Browser name and version

Firefox ESR 102 and Chromium 103.0.5060.134

### Operating System and version

Windows 10

**Comment by krystian3w** [comment] 2023-09-26 08:04
Firefox release 102 is being extinguished, users should start taking tests to see if they are ready for Firefox 115.2.1.

**Comment by gorhill** [comment] 2024-02-29 13:58
Reality is that I have no motivation to investigate such issues for outdated browsers. Even though these browser versions are officially supported, I can't guarantee that _everything_ works as intended in these, it's just a burden I don't want to take on. 

People using older browsers are welcome to put in the work to contribute to the project to help investigate and provide solution to issues specific to their old browser versions. Filter list maintainers are welcome to also refuse to look into such issues when some filters behave differently in older browser versions, and whoever submit reports for such filter issues are welcome to contribute to figure filter solutions in order to unburden filter list maintainers.

Closing as wontfix -- assuming it still is an issue with current stable release of uBO.

**Closed by gorhill** 2024-02-29 13:58 UTC
Labels: something to address
