### ISSUE TITLE
New UI panel & dashboard unreadable text and icons

### ISSUE THREAD

**Issue by lucknaumann** [uBlockOrigin/uBlock-issues#1090] opened 2020-06-02 19:25 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The new UI dark blue text and icon scheme does not allow readability when using Chome(ium) flag "Force Dark Mode for Web Contents"  chrome://flags/#enable-force-dark on both the panel and the dashboard. Specifically, all but the HSL-based & RGB-based selections are either unreadable or very difficult to read. Please change the text back as that was very easily read anywhere in the UI.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Enable chrome://flags/#enable-force-dark [I use "selective inversion of non-image elements"]
2. Relaunch Chrome(ium)
3. Open uBO panel and dashboard and notice the unreadable (or, at best, _very_ difficult to read) text. 

### Expected behavior:

Able to easily read the text and icons in both the panel and dashboard, as always.

### Actual behavior:

Text and icons in both the panel and dashboard are either unreadable or very difficult to read.

### Your environment

* uBlock Origin version: v1.27.10
* Browser Name and version: Google Chrome Version 80.0.3987.149 (Official Build)
* Operating System and version: Windows 10 v1809

**Comment by gorhill** [comment] 2020-06-02 21:14
Dark mode is not yet supported and the previous UI was also never made for dark mode, if it worked is was pure luck. Use [advanced setting](https://github.com/gorhill/uBlock/wiki/Advanced-settings#uiflavor) to bring back old panel.

Duplicate of #401.

**Closed by gorhill** 2020-06-02 21:14 UTC
Labels: Chromium, something to address

**Comment by lucknaumann** [comment] 2020-06-03 00:10
Thanks for your quick response. 

This is similar to, but not exactly a duplicate of, 401. That issue was mentioning the default color scheme of the browser overall and the inconsistency of having a white (regular) uBO panel. With that issue, the panel is still white with dark text and icons. Perfectly readable. I'm mentioning a flag that turns on additional color throughout the browser pages and also affects the UI color of extensions. I just want to be clear that we're discussing the same thing. However, it looks like that issue turned into general dark mode support, which is currently being worked on, so I await its completion and release. 

I realize uBO wasn't specifically made for a dark theme but was hoping a reversion to the old color scheme would be acceptable. Reverting to the classic panel only helps in the sense that I know where everything is, so thanks for pointing that out. I will just rely on the useful pop-ups to ensure I am making the correct selection and await an official dark theme release. 

FWIW - The new panel looks interesting.

Thanks for your time and attention to this.
