### ISSUE TITLE
Фильтры не обновляются в Яндекс браузере.

### ISSUE THREAD

**Issue by akela2015** [uBlockOrigin/uBlock-issues#2672] opened 2023-05-25 07:58 UTC
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

Фильтры не обновляются в Яндекс браузере.

### A specific URL where the issue occurs.

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html

### Steps to Reproduce

После обновления браузера фильтры не обновляются.

### Expected behavior

Исправить.

### Actual behavior

Фильтры не обновляются в Яндекс браузере.
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html

### Configuration

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html

**Comment by gorhill** [comment] 2023-05-25 11:37
@dimisa-RUAdList, can you answer? Looks like another case of using the Yandex browser, which is not supported.

**Comment by dimisa-RUAdList** [comment] 2023-05-25 11:53
I am not testing this browser. Even its portable version manages to mess up the system in such a way that it discourages any desire to deal with this browser. Therefore, I focus only on the feedback provided by users.

But as far as I know, the standard version of uBlock Origin does not work properly in this browser, and perhaps never did.

This browser is only compatible with [uBlock Origin development build](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).

**Comment by gorhill** [comment] 2023-05-25 12:21
Well I thought you would answer in Russian since it appears that person doesn't know English.

**Comment by gorhill** [comment] 2023-05-25 13:07
Will consider duplicate of <https://github.com/uBlockOrigin/uBlock-issues/issues/2627>, there was also a similar issue reported:

> filters do not load (can't attach settings screenshot here) - I see exclamation marks on all filters and can't update them

**Closed by gorhill** 2023-05-25 13:07 UTC

**Comment by iam-py-test** [comment] 2023-05-25 18:45
@akela2015 your email signature includes your name. I'm not sure you want that posted publicly...

**Comment by danildrozdov** [comment] 2026-01-20 08:51
> I am not testing this browser. Even its portable version manages to mess up the system in such a way that it discourages any desire to deal with this browser. Therefore, I focus only on the feedback provided by users.
> 
> But as far as I know, the standard version of uBlock Origin does not work properly in this browser, and perhaps never did.
> 
> This browser is only compatible with [uBlock Origin development build](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii).

Огромное вам спасибо! Вы очень помогли! Все заработало! 

Thank you so much! You've been a great help! Everything is working now!
