### ISSUE TITLE
Nested `!#if`/`!#endif` directives not evaluated properly

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBlock-issues#270] opened 2018-10-15 06:30 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Two conditions for limiting the operation of filters do not work well, the second condition is may not interpreted.

https://github.com/uBlockOrigin/uAssets/issues/3482 - where used two conditions.

### A specific URL where the issue occurs

`https://www.google.com/search?q=search`

### Steps to Reproduce

1. Open expample website

2.  In my filters panel put expample conditions:

    ```
    !#if env_firefox
    !#if env_mobile
    google.*###main > div
    !#endif
    !#endif
    ```
    and save.

3. Refresh website - almost all div should be hidden.

4. The second condition is somewhat ignored and cuts out the content despite the incompatibility of the platfrom.

### Expected behavior:

The second condition should be included.

### Actual behavior:

The second condition is not included?

### Your environment

* uBlock Origin version: 1.17.0
* Browser Name and version: **Firefox** 62.0.2
* Operating System and version: **Windows** 7 Professional x64 PL language edditon.

**Comment by uBlock-user** [comment] 2018-10-15 06:57
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/183

**Comment by gorhill** [comment] 2018-10-15 12:10
Does not seem to be a duplicate, there are no syntax error in the directives.

**Comment by uBlock-user** [comment] 2018-10-15 12:12
`google.*###main > div` filter doesn't get applied, is that expected response ?

**Comment by gorhill** [comment] 2018-10-15 12:14
If I understand correctly he is saying all divs end up being hidden, while this should not be the case if not using Firefox for Android.

**Comment by krystian3w** [comment] 2018-10-15 12:35
> If I understand correctly he is saying all divs end up being hidden, while this should not be the case if not using Firefox for Android.

Yes.


> search bar alongwith Google logo doesn't get hidden except that everything else is hidden.


I did not check this out, I noticed that it started hidding `div[data-hveid]` out in the simulator with mobile UA activated, so I preferred to report.

---


As for the problem, I even recreated it in Opera 56 - it also hides most of the elements and is the top browser bar.

```
!#if env_chrome
!#if env_mobile
google.*###main > div
!#endif
!#endif
```

> ![image](https://user-images.githubusercontent.com/35370833/46950890-8b88e600-d086-11e8-9b62-ab5ed8031608.png) |
> --- |

but uBO do not support officially Mobile Yandex browser.

**Comment by uBlock-user** [comment] 2018-10-15 12:41
@gorhill Do all preparsing directives have to be **true** for the filter to apply ?

**Comment by gorhill** [comment] 2018-10-15 12:51
Yes.

However looking at the code, I see that directives which evaluate to false will be ignored if contained in a directive which evaluate to true -- this is a bug. I can't remember what was my thinking when I wrote that code, but [my answer](https://github.com/uBlockOrigin/uBlock-issues/issues/183#issuecomment-416255000) to @grenzor in #183 says that I was expecting the code to deal properly with `!#if` within `!#if`.

**Closed** 2019-05-19 05:53 UTC
Labels: bug

**Comment by krystian3w** [comment] 2019-05-26 19:56
Possible add in the feature this syntax:

```
!#if (!adguard_ext_android_cb && !adguard_ext_safari && !adguard_app_ios)
```

similar proposed by @mapx-


---

```
!#if !adguard_ext_android_cb 
!#if !adguard_ext_safari 
!#if !adguard_app_ios

! filter for modern uBlock Origin and AdGuard Adblocker / AdGuard APP (macOS, Windows, Android).

!#endif
!#endif
!#endif
```
