### ISSUE TITLE
uBlock Origin v1.25.2 + VPN add on cause DNS leaks

### ISSUE THREAD

**Issue by wanglai8** [uBlockOrigin/uBlock-issues#967] opened 2020-03-30 12:20 UTC
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. install dan start browsec https://addons.mozilla.org/en-US/firefox/addon/browsec/ or hoxx vpn https://addons.mozilla.org/en-US/firefox/addon/hoxx-vpn-proxy/

2. use DNS leaks test site
https://www.expressvpn.com/dns-leak-test

 "DNS leaks" exposed your location. when disable the uBlock Origin from add on, the problem is gone.

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.25.3rc0
* Browser Name and version: firefox 74
* Operating System and version: windows 1909  x64

**Comment by gwarser** [comment] 2020-03-30 12:29
Duplicate of https://github.com/uBlockOrigin/uBlock-issues/issues/911

**Closed by gwarser** 2020-03-30 12:29 UTC
