### ISSUE TITLE
Incompatibility of pseudo-classes and procedural filter operators.

### ISSUE THREAD

**Issue by whileloopa** [uBlockOrigin/uBlock-issues#238] opened 2018-09-22 01:30 UTC
Currently uBlock0 do not support using pseudo-classes selectors (eg. :hover, :focus, :first-child) together with procedural filter operators (eg. :style, :xpath, :has, :matches-css).

Hope this issue can be solved in future version.

**Comment by uBlock-user** [comment] 2018-09-22 05:06
and is this you making a suggestion or what ?

**Comment by gorhill** [comment] 2018-09-22 13:04
Please, do **not** delete the template: fill it with all the details and especially with detailed reproducible steps, preferably of an actual, real world case. Closing as _invalid_ due to complete failure to respect the issue template.

**Closed** 2018-09-22 13:04 UTC
Labels: invalid
