### ISSUE TITLE
Rule window stuck at Logger

### ISSUE THREAD

**Issue by calendulish** [uBlockOrigin/uBlock-issues#2704] opened 2023-06-26 13:17 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

There's no way to move it

![](https://i.imgur.com/8hMMw2a.png)

### A specific URL where the issue occurs.

Logger Window

### Steps to Reproduce

1. Open Logger
2. click an entry

### Expected behavior

Window not stucked

### Actual behavior

Window stucked

### uBO version

1.50.0

### Browser name and version

LibreWolf 114.0.1-2

### Operating System and version

Windows 11

**Comment by krystian3w** [comment] 2023-06-27 09:04
Test in Devtools for Logger window:

```css
.entryTools:is([style*="top:-"], [style*="top: -"]) { top: 0 !important }
```

If move down, then try drag to reset negative value for the style attribute? Then the change might register.

If not, chances are it has to be fixed by the LibreWolf team, and it's beyond the capabilities other than the aforementioned CSS with detection:

- `top:-`
- `top: -` 

More whitespace between `:` and `-` would have to be detected with CSS using a very loose CSS selector:

```css
.entryTools[style*="top:"][style*="-"] { top: 0 !important }
```

Assuming, of course, that the window has a negative value for `top` (minimum -11% as value): 
https://github.com/uBlockOrigin/uBlock-issues/assets/35370833/f5a05ced-e85a-4baa-854e-724e0ea479a9

**Comment by gwarser** [comment] 2023-06-27 20:05
What is this black bar on top?

**Comment by krystian3w** [comment] 2023-06-27 20:10
Its maybe pseudo elements from invalid userConent.css Moz://a file.

**Comment by gorhill** [comment] 2023-06-30 11:42
The logger code does not allow the `style.top` property of the floating widget to be under zero, the property is always clamped to be zero at a minimum. Maybe OP might have browser-side customizations which are causing this. I will let OP investigate on his side and will close as _invalid_ in a few days if nothing comes out of this.

**Comment by gorhill** [comment] 2023-06-30 15:47
> It's the letterbox setting to prevent fingerprinting, should be the cause of the problem

I can't reproduce letterboxing for the logger window of Tor browser, and neither letterboxing at the top of any tab -- it's always at the bottom if any.

But since it appears the value of `top` was a negative one, I added code to clamp to `0` if ever uBO detects the value to be negative.

**Closed** 2023-06-30 15:47 UTC
Labels: unable to reproduce

**Comment by krystian3w** [comment] 2023-07-01 21:11
Maybe something else has active to make the bar at the top, or it's LibreWolf messing up forking Firefox.

**Comment by calendulish** [comment] 2023-07-01 23:54
> Maybe something else has active to make the bar at the top, or it's LibreWolf messing up forking Firefox.

LibreWolf is aligning the box on center and TorBrowser on top
