### ISSUE TITLE
uBO install irreversibly changes WebGL fingerprint?

### ISSUE THREAD

**Issue by ofiala-a51** [uBlockOrigin/uBlock-issues#1583] opened 2021-05-12 21:23 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

First off, I am unsure whether this is a bug in Tor Browser or uBO. Anyway; I am aware that adding uBO to Tor Browser might reduce fingerprinting resistance if fingerprinters target this specifically. However, what caught me off guard is that the mere act of installing uBO, without even having it enabled, modifies WebGL fingerprint. What's even more interesting is that this is irreversible -- if you install uBO on Tor Browser, then remove it, your WebGL fingerprint is unique until you completely erase the whole browser and install it from scratch. From what I understand about WebGL, none of this should happen at all.

### A specific URL where the issue occurs

<https://coveryourtracks.eff.org/>

### Steps to Reproduce

1. download Tor Browser
2. go to the specified link and test
3. install uBO
4. go to the link and test
5. remove uBO from browser
6. go to the link and test
7. compare all three results

### Expected behavior:

Installing uBO doesn't affect WebGL fingerprint.

### Actual behavior:

Installing uBO irreversibly changes WebGL fingerprint.

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Tor Browser v10.0.16
* Operating System and version: latest Void Linux on amd64-glibc (rolling)

**Comment by gorhill** [comment] 2021-05-13 10:43
> compare all three results

You don't disclose _any_ results. What exactly did you get at each step?


uBO has nothing to do with WebGL, this sounds like a spurious report. Also, please check all the checkboxes in the template, they are their to rule out issues outside of uBO.

**Comment by gorhill** [comment] 2021-05-14 13:50
Closing as _invalid_. I will re-open if the issue is made that uBO is really the issue and that the issue is explained with more details; _"results"_ without providing details of actual result is too vague.

**Closed by gorhill** 2021-05-14 13:50 UTC
Labels: something to address
