### ISSUE TITLE
Block element on booking.com

### ISSUE THREAD

**Issue by thany** [uBlockOrigin/uBlock-issues#1568] opened 2021-04-27 23:05 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Element picker does not work on booking.com. When selecting it, absolutely nothing happens. And when I say nothing, I do really honestly genuinely mean **nothing**, as in not even so much as an error in the console. Just nothing.

On other websites -> Works
Javascript disabled -> Still not working
When uBlock Origin is the *only* extension after disabling all others and hitting F5 on the page -> Still not working
When in a new profile where uBlock Origin is the only extension -> This does work
When in a private window -> Doesn't work

There might be a problem in my settings, but then why would it work fine on other websites? Booking.com might be doing something crazy that it isn't doing when in a fresh profile (which is likely, they are known to do weird stuff on a per-user or per-visit basis). But then it should also work fine in a private window, which it doesn't.

Element zapper does work, in all these scenarios.

### A specific URL where the issue occurs

`https://www.booking.com/index.en-gb.html`

### Steps to Reproduce

1. Open URL
2. Right-click somewhere and select "Block element", or
3. Click the uBlock icon in the toolbar and click the eyedropper button

### Expected behavior:

It goes into element picker mode

### Actual behavior:

Absolutely nothing.

### Your environment

* uBlock Origin version: 1.35.0
* Browser Name and version: Firefox 88 x64
* Operating System and version: Windows 10 20H2

**Comment by llacb47** [comment] 2021-04-27 23:14
Works for me..

**Comment by uBlock-user** [comment] 2021-04-27 23:34
Is cosmetic filtering disabled for `booking.com`? If so, enable it.

**Comment by thany** [comment] 2021-04-28 08:09
Oh is that it... I see.

Initially after enabling it it still didn't work, but after a *secondary* reload it started working.

So that makes the bug slightly different:

If cosmetic filtering is off, element picker mode is not working. Instead, nothing happens and no message is displayed telling the user to turn on cosmetic filtering first. It is also not turned on automatically. To a user, it feels like element picker mode is broken.

**Comment by uBlock-user** [comment] 2021-04-28 08:22
Duplicate of gorhill/uBlock#3212

**Closed by uBlock-user** 2021-04-28 08:22 UTC
Labels: unable to reproduce
