### ISSUE TITLE
pop up user menu shows up blank when clicked

### ISSUE THREAD

**Issue by whatdoyoumeanitsnotawesome** [uBlockOrigin/uBlock-issues#1374] opened 2020-11-30 23:37 UTC
### URL(s) where the issue occurs

instagram.com, ublockorigin.com, google.com, reddit.com, etc.

### Describe the issue

pop up user interface is blank, and cannot access uBlock through context menu. it appears as an option, but when clicked, nothing happens.

### Screenshot(s)

![ublock instagram](https://user-images.githubusercontent.com/30984112/100678003-1093ef80-3321-11eb-9112-fb6afc05bc59.png)

### Versions

- Browser/version: [83.0 (64-bit), Firefox for Ubuntu canonical 1.0]
- uBlock Origin version: [1.31.0]

### Settings
 i can't access the add on to determine that

### Notes

can't investigate, nothing shows up

![ublock preferences](https://user-images.githubusercontent.com/30984112/100678427-f7d80980-3321-11eb-8510-a151c3f90db2.png)

**Comment by gorhill** [comment] 2020-12-02 12:50
Please fill this template carefully and truthfully:

---





- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

**Comment by ceejayoz** [comment] 2020-12-02 16:15
@gorhill I can recreate this by doing the following:

* New Firefox profile
* Install uBlock Origin extension - at this point it functions
* Install 1Password's extension - this appears to break uBlock

This is in Firefox 84.0b7 on a new Apple M1 Macbook Pro.

**Comment by gorhill** [comment] 2020-12-02 16:20
> This is in Firefox 84.0b7 on a new Apple M1 Macbook Pro.

There are known issues with extensions on Firefox/M1, see <https://bugzilla.mozilla.org/show_bug.cgi?id=1678805>.

**Comment by ceejayoz** [comment] 2020-12-02 16:26
@gorhill Appreciate it; I'd imagine my issues are unrelated then. Sorry!

**Comment by gwarser** [comment] 2020-12-02 16:41
Duplicate of #1352

**Comment by gorhill** [comment] 2020-12-02 16:47
Not duplicate since OP says:

> Browser/version: [83.0 (64-bit), Firefox for Ubuntu canonical 1.0]

**Comment by gorhill** [comment] 2020-12-04 12:59
Closing due to lack of feedback. Most likely a Firefox profile issue, possibly bad `about:config` changes or another extension misbehaving in the extensions process.

**Closed by gorhill** 2020-12-04 12:59 UTC
Labels: something to address

**Comment by VaelophisNyx** [comment] 2023-07-15 21:08
Just wanted to pop by and say I've run into this issue (affects ALL firefox addons that had popup settings on click)
Very unlikely a bad config change, as this started randomly today for me. Ublock has also ceased functioning after turning it off and back on.

**Comment by iam-py-test** [comment] 2023-07-15 21:43
Can you reproduce in a new Firefox profile?
