### ISSUE TITLE
Subscriber script needs to be improved

### ISSUE THREAD

**Issue by gwarser** [uBlockOrigin/uBlock-issues#763] opened 2019-10-24 12:26 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Subscriber scriptlet does not work after navigation in dynamic pages when first loaded page does not have subscribe links. For example on some GitHub pages (dynamic tabs) or Discourse forums (dynamic subforums/categories/comments).

### A specific URL where the issue occurs

https://github.com/MajkiIT/polish-ads-filter

### Steps to Reproduce

1. open https://github.com/MajkiIT/polish-ads-filter/issues
2. click on "<> Code" tab (address will change to https://github.com/MajkiIT/polish-ads-filter)
3. scroll down to table and click on one of the "Subskrybuj" links

OR

1. open https://discourse.mozilla.org/t/support-ublock-origin/6746 (first message)
1. scroll down to my last message (768)
1. click on subscription link

### Expected behavior:

uBO Subscribe dialog should appear

### Actual behavior:

Navigation to non existing page.

### Your environment

* uBlock Origin version: 1.22.5rc6, 1.23.0
* Browser Name and version: Firefox 72, Chrome 77
* Operating System and version: Manjaro

**Comment by uBlock-user** [comment] 2019-12-02 09:42
Similr issue with scriptlets/HTML filters, they don't applied/injected when a page is fetched via an XHR.

STR -- Open https://github.com/gorhill/uBlock/tree/master/src/web_accessible_resources

Then open any scripts for example -- hd-main.js, first time opening will fire a network request but subsequent openings will fetch the page via an XHR where HTML filters nor scriptlets that removes an element get injected/applied.

**Comment by Yuki2718** [comment] 2020-03-27 14:00
This bug bogged me, but somehow the link for NanoContrib/Placeholder-buster works despite it is on Github in the same manner. And it seems their use of gitcdn is irrelevant.

**Comment by gorhill** [comment] 2020-09-13 12:43
Users will now go through the asset viewer to confirm subscribing to a list. This opens the door for potential future improvements such as maybe detecting problematic lists (i.e. with lots of invalid filters) or insight into the number of various categories of filters and so on.

**Comment by gwarser** [comment] 2020-09-13 14:59
Support for this style of subscribtion links is dropped?

    https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt&title=Official%20Polish%20filters%20for%20AdBlock,%20uBlock%20Origin%20and%20AdGuard

Page from STR used them at the time when this issue was submitted: https://github.com/MajkiIT/polish-ads-filter/tree/7b77632754940329a01fc9857bcd3a341ac49726

**Comment by uBlock-user** [comment] 2020-09-13 15:05
Seems so as per the commit msg --

> From now on, uBO will allow click-to-subscribe on only
a few select domains, currently:
- https://filterlists.com/
- https://github.com/
- https://github.io/

> More domains can be added if and only the demonstration
is made that more than a marginal number of filter lists
can be subscribed from those domains.

**Comment by gorhill** [comment] 2020-09-13 15:10
> Support for this style of subscribtion links is dropped?

I couldn't find a case where this syntax was used, so I dropped it. Looks like the project now uses the traditional syntax: <https://majkiit.github.io/polish-ads-filter/>.

I could bring back support if it's still used somewhere by high profile list projects.

**Comment by gwarser** [comment] 2020-09-13 15:18
>I couldn't find a case where this syntax was used, so I dropped it. Looks like the project now uses the traditional syntax: majkiit.github.io/polish-ads-filter.

Popular list:

https://github.com/yourduskquibbles/webannoyances/#one-click-installation

**Comment by gorhill** [comment] 2020-09-13 15:50
Fixed in 1.29.3b17.

**Comment by Yuki2718** [comment] 2020-09-13 15:58
Not as popular as WAUL but: https://github.com/NanoAdblockerLab/NanoContrib
So if I understand correctly `https://subscribe.adblockplus.org/?location=` won't be available even on Github while `abp:subscribe?location=` will? I couldn't get the latter work on Github if simply pasted.

**Comment by gwarser** [comment] 2020-09-13 17:00
Links on filterlists.com stopped working. Probably because of wrong escaping: `abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Fxxcriticxx%2F.pl-host-file%2Fmaster%2Fhosts.txt&amp;title=.pl-host-file` (`&amp;`?)

**Comment by gwarser** [comment] 2020-09-13 20:36
Looks like this ampersand encoding is [created on purpose](https://github.com/collinbarrett/FilterLists/issues/252#issuecomment-366543109) by following what ["Subscription link factory for Adblock Plus"](https://adblockplus.org/en/abp_linkfactory) is creating.

**Closed** 2020-09-13 20:46 UTC
Labels: bug, fixed

**Comment by gorhill** [comment] 2020-09-13 21:59
There own example link at that page and their own [subscription links](https://adblockplus.org/en/subscriptions) use `&`.

**Comment by krystian3w** [comment] 2020-09-14 07:00
So this is too small:

https://polishannoyancefilters.netlify.app/otherfiltersforadblockers/
https://polishannoyancefilters.netlify.app/modules/

https://kadantiscam.netlify.app/
https://kadantiscam.netlify.app/#recommended

**Comment by collinbarrett** [comment] 2020-09-14 12:24
@gorhill I just removed the encoded `&amp;`s. See [here](https://github.com/collinbarrett/FilterLists/commit/2c0dd92ac7b41dbf41c3d2e25cec66bf61da7eb4). @gwarser was right, I was trying to adhere to what ABP's factory page produces; but, like you said, their own examples don't use encoded `&amp;`.

[ref 252](https://github.com/collinbarrett/FilterLists/issues/252)

**Comment by collinbarrett** [comment] 2020-09-14 12:31
I do still see frequent intermittent failures with subscribe links on FilterLists.com with uBO in Chrome. It seems to be some kind of a timing thing, maybe. Without reloading the page, I can toggle between info drawers (by clicking the info buttons on the left) and then clicking Subscribe and sometimes the buttons for the same list work and sometimes they throw console errors. If anybody has a suggestion on how I can improve that, let me know.

```
Failed to launch 'abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Fbadmojr%2F1Hosts%2Fmaster%2Fmini%2Fdnsmasq.conf&title=1Hosts%20Mini%20(dnsmasq)' because the scheme does not have a registered handler.
```

**Comment by krystian3w** [comment] 2020-09-14 12:38
`abp://subscribe?location=` is legacy / obsolete? Maybe chrome don't like `abp:subscribe?location=`...

**Comment by gorhill** [comment] 2020-09-14 12:39
> I do still see frequent intermittent failures with subscribe links on FilterLists.com with uBO in Chrome. 

Is this the stable release, dev build, or either? I made changes in the dev build so that the content script no longer bail out if it does not find subscription links on a page. (hence why now the content script is injected only on a handful of sites).

**Comment by collinbarrett** [comment] 2020-09-14 12:41
> Is this the stable release, dev build, or either?

Ah, I was seeing it in just the standard stable build from Chrome store. Cool, that fix sounds promising. I've never used a dev build of uBO, but sounds like a time I need to learn how to try it out. Will try to test later on.

**Comment by collinbarrett** [comment] 2020-09-14 14:26
Dev build seems to always open a new uBO tab previewing the list when clicking a subscribe button. Assuming that means its working. Clicked around quite a bit on FilterLists.com with the dev build and can't seem to reproduce the `scheme does not have a registered handler` error with the dev build. Nice.

**Comment by NatoBoram** [comment] 2021-05-15 01:58
Is there some documentation or a tool somewhere that can help uBlock Origin filterlists create an easy install button? I've been having some difficulties with the auto install on [my personal list](https://gitlab.com/NatoBoram/Beemoov-Annoyances).

**Comment by gwarser** [comment] 2021-05-15 08:40
@NatoBoram subscribing by click is allowed only on these domains:

```
https://easylist.to/
https://*.fanboy.co.nz/
https://filterlists.com/
https://forums.lanik.us/
https://github.com/
https://*.github.io/
```

**Comment by gorhill** [comment] 2021-05-15 12:05
I will add the ability to subscribe through right-click contextual menu, this will work for all sites without the need to keep expanding that list.

**Comment by Erquint** [comment] 2021-06-22 04:51
I'm getting the `abp:` […] `scheme does not have a registered handler` error and cannot subscribe to AAK currently in Vivaldi (yet another Chromium fork trying to be the old Opera of the modern day).

Furthermore, if AAK is added as a custom list — stays on 0/0 and `outdated` despite prompting the update manually.
The link does open to a plaintext filterlist normally.

**Comment by uBlock-user** [comment] 2021-06-22 07:00
> Furthermore, if AAK is added as a custom list — stays on 0 used out of 0 and outdated despite prompting the update manually.
The link does open to a plaintext filterlist normally.

AAK is blocked, so users will not be able to subscribe.

**Comment by krystian3w** [comment] 2021-06-22 10:17
Or use tricks if is a "Smart" user (possible found on Reddit/github).

**Comment by Erquint** [comment] 2021-06-22 10:23
Why is it blocked?
Ad providers are getting crazy again recently.
After what happened to Nano Adblocker/Defender, I know no other choice than AAK.

**Comment by uBlock-user** [comment] 2021-06-22 10:45
> Why is it blocked?

AAK is dead and outdated, author went mia since 2016. Report anti-adblock issues to uAssets.
