### ISSUE TITLE
xhamster middle click functionality broken

### ISSUE THREAD

**Issue by kracov** [uBlockOrigin/uBlock-issues#2134] opened 2022-06-08 16:04 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

In Firefox 92 and the current ublock version with default settings and filter lists
middle clicking to open links in a new tab doesn't work in xhamster

### A specific URL where the issue occurs

`https://www.xhamster.com`

### Steps to Reproduce

1. Go to xhamster
2. use middle click to open a link

### Expected behavior

links should open in a new tab in foreground

### Actual behavior

links won't open at all.  I found out that this is some conflict between ublock and Firefox.  In FF's settings there is the option "✓ When you open a link, image or media in a new tab, switch to it immediately" in Firefox preferences
By default it's unchecked, but for my preferences I need that checked.  Keeping it unchecked allows for middle click, but links open in the background.  

### uBlock Origin version

1.42.4

### Browser name and version

Firefox 92

### Operating System and version

Windows 7

**Comment by gorhill** [comment] 2022-06-08 17:35
Caused by `*$popunder,domain=xhamster.*`. Changing the filter to `*$3p,popunder,domain=xhamster.*` fixes the issue.

**Comment by kracov** [comment] 2022-06-08 17:51
@gorhill
I tried adding that to my filters, it didn't work.  Unless you meant easylist? I don't know how to change that.

@mapx
What is the dynamic panel? You mean the My Rules section?

**Comment by gorhill** [comment] 2022-06-08 17:54
> I tried adding that to my filters, it didn't work.

The other filter is still active, it needs to be replaced with the new one. Until this is fixed in the list, you can disable the problematic filter with:

    *$popunder,domain=xhamster.*,badfilter

**Closed** 2022-06-08 18:58 UTC

**Comment by gorhill** [comment] 2022-06-08 19:11
> I see no popunder filter in the logger

I had to select _All_ to avoid the entries related to the closed tab to be automatically removed.
