### ISSUE TITLE
Add an option to remove the URL comments in My filters

### ISSUE THREAD

**Issue by CreamyCookie** [uBlockOrigin/uBlock-issues#372] opened 2019-01-08 10:02 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I would like an option to not include the full URL (base would be fine) in the comments in "My filters" (for privacy reasons)

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Use block element to block an element on a page.

### Expected behavior:

No full URL in My filters.

### Actual behavior:

The full URL + date and time is included above the filter line in My filters.

### Your environment

* uBlock Origin version: uBlock Origin v1.17.4
* Browser Name and version: Firefox 64
* Operating System and version: Kubuntu 18.04

**Comment by uBlock-user** [comment] 2019-01-08 10:16
Although it's a duplicate of https://github.com/gorhill/uBlock/issues/93, I will keep it open, since gorhill didn't decline that issue.

**Closed** 2019-01-08 13:50 UTC
Labels: enhancement, fixed

**Comment by uBlock-user** [comment] 2019-01-08 13:51
Fix is in the dev build.

**Comment by CreamyCookie** [comment] 2019-01-08 21:03
That was quick. Thank you both! =)

**Comment by 07416** [comment] 2019-06-18 10:05
Is there a configuration setting for this option?

**Comment by yourduskquibbles** [comment] 2019-06-18 12:32
> Is there a configuration setting for this option?

@07416 Set `autoCommentFilterTemplate` to blank in the [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings). 

[autoCommentFilterTemplate options wiki](https://github.com/gorhill/uBlock/wiki/Advanced-settings#autocommentfiltertemplate)
