### ISSUE TITLE
Allow a blocked request

### ISSUE THREAD

**Issue by thany** [uBlockOrigin/uBlock-issues#1228] opened 2020-08-31 09:19 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

There should be a way to allow a blocked request. The popup pane, even in advanced mode, does not have a facility to do that.

### A specific URL where the issue occurs

Not relevant. But fine, here's your url: https://google.com

### Steps to Reproduce

1. Open any page that has blocked content. I don't care what it is.
2. Try to allow that blocked content. It's not possible.

### Expected behavior:

I want to be able to click on a blocked domain or whatever, in the popup pane, and allow it (temporary or permanently).

### Actual behavior:

The opposite of *Expected behaviour*.

### Your environment

* uBlock Origin version: 1.29.2
* Browser Name and version: Firefox 80
* Operating System and version: Windows 10 2004

**Comment by uBlock-user** [comment] 2020-08-31 09:25
Duplicate of #1153

**Closed by uBlock-user** 2020-08-31 09:25 UTC

**Comment by thany** [comment] 2020-08-31 09:29
@uBlock-user That's a closed issue, and it doesn't seem to have been implemented.

**Comment by gorhill** [comment] 2020-08-31 11:38
It's all explained in the release notes: https://github.com/gorhill/uBlock/releases/tag/1.28.0

**Comment by thany** [comment] 2020-08-31 12:47
> It's no longer possible to point-and-click to create allow (green) rules from within the popup panel by default. This change is motivated by seeing way too many cases of improper usage of dynamic filtering 

So it's been removed. Can you add it back in a way that it doesn't cause people to accidentally whitelist something?

I disagree that it's explained though. It just states the removal of this feature. It doesn't explain what to do instead.

**Comment by gorhill** [comment] 2020-08-31 12:50
> Can you add it back

No. This won't change, all has been said, there is no point to keep arguing about this.
.
