### ISSUE TITLE
Blocking pages on first load

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBlock-issues#1004] opened 2020-04-29 19:16 UTC
I do not have time to investigate this for now, just quickly opening an issue to be sure to investigate in the future:

https://www.reddit.com/r/uBlockOrigin/comments/gac2h8/blocking_pages_on_first_load/

> I've noticed this happening in both Chrome and Edge Chromium - if you launch the browser fresh and have uBlock installed, the first URL that loads will show as being blocked by an extension, and then it will load once uBlock fully initializes. Unsure if this is a bug in Chrome or uBlock.

**Comment by lexcyn** [comment] 2020-04-29 19:24
Thanks! Subscribed (I am also Lexcyn on reddit).

**Comment by jspenguin2017** [comment] 2020-04-30 15:16
The network traffic is suspended synchronously on browser start: 

https://github.com/gorhill/uBlock/blob/11d24abea01fdb1c7070a2940dfda6e43cfe0c2c/src/js/traffic.js#L1038

But unsuspended after 2 `await`s, which make unsuspend asynchronous: 

https://github.com/gorhill/uBlock/blob/b295d4a0d0d25848211c43cc2e7068859c2cb9ea/src/js/start.js#L270

On Chromium, the suspend blocks the request and unsuspend reloads all suspended tabs: 

https://github.com/gorhill/uBlock/blob/010635acd6b92f18dfb2369aa3bd385b3698effc/platform/chromium/vapi-webrequest.js#L126-L135

I thought this might be a problem some time ago, I did test it but I couldn't reproduce any issues. Might be because all my devices have pretty good SSDs. I don't think this can be easily fixed without synchronous LocalStorage. I guess one way to fix it is to use synchronous LocalStorage for `suspendTabsUntilReady` on Chromium.

**Comment by willismonroe** [comment] 2020-05-03 17:32
I'm also experiencing this Chrome (81.0.4044.129) on Ubuntu 20.04, using uBlock Origin (1.26.0).

**Comment by gorhill** [comment] 2020-05-07 00:18
I don't understand why the `tabs.reload()` wouldn't work, which is what seems to happen. Failing to understand this, the only solution I can think of is to not suspend preemptively and do so only when the hidden setting asks to suspend.

**Comment by jspenguin2017** [comment] 2020-05-07 02:20
I think Chromium do inter process communication in batches, so when an extension initiates an action that require IPC, Chromium may wait a bit before sending the message out. If more actions that require IPC come in during the wait period, Chromium may batch them together. Since a lot happen during launch, it is possible that the request blocking action and the tab reloading action are batched together and then executed in the wrong order by the browser process. 

I had a similar issue with Nano Linter, where the background script would receive the message for getting the linting result before the message for saving personal filters, even though the message for getting the linting result was sent 0.5 seconds later from the dashboard. I changed the delay to 1 second and then it always work.

**Closed** 2020-05-12 06:47 UTC
Labels: Chromium, bug, fixed
