### ISSUE TITLE
set-cookie not converting [] Cookie Names

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uBlock-issues#2777] opened 2023-08-14 02:32 UTC
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Using set-cookie, [] isn't translated or with `\[`  `\]`

### A specific URL where the issue occurs.

https://www.dlalakierni.pl/

### Steps to Reproduce

Add the following; to counter the cookie message: (or with `\[`  `\]`)

```
dlalakierni.pl##+js(set-cookie, AtomStore[COOKIES_ACCEPTED], 1, , reload, 1)
dlalakierni.pl##+js(set-cookie, AtomStore[FUNCTIONAL_COOKIES_ACCEPTED], 1)
dlalakierni.pl##+js(set-cookie, AtomStore[MARKETING_COOKIES_ACCEPTED], 1)
```
or,
```
dlalakierni.pl##+js(set-cookie, AtomStore\[COOKIES_ACCEPTED\], 1, , reload, 1)
dlalakierni.pl##+js(set-cookie, AtomStore\[FUNCTIONAL_COOKIES_ACCEPTED\], 1)
dlalakierni.pl##+js(set-cookie, AtomStore\[MARKETING_COOKIES_ACCEPTED\], 1)
```

### Expected behavior

Doesn't counter cookie message

### Actual behavior

translate too `AtomStore%5BCOOKIES_ACCEPTED%5D`, `AtomStore%5BFUNCTIONAL_COOKIES_ACCEPTED%5D`, `AtomStore%5BMARKETING_COOKIES_ACCEPTED%5D`

Instead of 

`AtomStore[MARKETING_COOKIES_ACCEPTED]`, `AtomStore[FUNCTIONAL_COOKIES_ACCEPTED]`,`AtomStore[COOKIES_ACCEPTED]`

### uBO version

1.51.1b

### Browser name and version

All Bravey baby

### Operating System and version

Windows

**Comment by gothic-bum** [comment] 2023-08-14 08:17
Per the documentation for [`set-cookie.js`](https://github.com/gorhill/uBlock/wiki/Resources-Library#set-cookiejs-) :

> The scriptlet encodes cookie names and values, e.g value "{ test: 'value'}" becomes `%7B%20test%3A%20'value'%7D`.

Per the documentation for [`trusted-set-cookie.js`](https://github.com/gorhill/uBlock/wiki/Resources-Library#trusted-set-cookiejs-) :  
  
> The scriptlet does not encode cookie names and values.
  
The following filters therefore work - but only if they are from a "trusted source" which is [currently](https://www.reddit.com/r/uBlockOrigin/comments/154ecr3/now_with_release_1510_can_we_finally_set/) the uBO created filter lists (i.e. those prefixed with "uBlock filters – ...") and the user's own filters from ["My filters"](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters):  
 
    dlalakierni.pl##+js(trusted-set-cookie, AtomStore[COOKIES_ACCEPTED], 1, 1year, , reload, 1)
    dlalakierni.pl##+js(trusted-set-cookie, AtomStore[FUNCTIONAL_COOKIES_ACCEPTED], 1, 1year)
    dlalakierni.pl##+js(trusted-set-cookie, AtomStore[MARKETING_COOKIES_ACCEPTED], 1, 1year)

**Comment by ryanbr** [comment] 2023-08-14 11:27
If only setting a simple value of 1 or 0, isn't this fine in set-cookie?  Correct me if I'm wrong that trusted support applys to non-boolean values

**Comment by gorhill** [comment] 2023-08-14 11:29
I followed [AdGuard's reference documentation](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#-%EF%B8%8F-set-cookie) to implement `set-cookie`, and this is what it says:

> scriptlet encodes cookie names and values

I think the idea is to prevent using `set-cookie` to set arbitrary values:

    ...##+js(set-cookie, cookiename=anystring;, allowedvalue)

Encoding the name prevents this.

**Comment by ryanbr** [comment] 2023-08-14 11:38
Okay.

**Comment by gorhill** [comment] 2023-08-14 11:50
Maybe we could discuss with @ameshkov a different safety approach: if a cookie name has any character outside the ones considered safe, the scriptlet won't do anything. The safe set of characters would be `/[\w%\[\]]/`.

**Comment by stephenhawk8054** [comment] 2023-08-14 13:19
> The unsafe set of characters would be `/[^\w%\[\]]/`

You mean safe set?

**Comment by ameshkov** [comment] 2023-08-14 20:50
@gorhill sounds like a good solution. The easiest way would be to follow the [RFC](https://www.rfc-editor.org/rfc/rfc6265), but the problem is that it actually forbids separators including `[` `]` while Chrome allows any character in a cookie name, even control characters.

Actually, what if we only forbid `=` and allow any other ASCII character? Do you see any potential problem with that approach?

**Comment by iam-py-test** [comment] 2023-08-14 21:02
What about `;`? It isn't valid in a cookie name, and can be used to set cookie attributes. Maybe not dangerous as I think most of those attributes can already be set

**Comment by stephenhawk8054** [comment] 2023-08-15 09:31
I think this is another case. `Adguard - Popup Overlays` list has this filter to deal with the popup on `medium.com`: https://github.com/AdguardTeam/AdguardFilters/commit/49bcd13c2c87c1da88170a3212a64810ac95e945

```adb
medium.com##+js(trusted-set-local-storage-item, 'lo-non-moc-membership-upsell|dismissed-at', $now$)
```

However, as a trusted scriptlet, this won't appear in uBO's version.

**Comment by krystian3w** [comment] 2023-08-18 11:41
IMO fine is:

```adb
dlalakierni.pl###RodoCookiesInfo:remove()
```

If nobody can document breakges.

**Comment by gorhill** [comment] 2024-04-14 23:49
Fixed with <https://github.com/gorhill/uBlock/commit/11a48561e0987419a54da2c9fd6ebd7ff202a3fe>

**Closed by gorhill** 2024-04-14 23:49 UTC
Labels: enhancement
