### ISSUE TITLE
Add an option to risk breaking pages instead of applying a whitelist

### ISSUE THREAD

**Issue by Noir-** [uBlockOrigin/uBlock-issues#317] opened 2018-11-27 12:18 UTC
### Prerequisites (Only applicable things left)

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Most lists implement a whitelist for certain sites to maintain its full functionality. This is especially the case for tracking protection. This is a good idea for many users who just want to have a working solution and this helps bringing ad-blocking to the masses. However, more privacy aware users might want to decide for themselves whether it is appropriate to allow tracking for certain sites. It could be possible that the broken features aren't needed or that the user decides to avoid the entire page instead of getting tracked.

### A specific URL where the issue occurs

Not applicable.

### Steps to Reproduce

Not applicable.

### Expected behavior:

When configured, uBlock warns me that the current site might not work as expected because there's a whitelist filter for it in place which is not enabled. If I wish, I could temporarily or permanently enable this whitelist item with an provided option. Ideally there's information in place about the content of whitelist filter so that the user can make an informed decision.

### Actual behavior:

uBlock just applies the rules in the lists. Users must rely on that lists as long as they don't look into them.

### Your environment

Not applicable.

**Comment by uBlock-user** [comment] 2018-11-27 12:20
Duplicate of https://github.com/gorhill/uBlock/issues/3353

**Closed by uBlock-user** 2018-11-27 12:20 UTC
