### ISSUE TITLE
Chrome still leaks WebRTC

### ISSUE THREAD

**Issue by re1oaded** [uBlockOrigin/uBlock-issues#1685] opened 2021-08-13 15:08 UTC
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Chrome uses [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega) global PROXY mode.

uBlockOrigin "Prevent WebRTC from leaking local IP addresses" is turned on.

`https://browserleaks.com/webrtc`

`https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/`

IP still leaked.

### A specific URL where the issue occurs

`https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/`

### Steps to Reproduce

1. Chrome uses [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega) global PROXY mode.
2. uBlockOrigin "Prevent WebRTC from leaking local IP addresses" is turned on.
3. Open `https://browserleaks.com/webrtc` or `https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/`

### Expected behavior

IP is not leaked

### Actual behavior

IP still leaked

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Chrome 92.0.4515.131

### Operating System and version

macOS Catalina 10.15.7

**Comment by uBlock-user** [comment] 2021-08-13 20:02
> IP still leaked

Settings only hides local IP address, not your ISP's IP address, see - https://github.com/gorhill/uBlock/wiki/Prevent-WebRTC-from-leaking-local-IP-address

**Comment by gorhill** [comment] 2021-08-13 20:15
Duplicate of <https://github.com/gorhill/uBlock/issues/2853>.

The setting won't work when you proxy through another extension.

**Closed by gorhill** 2021-08-13 20:15 UTC
Labels: unable to reproduce
