### ISSUE TITLE
Extreme popup blocking - uBo dashboard is blocked when popups are

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uBlock-issues#1616] opened 2021-06-07 20:15 UTC
### Prerequisites

- [X] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues) (This occurs when disabling all filters in a new browser profile)
    
- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser (That is not possible - uBo is clearly blocking it - it even admits it)
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [X] uBO is the only extension
    - [X] uBO with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior (why would this be a feature?)

### Description

uBlock Origin prevents me from opening links in another extension's popup, or from opening its own dashboard. 

### A specific URL where the issue occurs
`https://www.mywot.com/scorecard/65f7a0cc580d40e0-8d49da6c671bcf86.xyz`

### Steps to Reproduce
1. Go to the MyWot url & block popups via the uBo popup
2. Right click on the dashboard icon and try to open it in another window via the context menu
3. Note that it fails
uBo also blocks links from other extensions popups in the same way. 
### Expected behavior:

The dashboard opens

### Actual behavior:

It is blocked as if it was from mywot.com

### Your environment

* uBlock Origin version: uBlock Origin v1.35.2
* Browser Name and version: Firefox 89.0 (64-bit)
* Operating System and version: WindowsOS 10 21H1

**Comment by gwarser** [comment] 2021-06-09 11:50
I'm afraid this is actually "by design" plus some api limitations. It works better in Firefox than in Chrome where some popups are *not* blocked.

>Caveat: It's not always possible for uBlock Origin to determine for sure whether a new tab being opened is that of a popup, or is the result of a legitimate click on a link by the user. So if the no-popups switch is in use, you may not be able to open a link in a new tab through the context menu.

https://github.com/uBlockOrigin/uBlock-issues/wiki/Per-site-switches#no-popups

**Comment by iam-py-test** [comment] 2021-06-09 11:51
> I'm afraid this is actually "by design" plus some api limitations. It works better in Firefox than in Chrome where some popups are _not_ blocked.
> 
> > Caveat: It's not always possible for uBlock Origin to determine for sure whether a new tab being opened is that of a popup, or is the result of a legitimate click on a link by the user. So if the no-popups switch is in use, you may not be able to open a link in a new tab through the context menu.
> 
> https://github.com/uBlockOrigin/uBlock-issues/wiki/Per-site-switches#no-popups

Ok. Should this be closed as can’tfix?

**Comment by iam-py-test** [comment] 2021-06-09 11:54
Maybe update the Docs with a warning not to use uBo for blocking PopUps & open the dashboard in another window

**Comment by iam-py-test** [comment] 2021-06-09 11:55
Someone could open a Firefox bug to get the API extended for cases like this

**Comment by uBlock-user** [comment] 2021-06-09 12:14
> with a warning not to use uBo for blocking PopUps

No, this only happens with `no-popups` switch, uBO is fully capable of blocking popups withthut blocking dashboard with scriptlets.

**Comment by uBlock-user** [comment] 2021-06-09 12:17
> with a warning not to use uBo for blocking PopUps

No, this only happens with `no-popups` switch, uBO is fully capable of blocking popups withthut blocking dashboard with scriptlets.

The caveat explains the false positives bit clearly. So if one decides to use `no-popups` switch, one also needs to prepare himself for whatever breakage that come with it.

**Comment by iam-py-test** [comment] 2021-06-09 12:45
> > with a warning not to use uBo for blocking PopUps
> 
> No, this only happens with `no-popups` switch, uBO is fully capable of blocking popups without blocking dashboard with scriptlets.
> 
> The caveat explains the false positives bit clearly. So if one decides to use `no-popups` switch, one also needs to prepare himself for whatever breakage that come with it.

 I just meant that new users should be aware that the `no-popups` switch is a bit buggy (due to browser limits). 
Sorry; that could have been worded better

**Comment by gorhill** [comment] 2021-06-09 13:22
> Maybe update the Docs

There is already a ["Caveat" paragraph](https://github.com/uBlockOrigin/uBlock-issues/wiki/Per-site-switches#no-popups) explaining potential false positives:

> **Caveat:** It's not always possible for uBlock Origin to determine for sure whether a new tab being opened is that of a popup, or is the result of a legitimate click on a link by the user. So if the no-popups switch is in use, you may not be able to open a link in a new tab through the context menu.

**Comment by iam-py-test** [comment] 2021-06-09 13:24
> > Maybe update the Docs
> 
> There is already a ["Caveat" paragraph](https://github.com/uBlockOrigin/uBlock-issues/wiki/Per-site-switches#no-popups) explaining potential false positives:
> 
> > **Caveat:** It's not always possible for uBlock Origin to determine for sure whether a new tab being opened is that of a popup, or is the result of a legitimate click on a link by the user. So if the no-popups switch is in use, you may not be able to open a link in a new tab through the context menu.

I understand; I must have forgotten that.
Should I close this issue?

**Comment by gorhill** [comment] 2021-06-09 13:31
I haven't had the time to repro the steps yet, I want to confirm for myself that there is really nothing which can be done before closing.

**Comment by gorhill** [comment] 2021-06-09 13:39
I don't understand the repro steps. I installed MyWOT, and toggled no-popups switch for both `mywot.com` and `example.com`, and when I click "View full scorecard" in the popup panel of MyWOT, a new tab is opened and is not automatically closed by uBO.

**Comment by iam-py-test** [comment] 2021-06-09 13:41
> I don't understand the repro steps. I installed MyWOT, and toggled no-popups switch for both `mywot.com` and `example.com`, and when I click "View full scorecard" in the popup panel of MyWOT, a new tab is opened and is not automatically closed by uBO.

You don't have to install MyWOT (The website is just an example); just open the uBo popup, right click on the link to the dashboard, and click `Open in new window`:
![image](https://user-images.githubusercontent.com/84232764/121365673-d9714d00-c906-11eb-81a1-ee74a731c04e.png)

**Comment by gorhill** [comment] 2021-06-09 15:42
Ok I understand now. Well, the dashboard opens fine if you just click on the icon, right-clicking isn't necessary. What is the other extension with which you had an issue?

This is the logger output:

![d](https://user-images.githubusercontent.com/585534/121385948-97043c00-c917-11eb-95e5-0a9b5a24ccb7.png)

So clearly I think uBO should bail out of blocking popups when the destination is an extension URL.

**Comment by gorhill** [comment] 2021-06-24 12:40
> What is the other extension with which you had an issue?

**Comment by iam-py-test** [comment] 2021-06-24 12:53
> 
> 
> > What is the other extension with which you had an issue?

The original one was a custom extension I made ([here](https://github.com/iam-py-test/check-site)), but I also had issues with my antivirus.
However, I don't know how uBo can detect them as the urls are all non-extention (http/https) urls.

**Comment by gorhill** [comment] 2021-06-24 13:06
What I am trying to assess is why would someone use the contextual menu to open a link in a popup panel. There is no reason to do so in uBO, so I want to see actual cases (which does not require me to create an extension from a GitHub repo) where this is really an issue.

**Comment by iam-py-test** [comment] 2021-06-24 13:07
> 
> 
> What I am trying to assess is why would someone use the contextual menu to open a link in a popup panel. There is no reason to do so in uBO, so I want to see actual cases (which does not require me to create an extension from a GitHub repo) where this is really an issue.

I am sorry, but I don't really have a use case.
I guess there is no need to investigate this unless one arises. 
Sorry for wasting your time

**Comment by gorhill** [comment] 2021-06-24 13:16
I sis fix it on my side, but I wish there was an actual case supporting that the fix was worth the time spent on it.

**Closed** 2021-06-25 11:02 UTC
Labels: fixed, something to address
